### ISSUE TITLE
The return value of block() is not considered safe

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#1000]
the following code will escape the content of the block:

``` jinja
{% set nav = block('heading_navigation') %}
{% if nav is not empty %}
    <nav>{{ nav }}</nav>
{% endif %}
```

Wouldn't it be better to return a `Twig_Markup` instance in `block()` ?

**Comment by fabpot** [comment]
I've thought about this one and I think we can close it as a "won't fix".

Even your example would break as `nav is empty` would return `false`.
