### ISSUE TITLE
Acessing globally imported macro in another macro fails with PHP fatal error

### ISSUE THREAD

**Issue by dmzkrsk** [twigphp/Twig#1052]
**Twig 1.12.3 (2013-04-08)**

Assume we have this template:

``` twig
{% import "macros/clipart.twig" as clm %}

{% macro show(something) %}
    {{ unknown_variable.moody }}
    {{ clm.moody }}
{% endmacro %}
```

The docs say, that macros have no access to global scope. That's fine. But they still track imported macroses!

Line `{{ unknown_variable.moody }}` runs without errors producing an empty strings (with strict variables disabled)

The other line `{{ clm.moody }}` fails with fatal error **Call to a member function getmoody() on a non-object**

As far as I could dig into the sources, I found that in _ExperssionParser.php:368_ uses `$this->parser->getImportedSymbol` to look for `clm` variable, that uses `Parser::importedSymbols` which is global. But `clm` isn't included in the `$context` of the generated template method. And `strict_variables` don't help here.

And in generated template method we have `echo $_clm_->moody();` (and `$_clm_` is `null` since it doesn't exists in `$context`) with no sanity checks.

Solutions:
- make imported modules visible within macros context (against the docs)
- don't recognize them as modules within macros (according to the docs)

**Comment by stof** [comment]
@fabpot the parser should be taught that the body of a macro tag is always isolated in scope, and so should have its own set of imported symbols, due to the way macros are implemented currently

**Comment by fabpot** [comment]
#3009 fixed the error message to get "Variable "clm" does not exist..." like any other variable.
#3012 makes the code valid.
