### ISSUE TITLE
Support for hooks

### ISSUE THREAD

**Issue by Stelian** [twigphp/Twig#1065]
Hello guys,

I've been looking around for a couple of days and I couldn't find anything related to supporting hooks when it comes to variables manipulation, as in allow a variable to have conditional outputs:

{{ test }} could output "<span class="class">12</span>"
{{ test | number_format }} could output 12.00

I am aware of being able to strip tags, adding an extra filter, etc but I am looking for something that would be built in, adding a little bit more flexibility to twig when you want to use it as a templating engine in let's say a blogging platform. 

This could easily be achieved with either pre / post hook or by passing an object of a given interface type, that would know how to handle such morphing behavior.

I have clear uses cases for such a functionality so I would implement it, not sure about the general perception though.

**Comment by dupuchba** [comment]
@stof in the same way I have a use case where I want to be able to list all `*.twig`that have been called from a certain template (e.g: a template extends one default.html.twig and import three other templates, I want to be able to list the 5 files).
I am not sure if a node visitor would be the best way to do it. 
But from my understanding, I have to be able to catch `Twig_Token::BLOCK_START_TYPE` with import/extends/include value during the tokenize phase. 
Can someone help me with this one :-) ? (ping @fabpot )

**Comment by stof** [comment]
@dupuchba you can use the Twig profiler available in latest versions. It already does it during the rendering.

A node visitor could also allow to extract this info at compile time, but only for static template names, not for dynamic names. And it forces you to know all the function and tags involving a separate template, which is hard to maintain (any extension can add new ones, and new twig versions as well). Getting it when actually rendering the template (thanks to the profiler) is much easier if it is enough for your use case

**Comment by stof** [comment]
anyway, you should probably not discuss this on a different issue closed 1 year ago
