### ISSUE TITLE
Can I use extends inside `template_from_string`

### ISSUE THREAD

**Issue by makasim** [twigphp/Twig#1134]
I would like to render such template

```
{% extends 'CoreBundle::layout-static.html.twig' %} 

{% block content %}
  Some content
{% endblock %}
```

with `template_from_string` function. I am doing it like this:

```
{{ include(template_from_string(page.template.body)) }}
```

It render next:

```
CoreBundle::layout-static.html.haml
```

Where I expect `Some content`.

**Comment by apollonin** [comment]
@kalenjordan you should use Twig_Loader_Filesystem instead of Twig_Loader_String, and than write something like this:
```
$twig->render('test.html.twig', [
				'template' => $templateContents
			]);
```
where 
test.html.twig is
```
{% include template_from_string(template) %}
```

**Comment by kalenjordan** [comment]
@apollonin awesome thanks!
