### ISSUE TITLE
Named arguments in macros does not work with template inheritance

### ISSUE THREAD

**Issue by hason** [twigphp/Twig#1157]
When I use a macro from a file which not directly import the macro file, I get the message _Uncaught exception 'Twig_Error_Syntax' with message 'Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",") in "child.twig"._

Original report: https://github.com/hason/Twig/commit/9691580aed23da9920cf98db2d1919977124a4cb#commitcomment-3769291

To reproduce the bug :

``` jinja
{# macros.twig #}
{% macro hello(name, age, lang="fr") %} 
{% endmacro %}
```

This works:

``` jinja
{# parent.twig #}
{% import "macros.twig" as macros %}
{{ macros.hello(name="Gilles", lang="en") }}
{% block content %}{% endblock %}
```

This doesn't work until I re-import the macro file. But it works without named args:

``` jinja
{# child.twig #}
{% extends "parent.twig" %}
{% block content %}
    {{ macros.hello(name="John", lang="en") }}
{% endblock %}
```

**Comment by fabpot** [comment]
Closing this one as it was related to an implementation that was reverted (#929).
