### ISSUE TITLE
Add {% call %} tag

### ISSUE THREAD

**Issue by hason** [twigphp/Twig#1175]
see http://jinja.pocoo.org/docs/templates/#call

``` twig
{% macro render_dialog(title, class='dialog') -%}
    <div class="{{ class }}">
        <h2>{{ title }}</h2>
        <div class="contents">
            {{ caller() }}
        </div>
    </div>
{%- endmacro %}

{% call render_dialog('Hello World') %}
    This is a simple dialog rendered by using a macro and
    a call block.
{% endcall %}
```

**Comment by HeahDude** [comment]
I agree with Fabien, `caller()` doesn't sound that friendly.

May I ask what's the real benefit compared to:
```twig
{% macro render_dialog(title, content, class='dialog') -%}
    <div class="{{ class }}">
        <h2>{{ title }}</h2>
        <div class="contents">
            {{ content }}
        </div>
    </div>
{%- endmacro %}

{% set content %}
    This is a simple dialog content rendered by using a macro.
{% endset %}

{{ macro.render_dialog('Hello World!', content) }}
```
?

**Comment by NakajimaTakuya** [comment]
I agree with the hason's opinion.
I really want this feature.

Without `yield`, macros will have more arguments in the future just for a little if statement.

```jinja
{% macro xxx(hasX, hasY) %}
<div>
  <any_contents>
    {% if hasX %}
       ..
    {% elseif hasY %}
       ..
    {% else %}
       ..
    {% endif %}
  </any_contents>
</div>
{% endmacro %}
```

In fact, I've seen macros with more than 10 arguments.

I can also understand the suggestion to use `embed`.
However, the interface of `embed` is unclear when looking at the file alone.

I don't want to use templates with obscure interfaces other than root templates.
I think it is not suitable for long-term maintenance.

I can also understand the suggestions for using `set`.
However, this lacks the expressive power of the parent-child relationship of the code.

So I want `yield` in `macro`.
