### ISSUE TITLE
Typed views

### ISSUE THREAD

**Issue by webberig** [twigphp/Twig#1199]
I've been doing some work in a more complex project where views use a lot of inheritance (include, extend, use block, ...). One of the challenges is knowing which variables you must pass on and which variables are available to you in the view. 
- When creating an include, I need to open the given view to check which variables are needed. If necessary, I add "with" to create variable aliases.
- When creating a view, I need to check the parent view or the controller to see which variables have been passed and which name they have been given.

Good naming conventions are definately a huge step forward resolving this, but having experience with ASP.NET MVC 3 and the Razor template engine, I kind of miss one of its features: (strongly) typed views.

Would it be possible to add a "strict mode" with proper syntax to declare variables at the top of each view ? Maybe it can be similar to phpdoc syntax.
The Twig engine could then throw exceptions when a controller or parent view passes the wrong variables, or lacks certain variables ?

IDE's that already support twig syntax can go further by using those definitions for their autocomplete feature.

An example:

``` twig
{% var name, address Entity\Address, website string %}
...
```

**Comment by hason** [comment]
Symfony2 Plugin supports PHP types in comments http://symfony2-plugin.espend.de/languages/twig/index.html#phptypes

**Comment by webberig** [comment]
@hason,
Thx for the tip. It's strange that this feature is part of the symfony2 plugin, and not the Twig plugin.
That's not very helpful if you're using Twig in non-Symfony projects...

**Comment by stof** [comment]
@webberig the Twig plugin is part of the PhpStorm core. This feature has been added by the dev of the Symfony2 plugin, and he has not created a separate plugin with just the Twig features (especially given that many other Twig features he added are specific to the Symfony integration)

**Comment by webberig** [comment]
I do appreciate the dev's intention and work that is done in the Symfony2 plugin, I like using it in my Symfony projects. But the fact remains that I can't use the feature @hason suggested in non-Symfony projects.

Btw, this discussion is offtopic, the op is about implementing strongly-typed views, not about phpStorm...

**Comment by stof** [comment]
@webberig just enable the Symfony2 plugin and this feature will work even if nothing else will benefit from the plugin

**Comment by fabpot** [comment]
I'm closing this issue as it's almost impossible to implement. Twig is too dynamic to make it worth.
