### ISSUE TITLE
Magical and incorrect macro call

### ISSUE THREAD

**Issue by hason** [twigphp/Twig#1217]
Let us have templates:

``` jinja
{# index.twig #}
{% extends "parent.twig" %}

{% block content %}
{{ macros.hello("Jack") }}
{% endblock %}

{# parent.twig #}
{% macro hello(name) %}
{% endmacro %}

{% import _self as macros %}

{% block content "" %}
```

The `{{ macros.hello("Jack") }}` line in the template `index.html` is compiled to:

``` php
$this->getAttribute($this->getContext($context, 'macros'), 'hello', ...)
```

Properly, we should find out what is the variable `macros` and call the macro `hello` normally.

**Comment by stof** [comment]
IMO, the issue is that we let this work in the first place. and this is because ``import`` is changing the context.

**Comment by fabpot** [comment]
As of Twig 1.28, this code generates a deprecation and this code is not supported anymore in Twig 2.0.
