### ISSUE TITLE
Allow access to context as it was before merging with globals

### ISSUE THREAD

**Issue by therealmikz** [twigphp/Twig#1298]
In Twig_Template class, method display there is mergeGlobals call that merges data returned from f. ex. controller with other global variables.
I wanted to render all data returned from controller as json and I found it impossible  because I could not filter out those globals in template. It would be really nice to have access to the context that isn't merged with global variables in that situation.

**Comment by fabpot** [comment]
As the context is passed by the application to Twig, the application already has access to it.
