### ISSUE TITLE
JavaScript string escaping

### ISSUE THREAD

**Issue by dunglas** [twigphp/Twig#1316]
Is there a way to escape JavaScript string? I've found no way to do that.

Use case:

``` html
<script>
var myString = "{{ myVar|e('js_str_or_someting_like_that') }}";
var obj = JSON.parse("{{ obj|json_encode()|e('js_str_or_someting_like_that') }}");
</script>
```

Expected output:

``` html
<script>
var myString = 'The \'content\' of "my var"';
var obj = JSON.parse("{ foo: \"bar\" }");
</script>
```

If there is no way to do that, is a contribution to add support of JavaScript string context to the escaping feature welcomed?

**Comment by teohhanhui** [comment]
@dunglas It's safe, unless `JSON_UNESCAPED_SLASHES` is used.
