### ISSUE TITLE
Should html safe methods work in ternary if-conditions?

### ISSUE THREAD

**Issue by nifr** [twigphp/Twig#1320]
Imagine i have the html-safe twig function `icon()` ( i.e. [the one  provided by BCBoostrapBundle](https://github.com/braincrafted/bootstrap-bundle/blob/develop/Twig/BootstrapIconExtension.php#L48) ). 

Then i would expect the following to work out of the box:

```
{{ article.description ?: icon('minus') }}     -> output is being escaped :(
```

It looks like you currently have to use this (ugly) workaround:

```
{{ ( article.description ?: icon('minus') )|raw }}    -> works but ugly :(
```

Am i missing something (i.e. some `autoescape` setting ) or should we probably fix this ?

**Comment by fabpot** [comment]
Will finally be fixed by #2934
