### ISSUE TITLE
Feature Request: One-line style comment

### ISSUE THREAD

**Issue by c33s** [twigphp/Twig#1331]
it would be really awesome, having a equivalent to the [php one-line style comments](http://www.php.net/manual/en/language.basic-syntax.comments.php) in twig.

they could look like that:

```
{%// The line to be commented out
```

or if the curls have to be closed, something like this:

```
{%//%} The line to be commented out
```

for faster tying it would be even more handy to use the double curly braces `{{//`but it would be inconsistent to the normal usage of the double braces.

**Comment by olets** [comment]
+1

Many languages have inline comments, which people use for all sorts of reasons - for example, as @c33s says, when commenting out something that includes documentation comments or commented out code.

It's a user experience difference: the difference is going back and forth between these
```
line 1
line 2 {# comment 1 #}
line 3 {# comment 2 #}
```
and 
```
{#
line 1
line 2 {# comment 1
line 3 // comment 2
#}
```
, and going back and forth between these, which in most editors can be done with a single keyboard shortcut
```
line 1
line 2 {/ comment 1
line 3 {/ comment 2
```
and 
```
{#
line 1
line 2 {/ comment 1
line 3 {/ comment 2
#}
```
