### ISSUE TITLE
Use template $file and $line in Twig_Error

### ISSUE THREAD

**Issue by barryvdh** [twigphp/Twig#1347]
Is there a reason Twig_Errror uses $filename and $lineno instead of $file and $line, which are used by the base Exception?
Wouldn't it be possible to set the Twig_Error line/file, so the backtrace can be shown by error handlers?
For example, Whoops shows the file/line, and a part of the file. For Twig, this isn't really useful, because it points to Twig_Template for example, but I guess you would rather see the template source..
I also created an issue for Whoops (https://github.com/filp/whoops/issues/167), but changing Twig (if possible) would probably be better, as it would work just like any other exception.

Some quick testing made it work fine in Whoops, the only problem was that the getTemplateName() function doesn't return the full path, but just the name. So it would have to be converted to the real path.

**Comment by chetzof** [comment]
@barryvdh Hey! Have you made any progress on this issue since then?

**Comment by barryvdh** [comment]
Yeah I just implemented that in the Laravel loader, to catch the Exceptions that occur. And extended the loader to find the files:
https://github.com/rcrowe/TwigBridge/blob/master/src/Engine/Twig.php

Works pretty good, didn't have any issues yet.

But there doesn't seem to be a real interest in this in the core..

**Comment by barryvdh** [comment]
Ah, it seems this will be implemented with https://github.com/twigphp/Twig/pull/2273
Closing this issue in favor of that PR

**Comment by fabpot** [comment]
@barryvdh I think this is not related. The other PR is "just" about exposing the original file name when available in the exception.

**Comment by barryvdh** [comment]
Yes but also the $file and $line properties, when the path is given, which should be most cases, right?

```php
protected function updateRepr()
    {
        $this->message = $this->rawMessage;
        if ($this->path && $this->lineno > 0) {
            $this->file = $this->path;
            $this->line = $this->lineno;
            return;
        }
 ...
```
