### ISSUE TITLE
% operator returns the integer result

### ISSUE THREAD

**Issue by Virakal** [twigphp/Twig#1353]
Apologies if this has already been mentioned - I wasn't sure exactly what to search for.

Currently, `{{ 1.5 % 1 }}` will display 0 instead of 0.5 because it is a straight proxy for PHP's `%` operator instead of `fmod`.

This might be expected behaviour for a PHP developer but I personally believe that the majority of template designers would expect the latter.

This issue also affects `divisibleby`, more noticeably, with `{{ 1.5 is divisibleby(1) ? 'true' : 'false' }}` displaying true instead of the expected false.

It also makes things act strangely when the operands exceed the maximum integer size, though I'd imagine that's pretty rare.

**Comment by fabpot** [comment]
Closing here as discussion is happening on #1440
