### ISSUE TITLE
Bug in whitespace removal

### ISSUE THREAD

**Issue by Zakay** [twigphp/Twig#1358]
Twig removes newlines that shouldn't be removed.

```
To: {% if order.use_delivery_address_for_billing %}{{ order.delivery.first_name }} {{ order.delivery.last_name }} <{{ order.delivery.email }}>{% else %}{{ order.billing.first_name }} {{ order.billing.last_name }} <{{ order.billing.email }}>{% endif %}
From: Store name <orders@store.com.au>
```

Results to

```
To: Customer Name <customer@name.com>From: Store name <orders@store.com.au>
```

Latest twig used.

**Comment by fabpot** [comment]
Closing as changing the current behavior would (unfortunately) be a big BC break.
The newline removal comes from PHP which does the same; that makes more or less sense for HTML templates but indeed, as soon as you are using Twig with another format, it's indeed a poor behavior.
