### ISSUE TITLE
{{ -3 }} vs {{ (-3) }}

### ISSUE THREAD

**Issue by inalgnu** [twigphp/Twig#1368]
Hello, 
I don't know if it is expected to be like this, but why is 3 interpreted as an expression in this case {{ -3 }} ?  different from {{ (-3) }}

**Comment by fabpot** [comment]
I'm closing this one as I've look at this again, and the BC break would introduce subtle bug, not necessarily with `-` or `+`, but probably more with the other built-in unary operator `not`.

**Comment by SpacePossum** [comment]
:(

**Comment by fabpot** [comment]
Fixed in #4543
