### ISSUE TITLE
Access to object's property with NULL value throws an Exception

### ISSUE THREAD

**Issue by Igreh** [twigphp/Twig#1385]
Such issue I faced during working with Yii ActiveRecord object and Twig

Assuming we have a class like this:

``` php
class c {
    public $vars = array();

    public function __construct() {
        $this->vars['a'] = 'value';
        $this->vars['b'] = null;
    }

    public function __call($name, $parameters) {
        if (true/*method's existance check here*/) {
            throw new Exception('There\'s no such method!!!');
        }
    }

    public function __get($name) {
        return $this->vars[$name];
    }

    public function __isset($name) {
        return isset($this->vars[$name]);
    }
}
```

We can access 'a' and 'b' properties:

``` php
$c = new c;
var_dump($c->a, $c->b);
```

it prints:

```
string 'value' (length=5)
null
```

everything works as expected, but if we try to access these properties from twig template:

``` twig
{{ c.a }}
{{ c.b }}
```

we'll get an exception "'There's no such method!!!'" for {{c.b}} because isset($c->b) === false and $c->b() method doesn't exist.

**Comment by ihatehandles** [comment]
Not to start a concluded discussion 2 years on. But is there any 2016 resolve for this?
