### ISSUE TITLE
Twig Cache WarmUp (compileSource) Optimization

### ISSUE THREAD

**Issue by DimaSoroka** [twigphp/Twig#1387]
In scope of our project we have a lot of templates (~500 and growing). Some templates are simple and some are very complex. Currently twig templates cache wamup takes ~13 seconds on very powerful machine with SSD and this is growing. 
I just wanted to check if there any optimization is planed for templates cache generation  or maybe we should take into account some tips that will help to make this process faster.

Here is an [example](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/UIBundle/Resources/views/macros.html.twig) of the template that requires ~0.2 second to generate the cache.

**Comment by fabpot** [comment]
I've once again tried to see what could be optimized by taking the ORO templates as an example, but there is nothing obvious to me. So, closing for now.
