### ISSUE TITLE
Move output escaping into it's own repo.

### ISSUE THREAD

**Issue by yjv** [twigphp/Twig#1408]
This functionality would be useful in other projects that want to do output but may not need the full templating functionality. 

This is to move the escaping function to its own repo. not to make a class out of it as that would introduce new overhead to a function that is called many many times. Therefore since it cant be autoloaded there will need to be a different solutions to include it. A non composer environment will need to be considered as well.

possibly a git subtree.

**Comment by Koc** [comment]
https://wiki.php.net/rfc/escaper

**Comment by GromNaN** [comment]
You can use Zend Escaper.
http://framework.zend.com/manual/current/en/modules/zend.escaper.introduction.html

**Comment by yjv** [comment]
@Koc interesting. I wonder if anyone is still involved in this rfc. Sound like it may be fun to write :)

@GromNaN good idea thanks!

**Comment by fabpot** [comment]
I'm closing this feature request. It never happened and as performance is critical for this part of Twig, I prefer to keep the code optimized for our use case.

**Comment by stof** [comment]
For anyone needing this, use zend-escaper. they have the same 5 escapers than Twig core
