### ISSUE TITLE
Parse error: failed at `content: '· ';`

### ISSUE THREAD

**Issue by shkarupa-alex** [twigphp/Twig#1428]
This issue found in Piwik open source web analytics (http://piwik.org).
Piwik use Twig to render it's template. I tried to submit issue to Piwik but they said 
> We use latest Twig http://dev.piwik.org/trac/ticket/5338

So, when i trying to install piwik it fails with error:
> An exception has been thrown during the rendering of a template ("parse error: failed at `content: '· ';` line: 3682") in "@Installation/layout.twig" at line 40.

Error throws only when i put 
```mbstring.func_overload 2 ```
in .htaccess.

I found closed issues like https://github.com/fabpot/Twig/issues/32 or https://github.com/fabpot/Twig/issues/731 but Piwik uses latest Twig release.

So, i'd like to determine where this error throws, but have no ideas how.
Even if i remove all code from layout.twig error throws, but with such text:
> parse error: failed at `content: '· ';` line: 3682

Please somebody help me to determine where is "line: 3682" (what file?) and how to debug this error.

**Comment by fabpot** [comment]
Closing as there is no feedback from the reporter.

**Comment by Tobion** [comment]
One must not activate function overloading. It's also in the requirements of symfony.
