### ISSUE TITLE
Implement repeatable blocks

### ISSUE THREAD

**Issue by curry684** [twigphp/Twig#1478]
While the extend functionality with blocks works a charm for many cases, I also frequently find myself building templates for apps that have repeated blocks. Practical use case: a tabbed dialog. Right now I would do something like:

```
{% extends 'master-dialog.twig' %}
{% block content %}
<div class="tabbar">
  <div class="tab" data-title="Tab 1"><!-- first tab --></div>
  <div class="tab" data-title="Tab 2"><!-- second tab --></div>
  <div class="tab" data-title="Tab 3"><!-- third tab --></div>
</div>
{% endblock %}
```

While this works fine of course it semi-defeats the purpose of inheritance, since it still means a lot of copy/paste code remains in the derived template. What I would like instead:

```
{% extends 'master-tabbeddialog.twig' %}
{% block tab with {title:'Tab 1'} %}
  <!-- first tab -->
{% endblock %}
{% block tab with {title:'Tab 2', default:true} %}
  <!-- second tab -->
{% endblock %}
{% block tab with {title:'Tab 3'} %}
  <!-- third tab -->
{% endblock %}
```

(`with` syntax shamelessly borrowed from [#1278](https://github.com/fabpot/Twig/issues/1278))

In the base template this could be implemented as:

```
{% extends 'master-dialog.twig' %}
{% block content %}
<div class="tabbar">
{% forblock tab %}
  <div class="tab"{% if default %} data-default="1"{% endif %} data-title="{{ title:default('Unnamed') }}">{{ content() }}</div>
{% endforblock %}
</div>
{% endblock %}
```

The end result is a complete separation of concerns and as such better maintainable templates. The practical use case could also apply to repeated page sections, paged wizards and the like.

**Comment by parijke** [comment]
Somebody knows a working well designed implemented use case of extends and embed?
