### ISSUE TITLE
type string - Twig_Markup - Maybe a bug?

### ISSUE THREAD

**Issue by kpietru** [twigphp/Twig#1480]
Hi,

Example problem:

Error:

{% set some_var %}
Hello
{% endset %}
{{ myclass.method(some_var) }}

The variable "some_var" for my class must be a string.
My class throws an error because "some_var" is the object "Twig_Markup".

OK:

{{ class.method('Hello') }}
Now "Hello" is a string.

Is it logical? Maybe a bug?

**Comment by fabpot** [comment]
When you set a var in a template, Twig might wrap it with a Twig_Markup instance to be able to manage escaping properly. As @waitxd said, you can cast them to a string if needed.
