### ISSUE TITLE
Limit include to specific paths in sandbox

### ISSUE THREAD

**Issue by standaniels** [twigphp/Twig#1505]
Wouldn't it be nice to be able to limit `` {% include %}`` to access only a certain path within a sandboxed template? I have some untrusted templates which I run in a sandbox, but those templates are still able to include templates outside their sandbox.

Or is it better to use a separate environment for this? What do you think?

**Comment by fabpot** [comment]
The `include` tag/function or any other tag/function that takes a template name as an argument (like `extends` for instance) uses the current loader to load the template. But a loader is not tied to the filesystem, so restricting the paths in the sandbox is not really possible. Instead, you should indeed create a specific environment with a specific loader.
