### ISSUE TITLE
Render Strings

### ISSUE THREAD

**Issue by peterrehm** [twigphp/Twig#1506]
In addition to rendering strings from an variable within a template as added within #874 
I see the use case of rendering a string e.g. in the Servicelayer to e.g. Prepopulate Entites
or whatever.

This can currently be achieved with several ways which all have some drawbacks:

- Adding the String Loader
````
    acme.demo.twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }
````

This has the drawback that all invalid templates will be rendered as strings. If you have an exception in the template or the template does not exist you will just see the rendered template name. 

- Adding a StringTwigService

````
services:
    acme.twig_string_loader:
        class:        "Twig_Loader_String"
    acme.twig_string:
        class:        "%twig.class%"
        arguments:    [@acme.twig_string_loader, %twig.options% ]
````

With this approach you have a separate string loader for the above mentioned purpose, however you do not have access to all your extensions. However for my use cases I usually go with Option (2).

I was just considering if a renderString() method in the Twig Core might make sense. When I was investigation those issues I saw a lot of comments how to render a string.

**Comment by fabpot** [comment]
Doing some cleaning today, I found an old branch doing pretty much what you are asking for. Have a look at #1602
