### ISSUE TITLE
Twig_Markup objects cannot be compared by some operators

### ISSUE THREAD

**Issue by jaytaph** [twigphp/Twig#1512]
When working with a Twig_Markup object, I can easily print this as it implements __toString().

```
{{ myvar }}
```

However, certain operators, like the "in" and "not in" which internally depend on the [twig_in_filter function](https://github.com/fabpot/Twig/blob/master/lib/Twig/Extension/Core.php#L893) , behave differently internally by checking the right operator against arrays or actual strings. This means Twig_Markup objects cannot be used with this operator:

```
{% if "foo" in myvar %}  
```

It's trivial to add some additional tests in the twig_in_filter function like [this one](https://github.com/fabpot/Twig/blob/master/lib/Twig/Extension/Core.php#L925), but more operators might be affected as well (like "starts with", and "ends with").

I'm not sure if this is the correct way, if so, i'm happy to create a PR with the additional string-cast.

**Comment by fabpot** [comment]
Indeed, `Twig_Markup` objects are annoying and the more support we can add, the better. I will try to see if doing that across the board is realistic or not, starting with the in test.

**Comment by fabpot** [comment]
fixed in #2952 for the in operator.

**Comment by fabpot** [comment]
I've decided to fix only the "in" operator as no so many people are having this issue (this is the only report in the last 5 years).
