### ISSUE TITLE
Proposal: option to hide or ignore Twig Exceptions

### ISSUE THREAD

**Issue by ohmance** [twigphp/Twig#1562]
First off, Twig is awesome.  Thanks for all you've done on it.

Assuming I have the template:
`This is my variable: {{myVar}}`

I can pass in this data when rending:
`['myVar' => 'pizza']`

The result should be:
`This is my variable: pizza`

The problem occurs when I pass in something like this:
`['myVar' => ['pizza1','pizza2','pizza3']]`

The result is an Array to string conversion exception, which is understandable.

TwigJS in this situation would print this, which is great:
`This is my variable: pizza1,pizza2,pizza3`

I propose an configuration setting that ignores errors such as this and prints nothing instead.  It would be nice if a print_r could be run in place of this variable, but even if it printed nothing I would be happy.  I'm hoping to utilize Twig over Handlebars in a email sending platform but it doesn't make sense to axe the entire preview of the email over one minor detail like this.  It'd be more desirable to just ignore the troubled variable and move on.

I do understand that this can be accomplished using a custom function/filter, but to me that defeats the purpose of why I want to use Twig in the first place.  Having to write {{valueOf(myVar)}} creates boilerplate and a disadvantage to those already familiar with Twig who are coming to use this platform.

**Comment by fabpot** [comment]
Closing this issue as this is something we will ad in ore Twig for reasons already mentioned, but also because having a way to configure such a thing would complexify Twig and support.
