### ISSUE TITLE
Fatal error when a function goes away

### ISSUE THREAD

**Issue by AndreKR** [twigphp/Twig#1563]
When I try to use a function in a template that is not defined, Twig throws a nice exception:
> Uncaught exception 'Twig_Error_Syntax' with message 'The function "undefined_function" does not exist in "test.html.twig" at line 9'

However, when I define this function (`$environment->addFunction(new Twig_SimpleFunction('undefined_function', function () {}));`) and use the template, it is compiled and cached.

Now when I try to use the same template again without the function being defined, instead of an exception I get a PHP fatal error:
> Fatal error: Call to a member function getCallable() on a non-object in N:\htdocs\test\compilation_cache\6c\2b\b57b5da9f747eb051e76b39fa30b2ca01363c64857828ccb8c8ae43de9b9.php on line 37

The line in question is:
`echo call_user_func_array($this->env->getFunction('undefined_function')->getCallable(), array());`

This is particularly bitter because PHP flushes to current output buffer when a fatal error happens:
```
echo 'before';
ob_start();
echo 'inside';
undefined_function();
ob_end_clean();
echo 'after';
```
outputs "`beforeinside`"

Any thoughts on this? Is it by design to save the performance impact of runtime checks? Could the environment become part of the cache key? Could `getFunction()` return a dummy object whose `getCallable()` method throws an exception? Would that change anything?

**Comment by fabpot** [comment]
Functions should always be defined. If not, it's up to you to wrap them so that such problems do not occur. Anyway, we cannot afford to check existence of functions at runtime.
