### ISSUE TITLE
Getters for virtual columns created with Propel not supported

### ISSUE THREAD

**Issue by standaniels** [twigphp/Twig#1577]
I use Propel in my projects and I found out the getter of virtual columns aren't supported.

For instance I create two virtual columns (``Month`` and ``Total``) with this query:

    $incomePerMonth = IncomeQuery::create()
        ->withColumn('MONTH(Income.Date)', 'Month')
        ->withColumn('SUM(Income.Amount)', 'Total')
        ->groupBy('Month')
        ->orderBy('Month')
        ->find();

And I can get them with PHP like this:

    foreach ($incomePerMonth as $month)
    {
        echo $month->getMonth() .': '. $month->getTotal() ."\n";
    }

You would think that this also works within Twig:

    {% for month in incomePerMonth %}
        <p>{{ month.month }}: {{ month.total }}</p>
    {% endfor %}

But then an exception is thrown: ``Call to undefined method: month.`` When I try to display only the ``total`` column I get a different error: ``The file "Unknown parser class "\Propel\Runtime\Parser\TalParser"" does not exist``. I have to do it this way in order to get the virtual columns:

    {% for month in incomePerMonth %}
        <p>{{ month.virtualcolumns.Month }}: {{ month.virtualcolumns.Total }}</p>
    {% endfor %}

**Comment by fabpot** [comment]
I know nothing about Propel, but this might be related to this: http://twig.sensiolabs.org/doc/recipes.html#using-dynamic-object-properties

**Comment by standaniels** [comment]
Yes, I think it might. I made me think again and look at the source could, I think it's the ``__call`` method that isn't called by Twig: https://github.com/propelorm/Propel/blob/master/runtime/lib/om/BaseObject.php#L439

**Comment by stof** [comment]
does your object also implement ``__get`` and ``__isset`` or no ?

**Comment by stof** [comment]
Can you try giving the name of the magic method itself: ``month.getMonth`` and ``month.getTotal`` ? Twig will also try calling the method without prepending ``get``, and Propel has a special handling for methods starting with ``to``. And it does not throw a BadMethodCallException when calling an undefined method, but its own exception, which is not catched by Twig to go to the next candidate

**Comment by standaniels** [comment]
Ok I understand it better now.

No, my object does not implement ``__get`` or ``__isset``. When I try the full method's full name (``month.getTotal``) it works. And now my object has implemented ``__get`` and ``__isset`` ``month.total`` works as well.

Thanks for coming back at this.

**Comment by stof** [comment]
yeah, the issue is related to the exception being thrown when ``__call`` does not support the method (and the fact that some of these names are matching a different magic method)
