### ISSUE TITLE
Deadlink in docs

### ISSUE THREAD

**Issue by marcel-burkhard** [twigphp/Twig#1586]
You find a link on **The Intl Extension** to edit the document if you **Found a typo or an error**.

http://twig.sensiolabs.org/doc/extensions/intl.html#localizeddate

That link points to: https://github.com/twigphp/Twig/edit/master/twig/extensions/doc/intl.rst

Which is github 404.

**Comment by nicolasdewez** [comment]
@marcel-burkhard : fixed ?

**Comment by marcel-burkhard** [comment]
Nope.

**Comment by nicolasdewez** [comment]
Oh ok i seen... Part "Twig extensions" moved on https://github.com/twigphp/Twig-extensions

**Comment by marcel-burkhard** [comment]
So..? It's still not fixed. And I don't know where to edit/fork the page because the link is dead.

**Comment by nicolasdewez** [comment]
Yes, i don't know... ping @stof ?

**Comment by stof** [comment]
Edit it in the Twig-extensions repo linked by @nicolasdewez above.

@fabpot can you fix the edit link for the extensions doc ?

**Comment by marcel-burkhard** [comment]
The link is still dead

**Comment by SpacePossum** [comment]
ping; ran into this same thing today ^-^
I think the link should be to:
https://github.com/twigphp/Twig-extensions/blob/master/doc/intl.rst

**Comment by fabpot** [comment]
Closing as Twig-extensions docs are not part of the website anymore.
