### ISSUE TITLE
[2.0] Remove the wrapping of exceptions when rendering Twig templates

### ISSUE THREAD

**Issue by fabpot** [twigphp/Twig#1587]
In Twig 1.x, all exceptions thrown during the rendering of a template are wrapped with a Twig exception. It looked like a good idea back then, but many people thinks it's wrong (see symfony/symfony#11755 for instance -- but we have many other ones).

The more I think about it, the more I think it was a mistake. So, I propose to remove this wrapping in Twig 2.

What do you think?

**Comment by fabpot** [comment]
hmmm, this is a bad idea: The wrapping of the exception allows us to tell the developer where in the original template the error occurred. So, I'm actually :-1: about this :)

**Comment by lyrixx** [comment]
I'm :-1: too, because the `Twig_Error` has useful information in it (line, filename), then it allow us to catch only twig exception and not all exception.
