### ISSUE TITLE
How can I get the variable name in Twig_SimpleFilter?

### ISSUE THREAD

**Issue by LDSign** [twigphp/Twig#1588]
Hi

Is there a way to get the variable name in Twig_SimpleFilter?

Thanks,
Frank

**Comment by stof** [comment]
Which variable name are you talking about ?

**Comment by LDSign** [comment]
For example:

In template:

{{username|line}}

Custom filter:

$line_filter = new Twig_SimpleFilter('line', function ($string,$length = 20) {
    // Here I would like to get the variable name ("username" in the example above).
});

Thanks,
Frank

**Comment by stof** [comment]
You cannot get the variable name. You cannot be sure that the value being filtered comes from a variable. It can come from any valid Twig expression (output of a function, output of another filter, literal value, variable, output of an operator, ...)

**Comment by lyrixx** [comment]
the real question is: Why do you want the variable name?
in pure PHP, you never get the variable name...

**Comment by fabpot** [comment]
Closing as you cannot get this information.
