### ISSUE TITLE
Is there a way to make some kind of "reflection" on a Twig template?

### ISSUE THREAD

**Issue by ByScripts** [twigphp/Twig#1589]
Given a template filename, I would like to know which template it extends, and get a list of all blocks defined in the template and all its parents.

Is there a way to do that? Or do I need to parse the file by myself with some regex ?

**Comment by ninsuo** [comment]
Hello,

To get the parent template:
```jinja
{{ _self.parent.templateName }}
```

To get the parent's block list:
```jinja
{% for blockName in _self.parent.blocks|keys %}
   {{ blockName }}
{% endfor %}
```

To get the current template's block list:
```jinja
{% for blockName in _self.blocks|keys %}
   {{ blockName }}
{% endfor %}
```
You can access everything available in a template using `_self` variable. To know more about what's inside a template, you can look at compiled templates in your cache directory.


Please consider using the [Twig mailing list](https://groups.google.com/forum/#!forum/twig-users) to ask questions in the future.

Enjoy!

**Comment by ByScripts** [comment]
Thank you, for the answer and the link to the mailing list.

2015-01-09 21:33 UTC+01:00, Alain Tiemblo <notifications@github.com>:
> Hello,
>
> To get the parent template:
> ```jinja
> {{ _self.parent.templateName }}
> ```
>
> To get the parent's block list:
> ```jinja
> {% for blockName in _self.parent.blocks|keys %}
>    {{ blockName }}
> {% endfor %}
> ```
>
> To get the current template's block list:
> ```jinja
> {% for blockName in _self.blocks|keys %}
>    {{ blockName }}
> {% endfor %}
> ```
> You can access everything available in a template using `_self` variable. To
> know more about what's inside a template, you can look at compiled templates
> in your cache directory.
>
>
> Please consider using the [Twig mailing
> list](https://groups.google.com/forum/#!forum/twig-users) to ask questions
> in the future.
>
> Enjoy!
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/twigphp/Twig/issues/1589#issuecomment-69394513


-- 
--

*Thierry Goettelmann*
Développement Web
thierry@byscripts.info
