### ISSUE TITLE
Better variable accessor guessing

### ISSUE THREAD

**Issue by RyanThompson** [twigphp/Twig#1590]
Because the convention in theming is generally snake case and in PHP it is camel, consider the following:

{{ foo.bar_baz }} the getter is missed because it seems to be looking for getBar_baz()

However {{ foo.barBaz }} properly relates to getBarBaz() as far as conventions go.

It SHOULD check for getBarBaz() (snake case entire variable name) which will work in both tag cases but suggest best practices on the PHP side of things.

**Comment by RyanThompson** [comment]
Here I am guessing: https://github.com/twigphp/Twig/blob/79333cc8e3c6d74305837a2df0d4014cab67164f/lib/Twig/Node/Expression/Call.php#L22

I can send a PR in if there is an agreement here ^_^

**Comment by Tobion** [comment]
Duplicate of #934

**Comment by RyanThompson** [comment]
Wow sure is - should have searched better thanks!
