### ISSUE TITLE
Not starts with, not ends with

### ISSUE THREAD

**Issue by yguedidi** [twigphp/Twig#1594]
`{% if foo not starts with 'bar' %}` and `{% if foo not ends with 'bar' %}` not work, but might be better than the working `{% if not foo starts with 'bar' %}` and `{% if not foo ends with 'bar' %}`.

I can take care of adding both new expression nodes.

**Comment by fabpot** [comment]
I'm not sure that adding such tests would be good. I mean, adding more ways to do the same thing is never a good idea. So, even if I agree that it would be better, it's not worth it.

**Comment by yguedidi** [comment]
Maybe the `not` operator should be treat as a special one, and be able to prepend a binary operator, because `!(x === y) <=> not x equals b` same as `x !(===) y <=> x not equals y` which mean `x !== y <=> x different to y`. Any thoughts?

**Comment by stof** [comment]
@fabpot we already have the ``not`` operator currently, to prepend other operators. But the issue is that this syntax is working only when the following operator is single-word, while multi-word operator names are allowed in Twig. This is inconsistent

**Comment by fabpot** [comment]
@fabpot Not sure I understand what you mean. We do have specific support for `is not` and `not in`, but a general/default way of dealing with it. For instance, `not matches` or `matches not` does not work.

**Comment by sstok** [comment]
@fabpot are you talking to yourself? :joy:

**Comment by fabpot** [comment]
@sstok lol, indeed

**Comment by corysimmons** [comment]
I'm still not sure what the status of this is. I'm trying to use lots of combinations of things to negate a match (`if foo does not match '/derp/'...`).

Any suggestions on how to do this?

**Comment by SpacePossum** [comment]
@corysimmons 

try something like:

```twig
{% set foo = '123aa' %}
{{ foo matches '/^[\\d]+$/' ? 'Y' : 'N' }}
{{ not (foo matches '/^[\\d]+$/') ? 'Y' : 'N' }}
```

**Comment by corysimmons** [comment]
Okay thanks
