### ISSUE TITLE
Adding a language construct

### ISSUE THREAD

**Issue by charlydagos** [twigphp/Twig#1595]
Hello,

According to the [docs](http://twig.sensiolabs.org/doc/advanced.html)

> First, remember that Twig has two main language constructs:
>   {{ }}: used to print the result of an expression evaluation;
>   {% %}: used to execute statements.

I want to add another language construct (for example `[[  ]]`), that is similar to `{{ }}`.

I tried extending `Twig_Lexer` rather unsuccessfully, and it basically felt like it could better done through registering an extension. However I cannot find that in the docs, if it's possible in anyway.

So my question is:

Can I add another language construct, and if so, what's the easiest way to go about it? 

Thanks :smile:

**Comment by stof** [comment]
What is the goal to have another similar construct ?

**Comment by stof** [comment]
And no, extensions cannot add language constructs. They can provide custom tags (inside the ``{% %}`` construct) or functions, filters, tests, operators and global variables (to be used inside expressions)

**Comment by charlydagos** [comment]
Well basically my goal is to have `[[ ]]` (or any other enclosing characters) behave in different, predefined ways, so as to simplify a designer's work (who doesn't have to know about *expressions*, *filters*, *operators*, etc).

If I can have `[[ text ]]` do behave as an alias of `{{ text|uppercase }}`, then it'd allow me to extend the language to my liking and broaden how I use Twig :smiley: 

Is there **any** way of doing this? I take it I might have to extend the Lexer and/or Tokens? I've barely browsed over the code to understand it fully, heh

**Comment by stof** [comment]
No, there is no way to do it. It would not only require extending the Lexer, but also the parser itself itself because you would be changing the syntax of the language itself beyond what Twig allows. What you are trying to achieve is actually defining your own template syntax entirely rather than extending the Twig language

**Comment by Tobion** [comment]
What you maybe could do is extend twig so that a certain filter is always applied. In that filter you could do your own stuff. But that's also limited and I fail to see your use-case, because 

> [[ text ]] behave as an alias of {{ text|uppercase }}

do you want to create dozens of new language construct for each alias?

**Comment by charlydagos** [comment]
I guess it depends on the difficulty of adding the construct. As the docs say, there's different things you can add, each with varying rate of occurrence and difficulty.

My approach is to simply have shorter ways of writing things like `{{ text|raw }}`. There's many different outputs in my templates that need escaping, and there's many different outputs that do not, therefore it'd be easier to have some people in my team write `[[ text_to_print_unescaped ]]` and/or `{{ tex_to_print_escaped }}`, more or less.

Perhaps I simply have the wrong approach altogether. As @stof said, there's no way to do it without extending the actual language, so I'm experimenting a bit with that (rather unsuccessfully) :)

**Comment by fabpot** [comment]
When we refer to language construct in the documentation, we are talking about tags; that's how we implement for, if, and so on. What you cannot extend is the syntax itself, which would make a totally new language that the default lexer/parser/compiler would not be able to deal with.

So, what you are asking for is not possible in Twig, nor desirable.
