### ISSUE TITLE
Cached template name should depends on enabled extensions and options

### ISSUE THREAD

**Issue by Koc** [twigphp/Twig#1604]
Use case: we can disable/enable debug mode on Symfony-based site depends on cookie (for debugging on production sites). And the problem is: twig regenerate templates which uses extensions available only for debug env. So all users without debug cookie got fatal error.

**Comment by fabpot** [comment]
You cannot share the same template cache for different Twig configuration. This is not supported.

**Comment by Koc** [comment]
So it would be nice create subdirectory `cache/%config_hash%` or consider config when generates cache key

**Comment by fabpot** [comment]
That's up to you.

**Comment by Koc** [comment]
No way to support it in core?

**Comment by stof** [comment]
Well, the core is asking for a cache folder. You can pass a different cache depending on the config environment or debug mode

**Comment by Koc** [comment]
I created this issue because we are having 2 separate dumped classes for DI container - for `debug=true` and `debug=false`. So it would logical do same for twig too.

Workaround for the issue.

```yml
# config.yml
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    cache:            %twig_cache_dir%
```

```php
# AppKernel
protected function getContainerBuilder()
{
    $container = parent::getContainerBuilder();
    $container->setParameter('twig_cache_dir', '%kernel.cache_dir%/twig'.($this->debug ? '-debug' : ''));

    return $container;
}
```
