### ISSUE TITLE
PHP Fatal error:  Allowed memory size of ... vendor/twig/twig/lib/Twig/Extension/Debug.php on line 66 ... when using : {{ dump(big_big_big)|raw }}

### ISSUE THREAD

**Issue by josedacosta** [twigphp/Twig#1606]
error: if we dump () with a massive variable:

{{ dump(big_big_big)|raw }}

PHP Fatal error:  Allowed memory size of ... vendor/twig/twig/lib/Twig/Extension/Debug.php on line 66

suggestion :

replace all var_dump(...); by :
https://github.com/symfony/var-dumper

another temporary solution:
install Xdebug, Xdebug dump() very well the enormous variables

**Comment by ninsuo** [comment]
In fact, there are lots of other cases where components could be useful inside other components. For example, in the Symfony2 validator, it could be useful to use parameters inside annotations, but it would require DependancyInjection component. There are lots of other cases like this - but this is the fair price for being able to use all components standalone; else it would be... a framework ;-).

For your specific case, this is really easy to overwrite the `dump` filter, you can see a full implementation here : https://github.com/ninsuo/twigfiddle/blob/master/web/src/Fuz/AppBundle/Twig/Extension/DebugExtension.php

**Comment by stof** [comment]
When you register the DebugExtension of the Symfony TwigBridge, it allows you to replace the ``dump`` function by an implementation based on the VarDumper component (which is done in Symfony 2.6+ when registering the DebugBundle btw). So there is no reason to force a dependency to VarDumper in Twig itself IMO. Just use the ``symfony/twig-bridge`` package for that.
