### ISSUE TITLE
Latest version of Twig uses deprecations

### ISSUE THREAD

**Issue by scaytrase** [twigphp/Twig#1612]
Latest version of Twig still uses deprecations and there is even no branch, where all classes have removed deprecated interfaces

I.e. 

https://github.com/twigphp/Twig/blob/master/lib/Twig/Node.php
```php
class Twig_Node implements Twig_NodeInterface
{
// some content
}
```

https://github.com/twigphp/Twig/blob/master/lib/Twig/NodeInterface.php
```php
/**
 * Represents a node in the AST.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 *
 * @deprecated since 1.12 (to be removed in 3.0)
 */
interface Twig_NodeInterface extends Countable, IteratorAggregate
```

When I request latest release of twig in Sf2 - I get a lot of debug errors from ```DebugClassLoader```, which fails all test due to phpunit default
```
convertErrorsToExceptions   = "true"
```

Is it possible to create a kind of transitional branch, where correct version of classes would be placed?

**Comment by stof** [comment]
Of course the node implements the deprecated interface. If we stopped implementing it, it would be a BC break.

**Comment by scaytrase** [comment]
Yes, but http://twig.sensiolabs.org/doc/deprecated.html say us, that instead of ```TwigNodeInterface``` we should use ```TwigNode``` which implements this ```TwigNodeInterface```. So to avoid deprecation we must use a class which implements this deprecation. How to break this loop?

**Comment by stof** [comment]
@scaytrase the issue is the way the DebugClassLoader reports usage of deprecated interfaces. See the issue references above

**Comment by scaytrase** [comment]
ok, thanks @stof
