### ISSUE TITLE
Can't use conditionally autoescape, i need this very hard

### ISSUE THREAD

**Issue by grytysek** [twigphp/Twig#1613]
this doesn't work 

    {% set mode = 'html' %}
    {% autoescape mode %}

also this doesn't work:

        {% autoescape testvar ? true : false %}

eather this:

        {% autoescape booleanvar %}

i think this syntax is similar to conditional using of extends in this case:
http://twig.sensiolabs.org/doc/tags/extends.html#conditional-inheritance
like this:

    {% extends standalone ? "minimum.html" : "base.html" %}

i can't really understand why such conditions works in extends but not in autoescape and this cause that my code like this will never works if You dont make this posiible:

                        
    <script type="text/tmp" id="tmp-li">
        {% set e = {eimg:'<%= eimg %>',cname:'<%= cname %>',eurl:'<%= eurl %>',ename:'<%= ename %>',ourl:'<%= ourl %>',endsat:'<%= endsat %>',location:'<%= location %>',title:'<%= title %>',category:'<%= category %>',cities:[{slug:'<%= city.slug %>',name:'<%= city.name %>'}],_: true} %}
        {% block tmp %}
            {% set _ = e._ is not defined %} {# is this rendered on php side? #} 
                
            {% autoescape _ %}
                {% if _ %}<ul class="offers-box clearfix">{% endif %}
                    <li class="col-xs-18 single-offer table-div clearfix" data-industry-name="job">
                        <div class="col-sm-offset-1 col-sm-2 hidden-xs table-cell text-left company-logo">
                            <img src="{{ e.eimg }}" alt="{{ e.ename }}" width="90" />
                        </div>
                    </li>
                {% if _ %}</ul>{% endif %}
            {% endautoescape %}
        {% endblock %}
    </script> 

... this is example of block in twig that is a template for php and also for templating engine in underscorejs

And here is example of using above template on php side in twig:
   
    {% for e in defaultsearch %}
        {{ block('tmp') }}
    {% endfor %}

and here is an example of using the same template in javascript using underscore library:

    var tmp          = _.template($('#tmp-li').html());
    $(...).html(tmp(data))

but there is a problem of rendering on first time, these data ("{% set e = {eimg:'<%= eimg %>',cname:'"....) in first rendering should be printed as raw (for example using filter raw), but when using like {{ block('tmp') }} all inner variable should be escaped to avoid javascript injection from data from database. It could be done by using conditional autoescape but as i mentioned above this is not possible...

**Comment by stof** [comment]
This is expected, because autoescaping is applied at compile time, not at runtime. So it cannot depend on the value of variables

**Comment by stof** [comment]
and moving the autoescaping at runtime would be a huge performance killer (and a very good way to introduce bugs in many places)

**Comment by grytysek** [comment]
That's what i thought...
So... doing such unified templates for php and js is not possible without making javascript injection vulnerability?

**Comment by grytysek** [comment]
i will change delimiter in javascript for example to [[ variable ]]  and [[=  variable ]]

**Comment by fabpot** [comment]
Closing as auto-escaping is Twig cannot be changed as explained by @stof.
