### ISSUE TITLE
Macros not known on calling renderBlock()

### ISSUE THREAD

**Issue by rtuin** [twigphp/Twig#1615]
This afternoon I was running into a situation where macros didn't work the way expect them to be, and I'm not sure whether this is a bug or a feature.

There is a script that calls the `renderBlock()` method to render a specific block, but the macro is only recognized when it is imported within the block itself. Even though Twig has the context because of `loadTemplate()`.

Please see the scripts below. 
Bug or feature, can anyone enlighten me?

```
{# PHP test script #}
$twig->loadTemplate($templateName);
$twig->renderBlock(‘bar’, []);
```

```
{# macros.html.twig #}
{% macro foo(text) %}
{{ text }}
{% endmacro %}
```

Works:
```
{# foo.html.twig #}
{% block bar %}
{% import 'macros.html.twig' as macros %}
{{ macros.foo('hello') }}
{% endblock %}
```

Doesn’t work: (undefined index macros)
```
{# foo.html.twig #}
{% import 'macros.html.twig' as macros %}
{% block bar %}
{{ macros.foo('hello') }}
{% endblock %}
```

**Comment by stof** [comment]
``renderBlock()`` is an internal API, so you should avoid calling it directly unless you know what you are doing (it requires some work to have proper cleanup on error for instance).

and the behavior is expected due to the way macros are implemented currently. ``{% import 'macros.html.twig' as macros %}`` is importing the template macros as a context variable named ``macros``. If you render only the block, the tag being outside the block is not executed, and so the ``macros`` variable is not added in the context.

**Comment by rtuin** [comment]
Thank you for your answer Christophe. It's just what I expected.
The renderBlock feature was implemented in the [mailer service of Sylius](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Mailer/TwigSwiftMailer.php). I feel like the calls to `renderBlock` are somewhat questionable and should be individual templates instead (and a translator call for the subject itself).

Do you know of any other software that renders twig templates for say multipart (mail) messages? I hope to get some inspiration there and improve this mailer.

**Comment by stof** [comment]
@rtuin FOSUserBundle and my own project at work are doing it (and FOSUserBundle does not handle error properly to avoid leaking output). But I also find it questionable, and I think that using separate templates is a better way.

**Comment by rtuin** [comment]
@stof good to hear we're on the same page then. I have to give this some more thought and will propose an improvement the next week or so.
Closing this ticket as my question is answered :)
