### ISSUE TITLE
round filter is broken, when representing numbers rounded to zero.

### ISSUE THREAD

**Issue by martinfrances107** [twigphp/Twig#1619]
He is some sample code showing how 0.25 should be represented with decreasing precision.

The sequence should be 0.25, 0.2, 0. The final result comes out  in error.

{# outputs "0.25" as expected #}
"{{(50/200)|round(2,'floor')}}"

{# outputs "0.2" as expeted #}
"{{(50/200)|round(1,'floor')}}" 

{# outputs "", NOT  "0" as expected #}
"{{(50/200)|round(0,'floor')}}" 

I am going to start looking for the cause, Its for an active project. so I would be grateful if someone could suggest a work around,  other than the obvious, which is  a condition to replace an empty return with a zero!

**Comment by martinfrances107** [comment]
Sorry - I should report my TWIG version

{{ constant('Twig_Environment::VERSION') }}

1.16.2

**Comment by ninsuo** [comment]
I cannot reproduce this: http://twigfiddle.com/faj1rk

**Comment by martinfrances107** [comment]
Ah that's interesting ....

I wrote my failing code, while working on  a Drupal8 module

I wonder what D8 is doing to mangle the output like that ...

That changes where I dig... 

Ninsuo - Thank you 

In any event, It looks like I should close this issue and open a drupal one...
I will do a little more work on this before I open a d8 issue, and then as I open that I will close this one. :)

**Comment by martinfrances107** [comment]
For what it is worth, I opened a d8 issue.

https://www.drupal.org/node/2417733

**Comment by joelpittet** [comment]
Got a patch in to resolve the issue, our autoescaping is short cutting through 0 values but the float returns a double/float.  0.0 and they are !==.

**Comment by martinfrances107** [comment]
patch committed to Drupal 8, issue fixed.
