### ISSUE TITLE
Twig doesn't render dollar ($) sign.   

### ISSUE THREAD

**Issue by feridmovsumov** [twigphp/Twig#1620]
Product titile is "Navy Maverick Aviator Jacket $10"

But when I try to render it with twig {{ product.title }} I get "Navy Maverick Aviator Jacket"

**Comment by ninsuo** [comment]
I cannot reproduce this: http://twigfiddle.com/npi2eq
Can you provide your Twig's version number and more info about your code?
Thanks,

**Comment by fabpot** [comment]
Closing as there is no feedback and because I doubt that the problem comes from Twig.
