### ISSUE TITLE
Problem with form use name "time"

### ISSUE THREAD

**Issue by andrewsmm** [twigphp/Twig#1623]
I use twig in Symfony 2.6.5. I created a FormType and set in public function getName(){ return "time" }
and get next error when render form(form):
Variable "widget" does not exist in form_div_layout.html.twig at line 123 

If i use any other name this problem resolve.

**Comment by ninsuo** [comment]
Can you give us this line 123? Thanks

**Comment by andrewsmm** [comment]
{% block time_widget -%}
    {% if widget == 'single_text' %}
        {{- block('form_widget_simple') -}}
    {% else -%}
        {% set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} %}
        <div {{ block('widget_container_attributes') }}>
            {{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {%- endif %}
{%- endblock time_widget %}

**Comment by ninsuo** [comment]
Ok -- are you sure `widget` is set? What if you type {{ widget|default('undefined') }}?

**Comment by Tobion** [comment]
You cannot use `time` as form name because it collides with the core form TimeType. Thus overwriting stuff and making bad things happen. Try using a different name.

**Comment by Tobion** [comment]
Also this is the wrong repository and has nothing to do with twig. Please close.
