### ISSUE TITLE
The title filter on date style phrases shows incorrectly

### ISSUE THREAD

**Issue by viion** [twigphp/Twig#1625]
If you have a number in-front of a letter, the first letter of the word is capitalized regardless of numbers prior to it. For example

```
{% set var = '3rd of the 7th winning' %}
{{ var|title }}
```
Output: **3Rd Of The 7Th Winning**
Expected: **3rd Of The 7th Winning**

Fiddle: http://twigfiddle.com/0s11rr

PHP's ``` ucwords() ``` does it as expected, apologies if I'm using the wrong filter.

**Comment by ninsuo** [comment]
I :+1:  this

From the source code, it comes from the `mb_convert_case` function.

```php
    /**
     * Returns a titlecased string.
     *
     * @param Twig_Environment $env    A Twig_Environment instance
     * @param string           $string A string
     *
     * @return string The titlecased string
     */
    function twig_title_string_filter(Twig_Environment $env, $string)
    {
        if (null !== ($charset = $env->getCharset())) {
            return mb_convert_case($string, MB_CASE_TITLE, $charset);
        }

        return ucwords(strtolower($string));
    }
```

If you test both functions separately, we get:

```php
$str = "3rd of the 7th winning";

// 3Rd Of The 7Th Winning
echo mb_convert_case($str, MB_CASE_TITLE, "UTF-8");

// // 3rd Of The 7th Winning
echo ucwords($str); 
```

The bug has already been reported 6 years ago: https://bugs.php.net/bug.php?id=46607
So using a workaround should be better.

**Comment by fabpot** [comment]
Closing this issue as the related PR was closed.
