### ISSUE TITLE
Can loaders get the context (name/path) of a calling template?

### ISSUE THREAD

**Issue by Cottser** [twigphp/Twig#1627]
Coming from https://www.drupal.org/node/2387069

From a Twig loader I am trying to get the context (name/path) of the calling template (the template containing the `include` or `extends` tag) and coming up short. Is this possible or am I barking up the wrong tree? Would there be another/better way to handle this?

Thanks.

**Comment by stof** [comment]
It cannot (this may be checked by a node visitor at compile time in some cases though). Thus, the loader will be triggered only for the first import of the template (Twig does not load the same template several times), so it cannot be used to protect against circular imports.
And building such a protection will be very hard: there are valid use cases to include the same template recursively (for instance when rendering a tree structure) if you take care of having a finite loop.

**Comment by Cottser** [comment]
@stof - thanks for the response. We are using recursive templates already in Drupal 8: http://cgit.drupalcode.org/drupal/tree/core/modules/system/templates/menu.html.twig

The issue we are trying to solve is that with the loader in question we do get an infinite PHP loop because it infinitely tries to extend itself.

We can probably close this because we at least know where to dig if we want to try and build in this protection. Thanks again.
