### ISSUE TITLE
Title filter on quoted string leaves words uncapitalized

### ISSUE THREAD

**Issue by michaelrog** [twigphp/Twig#1630]
It appears the title filter isn't sensitive to punctuation such as quote marks.

For example:
`'twig: the "ash wednesday" edition' | title`
would incorrectly produce:
`Twig: The "ash Wednesday" Edition`

(I'm seeing this issue in Craft CMS v2.3.2632, which appears to be using Twig v1.16.)

**Comment by joelpittet** [comment]
PHP does this as well, I don't think this is a Twig bug.
http://codepad.viper-7.com/bBhlLY

**Comment by michaelrog** [comment]
Yes, I noticed that as well. But, is that the *desired* behavior for the `title` filter? The docs seem to imply a slightly more nuanced ability... ("The title filter returns a titlecased version of the value" — not just that `ucwords` is applied.)

**Comment by joelpittet** [comment]
I'm quite sure that is exactly the desired behavior:
https://github.com/twigphp/Twig/blob/master/lib/Twig/Extension/Core.php#L1327

As that is how it's written.
