### ISSUE TITLE
attribute does not work properly when using macro variables as parameters to it

### ISSUE THREAD

**Issue by bgewehr** [twigphp/Twig#1632]
like described here http://stackoverflow.com/questions/28644743/twig-attribute-function-does-not-work-properly-when-used-in-twig-macro-smartivi

i have troubles with the attribute function when used in another macro.

Can someone please have a look, the results are not deterministic...

**Comment by bgewehr** [comment]
I got one step further: When i use scalar values as parameters to the attribute function, all works fine. But when i use variables instead it goes wrong: now the result is not predictable.

**Comment by ninsuo** [comment]
I cannot reproduce your case.
http://twigfiddle.com/uiq80g

Can you provide a reproductible case?

**Comment by bgewehr** [comment]
This behaves exactly like in my environment:
http://twigfiddle.com/uiq80g

data-min="3" data-max="255" is not what i expected!

Should be data-min="2.2" data-max="3" instead!

**Comment by ninsuo** [comment]
Well, you pass only 6 arguments to the `shifter` macro, but the `shifter` macro requires 7 parameters. 
`max` being the last one, it defaults to 255.

**Comment by bgewehr** [comment]
S... You're right, sorry for beeing so stupid! Thank you!

**Comment by ninsuo** [comment]
You're welcome. 

If you deal with lots of arguments in your macros, you'd better use the javascript-style format to avoid the need to pass even useless arguments to them:

```jinja
{% macro test(options) %}

{%
   set settings = {
     'color': 'black',
     'size': 'XL',
   }|merge(options)
%}

{# ... #}

{% endmacro %}
```

Sample: http://twigfiddle.com/hljgul
