### ISSUE TITLE
Twig 1.18.0 - tag "set" has a bug

### ISSUE THREAD

**Issue by Cyrille37** [twigphp/Twig#1633]
Twig 1.18.0

In the template:
```html
 {% set machine = 134 %}
```
the compiled template code is
```php
 $context["machine"] = 134;
 // line 33
 echo twig_escape_filter($this->env, (isset($context[" machine"]) ? $context[" machine"] : null), "html", null, true);
```
There is a space in the array key **" machine"** as is should be **"machine"**.

**Comment by joelpittet** [comment]
Trying to reproduce but can't : http://twigfiddle.com/dsdshb

Is there a character encoding issue maybe or an upper utf space character after the =?

**Comment by Cyrille37** [comment]
You should right, was maybe an upper utf space ...
Thanks a lot, I clause da but
