### ISSUE TITLE
Twig operator precedence discussion

### ISSUE THREAD

**Issue by maldoinc** [twigphp/Twig#1634]
In twig the `|` filter operator has a higher precedence than the rest. I think it should be the other way around.

Here's an example on how it could cause confusion: `2 * 2000 | number_format(2)` one would expect to output "4,000", instead it outputs "4" because it is evaluated as `2 * (2000 | number_format(2))` which in turn is evaluated as `2 * 2,000` and due to php's type coercing "2,000" is converted as an int to the value 2. So the whole expression is evaluated as `2 * 2`

Here is the twig parser output which verifies this:

    Twig_Node_Expression_Binary_Mul(
        left: Twig_Node_Expression_Constant(value: 2)
        right: Twig_Node_Expression_Filter(
            node: Twig_Node_Expression_Constant(value: 2000)
            filter: Twig_Node_Expression_Constant(value: 'number_format')
            arguments: Twig_Node(
                0: Twig_Node_Expression_Constant(value: 2)
            )
        )
    )

**Comment by stof** [comment]
Changing this now would be a huge BC break (and very hard to understand for users).

**Comment by fabpot** [comment]
I do understand your reasoning here but I think it's too late to make such a change.
