### ISSUE TITLE
Feature proposal - existential operator

### ISSUE THREAD

**Issue by AZielinski** [twigphp/Twig#1635]
There is something like this in coffeescript. Basically it would be really nice to be able to do something like:

```
{% if order.invoice?.total %}
    ..something
{% endif %}
```

and it would translate to

```
{% if order.invoice and order.invoice.total %}
    ..something
{% endif %}
```

Currently it throws an exception:

`Impossible to access an attribute ("total") on a NULL variable ("")`

**Comment by ninsuo** [comment]
Hello,

You can already do it using `| default` filter.

```jinja
{% if order.invoice.total|default(false) %}
   {# .. something #}
{% endif %}
```

See: http://twig.sensiolabs.org/doc/filters/default.html

**Comment by AZielinski** [comment]
Thanks! I didn't realize `|default` takes care of nulls in whole chain, thanks!
Btw I didn't see twigfiddle before, it's great!
