### ISSUE TITLE
Replace - Case Insensitive

### ISSUE THREAD

**Issue by pnkthrepwood** [twigphp/Twig#1636]
I want to replace a text inside a string to make it bold, here's my code:

```
{{ string|replace({(text): '<span style="font-weight: bold;">'~text~'</span>'})|raw }}
```

In this example:

```
string = "Hello world!"
text = "hello"
```

It will not replace the word 'Hello'.

Is there any workaround for this?

**Comment by stof** [comment]
you would need your own filter for that (PHP does not have case insensitive string replacement functions, it requires using a regex).

On a side note, be careful that your code above opens a XSS hole in case the content of ``string`` can come from user input because you are not escaping it anymore.

**Comment by barryvdh** [comment]
Wouldn't this be possible to use for an `ireplace` function?

http://stackoverflow.com/questions/7529330/php-case-insensitive-equivalent-of-strtr
```str_ireplace(array_keys($replace_pairs), array_values($replace_pairs), $str);```

**Comment by matthieuauger** [comment]
Currently, the `replace` filter seems to be just a proxy for [strtr](http://php.net/manual/fr/function.strtr.php) function, which have a different signature than [str_replace](http://php.net/manual/fr/function.str-replace.php).

I guess we could create our own function to dispatch toward one or the other, but the behaviours are also [slightly different](http://stackoverflow.com/questions/8177296/when-to-use-strtr-vs-str-replace), and as a developer, I would expect from a case insensitive replace to behave exactly as the case sensitive replace (except for the case of course)

**Comment by Dikerss** [comment]
The twig **ireplace** function works fine

`{{ string|ireplace({(text): '<span style="font-weight: bold;">'~text~'</span>'})|raw }}`
