### ISSUE TITLE
Non-comprehensible html output

### ISSUE THREAD

**Issue by Trainmaster** [twigphp/Twig#1640]
I'm really struggling with getting proper rendered html. See the following examples.

### Simple loop
Taken from http://twig.sensiolabs.org/doc/tags/if.html
```twig
{% if users %}
    <ul>
        {% for user in users %}
            <li>{{ user.username|e }}</li>
        {% endfor %}
    </ul>
{% endif %}
```

*Output*
```html
    <ul>
                    <li>Hans</li>
            </ul>
```
*Expected*
```html
<ul>
    <li>Hans</li>
</ul>
```

### Simple if
```twig
<div>
    <h1>Foo</h1>
    {% if users %}
        <p>There are users!</p>
    {% endif %}
</div>
```

*Output*
```html
<div>
    <h1>Foo</h1>
            <p>There are users!</p>
    </div>
```
*Expected*
```html
<div>
    <h1>Foo</h1>
    <p>There are users!</p>
</div>

```

### Simple include
```twig
<div>
    {% include 'navigation.tpl' %}
</div>
```
``navigation.tpl``
```twig
<nav>
    <ul>
        <li>Foo</li>
    </ul>
</nav>
```
*Output*
```html
<div>
    <nav>
    <ul>
        <li>Foo</li>
    </ul>
</nav>
</div>
```
*Expected*
```html
<div>
    <nav>
        <ul>
            <li>Foo</li>
        </ul>
    </nav>
</div>
```

What I'm doing wrong or is it just I'm expecting too much from Twig?

**Comment by Tobion** [comment]
If you really care about whitspace, look at white space control in twig doc.

**Comment by Trainmaster** [comment]
It's not that I didn't give the whitespace control a try.

If we look at my last example the ``include`` statement sets correct whitespace just for the first line of the included template. If I change ``navigation.tpl`` to
```twig
<nav>
        <ul>
            <li>Foo</li>
        </ul>
    </nav>
```
I get the expected output. But that can't really be a solution. And I have no clue how the other examples can be solved with whitespace control.

**Comment by ninsuo** [comment]
That's not really friendly to manage whitespace control, and you know, Twig doesn't basically aim to format your code. You'd better use something like [Mod-Tidy](http://mod-tidy.sourceforge.net/) to do the job for you.

**Comment by fabpot** [comment]
I'm closing this issue as there are other similar ones.
