### ISSUE TITLE
Compatibility between Twig 1.last and 2.0 for packages extending Twig

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#1644]
Currently, Twig 2.0 introduces a few hard BC breaks in classes where the typehints are changed because of the removal of a bunch of interfaces:

-  Twig_NodeVisitorInterface changed signature
- removal of ``Twig_ExistsLoaderInterface`` (making it impossible to write a loader compatible with Twig 2.x+ while being efficient on 1.x as it cannot implement the removed interface even if it implements the method)

These 2 changes mean that it is impossible to write a package depending on these features and supporting both Twig 1.x and 2.x, thus forcing to split the community: once a package migrate to Twig 2.x, you can use it in your project only if *all* other packages you are using are migrated too.
This would be an issue for Symfony for instance, which would have to break the Twig 1.x compatibility at some point when switching to 2.x (forcing the whole Symfony community to switch at the same point and to maintain older versions of their lib for Twig 1.x because of the Symfony LTS).

It would be much better to provide BC/FC layers for these:

- keeping the ``Twig_ExistsLoaderInterface`` for now (as an empty interface extending ``Twig_LoaderInterface`` so that loaders can be compatible with Twig 1.x in an efficient way (the ``exists`` method has been added to improve performance), and removing it in 3.0 only (as done for ``Twig_Simple(Filter|Test|Function)``)
- for the node visitor typehint change, a way to handle it would be to provide a base node visitor class in Twig 1.19 which would implement the methods and delegate the logic to protected methods using the Twig_Node typehint, and updating the public methods in 2.x to change the typehint. This way, a library could be compatible with both 1.19+ and 2.x by implementing the protected methods instead of the public ones.

this would make the adoption of Twig 2.x much easier by allowing extension packages to support both versions without branching different versions of themselves (which would either require abandonning the 1.x support or abandonning semver to add features in 2 versions in parallel based on Twig versionning)

**Comment by Green-Cat** [comment]
:+1:

**Comment by joelpittet** [comment]
👍

**Comment by fabpot** [comment]
Anyone willing to implement those changes?

**Comment by joelpittet** [comment]
I'm not super strong on the internals, but I'll try to send some pull requests to get there.

**Comment by joelpittet** [comment]
@stof Just to clarify the FC layer base class a bit more.  ```abstract class Twig_NodeBase implements Twig_NodeInterface```  would be created implementing the protected methods from Twig_Node?  Remove them from Twig_Node and extend from Twig_NodeBase. And change the type hint to Twig_Node in 1.x?

I may be completely lost in the implementation of your idea?

**Comment by stof** [comment]
@joelpittet the forward compatibility is for Twig_NodeVisitorInterface here, not for Twig_Node (IIRC, there is no issue for Twig_Node, but I may be wrong)

**Comment by fabpot** [comment]
#1752 and #1753 should cover compatibility for common use cases.

**Comment by stof** [comment]
@fabpot for better compatibility with existing code checking the possibility of the loader, the core loaders should implement the ``Twig_ExistsLoaderInterface`` too, so that libraries supporting both 1.x and 2.x can rely on this interface to perform the check. Otherwise, we only have the BC layer for packages providing loaders

**Comment by stof** [comment]
@fabpot the remaining point is discussing whether ``Twig_ExistsLoaderInterface`` and ``Twig_Simple*`` should be marked deprecated in 2.0 already or wait longer for that.
Given that using them is required to be compatible with both 1.x and 2.x (the loader interface to keep the performance enhancement, and the simple classes because the 2.x non-deprecated names are taken by old classes in 1.x), deprecating them already means it is impossible to write deprecation-free code compatible with both (and currently, being compatible with both is the only sane way to support 2.x)

**Comment by Tobion** [comment]
If people only want to maitain one branch for both major versions, then they have to live with using deprecated code IMO. That is exactly one reason why there are two major versions of twig. And to me it wouldn't make sense to have two classes Twig_Filter and TwigFilter for the same thing in a new major version without saying with should be used.

**Comment by stof** [comment]
@Tobion the main issue we have here is that the class to use in 2.x already exists in 1.x but with a different name. This means we have no real forward compatibility here. The solution would have been to choose an available name in 1.x for the class to use in 2.x (instead of choosing an available name which would become deprecated immediately in 2.0 when reusing an old class name with a different purpose).

And the issue with having deprecations triggered all the time when using Twig 2.x is that users of the library will open issues to the library all the time  asking them to stop using deprecated features so that their Symfony projects don't report them deprecated calls all the time (making it easier to find their own usage of deprecated features)

**Comment by Tobion** [comment]
Again libraries can just use two branches.

**Comment by stof** [comment]
@Tobion maintaining 2 different versions of the library just for different versions of Twig is a pain in the ass, and makes it quite impossible to follow semver (because you are now versionning based on other libraries, not your own code). And it becomes even more insane if you have to deal with multiple deps, not just Twig.

**Comment by fabpot** [comment]
@stof This one can be closed now, right?

**Comment by stof** [comment]
Yes indeed.
