### ISSUE TITLE
[2.0] Switch internal methods to private rather than protected

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#1645]
Currently, Twig is using the protected visibility almost everywhere, which means that any internal refactoring is technically a BC break.
Many of these protected members are not meaningful extension points at all. So I think that Twig 2.0 might be a good time to switch them to private (following the same rules than in Symfony, and making it much easier to follow semver by reducing the surface subject to BC)

**Comment by SpacePossum** [comment]
:+1:  would it help even more to declare some of the classes `final` as well?
