### ISSUE TITLE
"removed the Autoloader as Composer provide one"

### ISSUE THREAD

**Issue by sarciszewski** [twigphp/Twig#1646]
Just FYI, I was using git submodules in one of my projects (I don't pipe to my shell, so I don't use composer) and this change broke compatibility and I had to write my own :(

http://curlpipesh.tumblr.com/post/75800314128/its-always-safer-with-php

Solution for anyone else who runs into this:
https://gist.github.com/sarciszewski/b6cd3776fbd20acaf26b

**Comment by ninsuo** [comment]
Pipe is not mandatory, you can also install composer using 2 commands:

```sh
wget https://getcomposer.org/installer
php installer
```
or with curl:

```sh
curl -o installer https://getcomposer.org/installer
php installer
```

**Comment by sarciszewski** [comment]
When they distribute a digital signature (RSA or EdDSA) let me know. Until then, I refuse to use it.

**Comment by henrikbjorn** [comment]
@sarciszewski your problem is that you track the "master" branch which now contains the upcoming 2.0. You should change to track the "1.0" branch instead.

**Comment by ninsuo** [comment]
Okey sorry @sarciszewski I was confused by the *(I don't pipe to my shell, so I don't use composer)* sentence. By the way, I'm not experienced on security, your explication makes sense.

**Comment by fabpot** [comment]
As @henrikbjorn said, you should switch to the 1.x branch instead of master. See http://blog.twig.sensiolabs.org/post/112865370458/twig-master-as-the-upcoming-2-0

**Comment by sarciszewski** [comment]
I did so, I just wanted to provide this for anyone who doesn't want to use composer ;)

**Comment by ninsuo** [comment]
Thank you. At lest, it will be useful for Twig 2.x implementation on twigfiddle.com (can't use composer as it supports all twig versions)

**Comment by stof** [comment]
@ninsuo you could use any PSR-0 compatible autoloader though
