### ISSUE TITLE
from does not import overloaded bundle template

### ISSUE THREAD

**Issue by nicolasricci** [twigphp/Twig#1648]
Hi 
I have noticed a strange behaviour with the from function.

```twig
{% from MyBundle:MyFolder/my_macros.html.twig import my_macro %} 
```
is importing the macro from /vendor/MyBundle/Resources/views/MyFolder 
whereas the same code with the import function

```twig
{% import MyBundle:MyFolder/my_view.html.twig as macros %} 
```
is importing the file from app/Resources/MyBundle/Resources/views/MyFolder when it exists

Any idea on this?

**Comment by ninsuo** [comment]
Hi,

Yes, you can overwrite any part of a Symfony2 Bundle, including templates using `app/Resources` directory:
http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates

BTW, I don't think this issue should be opened on Twig project, it is related to Symfony2.

**Comment by nicolasricci** [comment]
Hi,

I know we can usually overwrite any part of the template in `app/Resources`.

But I have some weird behaviour with the `from` function from twig, hence why I have created this issue here.
As explained I have overloaded a template from the a vendor Bundle with the following code

```twig
{% from MyBundle:MyFolder/my_macros.html.twig import my_macro %} 
```

If I call the following code in my template it is going to load the one from the vendor directory

``twig
{{ my_macro(my_param) }} 
```
whereas if I use the import statement such as 

```twig
{% import MyBundle:MyFolder/my_macros.html.twig as macros %} 
```

and call 

```twig
{{ macros.my_macro(my_param) }} 
```

it is loading the correct my_macro function from the overloaded file in `app/Resources`

I will dive into the code and let you know if I find a reason for this

**Comment by ninsuo** [comment]
If you look at the compiled template in [this sample](http://twigfiddle.com/frmtge), you'll see that the loader is called the very same way for both files.

If you look at your first example, you're using `my_view.html.twig` and `my_macros.html.twig`, are you sure both files are overwritten in your `app` directory?

**Comment by nicolasricci** [comment]
That was just a typo in my example. I have not yet got to the bottom of it but will get back to you once I have.

**Comment by fabpot** [comment]
Any news on this one?

**Comment by nicolasricci** [comment]
Looks like it has been fixed.
