### ISSUE TITLE
Implement {% raw %}

### ISSUE THREAD

**Issue by howardroark** [twigphp/Twig#1653]
Hey!

I love the product!  There is one place that I wish it would line up with Jinja2 though. It would be nice if escaping could be accomplished with `{% raw %} {% endraw %}`. 

I am building a series of of templates based off off html5up.net which are intended to work with Jinja2, Twig and Nunjucks.  I would love to be able to use the same escape method in them all.  Currently Nunjucks does support `{% raw %} {% endraw %}` and it would be really great if Twig did as well.

https://github.com/tmpls

Thanks!

**Comment by ninsuo** [comment]
Hello,

This feature was removed in 2.x.

The `|raw` filter disables escaping on a string, and `{% autoescape  %}` is the related tag to do it on a larger piece of code. The `{% raw %}` tag added confusion as users expected it to work like `{% autoescape false %}`.

**Comment by howardroark** [comment]
Ah ok I think I see what you are saying.  So this is more of a case where Twig has diverged from Jinja2 in that in that  `|raw` is used vs `|safe` and then  `{% verbatim %}`  is used instead of `{% raw %}`?

Full disclosure... I only have limited experience working with Twig.  I am just looking at designing templates that work for both :)

**Comment by ninsuo** [comment]
Yes that's it.

**Comment by ninsuo** [comment]
Here is a sample: http://twigfiddle.com/h9tjsv

**Comment by howardroark** [comment]
In that event I would still like to make a request that Twig support `{% raw %}` and `|safe` since it sounds like they would not conflict with any existing code.  They would more or less be aliases to `{% verbatim %}` and `|raw`.

This would allow me to design templates that run across PHP, Node.js and Python which can be integrated into just about any web framework.  Jinja2 and Nunjucks both support the same syntax here and it would be super helpful if Twig did as well :)

Not expecting anyone to jump on it... just to be open to it. I could probably chip away at pull request as well.

**Comment by stof** [comment]
Well, ``{% raw %}`` is supported in Twig 1.x, and it was explicitly removed from Twig 2.x (currently in development)

**Comment by howardroark** [comment]
Darn, that is a shame. I hope it could be reconsidered. 

Twig is derived from Jinja because its sandboxed design could be so easily ported to another language. With Nunjucks on the scene there is now a huge opportunity to design templates that work everywhere. 

It would be really smart (IMO) if this project made efforts to share the same base syntax as its predecessor.

**Comment by reFX-Mike** [comment]
I think that some features of Nunjucks (e.g. like the async feature) are not doable, and as such their respective templates are incompatible anyway.

I personally would prefer if each engine/system would take advantage of it's underlying language (like Nunjucks does with the async feature) so each user (me in this case) gets the best features a system can have, instead of trying to keep everything compatible with everything else and compromising too much.

**Comment by jtwebb** [comment]
@howardroark You can create your own extension for twig. [The docs are here](http://twig.sensiolabs.org/doc/advanced.html).

If you're needing to create aliases then it would be rather trivial; you could copy/paste code for what you needed but just give them a different name. I'm sure there's a more elegant way to keep things DRY but that's just the first thing that popped in my head.

You might even be able to extend the classes that you need and just override the methods that dictate the names of the filters/tags.

**Comment by howardroark** [comment]
Yeah, that seems like the best plan from here.  Thanks @jtwebb :)

I'll close this up.
