### ISSUE TITLE
Lexer -> Tag leftover bug

### ISSUE THREAD

**Issue by SpacePossum** [twigphp/Twig#1654]
Hi,

On this line there is a reference to `$tag` in the build of the exception message:
https://github.com/twigphp/Twig/blob/master/lib/Twig/Lexer.php#L291
However the `$tag` variable is no longer passed on.
I don't know how to fix it, but I thought to let you you know (on `master` only btw).

**Comment by ninsuo** [comment]
:+1:

**Comment by ninsuo** [comment]
We do not use `{% raw %}` anymore so we should write `Unexpected end of file: Unclosed "verbatim" block` instead.
