### ISSUE TITLE
Test Case failure. 

### ISSUE THREAD

**Issue by r3wt** [twigphp/Twig#1657]
`'&ldquo; <br/> &rdquo;'|nl2br|raw` 

i tried wrapping it in autoescape off to no avail. i ended up just replacing the entities in the model before instantiate the view.

**Comment by ninsuo** [comment]
Hi, I am sorry but I do not understand the issue at all.
Can you tell us what you are expecting with the code you given?

**Comment by reFX-Mike** [comment]
Sounds to me like r3wt is expecting Twig to convert his HTML-entity-encoded string to be back-converted into 'raw' versions.

'raw' doesn't convert into anything. It leaves the string alone. It's not meant to convert into raw.

**Comment by r3wt** [comment]
@reFX-Mike looks like to me that Twig is replacing `&rdquo;` with `&amp;rdquo;`

**Comment by reFX-Mike** [comment]
Looks fine to me:

http://twigfiddle.com/eec122

**Comment by SpacePossum** [comment]
Ps. @r3wt is the string is in a variable try this:

```twig
{% set foo = '&ldquo; <br/>
&rdquo;' %}

{{ foo|raw|nl2br }}
```

http://twigfiddle.com/3z0jic
