### ISSUE TITLE
Twig_Extension::getName() allows to return null (A validation should be)

### ISSUE THREAD

**Issue by mikemirten** [twigphp/Twig#1658]
There is no validation of value returned by Twig_Extension::getName().
I forgot to put "return" before the name and lost a lot of time to understand why one extension overwrites another one.

**Comment by fabpot** [comment]
We cannot guard against all mistake like this one as it would make Twig much slower. As this is the first in years that someone had this problem, I'm going to close this.

**Comment by stof** [comment]
yeah, the day PHP 7 is the min requirement, we could use a return type hint to ensure it. But until then, adding checks in all places is too cumbersome.
This is more a job for static analyzers than for runtime checks

**Comment by mikemirten** [comment]
Yes, i know, the mistake is quite stupid, but there is a lot of places in the Symfony with such a runtime validations, so I've decided to open the issue. My apologies for bothering.
