### ISSUE TITLE
How can i use a variable as a key ?

### ISSUE THREAD

**Issue by r3wt** [twigphp/Twig#1663]
I tried this:

`{% if item.(item2.name) == 1 %}checked{%endif%}`

and get

`A hash key must be a quoted string, a number, a name, or an expression enclosed in parentheses (unexpected token "punctuation" of value "{" in "admin/crud_brand.twig" at line 45`

i need to use `item2.name` as the key on `item`

**Comment by Tobion** [comment]
Look at the attribute function.
This issue tracker is for bugs only. Please use the mailing list for support questions.

**Comment by r3wt** [comment]
thanks @Tobion
