### ISSUE TITLE
date-modify strange behaviour

### ISSUE THREAD

**Issue by jblanchon** [twigphp/Twig#1665]
Hi,
I have noticed a strange behaviour with date-modify method

I use this code in order to display the last three months in a table (the aim is to display statistics for the last three months)
```
 {% for i in 3..1 %}
   <th class="custom-border-right" colspan="3">{{ 'now'|date_modify("-" ~ i ~     "month")|localizeddate('short', 'none', null, null, 'LLLL yy') }}</th>
{% endfor %}
```
if we are on March 15 (2015), this code will display
```
<td>December 14</td>
<td>January 15</td>
<td>February 15</td>
```

But if we are on March 30 (just like today)

i will get this

```
<td>December 14</td>
<td>January 15</td>
<td>March 15</td>
```

I think it's simply because my script is searching for the 30th of february witch does not exist...

Could anyone help me to find a solution ?
Thank you
Jb

**Comment by sstok** [comment]
I tried this using plain PHP.

```bash
php -r "echo (new DateTime('- 1 month'))->format('d-m-Y');"
```

And

```bash
php -r "echo (new DateTime())->modify('-1 month')->format('d-m-Y');"
```

And both gave me 02-03-2015 :confused: so it seems this is a behavior of PHP self.

**Comment by sstok** [comment]
Ah OK, this seems to be expected behavior because this stupid function doesn't work properly with subtraction (only with adding). There is a workaround for this but you need to use your own function.
https://gist.github.com/66Ton99/60571ee49bf1906aaa1c

**Comment by jblanchon** [comment]
Thank you very much, this helps me a lot ! I will try with your solution

Jb

**Comment by mohamedhafezqo** [comment]
Thanks it's working.
