### ISSUE TITLE
On rendering form labels part of code get cut and "Warning: gettext() expects exactly 1 parameter, 3 given" appears

### ISSUE THREAD

**Issue by htochko** [twigphp/Twig#1670]
cached code:
echo ">";
echo twig_escape_filter(
              $this->env, 
              gettext((isset($context["label"]) ? $context["label"] : $this->getContext($context, "label")), 
              array(), 
              (isset($context["translation_domain"]) ? 
                         $context["translation_domain"] : 
                         $this->getContext($context, "translation_domain"))
              ), 
               "html",
                null,
                true
         );
echo "</label>";
finally becames:  
             gettext('Name', array(), null)
at back-trace on form label rendering - seems like statement becomes cut and rest of parameters 'twig_escape_filter' comes to 'gettext'.
Please let me know if more information needs to be provided.

**Comment by reFX-Mike** [comment]
Can you please post the twig template that creates this code?
