### ISSUE TITLE
add a list of frameworks using twig to the twig website

### ISSUE THREAD

**Issue by jrobeson** [twigphp/Twig#1671]
A user in #symfony asked which frameworks other than symfony used Twig. The only thing i could think of off the the top of my head was Drupal 8. It'd be nice to have a page to point people to.

**Comment by iekadou** [comment]
I was the user. It would really help, to see the spread of twig. :+1:

**Comment by anlutro** [comment]
Would you include frameworks that provide optional twig integration?

**Comment by jrobeson** [comment]
well technically even symfony's twig integration is optional (before 3.0). Not sure where to draw the line exactly.

**Comment by fabpot** [comment]
Let's list all frameworks/CMSes that supports Twig. Here is a first line (top of my head):

* Symfony
* Drupal 8
* eZPublish
* phpBB
* Piwik
* Craft
* bolt
* dotclear
* a lot more I cannot remember of right now :)

We might also want to link to their respective websites.

**Comment by iekadou** [comment]
Sylius is using it too

**Comment by jrobeson** [comment]
so projects based on symfony directly count?  I guess i'm not sure where draw the line before we add every symfony app :)

**Comment by fabpot** [comment]
I think we need to come up with a list of "significant" projects. Problem is in the definition of significant :) ... and then, everyone will want to add his own pet project to the list.

**Comment by kamilsk** [comment]
[OroCRM](http://www.orocrm.com) based on Symfony components, in particular uses the Twig

**Comment by kamilsk** [comment]
Yii has [official extension](https://github.com/yiiext/twig-renderer), supported by members of core team

**Comment by barryvdh** [comment]
I use Twig with Laravel, but it's not 'officially' supported I guess..

**Comment by ninsuo** [comment]
There are lots of unofficial Twig modules for Codeigniter too.

**Comment by r3wt** [comment]
Slim 2.6.2 + Twig in 2 easy steps

```php

namespace FooBar;

class Application
{
	public static $self = null;
	public $slim;
	public $twig_config;
	
	function __construct($slim_config,$twig_config)
	{
		if(self::$instance === null)
		{
			$this->slim = (empty($slim_config) ? new \Slim\Slim() : new \Slim\Slim( $slim_args ) );
			$this->twig_config = $twig_config;
			self::$instance = &$this;
		}
	}
	
	public static function getInstance()
	{
		return self::$instance;
	}
	
	public function __call($name, $args = false)
	{
		if(method_exists($this->slim,$name)){
			if($args)
				return call_user_func_array( [$this->slim,$name] , $args);
			else
				return call_user_func( [$callable,$name] );
		}
	}
}

//your view controllers should extend this
class ViewController implements ViewInterface
{
	public $twig;
	function __construct()
	{
		$this->twig = new \Twig_Environment( new \Twig_Loader_Filesystem( (\FooBar\Application::getInstance())->twig_config['template_path'] ) );
	}
	
	public function render($template,$args)
	{
		echo $this->twig->loadTemplate($template)->render($args);
	}
}

interface ViewInterface
{
	public function render($template,$args);
}
```

**Comment by joelpittet** [comment]
Kohana has had a module for years too. https://github.com/tommcdo/kohana-twig
http://picocms.org/

**Comment by fabpot** [comment]
e375c9c
