### ISSUE TITLE
1.18.1 Release schedule

### ISSUE THREAD

**Issue by joelpittet** [twigphp/Twig#1672]
No pressure at all, I'm just curious where I can find a road map or a rough guideline to when releases are made.  There are some nice fixes in the upcoming 1.18.1 release that I'd love to get into Drupal 8 before the RC release if possible and have an issue open for such. 

We just bumped from 1.16.x to 1.18.0 at Drupal Dev Days last week(I was holding out but another patch snuck in). Drupalcon LA is in a month and RC is like around that or shortly after I'd expect.

I've not seen any critical issues in this queue that would need a rollback but the fixes in head for the upcoming release are appealing for stability:)  We can work around any feedback if we need to grab HEAD right before RC or whatnot.

**Comment by fabpot** [comment]
Done

**Comment by joelpittet** [comment]
Touché sir, thank you:)
