### ISSUE TITLE
{% include myVariable %} doesn't use __toString() method of my composite view name

### ISSUE THREAD

**Issue by jessegreathouse** [twigphp/Twig#1675]
In my twig template if I include another template like:

    {% include "MyBundle:Default:index-searchform.html.twig" with {form:form} %} 

it works fine.

But if I use a variable for the include path like this:

    {% include searchFormView with {form:form} %}

I get this error:

    Unable to find template "MyBundle:Default:index-searchform.html.twig" in     MyBundle::layout.html.twig at line 53.

searchFormView is a composite view name for AB testing that I expect should be used as a string with __toString()

    class CompositeViewName
    {
    ...
        /**
         * @return string
         */
        public function __toString()
        {
            $myStr  = $this->bundle . ':';
            $myStr .= $this->controller . ':';
            $myStr .= $this->action . '.';

            if (null !== $this->appMode) {
                $myStr .= $this->appMode . '.';
            }

            $myStr .= $this->composeVariation();

            $myStr .= $this->extension;

            return $myStr;
         }
    }

**Comment by stof** [comment]
What would be the expected template name in such case ?

**Comment by jessegreathouse** [comment]
I would expect that the template name would be "MyBundle:Default:index-searchform.html.twig"

**Comment by fabpot** [comment]
Closing as support should be done via StackOverflow.
