### ISSUE TITLE
array variable underscore symbol _ array.parent_id  work like array.parentid 

### ISSUE THREAD

**Issue by agrisvv** [twigphp/Twig#1676]
may someone knows, can't find in documentation..
do not work:
<td>{{ arr.parent_id }}</td>
works:
<td>{{ arr.parentid }}</td>

dump(arr):
 -id: 19
    -name: "Testa dokuments"
    -parent_id: 0
    -description: "Dokuments"
    -version: 1
   
symfony error end with:
throw new Twig_Error_Runtime(sprintf('Method "%s" for object "%s" does not exist', $item, get_class($object)), -1, $this->getTemplateName());

thanks.

**Comment by kamilsk** [comment]
http://stackoverflow.com/questions/20046324/twig-is-not-calling-getter-method-of-object-property

**Comment by kamilsk** [comment]
Helped?

**Comment by agrisvv** [comment]
hi! thanks for explained.. now understand how twig get variables.

**Comment by hason** [comment]
@agrisvv It looks like you expect the behavior of #1299.
