### ISSUE TITLE
Add Support To Require a Block Be Overwritten in Child 

### ISSUE THREAD

**Issue by warren5236** [twigphp/Twig#1680]
In my base template I define the title as a block:

    <title>{% block title %}Title Goes Here{% endblock %}</title>

I want to require that my child twig files override this block but there doesn't appear to be a way to do this.  This stackoverflow answer came up with a good solution but it's a little hacky: http://stackoverflow.com/a/29867080/4437

**Comment by fabpot** [comment]
There is indeed no way to make a block required.
