### ISSUE TITLE
Requiring the autoloader but Twig_Loader_Array still not found

### ISSUE THREAD

**Issue by JosephShering** [twigphp/Twig#1682]
I git cloned the master branch into my project and I'm manually requiring the Twig Autoloader.php file.

`require '../vendors/twig/lib/Twig/Autoloader.php';`

It finds the file fine but the Twig_Loader_Array is not found. How do I resolve this issue?

**Comment by stof** [comment]
have you registered the autoloader ? The file ``/lib/Twig/Autoloader.php`` contains the ``Twig_Autoloader`` class, but requiring the file does not register the autoloader automatically.

**Comment by kamilsk** [comment]
http://twig.sensiolabs.org/doc/intro.html

> If you are not using Composer, use the Twig built-in autoloader:
>
> require_once '/path/to/lib/Twig/Autoloader.php';
> Twig_Autoloader::register();

**Comment by ninsuo** [comment]
The `master` branch contains the Twig 2.x-dev version, which does not contain the Twig Loader anymore.

You have 2 solutions:
- Clone the `1.x` branch instead of the `master` branch
- Use this workaround: https://github.com/twigphp/Twig/issues/1646#issuecomment-78349076

**Comment by ninsuo** [comment]
does not contain the Twig built-in Autoloader* anymore
