### ISSUE TITLE
Twig_SimpleFunction with forbidden name

### ISSUE THREAD

**Issue by hodiizidor** [twigphp/Twig#1683]
I have created one Twig_SimpleFunction named date, I wasn't aware that there is already filter with same name available. 
On windows system it gave me no error and html page displayed normally, but on production system with linux it failed to render a page.
There was only PHP Fatal error:  Call to undefined method Twig_SimpleFunction::compile() in /var/www/home/.../Twig/Node/Expression/Call.php on line 27 which doesn't give any specific clue what is happening.

**Comment by ninsuo** [comment]
This is allowed to create a function that overwrites another one. This let you redefine functions as you like (for example, Symfony2's varDumper wasn't integrated immediately in Symfony2 so we overwritten `dump` filter).

Problem must be located somewhere else. Can you send us your `date` extension's implementation?

**Comment by fabpot** [comment]
Closing as there is no feedback.
