### ISSUE TITLE
Compile Error when block tag inside another tag without whitespace

### ISSUE THREAD

**Issue by philer** [twigphp/Twig#1685]
I tried removing as much whitespace as possible from some templates (via regex) and found some weird behaviour which I believe to be a bug.

As far as I can tell, if a template extends another one and defines a block inside another tag (e.g. an if), and there is no whitespace present, it'll throw an error.

**Example:**
`foo.twig` may be completely empty, it doesn't seem to matter
`foobar.twig` looks like this:
```twig
{% extends 'foo.twig' %}

{% if true %}
{% block foobar 'asdf' %}
{% endif %}
```
Note that there is no whitespace between the `if`, `block` and `endif` tags except for those two newlines. If I add *any* whitespace in between those tags, e.g. a space character or another newline, this error does *not* occur. This is why I call it a bug.
Also, if I remove those two newlines so I get everything in one line, I still get the error.
Error: **`An exception has been thrown during the compilation of a template ("Node "1" does not exist for Node "Twig_Node".") in "path/to/foobar.twig". `**

Using a different tag yields a slightly different error, for example `spaceless`:
```twig
{% extends 'foo.twig' %}

{% spaceless %}
{% block foobar 'asdf' %}
{% endspaceless %}
```
Error: **`An exception has been thrown during the compilation of a template ("Node "body" does not exist for Node "Twig_Node_Spaceless".") in "path/to/foobar.twig".`**

I haven't tried any other tags since very few make sense in this context (probably only `if`).

Tested on Twig v1.18.1 in a Laravel v4.2.17 project via @rcrowe's TwigBridge v0.6.1
Let me know if you need anything else.

**Comment by reFX-Mike** [comment]
Verified: http://twigfiddle.com/6wydib

**Comment by fabpot** [comment]
You cannot us a block tag inside an if statement or any other tag for that matter.

**Comment by reFX-Mike** [comment]
But when having whites space around it, it works just fine! So why this artificial limitation and why does it only occur if there is no white space?

**Comment by fabpot** [comment]
There is no artificial limitation, the code you reference is not valid; a block cannot be wrapped in another tag. We should probably throw an exception in this case though.

**Comment by philer** [comment]
But it works just fine, why would you want to prohibit it?
Here's something I've been using, which works just as you'd expect (except for the problem described above):
```Twig
{% if user.staffMember %}
    {% block init_script %}
        {{ parent() }}
        js.doSomething();
    {% endblock %}
{% endif %}
```

**Comment by SpacePossum** [comment]
Hi @philer,
It doesn't, please check: http://twigfiddle.com/v60y6l
The `{% if user.staffMember %}` will always be ignored.
(https://github.com/twigphp/Twig/issues/1639)

**Comment by stof** [comment]
@philer the block will always be defined, because it is defined at compile time while the condition is evaluated at render-time.

**Comment by philer** [comment]
Alright, I see. I guess I didn't even notice since it was just some javascript that didn't throw an error.
Since the premise of my issue is wrong I guess this can be closed.
Thank you for your help. :)

**Comment by stof** [comment]
@fabpot this issue should be closed

**Comment by SpacePossum** [comment]
What about @fabpot suggestion (https://github.com/twigphp/Twig/issues/1685#issuecomment-102837802)?
>We should probably throw an exception in this case though.

would be a nice DX helper, I just don't know how/if this can be done :)
