### ISSUE TITLE
Fatal error: Class 'Twig_Loader_Filesystem' not found

### ISSUE THREAD

**Issue by Renari** [twigphp/Twig#1688]
This is probably me being stupid but I can't seem to get this to work. I runs fine on my local machine. However once I upload it to a server the above error occurs. This would normally mean the Autoloader wasn't included but as you can see below it is, else there would be an earlier error thrown by require_once. 

```
require_once('twig/Autoloader.php');
Twig_Autoloader::register();
$loader = new Twig_Loader_Filesystem('templates');
```

**Comment by Renari** [comment]
Turns out this is because the twig directory has to have a capital T for it to include files correctly.

**Comment by stof** [comment]
hmm, I indeed missed that your path does not match the structure of the Twig project. Downloading only the content of the ``lib/Twig`` folder is not the expected way to install Twig

**Comment by gsi-fidel** [comment]
Simply put this in "application/config/config.php"

`$config['composer_autoload'] = 'vendor/autoload.php';`
