### ISSUE TITLE
Add attr filter to get object attribute

### ISSUE THREAD

**Issue by bocharsky-bw** [twigphp/Twig#1691]
What about to add builtin `attr` filter to get object attributes (array keys)?

Example of usage:
``` jinja
{{ object|attr("foo") }}
{# is the same behavior like: #}
{{ object.foo }}
```

It will be more convenient to get attribute name, stored in variable:
``` jinja
{% set bar = 'foo' %}
{{ object|attr(bar) }}
{# is the same behavior like: #}
{{ object.foo }}
```

It's seems like [attribute](http://twig.sensiolabs.org/doc/functions/attribute.html) function but a bit convenient to use.

**Comment by reFX-Mike** [comment]
Simply use

object[bar]

Twig will replace the 'bar' with its contents, which is 'foo' and thus read object.foo for you

**Comment by bocharsky-bw** [comment]
Thanks! It's look like `attr` filter is redundant in this case

**Comment by stof** [comment]
I don't see how the function would be more difficult to use than a filter. ``attribute(object, bar)`` is not harder than ``object|attr(bar)``. And a function better respects the Twig semantic.
