### ISSUE TITLE
Call an undefined method "compile" of class "Twig_SimpleFilter"

### ISSUE THREAD

**Issue by akovalyov** [twigphp/Twig#1694]
```Twig_Filter_Method``` is deprecated but if you try to reference ```Twig_SimpleFilter``` in your custom twig extension - you will get 
```
Attempted to call an undefined method named "compile" of class "Twig_SimpleFilter". 
```
Twig v1.18.1.

**Comment by stof** [comment]
All the Twig codebase is using the non-deprecated class without having such errors. Can you provide a reproducing code ?

**Comment by akovalyov** [comment]
@stof sorry, it was an (of course) mine wrong implementation.
