### ISSUE TITLE
Fatal error: Call to undefined function twig_lower_filter()

### ISSUE THREAD

**Issue by jlc75** [twigphp/Twig#1696]
Hello, 

I have a site that works for 6 months and no problem to get the message for an hour and all came back without doing anything. 

My host assures me that it not nothing achieved in maintenance. Then come the following message: 

Fatal error: Call to undefined function twig_lower_filter() in /cache/88/55/1796de9f69c013ac234e47bb95a0b7045c0f4c1833d92b725909c0a44b98.php on line 24

I'm on PHP 5.2

Thanks for your help.

Best regards,
Jerome.

**Comment by SpacePossum** [comment]
Hi,

Could you provide what version of Twig you are using and if you have `mbstring` installed?
(Did you update Twig around the time the error turned up?)
Maybe `mbstring` got disabled (by your host) but your templates are compiled when it was enabled and the compiled templates are still in the Twig cache. Maybe try to clear the Twig cache.

**Comment by jlc75** [comment]
Hi,

The host confirmed not have realized no maintenance and the mbstring PHP module is present and has been activated.

Twig concerning the version is 1.18.0.

A big thank you for your help.

Best regards,
Jerome.

**Comment by SpacePossum** [comment]
Thanks for the additional information. Did you try to clearing the Twig cache to see if that would help?

The odd thing is, `twig_lower_filter` is defined in `Core.php`;
https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Extension/Core.php#L1264

However this is only done and used if `mb_string` is loaded (https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Extension/Core.php#L1225)

So the only time I can think of this could fail is when you have compiled (cached) Twig templates when the `mb_string` module was enabled and later on it is was no longer.

(Are you running any custom/3rd party module that use the `twig_lower_filter`-function directly? They really shouldn't so I think not)

**Comment by jlc75** [comment]
Hi,

Since, the problem was solved all alone. However, I seek to understand how this problem arrived.

My shelterer ensures me that module PHP mb_string was not decontaminated.

It is an internal application.

The error message of origin:

Fatal error: Call to undefined function twig_lower_filter() in /****/****/html/******/cache/1796de9f69c013ac234e47bb95a0b7045c0f4c1833d92b725909c0a44b98.php on line 24

The line 24 in error is the following one in the sources:
 
$context["osd"] = (twig_lower_filter($this->env, $this->getAttribute($this->getAttribute((isset($context["img_bar"]) ? $context["img_bar"] : null), "options"), "osd")) == true);

Up to now, I did not have any problem.

I hope that all information above will help you to understand the problem.

Best regards,
Jerome.

**Comment by Tobion** [comment]
This is probably just a random PHP or APC bug. PHP 5.2 is very old and not maintained anymore.
Bug I think the `twig_upper_filter` and `twig_lower_filter` should also be defined in the twig core extension when `mbstring` is not installed (just as the other filters also have alternative implementations).

**Comment by fabpot** [comment]
I agree with @Tobion. I don't remember why there are not always defined.

**Comment by jlc75** [comment]
Hello everyone.

Thank you for your answers.

I just get a reply from my host who informed me of the origin of the problem : 

The extension folder commented, the system then that is returned by the PHP, without relative link (internally).

Thanks again. ;-))

Best regards,
Jerome LACROIX.
