### ISSUE TITLE
Alternate if statement qualifiers

### ISSUE THREAD

**Issue by bertoost** [twigphp/Twig#1698]
When you work with non-technical people, it's great to have a template language. You can use alternates like "is not" or "in" etc. but it would be nice to have more alternates for "==" and "!=" etc.
Same as Smarty has would be great;
http://www.smarty.net/docsv2/en/language.function.if.tpl

**Comment by sstok** [comment]
There is already http://twig.sensiolabs.org/doc/tests/sameas.html for `===` so having `equals` would make sense but its not supported in Jinja (on which Twig is based) so not if this will be accepted.

**Comment by SpacePossum** [comment]
```twig
{% set foo ='1' %}
{% set bar = [1] %}
{% set c = 2 %}

{% if test is defined and bar is iterable and foo not in bar and c is same as(b) and b is odd or c is even or c is divisible by(3) %}
    Hellow
{% endif %}
```

most of what you want is already in ;)
