### ISSUE TITLE
TWIG - Display recursive menu

### ISSUE THREAD

**Issue by mmlab78** [twigphp/Twig#1705]
Hello,
i'm a this scenario :

Routes :

```
/*view user profile */
$app->get('/view/:id',function($id)use($app){
	global $twig;
	$db = getConnection();
		$result = $db->query("SELECT * FROM users WHERE id='$id'");
		$recapiti = $db->query("SELECT * FROM users_recapiti WHERE ks_id_users='$id'"); 
		
		echo $twig->render('view_cliente.php',array('data' => $result, 'id' => $id, 'recapiti' => $recapiti'));
		unset($db);
	});
```
Template :

```
{% for user in data %}
// ... some code line ... //

{% for rec in recapiti %}      <!-- first filter -->
   {% if rec.tipo_recapito == 'cell_pers' %}
      {{ rec.recapito }}
  {% endif %}
{% endfor %}

// ... some code line .. //

{% for rec in recapiti %}      <!-- second filter -->
   {% if rec.tipo_recapito == 'fax' %}
      {{ rec.recapito }}
  {% endif %}
{% endfor %}

{% endfor %} <!-- end for data -->
```

Why the first filter display a result and the second not function ???

If change "fax" whit "cell_pers" in the second filter ... not function

The code is correct ?

thank you

**Comment by stof** [comment]
Can you fix your issue description to use the proper Markdown markup for code blocks ? It will be much more readable.

**Comment by mmlab78** [comment]
ok

**Comment by reFX-Mike** [comment]
Have you checked that "rec.tipo_recapito" ever contains "fax"? To me this seems completely unrelated to twig and a simply data-input error.

**Comment by mmlab78** [comment]
yesser contain "fax".

the {% for ...data in dates %} function fo only one time... It's normal, it's correct  ???

I tried this another code :
```
			{% for rec in recapiti %}
				{{ rec.tipo_recapito| raw}}
				{% if rec.num_recapito %}
					{% set R = rec.tipo_recapito %}
							
					{% for sub_rec in sub_recapiti if tipo_recapito = R %} <!-- second loop -->
						{{ num_recapito }}
					{% endfor % }
				{% endif %}	
			{% endfor %}	
```

but the second loop function for only one way ...

I have this result :  (example)

- Fax
000-1234
032-4453
- Mobile
- Mobile Office
- Phone
- Phone Office

But i need this result :


- Fax
000-1234
032-4453
- Mobile
333-123456
- Mobile Office
324-789258
357-361258
- Phone
077-56123
- Phone Office
058-12358

**Comment by mmlab78** [comment]
My table is :
![table](https://cloud.githubusercontent.com/assets/12159810/8019035/5c2a4354-0c3a-11e5-9a57-a0099f42d0bf.jpg)

**Comment by reFX-Mike** [comment]
There is a simple bug in your code.

```
{% for sub_rec in sub_recapiti if tipo_recapito = R %}
```

Should be

```
{% for sub_rec in recapiti if tipo_recapito = R %}
```

This is not a twig problem, but you using the wrong (non-existing) variable.

**Comment by mmlab78** [comment]
I have used another solution... i have created many db result for many type :-D

**Comment by fabpot** [comment]
Closing as support is giving through StackOverflow.
