### ISSUE TITLE
Display flash message

### ISSUE THREAD

**Issue by mmlab78** [twigphp/Twig#1709]
Hello,
i no display a flash message in my page... ehit twig and slim framework

i have this configuration :
```
// ... //
$app = new \Slim\Slim();

$app->add(new \Slim\Middleware\SessionCookie);
//...//
$app->map('/activate_cliente/:id',function($id)use($app){
		global $twig;
		$db = getConnection();
	 $app->flashNow('error', 'Login required');
		$result = $db->query("SELECT * FROM users WHERE id='$id'");
		echo $twig->render('activate_cliente.php', array('data' => $result));
	})->via('GET','POST');

```

In my template :
```
//...//
{{error}}
//...//
```

But i no display a flash message..

why ???

**Comment by stof** [comment]
Twig knows nothing about Slim flasg messages. I suggest you to contact the maintainers of the Twig integration in Slim (I don't know whether this integration is provided by the Slim team or by someone else)

**Comment by ninsuo** [comment]
I advise you to ask those kind of questions on Stackoverflow: http://stackoverflow.com/questions/tagged/twig for faster answers and non-twig-specific Q/A.

By the way, you should use `flash['error']` as stated in their [documentation](http://docs.slimframework.com/flash/now/).
