### ISSUE TITLE
json_encode out of date filter list?

### ISSUE THREAD

**Issue by r3wt** [twigphp/Twig#1710]
` The filter "JSON_HEX_TAG" does not exist in "location.globe.twig" at line 3`

```html

<script>
var places = '{{places|json_encode( JSON_HEX_QUOT | JSON_HEX_TAG )|raw}}';
</script>

```

**Comment by stof** [comment]
The issue is the way you build the bitmask for the filter. ``|`` is not the binary OR in Twig, and PHP constants cannot be used directly like that. The working template would be the following:

```html+jinja
<script>
var places = '{{places|json_encode( constant('JSON_HEX_QUOT') b-or constant('JSON_HEX_TAG') )|raw}}';
</script>
```
