### ISSUE TITLE
filter slice on SimpleXMLElement

### ISSUE THREAD

**Issue by stloc** [twigphp/Twig#1711]
we can't apply slice filter on SimpleXMLElement 

PHP Catchable fatal error:  Argument 1 passed to LimitIterator::__construct() must implement interface Iterator, instance of SimpleXMLElement given

the call : 
    {% for manifestation in manifestations|slice(0, 4) %}

**Comment by Tobion** [comment]
Already fixed in #1637. Please use the search before reporting issues.

**Comment by stloc** [comment]
if the problem is resolved, why I have this error ? 
I use twig/twig (v1.18.2)

**Comment by Tobion** [comment]
You might not have cleared your cache.

**Comment by Tobion** [comment]
Otherwise please provide a failing test case.

**Comment by stloc** [comment]
sorry...
ok after cache clear
