### ISSUE TITLE
TWIG - How to implement autocomplete in select input from database ?

### ISSUE THREAD

**Issue by mmlab78** [twigphp/Twig#1712]
Hello,
how to implement ad autocomplete select input from database in twig template ???

Like this :
http://www.bewebdeveloper.com/tutorial-about-autocomplete-using-php-mysql-and-jquery

Thank you

**Comment by stof** [comment]
This is not something you implement in Twig. the only part which can involved Twig is the rendering of a template to build the HTML. Anything else is outside the scope of Twig

**Comment by mmlab78** [comment]
whitout twig i can implement my question ???
I implement in my template...!!!

**Comment by fabpot** [comment]
@mmlab78 Can you use the mailing-list to ask for support (https://groups.google.com/forum/#!forum/twig-users)? You will have much more answers than here as we are only using Github for issues and feature requests. Thanks.
