### ISSUE TITLE
How to show content in previous location

### ISSUE THREAD

**Issue by emanuelbg** [twigphp/Twig#1716]
I have the Twig installed inside the folder **"test / blog"**. I want to show content that is within this blog folder in a file that is in **"test"**. How can I do it?

**Comment by stof** [comment]
I don't understand what you mean at all.

**Comment by emanuelbg** [comment]
I have the twig installed in a folder on the server "test / blog," and can
usually show the records on the home page within that directory. But I need
to show the records in a file that is in the previous directory, "test". How
can I do this? must install the twig in the "test" directory also? Or is
there any calls?

___
Att,
*Emanuel Barbosa Gonçalves*
Designer & Web Developer

<http://www.linkedin.com/in/emanuelbg>  <http://be.net/emanuelbg>
<https://www.facebook.com/emanuelbg>
<https://plus.google.com/+EmanuelBarbosaGonçalves>
<https://twitter.com/man3co0>

2015-06-23 13:51 GMT-03:00 Christophe Coevoet <notifications@github.com>:

**Comment by reFX-Mike** [comment]
I think you're in the wrong place. This is not support for twig. This is for bug reports and feature requests.
