### ISSUE TITLE
Docs translation

### ISSUE THREAD

**Issue by eberfreitas** [twigphp/Twig#1718]
Is there any intention to support the translation of docs on the repository level? I would love to translate it to portuguese. I know I can just go and do it on my own. Just wanna know if that is a thing. Thanks!

**Comment by fabpot** [comment]
Hi @eberfreitas Thanks for your proposal. You are indeed free to translate and update the docs for Portuguese, but I have no intention in hosting translations on the official websites as (from my experience) translations become stale pretty fast (this is a huge work to keep them in sync with the main docs), and I don't want to provide wrong docs for my users.
