### ISSUE TITLE
nl2br escaping not working

### ISSUE THREAD

**Issue by rslid** [twigphp/Twig#1719]
Hello,

It may be really simple problem but Im still not able to find out why the following code is not working. In my twig file I have defined {{ step.output|nl2br }} and in my functions I have used for example printf('The response time is: "%s" and it is in the range of "%s" \n ',$something,$anotherSomething);

My question is why in the HTML report \n is not being replaced by <br> ? Any ideas and sorry if the question is kinda stupid.

**Comment by ninsuo** [comment]
That's because \n is not interpreted as a newline between single quotes.
Use double-quotes instead: 
```php
printf("The response time is: \"%s\" and it is in the range of \"%s\" \n",$something,$anotherSomething);
```

**Comment by rslid** [comment]
As I thought it was stupid question... Thank you very much!
