### ISSUE TITLE
Allow including a partial outside blocks from child template

### ISSUE THREAD

**Issue by simohammedhttp** [twigphp/Twig#1733]
HI,

Wouldn't be nice if we can include a partial from a template that extends another one without putting it inside any block if the included partial doesn't output any content.

Think for instance of a partial that makes some logic in order to define some variables which will be used in many templates.

**Comment by simohammedhttp** [comment]
Another issue : 
Defined variables in included partial are not available in the original template.

**Comment by stof** [comment]
including a templated cannot define variables in the includer template, for 2 reasons:

- ``{% include %}`` is rendering the template and including its output
- Twig scoping rules are isolating scope for such case (btw, defining a variable inside a block won't make it available outside the block)
