### ISSUE TITLE
Add alias for the default filter

### ISSUE THREAD

**Issue by nuxwin** [twigphp/Twig#1735]
Hello ;

Since the default filter can be used a lot, it could be a good thing to add an alias such as d() at is done for the escape filter.

I known that we can do that easily in our code but...

Thanks.

**Comment by fabpot** [comment]
Yes, I will let you do that from your own code. Saving a few chars is not for Twig core. Twig tries to favor readiness over compactness. If not, we would not use the quite verbose `{{ }}` and `{% %}` delimiters.

**Comment by nuxwin** [comment]
@fabpot 

Following your sentence, you could so remove the e() alias... OUCH ... Whatever.
Thank anyway..

**Comment by fabpot** [comment]
agreed, it was a mistake.
