### ISSUE TITLE
Escape context detection

### ISSUE THREAD

**Issue by nuxwin** [twigphp/Twig#1736]
Hello,

I've read the documentation carrefully but I didn't find an answer to my question regarding context detection when auto-escape feature is enabled.

By default the auto-escape mode is set to html. However, for html attributes this escape method is not really good. Indeed, we should use the html_attr() escape method instead.

My question: When the auto-escape mode is set to html (default), does the compiler is able to auto-switch to the html_attr() escape method for html attributes?

The expected behavior:

```html
<h1>{{ view.title }}</h1>
<form>
...
<input type="text" name"firstname" value="{{ view.username }}">
...
</form>
```

Here, I would see the view.title variable escaped using the html escape method, while I would see the view.username variable to be escaped using the html_attr escape method. All this is about the context which could be detected at compile time (at least from my point of view). Regarding this, what is the current behavior?

Thanks you.

**Comment by Koc** [comment]
duplicates #472

**Comment by nuxwin** [comment]
@Koc 

Thanks but this doesn't answer me clearly...

**Comment by fabpot** [comment]
There is no context detection in Twig.

**Comment by nuxwin** [comment]
@fabpot 

And you're happy with this answer? To resume here, the auto-escaping feature, as currently implemented, is really bad because developer are forced to apply the html_attr() escape method manually on all dynamic html attribute values or adding the raw filter... Else, the values will be escaped using the html escape method which is bad.

Don't get me wrong here fabien, I'm happy with your template engine but it would really usefull to review this particular point. You're using a lexer and from my point of view could easily detect such exccape context at compile time, at least for the html attributes.

**Comment by fabpot** [comment]
@nuxwin Auto-escaping is very different from context-aware escaping. Also keep in mind that Twig is not just an engine for HTML, but for any other formats. Of course, I'm eagerly waiting for you pull request to see how you can "easily" do context-escaping in Twig. But before, read carefully the various links from the other issue talking about this very same topic, it can help you a lot.

**Comment by nuxwin** [comment]
I'll have a look at those links but please, don't get angry. You really react like a horse ...

Thanks anyway ;)
