### ISSUE TITLE
The date fliter can't work well

### ISSUE THREAD

**Issue by bohanyang** [twigphp/Twig#1737]
```
{{ "20150714"|date("Y/n/j") }}
```
This output "19700822" ?

**Comment by bohanyang** [comment]
OK. I've created a filter to fix this bug.
The title is "The date filter can't work well".
The word "fliter" is wrong.

**Comment by ninsuo** [comment]
You are giving your date as an unix timestamp (an integer), then 20150714 represents a number of seconds after 1970-01-01, so height months and twenty-two days.

Try with a valid date such as `{{ "2015-07-14"|date("Y/n/j") }}`: http://twigfiddle.com/c6lzn1
