### ISSUE TITLE
major bug - <a> tag within <a> tag weirdness!!!

### ISSUE THREAD

**Issue by hedgehog90** [twigphp/Twig#1738]
This is bizarre, can't understand how I'm the only one reporting this because I noticed it within a few minutes of using the thing. I've tested it extensively and come to the conclusion that it handles nested <a> tags within <a> tags incorrectly.
Example:

```
<li class="a">
	<a href="/">
		<ul class="d">
			<a class="asdads" href="#">123</a>
		</ul>
	</a>
</li>
```

will produce the mangled:

```
<li class="a">
	<a href="/">
		</a><ul class="d"><a href="/">
			</a><a class="asdads" href="#">123</a>
		</ul>
	
</li>
```

First, it closes the parent `<a>` tag immediately (it thinks I've made a mistake), then, when I get to the nested <a> tag, the parent has been cloned and inserted!

If I changed the `<a>` tags to `<b>` or any other tag it worked! so It seems it treats <a> tags in a special way.

Having nested `<a>` tags is not illegal syntax, so please fix this! I require Twig for my project and this completely stops progress, it's a site breaker, so the faster the better.

**Comment by fabpot** [comment]
That's not related to Twig as Twig does not change anything in your HTML code, it does not even parse it. So, it must come from something else.

**Comment by hedgehog90** [comment]
Could you please test the code above and confirm this?

**Comment by hedgehog90** [comment]
Ah, apologies. Worked out it's Chrome doing the mangling... great!

**Comment by ninsuo** [comment]
If you have doubts about what Twig does, [you can try it here](http://twigfiddle.com/w3qcd9).
