### ISSUE TITLE
Twig "raw" filter ignored in ternary operator

### ISSUE THREAD

**Issue by Kid-Binary** [twigphp/Twig#1739]
If you apply filter in ternary operator, like this:
`{{ ( entity.description ) ? entity.description|raw : 'entity.no_decription'|trans }}`
the "raw" filter will be ignored. If you just write as usual:
`{{ entity.description|raw }}`
all works well. Probably not a problem?

**Comment by ninsuo** [comment]
Hello,

I can't reproduce your issue: http://twigfiddle.com/0w4o63

Can you create a fiddle reproducing your case?

Thanks

**Comment by Kid-Binary** [comment]
Your fiddle is working as it should because there is no "trans" filter in "else". Unfortunately, I can't put "trans" in this fiddle, but yesterday I've found out that strange thing is actually happens this way:

`{{ ( entity.description ) ? entity.description|raw : 'No description' }}`

gives (in case when `entity.description` is not null) unescaped raw output as it should, but

`{{ ( entity.description ) ? entity.description|raw : 'entity.no_decription'|trans }}`

outputs **escaped** string with tags in it. "raw" filter is ignored if there is a "trans" filter in "else" condition body.

**Comment by fabpot** [comment]
see #1333

**Comment by fabpot** [comment]
Will finally be fixed by #2934
