### ISSUE TITLE
Template getAttribute() does not support hasser

### ISSUE THREAD

**Issue by garak** [twigphp/Twig#1750]
Using Twig with Symfony, I expected a support for hasser (just like in Symfony PropertyAccess component). Instead, Twig only supports getter and isser.

**Comment by fabpot** [comment]
It does support hasser via `is defined`.

**Comment by garak** [comment]
Sorry to reply to a closed issue, but I don't understand your reply.
My use case is for calling in Twig something like ``foo.bar``, where ``foo`` is a ``Foo`` object with ``hasBar`` property.
I can't see how ``is defined`` could help here...

**Comment by fabpot** [comment]
oops, I'm the one who did not understand the question, sorry. That's an oversight and be added if needed.

**Comment by xabbuh** [comment]
see #1969 for a patch
