### ISSUE TITLE
[PHP Extension] Array to string conversion issue

### ISSUE THREAD

**Issue by tkleinhakisa** [twigphp/Twig#1751]
Hello,

I've got a weird issue when using the twig php extension
I'm using twig inside symfony with doctrine, and the debug component

I have a conversation object with a messages property, the messages are oneToMany EXTRA LAZY association

The code that is not working is:
`{{ dump(conversation.getMessages.last) }}`

![image](https://cloud.githubusercontent.com/assets/1912952/9197693/d4d3577a-4036-11e5-8fb3-03ac6e7358b0.png)

If i disable the twig extension, the code works fine

A weird thing is that i don't get the error when xdebug is enabled ... only with the twig extension enabled and xdebug disabled

Here is the line from my twig cache where the error is located:
`echo $this->env->getExtension('dump')->dump($this->env, $context, twig_template_get_attributes($this, twig_template_get_attributes($this, (isset($context["conversation"]) ? $context["conversation"] : $this->getContext($context, "conversation")), "getMessages", array()), "last", array()));`

Let me know if you need more info

**Comment by stof** [comment]
can you show the output of ``phpversion('twig')`` (with the extension enabled) ?

**Comment by tkleinhakisa** [comment]
On my local machine:
php -r "echo phpversion('twig');"
1.18.0

On a remote server i'm using for tests (xdebug not installed):
php -r "echo phpversion('twig');"
1.19.0-DEV

both show the same issue

**Comment by stof** [comment]
Can you try with the latest version of the extension (1.19.0 for the stable release) ?

**Comment by tkleinhakisa** [comment]
Same behavior with 1.19.0 on my local debian with php 5.4.31 and remote amazon linux with php 5.6.9

**Comment by tkleinhakisa** [comment]
I made some more test using some simple stdClass and ArrayCollection and i don't have the issue so i guess this is somehow related to Doctrine lazy collections

**Comment by fabpot** [comment]
Closing as it seems not related to Doctrine. Feel free to reopen if can provide some code that exhibits the problem.
