### ISSUE TITLE
Provide a way to trigger deprecation warning in Twig

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#1756]
We should have a way to trigger deprecation warnings in compiled Twig code. The previous attempt in Symfony failed because many things are expressions in Twig, making it hard to bring a statement in.

A way to solve it may be to provide a function which could be used to trigger deprecations in expressions:

```php
function twig_deprecated($value, $message) {
    @trigger_error($message, E_USER_DEPRECATED);

    return $value;
}
```

A deprecated usage in an expression could then be wrapped into a call to this function. And we could have an optimization disabling deprecation calls in prod optionally (which would remove the wrapping node).
what do you think @fabpot ?

**Comment by fabpot** [comment]
I'm not sure we need something at runtime. I'm not sure, but I think we can do everything at compile time. If possible, that means that compiling all templates of a project would give you all deprecations in one go.

**Comment by fabpot** [comment]
see #1769

**Comment by greg0ire** [comment]
If I understand correctly, #1769 provides a way to deprecate filters. Still, it would be great to have a function so that we could do this :

```html+jinja
{% block 'my_legacy_block' %}
{% deprecate('This block is deprecated in favor of my_block') %}
{# do some stuff here #}
{% endblock 'my_legacy_block %}
```

Maybe this issue should be reopened?
