### ISSUE TITLE
Simplify Twig_Loader_Filesystem

### ISSUE THREAD

**Issue by tleb** [twigphp/Twig#1760]
I think the filesystem loader is too complex: it allows having multiple directories even though Twig_Loader_Chain is made to support such a case. Both behave in the same way: they try the first one then go on to the second one if the first one didn't have the required template.

Why does the filesystem loader manage this when we can have a chain loader which has multiple filesystem loaders?

**Comment by fabpot** [comment]
Because the chain loader adds some overhead but more importantly, having more than one directory to load from is a very common use case. The namespace feature would also not be easy to replicate with the chain loader.

**Comment by tleb** [comment]
I'm not sure why the namespace feature is implemented in the filesystem loader but not in the chain loader. Any specific reason?

**Comment by sstok** [comment]
Twig allows to load a Twig template from anywhere including a database, memory storage, etc. So it doesn't know anything of the concept of a "file".

The `Twig_LoaderInterface` provides a common interface for loading templates, but that would always leave you with one specific implementation (filesystem, database, etc).

So `Twig_Loader_Chain` allows to register multiple loaders, trying each one till one seas (yes, I know how to process this input) and returns the source of the template.
*The actual processing/loading logic is handled by the loader.*

`Twig_Loader_Filesystem` works with directories and actual files in the filesystem.
If you want to use a custom loader that loads templates from a database structure and want to also support namespaces that's perfectly possible.

The idea behind namespaces is that you can load templates from multiple locations, completely separated from each other (without having to hardcode there full locations, kind of like what hostnames are for IP addresses).

Have a look at http://docs.puli.io which is completely build on the idea of relative file-location loading.

**Comment by tleb** [comment]
Thank you, but I know all of this. What I mean is that, IMO, the loaders do not respect ATM the single responsability principle (S of SOLID). The Filesystem loader shouldn't manage different directory, it should only manage one. If someone wants to have multiple directories (this should mean different loaders), he should use the chain loader, which is made to use multiple loaders.

So, for me, the loaders should be like this:

The `Twig_Loader_Filesystem` should only manage a single directory, no namespace option.

The `Twig_Loader_Chain` should use the appropriate loader and include the namespace option. This would allow not only to have namespaced folders, but namespaced loaders.

This is just my opinion, of course.

**Comment by stof** [comment]
@tleb putting the handling of namespaces in the Twig_Loader_Chain would be wrong. It would mean putting some logic rewriting template names in Twig_Loader_Chain, while the Twig_Loader_Chain is purely asking all loaders in chain.
Each loader can decide how names it supports are looking like.

**Comment by Tobion** [comment]
Ideally the namespace feature would have been implemented a new loader using composition. This way it would not be tied to the filesystem.

**Comment by Tobion** [comment]
ref #772

**Comment by tleb** [comment]
+1 My biggest complaint is about the namespace feature being implementing into the Filesystem loader.
