### ISSUE TITLE
Make sure deprecations are triggered in 1.x for any deprecated features

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#1767]
We need deprecations in many places in 1.x for removed things:

- Twig_Environment constructor without loader
- Twig_Filter, Twig_Test and Twig_Function usage when registering them
- custom implementations of deprecated interfaces being passed (not sure if this is needed though, or if we consider that people would be warned about this by the DebugClassLoader of Symfony when using it)
- ... (the list needs to be completed)

We should also warn about features deprecated in templates, but this would require #1756 first

**Comment by fabpot** [comment]
see #1769
