### ISSUE TITLE
getFunctions() requires array Exception

### ISSUE THREAD

**Issue by ofbeaton** [twigphp/Twig#1774]
Whatever method calls `getFunctions()` on an `Twig_Extension` should enforce that it return an `array` by raising some kind of Exception. 

I spent several days scratching my head why `app/console twig:debug` was not showing my function only to realize that I was returning my `Twig_Simplefunction` directly instead of first putting it in an `array`. 

User error for sure, but one that Twig could give an error about instead of silently failing. The same can probably be said for `getFilters` or any similar method.

**Comment by stof** [comment]
Well, given that PHP 5.x does not support static typehints, this would require to implement checks in caller code, which is not a very maintainable solution (even though there is not so much callers in this case).
The common convention in most libraries is to assume that people implementing interfaces will respect the signature given in the phpdoc (it would be a pain to handle this in all calling places, as it would mean ignoring the contract of the interface, and adding overhead in all places using such a method).
Such mistakes in implementations are best checked by a static analysis tool (most IDEs have one, and [Scrutinizer](https://scrutinizer-ci.com/) also provides one)

**Comment by ofbeaton** [comment]
I don't deny that it is user error. Merely that it might be worth
investigsting and improving the user experience.

Tools like scrutinize require me to check in broken code, and are not good
solutions.

While I may just be misusing it, I find I often have to exclude my vendors
dir in php storm and lose type hints,  because not doing so makes the
search function near useless and slow. Never mind that many such ide have a
cost associated with them for most users.

If doing an is_array before using returned data from a 3rd party is
unreasonably prohibitive, perhaps a middle ground could be found?

For example, someone debugging their twig extension is bound to run
twig:debug. Could some common checks be made there so devs could spot
problems sooner?

Obviously you have to draw the line somewhere, and the fact I ran into this
and wasted days tracing through symfony code does not mean that it is
common. You'll have to make that valuation yourself.

**Comment by stof** [comment]
@ofbeaton enable the composer integration in PHPStorm and the vendor folder will be marked as a library path, meaning it is excluded from the search by default (by default, it does not search in the library path), but still used for typehints (there may be ways to mark paths as library paths without using the composer integration too, but I never looked for such feature as I'm fine with enabling the composer integration, which just requires to tell PhpStorm where your composer phar is and that you have a composer.json)
