### ISSUE TITLE
Macro imports with {% from %} should not rely on the context

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#1790]
currently, the `{% from %}` generates an internal variable in the context. But this means that using the macro is subject to context scoping, while the Twig compiler is not aware of it (leading to weird failure messages).

Here are 2 cases where it will break at runtime:
- recursive macros (yeah, my example is totally dumb. See the form panel of the Symfony profiler for a real-world use case)
- calling a block with a different context than the original one (harder to achieve, but I can provide a template triggering it if you want)

``` twig
{% from _self import recursive_macro %}

{{ recursive_macro(10) }}

{% macro recursive_macro(n) %}
    {% if n > 0 %}
        {{- recursive_macro(n - 1) -}}{# this breaks here #}
    {% endif %}
    {{ n }}
{% endmacro %}
```

currently, the failure looks like this:

```
An exception has been thrown during the rendering of a template 
("Notice: Undefined index: __internal_3fdeda406e109fab86e32799388d7e009376041033cede9a9e555c402985ed3b") 
in @WebProfiler/Collector/form.html.twig at line 437
```

In case the notice does not throw an exception, you then get a fatal error just after that because of calling `getrecursive_macro` on `null` (see https://github.com/twigphp/Twig/pull/1309 trying to fix it, but in a way which may degrade performance because it wraps all macro calls in runtime checks).

We should either detect such mistakes at compile time, relying on the knowledge that macros are not inheriting context, or we should change the way macro calls are compiled to avoid relying on the context (which would be possible in 2.0 thanks to the fact we could break BC on the fact that macros can be called through property access as reported in https://github.com/twigphp/Twig/issues/1217)

**Comment by stof** [comment]
Btw, the fact that macros imported with ``{% import %}`` are creating a variable with a name chosen by the template author can also create weird issues if the child and the parent template are both using the same name for their imported macros as it will overwrite the import (and so break things if the imported template is not the same)

**Comment by fabpot** [comment]
I might have an idea on how to "fix" this.

**Comment by stof** [comment]
@fabpot any news about your idea ?

**Comment by fabpot** [comment]
Not really. I've tagged all issues about macros some time ago. I think the whole macro system needs a careful rewrite in the 2.x series.

**Comment by ikvasnica** [comment]
I ran into a similar problem with macros **after updating from Twig 1.x to 2.1.0**.

**Before**, it was okay to use this syntax:
```
{% macro create_row(form, type) %}
    some magic
{% endmacro %}

{% block password_row %}
    {{ _self.create_row(form, 'password') }}
{% endblock %}
```

**After the update**, I needed to rewrite it like this:
```
{% block password_row %}
    {% from _self import create_row %}
    {{ create_row(form, 'password') }}
{% endblock %}
```

As I have multiple blocks like that I need to do the import stuff in each of them. When I put it outside, I get the weird __internal undefined index_ exception.

**Comment by szymach** [comment]
I have the same issue as @ikvasnica

**Comment by fabpot** [comment]
#3009 fixed the fatal error with an error message like "Unknown "recursive_macro" function...".
#3012 makes the code valid.
