### ISSUE TITLE
malformed behavior of merge

### ISSUE THREAD

**Issue by drmonty** [twigphp/Twig#1793]
I'm using twig 1.21.0 and want to use the `merge` filter, as described [here](http://twig.sensiolabs.org/doc/filters/merge.html) to replace already existent fields in an hash, with new values. The following usage should be supported, shouldn't it?:

```
{% set array, count = {}, 0 %}
{% set array = array|merge({ (count) : 0 }) %}
{% set array = array|merge({ '0' : 1 }) %}

count: {{ array|length }}<br />
items: {% for i in array %}{{ i }}, {% endfor %}
```

this will response the following:

```
count: 2
items: 0, 1
```

but I do expect the following:

```
count: 1
items: 1, 
```

**Comment by SpacePossum** [comment]
fiddle for this:
http://twigfiddle.com/1eo8k9

break down:
```
operation:
  set array, count = {}, 0 

result: 
  array:
    array (size=0) 
      empty
  count:
    int 0

operation: 
  array|merge({ (count) : 0 }:

result:
  array (size=1)
    0 => int 0

operation:
  array|merge({ '0' : 1 }):

result:  
  array (size=2)
    0 => int 0
    1 => int 1
```

minimized:

```twig
{% set array = {0 : 1} %}
{% set array2 = {0 : 5} %}
{% set array = array|merge(array2) %}
{{ dump(array) }}
```

result
```
array (size=2)
  0 => int 1
  1 => int 5
```

expected
```
array (size=2)
  0 => int 5
```

**Comment by drmonty** [comment]
@SpacePossum should be:

expected

```
array (size=1)
  0 => int 5
```

**Comment by jvasseur** [comment]
This is because in your first array, the key is a an int and in the second one a string, it's the php behavior for array_merge (https://3v4l.org/bi6pa).

Not sure if it is the role of twig to solve this kind of problem.

**Comment by drmonty** [comment]
@jvasseur well, it's the same with:

```
{% set array, count = {}, 0 %}
{% set array = array|merge({ ('' ~ count) : 0 }) %}
{% set array = array|merge({ '0' : 1 }) %}

count: {{ array|length }}<br />
items: {% for i in array %}{{ i }}, {% endfor %}
```

`'' ~ count` should convert the int to string, shouldn't it?

and also with:

```
{% set array, count = {}, '0' %}
{% set array = array|merge({ (count) : 0 }) %}
{% set array = array|merge({ '0' : 1 }) %}

count: {{ array|length }}<br />
items: {% for i in array %}{{ i }}, {% endfor %}
```

Don't know, what twig internal do with these vars...

**Comment by stof** [comment]
@drmonty PHP converts it back to an integer when using a numeric string as array key, considering it the same than an integer key (because PHP has no strict typing for variables)

**Comment by Tobion** [comment]
array_merge for numeric keys will make join them together and using different keys. If you want the "replace" behavior you need to use string keys. Please close this ticket.
