### ISSUE TITLE
Saving a value to be accessed later

### ISSUE THREAD

**Issue by abhibeckert** [twigphp/Twig#1798]
I'm new to twig and attempting to define this DSL:

    {% form action='login-submit' data=loginFormData %}
        {% field name='username' %}
    {% endform %}

The `loginFormData` value is an object with a "username" ivar, I want the `{% field %}` tag to generate an `<input>` tag with the value of that ivar.

So far I've got the form node saving $this a static var:

    public function compile(\Twig_Compiler $compiler)
    {
        if (self::$currentForm) {
            throw new exception('Cannot nest HTML <form> tags!');
        }
        self::$currentForm = $this;
    
        $compiler
            ->write("print '<form ...

And my Field node is able to access it:

    public function compile(\Twig_Compiler $compiler)
    {
        if (FormNode::$currentForm && FormNode::$currentForm->hasNode('data')) {
            $dataNode = FormNode::$currentForm->getNode('data');
            print_r($dataNode); exit;
        }
    }

Output:

    Twig_Node_Expression_Name Object
    (
        [specialVars:protected] => Array
            (
                [_self] => $this
                [_context] => $context
                [_charset] => $this->env->getCharset()
            )
    
        [nodes:protected] => Array
            (
            )
    
        [attributes:protected] => Array
            (
                [name] => loginData
                [is_defined_test] => 
                [ignore_strict_check] => 
                [always_defined] => 
            )
    
        [lineno:protected] => 7
        [tag:protected] => 
    )
    
But I'm not sure where to go next?

All the ivars are `protected`, so I can't see how to compile the `loginData` node into something like this:

    print twig_escape_filter($context['loginData']->username);

Any help with my project would be appreciated. The actual source code is here:

 * https://github.com/fierce/fierce/blob/master/classes/Tag/FieldNode.php
 * https://github.com/fierce/fierce/blob/master/classes/Tag/FormNode.php

**Comment by abhibeckert** [comment]
I got this to work with the following code:

      $dataNode = FormNode::$currentForm->getNode('data');
      
      $this->compiler
        ->write('$formData = ')
        ->subcompile($dataNode)
        ->raw(";\n")
      ;
      $this->compiler
        ->write('$fieldName = ')
        ->subcompile($this->getNode('name'))
        ->raw(";\n")
      ;
      
      $this->compiler
        ->write("print ' value=\"' . ")
      	->raw('(isset($formData->$fieldName) ? htmlspecialchars($formData->$fieldName) : "")')
      	->raw(" . '\"';\n")
      ;

Is that correct? Or is there a better approach?

**Comment by stof** [comment]
use ``$compiler->getVarName()`` to generate a random variable name rather than using ``formData``, to avoid issues with reusing it.

Regarding the implementation, you may want to reuse the Twig nodes to perform some output instead of doing some printing yourselves. This would give you the benefit of autoescaping.

**Comment by lyrixx** [comment]
IMHO it's not the reight approach:

You should not use tag to generate output.
Tag are meant to control the execution (if, for) and the rendering (raw, escape) of your content.
It's not meant to generate html.

For exemple, we replace the tag include by the function include.

More over, this make fragment overloading more complex. It will be complex to change how is rendered an input (for example).

So IMHO, you should create something with include or embed and compose everything with that.

You will gain in maintainability and in flexibility.
