### ISSUE TITLE
Escaper is br0ken after update to 1.21

### ISSUE THREAD

**Issue by mbretter** [twigphp/Twig#1799]
Hey,

after update of twig 1.21, Escaper throws this exception:
```
PHP message: PHP Fatal error:  Uncaught exception 'ErrorException' with message 'call_user_func() expects parameter 1 to be a valid callback, no array or string given'
 in httpdocs/vendor/twig/twig/lib/Twig/Extension/Escaper.php:95
Stack trace:
#0 [internal function]: Slim\Slim::handleErrors(2, 'call_user_func(...', '/var/www/vhosts...', 95, Array)
#1 httpdocs/vendor/twig/twig/lib/Twig/Extension/Escaper.php(95): call_user_func(NULL, 'includes/inline...')
#2 httpdocs/vendor/twig/twig/lib/Twig/NodeVisitor/Escaper.php(37): Twig_Extension_Escaper->getDefaultStrategy('includes/inline...')
#3 httpdocs/vendor/twig/twig/lib/Twig/BaseNodeVisitor.php(28): Twig_NodeVisitor_Escaper->doEnterNode(Object(Twig_Node_Module), Object(Twig_Environment))
#4 httpdocs/vendor/twig/twig/lib/Twig/NodeTraverser.php(77): Twig_B" while reading response header from upstream
```
it looks like this error happens if default strategy is null for a file, changing

    if (!is_string($this->defaultStrategy) && false !== $this->defaultStrategy ) {

to

    if (!is_string($this->defaultStrategy) && false !== $this->defaultStrategy && null !== $this->defaultStrategy) {

fixes the problem.

**Comment by fabpot** [comment]
ping @Tobion

**Comment by stof** [comment]
``null`` is an invalid autoescaping strategy. So it looks weird to have it working in Twig 1.20 (the error would indeed appear only at runtime with weird issues instead of being at configuration time).
The "fix" you are proposing does not make null supported. It just moves the issue at runtime by accepting an invalid strategy value before.

**Comment by Tobion** [comment]
@mbretter can you debug where the `null` autoescaping strategy comes from?

**Comment by mbretter** [comment]
ok I have found the problem, the autoescape option was accidentally set to null, instead of false

**Comment by stof** [comment]
@Tobion @fabpot we might want to trigger an exception for invalid input instead of letting PHP trigger an error in call_user_func. It might be easier to understand for people setting an invalid value. What do you think ?
