### ISSUE TITLE
left/right trim

### ISSUE THREAD

**Issue by abhibeckert** [twigphp/Twig#1802]
When the `trim` filter was added, there was some discussion about extending it to include `ltrim`/`rtrim` functionality: https://github.com/twigphp/Twig/pull/662

Should this be done? I think so, in particular when working with `<a href>` tags I often need to trim a leading slash.

If I do submit a pull request adding this to twig, what syntax should I go with?
- `<a href="{{ foo|trim('/', 'left') }}">`
- `<a href="{{ foo|ltrim('/') }}">`
- `<a href="{{ foo|left_trim('/') }}">`

**Comment by ninsuo** [comment]
`ltrim` and `rtrim` seems easier to use IMO

But to avoid adding too much filters in Twig Core, those may be implemented in the [Text extension](http://twig.sensiolabs.org/doc/extensions/text.html).

**Comment by fabpot** [comment]
As this can be done easily outside of core and because not that many people ask for this, I'm closing this feature request.

**Comment by fabpot** [comment]
Thinking again, back when we introduced the trim filter, we didn't have the named parameters, which is now the case, so adding a way to only trim on the left or on the right might be easier to include in the existing trim filter.

**Comment by antonydandrea** [comment]
I would really like to contribute some code to this project, can I have a go at implementing this?

**Comment by ninsuo** [comment]
Everybody is welcome to contribute, don't ask for permission 😄

**Comment by antonydandrea** [comment]
Just didn't want to step on any toes of someone was already working on it

**Comment by antonydandrea** [comment]
Is there a reason why we would want them as parameters of trim rather than introducing rtrim and ltrim filters?

**Comment by antonydandrea** [comment]
Ok, I have done a pull request #2403
