### ISSUE TITLE
private runtimeInitialized property in Twig_Environment is a barrier to overriding loadTemplate()

### ISSUE THREAD

**Issue by Cottser** [twigphp/Twig#1811]
This issue is for 2.x. Coming from https://www.drupal.org/node/2555243.

Drupal 8 extends `Twig_Environment`, and because the `runtimeInitialized` property is now private in 2.x our override of `loadTemplate()` no longer works.

I think we need to either add a getter or make it protected. Once there is a clear path forward I'm happy to submit a PR.

This looks to be the only barrier to our upgrading to Twig 2.x as we near RC1 that is outside of our control. This was changed in #1773.

**Comment by fabpot** [comment]
#1812 should fix your issue and allow Drupal to stop copy/pasting some Twig code, which is always a good thing.

**Comment by Cottser** [comment]
@fabpot first of all, thanks for all the help with this.

This is still proving to be an issue in Drupal 8, the cache class implementation does not allow us the protection from the race condition where load() == TRUE but then the storage goes away.

See around https://www.drupal.org/node/2568171#comment-10337391 for some comments.

In short I think we still need to override loadTemplate() in Drupal 8 to add the eval() if the storage fails.

If you can think of another way that loadTemplate() and Twig_CacheInterface could be implemented to support this of course that would be great but if it's not a common use case then just allowing us to override loadTemplate() might be for the best.

**Comment by Cottser** [comment]
I may submit a PR to add another method to the cache interface under the assumption that what we're trying to do is a somewhat common use case. Stay tuned.

**Comment by fabpot** [comment]
@Cottser twigphp/Twig#1840 is now merged. Does it cover everything now? Or do you still have issue on the Drupal side?

**Comment by Cottser** [comment]
@fabpot looks great now and I think we can now be fully Twig 2.x compatible, that's what I'm focussing on today at DrupalCon :)

Thanks!

**Comment by Cottser** [comment]
@fabpot just so you know you can see at the top of https://www.drupal.org/node/2555243 what our roadmap looks like for getting ready for 2.x at this point. If you feel like it's the right time to cut 1.22.2 that would be very helpful for Drupal.

At https://www.drupal.org/node/2568181#comment-10355611 there are a couple patches which are passing on our newer test infrastructure (old test infrastructure is pretty blocked up ATM). One patch is for 1.x and for 2.x, the only difference between the two is the actual Twig library update and the 2.x patch effectively has the first patch from https://www.drupal.org/node/2571817#comment-10351435 applied.
