### ISSUE TITLE
Commit c7e9744ca8396c48e5bfeb72b9314ef8f7c4f55e breaks with templates containing XML

### ISSUE THREAD

**Issue by xhaleera** [twigphp/Twig#1814]
Commit c7e9744ca8396c48e5bfeb72b9314ef8f7c4f55e is buggy.

If the compiled template contains an XML file and includes `<?xml version="1.0" encoding="UTF-8"?>`, the closing `?>` will be interpreted by PHP as a closing tag.
Then following commented source lines will be considered outside of PHP source scope, then echoed to the browser, breaking XML parsing.

**Comment by nicolas-grekas** [comment]
Fixed in #1813
