### ISSUE TITLE
Twig_Null_Cache is oddly implemented

### ISSUE THREAD

**Issue by dawehner** [twigphp/Twig#1832]
https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Cache/Null.php uses write() to load the template and load() then just does nothing.

This is kinda problematic if you think about implementing a generic chain of cache backends. There you ideally want to iterate over all of them on write() and just dump the content.

What about adding a hashmap in write() and using that to load the compiled filein load()

**Comment by fabpot** [comment]
Can you have a look at #1833?

**Comment by dawehner** [comment]
Thanks again

On Wed, Sep 16, 2015 at 10:32 AM, Fabien Potencier <notifications@github.com
