### ISSUE TITLE
Lowercase Ante meridiem and Post meridiem not working when using space in date filter

### ISSUE THREAD

**Issue by bkmorse** [twigphp/Twig#1834]
The normal distinction between `a` and `A` isn't there.

I noticed for the date filter, date('g:i a'), this produces a uppercase AM/PM, but if I remove the space between i and a, date('g:ia') it displays it as lowercase am/pm. Is this a bug? I want it to display with a space between the minute and am/pm, in lowercase.

**Comment by SpacePossum** [comment]
Hi,
What version of Twig are you using? I put a little fiddle together but was not able to reproduce the problem; http://twigfiddle.com/99q6rx

**Comment by bkmorse** [comment]
Twig 1.20.0 - using it in the craftcms.

**Comment by stof** [comment]
Works on Twig 1.20 too on twifiddle. I guess we would need more info about your PHP version.

**Comment by reFX-Mike** [comment]
Sounds to me some post-processing is capitalizing strings after a space...

**Comment by reFX-Mike** [comment]
BTW, I meant the fault lies within the code of @bkmorse

**Comment by bkmorse** [comment]
Close this, Twig 1.2 is being used within Craft CMS https://buildwithcraft.com/

I'll open a ticket with them, thanks.
