### ISSUE TITLE
Race condition in `Environment::loadTemplate`

### ISSUE THREAD

**Issue by znerol** [twigphp/Twig#1836]
The `Environment::loadTemplate` currently is subject of a race condition. It can be reproduced with the following steps:

* Set a breakpoint in `Environment::loadTemplate` at the top of the `!class_exists($cls, false)` branch.
* Step through until the `$this->cache->load($key);` call.
* Remove the on-disk cache (`rm -r app/cache/twig')
* Continue the debugger

This will result in the following fatal error:

    Compile Error: Twig_Cache_Filesystem::load(): Failed opening required '[...]/app/cache/dev/twig/4/5/451[...].php' (include_path='[...]')

The problem is that between `$this->cache->has($key)` and `$this->cache->load($key)` anything can happen.

Proposed solution: Remove `has()` and instead try to `load()` the class directly from the cache. If the class still does not exist after that, compile the template and write it to the cache and then `eval()` the generated source directly.

**Comment by Cottser** [comment]
I guess implicit in this proposal is that load() on the cache interface would return a boolean, currently it doesn't return anything.

**Comment by Cottser** [comment]
Nevermind that, I looked at the PR.

**Comment by znerol** [comment]
Updated the summary.
