### ISSUE TITLE
Introduce join accessor parameter

### ISSUE THREAD

**Issue by Rvanlaak** [twigphp/Twig#1847]
`join` is great to quickly show the content of collections. Usually implementing `__toString` is enough to change the field (or group of fields) that is shown.

We have a scenario where `__toString` is used for all FormTypes, and would like to access another parameter. What about introducing an extra parameter to define that accessor, to prevent we need to make a loop.

```twig
{{ parent.children|join(', ', 'address.country') }}
```
This now can be accomplished using the following snippet, but could be a bit more clear:

```twig
{% for child in parent.children %}{{ loop.index0 ? ', ' }}{{ child.address.country }}{% endfor %}
```

**Comment by Tobion** [comment]
This looks like you actually want to just expose `array_map` as a twig function. Join and property retrieval are unrelated things.

**Comment by Rvanlaak** [comment]
You're correct, in order to prevent the introduction of a new filter it did seem logical to me that this could be an optional parameter for `join`. That way the usage of `loop` could be circumvented.

**Comment by stof** [comment]
I don't think this belongs to the ``join`` filter. It would mix responsibility on this filter, which seems a bad idea (and it would require either a dependency on the PropertyAccess component of a reimplementation of the same feature to fit your use case, which is a no-go for Twig IMO).

**Comment by Rvanlaak** [comment]
:+1:

**Comment by henrikbjorn** [comment]
wouldnt this be a `pick` filter instead?
