### ISSUE TITLE
Twig compilation cache - attempting to stat non-existent file?

### ISSUE THREAD

**Issue by domhnallw** [twigphp/Twig#1848]
Hi folks:
I've discovered I'm having inconsistent template loading issues with Twig that seem to have happened after version 1.21.2.

We're currently using the following versions, pulled from composer this morning:
 * Twig 1.22.2
 * Twig-extensions 1.3

Server is Ubuntu 14.04 64-bit, running PHP 5.5.29 on Apache 2.4.16

Basically, the problem I'm having is that some templates compile and render just fine, while some just don't. One of my colleagues here just tested his prior to updating from 1.21.2 - worked fine before, and now it doesn't. The messages we get look like this:

```
Got error 'PHP message: PHP Fatal error:  Uncaught exception 'ErrorException' with message 'filemtime(): stat failed for /var/www/html/myapp/compilation_cache/c/0/c0c28c5396c42cf220b237b791a9a8305de55491371ddf034ed61fd60cf4c158.php' in /var/www/html/myapp/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:90
```

In this case, the compiled template file mentioned in the error message does not exist (though the source template definitely does, and loads and renders just fine with Twig 1.21.2). At the point that this error occurs, two other templates have been loaded and rendered without issue.

I can delete the cache folder (`/myapp/compilation_cache`) and Twig can recreate it and the first two templates get compiled, saved into this folder, and ultimately render on-screen just fine, so the file/folder permissions seem to be fine. It still stumbles on this third template (and several others), which are very very plain - no `import`s, no `include`s, no `macro`s, no `use`s, or anything like that. Yet. :)

I don't know if I'm doing something stupid or not but since this problem only occurs in very recent version(s), so I thought I'd log it as an issue to see if it's happening to anyone else.

**Comment by fabpot** [comment]
ping @Tobion Isn't it related to the removal of `clearcache`?

**Comment by domhnallw** [comment]
I can add that before updating Twig, that there was a compiled copy of the now "broken" template in the compilation cache folder which rendered fine, but I did spot from the error logs that the derived hash that Twig was using to try to find the previously-compiled file had changed (because the file it was looking for now didn't exist - and yes, this is before I deleted the cache folder :) ), which I presume is related to "changed template cache names to take into account enabled extensions" in the changelog for 1.22.0?

**Comment by Tobion** [comment]
@fabpot I don't think it's related to #1843. Otherwise the error would be different.

It looks like the PHP warning is not correctly silenced in https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Cache/Filesystem.php#L90 . I already used the new race-condition free caching appraoch from #1840 and had no problem. The only "annoying" thing I noticed is, when you remove the cache and then run your app, all those non-existing template caches are reported as "silenced errors" from the symfony profiler whenever the template cache doesn't exist yet.

**Comment by Tobion** [comment]
@domhnallw what error handler are you using? Maybe it is buggy and throws exceptions on silenced warnings. And if it's symfonys error handler, which version?

**Comment by domhnallw** [comment]
@Tobion I'm not running that with an error handler, because to be honest I haven't needed to, it's "just worked". The path to the source template is checked before it's passed to Twig, but I'm not running exception handling on that stuff because it's never needed it before (and frankly, if bits of the UI go missing that's bad no matter what...)

**Comment by Tobion** [comment]
You are using a error handler otherwise the warning would not be transformed to `ErrorException` as your message says.

**Comment by domhnallw** [comment]
Unless it's xdebug I have no idea. There's no exception handler in my code.

**Comment by stof** [comment]
@domhnallw do you have ``xdebug.scream`` in your configuration ? If yes, this is the culprit. Such setting should die though, because this is its behavior:

- it disables the behavior of the silencing operator
- it disables exception catching (``try { } catch { }`` will not catch anymore).

**Comment by stof** [comment]
the other solution is that you have an error handler not compatible with the silencing operator (i.e. not checking ``error_reporting()`` when being called)

**Comment by domhnallw** [comment]
@stof I don't have any error handlers enabled (except xdebug seems to be doing so). And `xdebug.scream` is set to "Off". My colleague has no error handlers of any kind installed, his installation is a stock WAMP setup. No xdebug, nothing.

**Comment by domhnallw** [comment]
Anyone else have any ideas? This is a bit of problem for us and I'd like to at least understand it.

The presence or absence of xdebug doesn't seem to matter, and we don't believe there is an error handler enabled on my colleague's setup (he's using a stock XAMPP setup on Windows).

I'm using an Ubuntu 14.04 64-bit Vagrant VM generated by [PuPHPet](https://puphpet.com/) with most of the defaults enabled, including xdebug). Everything is up-to-date (barring perhaps that we're running PHP 5.5 rather than a later version)

At the end of the day, we're both still getting exactly the same problem. Reverting back to Twig 1.21.2 causes the problem to go away for both of us, so whatever has changed has been introduced since then. All advice gratefully received.

**Comment by Tobion** [comment]
Just debug your error handler and see why it transforms to an exception. See also #1850 who also used a buggy error handler.

**Comment by domhnallw** [comment]
@Tobion just found it in the most unexpected of places. Thank you !

**Comment by Tobion** [comment]
So what was the problem?

**Comment by domhnallw** [comment]
I had used `set_error_handler()` in another file that was being autoloaded by the pages that were having the problem, but I hadn't used `restore_error_handler()` to restore normal operation - I guess I assumed that the error handler would go out of scope or something. Feel a bit silly now :(

**Comment by tuanquynh0508** [comment]
Twig call some file not existed. Function getTimestamp in file vendor/twig/twig/lib/Twig/Cache/Filesystem.php bester like?.

```
/**
     * {@inheritdoc}
     */
    public function getTimestamp($key)
    {
        if(file_exists($key)) {
            return (int) @filemtime($key);
        }
    }
```
