### ISSUE TITLE
Render Content without Layout ?

### ISSUE THREAD

**Issue by daslicht** [twigphp/Twig#1853]
Hello,
is there a way to render the content without layout ?
Cheers Marc

**Comment by stof** [comment]
There is no concept of content and of layout in Twig. There is only the concept of templates.

If you want to be able to render only a part of the page, there is a solution: create a dedicated template rendering this (so without layout). And then, when rendering the full page with layout, use ``{{ include() }}`` to reuse the previous template (to avoid duplication)

**Comment by ninsuo** [comment]
If you mean "without file", you can have a look at Wooter J's answer on Stackoverflow:
http://stackoverflow.com/a/31082808/731138

**Comment by daslicht** [comment]
Ok fine, Thank you !
