### ISSUE TITLE
Attribute Support in Macros

### ISSUE THREAD

**Issue by srsgores** [twigphp/Twig#1856]
I would like to see *overloaded* attribute support in macros:

```
{% macro definitionItem(term, value) %}
	{% if term and definition %}
		<dt>
			{{ term }}
		</dt>
		<dd {{ attributes }}>
			{{ definition }}
		</dd>
	{% endif %}
{% endmacro %}
```

Where instead of passing an inline array of attributes, the attributes can be specified in a template like so:

```
{{ definitionItem("user", "srsgores")(class="github-user") }}
```

Which would result in:

```
<dt>srsgores</dt>
<dd class="github-user">srsgores</dd>
```

[Jade has this feature](http://jade-lang.com/reference/mixins/), and it makes macros (what they call *mixins* very versatile).

**Comment by stof** [comment]
Well, in Jade, the parameters still end up as an array inside the macro, not as a string, AFAICT from reading their doc. So ``{{ attributes }}`` would not work.
The feature you describe here is *not* the feature described in the Jade doc you are linking.

**Comment by srsgores** [comment]
@stof, very well.  Can you describe an alternative approach to achieving this right now?

**Comment by stof** [comment]
Well, to get attributes inside the class, my solution would be to use an array argument:

```twig
{{ definitionItem("user", "srsgores", {class:"github-user"}) }}
```

This will give you an ``attributes`` array (or whatever name you use in your macro signature) in the macro, similar to what is there in Jade (except for the auto-escaping things, because it does not work on macro calls in Twig, but on display)

**Comment by srsgores** [comment]
@stof, inside the macro, how would I dynamically assign attributes to the element?

**Comment by stof** [comment]
use a for loop (which is probably what is done inside the ``a()`` macro in the case of Jade)

**Comment by fabpot** [comment]
Closing as there is no more activity here.
