### ISSUE TITLE
Array to string conversion Exception when joining Twig array

### ISSUE THREAD

**Issue by Rvanlaak** [twigphp/Twig#1859]
Twig allows to define an array by making a range:

```js
[1..8]
// or
[1..variable]
```
This is really great, because I needed a joined array for a `DataTables` column definition:
```js
$("table").DataTable({
    paging: false,
    searching: false,
    // ...
    columnDefs: [
        { orderSequence: [ "desc", "asc" ], "targets": [1, 2, 3, 4, 5, 6, 7, 8] }
    ]
});
```
We did expect Twig to allow us joining this array a bit easier, that way we also could make the number of columns variable. A `join` on an array definition should be able to help:

```js
// ...
{ orderSequence: [ "desc", "asc" ], "targets": [{{ [1..8]|join(', ') }}] }
// ...
```
This will result in the following exception:

> An exception has been thrown during the rendering of a template ("Notice: Array to string conversion")

After dumping `[1..8]`, it seems the newly defined array actually is located on key 0. The `join` filter does not take that into account. This was fixed by joining that key:

```js
// ...
{ orderSequence: [ "desc", "asc" ], "targets": [{{ [1..8][0]|join(', ') }}] }
// ...
```
Twig version: `v1.21.1`

**Comment by jvasseur** [comment]
You don't need the ```[]``` to create a range in twig 1..8 will create the [1, 2, 3, 4, 5, 6, 7, 8] array.

That's why you get your range as the only element of an array.

**Comment by apfelbox** [comment]
Just to visualize what @jvasseur said:

```
1..8 === [1, 2, 3, 4, 5, 6, 7, 8]
[1..8] === [[1, 2, 3, 4, 5, 6, 7, 8]]
```

**Comment by Rvanlaak** [comment]
Damn, based the syntax of the operator on the way how it was [documented on the `join` page](http://twig.sensiolabs.org/doc/filters/join.html) instead of looking at [the operator documentation](http://twig.sensiolabs.org/doc/templates.html#other-operators). Quite confusing :+1:

**Comment by stof** [comment]
Well, the join page does not use this operator. It defines an array inline, in which case the syntax is right.

**Comment by Rvanlaak** [comment]
Actually, the following results into exactly the same error:

    {{ 0..9|join(', ') }}

Where the following does work:

    {{ (0..9)|join(', ') }}

**Comment by jvasseur** [comment]
The first syntax doesn't work because the range operator has less precedence than filter uses, it has nothing to do with the join filter.

**Comment by Rvanlaak** [comment]
thanks @jvasseur , found the precedence of `..` being lower than `|` :+1: 

> The operator precedence is as follows, with the lowest-precedence operators listed first: b-and, b-xor, b-or, or, and, ==, !=, <, >, >=, <=, in, matches, starts with, ends with, .., +, -, ~, *, /, //, %, is, **, |, [], and .:

http://twig.sensiolabs.org/doc/templates.html#expressions

So none of the filters will work with the range operator that way. Can you give me a scenario where and why this isn't preferable?

**Comment by stof** [comment]
The same is true for many other operators (the precedence of ``|`` was chosen badly IMO):

```twig
{{ 'foo' ~ 'bar'|upper }}
```

will output ``fooBAR`` (which is actually the reason why spaces around operators are recommended in the Twig coding standards, except for the filter operator)

**Comment by jvasseur** [comment]
The current way can still be useful in some cases:
```..``` needs to have a less precedence than ```+``` and ```-``` to do things like ```var..var + 5``` (it doesn't make sense the over way).
And ```|``` having more precedence than ```+``` and ```-``` can be useful for some filters (abs, length).

**Comment by Rvanlaak** [comment]
Thanks, that also explains why it does just work in the `{% for %}` loop. Based on the way we use it over there I expected it to work similar for the filters. :+1: 

Don't think the precedence for ` | ` is going to changes, but in my opinion in the following:

    var-1..var+1|join(',')

the ` .. ` should have precedence over ` | `, but indeed not over ` + ` and ` - `.
