### ISSUE TITLE
Add is_numeric() function to check if variable is numeric

### ISSUE THREAD

**Issue by bertoost** [twigphp/Twig#1861]
Title says enough I guess ;-)
Currently using this simple registered function

```
new \Twig_SimpleFunction('is_numeric', function ($str) {
    return is_numeric($str);
})
```

**Comment by stof** [comment]
this should not be a function. It should be a test if you want to add it (making it look like ``foobar is numeric``.

However, what is the use case for having it. I'm not sure it belongs to the core

**Comment by bertoost** [comment]
A test would be great indeed. Didn't thought about that.

A use case...
I am getting data through some API's and sometimes a specific value is a numeric ID instead of a text string. But when numeric, I don't want to show it, or show something as "Unknown".

**Comment by SpacePossum** [comment]
( @bertoost you can check here (for a sample implementation) https://github.com/GeckoPackages/Twig , disclaimer I wrote it)

**Comment by fabpot** [comment]
Closing as it won't be added in Twig core, Adding it in an extension is easy enough though.

**Comment by alexislefebvre** [comment]
You can find an implementation here: https://stackoverflow.com/a/52946699/2257664
