### ISSUE TITLE
Get variable variables in Twig

### ISSUE THREAD

**Issue by dvladimirov77** [twigphp/Twig#1862]
How to get the contents of the variable variables?

in conttoller: $name_1 = "title1"
in template: {% set var = `name_` ~ id_point %}

Php analogue: $$var

Thanks.

**Comment by henrikbjorn** [comment]
You dont.

**Comment by dvladimirov77** [comment]
it's impossible?

**Comment by sstok** [comment]
You can use an array with a dynamic key, using dynamic names for a variable in Twig is a horrible idea.
Having something like var1, var2 is a good indication your are not using the right technique.

**Comment by ninsuo** [comment]
I dislike the "Impossible" word, you can of course, even if that's not recommanded.

```jinja
{{ _context['myVar' ~ suffix] }}
```

**Comment by dvladimirov77** [comment]
Thank you, I understand that this is a bad way.
Unfortunately it is very difficult to alter.
