### ISSUE TITLE
Same vatiable in twig template has false value at some point in the template then true inside a script

### ISSUE THREAD

**Issue by NadjibBELLOUNDJA** [twigphp/Twig#1865]
Hi,

So basically, here is my problem.

My controller "viewSessionAction" in Symfony renders a template "view-session.php.twig", with a variable called "session" (do not mistake with the navigator session, my own entity's name is Session also). So here is a view of my controller:

```
    public function viewSessionAction(Request $request, $slug)
    {
        $sessionRepository = $this->getDoctrine()->getRepository("ATPlatformBundle:Session");
        $session = $sessionRepository->findOneBySlug($slug);
        if (!$session)
            throw $this->createNotFoundException("La session n'existe pas");

        return $this->render("ATPlatformBundle:Session:view_session.php.twig", array(
            'session' => $session
        ));
    }

```

The passed session entity "Session" is not empty (I have dumped it) and has two attributes "closed" and "canceled" both set to false, as you can see in the excerpt below (with their getters and setters):

```
    /**
     * @ORM\Column(name="closed", type="boolean", nullable=false)
    */
    private $closed;

    /**
     * @ORM\Column(name="canceled", type="boolean", nullable=false)
    */
    private $canceled;

    /**
     * Set closed
     *
     * @param boolean $closed
     *
     * @return Session
     */
    public function setClosed($closed)
    {
        $this->closed = $closed;

        return $this;
    }

    /**
     * Get closed
     *
     * @return boolean
     */
    public function getClosed()
    {
        return $this->closed;
    }

    /**
     * Set canceled
     *
     * @param boolean $canceled
     *
     * @return Session
     */
    public function setCanceled($canceled)
    {
        $this->canceled = $canceled;

        return $this;
    }

    /**
     * Get canceled
     *
     * @return boolean
     */
    public function getCanceled()
    {
        return $this->canceled;
    }

```

In the template view-session.php.twig, I **var_dump the {{ session.canceled }} attribute** and I get **bool false** at the beginning of my file view-session.php.twig, with the following** {{ dump(session.canceled) }} **and I get **bool(false)**. I have also tried to use the ladybug bundle, and I get bool false for {{ session.canceled | ladybug_dump}}.
Event when I **var_dump** from my controller, I get ** bool false**.

Now my issue is that when I use session.canceled in the same template view-session.php.twig, but **inside a <script type="text/javascript"> </script>**, **the value of session.canceled becomes true**. I really don't understand why the session.canceled is false everywhere, and true if I place it in a <script></script> in the same tamplate. If I do an alert({{ session.canceled}}) in the same template, but inside the script, I get true also. **And if I both {{ dump(session.canceled) }} and alert({{ session.canceled}}), I get bool false for the dump and alert true for the alert function.**

And in my database, the corresponding table has a 0(=false) value and ** this value never changes in my database and remains equal to false.**

The weird thing is that event if I force getCanceled() to return false in my Session entity, likeso

```
    /**
     * Get canceled
     *
     * @return boolean
     */
    public function getCanceled()
    {
        return $false;
    }
```

The {{ session.canceled }} still dumps to false, whereas it is equal to true in my <script></script>
Below is the code I use in my script, with the explanation.

```
    <script type="text/javascript">
        var slug = "{{ session.slug }}";
        var applicantUsername = "{{ app.user.username }}";
        {% if session.closed %}
            var sessionClosed = true;
        {% else %}
            var sessionClosed = false;
        {% endif %}

        {% if session.canceled %}
            var sessionCanceled = true;
        {% else %}
            var sessionCanceled = false;
        {% endif %}
        alert(sessionCanceled);
    </script>
```

As you can see, I alert(sessionCanceled) and I get true. Another weird thing is that it works perfectly with the "closed" attributes. When I {{ dump(session.closed) }} it in the view-session.php.twig, I get a value of false, and if I do an         alert(sessionClosed), I still get false. It works fine.

I believe there is an issue somewhere. If I do both alert({{ session.closed }}) alert({{ session.canceled }}), I get false for closed, and true for canceled. Same goes for alert(sessionCLosed) and alert(sessionCanceled).

Can somebody help me with it? How come the variable turns from false to true?

**Comment by ninsuo** [comment]
Hello,

Can you please move this thread on [Stackoverflow](http://stackoverflow.com/questions/tagged/twig)?

There are good chances you'll find a more active community for your issue.

Do not hesitate to put more code from your view, because here we can see the `alert()` but we don't know what's between when your bool is false and when it becomes true.

Thanks!
A

**Comment by NadjibBELLOUNDJA** [comment]
Hi ninsuo,

Thank you for your reply. I have actually found the solution; it is related to a personal mistake that I have corrected. Sorry for bothering and thanks again.

I will close the issue.
