### ISSUE TITLE
cache "failed to open stream"

### ISSUE THREAD

**Issue by accessite** [twigphp/Twig#1867]
Hi,
I'm trying to implement Twig on my system, and it seems a fantastic template engine but I have an issue with the cache. I'm using Twig 1.22.2 (on PHP 5.5.2).

I'm looking for a solution for this error : 
**Line 49 in /vendor/twig/twig/lib/Twig/Cache/Filesystem.php
include_once(/var/www/sandbox/web/cache/twig/2/f/2fe754c8ff5138908ac531769a84ba150054bbe4c931093211e335d1ea87d823.php): failed to open stream: No such file or directory**

Permissions are ok, the folder exist.

Thank for your help

**Comment by reFX-Mike** [comment]
This seems not a twig-related problem. As you can see it's a simple PHP directive to include a specific file.

Does that file exist? If not, then your permissions might not be "OK" after all. Does the Apache process have the right permissions to read/write/execute from that folder?

**Comment by Tobion** [comment]
He has the wrong error handler that doesn't respect the silencing operator `@include`. There are already several issues about that.

**Comment by reFX-Mike** [comment]
How do you trigger that error? We use Twig 1.22.2 on our production website and never encountered it before.

**Comment by accessite** [comment]
Thank for your answers.
Yes Toblon, it was my error handler, I've disabled it and it works !
