### ISSUE TITLE
Provide api for rendering blocks separately

### ISSUE THREAD

**Issue by Koc** [twigphp/Twig#1873]
Does it possible change something here for 2.0?

ref https://github.com/twigphp/Twig/issues/676

**Comment by stof** [comment]
Well, adding a new API does not break BC, so this could even go in the 1.x branch, if we decide on a design to do it

**Comment by alexweissman** [comment]
Just for context, the question is whether `renderBlock` will become an API method (as opposed to being labeled "internal").  The problem right now is:

- `renderBlock` is really useful for rendering email templates (i.e., one block for the subject, and another block for the body).
- Unfortunately, `renderBlock` does not seem to run in the global context, so any global Twig variables do not get passed in.
- Also, something about `renderBlock` and buffering.

**Comment by nakashu** [comment]
A use case I wanted to solve many times with block rendering is ajax responses.

```twig
{% extends 'layout.html.twig' %}

{% block breadcrumb %}... breadcrumb ... {% endblock %}
{% block content %}
.. content that should be changed after ajax request ..
.. with more complex logic, like form errors rendering etc .. 
{% endblock %}
```

Here you could just render the content block, based on if the request is ajax else render the whole page with extends ... Although it could be done by using %include 'content.html.twig'%, at least for me this seems like a nicer solution.

```php
return $request->isXmlHttpRequest()
    ? $this->renderBlock('page.html.twig')
    : $this->render('page.html.twig');
// or handle it in listener
```

If anoyone got a nice solutions for returning partially rendered twig tempales for ajax, let me know, I'll be gratefull.

**Comment by stof** [comment]
this can also be done using conditional inheritance (this is what the Symfony WebProfiler is doing):

```twig
{# ajax_layout.html.twig #}
{% block content '' %}
```


```twig
{% extends is_ajax ? 'ajax_layout.html.twig' : 'layout.html.twig' %}

{% block breadcrumb %}... breadcrumb ... {% endblock %}
{% block content %}
.. content that should be changed after ajax request ..
.. with more complex logic, like form errors rendering etc .. 
{% endblock %}
```

**Comment by nakashu** [comment]
that looks really nice thanks @stof.

**Comment by nakashu** [comment]
tested out @stof 's suggestion and with just tiny change to make it more dynamic, you can render any block from a larger template, thus also covering the email use case:

```twig
{# block.html.twig #}
{% if _block is defined %}
    {{ block(_block) }} {# render only block with specified name in the variable #}
{% endif %}
```

```twig
{# let _block be 'breadcrumb' #}
{% extends _block ? 'block.html.twig' : 'layout.html.twig' %}

{% block subject %}email subject{% endblock %}
{% block body %}emal body here{% endblock %}
{% block content %}some other content{% endblock %}
```

of course it can be made more flexible by passing/checking `_block` is array and render multiple blocks at one with a loop.
thoughts?

**Comment by amenophis** [comment]
@fabpot @stof Any chance to get renderBlock an @Api method ? in v2 ?

**Comment by fabpot** [comment]
Done! At last.
