### ISSUE TITLE
Request for clarification regarding C extension installation

### ISSUE THREAD

**Issue by mpdude** [twigphp/Twig#1875]
I would like to install the C extension from a configuration management system. For example, the [Puppet PHP module](https://github.com/mayflower/puppet-php) can easily install extensions via PECL.

Now the Twig docs warn that the PEAR channel for Twig is deprecated and will not be updated or even be removed in the future. This leads to the following questions:

1. Does the version of the C extension installed have to match the version of Twig used?
2. If not (i. e. if we can decouple the C ext and Twig itself maintenance-wise), can we somehow keep the option to install the C ext via PECL? 
3. If you don't want to run the Twig PEAR channel in the future, could the ext be placed at pecl.php.net?

For PHP code, Composer is the standard nowadays, but for PHP extensions PECL still seems to be a good choice.

**Comment by stof** [comment]
> Does the version of the C extension installed have to match the version of Twig used

Between 1.x and 2.x, yes. Then, you should use at least 1.20+ for the C extension (otherwise you suffer from the security issue fixed in Twig 1.20). Most minor releases of Twig don't change the C extension though (except for the version number).

> could the ext be placed at pecl.php.net

IIRC, this was not possible because the C extension is not a standalone package (it is totally useless without Twig)

**Comment by mpdude** [comment]
> Between 1.x and 2.x, yes. Then, you should use at least 1.20+ for the C extension

Not sure I get that right. You mean the major version numbers must match and for 1.x one should use ~1.20?

> Most minor releases of Twig don't change the C extension though (except for the version number).

Isn't that a good reason to split the C ext out of the main repo? And if you agree that PECL is a good thing(:tm:) for exts, can we have a dedicated pecl.twig-project.org channel for the ext only that will be maintained in the future?

**Comment by fabpot** [comment]
As of today, I'm still publishing PEAR packages and PECL packages. I won't split the C extension out of the main repo as I want to be able to run PRs that modify both the C ext and the PHP code as the same time (we are running some tests with and without the ext on Travis and having 2 repos would make this much more complex for no benefits).

**Comment by mpdude** [comment]
That's a valid point.

Even if you stop with PEAR, would you still provide PECL?

And could you please rephrase @stof's comment regarding version compatibility (see above), I think that's not entirely clear.

Thanks!

**Comment by stof** [comment]
@mpdude if you use Twig 1.x, you should also use ext-twig 1.x (and ext-twig before 1.20 suffers from the same security issue than Twig before 1.20).
If you use Twig 2.x, you should use ext-twig 2.x too (this requires compiling from source though, as there is no 2.x release yet).

**Comment by mpdude** [comment]
But the latest 1.x ext will work fine for all 1.x versions of php-Twig?

**Comment by stof** [comment]
@mpdude yes

**Comment by mpdude** [comment]
Thank you guys.
