### ISSUE TITLE
Twig C extension still useful for PHP7

### ISSUE THREAD

**Issue by reFX-Mike** [twigphp/Twig#1876]
Since PHP7 is about twice as fast as previous PHP versions, I wonder if the Twig C extension will even be ported to PHP7 or, given the almost negligible improvement it provides, be discontinued altogether.

**Comment by fabpot** [comment]
How do you know it's going to provide a negligible performance improvement? We will port the extension to PHP7 and we will see; but of course, if it's too small, we will drop it.
