### ISSUE TITLE
add a check when a date is null twig_date_format_filter

### ISSUE THREAD

**Issue by sound-code** [twigphp/Twig#1877]
Hi,
at the moment if a date is null the twig filter return the current date.
Do you think it's a good idea to check and return null when a date is null?

thank you

**Comment by Tobion** [comment]
:-1: 
- That is how php behaves `new \Datetime(null)`. 
- BC break
- The date filter shouldn't change the return type depending on value

**Comment by sound-code** [comment]
no no, I didnt make myself clear sorry
 
null|date('d-m-y')   return 14-10-2015 !

**Comment by sound-code** [comment]
yes sorry I got it
