### ISSUE TITLE
Tokenizer discards whitespace

### ISSUE THREAD

**Issue by joshuaspence** [twigphp/Twig#1880]
I am interested in writing a linter for Twig which can check for spacing around tokens. It seems that the current tokenizer discards whitespace, so this would not be possible.

Would it be possible for the Twig tokenizer to retain whitespace tokens?

**Comment by fabpot** [comment]
We don't keep whitespaces as it would add many nodes. We don't keep them as whitespaces are not significant for Twig and adding so many nodes would increase memory usage and decrease performance.

**Comment by joshuaspence** [comment]
Would you consider adding an option (which defaults to true) to discard whitespace?

**Comment by fabpot** [comment]
@joshuaspence I don't think so as I think it would change the code significantly.
