### ISSUE TITLE
Twig_Error_Syntax and ErrorException

### ISSUE THREAD

**Issue by julesnicolas** [twigphp/Twig#1887]
[Twig_Error_Syntax]                                                                                                                            
  An exception has been thrown during the compilation of a template ("The Twig_Filter_Function class is deprecated since version 1.12 and will   
  be removed in 2.0. Use Twig_SimpleFilter instead.") in "CoreBundle:Mailer:Shooting/new.html.twig".

[ErrorException]                                                                                                            
  The Twig_Filter_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead. 

My version twig is 1.22.3

**Comment by Tobion** [comment]
Firstly, you are using the a wrong error handler that does not ignore deprecations correctly. Secondly, the deprecated usage comes from "CoreBundle", so it must be fixed there. This is not Twigs fault. Please close.

**Comment by stof** [comment]
The only reason this can happen is indeed that you have an error handler turning **silenced** errors into exceptions. This is a bad idea

**Comment by kcassam** [comment]
Thanks guys, we had a bad error handling. We will close the issue.
