### ISSUE TITLE
Generating key, value array, key will not set

### ISSUE THREAD

**Issue by wiesson** [twigphp/Twig#1898]
I'm trying to generate a key, value array but my key will not set correctly:
```twig
{% set years = {} %}
{% set currentYear =  "now"|date("Y") %}
{% for year in currentYear..currentYear + 20 %}
	{% set years = years|merge({ year : year }) %}
{% endfor %}

{% for key, value in years %}
	{{ key }} -> {{ value }}
{% endfor %}
```
I would assume that the code above will result in something like this:
```
2015 -> 2015
2016 -> 2016
... 
2035 -> 2035
```
but instead I will receive this: ```year -> 2035```. I tried to wrap the key with brackets: ``` {% set years = years|merge({ (year) : year }) %} ``` but this will result in: 
```
0 -> 2015 
...
20 -> 2035
```

it works, if I append any string (not an empty one) to the key like this: ``` {% set years = years|merge({ ("t" ~ year) : year }) %} ``` But this is not my goal. Any further ideas?

**Comment by jvasseur** [comment]
This is cased because the twig merge filter uses php array_merge function which doesn't preserve keys when merging arrays with numeric keys.

**Comment by wiesson** [comment]
Thanks, I have not noticed this. Any idea, how I could solve my problem?

**Comment by jvasseur** [comment]
There is no real solution to this, you can append a letter to make php preserve keys like you did.

Another solution would be to create your own filter that does the merge with the ```+``` operator that preserve numeric keys.
