### ISSUE TITLE
Deprecate {% include %} tag in favor of include() function?

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#1899]
### Context

  * The `include()` function was added in Twig 1.12.0-RC1 (released on 2012-12-29).
  * In theory, `include()` function deprecates the `{% include %}` tag.
  * In practice, the `{% include %}` tag is not deprecated in the Twig source code.

### Questions

  * Should we deprecate `{% include %}` tag?
  * Is there any reason to have both a function and a tag for the same thing?

**Comment by fabpot** [comment]
That's right. I forgot about that. I need to double-check if both have the same set of features (IIRC, there are some features not available with the function).

**Comment by iltar** [comment]
I don't think it's possible to simply pass the whole scope of variables to an include:
```twig
{% include '...' with some_var only %}
```
Personally I think the `{% include %}` is more powerful and is superior to the function, but I don't know the reason why the function was introduced so I can't judge on that.

**Comment by javiereguiluz** [comment]
@iltar

```twig
{{ include('...', { 'some_var': some_value }, with_context = false)}}
```

**Comment by iltar** [comment]
@javiereguiluz so by default it has access to everything? how does the `with_context` work internally? It feels less intuitive for me, but if they can both do the same I'd say keep only one. I notice that my codebase is already using both (different developers, different implementations).

:+1: from me to keep only one of them.

**Comment by javiereguiluz** [comment]
@iltar the `include()` function works exactly like the `% include %` tag and has the same features: http://twig.sensiolabs.org/doc/functions/include.html  But maybe there is some edge case which is what Fabien is going to double-check.

**Comment by reFX-Mike** [comment]
I would prefer to keep the tag and deprecate the function. The function call seems overly verbose.

**Comment by ninsuo** [comment]
For me the `{{ include }}` function is more natural, it uses a standard pattern `path, {arguments}` and not keywords such as `with`, and others you should know by heart whose add complexity to the syntax.

Also, the function is more flexible:

```jinja
{% set contents = include('template.twig') %}
```

instead of:

```jinja
{% set contents %}
  {% include 'template.twig' %}
{% endset %}
```

The only reason why I see `{% include %}` exist is that in a lot of languages, `include` is a statement. But in Twig, we have so many options that the syntax becomes too complex to worth a statement, IMO.

**Comment by fabpot** [comment]
Closing as I still see a lot of usages of `include` as a block, looks like it would be a too drastic BC break, without any good reasons.
