### ISSUE TITLE
Twig_Error_Runtime leaves partial output rendered to standard output

### ISSUE THREAD

**Issue by dtyler7** [twigphp/Twig#1900]
I recently had a template with a typo inside in, which caused a Twig_Error_Runtime exception to be thrown - this was easily fixed, and is not the problem.

When the error was thrown, the rendered template up to the point the error occured was actually outputted to PHP standard out (print/echo)

While this might not be as much of a problem on a full normal HTML page, the template was being rendering in an Ajax call, which was expected to return json output. If an error occurs, I have logic to catch all exceptions and gracefully return an error via JSON.

However the partial output was printed first, causing problems when another app tried to parse the page as JSON.

The bug/suggestion is that if Twig shouldn't leave the output dirty - if Twig is using output buffering, it should be cleared on failure (before an exception is thrown), not just on success.

**Comment by stof** [comment]
It is already cleared on failure when using the public rendering API.

Can you show your code calling Twig ?

**Comment by dtyler7** [comment]
Hey stof,

I hadn't realized that renderBlock() had been marked as internal - when I wrote the original code, it was lacking the internal annotation, and it worked really well for my use case.

Since that isn't part of the public API, but my app pretty heavily relies on renderBlock(), I'll wrap my code in an ob_start() for now and wait for #1873
