### ISSUE TITLE
Global variable "_self" is deprecated

### ISSUE THREAD

**Issue by XWB** [twigphp/Twig#1908]
I just upgraded to Twig 1.23 and noticed the following error:

```DEPRECATED - Global variable "_self" is deprecated```

The error message is thrown due to the following code:

```{% form_theme form _self %}```

So the docs say:

http://twig.sensiolabs.org/doc/deprecated.html

> As of Twig 1.x, the _self global variable is deprecated **except for usage in the from and the import tags**. In Twig 2.0, _self is not exposed anymore but still usable in the from and the import tags.

However, Symfony docs still say you should use the `_self` variable:

http://symfony.com/doc/current/cookbook/form/form_customization.html

> By using the special {% form_theme form _self %} tag, Twig looks inside the same template for any overridden form blocks.

How can we apply `form_theme` without using the `_self` variable?

**Comment by ninsuo** [comment]
If your template is AppBundle:Default:template.twig:

```jinja
{% form_theme 'AppBundle:Default:template.twig' %}
```

In the future, please ask your questions on [Stackoverflow](http://stackoverflow.com/tags/twig) regarding twig usage.

**Comment by XWB** [comment]
> In the future, please ask your questions on Stackoverflow regarding twig usage.

The Twig/Symfony documentation is wrong though and needs to be fixed.

**Comment by stof** [comment]
There is nothing wrong in the Twig documentation, so there is nothing to ask in the Twig repository though.

Issues in the Symfony documentation should be reported in the symfony/symfony-docs repository, so that the Symfony documentation team sees it (they probably don't follow the Twig issue tracker)

**Comment by XWB** [comment]
https://github.com/symfony/symfony-docs/pull/5858
