### ISSUE TITLE
[1.23.0 release] Undefined variable: name in lib/Twig/Environment.php

### ISSUE THREAD

**Issue by rev42** [twigphp/Twig#1911]
In 1.23.0 release, I got an  Undefined variable: name in lib/Twig/Environment.php file.

Although it has been fixed (as per commit e7e334c8b200b74c5937f9497f81e77202c9a97a), the latest release (1.23.0) is still affected.

Could you please make a hotfix and release a new version?

**Comment by fabpot** [comment]
sure
