### ISSUE TITLE
Undefined variable: name in vendor/twig/twig/lib/Twig/Environment.php line 740

### ISSUE THREAD

**Issue by lxg** [twigphp/Twig#1912]
The [following line](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L740) causes an “undefined variable” error:

    @trigger_error(sprintf('Defining the initRuntime() method in an extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended).', $name), E_USER_DEPRECATED);

Obviously, because the `$name` variable isn’t set. As it looks, it is not even necessary to use `sprintf()` here, as there are no parameters to insert.

**Comment by fabpot** [comment]
fixed in 1.23.1

**Comment by lxg** [comment]
Ok, sorry, didn't see it in the branch.
