### ISSUE TITLE
Twig_TemplateInterface is missing

### ISSUE THREAD

**Issue by emodric** [twigphp/Twig#1914]
`Twig_TemplateInterface` is missing from master branch. It seems to me it was removed by a recent merge of 1.x branch.

Deprecation docs for 1.x branch (both in [doc/deprecated.rst](https://github.com/twigphp/Twig/blob/1.x/doc/deprecated.rst#interfaces) and in [interface itself](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/TemplateInterface.php#L17)) say this interface will be removed in 3.0 and that in 2.0 will only be blanked out.

**Comment by stof** [comment]
This is a mistake in the doc. All these interfaces are gone in 2.0

**Comment by emodric** [comment]
Ah, alright then.

To migrate from the interface, is it enough to use Twig_Template instead on 1.x?

**Comment by stof** [comment]
Yes (using a different implementation of the interface which does not extend Twig_Template does not work properly anyway, which is why the interface is deprecated)

**Comment by emodric** [comment]
Thanks @stof!

Closing the issue and PR!
