### ISSUE TITLE
Allow extensions to return twig code

### ISSUE THREAD

**Issue by marijnotte** [twigphp/Twig#1915]
Use case:
We use an extension in a base template that mixes and orders a number of twig views and returns the combined HTML. One of the mixed twig views needs to be overwritten in each controller action view. We can't do that, because the Twig extension can't return Twig code with a block (for example {% block custompanel %} {% endblock %}).

So it would be great to allow to return Twig code in an extension. A new option (like is_safe) should be added to enable this only when set explicitly (for example for security reasons). It would also help these users:
http://stackoverflow.com/questions/7066365/dynamic-block-name-in-twig
http://stackoverflow.com/questions/10945200/twig-variables-in-twig-variable

**Comment by ninsuo** [comment]
I don't really understand.

`is_safe` is related to escaping, not rendering?

**Comment by marijnotte** [comment]
Hmm, @ninsuo I think you are right. I changed title and description and removed the use of is_safe.

**Comment by ninsuo** [comment]
Oh ok now I get it.

This is not possible, because filters are called at runtime. There are no more twig code, but compiled php code instead; so no more blocks to overwrite or anything related to language constructs.

But anyway, if anything in your base template should be replaced according to a specific action, blocks are the way to go; why don't you overwrite the `{% custompanel %}` you mentioned in a child template?

**Comment by marijnotte** [comment]
@ninsuo the problem we have is that we have a number of views that need to be ordered based on database settings. So because of the dynamic order we can't define them as blocks. We wrote a Twig extension to parse the views in the right order and return the HTML. But we need to override one of them in the different item views. Because we can't define the blocks it is not possible to do that.

The only workaround would be to let the extension find out the right view based on the controller action, but this is very ugly in the sense of application architecture (the extension shouldn't know which controllers/bundles the application has).
