### ISSUE TITLE
Data-prototype ignore template markup.

### ISSUE THREAD

**Issue by fpilee** [twigphp/Twig#1917]
http://symfony.com/doc/current/cookbook/form/form_collections.html#allowing-new-tags-with-the-prototype

Data-prototype attribute ignore the template markup

For example for this template 
```html
<div id="form_items">
            <ul class="items" data-prototype="{{ form_widget(form.items.vars.prototype)|e }}">
                {% for item in form.items %}
                    <div class="col-lg-6">
                        {{ form_row (item.detalle) }}    
                    </div>
                    <div class="col-lg-4">
                        {{ form_row (item.importe) }}
                    </div>
                {% endfor %}
            </ul>
        </div>

```

I got this data-prototype:

```html
<ul class="items" data-prototype="<div id=&quot;appbundle_factura_items___name__&quot;><div class=&quot;form-group&quot;><label class=&quot;control-label required&quot; for=&quot;appbundle_factura_items___name___detalle&quot;>Detalle</label><input type=&quot;text&quot; id=&quot;appbundle_factura_items___name___detalle&quot; name=&quot;appbundle_factura[items][__name__][detalle]&quot; required=&quot;required&quot; class=&quot;item_detalle form-control&quot; /></div><div class=&quot;form-group&quot;><label class=&quot;control-label required&quot; for=&quot;appbundle_factura_items___name___importe&quot;>Importe</label><input type=&quot;text&quot; id=&quot;appbundle_factura_items___name___importe&quot; name=&quot;appbundle_factura[items][__name__][importe]&quot; required=&quot;required&quot; class=&quot;item_importe form-control&quot; /></div></div>">

```

Which does not include col-lg-x markup.

**Comment by stof** [comment]
this is expected: you don't use theming of the children but render them manually, while the prototype is rendered using theming. There is no reason for the themed rendering to magically use your extra divs.
If you want to use divs in the items, you should do it through the form theming for collection items, so that the prototype also uses it: http://symfony.com/doc/current/cookbook/form/form_customization.html#how-to-customize-a-collection-prototype

**Comment by stof** [comment]
and btw, ths has nothing to do in the Twig issue tracker. Rendering of Symfony forms is not a feature of Twig, it is a feature of Symfony
