### ISSUE TITLE
raw doesnt work in conjunction with nl2br

### ISSUE THREAD

**Issue by r3wt** [twigphp/Twig#1923]
we are using Markdown as a basic text editor for the administrators to enhance listings as they come in on the site, via the Parsedown library, and HtmlToMarkdown library to translate it back. This works fine, however we are unable to use `nl2br` and `raw`  filters in conjunction with `default()`

code:

```
{{item.description|default('No description available')|nl2br|raw}}
```

**Edit** This appears to be a documentation issue. the documentation is stated in a way that raw is only applied if it is the last filter, which is clearly wrong. the following code works:

```
{{item.description|default('No description available')|raw|nl2br}}
```

**Comment by stof** [comment]
this is because ``nl2br`` askes the auto-escaping to escape things *before* the filter (otherwise ``<br>`` would be escaped too), so you need to put ``raw`` before ``nl2br``, not after (where it is useless as the ``nl2br`` output is already marked as safe, and the only goal of ``raw`` is to mark its output as safe)

**Comment by r3wt** [comment]
@stof yep, but the documentation at the twig website states:

>
> The raw filter marks the value as being "safe", which means that in an environment with automatic > escaping enabled this variable will not be escaped if raw is the last filter applied to it:

**Comment by stof** [comment]
sure, but the output of ``nl2br`` is already safe. This is not the place where the value gets escaped.. The documentation of the ``raw`` filter is too simplistic as the auto escaper has much more feature than that (the documentation was right in early Twig versions where filters were not able to receive a safe input)
