### ISSUE TITLE
Macros imported to parent template are not accessible in child templates

### ISSUE THREAD

**Issue by sarcher** [twigphp/Twig#1924]
Testing a Symfony 3/Twig 2 migration on a very large project and came across this.

Suppose we have in `parent.html.twig`:

```
{% import 'example_macros.html.twig' as example_macros %}
```

And then in another template:

```
{% extends 'parent.html.twig' %}

{{ example_macros.something() }}
```

This works in Twig 1.x but does not work in Twig 2 (on master). I can't find a specific reference to removing this in the documentation, and wonder if it is intended, since I can find no workaround other than importing commonly used macros into every template. On a large project this is very cumbersome, so I am hoping this is not intended.

If it is intended, is there a workaround for something like this or similar to this?

**Comment by ninsuo** [comment]
This looks like a bug to me.

In 1.x, macros are compiled with a `get` prefix (eg: getMacroName($__param__, ...))
In 2.x, macros are now compiled with a `macro` prefix (eg: macroMacroName($__param__, ...))

But Twig_Template::getAttribute do not implement this new prefix:
https://github.com/twigphp/Twig/blob/master/lib/Twig/Template.php#L538

```php
        if (isset(self::$cache[$class]['methods'][$lcItem])) {
            $method = (string) $item;
        } elseif (isset(self::$cache[$class]['methods']['get'.$lcItem])) {
            $method = 'get'.$item;
        } elseif (isset(self::$cache[$class]['methods']['is'.$lcItem])) {
            $method = 'is'.$item;
        } elseif (isset(self::$cache[$class]['methods']['__call'])) {
            $method = (string) $item;
            $call = true;
        }
```

**Comment by fabpot** [comment]
The compiler uses `getAttribute()` in the second case because the macro is not defined, so it cannot be "fixed". Unfortunately, the use case described in this ticket was not supported in Twig 1.x, it worked "by chance".

**Comment by ninsuo** [comment]
As the context is passed to child templates, the macro is well defined. It is just not callable because `getAttributes` does not manage the `macro` prefix.

**Comment by sarcher** [comment]
Is there a philosophical reason to not support this type of inheritance, or is merely a technical one that could be solved with the right PR?

**Comment by hason** [comment]
The discussion is in #1766 and the commit was introduced in #1771.

**Comment by ninsuo** [comment]
Yep, renaming the prefix introduced this issue. What do you think @stof?

**Comment by stof** [comment]
@ninsuo the fact that macros imported in the parent were available in the child templates is a side effect of the old implementation, and it was never supported officially. Note that we are aware of the fact it does not work anymore. This is why we were not able to change this in 1.x.
Making macros callable through ``getAttribute`` caused several issues in the past (and requires some special handling in ``getAttribute`` to mark such methods as safe btw)

**Comment by ninsuo** [comment]
Hmm, yeah, I just read the expression parser, you are right. So the old implementation was a cool bug :)

**Comment by ninsuo** [comment]
I think we could "fix" this but this will require deep work. It looks weird to add even more work to the already most perf-killing method (`Template::getAttribute`), but treating macro calls at parsing/compilation time makes them unavailable to other templates. 

Maybe _copying_ the blocks behavior (a MacroReference in the function parser, then inheritance via doDisplay...)?

**Comment by hason** [comment]
@ninsuo Yeah, I prefer blocks as is mentioned in #1302 and prepared in #1433.

**Comment by ninsuo** [comment]
Not sure, I want to keep macros, but allow macros inheritance just like blocks are inherited.
I don't know yet what could be done, but that's a good and challenging feature, will try to find something.

**Comment by stof** [comment]
@ninsuo normal macro calls were already treated at compilation time (they are not compiled through getAttribute, even in 1.x)

**Comment by HeahDude** [comment]
If anyone is interested, I made a gist for an extension allowing to dynamically autoload macro from any views : see [link](https://gist.github.com/HeahDude/f9aeb128fcac309dddc8)

**Comment by HeahDude** [comment]
It also work inside macro and set tags

**Comment by HeahDude** [comment]
Made some tests with this gist and it works perfectly.

Autoload works from absolutely everywhere without `import` tag, and bonus, once a template is compiled, it is cached for future requests too !

**Comment by fabpot** [comment]
I'm going to close this one as the 1.x "feature" was actually a nice side effect (but it also came with even more not so nice side effects). With #3012, we are redefining the macro scope rules.
