### ISSUE TITLE
Remove whitespace at compile time, not at render time?

### ISSUE THREAD

**Issue by downhiller** [twigphp/Twig#1928]
I was wondering if this is possible, to save on the potentially costly preg_replace at render time?

http://stackoverflow.com/questions/33921439/can-we-make-twig-remove-whitespace-when-its-compiled-rather-than-when-its-ren

I assume there's a good reason why you don't already do that though, would you care to share what the reason is? Thanks!

**Comment by stof** [comment]
well, spaceless cannot be done at compile time, because of its semantic: removing spaces between HTML tags. But using spaceless is totally optional.

And if your goal is to remove spaces used in the template source only (not spaces coming from content being generated), the right tool for the job is to use the whitespace control system, which is a compile-time feature. http://twig.sensiolabs.org/doc/templates.html#whitespace-control

**Comment by downhiller** [comment]
You're correct that my goal is to remove spaces used in the template source.  But I'm talking about the spaces around the HTML tags in the template source, not spaces around {{ }} statements.

e.g.

<section>
    <h2>Header</h2>
    <div>{{ bodyText }}</div>
</section>

I want the output to be

<section><h2>Header</h2><div>bodyText</div></section>

spaceless does this, but at render time rather than compile time.

Whitespace control doesn't do this, it only controls whitespace inside the {{ }} statement, I think?

**Comment by stof** [comment]
spaceless does it at render time, because it would be quite impossible to know whether the twig structure could output something between HTML tags

**Comment by downhiller** [comment]
Can you give me an example please, I'm trying to understand!

**Comment by apfelbox** [comment]
@downhiller 

```
$twig->render("a.twig", [
    "exampleString" => "<article>          <h3>Headline</h3></article>",
]);
```

```
<section>
    <h2>Header</h2>
    <div>{{ exampleString | raw }}</div>
</section>
```

Here twig can't possibly now what the value of `exampleString` will be (as the value will be set at a later time and can vary between renderings). `{% spaceless %}` will also remove whitespace *inside* the *content* of these variables.

@stof Nevertheless, an option would be nice to automatically strip whitespace in the template (not in the content, but just the template), basically an automatic `{{- ... -}}`, if you will. With the addition that it could work between tags that don't have twig tags around them. If you look at my example the possible output would be:

```
<section><h2>Header</h2><div><article>          <h3>Headline</h3></article></div></section>
```

what imho would be good enough.

**Comment by downhiller** [comment]
But we can easily control that in the app.  It's trivial to send clean whitespace-less content to the template.

As you go on to say, an automatic template-whitespace-strip function is what's "needed", and would certainly be nice.

As it is I think I've achieved this myself with this simple modification to /lib/Twig/Node/Text.php:

http://stackoverflow.com/a/33922380/1058739

Are there any potential downsides to this that I've not thought of?

**Comment by stof** [comment]
@downhiller your suggestion (which would be a partial spaceless as it would miss any case where the spaces are coming from different nodes, for instance because of a loop rendering a list) could be implemented in an extension (using a NodeVisitor to modify text nodes)

**Comment by apfelbox** [comment]
@downhiller yep, I think the second suggestion could be enough. Most of the time the inserted HTML would possibly also generated by twig and would be therefore already be whitespace-sanitized.
