### ISSUE TITLE
Ability to iterate over object properties

### ISSUE THREAD

**Issue by RedactedProfile** [twigphp/Twig#1931]
Scenario: an object (possibly a JSON decoded object) is passed into a twig template's scope. One wants to iterate over the objects properties and their values, possibly to generate a table (for example).

controller: 

    $data = json_decode('{
        "key": "value",
        "another_key": "another value"
    }');

    echo $twig->render('template.html.twig', array('data' => $data));

template:

    {% for key, value in data %}
        {{ key }}: {{ value }}<br />
    {% endfor %}

This will not work. It doesn't even try to iterate. The only way around it, is to either cast the object as an array in the logic, or add a new function/filter to twig to cast it there. 

    {% for key, value in data|array %}
        {{ key }}: {{ value }}<br />
    {% endfor %}

That, I feel, shouldn't be a solution as PHP is more then capable of iterating through an objects properties

    $data = json_decode('{
        "key": "value",
        "another_key": "another value"
    }');

    foreach($data as $key=>$value)
        echo "$key: $value<br />";

Is there a specific reason this doesn't work? 

Thank you!

**Comment by ninsuo** [comment]
In fact, objects that implement `\Traversable` interface can be used in a `for`. Even if PHP is very permissive, it is more consistent to iterate through objects that implements the behavior of being iterated.

In your case, it seems easier to decode your data directly into an array by adding `true` as second argument of `json_decode`:

```php
$data = json_decode('{
    "key": "value",
    "another_key": "another value"
}', true);
```
