### ISSUE TITLE
[Suggestion] Add a way to access the name of the current template

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#1932]
``_self`` accessing the current Twig_Template instance is deprecated (and removed in 2.0). This causes headaches in several places needing an easy way to reference the current template (and this is why we kept a special handling of it in from and import tags).

However, most places relying on ``_self`` today don't actually need the template instance. The template name would be enough as they pass it to functions resolving the template anyway. Would you accept a way to get the name of the current template rather than the instance (there is no security implication with just the name). This could even allow to remove ``_self`` entirely as the from and import tag would also accept it.

See https://github.com/symfony/symfony-demo/issues/242#issuecomment-153388234 and https://github.com/symfony/symfony/issues/16804 for instance

**Comment by webmozart** [comment]
:+1:

**Comment by webmozart** [comment]
Maybe we could even change `_self` to contain the template name in 2.0? Since it can only be used in internal code, that wouldn't break any BC IIUC.

**Comment by ninsuo** [comment]
:+1: 

May be also useful to keep `_parent` template name, considering that the same view may behave differently if it extends a base, a baseMobile or a baseAjax layout (for example).

**Comment by stof** [comment]
@webmozart this would break BC for people using this variable and expecting to get a Twig_Template, and would force to have 2 different logic if you really want to get the template name in both 1.x and 2.x.

``_self`` is not used in internal code. It is a special variable available everywhere in 1.x (the change in 2.x is the removal of this special variable, and a special handling of it in 2 places).

I suggest creating a ``_current`` special variable holding the template name (well, compiled to ``$this->getName()``)

**Comment by webmozart** [comment]
I'm only talking about Twig 2. If the `_self` variable is not available anymore, introducing it again does not break BC, does it?

**Comment by sstok** [comment]
:+1:

**Comment by Tobion** [comment]
The advantage of just changing the meaning of `_self` as @webmozart suggests is that most people do not have to change their code. As `import`, `form_theme` etc should work in both cases.
So I would say we should optimize for the standard use-case and not the edge case where somebody really needed the Twig_Template instance.

**Comment by stof** [comment]
@fabpot what do you think here ? Should we just change ``_self`` in Twig 2, or introduce a new one (``_current`` for instance) in Twig 1.x ?

**Comment by fabpot** [comment]
See #1964 (1.x) and #1965 (2.0)
