### ISSUE TITLE
PHP 7 & c extension: "undefined symbol: zval_used_for_init in Unknown on line 0"

### ISSUE THREAD

**Issue by downhiller** [twigphp/Twig#1935]
After compiling the c extension and including twig.so in php.ini I get this error when I restart php-fpm (in this case remi's php70-php-fpm).

**Comment by fabpot** [comment]
That's because the C extension does not support PHP 7 yet.

**Comment by downhiller** [comment]
That's fair enough.  I had looked on here and twig's site and saw no mention one way or the other, so I wondered if it was supposed to work and I'd just done something wrong.

**Comment by fabpot** [comment]
C extensions are totally different in PHP 5 and PHP 7, so we need to rewrite the extension from scratch :(

**Comment by downhiller** [comment]
:-(
