### ISSUE TITLE
Composer installation 404 error?

### ISSUE THREAD

**Issue by itawde** [twigphp/Twig#1937]
Hi all,
I'm just trying to set up a new installation and included twig into my composer.json but when running composer install I always run into

  The "https://packagist.org/p/twig/twig%24bd3f9e87cdeb581cbea597ed0ed3476c30c93f9b5de38cd3064f8eff7b64357a.json" file coul  
  d not be downloaded (HTTP/1.1 404 Not Found) 

Am I missing something? Any hint would be appreciated :)

**Comment by stof** [comment]
this should be reported to composer as it is an error while running composer, not while running Twig
