### ISSUE TITLE
Parsing error when trying to extend main.twig

### ISSUE THREAD

**Issue by enail12** [twigphp/Twig#1938]
I was using twig with no issues last week whatsoever. But when I started working on a new project this week I installed slim, twig, and views. All of which are now requiring new libraries. The new libraries are called nikic and pimple. I am not sure if these are what is causing my issue. I am using wamp to host my files locally. When I try to extend my main template, main.twig, there is a parsing error on the
 {% extends 'main.twig' %} line. Here is what the base structure of my code is: 

html: main.twig

<head>

**{% block head %}**

**{% endblock head %}**

</head>
	
<body>
     <div id="wrapper">

**{% block top %}**
              
        <div id="header">
	      
              </div>
				
               <div id="navigation">
			<ul >
				* Item 1
				* Item 2
					<ul >
			            * Item 2a
						* Item 2b
                        * Item 2c
		                * Item 2d
					    * Item 2e
					</ul>
				* Item 3
					<ul>
						* Item 3a
						* Item 3b
						* Item 3c
                        * Item 3d
						* Item 3e
						* Item 3g
					</ul>
                * Item 4
				* Item 5
			</ul>
		</div>
**{% endblock top %}**
			

**{% block content %}**
				
**{% endblock content %}**
		
             
				
				
**{% block footer %}**
				
                 <div id="footer">
					<div id="footer-navigation">
						<ul>
							* Item 1
                            * Item 2
							* Item 3
							* Item 4
							* Item 5
						</ul>
					</div>
				</div>
			
**{% endblock footer %}**
			

-------------------------------------------------------------------------------------------------------------------------------

here is an example of the file that I am trying to extend from main.twig

**{% extends 'main.twig' %}**

{% block content %}
         
{% endblock content %}

-------------------------------------------------------------------------------------------------------------------------------

and here is the php:

<?php

	require 'vendor/autoload.php';
	date_default_timezone_set('America/New_York');
	
	use Monolog\Logger;
	use Monolog\Handler\StreamHandler;
	
	$app = new \Slim\Slim( array(
		'view' => new \Slim\Views\Twig()
	));
	
	$view = $app->view();
	$view->parserOptions = array(
		'debug' => true
	);
	
	$view->parserExtensions = array(
		new \Slim\Views\TwigExtension(),
	);	
	
	$app->get('/', function() use($app) {
		$app->render('home.twig');
	})->name('home');
	
	$app->run();

Again using basically this same set-up last week this was working just fine. Now when I try and load the page I get the error: Parsing error expected '', }, or string. I really have no idea what is going on. Maybe the new libraries that are loading when I am installing slim, twig, or views. Not sure. Please help!!!

**Comment by stof** [comment]
Can you fix the markup of your post to use markdown code-blocks ? Otherwise it is hard to read as code blocks are messed up (and some info gets missing)

**Comment by xabbuh** [comment]
@enail12 If you are struggling with Markdown here, you may want to create a [Gist](https://gist.github.com/) which makes it easier to create code examples (even with multiple files).

**Comment by SpacePossum** [comment]
where does the `unblock [block name]` syntax come from?

**Comment by enail12** [comment]
That is supposed to be endblock. My mistake, however I fixed that and still the same issue

**Comment by stof** [comment]
@enail12 I suggest you to read the markdown guide: https://guides.github.com/features/mastering-markdown/ (this is linked from the comment form btw)

**Comment by enail12** [comment]
Have a look at the original post. I have updated it

**Comment by SpacePossum** [comment]
Rebuild using the samples provided, no issues. Could you provide a bit more of the error (stack trace),
what is outputting `Parsing error expected '', },` ?

**Comment by stof** [comment]
@enail12 your issue still does not use the code-block markup to enclose the code snippet, making the code much harder to read (and probably partially hidden because of it being stripped by the markdown parser)

**Comment by enail12** [comment]
Error: Parse error on line 1:
{% extends 'main.twig
-^
Expecting 'STRING', '}'

This is the error that I am receiving. I really have no idea what is happening.

**Comment by enail12** [comment]
I am still having this issue. could someone please weigh in???

**Comment by xabbuh** [comment]
@enail12 Please provide a completely readable code example here by updating your problem description or create a gist containing code.

**Comment by enail12** [comment]
https://gist.github.com/enail12/40d78ee003821672c7a3

**Comment by enail12** [comment]
i hope this is what you need. please advise

**Comment by xabbuh** [comment]
Can you also show your `composer.json` file so that we know which dependencies your code needs?

**Comment by enail12** [comment]
composer.json file is now part of the gist

**Comment by xabbuh** [comment]
@enail12 That cannot work in any way as some dependencies are still missing:

```
PHP Fatal error:  Class 'Slim\Slim' not found in /home/christian/Symfony/twig/index.php on line 8
PHP Stack trace:
PHP   1. {main}() /home/christian/Symfony/twig/index.php:0
```

**Comment by enail12** [comment]
I have slim I have everything installed. How do I fix that issue?

**Comment by xabbuh** [comment]
I don't know Slim so I don't know if the versions you provided work or do not work. But we cannot help you when you cannot provide a reproducable example. If this only happens with certain versions of your dependencies you can also show the `composer.lock` file and we can try that.

**Comment by enail12** [comment]
composer.lock file added. This issue can be reproduced when you are going to the home.twig page. I have gotten both the twig parsing error and the class \Slim\Slim error before when trying to fix this issue.

**Comment by xabbuh** [comment]
That doesn't change anything and there even is no class `Slim` anywhere in your vendors.

**Comment by SpacePossum** [comment]
there are still `{% endblock [name[ %}` in your example, please try `{% endblock %}`

**Comment by enail12** [comment]
i will try that but I am still confused as to how you would know that I dont have the class Slim anywhere. I should have all the classes that are included in slim when slim is installed through composer. And if I dont have them, why? and how can they be installed independently

**Comment by RocKordier** [comment]
Hey @enail12 ,

bit late, but maybe it can help you.

With your Gist-Files i'll get the same error like @xabbuh posted before.
Within Slime 3 the \Slim\Slim - Class dosen't exist anymore. Its replaced by the App - Class (see also [Slim 3 Readme](https://github.com/slimphp/Slim/blob/3.x/README.md))

I've downgraded the Slim version to 2.x in the composer.json ```"slim/slim": "2.*",``` and everything works fine and also I don't get your parsing error.

**Comment by enail12** [comment]
I eventually did the same. Downgrading that is. I also tried Slim\App but that didn't work.

**Comment by xabbuh** [comment]
Can you then close here please when your issue is solved?

**Comment by RocKordier** [comment]
@enail12 
Please make sure for slim3 that you remove ```"slim/views": "^0.1.3", ``` and add ```"slim/twig-view": "^2.0"``` in your composer.json.

Your index.php should look like this:
```
<?php
require 'vendor/autoload.php';

use \Slim\App;
use \Slim\Container;
use \Slim\Views\Twig;
use \Slim\Views\TwigExtension;

$configuration = [
    'settings' => [
        'displayErrorDetails' => true,
    ],
];

$container = new Container($configuration);

$container['view'] = function ($c)
{
    $view = new Twig('templates', [
        'cache' => 'cache'
    ]);
    $view->addExtension(new TwigExtension
    (
        $c['router'],
        $c['request']->getUri()
    ));
    return $view;
};

$app = new App($container);
$app->get('/', function ($request, $response, $args) {
    return $this->view->render($response, 'home.twig', []);
})->setName('home');

$app->run();
```
Yes, i think you should close that issue, because it seams that its not a Twig - Issue.

**Comment by pcoloma** [comment]
Hello, I don't know if this can help,
I had a similar problem with extending templates with Slim Twig combo.
The extends fails because they are no blocks to render or the blocks are not rendered right because the syntax is wrong of  the variables undefined or whatever). 

Make sure you have in: 
**main.twig**
{% block content %}
my primary content goes here
{% endblock %} 

in the extended template say 
**secondary.twig**
{% extends "main.twig" %}
{% block content %} replacement content{% endblock %} 

A slight error in the block definition will make the extend fail, as the errors are intercepted by slim and twig is not able to tell you what is wrong.
