### ISSUE TITLE
Evalutate `needs_environment` and `needs_context` in compiled template, not during compile

### ISSUE THREAD

**Issue by SpacePossum** [twigphp/Twig#1939]
I ran into a little issue when using different implementations for the same filter and using caching.

When a template gets compiled the filters are evaluated to see if the filters need the context (and/or environment). This causes issues if you reuse the template (using caching) with a different filter (implementation) which has different requirements related to the need for context.

This is a simple test to show the issue;

`test.php`
```php
<?php
require_once __DIR__.'/lib/Twig/Autoloader.php';
Twig_Autoloader::register();
$loader = new Twig_Loader_Filesystem(__DIR__);

$twig = new Twig_Environment($loader,array('cache' => __DIR__.'/cache',));

class Filter1 extends \Twig_SimpleFilter {
    public function __construct()
    {
        parent::__construct('testFilter', function ($value) {
            return '1';
        });
    }
}

$twig->addFilter(new Filter1());

echo $twig->render('test.twig', array('dummy' => 'a'));

$twig = new Twig_Environment($loader,array('cache' => __DIR__.'/cache',));

class Filter2 extends \Twig_SimpleFilter {
    public function __construct()
    {
        parent::__construct('testFilter', function ($contect, $value) {
            return '2';
        }, array('needs_context' => true));
    }
}

$twig->addFilter(new Filter2());

echo $twig->render('test.twig', array('dummy' => 'a'));
```

`test.twig`
```twig
{{ dummy|testFilter }}
```

Ends with 
```
1PHP Warning:  Missing argument 2 for Filter2::{closure}() in /home/possum/work/Twig/test.php on line 34
```

Before I start working on this, does anyone have a good idea how to solve this without reworking https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Node/Expression/Call.php#L23 to much?

**Comment by stof** [comment]
This cannot be done at runtime: these flags are changing the way the template is compiled, as the call needs more arguments. Moving such check at runtime would require to use much less efficient code at runtime when calling a template, which would have an impact on performance.

If you have 2 environments configured differently, sharing the cache folder is likely to produce weird things, as the cache depends on the configuration. And IMO, such weird setup does not warrant making Twig filters and functions slower

**Comment by stof** [comment]
btw, your use case would also mean that auto-escaping checks for filters should be done at runtime (in case they don't have the same safety), and this would simply be impossible (it would basically require doing most of the compilation at runtime, which you can already do if you don't care about performance: disable the cache).

**Comment by SpacePossum** [comment]
Fair enough; I use one environment on which I add one of two filters based on a runtime condition which I check in the bootstrap (for performance reasons, so I don't have to check the condition each time in the filter). Making both filters requiring the same (context/environment) and such this works.
Thanks for the insights :+1: .
