### ISSUE TITLE
Race condition on cache initialization

### ISSUE THREAD

**Issue by webengineer** [twigphp/Twig#1944]
Hi, 

we are observing that exception 
```
Uncaught PHP Exception RuntimeException: "Unable to create the cache directory (/[skipped]/app/cache/prod/twig/c7)." at /[skipped]/vendor/twig/twig/lib/Twig/Cache/Filesystem.php line 60
```
is raised sporadically.

I am suspecting it's race condition because:

* it happens during creation of first cache folders, when them are created in bulk;
* that folder is actually created and has the same creation time as an exception in log entry
![image](https://cloud.githubusercontent.com/assets/181212/11911584/1165ee6c-a623-11e5-8d3f-efcbcf92f0aa.png)
* the was similar behavior reported [previously](https://github.com/twigphp/Twig/pull/1583) but without resolution.

My assumption is that while two processes / threads [initialize the cache](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Cache/Filesystem.php#L59) concurrently them might:

1. try to `mkdir` the same folder simultaneously,
2. one of them acquire the lock and another got `false` from `mkdir`,
3. while the folder creation still isn't finished by the former process / thread, the latter one would get `false` from `is_dir` check, resulting in the exception.

Probably folder creation should be arranged with mutex, that must be unlocked before `is_dir` check.

**Comment by fabpot** [comment]
Closing as AFAIK, we do everything we can to prevent race conditions. But one good practice is to pre-generate Twig's cache ahead of time (before deployment) especially on highly loaded servers.
