### ISSUE TITLE
Unexpected string concatenation results

### ISSUE THREAD

**Issue by JohnONeill** [twigphp/Twig#1946]
Howdy –

We're attempting to doing something like 
```
<a href="{{base_url}}/path">
```
where `base_url` is something like `https://www.example.com/level1/level2`. 

Ideally we want the result `https://www.example.com/level1/level2/path` but it seems like Twig is producing the output `https://www.example.com/path` instead – and unfortunately string concatenation doesn't seem to work as expected either (maybe I'm using it incorrectly). Attempts:

```
<a href="{{base_url ~ "/path"}}">
<a href="{{base_url ~ '/path'}}">
<a href="{{base_url ~ '/path'}}">
<a href={{base_url ~ '/path'}}>
```

We're using version `1.23` since it's the latest stable version, which means that the new string interpolation isn't available. 

Any help would be much appreciated – thanks in advanced!

**Comment by xabbuh** [comment]
Are you sure that the value of the `base_url` variable isn't simply just `https://www.example.com`?

**Comment by JohnONeill** [comment]
Yeah – our exact code is
```
<li class="tabbar-tab">
  <a href="{{user_public_profile}}" class="tabbar-tab-link {{ on_everything_page ? 'is-active' }}">
    Everything
  </a>
</li>

<li class="tabbar-tab">
  <a href="{{user_public_profile}}/saved" class="tabbar-tab-link {{ on_saved_page ? 'is-active' }}">
    {{ num_saved }} Saved
  </a>
</li>
```
and oddly enough that first link is perfectly fine (it comes out to `https://www.example.com/level1/level2`)

**Comment by SpacePossum** [comment]
could you tweak http://twigfiddle.com/ges3g0 to reproduce the problem?

**Comment by stof** [comment]
I suggest you to add a ``{{ dump(base_url) }}`` in your template (you need to register the debug extension if it is not done yet, which you will know by seeing whether Twig knows the function already or no)

**Comment by JohnONeill** [comment]
Apologies! Seems like `user_public_profile` was undefined (it was actually something like `user_public_url`). Thanks for the help!

**Comment by stof** [comment]
@JohnONeill I suggest you to turn on strict_variables when developing, which would throw an exception when accessing undefined variables.

**Comment by JohnONeill** [comment]
Oh man, will do. Thanks @stof!
