### ISSUE TITLE
Twig 1.23.2 and typo in ExpresionParser.php

### ISSUE THREAD

**Issue by flylord** [twigphp/Twig#1956]
You have typo on 581. line. It should be $function but you have $functon

            if (!is_bool($functon->getDeprecatedVersion())) {
                $message .= sprintf(' since version %s', $function->getDeprecatedVersion());
            }

**Comment by chandon** [comment]
+1 ?

PHP Notice:  Undefined variable: functon in /home/visiint/symfony/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 581
