### ISSUE TITLE
Current v1.23.2 release broken due to a typo

### ISSUE THREAD

**Issue by ratza** [twigphp/Twig#1957]
Hi! I had the luck to update my dependencies 15 minutes after the release of v1.23.2.

The latest version has been released with a typo. The line 581 in `lib/Twig/ExpressionParser.php` reads:
```php
if (!is_bool($functon->getDeprecatedVersion())) {
```

The variable name of the variable should read `$function`.

Not sure if a pull request is needed as the release should be removed or marked as broken, and re-released with the small fix.

Thanks for the awesome work!

**Comment by SpacePossum** [comment]
duplicates https://github.com/twigphp/Twig/issues/1956
