### ISSUE TITLE
ExpressionParser bug

### ISSUE THREAD

**Issue by alx-bongard** [twigphp/Twig#1959]
Hello all, i have a error when i try do deploy a website.

twig/twig (v1.23.1) => OK
twig/twig (v1.23.2) => Error

``` php
Call to a member function getDeprecatedVersion() on a non-object in ......../vendor/twig/twig/lib/Twig/ExpressionParser.php on line 581
```

Thanks ;)

**Comment by Itaelle** [comment]
:+1: Same here!

**Comment by stloyd** [comment]
There was already release `1.23.3` fixing this issue - https://github.com/twigphp/Twig/releases/tag/v1.23.3.

**Comment by alx-bongard** [comment]
I will try this version, thanks @stloyd
