### ISSUE TITLE
[Suggestion] Make _self usable in form_theme tags

### ISSUE THREAD

**Issue by Phobetor** [twigphp/Twig#1961]
The [documentation](http://twig.readthedocs.org/en/1.x/deprecated.html#globals) states that:
As of Twig 1.x, the `_self` global variable is deprecated except for usage in the `from` and the `import` tags.
In Twig 2.0, `_self` is not exposed anymore but still usable in the `from` and the `import` tags.

I think the `form_theme` tag is pretty equal to `from` and `import`. Should `_self` be also usable in that tag? e.g.
```
{% form_theme form _self %}
```

I know that there is another suggestion (#1932) which also solves this situation but it looks more complicated than just using the logic already used for `from` and `import` tags.

**Comment by Tobion** [comment]
`form_theme` does not come from Twig but Symfony. So `_self` cannot be supported there. Also no need to open a new PR when you can just discuss this topic on the existing issue.
