### ISSUE TITLE
Can't parsing syntax inside anchor href

### ISSUE THREAD

**Issue by oknoorap** [twigphp/Twig#1963]
My code
```<a href="{{ variable }}">Test</a>```
it's always blank, but if variable is outsite it's works
```<a href="{{ variable }}">{{ variable }}</a>```

Any suggestion how to solve this?

**Comment by xabbuh** [comment]
Can you provide some code that reproduces your issue?

**Comment by Tobion** [comment]
Ideally reproduce the problem with http://twigfiddle.com/

**Comment by fabpot** [comment]
Closing as there is no feedback.

**Comment by ghost** [comment]
Same problem here:

`<input type=button onClick="location.href='{{ variable }}'">`

It results in blank.

I think it is cause of the ' char.

**Comment by SpacePossum** [comment]
Can you provide a failing sample, maybe something over at https://twigfiddle.com/ ?
If that doesn't work for you, can you maybe use something like `{{ dump(variable) }}` and let us know what the outcome is?

**Comment by ghost** [comment]
@SpacePossum 
I checked again, and it works. It was a fail of me, sorry.

**Comment by SpacePossum** [comment]
@runsy great to hear you resolved this, thanks for reporting back!
