### ISSUE TITLE
Warning when using `variable-name` with hyphen

### ISSUE THREAD

**Issue by di5abled** [twigphp/Twig#1967]
Hello, 

is it possible in Twig to add a warning if one is using an `variable-name` with an hyphen. 
Currently we are only getting `0` as the value if we are using such an variable name.

Because there was no explicit warning of Twig we searched in various other places until we finally found the error.

Adding such a warning to Twig could help other developers avoid this problem and time consuming searching for error.

**Comment by stof** [comment]
the point is that this is not a variable as far as Twig is concerned: it is the difference between 2 variables.

But this is likely to be caught when using strict variables (as it is unlikely that you have 2 variables defined named ``variable`` and ``name``). My advice is to always enable strict variables during development.

**Comment by fabpot** [comment]
Using strict variables is indeed the solution.

**Comment by di5abled** [comment]
thanks, I'll try this!
