### ISSUE TITLE
Filters on blocks?

### ISSUE THREAD

**Issue by cjonasw** [twigphp/Twig#1973]
This is what I would like to do (for ajax sites):

```twig
{% block content | json_encode() %}{% endblock %}
```

Or is there something else I could be doing?

**Comment by stof** [comment]
This can be done in a different way:

```twig
{% filter json_encode %}{% block content %}{% endblock %}{% endfilter %}
```

**Comment by cjonasw** [comment]
Thanks! Exactly what I wanted. Is it missing in the documentation?

**Comment by stof** [comment]
No. The filter tag (allowing to apply filters on a whole section of a template) is documented here: http://twig.sensiolabs.org/doc/tags/filter.html

**Comment by cjonasw** [comment]
Nice! Thanks dude
