### ISSUE TITLE
[Best Practice] Naming extensions

### ISSUE THREAD

**Issue by mattdrose** [twigphp/Twig#1975]
I can't find any documentation on the best practices for [naming extensions](http://twig.sensiolabs.org/doc/advanced.html). I'm assuming it should follow the the lowercased snake_case standard. If so, it'd be helpful to have a best practice badge added to the docs.

**Comment by fabpot** [comment]
"lowercased snake_case" is indeed how we name them internally, but Twig does not really care, so I'm not sure we need to enforce anything here. It's up to you :)
