### ISSUE TITLE
starts with not working anymore in 1.6.5

### ISSUE THREAD

**Issue by dadixon** [twigphp/Twig#1977]
{% if 'Fabien' starts with 'F' %}
{% endif %}

throws an error now.

Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected token "name" of value "starts" ("end of statement block" expected) in "nav.twig" at line 6'

**Comment by stof** [comment]
1.6.5 ? This release is **older** than the ``starts with`` test. It is not about "not anymore" but about "not yet" working

**Comment by dadixon** [comment]
Oh ok. I'm running composer and that's the latest version available

Be Blessed

**Comment by stof** [comment]
The latest Twig version is 1.24.0

**Comment by dadixon** [comment]
Thanks
