### ISSUE TITLE
Null-coalescing operator (??): The "defined" test only works with simple variables

### ISSUE THREAD

**Issue by mnpenner** [twigphp/Twig#1979]
The null-coalescing operator (??) should work with "non-simple" variables (e.g. functions or filters that return `null`). 

As an example,

``` twig
{{ "A" ?? log('XXX') ?? "B" }}
```

This throws an exception, where `log()` is a function that returns `null`. I don't believe it should throw.

~~I don't have PHP7 to verify with, but I'm pretty sure that PHP7 wouldn't throw an exception.~~

``` php
Psy Shell v0.6.1 (PHP 7.0.2 — cli) by Justin Hileman
>>> function a() { return null; }
=> null
>>> a() ?? 'b'
=> "b"
```

**Comment by gadelat** [comment]
Here is the actual error to make this report more useful

> Uncaught Twig_Error_Syntax: The "defined" test only works with simple variables in "index.twig" at line 12. in {redacted}/twig/lib/Twig/Node/Expression/Test/Defined.php:37

From the message it's obvious this is not a bug and this issue is a feature request

**Comment by mnpenner** [comment]
Never claimed it was a bug; just said it's inconsistent with the `??` operator in PHP 7. It would make sense to have it behave the same.

So yes, please consider this a feature request.

**Comment by chiqui3d** [comment]
Hello @fabpot, for me not work with:

`{{observa[1] is defined ?? observa[1]}}`

error:

`The "defined" test only works with simple variables.
`

**Comment by xabbuh** [comment]
I think you may want to use something like `{{ observa[1] ?? '' }}`.

**Comment by chiqui3d** [comment]
thanks but not work.

I finally put it that way:

`{{observa[1] is defined ? observa[1] : "" }}`

**Comment by apfelbox** [comment]
@chiqui3d quick heads up:

You don't need the empty state, this works as well: `{{ observa[1] is defined ? observa[1] }}` (as well as `{{ observa[1] | default("") }}`).

**Comment by chiqui3d** [comment]
wonderful, thanks very much
