### ISSUE TITLE
[Request]Globally replace null/empty template values by specific string

### ISSUE THREAD

**Issue by jin78** [twigphp/Twig#1982]
Currently there is no way to perform either a global replacement either per template or app-wide of null/empty string values.

E.g:

{# Where replace_empty_string() would be an actual function added to Twig #}
{%
    replace_empty_string("Nothing to see here...")
%}

**Comment by iltar** [comment]
This looks like a debugging tool to me, why would you need this?

**Comment by jin78** [comment]
Not actual debugging no.

For example, some db datasets may contain null or empty column.

As it stands I have to do a if statement on every single potential null value to replace its contents to a more user-friendly message like "not available" or something like it.

Is my explanation clear?

**Comment by xabbuh** [comment]
You can already do this with something like `{{ var|default('nothing to see here') }}`.

**Comment by jin78** [comment]
Does this applies to every single variable in a template?

**Comment by xabbuh** [comment]
No, but imho that wouldn't make sense as a generic solution. I think if you wanted to have that as a global option, you would be better of with creating a custom extension that does this job for you.

**Comment by jin78** [comment]
I don't agree on that point.

I think it would be much easier to have a generic solution so it wouldn't be required to test with if statements every single var.

In the end it would be up to the developer to make the decision or not to use this feature.

Currently, my templates are bloated with if myVar is not empty stuff.

Not clean.

**Comment by iltar** [comment]
In 2+ years of Symfony and twig, I've actually never seen anybody need this. I think this is actually pretty hard to implement as well as you have to start working with scopes. If you have a template where you define that, you might end up assigning default values to "imported" variables.

To me this looks like something you just want to implement and not having think about the actual values that are displayed. I think this is the wrong approach and you should think about what you render where. The default filter is the way to go imo.

**Comment by jin78** [comment]
OK, so I’ll demonstrate a simple example of what I’d like to achieve, let’s say I have an array of customer with first/last name and an address. How to apply default filter on all array keys of this ‘customer’ array?

In other words, applying default recursively.

Am I clear or not?

**Comment by fabpot** [comment]
I don't see how applying a default to value for all variables might make sense; I have the same concern as @iltar. Using `|default()` seems like it covers your use case pretty well. And of course, you can create a Twig extension to do so if that's really what you want to achieve. Anyway, that's not something we want to have in core, so I'm closing this issue.
