### ISSUE TITLE
DATE filter

### ISSUE THREAD

**Issue by nicovak** [twigphp/Twig#1983]
The date filter of a null variable gives the date of today. I think that the filter should return a null or an empty string, because you display a data which is corrupted.

EX

`{{ null | date('d-m-Y') }}` return the date of today

**Comment by stof** [comment]
Changing this would be a BC break, so it is not possible

**Comment by xabbuh** [comment]
And by the way, this behaviour [is documented](http://twig.sensiolabs.org/doc/filters/date.html):

> If the value passed to the date filter is null, it will return the current date by default.

**Comment by nicovak** [comment]
Ok, thank you, but I still think that the behaviour is illogic. I close the issue.

**Comment by sstok** [comment]
For now `{{ null is empty ? '' : date('d-m-Y') }}`

Maybe add an arguments like `empty_on_null` or something?
`date` is the only filter (it seems) that returns a result on null, all other filters simple return an empty string.

**Comment by thedamon** [comment]
I find this logic pretty weird as well. It basically requires adding the `is empty` thing any time it is used

**Comment by ninsuo** [comment]
You can still overwrite this behavior to fit your personal needs.

```php
        $twig->addFunction(new \Twig_SimpleFunction('date', function($date) {
            return is_null($date) ? null : date($date);
        }));
```

**Comment by stof** [comment]
@ninsuo except that your implementation for non-null values is wrong, as it supports far less things that the core filter

**Comment by fabpot** [comment]
Changing the current behavior is not possible as it would be a BC break. I'm not convinced about adding an argument as it would make it more verbose that the current workarounds. So, let's close.

**Comment by stof** [comment]
Another option is to deprecate passing `null` entirely.
