### ISSUE TITLE
autoscape doesn't work in textarea tag

### ISSUE THREAD

**Issue by karousn** [twigphp/Twig#1985]
``` html
<textarea> {% autoescape true html %} <b> {% endautoescape %}</textarea>
```
output : 
![autoscape](https://cloud.githubusercontent.com/assets/1721960/12844469/b38a35d4-cbff-11e5-9a72-cfc60dec7f2a.png)

**Comment by stof** [comment]
Well, you are not using any Twig display syntax here, so there is no autoescaping in place (meaning disabling it is useless).
Just look at the source of your page to see how it looks like.

**Comment by karousn** [comment]
@stof : yes i make mistake, i update my comment , but i have the same result !

**Comment by Baachi** [comment]
@karousn The `autoescape` filter only affects variables.

**Comment by xabbuh** [comment]
@karousn see http://twigfiddle.com/t8ecvq for how Twig behaves depending on what and how you generate the output
