### ISSUE TITLE
Nested loop variable scope bug

### ISSUE THREAD

**Issue by Pridit** [twigphp/Twig#1988]
Encountered a strange issue with trying to call `loop.index` within a nested loop, doesn't seem to be apart of the scope and I get an error thrown saying it's undefined. However if I call the loop variable at any point outside the nested loop then it works perfectly fine in the nested one.

**Works**:
```
{% for game in games %}
    {{ loop.index0 }}
    {% for company in companies[loop.index0] %}
        {{ company.name }}
    {% endfor %}
{% endfor %}
```

**Breaks**:
```
{% for game in games %}
    {% for company in companies[loop.index0] %}
        {{ company.name }}
    {% endfor %}
{% endfor %}
```

**Throws**:
Notice: Undefined index: loop in C:\xampp\htdocs\vendor\twig\twig\lib\Twig\Environment.php(403) : eval()'d code on line 272

I'm relatively new to Twig, so let me know if I'm just doing something wrong but it seems like a bug.

**Comment by iltar** [comment]
I did find a bit of documentation here: 

> Using the loop variable within the condition is not recommended as it will probably not be doing what you expect it to. For instance, adding a condition like loop.index > 4 won't work as the index is only incremented when the condition is true (so the condition will never match).

Maybe you can check what the generated code looks like and see if this can be fixed in the compiler.

**Comment by HeahDude** [comment]
You should use a `set` tag to share the scope of the first loop in the condition of the second since a condition seems apart of the body of a loop :
```twig
{% for game in games %}
    {% set idx = loop.index0 %}
    {% for company in companies[idx] %}
        {{ company.name }}
    {% endfor %}
{% endfor %}
```

**Comment by Pridit** [comment]
I read that part of the documentation when I was investigating the issue but it didn't seem like it fell under it, but it must have considering the issue I ran into.

Never came across my mind to just define it and then use it within the scope. Works perfectly fine now, much appreciated for your suggestions.
