### ISSUE TITLE
Float value in HTML attribute and Locale fr_FR.utf8

### ISSUE THREAD

**Issue by mehdi-ghezal** [twigphp/Twig#1989]
Hello,

I got a potential issue with output float value in an HTML attribute.
- Twig version : 1.23.3
- PHP : 5.6.17
- Debian GNU/Linux 8
- Locale fr_FR.utf8 installed

My PHP configuration in my boot file :

```php
mb_internal_encoding("UTF-8");
setlocale (LC_ALL, "fr_FR.utf8");
```

The twig code :

```html
<div class="progress-bar" data-percentage="{{ shippingUsage }}"></div>
```

If the value of **shippingUsage** is 8.7 (float), Twig print 8,7 (string with a comma). 

It seems to be common sens but I cannot disable this behaviour or I don't find how to do. I want to display the float value because it's use by JS for setup my progress bar.

I try to disable escaping and I try the raw filter ; it doesn't change anything. If I uninstall the fr_FR.utf8 from my system (Debian), the output still 8.7, US format of the number of course.

Did I miss something ?

PS : For now I have a quick workaround with round filter or casting value to int.

Mehdi

**Comment by SpacePossum** [comment]
Hi,
Please take a look at, http://twig.sensiolabs.org/doc/filters/number_format.html

```twig
{{ shippingUsage|number_format(2, '.') }}
```

**Comment by mehdi-ghezal** [comment]
Hi,

I know this filter but I was trying to understand what append.
I was so focus on Twig that I don't notice that behaviour is driven by PHP when it cast my float to string for output my HTML...

The magic of implicit type conversions... my mistake :)
Thank you :)
