### ISSUE TITLE
Allowed memory size of xxxxx bytes exhausted (tried to allocate 65488 bytes)

### ISSUE THREAD

**Issue by abdielcs** [twigphp/Twig#1991]
I'm getting this error in a symfony 2.7.9 almost fresh installation, I thought that could be related to one specific bundle but happens with all that I try. The problem occurs when I override any template from a bundle in the app/Resources folder.
```
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\symfony\2.7\install\source\WiseCar\app\cache\dev\classes.php on line 3195
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\symfony\2.7\install\source\WiseCar\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Loader\FilesystemLoader.php on line 139
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\symfony\2.7\install\source\WiseCar\app\cache\dev\classes.php on line 4833 
```
In those lines in classes.php I found
```
protected function loadTemplate($template, $templateName = null, $line = null, $index = null)
{
..
return $this->env->loadTemplate($template, $index); //line 4833 
..
}
```
and
```
public function loadTemplate($name, $index = null)
{
$cls = $this->getTemplateClass($name, $index); //line 3195
..
}
```
In the case of FilesystemLoader.php there is no line 139.

I't happen overriding the layout of FOSUserBundle and also with layout of EasyAdminBundle. No matter how much I increase the memory_limit in php.ini, it always happen, so it look like an infinite loop. The twig template only contain the line

`{% extends 'FOSUserBundle::layout.html.twig' %}`

Since it happen with more than one bundle I think that this is the right repository to report.

twig/extensions v1.3.0
twig/twig  v1.24.0

Thanks in advance.

**Comment by stof** [comment]
Could it be that your own template is overwriting ``FOSUserBundle::layout.html.twig``, meaning that it would then actually extend itself ?

**Comment by abdielcs** [comment]
In FOSUserBundle in Resources/views/layout.html.twig there is just the full html like
```
<!DOCTYPE html>
<html>
    <head>
...
</html>
```
and then in my symfony installation in app/Resources I create a FOSUserBundle/views/layout.html.twig with one only line 
`{% extends 'FOSUserBundle::layout.html.twig' %}`
That should work right?

**Comment by stof** [comment]
The issue in your case is that ``app/Resources/FOSUserBundle/views/layout.html.twig`` is overwriting the template named ``FOSUserBundle::layout.html.twig``.
This means that the parent template is **your** template again (which again extends itself and so on)

**Comment by abdielcs** [comment]
Uff, in my head that was the way of override any bundle template, I made a huge mistake, Thanks a lot and sorry for your time lost.
