### ISSUE TITLE
Avoid using realpath in Twig_Loader_Filesystem

### ISSUE THREAD

**Issue by edefimov** [twigphp/Twig#1994]
As of twig 1.18.0 the findTemplate method from the class Twig_Loader_Filesystem uses internally realpath function to cache the actual path to the target template. However the result of findTemplate method is used as the cache key for given template. This cause an error of mismatching the cache filenames when application is built on separate server and then is deployed to backend. In such a case absolute path on backend and build server is different and actual cache generating will be done the second time after deploying when template will be needed for the first time.

**Comment by fabpot** [comment]
see #2127
