### ISSUE TITLE
Non ASCII characters converted to HTML entities.

### ISSUE THREAD

**Issue by konrados** [twigphp/Twig#1995]
I'm really sorry for posting here, as this probably is not an issue, but I've struggling with this for the last 3 hours and I simply run out of options.

I tried on #symfony irc channel and [StackOverflow](http://stackoverflow.com/questions/35550166/twig-replaces-non-ascii-characters-with-entities)  without a success.

I believe this is my last chance...

When I do this:

```
{% autoescape false %}
    <script>
            alert('ółż');
    </script>
{% endautoescape %}
```

The 'ółż" characters are converted to entities, resulting in:

`alert('&oacute;&#322;&#380;');`

I don't want this. I don't want any conversion... but nothing works.

This only happens in `script` section. Above it those characters are intact. 

Please bear in mind, that "alert" or "confirm" functions don't convert entities back to UTF-8, they display strings as they are.

**Comment by SpacePossum** [comment]
If you don't want Twig to do anything at all, try the `{% verbatim %}` tag.
http://twig.sensiolabs.org/doc/tags/verbatim.html

**Comment by konrados** [comment]
Thanks SpacePossum, but it didn't help, I do this:

```
{% verbatim %}
<script>
            alert('ółż');
</script>
{% endverbatim %}
```

And I still see entieties.

**Comment by fabpot** [comment]
Twig itself does not change HTML contents, so the conversion comes from something else.

**Comment by konrados** [comment]
@fabpot ach, Fabien himself answered :) Thanks.

Indeed, that's my stupidity & sclerosis. Someday I wanted a better html source code formatting, more readable (functions like form_start produce a non-formatted, one-line code, I wanted indentation etc. So I did this: http://stackoverflow.com/a/35080486/5733557 and forgot about it :) )

And this piece of code is responsible for the issue:

`$html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');`

Thanks again. Seems I have a right to close this issue, if so then I'll do it.
