### ISSUE TITLE
Add function: array_search

### ISSUE THREAD

**Issue by JHGitty** [twigphp/Twig#2003]
http://php.net/manual/de/function.array-search.php

**Comment by iltar** [comment]
What would be the use-case of searching for keys in a hashmap in your view?

**Comment by Muriano** [comment]
@JHGitty Do you mean a filter? In this case, you alway can make a [custom filter ](http://twig.sensiolabs.org/doc/advanced.html#filters)

**Comment by fabpot** [comment]
Not sure it belongs to the core. In any case, as nobody really ask for something similar in the past, I'm closing it for now.
