### ISSUE TITLE
applying form_start or form_end on a form 

### ISSUE THREAD

**Issue by sdmg15** [twigphp/Twig#2004]
Hi,
I remark that went you start a form with `form_start(myForm)` 
and start processing it without closing it with `form_end(myForm)` ,
it doesn't display any error and for that, we are not informed about what is happen 
why this ?

**Comment by Tobion** [comment]
form_start just renders the form start tag. No errors or fields. form_end renders all the stuff that has not been rendered yet.
I refer you to the symfony form doc. Also this is about symfony, not twig: https://github.com/symfony/symfony
