### ISSUE TITLE
Auto reload when template changed in long running process (PHP-PM)

### ISSUE THREAD

**Issue by marcj** [twigphp/Twig#2007]
Hi!

Just wanted to develop some workaround to get Twig correctly working in php-pm, but no luck due to the fact, that Twig generates classes based on name generation that doesn't include the filemtime. I tracked it down to this line:
https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L384

If a template has already been loaded, and subsequent changed Twig doesn't check if it's still fresh when its class is already registered, which makes perfectly sense since PHP can't overwrite an existing class. So I thought the only way could be to implement the Twig compiling in another way than creating php classes, but this would be enormously much work.

@fabpot, do you have any idea to get that working?

The cheapest way yet would be to hack into Twig and read all read template files and pull they into the watched files, so PHP-PM restarts its worker automatically if one of those files change. I guess I'm going to do exactly this for now, but wonder if there is a still better way.

**Comment by stof** [comment]
@marcj auto_reload is a development feature. AFAIK, you already have to restart your php-pm process any time you change a class (to make it reload the class definition), so this is already part of the development workflow. If PHP-PM has hot-reloading, the best way is probably to hook into hot-reloading to watch templates too.

Including the filemtime in the compiled class name is impossible in the current Twig architecture: Twig does not know the latest modification time of a template. It is only able to ask loader whether it was before or after a specific time. Asking loader to return a mtime would be a totally different architecture for the loader system (and harder to implement for some cases, as the loader is not always able to determine such a mtime)

**Comment by stof** [comment]
> So I thought the only way could be to implement the Twig compiling in another way than creating php classes, but this would be enormously much work.

This would force to rewrite Twig almost entirely, so not an option IMO

> The cheapest way yet would be to hack into Twig and read all read template files and pull they into the watched files, so PHP-PM restarts its worker automatically if one of those files change. I guess I'm going to do exactly this for now, but wonder if there is a still better way.

The way to do it in Twig would probably be to wrap the filesystem loader in a special loader delegating all calls but calling ``ppm_register_file`` (the file name is the cache key for the filesystem loader)

**Comment by marcj** [comment]
Thanks for your feedback. I feared that it is indeed too much work to get that working in twig itself. The `ppm_register_file` [works so far perfectly](https://github.com/php-pm/php-pm-httpkernel/commit/0f5b1a32ff4da9af6814e84b0d105c27941b37bb), so I guess we could close this :) :+1:

**Comment by stof** [comment]
@marcj your implementation is broken in case the twig.loader service is a chain loader wrapping multiple loaders.

**Comment by marcj** [comment]
Yes, but I have never worked with Twig that intensively especially not with different loader, so atm no idea how to cover all configurations.
