### ISSUE TITLE
Unexpected buffers output on fatal error

### ISSUE THREAD

**Issue by psylosss** [twigphp/Twig#2008]
When fatal error occurs, all the PHP buffers flushes to output (in browser). It may be very undesirable, especially on [some cases](https://github.com/Elao/ErrorNotifierBundle/issues/58). 

code from `TwigTemplate::render`:

```
    public function render(array $context)
    {
        $level = ob_get_level();
        ob_start();
        try {
            $this->display($context);
        } catch (Exception $e) {
            while (ob_get_level() > $level) {
                ob_end_clean();
            }

            throw $e;
        }

        return ob_get_clean();
    }
```

Fatal error is not exception, so `ob_get_clean()` not invoked and when script dies, we got whole rendered template in browser. 

To solve this issue I registered listener onKernerRequest:

```
    public function onKernelRequest(GetResponseEvent $event)
    {
        // Production mode only
        if ($this->kernel->getEnvironment() !== 'prod') {
            return;
        }

        // Clean all output buffers on fatal error
        register_shutdown_function(function(){
            $level = ob_get_level();
            while (ob_get_level() >= $level) {
                ob_end_clean();
            }
        });
    }
```

Is it true way? Is this issue of twig or application?

**Comment by Tobion** [comment]
How does your error handler look like?

**Comment by psylosss** [comment]
I had no custom error handlers except [this one from ElaoErrorNotifierBundle](https://github.com/Elao/ErrorNotifierBundle/blob/master/Listener/Notifier.php#L192)

**Comment by fabpot** [comment]
Does not look like something we can deal with in Twig, it really depends on your error handler and the whole project. Closing.
