### ISSUE TITLE
Unable to compile Twig C extension with PHP 7

### ISSUE THREAD

**Issue by sylvaindeloux** [twigphp/Twig#2012]
I can't install the C extension of Twig on a fresh PHP7 installation (with pear repository).

How to reproduce (Dockerfile) :

    FROM php:7-fpm
    ENV DEBIAN_FRONTEND noninteractive

    RUN pear channel-discover pear.twig-project.org && \
        pear install twig/CTwig

And the compilation fails :

     cc -I. -I/tmp/pear/temp/CTwig -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserlwdVZL/CTwig-1.24.0/include -I/tmp/pear/temp/pear-build-defaultuserlwdVZL/CTwig-1.24.0/main -I/tmp/pear/temp/CTwig -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/CTwig/twig.c  -fPIC -DPIC -o .libs/twig.o
    /tmp/pear/temp/CTwig/twig.c:23:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
     #include "ext/standard/php_smart_str.h"
                                            ^
Actually, in PHP7 ``etc/standard/php_smart_str.h`` has been renamed to ``etc/standard/php_smart_string.h``.

**Comment by fabpot** [comment]
The Twig extension is not compatible with PHP 7.
