### ISSUE TITLE
unexpected 'finally

### ISSUE THREAD

**Issue by gerson22** [twigphp/Twig#2014]
unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in vendor/twig/twig/lib/Twig/Environment.php on line 369

**Comment by gerson22** [comment]
try {
            $template = $this->loadTemplate($name);
        } catch(Exception $ex){
            echo $ex;
        }
        //this part fail in the goodady's server
        /*finally{
            $this->setLoader($current);
        }*/

**Comment by ninsuo** [comment]
Hello, 

I recommend you to use a stable Twig version: 

```
composer require twig/twig ^1
```

Note that the one you installed (2-dev) requires PHP >= 5.5

**Comment by Aldairnatan** [comment]
Thank you, I managed to solve the problem
