### ISSUE TITLE
Documentation not clear about 'sameas' and 'null' tests

### ISSUE THREAD

**Issue by victorsmirnov** [twigphp/Twig#2018]
I think the documentation might be improved and I suggest to add the following notes

In the [Comparison Operators](http://twig.sensiolabs.org/doc/templates.html#comparisons) section I suggest to add the following

- `is same as` does strict comparison. In short `===` in Twig is `is same as` and `!==` in Twig is `is not same as`. 
- `is null` does strict comparison against `null`, it is the same as `=== null`.

In the [`null`](http://twig.sensiolabs.org/doc/tests/null.html) section I suggest to clarify that the comparison is strict. One might think that empty string or `false` are consider as `null` values. But I believe this is not the case.

`same as` is described under the Tests section in the manual. But I think it might be good to have the same explanation in the 'Twig for Template Designer' document too.

Should I create pull request for this?

Let me know if I'm wrong.

**Comment by stof** [comment]
> But I think it might be good to have the same explanation in the 'Twig for Template Designer' document too.

A better solution would be to have a link to the dedicated doc instead of duplicating it

**Comment by victorsmirnov** [comment]
>> But I think it might be good to have the same explanation in the 'Twig for Template Designer' document too.
> A better solution would be to have a link to the dedicated doc instead of duplicating it

This should work too. What I do want to see is a note that strict check is also available and quick explanation or example how it should be done. May be some code sample and link to the `same as` test documentation. For example

```
    {% if isAdd is not null %}
        <ADD>{{ isAdd ? 'TRUE' : 'FALSE' }}</ADD>
    {% endif %}
```

I think it's important to show in the document for template designers how to distinguish `null` values and values that are silently considered equal to null. It might happen that designer even do not understand the issue. As for me I just wrote `===` in the template and wondered who broke the tests :)

**Comment by fabpot** [comment]
Most of the time, designer should not have to understand what a strict comparison is. Actually, if he needs to understand the difference, it means that the context passed to the template is not good enough. We added strict comparison because people asked for it, but if you ask me, nobody should use them in a template.
