### ISSUE TITLE
Get file name after include

### ISSUE THREAD

**Issue by GuigZ-** [twigphp/Twig#2020]
I everybody,

I need to get filename in my env after an inclusion.
That information is required in my custom method.

`<div>
{{customMethod('File name is ok')}}
{% include 'template.tpl' %}
{{customMethod('File name is not ok')}}
</div>`

In my second call, to my custom method, i get the filename of including template.

**Comment by xabbuh** [comment]
What exactly do you mean? What does your `customMethod` look like?

**Comment by GuigZ-** [comment]
I try to get a current filename.

I get the filename with Environment model. $env->getCompiler()->getFileName().

**Comment by stof** [comment]
@GuigZ- please paste the code of your ``customMethod``, so that we can try to understand what is going on

**Comment by GuigZ-** [comment]
```php
public static function twigFilter(Twig_Environment $environment, $value, $module = null)
    {
        # Current file name
        $file      = $environment->getCompiler()->getFileName();
        $file_name = basename(strstr($file, strrchr($file, '.'), true));

        return Translate::findTranslations($file_name, $value, $module);
    }

**Comment by GuigZ-** [comment]
Up ? :(

**Comment by fabpot** [comment]
You should never use `getCompiler()` from a filter. That's not supported as you figured out not reliable for your use cas.
