### ISSUE TITLE
Add a without filter, which excludes elements from an array

### ISSUE THREAD

**Issue by dawehner** [twigphp/Twig#2024]
Let's assume you have an array with 3 elements, `footer, header and body` and you want to exclude one of them.

What about introducing a filter which works like that:

```
<strong>No author:</strong> {{ quote | without('author') }}.
```

The implementation could be something like:

```
  if ($element instanceof ArrayAccess) {
    $filtered_element = clone $element;
  }
  else {
    $filtered_element = $element;
  }
  $args = func_get_args();
  unset($args[0]);
  foreach ($args as $arg) {
    if (isset($filtered_element[$arg])) {
      unset($filtered_element[$arg]);
    }
  }
  return $filtered_element;
```

Any thoughts about it?

**Comment by HeahDude** [comment]
Actually, you are returning an array which will be converted to string by `{{ }}` so this example looks broken.

Beside that, I agree Twig core miss a way to unset values. Also `with` keyword is already used and `without` in this context could be misleading.

What about:
```twig
{% do some_array|unset_keys('key1', 'key2') %}
{# or #}
{% set filtered = array|unset_keys('key') %}
```

Note that you can already use an `if` in `for` loops which allows:
```twig
{% for key, value in array if key not in ['key1', 'key2'] %}
{# ... #}
```

**Comment by fabpot** [comment]
I'm closing this issue as this ticket did not get much traction and I'm not a big fan of easing manipulating variables in the templates (`unset_keys`).
