### ISSUE TITLE
Compiling C extension with php7 fatal error: ext/standard/php_smart_str.h no file

### ISSUE THREAD

**Issue by djfordz** [twigphp/Twig#2026]
in php 7 php_smart_str.h has been renamed to php_smart_string.h thus the compiler fails at this point.
I wish this was as easy as fixing the name, however after changing the file to the correct php7 named file another compile error:
/usr/include/php/Zend/zend_variables.h:112:15: note: expected 'zval * {aka struct _zval_struct *}' but argument is of type 'zval ** {aka struct _zval_struct **}'
 ZEND_API void _zval_ptr_dtor(zval *zval_ptr ZEND_FILE_LINE_DC);

Thus the C extension does not work with php7 as this juncture

**Comment by stof** [comment]
This is known. the C extension has not been rewritten for PHP 7.

Note that reading an attribute is already faster on PHP 7 than when using the C extension in PHP 5, meaning that porting the extension is not considered a priority at all.
