### ISSUE TITLE
Extend templates without using blocks

### ISSUE THREAD

**Issue by barbushin** [twigphp/Twig#2027]
I have layout template
```
<html>
<body>
{% block content %}{% endblock %}
</body>
</html>
```
And many child templates like this
```
{% extends 'layout/default.twig' %}
{% block content %}
    <p>content</p>
{% endblock %}
```
And it's very annoying that every single child template in Twig must include `{% block content %}...{% endblock %}` to be extended by parent block, otherwise there will be error: **A template that extends another one cannot have a body.**

Is there any solution to bind all child template output(that is not located in any block) in some variable, and then use it to paste in parent template? Like this:

Layout
```
<html>
<body>
{{ _context.childOutput }
</body>
</html>
```
Child
```
{% extends 'layout/default.twig' %}
<p>content</p>
```
It will make child templates code more compact and there will be no dependency from parent templates blocks name.

**Comment by stof** [comment]
But this is much less flexible (you must have all content in a single place), would require a rewrite of all Twig template rendering and would break BC (a child template can currently have *some* content outside blocks, for instance variable declarations, which is executed before starting the execution of the parent template)

**Comment by barbushin** [comment]
It's not less flexible until is optional. I mean you can still use blocks, but if some part of templated is not inside block, then it can be assigned to some special variable or special block name. It will be perfect solution for pages main "content" blocks, usually the most popular kind of templates.

**Comment by stof** [comment]
@barbushin I never had a layout where a single block was available as hook.

and as I said, this would require changing totally the way a template is executed when it extends another one, which is a BC break and cannot be done.

**Comment by barbushin** [comment]
Maybe I'm doing something wrong, but the thing is that me and my team don't use blocks for settings `<head><title>` and etc. This kind of syntax makes us feel crazy:
**Parent**
```
<head>
<title>{% block title %}{% endblock %}</title>
<meta name="description" content="{% block description %}{% endblock %}" />
</head>
<body>
{% block body %}{% endblock %}
</body>
```
**Child***
```
{% block title %}Some title{% endblock %}
{% block description %}Some description{% endblock %}
{% block body %}...{% endblock %}
...
```
So we just use global variables, like this:
**Parent**
```
<head>
<title>{{ page.title }}</title>
<meta name="description" content="{{ page.description }}" />
</head>
```
**Child**
```
{% block body %}...{% endblock %}
```
And just assigning global vars in controllers because anyway they're generated dynamically.

I don't want to say that blocks are bad idea, but sometime the only thing you need to use it, is to pass some content data to parent template, and it will be great if there will be an option to do this without extra code and woring about content block name matching.

**Comment by fabpot** [comment]
Thanks for your idea @barbushin but doing what you suggest would change Twig's fundamentals. So, I'm closing this as it will never happen.
