### ISSUE TITLE
consider increasing leniency in referenced file paths

### ISSUE THREAD

**Issue by olets** [twigphp/Twig#2030]
Twig will break if you attempt to include "x.html" with `{% include 'x.html ' %}`. That's reasonable, and of course I don't want to encourage anyone to go throwing around extra spaces, but to my thinking it would be friendly to quietly trim off leading or trailing whitespace in paths like this.

**Comment by fabpot** [comment]
What about a file that indeed contains some whitespaces? That's legitimate as well. I don't the issue here. You get an error, you fix your mistake, done.

**Comment by olets** [comment]
You're absolutely right, I wasn't considering file names with leading or trailing whitespace
