### ISSUE TITLE
Convenient tag escaping feature 

### ISSUE THREAD

**Issue by a2xchip** [twigphp/Twig#2032]
Hello guys! **It is feature request** and **question**.

As we know batch of modern frameworks use the same ```{{}}``` and ```{%%}``` tags as Twig (Of course it is Twig's and Django templates merit :) ). But it makes usage of Twig with these js frameworks inconvenient. For example i can't use semi-pure angularjs or react with my favorite template engine in Symfony projects. And ```verbatim``` or ```{{ '{{' }} {{ '}}'}}``` is a wild thing. 

Today I found that Blade resolved this issue by ampersand prepending ```@{{ fs }} --> out {{ fs }}```. Looking into Twig source and api didn't help much to understand if it is possible to implement by extending or it is only possible by source code update. 

**The question is**: Is there such implementation I don't know about or is it possible to implement it fast by extending Twig core? Or are there plans to implement it in Twig core? Thanks!

**Comment by fabpot** [comment]
see #2128

**Comment by a2xchip** [comment]
@fabpot Thank you very much!!!! :+1:
