### ISSUE TITLE
Add code to third-party bundle templates in non intrusive way

### ISSUE THREAD

**Issue by Ziiweb** [twigphp/Twig#2034]
Hi,

I know it is possible to override a template of a bundle. But.. is it possible to add _additional code_ to a template? Im thinking about this possiblity after writing this question: http://stackoverflow.com/questions/37125940/symfony-and-twig-conditions-in-templates?noredirect=1#37125940

Sorry if this is a symfony issue maybe..

**Comment by fabpot** [comment]
This is indeed a Symfony question :) Twig does not have the notion of "bundles".
