### ISSUE TITLE
add support for a "list" tag

### ISSUE THREAD

**Issue by HeahDude** [twigphp/Twig#2035]
I've got a use case where I get a view var, let's name it `data` which is a simple array without keys and holding a code, a message and a timestamp.
Currently, one can use:
```twig
{% set code, message, timestamp = data[0], data[1], data[2] %}
```

So I quickly made a `list` tag based on `set` to be able to do:
```twig
{% list code, message, timestamp = data %}
```
Which I find much cleaner.

Is that something that would be interesting in core?

Thanks!

**Comment by fabpot** [comment]
I don't think that it belongs to core. Besides that, I don't like the fact that this is not really "explicit" when reading the code. What if data has more than 3 entries, or less, ...
