### ISSUE TITLE
[RFC] Make Intl extension work when no PHP Intl extension is available

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#2036]
### Context

I know that failing hard is the right thing to do for most errors. For example, if `date.timezone` is not set in php.ini, Twig refuses to work. But the solution to this problem is trivial: change one file, restart, done!

However, when you don't have the PHP `intl` extension, for most people there is no solution possible. You can't install that damn extension in a simple way.

### Problem

If you don't have the PHP intl extension, the Twig Intl extension fails hard and the application explodes.

### Proposal

In the Symfony Demo app we use the Twig Intl extension, but we've made it work for people who don't have the `intl` PHP extension: https://github.com/symfony/symfony-demo/pull/335/files

My (crazy) proposal: could we update Twig Intl to fallback to English-only when the PHP intl is not available? As you can see, it's a matter of adding a few lines of code and the maintenance will be minimal.

**Comment by fabpot** [comment]
There is no intl support in Twig :)

**Comment by javiereguiluz** [comment]
@fabpot my bad! Do you have some magic command to move this issue to https://github.com/twigphp/Twig-extensions/issues? Thanks!

**Comment by javiereguiluz** [comment]
Moved it to https://github.com/twigphp/Twig-extensions/issues/177
