### ISSUE TITLE
[feature request] pass macro as param (callback fashion)

### ISSUE THREAD

**Issue by quazardous** [twigphp/Twig#2037]
I've spotted this request here and there on the web: be able to pass a macro as a param to another macro.

I will illustrate the benefit with a case.

Say you need to create a macro for a list paginator. As it you need to pass a lot of data to tell the paginator how to create the URL (route name, url params, get params, etc).

If we could pass a macro handling the url generation it will be a lot nicer ans easier to reuse.

``` twig
{% macro paginator(page, pages, dourlmacro) %}
...
{{ call dourlmacro(page) }}
...
{% endmacro paginator %}

...

{% macro dourl(page) %}
<a href="{{ path('route', {'page': 'download'}) }}">{{ page }}</a>
{% endmacro dourl %}
```

the paginator call:

``` twig
{{ helpers.paginator(page, pages, helpers.dourl) }}
```

On top of that the next step could be inline-closure-like-macro (day dreaming mode):

``` twig
{{ helpers.paginator(page, pages, macro (page) use (foo) {>
<a href="{{ path('route', {'foo': foo, 'page': page}) }}">{{ page }}</a>
<}) }}
```

This feature could be related to #1175

**Comment by fabpot** [comment]
That's already possible without any changes: use `{{ _self.dourl(page) }}` instead of `{{ call dourlmacro(page) }}`
