### ISSUE TITLE
Add SilentNodeInterface to allow creation of tags similar to 'block' or 'set'

### ISSUE THREAD

**Issue by philer** [twigphp/Twig#2045]
I'm trying to create a new tag that allows me to put JavaScript (or anything else) in its body that will be collected and then output in one location at the bottom of the generated HTML. This tag should be usable _anywhere_, even outside of blocks in extended templates. Here's a simplified usage example:

``` PHP
{# base.twig #}
<html>
  <head></head>
  <body>

    {% block content '' %}

    {# collected javascript from various templates #}
    <script>{{ dump_javascript() }}</script>

  </body>
</html>
```

``` PHP
{# some_page.twig #}
{% extends 'base.twig' %}

{% script %}
    console.log("foo"); // this is JS
{% endscript %}

{% block content %}
    ...
{% endblock %}
```

Now obviously in this simple example I could just be using `block` instead of `script`, however my extension does a bunch of additional logic that the native `block` doesn't. That logic works fine, the only issue is the expected error: "**A template that extends another one cannot have a body**" thrown inside `Twig_Parser::filterBodyNodes`. This method is evidently designed to ensure that no Nodes are able to output anything in inappropriate places. However, as the example above hopefully demonstrates, my `script` tag is never going to output anything and instead collects its body content for later use. It shares this behaviour with the `block` and `set` tags and should thus cause no issues when used outside a block.

`Twig_Parser::filterBodyNodes` checks for several hardcoded cases, namely `Twig_Node_Set`, `Twig_Node_BlockReference` and empty `Twig_Node_Text` instances. It also works with a `Twig_NodeOutputInterface`, which is used to indicate that a Node _does_ output something.

In the end my suggestion is quite simple: Add another interface, possibly called `Twig_NodeNoOutputInterface` or `Twig_SilentNodeInterface`, that can be used to indicate that a Node will never output anything and can safely be used outside of blocks. Add this interface to the BlockReference and Set nodes and replace the hardcoded checks with one for the new interface.

Unless I missed something this should be quite simple. If I am missing something or there is a better way to achieve what I'm trying to do please let me know.

– Regards and thanks for Twig!

PS (updated): I'm able to work around the current limitation by having my ScriptNode extend Twig_Node_Set and bypassing its constructor. It's hacky but works.

**Comment by sstok** [comment]
https://github.com/boekkooi/TwigJackBundle/blob/master/doc/twig-defer.md (Symfony Bundle)
https://github.com/rybakit/twig-extensions-deferred

**Comment by philer** [comment]
I noticed the commits. Thanks!
