### ISSUE TITLE
Add parameter to first/last filters.

### ISSUE THREAD

**Issue by SamMousa** [twigphp/Twig#2046]
It would be nice to have an offset parameter for first / last filters.
For example sometimes I don't want to get the last, but the "next-to-last" element. 

I can submit a PR if you'd like this feature / improvement. 
1. What parameter name would you prefer?
2. What does first / last currently return on empty arrays / strings? --> Should that not be added to the docs?

**Comment by SamMousa** [comment]
Hmm, I see in the source code it internally uses slice; which I could use as well. Feel free to close this if you do not think this is a good addition and the workaround with slice suffices.

**Comment by iltar** [comment]
Wouldn't it be something like [:-1] ? I'm not too familiar with the syntax though

**Comment by SamMousa** [comment]
@iltar If that works, that'd be great; i'll test it.

**Comment by SpacePossum** [comment]
I don't think that works, or I misread the PR/suggestion;
http://twigfiddle.com/ulgbxw

**Comment by iltar** [comment]
http://twig.sensiolabs.org/doc/filters/slice.html

**Comment by SamMousa** [comment]
@iltar, see my second comment:

> Hmm, I see in the source code it internally uses slice; which I could use as well. Feel free to close this if you do not think this is a good addition and the workaround with slice suffices.

**Comment by iltar** [comment]
But that's exactly what I was referring to with my notation (check the syntactic sugar block)

**Comment by SamMousa** [comment]
Ah okay, so then this would work (and it does):
````
['a','b','c','d','e'][:-1][0]
````

**Comment by SpacePossum** [comment]
```
['a','b','c','d','e'][-1:][0]
```
`:` after the offset ;)  (http://twigfiddle.com/ulgbxw)
thanks @iltar !

**Comment by SamMousa** [comment]
That's what I meant yeah :p

**Comment by reFX-Mike** [comment]
I've fixed the example for you:

http://twigfiddle.com/ulgbxw/2

**Comment by SpacePossum** [comment]
@SamMousa if there is nothing left to do, please click `close` ;)  If there is, please keep the issue open and state actions needed :)

**Comment by SamMousa** [comment]
@SpacePossum that is up to you, the current syntax would be:
````
{{ foo[-2:][0] }}
````
I propose adding:
````
{{ foo|last(1) }}
````

If you'd like to have that added let me know and I can implement it, if you feel it is not worth the extra code then feel free to close this :)

So actions needed: tell me if you want me to implement my proposal or close this ;-)

**Comment by fabpot** [comment]
I don't like adding too many filters in core. This is a typical example of slice usage, and adding last() without first() would be weird. So instead, I propose to add a note in the documentation about how one can get the last item of a sequence. @SamMousa Can you submit a PR for the docs?

**Comment by SamMousa** [comment]
https://github.com/twigphp/Twig/pull/2049
Note that it is untested since I do not know what "addons" you use for reStructuredText.

**Comment by fabpot** [comment]
Closing as there is a doc PR now.
