### ISSUE TITLE
Creating a template for a custom field type

### ISSUE THREAD

**Issue by Ziiweb** [twigphp/Twig#2048]
Hi,

[here](http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html#creating-a-template-for-the-field) it is said that is said it is possible to create a template for a custom form type. But, is it possible to include the template in a bundle? Im creating a bundle at this moment, and I would **not** like to include the template of the custom field type at `app/Resources`, but **inside of it**.

**Comment by sstok** [comment]
Yes that is possible, `app/Resources/views` is only for application specific templates.

If you want to create a Form theme (which is what it's called) you can place it in `Resources/views/Form` of your bundle. But that alone is not enough, you need activate the Form Theme (http://symfony.com/doc/current/cookbook/form/form_customization.html#form-theming) or if you want to activate it for all forms, you can use a special technique http://symfony.com/doc/current/cookbook/bundles/prepend_extension.html see 
https://github.com/braincrafted/bootstrap-bundle/blob/develop/DependencyInjection/BraincraftedBootstrapExtension.php#L89-L93
https://github.com/braincrafted/bootstrap-bundle/blob/develop/DependencyInjection/BraincraftedBootstrapExtension.php#L161-L173
for a working example.

For further help please use of the http://symfony.com/support channels as the Twig issue tracker is only used for bugs and new features about Twig ;) Twig is a separate project and has nothing to do with Symfony. If you think the documentation of Symfony can be improved to better explain Form themes in a bundle please open a new issue in https://github.com/symfony/symfony-docs/ and explain what problems you are facing. Thanks 👍
