### ISSUE TITLE
Template-dependent template loading

### ISSUE THREAD

**Issue by wimleers** [twigphp/Twig#2059]
We're trying to use `{% extends "image.html.twig" %}` in more places in Drupal 8 core.

Today, Drupal 8's Twig templates sadly still duplicate most of the original template. Using `extends` allows for less repetition, and for bug fixes in base themes to propagated to custom sites, without having to change code.

Unfortunately, we're running into a significant problem, which appears to be an architectural limitation in Twig.

Drupal.org issue: https://www.drupal.org/node/2387069. Below, I've explained it in a way that hopefully removes the need to have any Drupal knowledge, having Twig knowledge is sufficient.

## Drupal's needs.

Drupal's theme system has inheritance. In Drupal 8 core by default, the Bartik theme extends the Classy theme, which extends the Stable theme. Classy and Stable are called "base themes".

This means that extending works:

- *from current theme to the first ancestor theme* when rendering `SOMETHING.html.twig`: Bartik's would extend Classy's which would extend Stable's. Crucially, Classy's may be removed (then Bartik's extends Stable's) and then added again (which then goes back to the original behavior), and we'd expect this to work
- *within the current theme* when rendering a variant: `SOMETHING--variant.html.twig` would extend the current theme's SOMETHING.html.twig, and if that doesn't exist, it'd go and look at the ancestor.

It also means we specifically do *not* want to specify the full path to the base theme's template (nor the namespaced path — we also have registered the necessary namespaces). In other words: `{% extends "path/to/base_theme/SOMETHING.html.twig %}` or `{% extends "@base_theme/SOMETHING.html.twig" %}` is unacceptable.

## Concrete example

1. `core/themes/stable/templates/foo.html.twig`
2. `core/themes/classy/templates/foo.html.twig` contains `{% extends "foo.html.twig" %}` (to add a specific class) and expects Stable's foo.html.twig to be extended
3. `core/themes/bartik/templates/foo.html.twig` contains `{% extends "foo.html.twig" %}` (to override a Twig block) and expects Classy's `foo.html.twig` to be extended — or, really, any of its ancestor themes, because it couldn't care less if Classy's `foo.html.twig` was removed

Notes:

- in point 3, again, we specifically do NOT want to specify `{% extends "@classy/foo.html.twig" %}` because we don't want to care. We just want the parent theme's template — according to the theme registry — to be extended. Think e.g. bug fixes that are added later.
- in point 1, the "root template" could just as well not live in a theme, but in a module. That's also a valid use case.

### 1. Twig's dynamic inheritance

http://twig.sensiolabs.org/doc/tags/extends.html#dynamic-inheritance doesn't help us, since we specifically don't want to have to specify the theme name. We want _only_ `SOMETHING.html.twig`.

### 2. Twig team's answer the previous time this was raised.

This same problem was reported more than a year ago at #1627, but with less contextual detail. @stof posted an analysis, but AFAICT it was not entirely accurate.

@stof's analysis missed one important detail: we don't want to load the same template several times. Each template can still be loaded only once. We just want the same `{% extends foo.html.twig %}` expression to be able to resolve to a different template for each invocation.

So, we need `{% extends "foo.html.twig" %}` to evaluate to the following depending on the calling template:

1. calling template = `core/themes/stable/templates/foo.html.twig` ⇒ `{% extends "foo.html.twig" %}` must evaluate to `core/modules/system/templates/foo.html.twig`
2. `core/themes/classy/templates/foo.html.twig` ⇒ `{% extends "foo.html.twig" %}` must evaluate to `core/themes/stable/templates/foo.html.twig`
3. `core/themes/bartik/templates/foo.html.twig` ⇒ `{% extends "foo.html.twig" %}` must evaluate to  `core/themes/classy/templates/foo.html.twig`

This does _not_ violate the restriction that @stof described: the loader will not load the same template several times.

## Proposed solution

Change (expand) Twig's `loadTemplate()` signature, because without knowing the current template's path, we cannot let `{% extends "foo.html.twig" %}` load a different template based on the current template. And consequently, `Twig_(Exists)LoaderInterface` would need to be changed also: all of its methods would need to receive this new argument.

I realize this will likely be dismissed by the Twig team as unnecessary complexity. Nobody is questioning that this would make Twig more complex, simply because it enables more complex behavior (out of the box, Twig would still function the same as it does today even with these changes).

But Twig's simplicity gets in the way for Drupal here: it prevents Drupal from being simple. Without this, there is only one solution: the status quo, which offers only two options:
- continue to duplicate base theme templates when you create a new Drupal theme
- spell out the full path to the base theme template that you're inheriting

In either of those options, the creator of a custom theme _must_ apply bug fixes manually: either transplant template changes by hand, or change the base theme template that you're inheriting (if the base theme added or removed a particular template).

So, please work with us to solve this big pain point in Drupal 8 theming.

**Comment by wimleers** [comment]
Also related: #1991.

**Comment by stof** [comment]
Passing the current template to the loader would not solve your issue, because Twig uses the template name to name the compiled template class, and so you cannot have 2 different sources for the same name (the second source will never be used). So it would force to add more complexities to handle that.

There are ways to achieve your use case though.

Puli solved a similar issue (they wanted to be able to use named like ``../foo.html.twig`` for relative references) by hooking into several parts of Twig:

- hooking into the loader to add a special ``{% loaded_by_puli %}`` tag at the beginning of the source of the template (to be able to identify templates loaded by Puli in which the magic should happen)
- using a Twig node visitor to rewrite template names in extends/include/embed tags, to resolve paths, and to clean the custom tag after that.

In your case, things could look like that:

- add a special tag during loading to remember which theme provided the template (can be done in the loader, as it knows where it found the file): ``{% drupal_theme 'classy' %}`` when loading ``core/themes/classy/templates/foo.html.twig`` for instance.
- add a Twig node visitor rewriting the parent template name in ``{% extends 'foo.html.twig' %}`` tags to something like ``#drupal_parent_theme:classy/foo.html.twig`` (the naming convention should be chosen to something which does conflict with normal Twig template names, which is why I avoided the ``@`` prefix which is already used by a Twig core feature)
- make your template loader able to parse such template names, to resolve them only in parent locations of the ``classy`` theme.

In your case, you will probably need to rewrite only ``extends`` tag, as you probably want ``{% include 'bar.html.twig' %}`` to go through the normal resolution (i.e. looking at the current theme rather than the theme containing the include, to allow overwrites).

I can assist you implementing this solution if you need (but not in the next few days)

**Comment by wimleers** [comment]
> using a **Twig node visitor** to rewrite template names in extends/include/embed tags, to resolve paths, and to clean the custom tag after that.

This is the approach we went with! :) See https://www.drupal.org/node/2387069#comment-11295493 — somebody had suggested that independently of you. We rewrite it to use Twig's https://www.drupal.org/node/2387069#comment-11295493. It works rather well :)

It rewrites

```
{% extends "block.html.twig %}
```
to:
```
$this->loadTemplate(array("core/themes/bartik/templates/block.html.twig", "core/themes/classy/templates/block.html.twig", "core/modules/block/block.html.twig"), "block.html.twig", 1);
```

**However, AFAICT it's impossible to do this sort of rewriting for `embed`** — as I explained at https://www.drupal.org/node/2387069#comment-11296019:
> I tried to make embed also work, but there's a bug deep in Twig that prevents this from working: `\Twig_TokenParser_Embed` sets the parent template *a*fter the parser is invoked, i.e. after node visitors are applied. So that's literally impossible to fix. I don't want this to be blocked on Twig fixing their stuff, and then Drupal getting an updated Twig version (which can only happen in Drupal 8.2, not 8.1).

---

That being said, I've since come to the same conclusion — at least for now — as you:
> In your case, you will probably need to rewrite only `extends` tag, as you probably want `{% include 'bar.html.twig' %}` to go through the normal resolution (i.e. looking at the current theme rather than the theme containing the include, to allow overwrites).

So, for now, let's not worry about `include` and `extends`.

---

> I can assist you implementing this solution if you need (but not in the next few days)

This is very kind of you! :) Rather than writing it, I'd appreciate a review of the current patch from a Twig POV (patch attached below, originates from https://www.drupal.org/node/2387069#comment-11341787). Although at this point, it's 97% Drupal-specific.

[twig_theme_registry-2387069-59.patch.txt](https://github.com/twigphp/Twig/files/335055/twig_theme_registry-2387069-59.patch.txt)

**Comment by stof** [comment]
I will review it in the next few days

**Comment by wimleers** [comment]
Thanks!

BTW, the problem with `{% embed … %}` is:

```
/**
 * Embeds a template.
 */
class Twig_TokenParser_Embed extends Twig_TokenParser_Include
{
    public function parse(Twig_Token $token)
    {
        …

        // inject a fake parent to make the parent() function work
        $stream->injectTokens(array(
            new Twig_Token(Twig_Token::BLOCK_START_TYPE, '', $token->getLine()),
            new Twig_Token(Twig_Token::NAME_TYPE, 'extends', $token->getLine()),
            new Twig_Token(Twig_Token::STRING_TYPE, '__parent__', $token->getLine()),
            new Twig_Token(Twig_Token::BLOCK_END_TYPE, '', $token->getLine()),
        ));

        $module = $this->parser->parse($stream, array($this, 'decideBlockEnd'), true);

        // override the parent with the correct one
        $module->setNode('parent', $parent);
```

This means any `Twig_NodeVisitorInterface` sees that the parent is `'__parent__'`, which is of course not true.

This has been true since the very introduction of the `embed` tag: since #709, introduced at commit https://github.com/twigphp/Twig/commit/0f623a11129ce28a897dbd5b812241d8b3ea9730.

**Comment by fabpot** [comment]
Are you sure? `$module->setNode('parent', $parent);` should override the parent with the correct one.

**Comment by stof** [comment]
@fabpot but node visitors are called inside ``$this->parser->parse``

**Comment by wimleers** [comment]
Yes, I'm absolutely certain. It's `$this->parser->parse(…)` that causes node visitors to be called. Which means when a node visitor is … well, visiting, that it sees `extends "__parent__"`, which of course it cannot make sense of.

PR upcoming.

**Comment by wimleers** [comment]
Filed PR: #2059.

**Comment by fabpot** [comment]
See #2124 for a partial solution (not a big fan, but I don't have any better idea right now... except having a way to dump back a node to a Twig template representation :().
