### ISSUE TITLE
Document default autoescape value?

### ISSUE THREAD

**Issue by paragonie-scott** [twigphp/Twig#2061]
https://github.com/twigphp/Twig/blob/master/doc/tags/autoescape.rst

I think it would help if people knew what the default escaping strategy was without declaring an autoescape block. (I'm assuming "html".)

**Comment by stof** [comment]
The default escaping depends on the default strategy configured in the Twig_Extension_Escaper (through the Twig_Environment options generally).

In Twig itself, the default is ``html``.

In Symfony, the default is ``filename``, which is a special value to use the ``array('Twig_FileExtensionEscapingStrategy', 'guess')`` callable (you can pass any callable too), which chooses the strategy based on the  template name: names ending in ``.txt`` or ``.txt.twig`` will disable auto-escaping, names ending in ``.js`` or ``.js.twig`` will use the ``js`` strategy, names ending in ``.css`` or ``.css.twig`` will use the ``css`` strategy and everything else will use the ``html`` strategy.

**Comment by stof** [comment]
@fabpot should we change the Twig default value to ``filename`` in Twig 2 ?

**Comment by paragonie-scott** [comment]
This will has no bearing on my project, which just uses `.twig` everywhere, but I think that would be useful if others follow Symfony's naming convention.

**Comment by fabpot** [comment]
see #2227
