### ISSUE TITLE
Can twig return variables as it is(kind of not executing it) by prefixing some special chars

### ISSUE THREAD

**Issue by bishwanathjha** [twigphp/Twig#2070]
Is there a way we can tell twig to not execute/print the variables(just return as it is) by adding some special characters(like backslash)

What i want to achieve is:
```
\{{ user.name }}\ 
{{ user.name }}
```

The output should be:
```
{{ user.name }}
Bishwanath
```

Can i achieve this in twig?

**Comment by stof** [comment]
there is a ``{% verbatim %}`` tag to enclose parts which should not be parsed for Twig markup:

```twig
{% verbatim %}{{ user.name }}{% endverbatim %}
```

If it happens only once for ``{{``, you can also use this trick:

```twig
{{ '{{' }} user.name }}
{{ user.name }}
```
