### ISSUE TITLE
Twig not loading in Symfony Dev environment when using XAMPP localhost

### ISSUE THREAD

**Issue by shaunthomson2097** [twigphp/Twig#2072]
### Twig not Loading in Symfony Dev Environment When Using XAMPP Localhost

I do not know if this is a Twig, Symfony or Xampp issue.

My Setup:
Running xampp-win32-5.6.23-0-VC11 localhost
Symfony 3.1.2

The Twig template works in:
  - Symfony localhost:8000
  - Symfony localhost:8000/app_dev.php
  - XAMPP localhost

but does not work in XAMPP localhost/app_dev.php **(I need it to work in this environment)**

I have cleared the dev environment cache and restarted XAMPP bur unfortunately no success.

Could you please assist?

**Comment by xabbuh** [comment]
What do you mean with "it does not work"? Did you check your web server's log file(s)?

**Comment by shaunthomson2097** [comment]
Hi


i will have another look and get back to you.

Please be patient as I am extremely new to Symfony.

Kind Regards

Shaun

**Comment by shaunthomson2097** [comment]
Hi

I just had a look and it seems that the Twig is working after all, but the
styles does not load.

I will have a look at further

Apologies from my side.

Kind Regards

Shaun
