### ISSUE TITLE
Twig_Node_Set hard coded into twig/lib/Twig/Parser.php

### ISSUE THREAD

**Issue by ken-spencer** [twigphp/Twig#2073]
I am writing an extension that behaves similarly to the set tag, but is defining some internal features. However unlike set my extension gets a fatal error: "A template that extends another one cannot have a body in"

After debugging, I traced this problem to the following section in Parser.php. It appears that the workaround for this error for set is hardcoded in: 

	// bypass "set" nodes as they "capture" the output
        if ($node instanceof Twig_Node_Set) {
            return $node;
        }

Can we change this so that any tag can have this capability, not just set?

**Comment by stof** [comment]
Duplicate of #2045

**Comment by fabpot** [comment]
Closing as a duplicate
