### ISSUE TITLE
'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)

### ISSUE THREAD

**Issue by sciamannikoo** [twigphp/Twig#2074]
I'm getting many of these errors when using Twig as a composer library in PHP7.

As far as I know, here are the affected files:
* Twig/Compiler.php
* Node/Embed.php
* Node/Expression/AssignName.php
* Node/Expression/Call.php
* Node/Expression/Name.php
* Node/Expression/Parent.php
* Node/Macro.php
* Node/Module.php
* Node/SetTemp.php
* Node/Text.php

**Comment by stof** [comment]
In which case are you getting an error about invoking ``string`` as a function ? I don't think all these file are affected by an issue. And without a reproducing case, it will be hard to identify the issue.

**Comment by sciamannikoo** [comment]
The actual example is on the way: I need to prepare it, as we are using Twig as part of a WordPress plugin and I think you want a simpler case.

by the way, "string" it's used a function in all above mentioned cases. An example is `\Twig_Compiler::string` (which is a class method: same as a function):

```
/**
 * Adds a quoted string to the compiled code.
 *
 * @param string $value The string
 *
 * @return Twig_Compiler The current compiler instance
 */
public function string($value)
{
    $this->source .= sprintf('"%s"', addcslashes($value, "\0\t\"\$\\"));
    return $this;
}
```

**Comment by jvasseur** [comment]
"string" is allowed as a function name in PHP7, it is only disallowed as a class name.

**Comment by stof** [comment]
btw, Twig is working fine on PHP 7, as shown by the testsuite. This is why I'm asking you for the issue you are facing (with the error message you are getting)

**Comment by sciamannikoo** [comment]
Ok, it seems that this was caused by a false positive from a compatibility checker tool, which was reporting the following:
> Function name, class name, namespace name or constant name can not be reserved keyword 'string' (since version 7.0)
> 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)

That's the tool one of our developers was using: https://wordpress.org/plugins/php-compatibility-checker/

Indeed, there is no mention of functions or class methods about reserved words.

I'll advice the developer to use more reliable tools, such as http://php5.laurent-laville.org/compatinfo/.

Sorry for the false alarm.

**Comment by stof** [comment]
@sciamannikoo please close this issue then (I cannot do it as I'm not a Twig maintainer, even though I'm contributing as a reviewer)

**Comment by sciamannikoo** [comment]
Actually, I've pressed "Close and comment" before, but it looks like it didn't work: let's try again.
