### ISSUE TITLE
Is there an option to ignore Twig tags between certain HTML tags?

### ISSUE THREAD

**Issue by howardroark** [twigphp/Twig#2077]
So I am an active user of both Twig and Nunjucks.  One for the server and one for the client.  I want to use them inline together, but my issue is well pretty obvious I'm sure  :P 

What I would really like to do is ask twig to ignore tags between `<template>` and `</template>`.  As of now is Twig capable of this?  Is it an outrageous idea? 

Thanks!

**Comment by SpacePossum** [comment]
In what way `ignore`? Like [verbatim](http://twig.sensiolabs.org/doc/tags/verbatim.html)?

**Comment by howardroark** [comment]
Yup, just like that!

**Comment by stof** [comment]
You cannot tell Twig to ignore things between the ``<template>`` and ``</template>`` tags, because these are just text as far as Twig is concerned (Twig does not know about the HTML markup).
Use the ``{% verbatim %}`` Twig tag

**Comment by howardroark** [comment]
Totally get that!  

But it could ;) I use Grav a lot and may experiment with this. 

Thanks!
