### ISSUE TITLE
Twig Template render results show the source instead of the rendered template

### ISSUE THREAD

**Issue by tyurderi** [twigphp/Twig#2078]
I am currently getting the source of the template instead of it's content using version `1.24.1`

``` php
/** @var $view \Twig_Environment*/
$template = $view->createTemplate('/absolute/path/to/template.twig');

echo $template->render([]); // echoes "/absolute/path/to/template.twig"
```
The template file exists and have 0777 permissions.

I had the same issue before on another system when refering to the template with a relative path. When I changed the relative path to an absolute one it worked. But in my example (shown above) it doesn't work with an absolute path, too.

Both tests was exected on linux (Ubuntu 15.10 and Ubuntu 14.04) with apache and php5.

**Comment by sstok** [comment]
https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L417
"This method should not be used as a generic way to load templates."

The createTemplate is only to create a template from a string, it's for internal purposes.
You need the `loadTemplate()` method to load a template 👍 
http://twig.sensiolabs.org/doc/api.html#basics

**Comment by tyurderi** [comment]
Now its working, thank you. :+1:

**Comment by stof** [comment]
Templates are not loaded by path, but by name. How names are resolved to find the source code is the job of the loader (there is nothing enforcing to rely on files btw).
