### ISSUE TITLE
Clear cache documentation

### ISSUE THREAD

**Issue by SpacePossum** [twigphp/Twig#2079]
After; https://github.com/twigphp/Twig/pull/1812 the methods to clear the Twig cache are deprecated. 
While this is a good thing (imo) I wonder, what would be a good/the best way to do it? And would it be a good idea to write a best practice of how to clear the cache in the docs., maybe as recipe (*"Clearing file based Twig cache"*)?

**Comment by stof** [comment]
``rm -rf /path/to/cache/folder``, or any other way to remove the content of a folder (written in any language you want)

**Comment by SpacePossum** [comment]
hmm is there no way to get this back into Twig at some level?
* why are there no new flush methods added to the `Twig_CacheInterface`, I get you don't want those on the environment but why not on the cache implemenations?
* if these won't come back; I would like to get the directory from the [Twig_Cache_Filesystem](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Cache/Filesystem.php#L21), was a getter left out by design?

**Comment by SpacePossum** [comment]
I found something like this in a review;
```php
<?php
$clear = 'ls -rf /'.$this->app['twig']->getCache(true);
$clear = `$clear`;
```

With `ls` being `rm`. So when `getCache()` returns `null` there is a big problem. Secondly the code is not portable, i.e. won't run on Windows.
If a client/driver can read and write to cache why shouldn't be able to clear it so the flush functionality can be restored on Twig?

**Comment by fabpot** [comment]
see #1879, which discuss the same topic. For the record, I agree with @Tobion
