### ISSUE TITLE
Add values filter.

### ISSUE THREAD

**Issue by SamMousa** [twigphp/Twig#2081]
Currently there is a `keys` filter, but no `values` filter.
This filter is relevant in case you sort an array and then want a specific value without knowing the key.

For example: `{a: 5, b: 2, c: 3}|sort|values[0]` would get the lowest value regardless of key.

**Comment by Koc** [comment]
http://twig.sensiolabs.org/doc/filters/first.html ?

**Comment by SamMousa** [comment]
Okay @koc, my bad ;-) What about the 3rd highest? 
There is no way to discard the keys and use the values as numeric array.

It seems weird to me to have `keys` but not `values`.

**Comment by SamMousa** [comment]
I'm up for creating a PR for a `values` filter. Let me know if you'd like that feature @fabpot. If not feel free to close this issue!
