### ISSUE TITLE
trigger_errors are suppressed

### ISSUE THREAD

**Issue by msierks** [twigphp/Twig#2082]
The **trigger_error** calls throughout twig are suppressed by the **@**. They won't appear logs or in display errors. But you can still catch them with a custom error handler.

Is this the desired outcome ? Users won't see these errors unless a custom error handler is used.

**Comment by Tobion** [comment]
This decision was made on purpose so people can opt-in to get deprecation warnings instead of having to opt-out.

**Comment by stof** [comment]
This is the convention used in the Symfony ecosystem to make deprecation warnings opt-in (not silencing them would break your projects as soon as you have an error handler turning warnings into exceptions, which is the case in almost all frameworks).
The Symfony error handler has some logic to log silenced deprecations, and Twig also has a tool to collect these deprecations when you are not using the symfony/debug component.
