### ISSUE TITLE
Use of symfony/cache component

### ISSUE THREAD

**Issue by aferrandini** [twigphp/Twig#2084]
Now that `symfony/cache` component has been released, maybe we can move the cache classes and engine to this component. This could be a good start to move templates caching to other engines like memcached, redis, etc...

There is a known problem about that, the current cache files are included with `require_once` and maybe we should think about another way to include this files o `eval` the code retrieved from cache.
Another problem I could see, and worst than others, is that if the cache is not a file, `opcache` will not cache this piece of code. So, I'm not sure if this will be the right way to go further with this change.

https://github.com/symfony/cache

**Comment by sstok** [comment]
The Symfony Cache component is an PSR-6 implementation so you would rather target PSR-6 then an implementation. And doing this is already possible when you create your own Cache implementation for Twig.

Note that the Twig caching is more about a compiled version then a computed result that is cached. So doing this for Twig is allot more complex then normal.

**Comment by reFX-Mike** [comment]
Since PHP already does op-code caching, it would be unnecessary to cache the compiled code again. It's already done automatically by PHP itself. The files are not loaded again or compiled again, they are just executed from memory.

**Comment by fabpot** [comment]
Twig cache must be in files (op-code cache, ...). Recently, we let the user decide to do something else but this highly not recommended. So, adding symfony/cache would not go in the right direction.

**Comment by aferrandini** [comment]
Thanks @fabpot
