### ISSUE TITLE
Problem with "use" in twig template - does not display anything

### ISSUE THREAD

**Issue by tomandquery** [twigphp/Twig#2088]
I am trying to use "use" in twig template, it does not show any errors but also does not display anything as intended. I want to display the menu with "use" instruction. Am I missing something? Basically I copied the example from documentation on: [http://twig.sensiolabs.org/doc/tags/use.html](http://twig.sensiolabs.org/doc/tags/use.html) 

Why is it not working?

Here is my code:

index.twig:

[http://pastebin.com/2r2Pc6da](http://pastebin.com/2r2Pc6da)

menu.twig:

{% block menu %} 
sample menu 
{% endblock %}

**Comment by tyurderi** [comment]
You may try this in `index.twig`

```twig
<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
</head>
<body>
 
<div id="page">
    {% use 'menu.twig' %}
    {% block menu %}
        {{ parent() }}
    {% endblock %}
</div>
 
</body>
</html>
```

But isn't it easier to just include `menu.twig`?

**Comment by stof** [comment]
This is totally expected. ``{% use %}`` is about importing block definitions. But in your case, you are overwriting the block in your own template
