### ISSUE TITLE
Reconsider precedence when accessing attributes of array and object

### ISSUE THREAD

**Issue by HeahDude** [twigphp/Twig#2089]
ref https://github.com/symfony/symfony/issues/18882 which shows an issue when dealing with objects using `ArrayAccess` where keys may conflict with public property or methods.

What about checking object first for property/method, before handling both array and object implementing `ArrayAccess`?

The comment https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L464 is misleading because object with `ArrayAccess` are handled here too.

Also I'm wondering if the magic methods `__get` and `__set` are handled they seem missing here: https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L578.

**Comment by fabpot** [comment]
Closing as it would be a BC break.
