### ISSUE TITLE
array merge with null parameter

### ISSUE THREAD

**Issue by caiquecastro** [twigphp/Twig#2093]
I'm having a issue where the compiler writes to the compiled template a attempt to array_merge with null:

`$this->loadTemplate("template_file_1.html.twig", "template_file_2.html.twig", 131)->display(array_merge($context, (isset($context["variable_x"]) ? $context["variable_x"] : null)));`

Shouldn't it use  `(isset($context["variable_x"]) ? $context["variable_x"] : array())` instead of ` (isset($context["variable_x"]) ? $context["variable_x"] : null)`

**Comment by caiquecastro** [comment]
The `Twig_Template::getAttribute` should return provide valid return for array_merge. As it sometimes is passed as a parameter to array_merge.

**Comment by fabpot** [comment]
Can you provide more details? What is the snippet of code that gives you this issue?

**Comment by fabpot** [comment]
So, you are probably using something like `{{ include('tpl', vars) }}` but `vars` does not exist (`strict_variables` being `false`). I don't see any simple way to "fix" that. In any case, `vars` should exist at this point, so I'm going to close this one for now.
