### ISSUE TITLE
Round function not working as expected when using ceil

### ISSUE THREAD

**Issue by bensampaio** [twigphp/Twig#2095]
When i try `someRandomFloatValue|round(1, 'ceil')` I get the following error message: `Warning: round() expects parameter 3 to be long, string given`. But in the [documentation](http://twig.sensiolabs.org/doc/filters/round.html) it says the third argument should be 'common', 'floor' and 'ceil'. What am I doing wrong? Thank you!

**Comment by joelpittet** [comment]
This seems to work... http://twigfiddle.com/mkpcen

**Comment by xabbuh** [comment]
@bensampaio Do you have an extension that replaces the built-in `round` filter?

**Comment by bensampaio** [comment]
@xabbuh I hope not... but maybe that's the case... how can I check for that?

**Comment by bensampaio** [comment]
I found out there was indeed a very old extension replacing the built-in `round` filter. Thank you!
