### ISSUE TITLE
[feature request]  Provide sectional use within a single twig template

### ISSUE THREAD

**Issue by ucsdmath** [twigphp/Twig#2097]
I think it would be a nice feature to be able to mark sections of a template to render.

```
$pdfHeader = $twig->render('pdf.twig', $data, '#header');
$pdfFooterOdd = $twig->render('pdf.twig', $data, '#footerOdd');
$pdfFooterEven = $twig->render('pdf.twig', $data, '#footerEven');
```

For little snippets of HTML rendering needs, for smaller dialogs, etc.
Maybe like an array of related template code, but kept all in one template file.

I am not sure how easy or difficult that would be to add such a feature, but something I just thought about that I would make use of it available.

Thank you!

**Comment by sstok** [comment]
This is already possible, but it requires one extra template.
https://github.com/twigphp/Twig/issues/1873#issuecomment-208997182

**Comment by ucsdmath** [comment]
Awesome!  Thank you for pointing me to this.  I will give a try.
