### ISSUE TITLE
integer with null as value is evaluated in == 0 condition

### ISSUE THREAD

**Issue by jin78** [twigphp/Twig#2100]
Hi all,

I noticed a bug in Twig where a null value is executed in a if statement like this one : 
{% if someVar == 0 %}
    {# code here #}
{% endif %}

The someVar is either an integer (not an integer as string) or is null.

Regards.

**Comment by SpacePossum** [comment]
This is how PHP evaluates the values when using `==`:
https://3v4l.org/SFn85

You can use `===` for strict checking (works in Twig, however not much advertised)
