### ISSUE TITLE
[Filters] allow any php callback

### ISSUE THREAD

**Issue by popnikos** [twigphp/Twig#2102]
While attempting to use filter in a template many php function do the job and customize filters only represents a call to php function which is expected the variable as the first argument - I mean for example : 
{{ mystring | substr(0, -1)}}
 wich is simply the same as php's call 
substr($mystring, 0, -1)

**Comment by jfcherng** [comment]
I use funtion though.
```php
<?php

$twig->addFunction(new \Twig_SimpleFunction(
    '_',
    function ($funcName, ...$args) {
        if (function_exists($funcName)) {
            return $funcName(...$args);
        }
        // throw an error or what ever
    }
));
```
In template,
```
{{ _('strpos', 'abcd', 'c') }} {# 2 #}
```

**Comment by fabpot** [comment]
Exposing any PHP function by default is a no-go for core Twig as it can leads to severe security issues. Twig's philosophy is about exposing exactly what you need in templates. So, if you want to use a PHP function, just explicitly register a Twig filter for it.
