### ISSUE TITLE
Twig 2.0 and namespaces

### ISSUE THREAD

**Issue by hkdobrev** [twigphp/Twig#2108]
Do you plan on introducing namespaces to the Twig source code? If they are introduced this would be a breaking change in the interface so it's best to be done as part of 2.0. Otherwise namespaces could come only at 3.0.

Some libraries introduce namespaces with an alternative interface mimicking the old one working as a facade to the new namespaced interface for easier upgrading. However I think Twig upgrading won't be so hard, because all popular service providers, bundles, plugins etc would be updated rather quickly.

If namespaces are indeed planned for 2.0, some community effort could help for converting the codebase.

(As a side note a list of issues (milestone or a label) or a roadmap for 2.0 would help the community submit more PRs).

**Comment by stof** [comment]
What would be the benefit of introducing namespaces ? This would mean a huge BC break for the community, and I don't see any real benefit.

**Comment by fabpot** [comment]
I've no plan in introducing namespaces for Twig. No real benefits as most people are using the Twig syntax, so PHP is not that interesting anyway.
