### ISSUE TITLE
Marking a block as deprecated

### ISSUE THREAD

**Issue by greg0ire** [twigphp/Twig#2112]
It would be great to provide a syntax to mark a block as deprecated, so that any user calling it with `{{ block('deprecated_block') }}` or extending it with `{% block deprecated_block %}` would get a deprecation warning about that.

Possible syntax:
```html+jinja
{% block example %}
    {% deprecate %}
        The "example" block is deprecated since version 3.x and will be removed in 4.0,
        please consider using the "brand_new_example" block instead.
    {% enddeprecate %}
    <p>This is an example block</p>
{% endblock %}
```

**Comment by fabpot** [comment]
I don't think this should be part of Twig core. AFAICS, this is totally possible to do this as an addon.

**Comment by greg0ire** [comment]
Since it is possible to deprecate filters natively, I thought it would make sense to also be able to deprecate other things like blocks. They are also part of the API of the library that provides them in some way, aren't they?

**Comment by HeahDude** [comment]
Don't you mean "tags" instead of "blocks"? Otherwise I'm curious about what blocks you're talking about.

**Comment by fabpot** [comment]
There is a big difference here. Filters/tags/functions are global to Twig. A block is a very local concept and Twig does not really care about them. So, I think it makes sense to not support blocks for deprecations in the core.

**Comment by greg0ire** [comment]
@HeahDude : I really do mean "blocks", as defined by the [block](http://twig.sensiolabs.org/doc/tags/block.html). [Here](https://github.com/sonata-project/dev-kit/issues/205) is the related issue that show why I need that : we have a bundle with a block named `example`, and it has been decided that blocks should be namespaced so that there is no risk of collision when inheriting from our templates. That means I would like to deprecate the `example` block in favor of a `sonata_randombundle_example` block.

@fabpot : big difference indeed, I get it now. I'm closing this then.
