### ISSUE TITLE
varibles\'s problem in include

### ISSUE THREAD

**Issue by guohuihot** [twigphp/Twig#2113]
```
{# a.html #}
{% set aaa = 1 %}
{% include 'b.html' %}
{{ dump(aaa) }} {#  aaa = 1 #}
```
```
{# b.html #}
{% set aaa = 10 %}
```
How to make `a=10` in `a.html` ???

**Comment by sstok** [comment]
This is not possible with include, basically it renders the template and 'includes' the rendered output in that location.

See the documentation: http://twig.sensiolabs.org/doc/tags/include.html
Maybe you need to use template inheritance instead or [use](http://twig.sensiolabs.org/doc/tags/use.html)

**Comment by fabpot** [comment]
You should ask your questions on StackOverflow. We are only using Github for the development of Twig itself, and as such, you won't get many answer here. Thanks for your understanding.
