### ISSUE TITLE
manipulate parent's variable from block in child template

### ISSUE THREAD

**Issue by lostideaslab** [twigphp/Twig#2114]
Hi,
I'm quite new to Twig, but as far as my logic goes, I find the variable manipulation in Twig a bit challenging, here is what I mean:

main.twig
```
{% set var = var|default("hi") %}
{% set var2 = var2|default("how are you?") %}
{% block body %}
{% endblock %}
- {{ var }}
- {{ var2 }}
```

a.twig
```
{% extends "main.twig" %}
{% block body %}
    {% set var = "hello" %}
{% endblock %}
{% set var2 = "I am fine!" %}
```

Rendering a.twig results in:
```
    - hi
- I am fine!
```

but logically if the `block` element in a.twig be exactly replaced in the parent, we would have "hello" instead of "hi".

Here is the an online version of what I am talking about: http://twigfiddle.com/896bsi

Apologize for my newbie language and description of the issue.

**Comment by fabpot** [comment]
You should ask your questions on StackOverflow. We are only using Github for the development of Twig itself, and as such, you won't get many answer here. Thanks for your understanding.
