### ISSUE TITLE
[Bug] Unexpected token "operator" of value "~"

### ISSUE THREAD

**Issue by ad3n** [twigphp/Twig#2115]
I have code like below:

```
        {%- javascripts
               'bundles/symfonyidadmin/plugins/bootstrap-fileinput/js/fileinput.min.js'
               'bundles/symfonyidadmin/plugins/bootstrap-fileinput/js/fileinput_locale_' ~ locale ~ '.js'
        -%}
               <script src="{{- asset_url -}}" type="text/javascript"></script>
        {%- endjavascripts -%}
```
Previously i don't have a problem, but just now i got an error after `composer update`

**Comment by fabpot** [comment]
Looks like you are using Symfony, probably with Assetic. In any case, it's probably not related to Twig. You should use StackOverflow to get support. Thanks.

**Comment by ad3n** [comment]
@fabpot : thanks for you response... okay i will check again in StackOverflow

**Comment by stof** [comment]
Assetic does not support expressions in the Asset references. It expects strings only.

**Comment by ad3n** [comment]
@stof : thanks for your confirmation... The problem is solved :+1:
