### ISSUE TITLE
Embed Docs explain a problem, but only shows solution to half the problem.

### ISSUE THREAD

**Issue by beausmith** [twigphp/Twig#2133]
The [embed](http://twig.sensiolabs.org/doc/tags/embed.html) docs describe an issue with top/bottom and left/right blocks, but only shows solution for top/bottom blocks.

Please update `embed` docs to include example of what the template that uses the left/right blocks would be.

**Comment by stof** [comment]
it would be the same. Block names are just that: names.

Making them left and right rather than top and bottom would be a matter of CSS applied to the HTML output of the template

**Comment by fabpot** [comment]
@stof is right. There is nothing special about top/bottom vs left/right.
