### ISSUE TITLE
Twig_Error_Syntax: An array element must be followed by a comma

### ISSUE THREAD

**Issue by timy-life** [twigphp/Twig#2135]
hi, i use tiwg in phalcon.

html code: 

{{ form(['Admin/Login/doLogin','method'=>'post','class'=>'form-horizontal']) }}

php code :

new \Twig_SimpleFunction('form', function ($parameters = []) {
                return \Phalcon\Tag::form($parameters);
}, $options),

but, System prompt an error:

Twig_Error_Syntax: An array element must be followed by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",") in "Admin/User/new.twig" at line 7.

How do I can use  ??

**Comment by stof** [comment]
Arrays cannot be associative in Twig. Twig has 2 different concepts: arrays and hashes (with syntaxes similar to the JSON one to define them). It does not allow mixed ones

**Comment by timy-life** [comment]
@stof can you give me an example about hashes ?

**Comment by fabpot** [comment]
Something like this: `{{ form({0: 'Admin/Login/doLogin', method: 'post', class: 'form-horizontal' }) }}`

But you should really read the docs: http://twig.sensiolabs.org/doc/templates.html#literals
