### ISSUE TITLE
Segmentation fault in Twig

### ISSUE THREAD

**Issue by flylord** [twigphp/Twig#2136]
I am using symfony 2.8.11 on php 5.6.11
I made template: 
HomeTestBundle::layout.html.twig
and in it I have 
{% extends 'HomeTestBundle::layout.html.twig' %}  

And after that I got segmentation fault and not some php error. Is it normal behavior?

**Comment by SpacePossum** [comment]
Segmentation fault is never normal behavior.
Can you post more details?
(btw. are you using the Twig PHP extension?)

**Comment by flylord** [comment]
I am not using twig extension

This is [phpinfo](https://www.dropbox.com/s/3wilmsnwc6pm48w/phpinfo.html?dl=0) 

composer.json
`    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "dev-master",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "dev-master",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "beberlei/DoctrineExtensions": "^1.0",
        "gedmo/doctrine-extensions": "2.3.*@dev",
        "stof/doctrine-extensions-bundle": "1.1.*@dev",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/buzz-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "1.3.*",
        "masterexploder/simphpthumb": "dev-master",
        "liip/imagine-bundle": "dev-master",
        "symfony/intl": "2.6.*@dev",
        "friendsofsymfony/jsrouting-bundle": "~1.5",
        "symfony/process": "2.8.2",
        "suncat/mobile-detect-bundle": "dev-master",
        "simplicity-projects/helper-bundle": "1.*@dev",
        "guzzlehttp/guzzle": "^6.2",
        "white-october/pagerfanta-bundle": "^1.0",
        "nesbot/carbon": "^1.21"
    },`

**Comment by flylord** [comment]
I am not getting core dump file, I don't know why, it is turned of somewhere in OS. In apache error file there is line: 

[Thu Sep 22 10:33:08.839012 2016] [core:notice] [pid 10503] AH00051: child pid 11978 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by lyrixx** [comment]
How can you be sure it comes from twig?

**Comment by flylord** [comment]
I can't. I don't have deep knowledge of symfony and twig. But, I am getting this if I try to render this faulty template. As I know, twig is handling template extending, so I supposed it is up to twig. 
I haven't tried to make some test only with twig, without symfony. I will try soon and post info here

**Comment by flylord** [comment]
I tried with twig and plain php, without any framwork. 

This is template: 

```php
{% extends 'Test/test.html.twig' %}
{% block content %}
{% endblock %}

```

This is controller function

```php
public function actionIndex() {
    $em = Context::getContext()->entityManager;

    echo $this->Tpl->render('Test/test.html.twig', []);
 }

```

Still geting: [Thu Sep 22 11:59:29.160338 2016] [core:notice] [pid 29440] AH00051: child pid 29505 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by lyrixx** [comment]
You can adapt [this snippet ](https://gist.github.com/lyrixx/17074868cdfabd4c783e).
I suggest you to put it in the front controller (`app_dev.php`) and to use `file_put_contents('/tmp/trace', FILE_APPEND)` instead of `echo`.

This script is going to log each PHP line execute. Obviously, Your application is going to be slow as hell. But at least, you will get the last lines executed and you will be able to figure out what's happening.

**Comment by jvasseur** [comment]
Since your template extends itself it will keep calling itself and PHP segfault on infinite recursions : https://bugs.php.net/bug.php?id=43187

**Comment by fabpot** [comment]
A template cannot extend itself. What would that mean?

The segfault is indeed "normal" as PHP enters an infinite loop.
