### ISSUE TITLE
BOM rejection for inherited templates

### ISSUE THREAD

**Issue by tigerw** [twigphp/Twig#2137]
Twig explicitly rejects byte order marks present in templates which extend some other base template. This behaviour seems inconsistent with the property of the BOM in that it denotes an attribute of the file rather than content to be displayed.

Is there any technical or semantic reason why the mark should be accepted in some cases but not others?

**Comment by fabpot** [comment]
Thinking about this issue, would it make sense to just remove/ignore the BOM in such a situation?

**Comment by stof** [comment]
yeah, it might be fine

**Comment by fabpot** [comment]
see #2808
