### ISSUE TITLE
Inner scopes unable to overwrite outer-scope variables?

### ISSUE THREAD

**Issue by martixy** [twigphp/Twig#2138]
I just ran into this... I use a 3P bundle, which defines blocks I can override.
In this particular case it also defines a variable outside of any blocks.

So I extend the template, overwrite this variable in one block and in another block, I don't get the overwritten value.

If this is by design, the least that can be done is to document this behaviour. Neither `set`, nor `extends` documentation make even a passing mention of this.

**Comment by stof** [comment]
the code being outside the blocks in a child template (which is restricted to defining variables) is executed before any code of the parent template. So you are not overriding the variable when defining it top-level.

Regarding defining it in a block and not getting it in another sibling block, this is totally expected: each block defines a new scope in Twig. So variable assignments never go out of the block.

**Comment by martixy** [comment]
The variable is being defined outside of blocks in the parent template, not the child.

In the child template twig reports that it is not defined outside of blocks and if I try to overwrite it inside an overridden block, the value does not persist to a sibling overridden block.
Even if this is by design, IMO, it should at least be explicitly mentioned in the documentation.

**Comment by stof** [comment]
Overwriting it in a block means you are defining it again. but this defines it again only for the current scope.
