### ISSUE TITLE
[RFC] FQCN extension names?

### ISSUE THREAD

**Issue by ro0NL** [twigphp/Twig#2147]
Hi,

Any thoughts on referencing extensions by FQCN? Similar as symfony form types are doing..

```php
$env->addExtension(new Twig_Extension_Core());
$env->getExtension(Twig_Extension_Core::class);
```

Imo. the `getName` is causing namespace collisions that can only be solved by creative naming yourself (where we already have a unique class name).

Also see https://github.com/symfony/symfony/pull/20053, this causes symfony to provide `asset` and `intl_bridge` whereas twig-extensions provides `intl`.

**Comment by fabpot** [comment]
Indeed, that's probably a good idea. I will have a look at this.

**Comment by ro0NL** [comment]
Awesome :)

**Comment by fabpot** [comment]
see #2148
