### ISSUE TITLE
Does not find templates for paths with symlink and .. in it

### ISSUE THREAD

**Issue by UlrichKu** [twigphp/Twig#2149]
Our system looks for several files in a .. directory. And on some machines this path then also contains  a symlink.

This commit https://github.com/twigphp/Twig/commit/6f0e3edbc55a7ce0464fa0ec90462d66822e0750#diff-ab2c33d8c67960ac482a493a70f61126 removes the usage of "realpath" which yielded the correct absolute path.
Instead the new "normalizePath()" in "FileSystem" simply removes directories if it finds a .. in the path.

Example:
The path as template given to Twig is dir1/dir2/../dir3/template.twig and dir2 is a symlink.
The current result in Twig would be dir1/dir3/template.twig which does not exist.

The workaround is to specify the correct absolute path directly.

**Comment by SpacePossum** [comment]
maybe https://github.com/twigphp/Twig/issues/2145 ?

**Comment by fabpot** [comment]
Fixed in the upcoming 1.27 version.
