### ISSUE TITLE
Stale templates loaded from cache even if Loader#isFresh() returns false

### ISSUE THREAD

**Issue by AssortedParrot** [twigphp/Twig#2151]
I'm using Twig 1.24.2 with Symfony 2.8.

I followed the [Twig recipe for loading templates from the database](http://twig.sensiolabs.org/doc/recipes.html#using-a-database-to-store-templates) and created a loader class for my templates. I'm facing the problem that Twig will still load the cached version even if the template changed in the database. My loader's `isFresh()` method returns false, but Twig doesn't seem to honor it.

I believe the problem is in `Twig_Environment`, specifically in `lib/Twig/Environment.php`, in function `loadTemplate`, line 391 and following:

```php
            if (!$this->isAutoReload() || $this->isTemplateFresh($name, $this->cache->getTimestamp($key))) {
                $this->cache->load($key);
            }
```

If auto reload is disabled, it will always (try to) load the template from the cache, even if the cached version is not fresh. Shouldn't the `||` be changed to `&&`? Then it would automatically reload the template if auto reload is enabled, and fetch it from the cache if the cached version is still fresh.

**Comment by stof** [comment]
if you disable autoReload, this is totally expected. ``autoReload = false`` precisely means "if the cache exists, use it without checking for freshness". The goal is to optimize things for the common case where templates are stored in the project source code, and so they cannot change without a deployment (and the cache would be removed during deployment).

If you want to check for template changes each time, you precisely want ``autoReload = true`` (this is exactly what it means)

**Comment by AssortedParrot** [comment]
I see. I sort of thought, why use auto reload if it still loads templates from the cache, but I think I can see how that makes sense.

How big is the performance penalty when using auto reload? It's still loading templates from the cache, so the only overhead should be checking the freshness?

**Comment by stof** [comment]
Well, if the template has not changed since the last time we compiled it, we can reuse the cache, to be faster. If you don't want to use the cache at all, disable it in the constructor.

Regarding the performance penalty, it depends on the filesystem performance for stat calls
