### ISSUE TITLE
Perfomance of comparing two objects

### ISSUE THREAD

**Issue by edamov** [twigphp/Twig#2153]
Why the second variant works more quicker? I tried it on count of 10 000 elements in `items` and the second variant works 8x times quicker.
```twig
1)
{% for item in items %}
    {% if item.id == object.id %}
        ...
    {% endif  %}
{% endfor %}

2) 
{% for item in items %}
    {% if item == object %}
        ...
    {% endif  %}
{% endfor %}
```

**Comment by xabbuh** [comment]
The first example involves all the Twig logic that is needed to extra `id` from the object (checking for different kind of accessors and so on) while in the second example Twig can simply pass both objects to PHP's `==` operator.
