### ISSUE TITLE
[feature request] Add a {% print … %} tag

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#2156]
I think Twig should have a `{% print … %}` tag, that works identically to `{{ … }}`.

**I do realize this is completely pointless from a technical point of view.**

But from an educational point of view, it would be easier to explain how Twig templating works to noobs if this existed. I've found that most noobs think `{{ variable }}` tags are just how you access a variable, even within other `{% … %}` tags ([example](http://craftcms.stackexchange.com/q/17079/9)) – and for whatever reason this is a hard assumption to break.

If a `{% print … %}` tag existed, when teaching someone Twig you could start by only introducing normal `{% ... %}` tags (including `print`). Once they have a basic understanding of normal tags, you could introduce `{{ ... }}` tags, as a _shortcut_ for `{% print … %}`, which I think would help it “click” better.

**Comment by brandonkelly** [comment]
(I’d be happy to add the tag myself, but would like to get @fabpot’s blessing before getting to work.)

**Comment by fabpot** [comment]
Thanks for your suggestion. But that won't be added to Twig as it would be very wrong from a semantic point of view. 

``{{     }}`` The “say something” syntax
``{%     %}`` The “do something” syntax

**Comment by fabpot** [comment]
What we can do, as I realize that's not already the case, is to start the "Twig for Template Designers" chapter with this information.

**Comment by svenluijten** [comment]
"do something" can be said to also encompass "print something" though, right? Semantically it makes sense in my opinion, much like you start with `<?php echo $var ?>` in PHP and then later learn about `<?= $var ?>`.

**Comment by brandonkelly** [comment]
@svenluijten was thinking the exact same thing (including the PHP tag example:)

**Comment by fabpot** [comment]
ok, let's take the time to discuss this a bit more

**Comment by erikreagan** [comment]
> ...it would be very wrong from a semantic point of view.
> `{{ }}` The “say something” syntax
> `{% %}` The “do something” syntax

These semantics actually seem to support the feature request the way I'm reading it.

In getting one of my team members up to speed on Twig I actually used this echo/print comparison which helped a lot. I just wanted to throw some support behind the FR.

**Comment by iltar** [comment]
The designers I work with actually had no problems understanding twig at all. I think the difference that Fabien gave between 'say' and 'do' is exactly the way it should stay. I can't really envision either what it should look like. I think twig should stay as clean as possible. The fact that we have e.g. {{ include() }} and {% include %} is already annoying and confusing enough.

If it's just for educational purposes, maybe a tutorial on how to write your own tag or a custom repository for educational purposes could suffice.

**Comment by brandonkelly** [comment]
@iltar Not to derail this convo, but the include() function is great for times when you need to include a template as a variable – much cleaner than `{% set … %}{% include … %}{% endset %}`. Maybe the docs should clarify use cases when include() makes sense.

I’d say it’s similar to how the [range()](http://twig.sensiolabs.org/doc/functions/range.html) function has a `#..#` shortcut, and how the [|slice](http://twig.sensiolabs.org/doc/filters/slice.html) filter has a `[#:#]` shortcut. If the `{% print … %}` tag existed, we could start thinking of the `{{ … }}` syntax as just another shortcut.

Yes, it’s a change in the way we think about `{{ … }}` tags, but that’s not a bad thing if it’s a more natural way of thinking about them for newcomers.

**Comment by ryanirelan** [comment]
Semantically, Brandon's proposal makes sense. As an educator, it would make it simpler for my students if I teach the "long way" first and  the "shortcut" second. A lot of the people I teach do not write code outside of templates. To them, `{{ something }}` is a variable (like `$something`), not an output tag. I've also used the example `echo $something;` like Erik. But this translation doesn't always click because a lot of people are not familiar enough with PHP (yes, I realize this is a page 1 example of every PHP book or tutorial). They're using Twig as part of CMS that allows to them to work without needing to know PHP.

The only time I'd ever use Brandon's proposed `{% print ... %}` is in education on Twig but it would go a long way to be clear about how Twig variables work. 

Adding the functionality would also make this explanation from the Twig docs allows us to back it up with a code example:

> There are two kinds of delimiters: {% ... %} and {{ ... }}. The first one is used to execute statements such as for-loops, the latter prints the result of an expression to the template.

I'm happy to contribute to the documentation for this change.

**Comment by stof** [comment]
@ryanirelan if they thing that ``{{ something }}`` is the variable, they will have troubles as soon as they start using functions or filters and need to pass them a variable as argument. So to me, this looks like an issue in the way Twig is explained, not in the way Twig works.

**Comment by brandonkelly** [comment]
The issue probably stems from the fact that some simpler find-and-replace-based templating systems do just look for `{variable}` strings and replace them with the values. ExpressionEngine is one example. If you’re coming from something like that, then it’s reasonable to assume `{{variable}}` is Twig’s slightly more verbose version of the same thing. Even if you read the Twig docs, if you’re pretty sure you already understand what `{{variable}}` does, you’re not going to pay close enough attention to it.

I believe that skipping `{{ … }}` tags entirely in the initial introduction, and introducing them as a shortcut for `{% print … %}` should avoid that trap. (And I’m not saying Twig’s official docs should necessarily take that approach; but it would make sense for 3rd party introductions aimed at less technical designers.)

**Comment by fabpot** [comment]
I'm going to close this one as I'm still not convinced we need to change anything here.
