### ISSUE TITLE
Warning occurs in "vfs://path/to"

### ISSUE THREAD

**Issue by chihiro-adachi** [twigphp/Twig#2166]
I'm using vfsStream.
https://github.com/mikey179/vfsStream

from twig 1.26.0, php warning occurs:

`Warning: file_get_contents(vfs:/twig_dir/test.twig): failed to open stream: Invalid argument in /path/to/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 131`

```
<?php
require_once 'vendor/autoload.php';

use org\bovigo\vfs\vfsStream;

vfsStream::setup('twig_dir');
$twig_dir = vfsStream::url('twig_dir');

file_put_contents($twig_dir.'/test.twig', '<h1>test</h1>');

$loader = new \Twig_Loader_Filesystem($twig_dir);
$twig = new \Twig_Environment($loader);

echo $twig->render('test.twig');
```
this code, twig 1.24.2 OK, twig 1.26.0 NG

The path of the URL format(ex: vfs://path/to/test.twig) is not available, is specifications?

**Comment by fabpot** [comment]
Can you check that #2178 fixed your issue?

**Comment by chihiro-adachi** [comment]
@fabpot 
i confirmed this fix.it is ok.
thank you !
