### ISSUE TITLE
Move isDebug() check to compile time instead of removing the code from the Token_Stream.

### ISSUE THREAD

**Issue by LionsAd** [twigphp/Twig#2167]
In 1.25.0 / 1.26.0 I could do:

```php
$source = $this->parser->getStream()->getSource();
```

In 1.26.1 this returns an empty string.

I can see that we don't want to pollute templates with the source code, but could we make the source available in the Twig_TokenStream.

Our use case is that in Drupal 8 we want to allow 'drilling' down into templates for which we need the source code at the parser level.

For now I can pin the version to 1.26.0, but it would be really good if the added check was moved to compile time.

**Comment by stof** [comment]
what do you mean by "drilling down" ?

**Comment by LionsAd** [comment]
We do have preprocessors for themeable objects, for which we historically use so called render arrays.

e.g. you might have one that looks like:

```php

$build = [
  '#theme' => 'block',
  '#block' => $block,
];
```

which in the end after the preprocess and rendering steps, will load a template called block.tpl.php.

We have that pretty granular, so we have the same for e.g. 'field'.

Now many themers want to use a template within a parent template:

e.g.

```twig
{{ body }|

<span class="sidebar">
{% inline_template field_image %}
Label: {{ label }}
{% endinline_template %}
</span>
```

While it would be possible to implement that inline template purely with twig blocks (using __internal), that would make it impossible to use features like {% extend %} or other things.

So the idea is to just extract the source out of it and instead use:

```twig
Label: {{ label }}
```

as the inline template (hashed by it's content), which means that the inner contents of the inline template behave as if they were in its own file and included. (e.g. like loadTemplate) with the difference that all the preprocessors have run and post-processors run afterwards, which is important for admin sensitive markup like contextual links.

e.g. my template then looks like:

```php
        echo $this->env->getExtension('Twig_Extension_Sandbox')->ensureToStringAllowed($this->env->getExtension('Drupal\Core\Template\TwigExtension')->escapeFilter($this->env, $this->env->getExtension('Drupal\Core\Template\TwigExtension')->renderInlineTemplate($this->env, $context, (string) $this->renderBlock("inline_template___internal_d57134179531fdfd2158ddcf7e945e3c806a59a11ba7d033752f94e4692d9085", $context, $blocks), (isset($context["field_image"]) ? $context["field_image"] : null)), "html", null, true));

// ...

    public function block_inline_template___internal_d57134179531fdfd2158ddcf7e945e3c806a59a11ba7d033752f94e4692d9085($context, array $blocks = array())
    {
        echo "  Label: {{ label }}";
    }

```

I have all of that working (and as its render array specific) it is only for Drupal 8 anyway, but I need the check moved from the Lexer to the compile time or construction time of the Twig_Node_Body.

As you can see I just return the source code of the inner template from the block instead of the compiled version, which is then run via loadTemplate() again, etc.

**Comment by LionsAd** [comment]
https://www.drupal.org/node/2047263#comment-11698221 is my patch to Drupal (FYI)

**Comment by stof** [comment]
your use case seems like a use case for ``{% embed %}`` to me. Couldn't this be used ?

**Comment by stof** [comment]
btw, having the source in the lexer was *added* in Twig 1.25 less than 2 weeks ago. So is Drupal really relying on it already for its own need ?

**Comment by LionsAd** [comment]
@stof No, but I just did make the same patch to add getSource() locally for this patch and when I was about to push it upstream I updated twig and it was already there.

And no, embed is a completely different concept.

I am basically doing:

```php
  $context['var'] = [
    '#theme' => 'var',
    '#pre_render' => [function($elements) {
      $elements['#label'] = $elements['#entity']->label();
    }],
    '#post_render' => [function($input) {
      return '<wrapper>' . $input . '</wrapper>';
    }]
    '#entity' => $entity,
  ];
```

```
{{ render_var(var) }}
```

which then calls var.html.twig, which by default looks like:

```
<div class="for-fun">
  Label: {{ label }}
</div>
```

So now I could do:

```php
$context['var'][#theme] = ['var__no_wrapper', 'var'];
```

and add a 'var--no_wrapper.html.twig' file (which is found based on the suggestion) with:

```
Label: {{ label }} 
```

and do the same for every other special case or I could do with my patch just do:

```
{% inline_template var %}
  Label: {{ label }}
{% endinline_template %}
```

And that is why for Drupal it is so powerful as the #pre_render and #post_render still works properly.

Of course I could do:

```
{{ var[#entity].label }}
```

or

```
<wrapper>{{ var[#entity].label }}</wrapper>
```

but now I loose all the post process wrapper and in Drupal - where everything is dynamic - I can't rely on someone not adding more #post_render wrappers.

So hard-coding won't work either.

And that is what drillability is about.

**Comment by stof** [comment]
I don't see why you need the source here. You should be using the parsed AST of the tag body instead.

**Comment by LionsAd** [comment]
@stof The advantage of the source is that it is treated as a completely new template, which has the advantage that e.g. {% extends %} would work in the inline template.

It also makes it conceptually clearer that it is a completely new template.

I originally just wanted to use the AST in the body of the block__ and callback to that and that would work, but it was hard to explain to our Drupal themers why it should be limited in functionality to a real child template being rendered.

And {% extends %} by now is common already.

**Comment by LionsAd** [comment]
e.g. nothing stops me from doing:

{% inline_template var %}
  {% extends var-base.html.twig %}
  {{ block label }}
  Label: {{ label }}
  {{ endblock }}
{% endinline_template %}

and it would still work completely separately from the parent template.

I need to check that case though.

**Comment by LionsAd** [comment]
That won't work :/.

I tested verbatim though and it works:

```twig
{% filter inline_template(raw_block) %}
{% verbatim %}
  Label: {{ label }}
{% endverbatim %}
{% endfilter %}
```

So {% inline_template %} likely wants to extend verbatim instead of going to the source as it would be nice to simplify the syntax a little.

But in general that works without any TokenParser, which is kinda nice.

**Comment by LionsAd** [comment]
@stof Is there any processor in twig to change the source (similar to a C preprocessor before) parsing the template?

e.g. between loading and lexing?

If not officially supported upstream, it likely could be added to environment compileSource() right?

And then just collect source preprocessors from the extensions.

As really what I want to do is transform:

```
{% inline_template [expression] %}
```

to

```{% filter inline_template(var) %}{% verbatim %}```

in advance of the parsing. cc @fabpot

**Comment by stof** [comment]
we don't have such preprocessor. But as drupal has its own loader already, it could do it during loading

**Comment by LionsAd** [comment]
@stof Is it a known bug that verbatim tags can't be nested?

**Comment by stof** [comment]
@LionsAd this is not a bug. Anything inside a ``{% verbatim %}`` is not Twig markup anymore, but content displayed as is. When finding a ``{% verbatim %}`` tag, the Twig lexer will move until it sees a ``{% endverbatim %}``, without giving any special meaning to anything else it sees (so a ``{% verbatim %}`` inside it would just be normal text to be displayed in the output)

**Comment by LionsAd** [comment]
Yeah, just finds the wrong endverbatim tag. But I saw its impossible to solve with regexp alone by a little research.

**Comment by stof** [comment]
@LionsAd this is not the wrong end tag. It is wrong only in your mind, as you expect the content inside ``{% verbatim %}`` to contain Twig markup (and so balanced tags), while ``{% verbatim %}`` is precisely about making its body text-only

**Comment by LionsAd** [comment]
@stof Correct:

```twig
{% verbatim %}
  {% verbatim %}
  {% endverbatim %}
{% endverbatim %}
```

obviously can't work as it does not know as there is just 'text' inside.

**Comment by LionsAd** [comment]
@stof Thanks for all the feedback! That was very helpful.

I will go with the tokens of the inner body approach in a block (as extends won't work anyway) + add functionality to render an inline template.

That way I no longer need getSource() on the token stream.

I still think @nicolas-grekas PR is better for other reasons, but for Drupal (Twig) we don't need it anymore!

Therefore closing.
