### ISSUE TITLE
_self (or the template name) as a default argument to twig functions

### ISSUE THREAD

**Issue by CriseX** [twigphp/Twig#2174]
Is there a way to pass the equivalent of _self as a default argument to Twig functions implemented using Twig_SimpleFunction. I saw a closed pull request that added an option to pass the template instance to functions and filters but that seems to have been closed as unnecessary.

Might I also add, the whole business with _self is mighty confusing... I mean first it was deprecated and then it wasn't and so on...

**Comment by fabpot** [comment]
Why do you need `_self` in a function or filter?

**Comment by CriseX** [comment]
My original use case has to do with the function having to do caching of what it is doing. So I need something to build a cache key out of (serializing the context and hashing it is another, perhaps better, option but it can also be slower).

Another thing where I have bumped into this is when I need to do something with the uncompiled template source. ie. `{{ do_foo(source(_self)) }}`

As an aside, the scenario where you need to get source of the current template file could be optimized by removing the disk I/O from it. Although I noticed you opted to remove getSource when running without debug mode.

**Comment by fabpot** [comment]
The fact that template are compiled as PHP classes is an implementation details that you should not rely on. So, I don't want to expose it "too much".
