### ISSUE TITLE
Regression in #2124 (1.25.0)?

### ISSUE THREAD

**Issue by mnapoli** [twigphp/Twig#2175]
Hi, we've seen an issue with 1.25.0 with Puli: https://github.com/puli/issues/issues/204

Specifically that part of #2124:

```diff
-        $module->setNode('parent', $parent);
+        if ($fakeParentToken === $parentToken) {
+            $module->setNode('parent', $parent);
+        }
```

The parent node ends up not always being defined. I'm not sure if it's a regression: should the "parent" node always exist or not?

**Comment by fabpot** [comment]
@mnapoli It should always be set, we just override the value when it's a dynamic one. Can you give me a small script that makes this reproducible, so that I can investigate further? Thanks.

**Comment by fabpot** [comment]
Closing as I think the fix should be on Puli instead (I've submitted a PR there).
