### ISSUE TITLE
Use only selected blocks from trait

### ISSUE THREAD

**Issue by ogizanagi** [twigphp/Twig#2177]
Currently, horizontal reuse is available, but AFAIK does not allow reusing only some blocks from targeted template, even with the `with...as` notation:

``` twig
{# Will use all blocks and redefine existing ones #}
{% use "blocks.html" %}
```

``` twig
{# Will actually use all blocks, redefine existing ones, #}
{# but alias "sidebar" block in order to avoid collisions #}
{% use "blocks.html" with sidebar as base_sidebar %}
```

However, I think something like the following may be useful:

``` twig
{% use "blocks.html" with sidebar as base_sidebar only %}
```

For instance, in this [TwigFiddle](http://twigfiddle.com/vqlw1z), I'd like to get the following output:

```
Child Sidebar - Trait Sidebar
Parent Content
```

without the `only` feature, I get:

```
Child Sidebar - Trait Sidebar
Trait Content <-- using the trait replaced all blocks
```

Of course, I can alias `content` when using the trait, but it can be a pain when a lot of blocks are named the same, for instance when dealing with form themes in a Symfony application.

**Would such a feature be useful and doable ?**

Also, in many ways it looks similar to the **macro import** tag, thanks to which you can import only required macros:

``` twig
{% from 'forms.html' import input as input_field, textarea %}
```

**But it doesn't allow to import blocks. Would it be a better candidate ?**

**Comment by fabpot** [comment]
Why not splitting your templates in smaller chunks that makes sense when importing? It's up to you to include as much or as less blocks in a template you import. Thus, I think there is no need to add such a feature. Thanks for the suggestion.
