### ISSUE TITLE
request template_from_string

### ISSUE THREAD

**Issue by 719media** [twigphp/Twig#2180]
it would be nice if a {% include %} [really I want to use {% include(template_from_string)) %}, but it appears the issue is support for include, and then template_from_string would work] was valid inside of an {% embed %}

this is because I store a custom code string inside of a database, which is then retrieved by my front end and used to customize overriding certain blocks.

**Comment by stof** [comment]
please fix your comment to use the proper markdown markup for markdown, otherwise code is partially stripped by the markdown rendering (as it does not allow HTML tags). I don't understand what you are asking currently.

**Comment by 719media** [comment]
test1.twig
```
{% embed 'test2.twig' %}
  {% block default_a %}
    <div>This is overriden a</div>
  {% endblock %}
{% endembed %}
```

test2.twig
```
{% block default_a %}
  <div>This is default_a</div>
{% endblock %}
{% block default_b %}
  <div>This is default_b</div>
{% endblock %}
```

rendering test1.twig produces:
```
This is overriden a
This is default_b
```

Which is according to documentation and great.

What I'm asking for is to have the following give the same result:

test1.twig
```
{% embed 'test2.twig' %}
  {% include 'test3.twig' %}
{% endembed %}
```

test2.twig
```
{% block default_a %}
  <div>This is default_a</div>
{% endblock %}
{% block default_b %}
  <div>This is default_b</div>
{% endblock %}
```

test3.twig
```
{% block default_a %}
  <div>This is overriden a</div>
{% endblock %}
```

Of course, what happens is the error A template that extends another one cannot include contents outside Twig blocks. Did you forget to put the contents inside a {% block %} tag in "test1.html" at line 2? because includes are not valid inside embeds.

**Comment by stof** [comment]
This cannot work, because ``{% include %}`` is about including the output of the template, not about importing block definitions.
Use ``{% use %}`` to import blocks (but you have to make sure that the template does not contain anything outside blocks).

**Comment by 719media** [comment]
Several years ago you responded here: https://github.com/twigphp/Twig/issues/877

Unfortunately for me, `{% use %}` statement does not appear to be compatible with template_from_string, which is my use case.

**Comment by fabpot** [comment]
closing for the same reasons expressed in #877
