### ISSUE TITLE
Variable can be dumped but throws an exception 

### ISSUE THREAD

**Issue by abernard18** [twigphp/Twig#2189]
So, I have template which overwrite some blocks form an other template and inherit variables from a third template. 

One of the variable seems to be inaccessible in one of the blocks, but not in the other ones.

My first template embed the _list template :
`{% embed "AtgpTrackerBundle:Ticket:/_list.html.twig" with {"table": table, "category": category} %}`

This _list template extends a defaultTable template, which contains some blocks :
```
                 {% block tableHead %}
                        <tr>
                            {% block tableHeadStdColumns %}
                                {% for key, column in table.columns %}
                                    {% include "KilikTableBundle::_columnName.html.twig" %}
                                {% endfor %}
                            {% endblock tableHeadStdColumns %}
                        </tr>
                        {% if table.columns|length > 0 %}
                            <tr>
                                {% block tableHeadStdFilters %}
                                    {% for column in table.columns %}
                                        {% include "KilikTableBundle::_columnFilter.html.twig" %}
                                    {% endfor %}
                                {% endblock tableHeadStdFilters %}
                            </tr>
                        {% endif %}
                    {% endblock tableHead %}
                </thead>    
                <tbody id="{{ table.bodyId }}">
                    {% block tableBody %}
                        {% if tableRenderBody is defined %}
                            {% for row in rows %}
                                <tr>
                                    {% block tableBodyStdColumns %}
                                        {% for column in table.columns %}
                                            {% include "KilikTableBundle::_columnCell.html.twig" %}
                                        {% endfor %}
                                    {% endblock tableBodyStdColumns %}
                                </tr>
                            {% endfor %}
                        {% endif %}
                    {% endblock tableBody %}    
```

And in the _list template, for instance : 

```
{% extends "AtgpTrackerBundle:Table/_defaultTable.html.twig" %}

{% block tableHead %}
    {{dump(category)}}
    {{category}}
{% endblock %}

{% block tableBody %}
    {{dump(category)}}
    {{category}}
{% endblock %}
```

Both dumps work int the sense that they show the variable on screen. The exception "Variable "category" does not exist in AtgpTrackerBundle:Ticket:/_list.html.twig " is thrown at the line of the second dump, the one in the tableBody block. 

This behavior looks really weird to me...

 [Here is a link to the related StackOverflow question](http://stackoverflow.com/questions/40104073/why-does-my-variable-exists-in-a-block-and-not-in-an-other-one?noredirect=1)

**Comment by stof** [comment]
I don't understand what you mean. Please provide more details

**Comment by abernard18** [comment]
Sorry I accidentally pressed the "enter" button before I could type anything... It's edited now.

**Comment by fabpot** [comment]
As there is already a conversation on SO, I'm closing this issue, ans anyway, we only provide support via SO.
