### ISSUE TITLE
Attempted to call an undefined method named "getFilename" of class "Twig_TokenStream"

### ISSUE THREAD

**Issue by mhallnoinc** [twigphp/Twig#2191]
When attempting to load any template.

in vendor/symfony/assetic-bundle/Twig/AsseticTokenParser.php at line 49

`            // check the bundle
            $templateRef = null;
            try {
                $templateRef = $this->templateNameParser->parse($this->parser->getStream()->getFilename());
            } catch (\RuntimeException $e) {
                // this happens when the filename isn't a Bundle:* url
                // and it contains ".."`

**Comment by stof** [comment]
@mhallnoinc use Twig 1.x rather than the dev version of Twig 2 (which can be used only if you allow composer to install dev versions btw). Twig 2 made some additional BC breaks in the past few days, and I have not updated AsseticBundle yet for them.

**Comment by fabpot** [comment]
Closing as Assetic is going to catch up at some point

**Comment by mhallnoinc** [comment]
cool, thanks makes sense.

**Comment by Kookas** [comment]
Hi, is this still an issue?

**Comment by 4d4ch4u32** [comment]
I also got this mistake. Then I saw that I inserted single stylesheets separated by commas. After I fixed that, it worked.

**Comment by 4d4ch4u32** [comment]
So, the error is not the error above - it's the error message wich is not really helpfull.

**Comment by audoh** [comment]
Yeah, there would still be an error, but this is was an error from trying to throw that error. Is it still present?

**Comment by 4d4ch4u32** [comment]
Yes, I got this error an hour ago..
