### ISSUE TITLE
Cache file permissions

### ISSUE THREAD

**Issue by johndodev** [twigphp/Twig#2196]
Hello,

I have an issue with cache files permissions.

It seems included templates, invoked with {{ render('/path') }} or {% include 'path' %}, or manually rendered with a twigExtension, doesn't follow umask permissions.

I tryed with a 0000 umask on index.php : 

![permissions](https://cloud.githubusercontent.com/assets/2741956/19567657/d9644c26-96ee-11e6-8401-83c4ab9f99ea.png)

you can see 4 folders which are not 777, there is 
- my sidebar, {{ render('/sidebar') }}
- two widget called with an extension, return $this->twig->render('...'), 
- my footer, {% include 'footer' %} in the layout.

but there is no problem with my header, which is called exactly like my footer, but before the sidebar. Maybe _render_ function change something ?

Also, it's append only in production mode, in developpement, all created directories are in 777.

Actually I just need a 0002 umask, my CLI user is on the same group as my apache user, and should be able to delete the cache.

Am I missing something ?

**Comment by stof** [comment]
``render()`` in Symfony triggers a subrequest. Could it be possible than somewhere inside this subrequest, you have something changing the umask again ?

**Comment by johndodev** [comment]
It doesn't append every times, and actually not with only included templates.

I will continue to try to understand when it append, I keep you in touch if necessary..

**Comment by fabpot** [comment]
Closing until @johndodev find the exact reason.
