### ISSUE TITLE
Support variable definitions in the "use" tag

### ISSUE THREAD

**Issue by mpdude** [twigphp/Twig#2201]
`include` and `embed` have the option of defining (or re-naming) variables for the included or embedded template code. Although not as explicit as macro parameters (or method parameters in PHP code), this helps to make the interface clear when providing re-usable template snippets. Also it avoids cluttering the scope in the calling template.

For the `use` tag, this feature is missing. It would be great if we could add this. However, the `with` keyword cannot be used in this case because it already has a different meaning, it renames the blocks.

Maybe I can come up with a complete PR if the maintainers support the idea in the first place.

**Comment by hason** [comment]
`include`/`embed` renders a template, but `use` imports blocks from a template - defining variables in this case does not make sense. You maybe want #1433.

**Comment by mpdude** [comment]
My use case is where I have some kind of pattern or component library where a template can `use` one of several possible forms of displaying some data that needs to be placed in several blocks across the page, like so:

```
# feat.html.twig
{% block page_top %}
    {{ title }}
{% endblock %}
{% block stage %}
    {{ description }}
{% endblock %}
```

There are several variants of this (more complex in markup, of course) and the template picks one of them. Now currently, I am forced to write 

```
{% set title = obj.title %}
{% set description = obj.description %}
{% use "feat.html.twig" %}
```

Here, the `title` and `description` variables serve as the "interface" for the `feat.html.twig` component. If something like

```
{% use "feat.html.twig" let { 'title': obj.title, 'description': obj.description %}
```

were possible, IMO that would make intentions much clearer and prevent polluting the variable scope.

**Comment by stof** [comment]
``{% use %}`` does not execute the template, it imports block definitions. So your proposal does not make sense. Blocks will be rendered with the context available at the time you call ``{{ block('stage') }}``
