### ISSUE TITLE
Fatal error: Call to undefined method __TwigTemplate_d274519e20721b515a2322ff9f7f6a4f0f79ad7f90c66b59425305e717ac8c0e::dispaly() 

### ISSUE THREAD

**Issue by Conero** [twigphp/Twig#2207]
public function indexAction()
   {
       $v = $this->view->loadTemplate('Twig/index.html');
       // Error From $v->dispaly....
       $v->dispaly([
           'about' => 'TWig <a href="http://twig.sensiolabs.org/" target="_blank">Twig</a>'
       ]);  
   }

$this->view  => 
    public function Twig()
    {
        require $this->_dir.'Autoloader.php';
        \Twig_Autoloader::register();
        if(is_array($this->_option)) $opt = $this->_option;
        else $opt = config('Twig_opt');
        if(isset($opt['view_dir'])){
            if(isset($opt['cache_dir'])) $loader = new \Twig_Loader_Filesystem($opt['view_dir'],[
                'cache' => $opt['cache_dir']
            ]);
            else $loader = new \Twig_Loader_Filesystem($opt['view_dir']);
        }
        else $loader = new \Twig_Loader_String();//debug($loader,true);
        $twig = new \Twig_Environment($loader);
        if(isset($opt['debugging'])) $twig->addExtension(new \Twig_Extension_Debug());
        return $twig;
    }

**Comment by fabpot** [comment]
dispaly should be display.

**Comment by Conero** [comment]
echo $this->view->display('Twig/index.html',['about' =>  'TWig Twig']);
// It's Work

**Comment by Conero** [comment]
I fixed it now, thanks @fabpot!
I did some wrong

**Comment by Conero** [comment]
I fixed it now, thanks @fabpot!
I did some wrong
