### ISSUE TITLE
Removing @internal tag

### ISSUE THREAD

**Issue by kubawerlos** [twigphp/Twig#2210]
Some [deprecation notices](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/TokenStream.php#L169) suggest to use [function](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/TokenStream.php#L197) which has tag [@internal](https://phpdoc.org/docs/latest/references/phpdoc/tags/internal.html) in [Twig 2](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/TokenStream.php#L151) too, so IDE (e.g. PHPStorm) shows it as strikethrough.

Can we get rid of it?

**Comment by hkdobrev** [comment]
@kubawerlos Do you think you could provide a pull request which would ease the maintainers in considering it?

**Comment by kubawerlos** [comment]
"Lucky" me, I have found only place where it happened.

**Comment by fabpot** [comment]
@kubawerlos Can you share the place you found using this because regular uses of Twig should not use this method. This method is internal and should not be used.

**Comment by kubawerlos** [comment]
@fabpot I have found it fixing deprecated notices in assetic: https://github.com/kriswallsmith/assetic/pull/820/files#diff-e33c72b736dde42d91589869af6937db

**Comment by fabpot** [comment]
Ok, Assetic is really specific, so I was more thinking about real-world usage. So, closing this issue. Thanks for your fast feedback.
