### ISSUE TITLE
[BCB] v1.27.0: relative paths should not be the default

### ISSUE THREAD

**Issue by RenaudParis** [twigphp/Twig#2211]
Hi,

After updating from 1.26.1 to 1.27.0, I experienced a bug that forced me to rollback to 1.26.1.

I have several "applications" (webapp, admin, emails) handled by the same server, and I extend "_layout.twig" template in each page template of each app (each app has its own root-located "_layout.twig" template, of course!).

To be noted that I only add two paths to TwigLoaderFilesystem: the app's (webapp/admin) and the emails' (which are common so that every app can use them: admin/webapp/api).

Also to be noted that I'm not using the namespaces, because I was using Twig before it was added in 1.1. I just make sure I don't have the same template name twice (subfolder + file name) in two different "apps". And it works fine :)

However, after updating to version 1.27.0, whatever "_layout.twig" file is loaded first is stored in cache and used in all three applications, which should not happen. This is because of the new "relative paths" thing that was added in v1.27.0 and became the default.

It should not be the default, because it breaks applications like mine. Indeed, before v1.27.0, the "_layout.twig" template loaded by any page template extending it (say "main/homepage") was relative to the view folder that "main/homepage" template was in (in my case: either webapp, admin, or emails). Which is more of a "absolute path" behavior than "relative path".

You should leave "absolute paths" to be the default and allow those who wish so to voluntarily use "relative paths" by manually adding a new option, whenever some developers really need to benefit from this "portable" bonus that "relative paths" allow. Because I may be wrong, but I'm not sure the majority of developers here really need to warm the Twig cache in another server/vhost beforehand. However all those who, like me, have been using Twig for a long time and have not yet modified all their templates to use namespaces, will experience this BCB.

Please tell me if I'm wrong somewhere or if I missed an option in the updated docs (which I read after experiencing this bug) that allows to use the old behavior. For now I just rolled back to v1.26.1 and my website works fine again :)

Best regards,

**Comment by fabpot** [comment]
If I understand correctly, you have 3 different applications (with different Twig configurations -- at least, the filesystem loader configuration) sharing the same Twig cache?

**Comment by fabpot** [comment]
Actually, I don't understand when that can happen. Can you give me a small script that reproduces the issue? I must be missing something here.

**Comment by RenaudParis** [comment]
Mmmh not exactly. I have 3 "applications" (webapp, admin, api -- which sends emails) located in the same place on the same server, each one having a specific vhost, but sharing the same common code (models, libs, ... including the Twig management class).

The Twig management class uses the Twig_Loader_Filesystem to provide Twig with places to search for templates.

Here is the ctor code, if it can help understand better how the application is architectured:

```
public function __construct(\stdClass $oConf)
{
	// Templates access path
	$aPaths = array();
	$aPaths[] = PATH_APP . 'view'; // App-specific views (webapp, api, admin). PATH_APP is defined in each front controller
	$aPaths[] = PATH_COMMON . 'view'; // Common views (like emails, typically)

	// Folder structure:
	// /mygreatapp/
	//			-> app/
	//					-> admin/
	//							-> view/
	//									_layout.twig
	//									-> module1/
	//									-> module2/
	//					-> webapp/
	//							-> view/
	//									_layout.twig
	//									-> module3/
	//									-> module4/
	//					-> api/
	//							-> view/
	//									(empty, using common/view/email)
	//					-> common/
	//							-> view/
	//									-> email/
	//			-> lib/
	//			-> cache/
	//			-> log/
	//
	//
	// The problem with Twig version 1.27.0 is happening for admin/view/_layout.twig and
	// webapp/view/_layout.twig because the new system does not seem to take the subfolder
	// into account for unicity of the cache file.



	$this->_config = $oConf;
	$this->_pathsViews = $aPaths;

	$bIsDev = \TestApp\AApp::isDev();

	$oTwigLoader = new \Twig_Loader_Filesystem($aPaths);
	$this->_twig = new \TestApp\Twig\Env($oTwigLoader, array(//\Twig_Environment($oTwigLoader, array(
														  'cache' => $bIsDev ? false : $oConf->view->cache,
														  'debug' => $oConf->view->debug,
														  'autoescape' => false,
														  'strict_variables' => true // Ensure valid templates with no undefined variables
	));

	// Allow for debug in DEV env.
	if ($bIsDev)
		$this->_twig->addExtension(new \Twig_Extension_Debug());

	// Global variables
	$this->_addGlobals();

	// Custom functions
	$this->_addFunctions();

	// Custom filters
	$this->_addFilters();
}
```

As I said, I could rename (for example) admin/view/_layout.twig in admin/view/_layout_admin.twig in order to have unique filenames, but then I'd have to change every place where this file is extended.

No big deal, of course, but I'd have preferred not to have to do it, and to have an option to use the old algorithm instead (which takes subfolder into account for computing the cache file name/key).

Best regards,

**Comment by fabpot** [comment]
The subfolder names are part of the key, so that's why I don't understand the issue here.

**Comment by RenaudParis** [comment]
It does not seem to be the case in 1.27.0 though because when I started using it, whatever template was loading first between admin/view/_layout and webapp/view/_layout was then used in both apps whenever I used `{% extends '_layout.twig' %}` in my templates.

**Comment by fabpot** [comment]
I've just tested and (unfortunately) it works well for me. So, if you could create a small script that demonstrate the issue, that would help me tremendously.

**Comment by RenaudParis** [comment]
Okay I will do that today and post it here (except if it allows me to understand why it did not work for me in the first place, but I'll tell you anyway). Thank you for your time in any case!

**Comment by RenaudParis** [comment]
First conclusions: I could not reproduce the bug with a simple test case. And I could still reproduce it with my application (just tested right now). But then I don't understand what else would have an impact on the cache file name. I will investigate further.

**Comment by RenaudParis** [comment]
Ok I think I got the issue.

In version 1.27.0, class `Twig\Loader\Filesystem` method `getCacheKey`, it uses something it doesn't in version 1.26.1: `$this->rootPath`.

Where version 1.26.1 uses fully qualified filename (of the template) as "key" (in `Twig\Environment::getTemplateClass`), version 1.27.0 trims the "rootPath" (which is based on cwd) from the filename before generating the key.

What happens in my real application (as opposed to the test app), is that I am performing a `chdir(PATH_APP);` at the top of every app, which means that for a template file named `/var/www/my_site/app/webapp/view/_layout.twig`, it just keeps `view/_layout.twig` (because cwd is `/var/www/my_site/app/webapp/` and it gets trimmed from the filename). But it does the same for the `admin` app. Which gives us a conflict.

It confirms this is due to the new "portable" / "relative paths" feature of version 1.27.0 of Twig, as I initially thought.

However, I honestly don't think many people will be in the same conditions, so if you don't plan on fixing this, please do tell me and I'll adapt my code instead (maybe remove the chdir and adapt the rest of the includes/whatever for each app), so that I can update Twig to newest versions if needed.

Thank you for your time!

**Comment by fabpot** [comment]
Thank you very much for investigating the issue. This is much appreciated. I would really not recommend doing what you are doing right now as this is really fragile and can lead to all sort of problems. And in any case, that's not something I want to support.

So, I'm closing this issue as a won't fix.

**Comment by RenaudParis** [comment]
Thank you @stof this is indeed a good alternative, as I'd like to minimize the side effects on my code. It's great that it is allowed to override this value!

@fabpot I understand, thank you anyway. Plus, the solution suggested by @stof allows me to mimic the 1.26.1 behavior and therefore prevent any "duplicate cache key" issue without any modification on my app code, which is great!
