### ISSUE TITLE
Build twig with VC14

### ISSUE THREAD

**Issue by mpaine-act** [twigphp/Twig#2213]
Following the instructions on http://twig.sensiolabs.org/doc/installation.html, I'm getting an "unknown option" error trying to compile twig within php-sdk.  I think I setup the ext/twig folder correctly and PHP typically compiles correctly (using nmake):

C:\php-sdk\phpdev\vc14\x64\php-7.0.12-src>configure --enable-cli --enable-pdo --with-pdo-mssql --enable-twig=shared
Unknown option --enable-twig; please try configure.js --help for a list of valid options

![twig](https://cloud.githubusercontent.com/assets/17752788/19869036/d9c50986-9f67-11e6-8263-2588f8071c56.png)

I looked at https://github.com/twigphp/Twig/issues/1200 but that didn't help me.   Any suggestions?

**Comment by SpacePossum** [comment]
Kindly note that the Twig extension is not PHP 7 compatible (ATM), please see https://github.com/twigphp/Twig/issues/2110 and other issues.

**Comment by mpaine-act** [comment]
Thank you.  Would the incompatibility cause this issue, or would I have this same issue if I used PHP SDK 5.6?

**Comment by SpacePossum** [comment]
The error you get seems familiar, but to be honest I haven't tried to build the extenstion (on PHP 7) for a while (nor I'm the author). You could try to build for 5.6, I think it should build OOTB :) 
(but if it is a lot of work you might want to wait for more input from the community)

**Comment by fabpot** [comment]
I'm closing this as I know nothing about Windows, so using StackOverflow is probably a better idea. Sorry.
