### ISSUE TITLE
Consider marking the output of |striptags filter as safe with Twig_Markup

### ISSUE THREAD

**Issue by joelpittet** [twigphp/Twig#2215]
Moving an issue we've been asked for in Drupal:
https://www.drupal.org/node/2705249

> Using |striptags on something should mark the output as safe.
> Right now it doesn't, which results in double-encoding of html entities, fore example.
> You have to use |striptags|raw currently as a workaround, but we don't want people to use |raw.

**Comment by stof** [comment]
using Twig_Markup is a bad idea, as it would mark it as safe for all formats, which is clearly not the case.

And declaring it as safe for html looks wrong to me, as this function does not ensure HTML safety (especially when stripping only partially, as any attributes will be kept on the allowed tags, including JS event listeners allowing a XSS). The output of this filter is not safe for any format

So IMO, having to mark it as raw explicitly when you want to bypass the escaping is a good idea, as it makes you aware that you may have a XSS issue there depending of where the input comes from.
