### ISSUE TITLE
Change to LexerInterface in 1.27 causes BC break with previous implementations

### ISSUE THREAD

**Issue by marc1706** [twigphp/Twig#2218]
The PR #2182 added Twig_Source as another possible input to the LexerInterface tokenize() method. Prior to that, only string was allowed for the `$code` argument.

Due to this change in the expected input of `tokenize()`, any implementation of the `LexerInterface` that relied on the previous fixed string input might run into fatal errors due to them receiving and instance of Twig_Source instead of a string:
`Catchable fatal error: Object of class Twig_Source could not be converted to string`

As a result, backwards compatibility with any implementation prior to 1.27 has been broken.

Also see related discussion in the commit that caused this BC break:
https://github.com/twigphp/Twig/commit/6c76583e23537b2503ccd555d053c09a8250b8ac#commitcomment-19686237

**Comment by fabpot** [comment]
Closing as there is nothing we can do now.
