### ISSUE TITLE
odd behaviour with in and keys-filter

### ISSUE THREAD

**Issue by grindhold** [twigphp/Twig#2219]
[my twig broke. pun intended.]

the following if-statements will both evaluate to true in twig 1.27.0
{% if 'a' in ['a','b'] %} obviously true {% endif %}
{% if 'a' in ['a','b']|keys %} not so obviously true {% endif %}

According to the docs I RTFM'd, ['a','b']|keys should evaluate to [0,1] and therefore should not contain 'a'. Is there any explanation to this?
Have a nice weekend.

**Comment by xabbuh** [comment]
This is due to how `in_array()` works in PHP when types do not match (try it yourself with `in_array('a', array_keys(['a', 'b']))`).

**Comment by grindhold** [comment]
I see. Thanks for the quick answer.
