### ISSUE TITLE
writing html is too terrible

### ISSUE THREAD

**Issue by yozman** [twigphp/Twig#2221]
hi
twig is really helpful
could you please support [pug](http://pugjs.org) grammar for it?

**Comment by reFX-Mike** [comment]
Twig is output agnostic. You can easily use pug-template with twig and then feed twigs' output into the pug-compiler.

**Comment by yozman** [comment]
@reFX-Mike 
could you please give me some example?

**Comment by reFX-Mike** [comment]
No, I can't give you an example. If you are not able to do some minimal programming (using Twig, capturing the ouput and sending it to pug) then maybe Twig isn't for you to begin with?
