### ISSUE TITLE
When parsing a value of a variable starting with number, getting error

### ISSUE THREAD

**Issue by madhurtandon** [twigphp/Twig#2224]
![screenshot 2016-11-08 20 17 26](https://cloud.githubusercontent.com/assets/2477653/20103582/969b62a6-a5f0-11e6-828a-5a52181346ad.png)

I tried this and got the error. Can you please tell me what are the reasons of this, and how we can fix that?

**Comment by SpacePossum** [comment]
You didn't assign a value to the variable '2kss'. Note that you cannot assign a variable starting with a number within a template itself.
You can do something like this:
```twig
{% set kss = 'test' %}
{{ kss }}
```

**Comment by stof** [comment]
Variables names are not allowed to start with a number. This is why you get a syntax error in the template
