### ISSUE TITLE
depecations Using "null" as the cache strategy

### ISSUE THREAD

**Issue by EmyJ** [twigphp/Twig#2225]
hi, 

I have a Deprecation, and I do not know where it comes from.

Deprecation:
Using "null" as the cache strategy is deprecated since version 1.23 and will be removed in Twig 2.0.

ps: If there is need to code, I can give in.

thank you in advance

**Comment by stof** [comment]
The documented way to disable the cache was always ``false``, not ``null``.

**Comment by fabpot** [comment]
Just change the value of the `cache` option to `false`.
