### ISSUE TITLE
Twig best practices for call propery

### ISSUE THREAD

**Issue by ReenExe** [twigphp/Twig#2226]
```php
class Entity
{
    private $id;
    
    public function getId()
    {
        return $this->id;
    }
}
```

in twig can use:
1.
```
{{ entity.id }}
```
2.
```
{{ entity.getId() }}
```

Understand - this is minor, but what will better in large projects?

**Comment by fabpot** [comment]
2 is much faster, 1 is slower
1 is a better abstraction as it hides the implementation
up to you :)
