### ISSUE TITLE
Trying to get variable key name for array

### ISSUE THREAD

**Issue by concept-core** [twigphp/Twig#2230]
Hello everyone,

I want to be able to get a variable key for one of my arrays ( laravel collection ).
I did not find a way to do this so I will show an example.

```twig
Region = {{ regions.{{item.region_id}} }}
```

Is something like this possible ?

**Comment by SpacePossum** [comment]
```
Region = {{ regions.{{item.region_id}} }}
```

With this statement you tell Twig to print `item.region_id` inside a print statement, which cannot be done.
Try something like:
```
Region = {{ regions[item.region_id] }}
```

**Comment by concept-core** [comment]
@SpacePossum God sorry, 
I feel stupid now.

That does work indeed.
Thanks for the help !

**Comment by SpacePossum** [comment]
you're welcome :)
