### ISSUE TITLE
Current Template and Line Number

### ISSUE THREAD

**Issue by ralouphie** [twigphp/Twig#2233]
Firstly, thank you for Twig. It's one of most useful PHP packages out there.

For a feature I'm working on it would be extremely useful to have the current twig file and line number available in my extension. 

Currently I am hacking that together by using base template class to push/pop from a stack, extending the compiler to write the current line number, and extending the twig environment to expose the call stack.

I would love to be able to add this feature directly to Twig. If I open a PR for this feature addition, would it be considered?

**Comment by stof** [comment]
What is the use case ?

**Comment by ralouphie** [comment]
There are a couple of use cases but they both deal with knowing what the current source twig file/line is at runtime. One use case is the ability to measure function/filter/extension usage at runtime by file/line. I'm working on a system that is multi-tenant and exposes helpers in twig that make dealing with data easier. We have a pipeline to aggregate runtime metrics on calls for optimization. Being able to include twig file/line per call is extremely helpful.

**Comment by stof** [comment]
The right time to detect the usage of filters and functions would be at compilation time using a NodeVisitor, and then storing this info during the compilation (which can be done by hooking into extension points of the Twig_Node_Module to add a new method in the compiled template exposing this collected data)

**Comment by fabpot** [comment]
Closing as this is probably not something we want in core. Thanks for proposing.
