### ISSUE TITLE
Using twig_call_method.php is not compatible with class cache

### ISSUE THREAD

**Issue by superdav42** [twigphp/Twig#2243]
Using the latest twig master with the Symfony TwigBundle produces this error 
Fatal error: Symfony\Component\ClassLoader\ClassCollectionLoader::main(): Failed opening required '/Users/davidstone/cbsi/gamespot/app/cache/dev/twig_call_method.php' 

This was introduced in https://github.com/twigphp/Twig/commit/bdbfb151115be4eea22e96abd4fd01aa385516aa#diff-8a1ffef1db834d4f5fa55d72a2f43894R14
and happens because the contents of the class file is copied into classes.php  but not the file twig_call_method.php. 

I recommend we remove twig_call_method.php and use only call_user_func_array in the 1.x branch and use $object->$method(...$arguments); in the 2.0 branch since it requires php 5.6.
I would guess the extra function call to twig_call_method() counteracts any performance benefit the new ... language construct provides.

**Comment by stof** [comment]
This looks like a bug in the ClassCollectionLoader instead. It should rewrite the ``__DIR__`` constant to a path relative to the new path.

> I would guess the extra function call to twig_call_method() counteracts any performance benefit the new ... language construct provides.

no it does not. Look at the benchmark given in the PR adding it.

**Comment by stephanvierkant** [comment]
I've got the same problem. After updating, I get this error:

> FatalErrorException in classes.php line 5259:
> Compile Error: Symfony\Component\ClassLoader\ClassCollectionLoader::main(): Failed opening required '/home/stephan/project/var/cache/dev/twig_call_method.php' (include_path='.:/usr/share/php')

**Comment by stof** [comment]
@nicolas-grekas can you have a look at this ?
