### ISSUE TITLE
Symfony bundle inheritance and twig templates overriding

### ISSUE THREAD

**Issue by kroshp** [twigphp/Twig#2258]
I have a third party bundle called VendorDeliveryBundle.

I want to override one of its twig templates that i called with this syntax in one of my App twig templates:  
`{% include '@VendorDelivery/Frontend/Booking/_delivery.html.twig' with { 'form': form } only %}`
Like this it works, the vendor template is called.

But if i want to override this template by registering the overriding bundle in AppKernel (as described in https://symfony.com/doc/2.8/bundles/inheritance.html) and by creating: 
`App/DeliveryBundle/Resources/views/Frontend/Booking/_delivery.html.twig`
this template doesn't override the vendor template.

But if i use this syntax instead
`{% include 'VendorDeliveryBundle:Frontend:Booking/_delivery.html.twig' with { 'form': form } only %}`
the template is overridden.

It seems that the @ syntax doesn't work as expected.

So i'm wondering if it is a bug or a normal behavior considering this symfony documentation https://symfony.com/doc/2.8/bundles/inheritance.html:

> The overriding of resources only works when you refer to resources with the @FOSUserBundle/Resources/config/routing/security.xml method. If you refer to resources without using the @BundleName shortcut, they can't be overridden in this way.

Thanks,

**Comment by stof** [comment]
This has nothing to do with Twig itself. It should be reported to Symfony instead (Twig has no idea what a bundle is)

And IMO, this is an issue in the symfony documentation first. The ``@Foo`` syntax used by Twig has nothing in common with the ``@AppBundle`` syntax used to access routing resources (except the usage of the ``@`` char). The doc should clarified to avoid confusion (which was OK when it was written years ago as the Twig feature was not implemented yet)
