### ISSUE TITLE
Twig_Environment::getParser() removal in 2.x

### ISSUE THREAD

**Issue by robfrawley** [twigphp/Twig#2259]
It looks like [Twig_Environment::getParser()](https://github.com/twigphp/Twig/blob/e55069863dc5408f7323b2789a23de781c0c192e/lib/Twig/Environment.php#L655) was officially removed from the 2.x branch, which is causing a plethora of 3rd party bundles to fail now.

This was an expected removal, due to the deprecation warning that has been present single `v1.25`, but what is the expected alternative moving forward? Is there a new API that replaces this in another interface? Thanks for any info pertaining to this!

**Comment by stof** [comment]
What is your use case for getting the parser directly ? Without use cases, we cannot explain you how to migrate them

**Comment by robfrawley** [comment]
*I* don't have a direct use case, other than my setup breaks horribly when invoking https://github.com/javiereguiluz/EasyAdminBundle without adding that method back. Not sure if directly related yet; will spend some time narrowing down what/where is causing the issue. (I do know at this time that it occurs from within a node visitor).

@stof So, I take it from your response there is no direct 1:1 expectation of where the API moved to?

**Comment by javiereguiluz** [comment]
@stof I'm seeing this deprecation notice on EasyAdminBundle since a few days ago (but only on AppVeyor and not Travis):

![deprecation-getparser](https://cloud.githubusercontent.com/assets/73419/20464644/4e8464b8-af4b-11e6-8636-65a408d9410d.png)

I'm not aware of using the `getParser()` method in any way, but I'll keep looking at it.

**Comment by robfrawley** [comment]
@javiereguiluz If one is requiring Twig 2.0@dev (which only recently *actually* removed this method from the code base), javiereguiluz/EasyAdminBundle breaks entirely ATM. I *have* narrowed it down to that dependency, *or* one of its dependencies. I'll see if I can't narrow it down more explicitly.

**Comment by robfrawley** [comment]
Fixed in Twig Bridge. See javiereguiluz/EasyAdminBundle#1398.
