### ISSUE TITLE
\Twig_Source::getName() and \Twig_Source::getPath() provides unexpected results

### ISSUE THREAD

**Issue by robfrawley** [twigphp/Twig#2260]
Currently, when using Twig with Symfony and using the bundle-syntax-shorthand for template name (for example `AppBundle:foo:barhtml.twig`) the values of `getName()` and `getPath()` provided by `\Twig_Source` seem unexpected (to me).

If using a Symfony-specific template name like `AppBundle:foo:barhtml.twig` the value returned by `\Twig_Source::getName()` is `AppBundle:foo:barhtml.twig` and the value provided by `\Twig_Source::getPath()` is null (or empty). It seems odd for Twig to provide the Symfony-syntax as the value; I would expect it to return the *resolved* name after taking `AppBundle:foo:barhtml.twig` and properly resolving this Symfony-specific value to the real path. Additionally, `getPath()` should absolutely return the real template path, instead of the current behavior of returning an empty string.

Is there a reason/need for the current values/behavior? Additionally, why is `\Twig_TokenStream::getSourceContext()` marked as `@internal`? This can be a very useful method to provide as part of the official API. Any chance of this occurring?

**Comment by stof** [comment]
the behavior of ``getName`` is expected. This method returns the template name, and ``AppBundle:foo:barhtml.twig`` is indeed your template name. Twig template names can be anything as long as you have a loader able to find them. Symfony does not convert its names to a different name. It registers a loader able to use the Symfony convention.

``getPath`` should return the filesystem path, as we are loading from the filesystem (and extending Twig_Loader_Filesystem). Getting an empty string looks weird to me.

**Comment by robfrawley** [comment]
Ok; the behavior of `getName` makes sense. Though, for me, with `symfony 3.1@dev` and `twig 2.0@dev` returns an empty string when called from within a custom twig parser.

**Comment by fabpot** [comment]
@robfrawley Do you have a snippet of code that reproduces the issue?

**Comment by robfrawley** [comment]
@fabpot To give you an overview of the context, I have two templates that contain legal text (TOS, Privacy Statement), and I have a custom token parser so `{% file_m_time %}` turns into the modification time of the template. Here is the [ModifiedExtension](https://github.com/src-run/srw-client-silverpapillon/blob/master/src/AppBundle/Twig/ModifiedExtension.php), which uses the [ModifiedParser](https://github.com/src-run/srw-client-silverpapillon/blob/master/src/AppBundle/Twig/Parser/ModifiedParser.php), which uses the [TemplateLocator](https://github.com/src-run/srw-client-silverpapillon/blob/master/src/AppBundle/Twig/Locator/TemplateLocator.php) which is passed `\Twig_TokenStream`. Now, in `TemplateLocator`, I call `$stream->getSourceContext()->getPath()` on the `\Twig_TokenStream`. See that here: https://github.com/src-run/srw-client-silverpapillon/blob/master/src/AppBundle/Twig/Locator/TemplateLocator.php#L59.

Using Twig <2.0, the path is properly populated. The moment I switch to Twig 2.0@dev, the path is empty. at which point I [created a fallback to derive the path](https://github.com/src-run/srw-client-silverpapillon/blob/master/src/AppBundle/Twig/Locator/TemplateLocator.php#L73) from the name (which is valid in both Twig versions, but uses the Symfony special syntax, so must be parsed to figure the location).

**Comment by robfrawley** [comment]
@fabpot Any chance a fix for this makes it into 2.0 release? Can I do anything to expedite/help with this?

**Comment by fabpot** [comment]
I'm going to close this old issue. Not sure if this is still relevant, but the special Symfony syntax has been deprecated a long time ago anyway.
