### ISSUE TITLE
Documentation seems to not be updated

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#2264]
1) Seven days ago you merged the `id defined` support for `block()` (https://github.com/twigphp/Twig/commit/0d6581bf64b3cf8a3c98d8536aa5ef3aaf5f39a2) which contains updated docs for `doc/functions/block.rst`

2) However, the published docs (http://twig.sensiolabs.org/doc/functions/block.html) don't display that update yet.

Is this a doc build error or is this delay normal? Thanks!

**Comment by stof** [comment]
@javiereguiluz the website is updated only for releases. and the new feature is not released yet

**Comment by stof** [comment]
hmm, actually, 1.28 has been released, so it looks like there is an issue

**Comment by fabpot** [comment]
@stof is right, the docs are only updated when I make a new release. But yesterday, I made the release and run out of power on my laptop, so I was not able to update the website. This is fixed now.
