### ISSUE TITLE
[1.28] Deprecated warning when using macro which is imported in parent template

### ISSUE THREAD

**Issue by gharlan** [twigphp/Twig#2267]
`base.html.twig`:

```twig
{% import "macro.html.twig" as macro %}

{% block content '' %}
```

`child.html.twig`:

```twig
{% extends 'base.html.twig' %}

{% block content %}
    {{ macro.foo() }}
{% endblock %}
```

Warning:

> Deprecated: Using the dot notation on an instance of __CLASS is deprecated since version 1.28 and won't be supported anymore in 2.0.

Is this expected behavior? 
There is no warning, when I import the macro in `child.html.twig` again.

**Comment by stof** [comment]
@gharlan relying on macros imported by the parent is indeed deprecated as well, as it does not work anymore in 2.0. You should import macros in the template using them (btw, the compiled code is more optimized in 1.x when the macro call is known to be a macro call instead of being detected as an object method access)

**Comment by gharlan** [comment]
Ok, thanks for the explanation.

Maybe the deprecation message can be improved for this case. Because I've searched for the new macro notation first (without a dot). But i couldn't find one. ;)
Than I had a deeper look to my templates, and found the difference between macros of parent template and macros imported in current template.

**Comment by trendfischer** [comment]
Perhaps doc/tags/macro.rst should be updated with the information about the parent template import, since it worked before and I found the same case in our codebase too.

**Comment by stof** [comment]
there is no new macro notation. But macros are meant to be imported in the same template, not in a parent.
Accessing macros imported by a parent template was never meant to be possible. It worked only because of the way macros imports are implemented in 1.x.

**Comment by gharlan** [comment]
> there is no new macro notation.

Yeah I know. But first I thought there must be a new notation because of the message "Using the dot notation on an instance of __CLASS is deprecated".

**Comment by stof** [comment]
Well, we might want to improve the deprecation message by trying to guess whether it was a macro call or something else.
The deprecation currently gives a generic message, but users generally don't know that the variable created for a macro import is a ``Twig_Template`` instance (btw, displaying ``__CLASS`` in the message is a bug due to a typo, which is fixed in Twig 1.28.1).
Some other improvements have already be done to the message for the upcoming 1.28.2 release, but we can probably cover more cases too

**Comment by kunsttorsten** [comment]
@stof: Import macros in self context does not work as expected. 

```
{% extends "main.twig" %}
{% use "block/example.twig" %}
{% from "path/to/macro.twig" import macro1, macro2, macro3 %}

{% block content %}
{{ macro1() }}
{{ block("example") }}

{% endblock %}
```

calling macro1() triggers deprecation message

**Comment by kunsttorsten** [comment]
Fixed in my case!
{{ macro1() }} uses another macro from same context macro.twig. Need to import it locally too

{% macro macro1() %}
{% import _self as macros %}
{{ macros.macro2() }}
{% endmacro %}

Deprecation message pointed me to line where macro was called, not to primary problem.

**Comment by roberthenniger** [comment]
Hi. Was having the same problem. Does that mean when i use:
`{% import _self as macro %}`

i can't use the macro in a child template?

**Comment by stof** [comment]
yes it means this. Macros must be imported in the template using them, not in parent

**Comment by kunsttorsten** [comment]
@roberthenniger 
only if you want to use a macro in another macro from same file you need to use import _self as ...
Otherwise you use import or from ... import to use macros in child templates. But remember to import them in all child templates, not in an extended parent template

**Comment by roberthenniger** [comment]
@stof and @kunsttorsten thanks for your fast reply. Even when i am getting confused. The issue we are talking here only comes in effect when i use the macro in a child template. Correct?

What is the best practice to share macros between base and child templates?
How to make code logic sharing between templates?

Thanks in advance for your feedback.

**Comment by stof** [comment]
@roberthenniger you are not forced to use ``{% import _self %}``. you can import from **any** template

**Comment by roberthenniger** [comment]
But i am using macros in my base.html.twig and use them in bade.html.twig.
Sometimes i wanna use the macro (from base.html.twig) in child.html.twig.

How can i do this?

**Comment by stof** [comment]
Import it **also** in the child.html.twig template. This is how macros are used. And you don't have to duplicate the macro, as you can import it from another template than the current one

**Comment by roberthenniger** [comment]
Thanks for the answer and sorry for my stupid question but do i have to give the correct filename of the template or can i reference from _self or _parent?

Will `{% import _self %}` or `{% import _parent %}` work?

**Comment by stof** [comment]
@roberthenniger ``{% import 'base.html.twig' ... %}``, as explained in the doc to reference any template

**Comment by roberthenniger** [comment]
So there is no way to just include the same macros as the parent with `{% import _parent %}`?

**Comment by kunsttorsten** [comment]
little example please?! Maybe we misinterpret your issue

**Comment by stof** [comment]
even if this is possible (I don't remember whether we have the special ``_parent`` variable or no, but I think we do), this would import macros **defined** in the parent template, not macros **imported** in the parent template.

**Comment by roberthenniger** [comment]
Imagine the following scenario:

block.html.twig
`{% import _self as blockmacro %}

{% macro gallery(config) %}

{% endmacro gallery %}

{% block text %}
<h1>{{ Headline }}</h1>
<p>{{ Text }}</p>
{% endblock text %}

{% block block_gallery %}
<div class="my-gallery">

{{ blockmacro.gallery(varCfg) }}
</div>
{% endblock block_gallery%}
`

I guess this scenario will still work in 2.0. Correct?


But in my child.html.twig i do the following:

`{% extends 'path/to/block.html.twig' %}
{% block block_gallery %}

{% endblock block_gallery%}

{% block text %}
<h1>{{ Headline }}</h1>
<div class="my-gallery-between-text">
{{ blockmacro.gallery(varCfg) }}
/div>
<p>{{ Text }}</p>
{% endblock text %}
`

In the 1.27 release this is still possible and very useful. But in 1.28 it throws the exception.
What would be the best practice or workaround for that "problem"?

It would be nice to just add a "macro import" into the child.html.twig like
`{% import _parent as blockmacro %}`
Is that a solution? If not yet, would it be a clever move to get these legacy code working?


Thanks in advance for your input and help. @stof, @kunsttorsten

**Comment by stof** [comment]
As the macro is defined in the parent, yes it would work. But just remember that what you should pass as template name in import is the place where the macro is defined (which is indeed your parent template here too, but could be something else).

Btw, in 1.28, it does not throw an exception, but a deprecation warning. And deprecation warnings are triggered as *silenced* ``E_USER_DEPRECATED`` precisely to avoid being turned into exception by an error handler not knowing our deprecation convention.
The only way to get an exception there would be to use an error handler incompatible with the ``@`` PHP operator (i.e. turning *silenced* errors into exceptions too), which should be considered a bug in the error handler IMO, as it breaks the ``@`` operator itself.

**Comment by roberthenniger** [comment]
Hi @stof thanks for your feedback. With the error handler you are right. We should investigate there.
The first topic is not fully clarified for me. Why do i have to do the import again? I am already telling twig that my template extends another template. In my opinion there should be an easier way then having to repeat the "extend/import". In PHP i also can use a parent class method 8when its not private) and don't have to use a trait or something to reimport it again. I can just use it.

maybe i am getting your answer wrong. Do you mean that my example would still work in 2.0?
Why do i get an deprecated warning then?

**Comment by stof** [comment]
@roberthenniger OK it extends another template. But macros are checked at compile time (partially only in 1.x, and fully in 2.x which is why your example still works in 1.x), and the resolution of the parent is done at runtime (as you can use variables in the name of the parent. This is why macro usages in a template cannot rely on ``{% import %}`` statements done in the parent, as these are not known at compile time.

**Comment by roberthenniger** [comment]
Ok. To make a long story short :-)

In my child.html.twig i have to do the following:

```
{% extends 'path/to/block.html.twig' %}
{% import 'path/to/block.html.twig' as blockmacro %}

```
I that correct?

**Comment by stof** [comment]
this should work, yes.

**Comment by roberthenniger** [comment]
Will test in the next days. Thanks @stof

**Comment by gharlan** [comment]
In current version the deprecation message is much better:
https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L682

So, should we close the issue?

**Comment by stof** [comment]
@gharlan I still have an idea to improve it for a few more cases.

**Comment by marcod85** [comment]
There's still an issue when using the macro within a block of an embedded block:

```
{% extends "layout.html.twig" %}
{% import "macros/buttons.html.twig" as button %}

{% block content %}
...
{% embed "blocks/modal.html.twig" with {'modal_id': 'test-modal' } %}
   ....
   {% block modal_body %}
      {{ button.default('Close', ....) }}
   {% endblock %}
   ...
{% endembed %}
...
{% endblock %}
```
It works if I import the macro again within the block `modal_body`, but IMO it should work without that too.

Or did I miss something?

**Comment by stof** [comment]
hmm, this is because ``{% embed %}`` starts a new internal template, and we may indeed not keep the list of imported macros at this point. This should be considered as a bug though

**Comment by vudaltsov** [comment]
I have a case where I need to call macros dynamically via `attribute()`. But it shows a deprecation notice.

```twig
{# macro.html.twig #}

{% macro one() %}
    {% import 'macro.html.twig' as macro %}
    {{ attribute(macro, 'two') }}
{% endmacro %}

{% macro two() %}
    2
{% endmacro %}
```

**Comment by stof** [comment]
@vudaltsov what is the reason to do it ?

**Comment by vudaltsov** [comment]
@stof, here's the actual example I am working on:

```twig
{# @macro/items.html.twig' #}

{% macro all(items) %}
    {% import '@macro/items.html.twig' as macros %}
    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12">
                    {% for item in items %}
                        {% if attribute(macros, item.type) is defined %}
                            {{ attribute(macros, item.type, [item]) }}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endmacro %}

{% macro text(item) %}
    <section class="item item-text item-bg-white">
        <div class="row">
            <div class="col-xl-8 offset-xl-2">
                {{ item.content|markdown }}
            </div>
        </div>
    </section>
{% endmacro %}

{% macro hook(item) %}
    {% import '@macro/tools.html.twig' as tools %}
    <h2 class="item item-hook item-bg-transparent mb-0" style="{{ tools.bg_img(item.backgroundImage) }}">
        {{ item.content }}
    </h2>
{% endmacro %}

{% macro horiz_side(item) %}
    <section class="item item-horiz-side item-bg-white">
        <div class="row">
            <div class="col-xl-8 offset-xl-2">
                <img src="{{ asset(item.image) }}" class="item-img">
                <div class="item-content">
                    {{ item.content|markdown }}
                </div>
            </div>
        </div>
    </section>
{% endmacro %}
```

I have a collection of various items, each extending an abstract class but representing different content types (`item.type`) with different fields. I want to be able to render each of them individually as well as together dynamically with the help of `all(items)`.

I believe, calling macro via `attribute()` is not something illegal for Twig 2.0, right?

**Comment by stof** [comment]
it is, because macros are not compiled as getters for an attribute anymore (which forces to have a bunch of complex code to prevent security issues, and cannot be compiled as a real macro call).
If you only have a few types, I suggest you to use a ``{% if type='text' %}[% elseif type='hook' %}{% else %}{% endif %}`` and using real macro calls in it instead of dynamic lookup of the macro being used.
Another solution would be to use blocks instead of macros for that:

```twig
{# @macro/items.html.twig' #}

{% macro all(items) %}
    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12">
                    {% for item in items %}
                        {% if block(item.type, _self) is defined %}
                            {% with {item: item} only %}
                                {{ block(item.type, _self) }}
                            {% endwith %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endmacro %}

{% block text %}
    <section class="item item-text item-bg-white">
        <div class="row">
            <div class="col-xl-8 offset-xl-2">
                {{ item.content|markdown }}
            </div>
        </div>
    </section>
{% endblock %}

{% block hook %}
    {% import '@macro/tools.html.twig' as tools %}
    <h2 class="item item-hook item-bg-transparent mb-0" style="{{ tools.bg_img(item.backgroundImage) }}">
        {{ item.content }}
    </h2>
{% endblock %}

{% block horiz_side %}
    <section class="item item-horiz-side item-bg-white">
        <div class="row">
            <div class="col-xl-8 offset-xl-2">
                <img src="{{ asset(item.image) }}" class="item-img">
                <div class="item-content">
                    {{ item.content|markdown }}
                </div>
            </div>
        </div>
    </section>
{% endblock %}
```

Note that my usage of the ``{% with %}`` tag is here to isolate the scope, to reproduce what the macro call was doing. You might not need it

**Comment by vudaltsov** [comment]
@stof, got it. Thank you very much for explanations!

**Comment by stof** [comment]
note that I would probably use blocks in your use case.

**Comment by CriseX** [comment]
If someone is still looking at this, maybe also fix the documentation for include and import to actually match the intended behavior.

https://github.com/twigphp/Twig/issues/2344#issuecomment-271738880

**Comment by viion** [comment]
Is there another way to provide snippets of code that isn't a macro? I have a macro, say "breadcrumbs" on my `base.html.twig` and there are a good amount (I'd say about 70 files in total) that extend `base.html.twig` and now have access to the macros.

Doing macro import on all 70 files is very tedious.. I might as well do the html manually by that point?

**Comment by CriseX** [comment]
@viion I haven't really tested this, but I guess the only alternative might be using a block that is defined in a template that inherits the base template, but is not displayed by it.

So, the inheritance chain would be something like this base.html.twig -> reusable_blocks.twig -> child.html.twig. Then you can use the block(...) function to invoke the blocks from the reusable_blocks.twig template because they are not being displayed by base.html.twig.

Doing macro imports on child templates is nothing but needless line of boilerplate code with the way it works now, however, the method described above is not any better in that regard either really (assuming it works).

**Comment by fabpot** [comment]
I'm going to close this long running issue as the situation has improved a lot with the latest changes. At least, you get error messages when you're doing something wrong (instead of PHP fatal errors) and some features were added to make everything more consistent. As there are a lot here, feel free to open new issues if needed (based on Twig 2.11+).
