### ISSUE TITLE
Can I use extension/inheritance to achieve this?

### ISSUE THREAD

**Issue by peto85** [twigphp/Twig#2275]
I just posted a question in SO, but I thought it's probably worth asking here as well, as it's not just a trivial one. Let's say I have these twig templates:

*base.twig*

```twig
    {# base.twig #}

    <html>
      <head>
        {% include 'head_js.twig' %}
      </head>
      <body>
         {% block content %}{% endblock %}
      </body>
    </html>
```

*head_js.twig*

```twig
    {# head_js.twig #}

    {% block headJS %}
      <script src='/js/some-script.js'></script>
      {% block headJSExtra %}{% endblock %}
    {% endblock %}
```

*page.twig* (the one loaded by the controller)

```twig
    {# page.twig #}

    {% extends base.twig %}

    {% block content %}
      <p>Widget 1</p>
      {% include 'widget.twig' with { name: 'foo' } %}

      <p>Widget 2</p>
      {% include 'widget.twig' with { name: 'bar' } %}
    {% endblock %}
```

*widget.twig*

```twig
    {# widget.twig #}

    {% if wigetAlreadyIncluded is not defined %}
      {% block headJSExtra %}
        {{ parent() }}
        <script src='/js/widget.js'></script>
      {% endblock %}

      {% set widgetAlreadyIncluded = true %}
    {% endif %}
    <p>My name is {{ name }}</p>
```
This code doesn't work (can't use parent() in widget.twig as it's not extending or using any template), but it should illustrate what I'm trying to achieve. The basic idea is:

- In order to work, *widget.twig* requires a js library to be loaded in  as a <script> tag in the <-head> .
- The widget can be rendered several times in one page.
- Other widgets should be able to also add their own <script> tags in the <-head> in this fashion, but they shouldn't override previous added <script> tags (they should be appended).
- I don't want to add more than once any <script> tag required by any widget found in the page.

Any ideas on how can I achieve this would be greatly appreciated. I've read two SO related questions with no luck at all.

- http://stackoverflow.com/a/29132604/4949663
- http://stackoverflow.com/a/18160977/4949663

**Comment by javiereguiluz** [comment]
Since 1.28 you can render a block of an arbitrary template without extending it:

```twig
    {# widget.twig #}

    {% if wigetAlreadyIncluded is not defined %}
      {% block headJSExtra %}
        {{ block('headJSExtra', 'page.twig') }}  <-- magic is here
        <script src='/js/widget.js'></script>
      {% endblock %}

      {% set widgetAlreadyIncluded = true %}
    {% endif %}
    <p>My name is {{ name }}</p>
```

**Comment by peto85** [comment]
Thanks @javiereguiluz,  that hint is actually useful, although I'm not sure it helps in this case.

The thing I can't achieve is to *override* (not just access it's content) the block `headJSExtra`, appending some more content to it.

**Comment by rybakit** [comment]
@peto85 Check this extension: https://github.com/rybakit/twig-extensions-deferred.
Perhaps this is what you are looking for?

**Comment by peto85** [comment]
Hi @rybakit, wow.. this is great. You even have a great example of what I'm trying to achieve in the real project I was working on :)

Thanks for sharing!

**Comment by alexiswbr** [comment]
Is there any chance to see this feature officially added into the twig repo ? @rybakit 
Because this is definitively awesome

**Comment by rybakit** [comment]
@alexiswbr I'm the wrong person to ask :) If you think this feature deserves to be added into the official repository, it's better to file a new ticket.
