### ISSUE TITLE
Weird behaviour with macros

### ISSUE THREAD

**Issue by creatika** [twigphp/Twig#2280]
Hi, we are having an issue where we have this macro
```
{% macro menu_links(menus) %}
{% for menu in menus %}
<li>
    <a href="{{ path(menu.route) }}"><i class="main-icon fa fa-dashboard"></i> {{menu.label|trans}} {% if menu.children|length > 0 %}
    <i class="fa fa-menu-arrow pull-right"></i></a>{% endif %}
    {% if menu.children|length > 0 %}
        <ul>
            {{ _self.menu_links(menu.children) }}
        </ul>
    {% endif %}
</li>
{% endfor %}
{% endmacro %}
```
and we are using it like this
```
<nav id="sideNav">
    {% set menus = generate_menu() %}
    {% import "macros/menu-macros.html.twig" as macros %}
    <ul class="nav nav-list">
        {{ macros.menu_links(menus) }}
    </ul>
</nav>
```
and this is the output
```
<nav id="sideNav">
            <ul class="nav nav-list">
        <li class="el_primary" id="el_0">
    <a href="/admin/portal/"><i class="main-icon fa fa-dashboard"></i> Portales     <i class="fa fa-menu-arrow pull-right"></i></a>    <ul>
        <li>
    <a href="/admin/portal/create"><i class="main-icon fa fa-dashboard"></i> Crear     <ul>
        
    </ul>
</a></li><a href="/admin/portal/create">

    </a></ul><a href="/admin/portal/create">
</a></li><a href="/admin/portal/create">

    </a></ul><a href="/admin/portal/create">
</a></nav>
```
I don't know if we are doing something wrong, or if we are missing something, I've tried replacing the call menu.children with a method that checks if the menu has children 
```
public function parentchildren()
{
    return $this->hasChildren;
}
```
and it does the same, the only thing that is making that extra HTML disappeared is removing the call at all of menu.children except in {{ _self.menu_links(menu.children) }}

The menus variable is an array with Menu class elements, and this is the method
```
public function getChildren(): array
{
    return $this->children;
}
```
```
public function __construct($options = [], $route)
{
    $this->children = [];
}
```

We're using Symfony 3.2 and Twig 1.28.2

I'll be happy to provide more info.

Cheers.

**Comment by stof** [comment]
You output has some class on the li, while the macro does not do such thing. So the output you gave us cannot be generated by the macro you gave

**Comment by creatika** [comment]
@stof Thank you for the quick response! Javascript is adding those classes
```
jQuery('#aside ul.nav > li').each(function() {
	jQuery(this).addClass('el_primary');
	jQuery(this).attr('id', 'el_' + count);
	count++;
});
```

**Comment by stof** [comment]
@creatika please give us the output of Twig, not the processed  DOM

**Comment by creatika** [comment]
Yeah, this is embarrassing, the </a> was inside the if... Sorry for wasting your time @stof and thank you for the help!
