### ISSUE TITLE
[BC break] getTemplateName in favor of getFilename from v1.27.0

### ISSUE THREAD

**Issue by 4rthem** [twigphp/Twig#2281]
Hi,
The following change seems to break cache warmup in TwigBundle:
> * deprecated Twig_Node::getFilename() in favor of Twig_Node::getTemplateName()

During the Symfony warmup phase the template named `foo/bar.html.twig` is generated and cached.
But from a controller, the template name (not the template filename) is used: `:foo:bar.html.twig`.
So the cache file in production is never warmed.

Why didn't you keep the filename as it is the final resolution? The name can go through transformations in TwigBridge or other layers...

Thanks!

**Comment by stof** [comment]
``getFilename`` was never the file name in Twig_Node. It was always the template name, but the name was misleading.
So your issue seems to be something else.

**Comment by 4rthem** [comment]
Got it! It's because of the `rootPath` removed from the `path` in the `Twig_Loader_Filesystem::getCacheKey` method.

https://github.com/twigphp/Twig/compare/v1.26.1...v1.27.0#diff-ab2c33d8c67960ac482a493a70f61126R164

`rootPath` is the cwd so from the console I get the root directory of my project and from CGI the 'web' directory is used.

I don't know if it is the best solution to make `$rootPath` mandatory in the Twig_Loader_Filesystem's constructor. It would avoid `getcwd()` which is not deterministic IMO.

But today the service `twig.loader.native_filesystem` in the Twig bundle is not passing this argument.
Now the cache key is based on that root path, we should have a null value by default, not `getcwd()`. So the cache key obtention would behave as before.

**Comment by stof** [comment]
@4rthem are you using the latest version of Symfony ? It should be passing the project root as root path now

**Comment by stof** [comment]
And ``getcwd`` is the BC default value for people passing relative path to the loader

**Comment by 4rthem** [comment]
I've just tried with Symfony 3.2 and my issue is still here.

Also I tried to add this parameter in a compiler pass but the `FilesystemLoader` class does not forward this argument to its parent (see [constructor](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/TwigBundle/Loader/FilesystemLoader.php#L37)). I'm aware that would be a TwigBundle issue but I don't where the problem could be fixed...

**Comment by stof** [comment]
then it is a bug in the Symfony FilesystemLoader. Please report it there

**Comment by 4rthem** [comment]
Thanks!
