### ISSUE TITLE
Add the possibility to render block in function

### ISSUE THREAD

**Issue by bfolliot** [twigphp/Twig#2283]
Symfony does this with the symfony/twig-bridge package for form integration, but it would be really useful to be able to do it without Symfony.

**Comment by stof** [comment]
Rendering block from other templates, and rendering blocks programmatically have both been implemented in Twig recently:
- https://github.com/twigphp/Twig/pull/2245
- https://github.com/twigphp/Twig/pull/2236

**Comment by bfolliot** [comment]
Thank you for your reply @stof, but i need to have access to the loaded template to call `displayBlock`. How to access it in a function (in an extension) ?

**Comment by stof** [comment]
Well, Twig functions cannot know the name of the current template, unless it is passed as argument (there is a ``_self`` variable in Twig for that).
But making a function meant to call a block of the current template looks weird to me. Why not using ``block()`` for that ?

**Comment by bfolliot** [comment]
My goal is to have a function to "prepare" data and to call one or multiple block for display this data.

Imagine you make a library to manage form. With the twig integration of your library, you can make several blocks (one for the form, one by elements, one for error messages, ...). But your blocks will become very complicated (for example, the form block need to check all elements and call other block). If you have a function to do the complicated routing to blocks and to prepare data for displaying, you can have juste very simple block and it's easy for the users of your package to personalize the output).



(sorry for my english)

**Comment by fabpot** [comment]
I'm not sure I understand what you're looking for. What would you add/change in Twig?
