### ISSUE TITLE
[1.28] Deprecation warning about getTemplateName()

### ISSUE THREAD

**Issue by althaus** [twigphp/Twig#2284]
Hi,

I'm using the template name in the templates to assist Assetic file generation by outputting the name in the dev environement:

```
{% block stylesheets %}
    {% if app.environment != 'prod' %}
        <!-- {{ _self.templateName }} => acme.css -->
    {% endif %}
    {# a stylesheets block with some css generation #}
{% endblock %}
```
After upgrading Twig to 1.28 this throws deprecations which I could track down to the usage of `_self` (http://twig.sensiolabs.org/doc/deprecated.html#globals):

"Calling "getTemplateName" on template "::base.html.twig" from template "::base.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0. (2 times)"

While this throws deprecations and I cannot switch to `{{ _self }}` as it'll be in 2.0, is there no way to get rid off the warning? It makes it hard to have a look on the Symfony ones. :(

Cheers
Matthias

**Comment by fabpot** [comment]
You're right. #2287 should fix this issue by allowing to use `{{ _self }}` in Twig 1.x.

**Comment by althaus** [comment]
Cool. Cheers for the quick fix, Fabien.
