### ISSUE TITLE
Implement custom __get method in Template::getAttribute

### ISSUE THREAD

**Issue by ollycross** [twigphp/Twig#2285]
Currently I have an object which has a magic `__get($key)` method which, when passed a key looks for a method called `find{$key}` within the object, then caches and returns the result of the call if it is found.  

This works fine when called directly form php `$foo_bar = $entity->foo_bar` will look for a method `$enity->findFooBar`.  When called through Twig however the getter is not called as Twig does not look for magic getters in `Template::getAttribute`, only for specific method `{$key}()`, `get{$key}()`, `is{$key}()`, or a magic `__call` method.

I have tested in my code the following, note the addition of the last `elseif` call.  If none of the Twig defined methods above are present then it will look for a `__get` method and call that with the `$item` as a key.  This works for me, with my `__get` method being called and running as it would through pure PHP. 

        if (isset(self::$cache[$class]['methods'][$lcItem])) {
            $method = (string) $item;
        } elseif (isset(self::$cache[$class]['methods']['get'.$lcItem])) {
            $method = 'get'.$item;
        } elseif (isset(self::$cache[$class]['methods']['is'.$lcItem])) {
            $method = 'is'.$item;
        } elseif (isset(self::$cache[$class]['methods']['__call'])) {
            $method = (string) $item;
            $call = true;
        // New condition
        } elseif (isset(self::$cache[$class]['methods']['__get'])) {
            $method = '__get';
            $arguments = [$item];
            $call = true;
        } else {
            ...
        }

Would this be suitable for inclusion into the codebase, or am I missing something with regard to how the getAttribute works?

**Comment by stof** [comment]
have you implement ``__isset``, returning true for property names it knows ?

Twig will not consider magic properties if they are implemented in ``__get`` without being supported in ``__isset`` as well (because Twig first checks whether the property can be used before accessing it)

**Comment by ollycross** [comment]
There is an `__isset` function but it will not return true until after the `__get` function is called as the 'magic' properties are lazy loaded as they are called.

I can simply call `{{entity.get('property')}} from the template if need be, it just looks nicer in my templates and is consistent with my backend code as `{{entity.property}}`.

**Comment by Tobion** [comment]
Why not just move the lazy loading to `__isset` as well and you have what you want?

**Comment by ollycross** [comment]
Good point, I'll have a go at implementing that on Monday, cheers for the
help.

**Comment by fabpot** [comment]
Closing as the current behavior is expected as explained by @stof
