### ISSUE TITLE
[DX] Easier operators adding

### ISSUE THREAD

**Issue by SpacePossum** [twigphp/Twig#2291]
Hi all,

I would like to make changes to allow adding operators to the environment without the use of an extension.
I.e. add the following two methods to the environment:
```php
    public function addUnaryOperator(array $operator)
    {
        if ($this->extensionInitialized) {
            throw new LogicException('Unable to add unary operator as extensions have already been initialized.');
        }

        $this->unaryOperators = array_merge($this->unaryOperators, $operator);
    }

    public function addBinaryOperator(array $operator)
    {
        if ($this->extensionInitialized) {
            throw new LogicException('Unable to add binary operator as extensions have already been initialized.');
        }

        $this->binaryOperators = array_merge($this->binaryOperators, $operator);
    }
```

However I would like to hear first if this is a welcome change (not sure if this is considered a BC break).

For the next _major_ release I would like to suggest to split up the `Twig_ExtensionInterface`,
replacing:
```php
    /** @return array[] */
    public function getOperators();
```
with:
```php
    /** @return array[] */
    public function getBinaryOperators();

    /** @return array[] */
    public function getUnaryOperators();
```

Maybe it is worth it to add an interface for the operators? The current `array` approach works fast and good inside Twig, but from a DX view adding an operator requires a bit of searching through the code to figure out how the `array` describing one operator should be like.

**Comment by JakeFr** [comment]
The functions could have all parameters as arguments too
```php
public function addUnaryOperator($operator, $precedence, $class);

public function addBinaryOperator($operator, $precedence, $class, $associativity);
```

**Comment by SpacePossum** [comment]
alright, thanks for the feedback!
