### ISSUE TITLE
[feature request] Throw an error (or warning) if the name of a token parser or filter is already defined

### ISSUE THREAD

**Issue by skarnl** [twigphp/Twig#2293]
It would be nice if there couple be some warning/error if there are more token parsers or filters with the same name.

We encountered a couple of times that in our library we had some Twig extensions that had some filters or token parsers. But at some point these filters/tokens were added to Twig - which is great! - but they collided with our own implementation... so we were bughunting for a while until we discovered the error was caused by a newer version of Twig.

So having some kind of error/warning (somewhere) if a filter or token with the same name is defined more than once, that would help a lot.

**Comment by fabpot** [comment]
see #2304

**Comment by skarnl** [comment]
Awesome, thanks!
