### ISSUE TITLE
Question: Rendering a block from currently rendered template stack programatically

### ISSUE THREAD

**Issue by emodric** [twigphp/Twig#2296]
I have templates like this:

`base.html.twig`

```
{{ custom_function(my_var) }}

{% block one %}
one
{% endblock %}
```

`template.html.twig`

```
{% extends 'base.html.twig' %}

{% block two %}
two
{% endblock %}
```

`custom_function` is a function that iterates over a complicated structure (`my_var`), where each element of that structure has it's own template, and where template name is selected using some rules defined elsewhere.

When I render `template.html.twig`, what would be the correct way to be able to render a block named `one`, or block named `two` in one of the templates rendered by a `custom_function` call?

Even if I transfer the current template with `_self` to `custom_function`, I would get `base.html.twig` so the best I could do is render the block named `one` by loading the template in Twig environment.

One solution I tried and which is working fine is to replace the function call with a custom tag, which can access current template as well as current context AND the current list of blocks (which now includes both blocks `one` and `two`), which I can then wrap in a wrapper similar to `Twig_TemplateWrapper` and pass it around and use at will. I'm not really sure this is the best way to achieve that, hence the question. Is there a better way? I hope I managed to explain my issue well enough.

Thanks!

**Comment by vudaltsov** [comment]
@emodric, you can render any block from any template with the `block()` [function](http://twig.sensiolabs.org/doc/functions/block.html).
You can pass context to the `block('one', 'base.html.twig')` through the `with` [tag](http://twig.sensiolabs.org/doc/tags/with.html).

**Comment by emodric** [comment]
@vudaltsov That's true, but I can't know the name of the extended template (`template.html.twig`) from `base.html.twig`, where `custom_function` call is located. Notice also that I'm not rendering `base.html.twig`, but `template.html.twig`.

**Comment by fabpot** [comment]
@vudaltsov gave the right answer. Having such a complex logic in the template seems wrong to me in the first place. Most of the processing should probably happen in the PHP code instead. Anyway, that's something very specific to your project and not really a bug or a feature request for Twig.
