### ISSUE TITLE
PHP7 issue: "The "Twig_Extension_Core" extension is not enabled"

### ISSUE THREAD

**Issue by dfu22** [twigphp/Twig#2297]
Hi,

Firstly, thank you so much for your work here.

We've got a problem with the last Symfony update. I've seen a legacy issue (#2200) that is fixed and merged but it isn't working with PHP7: https://travis-ci.org/twigphp/Twig/builds/169968655  

Any help to work with php7?

Thanks!

**Comment by stof** [comment]
The build you linked is not broken on PHP 7. It is just that the PR was merged before the Travis job for this PR had run, and so it could not clone the code. Look at the output of the build when it is red.
If you look at the travis build for the 1.x branch after this merge, it is green on PHP 7 too. Twig is perfectly compatible with PHP 7

**Comment by dfu22** [comment]
Thanks @stof. 
I have been looking for the commit in all commits included in the last versions and I've not found it (may be I didn't search correctly). Any way, we've got the same issue since the last composer update (Symfony 3).

**Comment by fabpot** [comment]
What problem do you have?

**Comment by fabpot** [comment]
Closing as I don't think the issue comes from Twig. If you have more details, feel free to reopen this issue.

**Comment by dfu22** [comment]
We no longer have the issue. Maybe it was generated by other library. Sorry for it and thank you so much.
