### ISSUE TITLE
Warning - realpath() expects parameter 1 to be a valid path, string given 

### ISSUE THREAD

**Issue by matematyk** [twigphp/Twig#2299]
@fabpot 
`Warning: vendor/twig/twig/lib/Twig/Loader/FileSystem.php `
I have problem about function realpath("\0"), I must investigate this problem, but I have no idea why.

I using quickly fix: 
`$rootPath = strval(str_replace("\0", "", $rootPath));`
but for the moment update to new version.

**Comment by stof** [comment]
Well, why are you passign a string containing ``\0`` in an argument expecting a path ?

IMO, gettign a PHP warning when you pass a buggy path is not something we should avoid by altering the input.

**Comment by matematyk** [comment]
@stof 
Yes, In my system analytic  https://github.com/piwik, this warning is showing for my customer.

> Well, why are you passign a string containing \0 in an argument expecting a path ? 
I don't know why \0 is  argument expecting a path, but maybe do you guess?

**Comment by stof** [comment]
Well, ``$rootDir`` is the argument expecting a path. The question is how you end up passing a string containing a NUL byte in this argument

**Comment by fabpot** [comment]
Closing this issue as `$rootDir` must be a path.
