### ISSUE TITLE
Proposal to move escaper to beginning of expression: {{ escaper: variable | filter }}

### ISSUE THREAD

**Issue by 0b10011** [twigphp/Twig#2306]
tl;dr: Escaping is vulnerable to human-error and changes can be made to the syntax to improve readability and auditing.

```twig
<!-- Current -->
<h1 title="{{ title | upper | e('html_attr') }}">{{ title }}</h1>

<!-- Proposed -->
<h1 title="{{ attr: title | upper }}">{{ title }}</h1>
```

I'm willing to do the coding to get this pushed through; I just want to make sure it's a feature that is actually wanted.

# Problems with the current solution

The current solution to escaping (filters) does the job of escaping well, but has some shortcomings in the syntax itself, which doesn't seem to be solvable by any of the available extension points.

## Scanning for incorrect escaping

Currently, escaping is done with the `e` or `escape` filter or autoescaping:

```twig
<h1 title="{{ title | e('html_attr') }}">{{ title }}</h1>
```

Or it's escaped with a different filter:

```twig
<a href="/?q={{ query | url_encode }}">{{ query }}</a>
```

This makes it hard to quickly and accurately scan a document to check for proper escaping in most non-trivial code, especially when mutiple filters are present (you have to scan the beginning and end of an expression, instead of just the beginning):

```twig
<dd itemprop="datePublished" content="{{ published | date('c') | e('html_attr') }}">
	<a href="/search/?q[published]={{ published | date('Y-m-d') | url_encode }}">
		{{ published | date("M j, Y") }}
	</a>
</dd>
```

In this case, it's difficult to see at a glance how, or if, an expression is escaped (arguably the most important part of outputting data).

This can also lead to double escaping and having characters appear in the output that shouldn't. This is more of an eyesore than anything, and will likely require someone looking at the whole expression, regardless of the syntax.

## Unnecessary prefixing for additional escapers

While there have been claims [Twig is not limited to HTML](https://github.com/twigphp/Twig/issues/472#issuecomment-3253184), the [`escape` filter](http://twig.sensiolabs.org/doc/filters/escape.html) is focused on HTML:

> Built-in escapers (`html`, `js`, `css`, `url`, `html_attr`) cannot be overridden mainly they should be considered as the final implementation and also for better performance.

This can turn into an issue when dealing with other languages (svg, xml, json, csv, rtf, etc).

```twig
{% autoescape 'svg_text' %}
<svg id="{{ id | e('svg_attr') }}" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
<a xlink:href="http://example.com/?q={{ query | e('url') }}">
	<text x="10" y="25">{{ link_text }}</text>
</a>
```

Ideally, the `svg_` prefix wouldn't be necessarily. Also, the `url` escaper wouldn't be marked as safe for `svg_text`, so it would be double escaped. The workaround would be to create an `svg_url` filter, but it would be very easy to accidentally use the wrong one, and requires a few extra characters (which turns out to be a lot in a large document).

## Length of boilerplate code

To escape, the bare minimum is `|e('STRATEGY')` (for any non-default escape strategy). Strategies are also commonly prefixed by the language (eg, `html_attr`). On their own, it isn't much, but the length quickly adds up, particularly when multiple expressions appear on the same line.

# Solution

This leaves us with a few problems that can hopefully be addressed:

1. Quickly scanning for incorrect/missing escaping
2. Unnecessary prefixing for additional escapers (and no way to disable html escapers)
3. Length of boilerplate code for escaping
4. Avoiding accidental double escaping (particularly for non-html languages)

Moving escapers to the beginning of the expression would solve 1, namespacing of some sort would solve 2 and help with 4, while both would help 3.

Compare:

```twig
<dd itemprop="datePublished" content="{{ published | date('c') | e('html_attr') }}">
	<a href="/search/?q[published]={{ published | date('Y-m-d') | e('url') }}">
		{{ published | date("M j, Y") }}
	</a>
</dd>
```

to:

```twig
<dd itemprop="datePublished" content="{{ attr: published | date('c') }}">
	<a href="/search/?q[published]={{ url: published | date('Y-m-d') }}">
		{{ published | date("M j, Y") }}
	</a>
</dd>
```

With the above snippets, I find it far easier to recognize at a glance when an expression is escaped for an attribute, url, or html. Any stricter escaping is fine, but it's always guaranteed to be escaped by the escaper named before the first `:`. This also has the added benefit of being less likely to be broken when changing filters, assuming the escaper is in place:

```twig
<h1 title="{{ title | filter_that_also_escapes }}">{{ title }}</h1>
```

A refactor may call for a filter that does something else:

```twig
<h1 title="{{ title | filter_that_doesnt_escape }}">{{ title }}</h1>
```

Now, the `title` is escaped for HTML, instead of an attribute. Ideally, this code would have had `e('html_attr')`, but it currently feels like escapers and filters are equal, so it isn't always made a priority. However, with this new syntax, this would feel more necessary (and take up less space than `e()`):

```twig
<h1 title="{{ attr: title | filter_that_also_escapes }}">{{ title }}</h1>
```

The refactor wouldn't allow unsafe escaping (or it would be immediately noticed that the main escaper was the default, or `html`).

Now let's take a look at the SVG example from above, in the new syntax:

```twig
{% autoescape svg.text %}
<svg id="{{ attr: id }}" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
<a xlink:href="http://example.com/?q={{ url: query }}">
	<text x="10" y="25">{{ link_text }}</text>
</a>
```

Now, all escapers would use `svg` as the namespace, so `url` would point to `svg.url`, forcing an svg-compatible escaper to be created, rather than double-escaping by default.

## Assumptions

- The escaper can't be a variable (hence why `'` are removed). I see it's a possibility with the current syntax, but is there a use-case? Or is it just because it worked with the existing code?
- The format will be one of: `namespace.escaper` or `escaper` (in the current namespace)
- It's okay to have the escaper come first. I thought about putting it immediately following the expression, but this leads to the list of filters at the end being confusing (eg, which order would they execute in). I believe adding namespacing should help with the length so expressions can still be read quickly to figure out the data that's being output.

## Implementing

- +1 *minor* version:
	1. Allow for an escaper first followed by a colon (currently throws a syntax error, so there shouldn't be any legacy issues). Require non-quoted and disallow variables.
	2. Move `html`, `js`, `css`, `url`, and `html_attr` to the `html` namespace
	3. Alias `text` to `html` (ie, `html.text`). Issue deprecation notice when using `html.html`.
	4. Alias `attr` to `html_attr` (ie, `html.attr`). Issue deprecation notice when using `html.html_attr`.
	5. Default to `html.html`
	6. For custom escapers, default to `html` namespace (issue deprecation notice). `attr` is allowed; issue deprecation notice and ignore alias to `html_attr`.
	7. Issue deprecation notice when calling `e()` as a filter (less helpful with new syntax, and I believe I read that it was a "mistake" to add it as an alias)
	8. Issue deprecation notice for using variable strategies (ie, `{% set strategy = some_strategy %}`)
	9. A flag could be added that, if set to true (false by default), would throw exceptions instead of issuing deprecation notices

- +1 **major** version:
	1. Remove `html.text` alias and rename `html.html` to `html.text`
	2. Rename `html.attr` alias and `html.html_attr` to `html.attr`
	3. Default to `html.text`
	4. Require namespace for custom escapers (allow appending to other namespaces?)
	5. Disable `e()`
	6. Disable variable strategies
	7. Enable non-quoted strategies with `{% set strategy %}` (issue deprecation notice for using quotes)

- +2 **major** versions:
	1. Disable quotes in `{% set strategy %}`

It may be ideal to spread this out more, to aid in the transition. Theoretically, quotes and variables could be kept for escaping, but if there's no use case, it'd be best to get rid of the option, I think, since it saves two (possibly unnecessary) characters.

---

I already have a personal branch that takes care of the escaper-first part of this, but want to make sure this is something that the wider community would be interested in before I invest more time in it. And if it is something that is wanted, ensure that the syntax choices I decided upon work for everyone.

**Comment by 0b10011** [comment]
(Partially related to #1417 since this change would likely have to be part of that, or would affect it later.)

**Comment by stof** [comment]
``url`` has no reason to be in a HTML namespace. It is not performing any HTML escaping. It performs escaping of URI components (and if you display the URL in the HTML, you still need to apply HTML escaping after that, which is generally handled by the autoescaping). ``css`` and ``js`` contexts are not related to ``html`` either. So I don't see the reason for namespaces here.

In ``<a href="http://example.com/?q={{ query | e('url') }}">``, the template applies both the ``url`` escaping (explicitly requested) and the ``html`` one (applied by autoescaping as the URL escaping is not safe for an HTML context). And the url filter will not be safe either in your SVG context btw, so applying both escapings is necessary.
Btw, your url_encode example is a bad one, as it does not handle escaping either (escaping is applied by the autoescaping there, not by the ``url_encode`` filter)

And removing the ``escape`` filter would forbid some use cases, where we need to apply some changes after the escaping is performed (to do a replacement on the HTML string).

and the syntax of giving an escaping context at the beginning of the displayed expression is weird to me (and I'm not even sure it would not be ambiguous in some cases)

**Comment by 0b10011** [comment]
> url has no reason to be in a HTML namespace. It is not performing any HTML escaping. It performs escaping of URI components (and if you display the URL in the HTML, you still need to apply HTML escaping after that, which is generally handled by the autoescaping). css and js contexts are not related to html either. So I don't see the reason for namespaces here.

Oh yeah, you're absolutely right. I knew I should have sat on this for the night before submitting. Sorry about that!

On this note, there could be a `url` namespace and a way to escape different parts of the url (path, directory [between `/`], query, query field, query value, fragment, etc).

> In `<a href="http://example.com/?q={{ query | e('url') }}">`, the template applies both the url escaping (explicitly requested) and the html one (applied by autoescaping as the URL escaping is not safe for an HTML context). And the url filter will not be safe either in your SVG context btw, so applying both escapings is necessary.

Ah, okay, so this should be `{{ query | e('url') | e('svg_attr') }}`?

And if it were used in HTML, `{{ query | e('url') | e('html_attr') }}`. The default autoescaping `{{ query | e('url') | e('html') }}` isn't technically what is wanted, since we're inside of an attribute. In the proposed syntax: `{{ attr: query | escape('url') }}`.

> And removing the escape filter would forbid some use cases, where we need to apply some changes after the escaping is performed (to do a replacement on the HTML string).

I don't think I proposed to remove the `escape()` filter (and if I did, it was by mistake). Instead, I just proposed to remove the `e()` shorthand, and that isn't a required step. I had just read in another issue that "adding `e()` was a mistake", or something along those lines, so I figured this would be a good time to deprecate and remove it. But it could be left in; it wouldn't break the new syntax. But even if taken out, `escape()` could still be used as-is. This proposal only suggests where to put the *final* escaper, since that's the one that matters most in terms of security.

> and the syntax of giving an escaping context at the beginning of the displayed expression is weird to me

It feels a bit weird to me as well, but it seems like the only way to provide a definitive "this expression will be escaped by this escaper last". Putting it after the main expression requires manual parsing, and throws off the whole "filters are applied left to right" paradigm that's in place. For example:

```twig
{# As last filter (current) #}
{# Add som_var to another_var and subtract yet_another_var. Apply a_filter and escape as an attr #}
<span title="{{ some_var + another_var - yet_another_var | a_filter | e('attr') }}">

{# After expression #}
{# Add som_var to another_var and subtract yet_another_var. This is an attr. Apply a_filter #}
<span title="{{ some_var + another_var - yet_another_var : attr | a_filter }}">

{# Before expression (proposed) #}
{# For this attr, add som_var to another_var and subtract yet_another_var. Apply a_filter #}
<span title="{{ attr: some_var + another_var - yet_another_var | a_filter }}">
```

Having it at the beginning allows you to know immediately what kind of escaping is expected to be done last (other than the default, if needed).

> (and I'm not even sure it would not be ambiguous in some cases)

In case your doubt regarding the ambiguity is from my explanation, I see it as applying to the entire expression, and wouldn't be present in subexpressions. So the only time you would see it is after `{{` and before any variables, filters, etc. Is there still a possibility for ambiguity?

**Comment by fabpot** [comment]
I'm closing this feature request as it won't happen for several reasons: first, we are very careful when it comes to introduce a new syntax in Twig (everything is done via functions/filters/tests/tags right now), then, we are trying to be similar to other templating engine with the same philosophy as us like Jinja2 in Python for instance.

Thanks you for your proposal.
