### ISSUE TITLE
Twig removes localhost but leaves port, breaking links

### ISSUE THREAD

**Issue by Blaxus** [twigphp/Twig#2307]
So I'm using [LiveReload](http://livereload.com) with [PrePros](https://prepros.io) on port `7879`, and I seem to hit a snag when it comes to removing localhost.

I was just setting up twig, and using a variable called `base` so I could make sure the paths were going to the right folder. And I noticed that `http://localhost` got removed but not the port I'm using (`7879`). See:
![example1](https://puu.sh/sVkjY/5421abe847.png)
![example2](https://puu.sh/sVkja/6d7e37e5d2.png)

This happens both when I set the variable outside of Twig as well as Inside:
```php
<?php
$data['base'] = 'http://localhost:7879/test/';
echo $twig->render('index.html', $data);
```
```php
{% set base = 'http://localhost:7879/test/' %}
```

I'm assuming this is normal behavior. I changed localhost to `127.0.0.1` it seems to work for now, but I'm guessing that this is because Twig removes localhost and makes sure it's using the right folder. However **this doesn't keep ports in mind**, so if I'm using LiveReload it leaves the port and breaks the loading of the css/js files.

**Comment by stof** [comment]
how does your index.html looks like ?

**Comment by Blaxus** [comment]
@stof here's my current base.html:
```php
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <title>{% block title %}Test{% endblock %}</title>
    {% set base = 'http://127.0.0.1:7879/test/' %}
    <base href="{{base}}">
    <link href="public/css/unsemantic-grid-responsive-no-ie7.css" rel="stylesheet">
    {% endblock %}
</head>
<body>
```

**Comment by stof** [comment]
Well, and how does the output of the Twig template look like (before any processing by other tool) ? I don't see anything there which would remove the ``http://localhost`` part, so I suspect that you have a post-processing step doing it (and that this step is the buggy one)

**Comment by Blaxus** [comment]
Ah that might be my router. Lol, I thought it was twig.

**Comment by Blaxus** [comment]
Ah that might be my router. I thought it was twig. My bad
