### ISSUE TITLE
Silent display of undefined block is deprecated

### ISSUE THREAD

**Issue by enumag** [twigphp/Twig#2309]
So I got this error:

```
Silent display of undefined block "help" in template "base.html.twig" is deprecated since version 1.29 and will throw an exception in 2.0
```

The thing is that the block simply may or may not exist. How can I check that without raising this error? The [answer](http://stackoverflow.com/questions/13774384/how-to-check-if-a-block-exists-in-a-twig-template-symfony2) on stackoverflow is outdated - it says to simply render the block which would raise the error.

Also I think the solution should be mentioned in the error message.

**Comment by stof** [comment]
``{% if block('help') is defined`` is available for that in recent Twig versions

**Comment by enumag** [comment]
Thank you. :-)

**Comment by stof** [comment]
@fabpot should we mention the ``block() is defined`` feature in the deprecation message of the silent display of a block to ease the migration path ?

**Comment by fabpot** [comment]
see 97a8c53

**Comment by pierredup** [comment]
The `is defined` doesn't seem to always work as expected.
In my one project, I'm getting the following error:

![screen shot 2017-03-08 at 08 08 38](https://cloud.githubusercontent.com/assets/144858/23692337/805e7430-03d6-11e7-9c77-eb587a6de10a.png)

As you can see, the block rendering is inside a `is defined` check, but it still throws an exception (I tried with `{{ block('scripts') is defined ? block('scripts') }}` as well, but getting the same error).

This only seems to happen in certain cases. So far I've noticed it when using the block `javascripts` and `scripts`, I have several other blocks that works fine. Changing those to only `javascript` or `script` works.

**Comment by fabpot** [comment]
@pierredup Can you provide a script that reproduces the error?

**Comment by pierredup** [comment]
@fabpot I figured that it is because a child template was calling `parent()` when the block didn't exist in the parent template. I created a PR to add a better error message in this case #2415

**Comment by ninze** [comment]
How about performance of this?

    {% if block('help') is defined %}
        {% set help = block('help') %}
    {% endif %}


Wouldn't this render the block twice internally - one for the check and another for the assignment?

**Comment by jvasseur** [comment]
@ninze the syntax `bock(...) is defined` is treated specially by Twig and compiled into an `hasBlock` call allowing your example to do only one render of the block.
