### ISSUE TITLE
Range (n,m) with m > n

### ISSUE THREAD

**Issue by DonCallisto** [twigphp/Twig#2312]
Is this a feature (so it should be documented as it is not) or a bug?

```
{% for i in range(5, 1) %}
  {{ i }}
{% endfor %}

>> 5
>> 4
>> 3
>> 2
>> 1
```

Twig version: 1.29 ([fiddle](https://twigfiddle.com/xi1piw))

**Comment by stof** [comment]
Well, at least, it is an existing behavior since years, and so removing it would be a BC break (and should go through deprecation if we want to remove it).

btw, this is implicitly documented when saying

> The ``range`` function works as the native PHP ``range`` function.

as this is a documented behavior of the PHP function

**Comment by DonCallisto** [comment]
@stof Yes, now that I read carefully I notice your quote but, to me, as documentation reports three example, I would _never_ expected `range` to work that way, because I was focusing on example and not on description (and, maybe, also other users).

Could we improve the docs with this kind of example?

**Comment by stof** [comment]
sure. Just send a PR updating the doc (it is in the ``doc`` folder in this repo)

**Comment by DonCallisto** [comment]
@stof [here it is](https://github.com/twigphp/Twig/compare/1.x...DonCallisto:patch-1)
