### ISSUE TITLE
Embed Block does not seem to work within a Loop

### ISSUE THREAD

**Issue by Jones-S** [twigphp/Twig#2325]
Hi there,
Embed blocks within a loop seem not to work properly.

I tried this:
```
{% for section in project.mediaSections %}
	{% embed "modules/section/section.twig" with { modifiers: section.modifiers } %}
		{% block sectioncontent %}
			not working :'(
		{% endblock %}
	{% endembed %}
{% endfor %}
```

I don't know why. The looping is okay and the embed itself works as well, just the content within the block is not shown. Probably a bug?...
Any ideas how to resolve this problem?

cheers
J

**Comment by stof** [comment]
Please also show the ``modules/section/section.twig`` template, otherwise helping you is impossible

**Comment by Jones-S** [comment]
Ah sure, I forgot...
```
<div class="mod_section{% if modifiers is defined %}{% for modifier in modifiers %} mod_section--{{ modifier }}{% endfor %}{% endif %}">
	<div class="mod_section__content">
		{% block sectioncontent %}
		{% endblock %}
	</div>
</div>
```

**Comment by Jones-S** [comment]
Hi.
Any idea how to solve this problem? Any suspicion where the bug can be found?

**Comment by d-simon** [comment]
Any update on this? 🙏

**Comment by stof** [comment]
could you build a reproducing case on https://twigfiddle.com/ ? It may help debugging this

**Comment by Jones-S** [comment]
Sorry @stof 
We got immensely confused. First we are not developing with the newest twig, which we need to update, and second the error could be lying within our [twig.js](https://github.com/twigjs/twig.js) implementation... Sorry for bothering you. With twig alone it works: https://twigfiddle.com/khq1wo/2

**Comment by stof** [comment]
Well, if you use twig.js, please don't report issues here. twig.js is a totally separate project, which is unrelated to the Twig one (well, they port the template syntax, but they implement it on their own and they are a separate team)

**Comment by Jones-S** [comment]
I know. We use both. The php twig and twig.js. But we don't know where the mistake originates. But we know for sure that it is not your php twig...
