### ISSUE TITLE
Performance Query - getAttribute()

### ISSUE THREAD

**Issue by mantis** [twigphp/Twig#2326]
Hi All,

I think I've noticed a possible performance optimization - the template i'm currently including makes 4212 calls to getAttribute(). (if I'm reading the profiler output right - 5.5% of total time)

and 1.2% of the page time was being used by the call to hasExtension() - which was being call 1934 times.

As i'm sure there's people more familiar with twig then myself ;) - is there a minor optimization here to add a:
` 
static $s_sandbox = null;
if ( $s_sandbox === null ) {
$s_sandbox = $this->env->hasExtension( 'Twig_Extension_Sandbox' );
}
`

above the // object property block in template.php.

Then have the 2 checks for the sandbox extension check if s_sandbox is true?

As the hasExtension code does a ltrim, on the string then checks for the class name exists, there would appear to be a optimization here. On the test page i've noticed this on, the size of the xdebug callgrind file froms from 7.164MB to 6.933MB - which seems a reasonable size.

If my logic here is sound, I can generate a pull request - i'd also appreciate suggestions for naming a static variable.

**Comment by fabpot** [comment]
Sounds reasonable.

**Comment by mantis** [comment]
I don't think this is going to be as simple as my initial first thought - which was to do: https://gist.github.com/mantis/ebe832f13df40581591ee13056351b31 (or even keep the sandbox object) - however that causes the phpunit tests to fail.  Presumably some of the unit tests make use of multiple environments?

**Comment by mantis** [comment]
@fabpot any thoughts on this - should I abandon as environment can change, or have you got an idea of how to handle that case sensible?

**Comment by fabpot** [comment]
You could store the value by env (by using `spl_object_hash` as a key for the cached array)

**Comment by fabpot** [comment]
fixed in #2635
