### ISSUE TITLE
Twig_Error_Runtime: The "core" extension is not enabled.

### ISSUE THREAD

**Issue by aimeos** [twigphp/Twig#2333]
Got this error during unit tests when using the 2.0.0 release in combination with Symfony 3.0.9.

Installed packages are:
  - Installing composer/installers (v1.2.0) Downloading: 100%
  - Installing psr/http-message (1.0.1) Downloading: 100%
  - Installing doctrine/lexer (v1.0.1) Downloading: 100%
  - Installing doctrine/inflector (v1.1.0) Downloading: 100%
  - Installing doctrine/collections (v1.3.0) Downloading: 100%
  - Installing doctrine/cache (v1.6.1) Downloading: 100%
  - Installing doctrine/annotations (v1.3.1) Downloading: 100%
  - Installing doctrine/common (v2.6.2) Downloading: 100%
  - Installing doctrine/dbal (v2.5.5) Downloading: 100%
  - Installing aimeos/aimeos-core (dev-master d5813f1) Cloning d5813f12b7
  - Installing aimeos/ai-gettext (dev-master dd75d68) Cloning dd75d68126
  - Installing psr/log (1.0.0) Downloading: 100%
  - Installing monolog/monolog (1.22.0) Downloading: 100%
  - Installing aimeos/ai-monolog (dev-master 61c1169) Cloning 61c1169435
  - Installing zendframework/zend-diactoros (1.3.7) Downloading: 100%
  - Installing symfony/polyfill-mbstring (v1.3.0) Downloading: 100%
  - Installing twig/twig (v2.0.0) Downloading: 100%
  - Installing symfony/polyfill-util (v1.3.0) Downloading: 100%
  - Installing paragonie/random_compat (v2.0.4) Downloading: 100%
  - Installing symfony/polyfill-php70 (v1.3.0) Downloading: 100%
  - Installing symfony/polyfill-php56 (v1.3.0) Downloading: 100%
  - Installing symfony/symfony (v3.0.9) Downloading: 100%
  - Installing symfony/polyfill-intl-icu (v1.3.0) Downloading: 100%
  - Installing aimeos/ai-symfony (dev-master 472f622) Cloning 472f6224e1
  - Installing swiftmailer/swiftmailer (v5.4.5) Downloading: 100%
  - Installing aimeos/ai-swiftmailer (dev-master 7d4d446) Cloning 7d4d44660c
  - Installing aimeos/ai-admin-extadm (dev-master e404234) Cloning e404234561
  - Installing aimeos/ai-admin-jqadm (dev-master e4b313e) Cloning e4b313e5e6
  - Installing aimeos/ai-admin-jsonadm (dev-master c7f9405) Cloning c7f9405305
  - Installing aimeos/ai-controller-jobs (dev-master 2ada665) Cloning 2ada66554b
  - Installing aimeos/ai-controller-frontend (dev-master b46c0d2) Cloning b46c0d20b2
  - Installing aimeos/ai-client-html (dev-master 0ea97f8) Cloning 0ea97f84a3
  - Installing aimeos/ai-fosuser (dev-master 325ebcc) Cloning 325ebccde0
  - Installing friendsofsymfony/user-bundle (v2.0.0-beta1) Downloading: 100%
  - Installing symfony/swiftmailer-bundle (v2.4.2) Downloading: 100%
  - Installing symfony/monolog-bundle (v3.0.2) Downloading: 100%
  - Installing sensio/framework-extra-bundle (v3.0.18) Downloading: 100%
  - Installing symfony/psr-http-message-bridge (v1.0.0) Downloading: 100%
  - Installing guzzle/guzzle (v3.8.1) Downloading: 100%
  - Installing satooshi/php-coveralls (dev-master 1b64b6e) Cloning 1b64b6e202
  - Installing doctrine/doctrine-cache-bundle (1.3.0) Downloading: 100%
  - Installing jdorn/sql-formatter (v1.2.17) Downloading: 100%
  - Installing doctrine/doctrine-bundle (1.6.4) Downloading: 100%
  - Installing doctrine/instantiator (1.0.5) Downloading: 100%
  - Installing doctrine/orm (v2.5.6) Downloading: 100%

**Comment by stof** [comment]
Symfony 3.0.9 does not fully support Twig 2, because additional breaking changes were made to Twig 2.x after the end of maintenance of Symfony 3.0.x. You should upgrade Symfony to a maintained version (or downgrade Twig in the meantime)

**Comment by Wardevour** [comment]
I am getting the same error but my project does not require Symfony. Why might I be getting this error?

I also had to remove "Twig_Autoloader::register();"

**Comment by arimolzer** [comment]
@stof I like the idea of updating to get past the error, but I'm getting the error when doing a `composer update`, not when doing a unit test. 

Anyone else had this issue?

**Comment by SpacePossum** [comment]
Did you clear the Twig cache? Please provide the Twig version you experience this issue on :)

**Comment by fabpot** [comment]
Closing as it looks like a migration issue to Twig 2.
