### ISSUE TITLE
[feature request] Twig_NodeCaptureInterface

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#2340]
There is currently no non-hacky way to have a custom Twig tag which captures its sub-nodes’ output (like `set...endset`) without Twig throwing an error if the tag pair is ever used in an inherited template outside of `block...endblock` tags.

*Example: In Craft CMS we have `css` and `js` tags which can be used as tag pairs just like `set`, which capture the output and register them to be output elsewhere in the template, combined with other registered CSS and JS code.*

Twig already has a `Twig_NodeOutputInterface` interface, for node classes that are meant to *output* something, which `Twig_Parser::filterBodyNodes()` checks for when making sure no tags are outputting anything outside of `block` tags in inherited templates.

What I propose:

- There should be an opposite `Twig_NodeCaptureInterface` interface, which tells Twig that the tag is going to *capture* the output of any of its sub-nodes, so there’s no need for `filterBodyNodes()` to loop through them. The interface should be completely empty, just like `Twig_NodeOutputInterface`.

- `Twig_Node_Set` should implement this interface.

- These lines in `filterBodyNodes()`:

  ```php
  // bypass "set" nodes as they "capture" the output
  if ($node instanceof Twig_Node_Set) {
  ```

  should be replaced with:

  ```php
  // bypass nodes that "capture" the output
  if ($node instanceof Twig_NodeCaptureInterface) {
  ```

To workaround this in Twig 1, we provided our own custom parser class, which extended `Twig_Parser` and overrode its `filterBodyNodes()` method:

```php
protected function filterBodyNodes(Twig_NodeInterface $node)
{
    // Bypass CSS/JS registration nodes as they "capture" the output
    if ($node instanceof RegisterResourceNode) {
        return $node;
    }

    return parent::filterBodyNodes($node);
}
```

However in Twig 2 `filterBodyNodes()` is now a private function, so not something we can override like that. Instead we have had to adjust our `RegisterResourceNode` class so that it actually extends `Twig_Node_Set`, just so it will pass that `$node instanceof Twig_Node_Set` condition.

```php
class RegisterResourceNode extends Twig_Node_Set
{
    public function __construct(array $nodes = [], array $attributes = [], $lineno = 0, $tag = null)
    {
        // Bypass Twig_Node_Set::__construct()
        Twig_Node::__construct($nodes, $attributes, $lineno, $tag);
    }

    // ...
}
```

Obviously this is super hacky and a bad idea. We'd much rather be able to change that to:

```php
class RegisterResourceNode extends Twig_Node implements Twig_NodeCaptureInterface
{
    // ...
}
```

**Comment by stof** [comment]
Duplicate of #2045

**Comment by brandonkelly** [comment]
Doh, thanks @stof.
