### ISSUE TITLE
Lots of broken links on the twig website

### ISSUE THREAD

**Issue by PunchyRascal** [twigphp/Twig#2342]
For example page about `if`: http://twig.sensiolabs.org/doc/2.x/templates.html/tags/if.html

They all report 404

**Comment by fabpot** [comment]
That URL is clearly wrong. Where did you get that?

**Comment by dubaaron** [comment]
I'm seeing this too ... I'm thinking it has something to do with the bump to 2.x, and there being separate doc paths for both 1 and 2 ... can't remember where I clicked them from, though, sorry ... If I come across another will let you know.

**Comment by PunchyRascal** [comment]
I googled `twig for template designers` and got to this page:
http://twig.sensiolabs.org/doc/templates.html/
where there was a link to
http://twig.sensiolabs.org/doc/2.x/templates.html/tags/if.html

**Comment by fabpot** [comment]
Should be fixed now
