### ISSUE TITLE
Twig 2.0 is calling a protected variable rather than a method

### ISSUE THREAD

**Issue by rhukster** [twigphp/Twig#2343]
I have an object that i'm assigning to a twig variable called `assets`.  In that Object i have a protected variable called `$css`, and a method called `css()`.

With Twig 1.X I have been outputting the result of the method via:

```
{{ assets.css() }}
```

This has worked great, but when I update to Twig 2.0, I get an error:

```
Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Array to string conversion").
```

When I dump `{{ assets.css() }}` I do in fact get an array, but it's the protected variable $css.

I changed the method of the function to `render_css` and then called it via:

```
{{ assets.render_css() }}
```

and that does work, but that is not an acceptable solution.  Twig should definitely not be using a protected variable ahead of a public method of the same name.  Also I tried changing the access to `private` on the `$css` variable but it had no effect.

Incidentally I have a similarly named protected variable called `$js` with a corresponding function `js()` and a similar call to:

```
{{ assets.js() }}
```

And that works 100% fine, so not sure what's going on here.

**Comment by fabpot** [comment]
Can you provide a script that reproduces the issue?

**Comment by rhukster** [comment]
Probably the simplest way to recreate this issue is to try with the actual project.  So in your webroot:

```
$ git clone https://github.com/getgrav/grav.git grav-twig2
$ cd grav-twig2
$ git checkout feature/twig_2.0_readiness
$ composer install --no-dev
$ bin/grav install
```

Then point your browser at `/grav-twig2`

I've already made some fixes in this branch, but this one issue I just can't seem to understand.  You will see the error is coming from the `{{ assets.css() }}` call.  You can then follow my first comment and see how the renaming of the method works, etc.

The `Assets` class in question is in `system/src/Grav/Common/Assets.php`

Also after going back to Twig 1.30 thinks start working again.

Thanks Fabien!

**Comment by xabbuh** [comment]
@rhukster Twig does not access the `protected` `$css` property, but calls the `getCss()` method instead. The changes in #2316 led to a change in the way Twig looked for methods to call. I opened #2356 which suggests a way to fix your issue.

**Comment by rhukster** [comment]
Thanks @xabbuh, i'll test this out with the latest 2.x branch.
