### ISSUE TITLE
Please support simpler HTML templates

### ISSUE THREAD

**Issue by dsaet56yhdfsefret** [twigphp/Twig#2349]
I really love Twig, and I use it for all my projects. But there is one big feature that I really think it's missing, and that Twig doesn't seem to be addressing. That is, supporting a simple, clean, and uncluttered HTML pre-processor. There are other template engines such as [Slim](http://slim-lang.com) that support a much cleaner HTML syntax, which **really helps a lot** to reduce HTML verbosity. Twig instead only allows to inject {%%} {{}} sections inside raw HTML. This really sucks, because HTML verbosity sucks, and templates end up messed up.
Could you guys **please, please, please** add support for this feature?? Pleaseeee

[related issue](https://github.com/symfony/symfony/issues/21227)

**Comment by stof** [comment]
Twig does not care about HTML **at all**. It can be used to output whatever you want. The output of Twig can then be processed using Jade for instance if you want.

**Comment by javiereguiluz** [comment]
@dsaet56yhdfsefret you can already do that. I use Twig to generate lots of different contents besides HTML. Everything works as expected.

**Comment by fabpot** [comment]
That would a totally different project then. So closing this request.

**Comment by dsaet56yhdfsefret** [comment]
@javiereguiluz what's the workflow to integrate Twig with Jade or any other HTML pre-processor? Do you write Twig {% blocks %} inside Jade files?
