### ISSUE TITLE
json_decode

### ISSUE THREAD

**Issue by dsaet56yhdfsefret** [twigphp/Twig#2352]
Why does Twig ship with a [json_encode](http://twig.sensiolabs.org/doc/2.x/filters/json_encode.html) filter by default, but not a **json_decode**?

**Comment by stof** [comment]
why would you be *decoding* JSON in the template ?

Encoding makes sense, as it is common to use JSON as an output format for some data (for instance putting some data in a HTML attribute by putting it as JSON)

**Comment by dsaet56yhdfsefret** [comment]
> why would you be decoding JSON in the template ?

For the same reason that "encoding makes sense, as it is common to use JSON". If for example I have some JSON objects serialized in my database, I can just use a filter **|json_decode()** on a particular object from Twig. Doing it from PHP would require me to loop through the records twice: first in PHP just for this operation, and then another time in Twig when I print out my items.
And please don't ask "why would you store JSON in the database", because this "I don't care, so it doesn't make sense" attitude gets tiresome after hearing it repeatedly. Also, yeah I know I can implement a new filter myself, but given that Twig already has a json_encode() filter, I think it would make sense to also have a default json_decode().

**Comment by stof** [comment]
@dsaet56yhdfsefret if your own project needs a json_decode, you can add it very easily:

```php
$twigEnvironment->addFilter(new Twig_SimpleFilter('json_decode', 'json_decode'));
```

If you use Symfony (or another framework not giving you direct access to the instantiation of the Twig_Environment), you could use an extension to provide the filter (which is not really harder).

I don't think adding this filter in core makes sense (once it is in, we cannot remove it anymore due to BC)

**Comment by fabpot** [comment]
This has been discussed before and such a feature does not belong to the core. And as adding it in a project is very easy, I'm closing this feature request.
