### ISSUE TITLE
Where is the Autoloader in Twig 2.x

### ISSUE THREAD

**Issue by WinXaito** [twigphp/Twig#2355]
Hello,

I can not find the Twig autoloader, as shown in the documentation here: http://twig.sensiolabs.org/doc/2.x/intro.html

Would you be able to tell me?
Thank you

[Texte original]
>*Bonjour,
Je n'arrive pas trouver l'autoloader de Twig, comme indiqué dans la documentation ici: http://twig.sensiolabs.org/doc/2.x/intro.html
Sauriez-vous me renseigner ?
Merci*

**Comment by stof** [comment]
There is no such autoloader in Twig 2. Use the autoloader provided by Composer (or a separate autoloading library if you don't use composer)

**Comment by WinXaito** [comment]
Okay, I have just download the source, because I don't use the Composer.
Which library I can use for autoloading ?

**Comment by stof** [comment]
See https://packagist.org/search/?q=autoload and https://packagist.org/search/?q=class%20loader for packages providing such features (maybe not all of them though, as the search might find packages providing other features).

**Comment by labby** [comment]
> Edit: It is still annoying to no longer have the autoloader integrated, why to have it removed?

I would also like to hear the answer...

**Comment by stof** [comment]
@labby because the recommended installation way is through composer, which already provides an autoloader (with better performance than the one shipped in Twig 1.x when enabling optimizations) and therz are already tons of libraries giving you an autoloader when you don't use composer for that.
Thus it's not Twig's job to provide an autoloader. It provides a templating engine.

**Comment by labby** [comment]
Thank you for that statement :-)

**Comment by fabpot** [comment]
@labby Nowadays, most people are using Composer, so the built-in autoloader was a redundancy. And if you are not using Composer, there are quite a few options available. We also decided to remove the autoloader as almost all projects are using more than just Twig and so, they need an autoloader for those other parts. Having more than one autoloader is not needed, so we decided to remove ours as this is not really part of the scope of Twig. Hope you understand.

**Comment by labby** [comment]
> Hope you understand

yes.
maybe I am not understanding composer... but some kind of "automatic update and autoload" may lead to problems.

**Comment by robfrawley** [comment]
@labby [Composer](https://getcomposer.org/) is the most-used dependency manager for PHP projects. You define a [composer.json](https://getcomposer.org/doc/01-basic-usage.md#composer-json-project-setup) per-project, which lists the "requirements" (or dependencies) and their respective versions (such as `twig/twig:~2.0`), among other settings describing the properties of your project. It then handles updating your dependencies (and the dependencies of those dependencies) *when you ask it to* (it isn't "automatic"), as well as building the autoloader files required to load them.

Once you use Composer, you'll never want to go back to downloading your own dependencies again. Give [this tutorial a look](https://www.codementor.io/php/tutorial/composer-install-php-dependency-manager).

**Comment by kiatweitan** [comment]
The installation chapter in documentation could do better to inform people who would want to install from tarball release.

**Comment by xabbuh** [comment]
@kiatweitan I'd say if you nowadays want to install libraries in another way than using Composer, you are pretty much on your own. I do not know of many modern packages in the wild that will give you such instructions.

**Comment by kiatweitan** [comment]
Agreed. In that case why don't remove the install by tarball section in the documentation, else it would be misleading for those uninitiated?

**Comment by fabpot** [comment]
@kiatweitan You're right. Fixed in #2672
