### ISSUE TITLE
How to get the php compiled code from a template?

### ISSUE THREAD

**Issue by oscarotero** [twigphp/Twig#2357]
Hello.
I need the raw php code of the templates to search for gettext functions. For the 1.x version I had this code:
https://github.com/oscarotero/Gettext/blob/master/src/Extractors/Twig.php#L28

But `Twig_Loader_String` has been removed in 2.x, so I'd like to know what is the best way to get the php code of a template from a twig template string.

Thank you

**Comment by stof** [comment]
There is nothing requiring the usage of the Twig_Loader_String in you code, as you never rely on the loader (you call ``compileSource`` directly)

**Comment by oscarotero** [comment]
Thanks for your quick answer, @stof 
I'm using `Twig_Loader_Array` as the loader to create a new instance of `Twig_Environment` but the `compileSource` need an instance of `Twig_Source` and passing the string directly throws and exception. :/

**Comment by stof** [comment]
@oscarotero just instantiate a Twig_Source object then. The source code is the second argument of the constructor

**Comment by stof** [comment]
btw, this will also work in recent versions of Twig 1.x (as we introduced Twig_Source in 1.x first)

**Comment by oscarotero** [comment]
Now seems to work fine. https://github.com/oscarotero/Gettext/blob/06bc9f41ab9311249671980de84c4696f23b3507/src/Extractors/Twig.php
Thank you!
