### ISSUE TITLE
Support ===

### ISSUE THREAD

**Issue by dawehner** [twigphp/Twig#2358]
I just wrote some twig template which contained ```===``` and the parser failed:

```
Twig_Error_Syntax: Unexpected token "operator" of value "=" in "foo.html.twig" at line 19. in Twig_ExpressionParser->parsePrimaryExpression() (line 208 of vendor/twig/twig/lib/Twig/ExpressionParser.php).
```

I wonder whether twig should simply treat ```===``` as ```==``` or even provide some form of strict comparison.

**Comment by fabpot** [comment]
`===` does exist in Twig, but the name of the test is `same as`.

**Comment by dawehner** [comment]
Right, I'm simply wondering whether === should be treated as "same as" automatically. I'm wondering whether its just me who is so stupid falling into that trap :)

**Comment by dawehner** [comment]
This is really not like a feature request or so, I'm really just wondering

**Comment by fabpot** [comment]
That's a good question and one for which we had a discussion in the past. The conclusion was that `===` is confusing for anyone not familiar with PHP. So, we decided to support it via `same as` instead.

**Comment by dawehner** [comment]
One thing which could be done is to not support "===" but instead throw a helpful exception telling people about "same as"

**Comment by fabpot** [comment]
That makes sense. Anyone willing to submit a PR for that? Could be done in the 1.x branch.

**Comment by dawehner** [comment]
Absolutely

**Comment by dawehner** [comment]
:+1: for closing PRs.

**Comment by fabpot** [comment]
@dawehner It's not closed but merged ;)

**Comment by dawehner** [comment]
Oh haha. Well even better :)

**Comment by fabpot** [comment]
See #4736
