### ISSUE TITLE
embed with not working

### ISSUE THREAD

**Issue by QuentinCurtet** [twigphp/Twig#2362]
Hi,

I'm working with symfony 3.2.2 and i have a problem in my twig template : 
```
<div class="content-wrapper">
        {% embed  '@theme/partial/contentHeader.html.twig'
        with {
        'basePageTitle': block('basePageTitle'),
        'basePageSummary': block('basePageSummary'),
        }
        %}
        {% endembed %}
        <section class="content">
            {% block layout %}{% endblock %}
        </section>
        <!-- /.content -->
    </div>
```
With this code in my base.html.twig, i have the following error : "Block "basePageTitle" on template "@theme/base.html.twig" does not exist."
I have the blocks defined in my contentHeader.html.twig.

Thanks for your help.

**Comment by stof** [comment]
The object you pass to ``with`` is evaluated in the main template, not in the embedded one, as it defines the context sent to the embedded template (it is exactly the same than ``{% include ... with {} %}``

**Comment by quentincurtet** [comment]
In each page, we fill the blocks in parameter : 
For the partial template 
```
<!-- Content Header (Page header) -->
{% include '@theme/partial/contentPageMessage.html.twig' %}
<div style="position: relative">
    <section class="content-header">
        <h1>
            {{ basePageTitle|default('Add the title of the page') }}
        </h1>
        <section> {{ basePageSummary }}</section>
    </section>
</div>
```
The base.html.twig
```
<div class="wrapper">
    {% include '@theme/partial/header.html.twig' %}
    {% include '@theme/partial/sidebarMain.html.twig' %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% embed  '@theme/partial/contentHeader.html.twig'
        with {
        'basePageTitle': block('basePageTitle'),
        'basePageSummary': block('basePageSummary'),
        }
        %}
        {% endembed %}
        <section class="content">
            {% block layout %}{% endblock %}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    {% include '@theme/partial/footer.html.twig' %}
</div>
```
For each page 
```
{% extends 'AdminBundle::layout.html.twig' %}
{% block title %}{% trans %}admin.setting.list_title{% endtrans %}{% endblock %}
{% block basePageTitle %}{% trans %}admin.setting.list_title{% endtrans %} {% endblock %}

{% block body %}
...
{% endblock %}
```
The param basePageSummary is optionnal

**Comment by stof** [comment]
Well, your parameter is optional, but you always render a block in it. So the block is *not* optional.

Twig 1.x was returning an empty string when rendering a non-existent block, but this was deprecated. So if you updated to Twig 2 without fixing the deprecation, it breaks.

**Comment by quentincurtet** [comment]
The thing that i don't understand, it that works with symfony 3.2.1

**Comment by stof** [comment]
it probably has nothing to do with Symfony 3.2.1. I suspect that your ``composer update`` updated Twig to 2.0.0 at the same time (because Twig 2 has been released), and your project was not ready for it yet.

**Comment by quentincurtet** [comment]
But i have Twig 1.31.0 when i run a composer update.
