### ISSUE TITLE
Documentation edit links are broken [Website]

### ISSUE THREAD

**Issue by davidgorges** [twigphp/Twig#2365]
The links to edit the documentation files are currently broken:

> **Questions & Feedback**
Found a typo or an error?
Want to improve this document? [Edit it.](https://github.com/twigphp/Twig/edit/master/internals.rst)

I think it's just the "doc" directory in the url missing, so
``https://github.com/twigphp/Twig/edit/master/internals.rst``
should become
``https://github.com/twigphp/Twig/edit/master/doc/internals.rst``

**Comment by fabpot** [comment]
fixed, thanks for the report
