### ISSUE TITLE
Fatal Error in Core.php since Version 2.1.1

### ISSUE THREAD

**Issue by Spikeworld** [twigphp/Twig#2367]
With Twig Version 2.1.1 my Server responds with the error posted below.
In my local environment everything works well its only on my live server.
When I overwrite Twig with 2.0.0 everything works fine again on my server.
Using Symfony 3.2.2 framework.
I´m completely lost...

[Wed Jan 18 13:50:58 2017] [-:error] [pid 21924] [client X.XXX.XX.XX] [host myhost.com] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/Extension/Core.php on line 139 and defined' in /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/Filter.php:35\nStack trace:\n#0 /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/Extension/Core.php(139): Twig_Filter-]__construct('date', 'twig_date_forma...', Array)\n#1 /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/ExtensionSet.php(429): Twig_Extension_Core-]getFilters()\n#2 /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/ExtensionSet.php(419): Twig_ExtensionSet-]initExtension(Object(Twig_Extension_Core))\n#3 /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/ExtensionSet.php(388): Twig_ExtensionSet-]initExtensions()\n#4 /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/En in /is/htdocs/wpxxxxx_BY6NBYG6KD/www/vendor/twig/twig/lib/Twig/Environment.php on line 548

**Comment by stof** [comment]
Twig 2.0 does not support PHP 5.x. If you deploy on PHP 5, tell composer about it when running ``composer update`` (through the [dedicated config setting](https://getcomposer.org/doc/06-config.md#platform)) so that it resolves dependencies compatible with PHP 5.x. By default, composer will resolve dependencies for the PHP version used to run composer.
so if you run PHP 7 locally, composer will think it is OK to use a Twig version requiring PHP 7, while your prod cannot run it.

**Comment by Spikeworld** [comment]
Thank you so much!
I set my PHP Version to 7 a long time ago, but when I just looked it was set back to 5.6.
The reason was that I made a new Vhost and now I saw a info sign on my providers backend saying something like this: "new Vhosts are being automatically set to php-Version 5.6".
Cost me half a day searching for errors and finally giving up and posting here...
Could I possibly figure it out by myself or is it just you knowing Twig inside out? How did you know?
Again thank you sooo much!

**Comment by stof** [comment]
@Spikeworld ``Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given`` is typically what PHP 5.x would throw as error when seeing a ``string`` scalar typehint and receiving a string (as it does not support scalar typehints, it thinks it is a class typehint for a ``string`` class and so expects an instance of this class).

**Comment by Spikeworld** [comment]
@stof Thanks again for the explanation.
