### ISSUE TITLE
Twig not working with php.ini config mbstring.overload = 3

### ISSUE THREAD

**Issue by sbdevelopment** [twigphp/Twig#2369]

**Comment by stof** [comment]
Are you using Twig 1 or Twig 2 ?

Twig 2 indeed dropped support for it, as the feature is deprecated as of PHP 7.2, and it was making the code much more complex. If you really need to use this feature in your project, keep using Twig 1.x

**Comment by sbdevelopment** [comment]
thanks!

**Comment by xabbuh** [comment]
@sbdevelopment Can you close this issue if your problem was solved?
