### ISSUE TITLE
Twig_Source should not be hidden from node visitors

### ISSUE THREAD

**Issue by mahagr** [twigphp/Twig#2372]
I'm trying to create context-aware node visitor for Twig_Node_Module, which makes changes to the nodes depending on the template name and path. Unfortunately `$source` is marked as private and there is no way to access it before template gets compiled into PHP.

Would you accept change that creates a public interface for accessing Twig_Source?

**Comment by robfrawley** [comment]
:+1: I'd love such an ability and would be happy to help with contributions to make this a reality, if the twig team is interested.

**Comment by fabpot** [comment]
IIUC, you want to compile the template differently based on the name and/or path? That's probably not something I want to support. Closing for now.
