### ISSUE TITLE
_self output inconsistent

### ISSUE THREAD

**Issue by c33s** [twigphp/Twig#2375]
running on Symfony 3.2.2

having a template in `example.com\app\Resources\views\static\about.html.twig`
`_self` outputs: 
- `static/about.html.twig` on windows7x64 PHP 7.0.13
- `:static:about.html.twig` on debian jessie PHP 7.0.14-1~dotdeb+8.1

**Comment by stof** [comment]
@fabpot are we sharing the cache key between both template names in Symfony ? This would be an issue as the template name is different for them, even though the source code is the same.

**Comment by fabpot** [comment]
Not sure why it could depend on the OS, but as we have unified to the Twig syntax, I'm going to close this issue now.
