### ISSUE TITLE
Twig variables not available within set context

### ISSUE THREAD

**Issue by CalvinMcGee** [twigphp/Twig#2376]
I have the following Twig templates:

`test_base.html`

    {% if language == 'sv' %}
        {% set website = 'exempel.se' %}
    {% else %}
        {% set website = 'example.com' %}
    {% endif %}

    {% block content %}{% endblock %}

`test.html`

    {% extends "test_base.html" %}
    {% set link %}http://{{ website }}{% block campaign_link %}/campaign/{% endblock %}{% endset %}

    {% block content %}
    <div>
        <a href="{{ link }}">Click here</a>
    </div>
    {% endblock content %}

`test_sv.html`

    {% extends "test.html" %}
    {% set language = 'sv' %}
    {% block campaign_link %}/kampanj/{% endblock %}

----------

When rendered the `test.html` becomes this:

    <div>
        <a href="http:///campaign/">Click here</a>
    </div>

And `test_sv.html` becomes this:

    <div>
        <a href="http:///kampanj/">Click here</a>
    </div>

So It is like the `{{ website }}` variable isn't available within the `set` context.

Am I doing something wrong, is this the desired behaviour or have I come across a bug?

**Comment by stof** [comment]
Code outside blocks in the child template runs *before* the code of the parent template (otherwise it would never run, as once the parent template rendering starts, it only calls blocks from the child template)).
So ``website`` is undefined at the time test.html uses it.

Btw, you should turn on strict variables during development. It makes it much easier to debug things (as undefined variable trigger errors in this case instead of giving ``null``)

**Comment by CalvinMcGee** [comment]
That sounds logical. Thanks for the tip about using strict_variables. That will certainly help in the future.

So I guess solving my issue would be doing something along the lines of:

    {% extends "test_base.html" %}
    {% block campaign_link %}/campaign/{% endblock %}

    {% block content %}
    {% set link %}http://{{ website }}{{ block('campaign_link') }}{% endset %}
    <div>
        <a href="{{ link }}">Click here</a>
    </div>
    {% endblock content %}

**Comment by stof** [comment]
yep.

You can even keep the ``{% block campaign_link %}`` inline inside the set if you want
