### ISSUE TITLE
Escaper crashes upgrading from 1.x to 2.x

### ISSUE THREAD

**Issue by vphantom** [twigphp/Twig#2386]
Luckily, I stumbled on #1799 and deduced that the `autoescape` configuration option probably can no longer handle `true` and must instead be set to `"html"` to keep that behavior.

It's not mentioned in http://twig.sensiolabs.org/doc/1.x/deprecated.html unfortunately.  Shouldn't it?

**Comment by stof** [comment]
hmm, this has indeed been forgotten in the doc. Can you send a PR updating this doc in the 1.x branch ?

**Comment by vphantom** [comment]
On one side I could edit [that text](https://github.com/twigphp/Twig/blob/1.x/doc/deprecated.rst), however I'm wondering if perhaps a small test for `true` to become functionally `"html"` in 2.x could be more useful going forwards?

I haven't seen your code before, but it seems that perhaps the [constructor](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Extension/Escaper.php) of `Twig_Extension_Escaper` could be the spot for that:

```diff
- public function __construct($defaultStrategy = 'html')
+ public function __construct($defaultStrategy = true)
{
+     if (true === $defaultStrategy) {
+         $defaultStrategy = 'html';
+     };
    $this->setDefaultStrategy($defaultStrategy);
}
```

Just a thought. :smile:

**Comment by stof** [comment]
No it should not. 2.x is totally fine breaking BC. The new major version is not the release where you add BC layers. It is the release where you **remove** them
And 1.x was adding a deprecation warning for the usage of ``true`` since at least 1 year.

**Comment by vphantom** [comment]
I never did have any deprecation warning while I was running 1.x as recently as last week on a fresh install, so I guess Composer had chosen a version from before that message appeared, for some reason.  Weird.

Now, I don't really know what kind of mention you're looking for in the text, but I'll give it a shot.
