### ISSUE TITLE
open_basedir issue when calling from command line

### ISSUE THREAD

**Issue by tsifra** [twigphp/Twig#2387]
Twig version is 1.30
I have a call in Symfony Command
$this->getContainer()->get('templating')->render('BackendType2SalesBundle:SalesOrder:email/order-item-updates.html.twig', array('items' => $soItems)),

php in command line called with special config that sets open_basedir = /srv/www/backend
usr/bin/php -c "/usr/local/php_custom_ini/php_backend.ini" -f /srv/www/backend/app/console -- --env=prod core:cron

It looks like i've never mentioned /var/www anywhere. So i expect twig to work only in app path. But it tries to access /var/www.
PHP Warning:  realpath(): open_basedir restriction in effect. File(/var/www) is not within the allowed path(s): (/srv/www/backend) in /srv/www/backend/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 35

**Comment by fabpot** [comment]
Closing as I've never used `open_basedir`, so I'm not sure what's wrong. Feel free to debug and submit a patch if there is something we can do. Thanks.
