### ISSUE TITLE
Unexpected "raw" tag (expecting closing tag for the "for" tag)

### ISSUE THREAD

**Issue by avant1** [twigphp/Twig#2390]
Hey there!
I've faced this error during upgrading from symfony 2.7 to 3.2 (twig version was bumped from 1.28.2 to 2.1.0).

Simple example:
```twig
{% for i in [1, 2, 3] %}
    {% raw %}
        {{ i }}
    {% endraw %}
{% endfor %}
```

However, if I use `verbatim` instead of `raw`, everything works fine.

<details> 
  <summary>Stack trace</summary>

```
[1] Twig_Error_Syntax: Unexpected "raw" tag (expecting closing tag for the "for" tag defined near line 31).
    at n/a
        in /src/app/Resources/views/abbreviations/index.html.twig line 31

    at Twig_Parser->subparse(array(object(Twig_TokenParser_For), 'decideForFork'))
        in /src/vendor/twig/twig/lib/Twig/TokenParser/For.php line 40

    at Twig_TokenParser_For->parse(object(Twig_Token))
        in /src/vendor/twig/twig/lib/Twig/Parser.php line 166

    at Twig_Parser->subparse(array(object(Twig_TokenParser_Block), 'decideBlockEnd'), true)
        in /src/vendor/twig/twig/lib/Twig/TokenParser/Block.php line 38

    at Twig_TokenParser_Block->parse(object(Twig_Token))
        in /src/vendor/twig/twig/lib/Twig/Parser.php line 166

    at Twig_Parser->subparse(null, false)
        in /src/vendor/twig/twig/lib/Twig/Parser.php line 79

    at Twig_Parser->parse(object(Twig_TokenStream))
        in /src/vendor/twig/twig/lib/Twig/Environment.php line 511

    at Twig_Environment->parse(object(Twig_TokenStream))
        in /src/vendor/twig/twig/lib/Twig/Environment.php line 543

    at Twig_Environment->compileSource(object(Twig_Source))
        in /src/vendor/twig/twig/lib/Twig/Environment.php line 362

    at Twig_Environment->loadTemplate(':abbreviations:index.html.twig', null)
        in /src/vendor/twig/twig/lib/Twig/Template.php line 327
```
</details>

This is probably some kind of regression.

**Comment by SpacePossum** [comment]
for ref.: https://twigfiddle.com/fkbi3s  (proofs OK on 1.x, fails on 2.x)

**Comment by avant1** [comment]
Thanks!

**Comment by avant1** [comment]
BTW I feel that the message itself is a bit confusing.
I read this message like 'we did not expect `raw` inside `for` cause it is not allowed or supported'.
But the main reason of error is unknown `raw` tag, right?

When we use unknown tags outside of `for` we get nice message about unknown tag: https://twigfiddle.com/6ecpw9
But unknown tag wrapped into `for` is just unexpected: https://twigfiddle.com/diohrd

What do you think?

**Comment by SpacePossum** [comment]
I'm not sure about the implementation details, so I would advice you to reopen the ticket and see if one of the maintainers can help you out :)

**Comment by fabpot** [comment]
The issue here is that Twig is not able to make a difference between a valid closing tag (`endif` of `endfor`, or even `else`) and an unknown tag.

In your case, the error message is indeed misleading, but if you have the following:

```twig
{% for 1 in 1..2 %}
{% endif %}
```

The message is more appropriate  as the `endif` tag exists but is not the one that is expected.

Not sure what to do here, except changing Twig so that it is aware of closing tags as well.

**Comment by avant1** [comment]
Yeah, the only thing that can be done here is to use more concrete message for unknown tags.
I'm not familiar with Twig internals so I cannot say if it is easy to implement such behaviour.
However the benefit is not large, just small DX improvement.

So feel free to close the issue if you think that it doesn't worth to be implemented.

**Comment by fabpot** [comment]
Closing as I don't think there is an easy way to make it better.
