### ISSUE TITLE
Change the way the cache classes are created (use anonymous classes)

### ISSUE THREAD

**Issue by bkielbasa** [twigphp/Twig#2392]
hi there, I consider adding pull request with changes to the way the cache classes are created in Twig. I am curious what you think about it.

Motivation: I have a service which uses twig a lot. It stops only when it crashes or new version is released. The service renders a lot of twig templates. The problem is when it runs for a very long time. I debugged the whole flow and I think the problem is here https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Environment.php#L384

Every time new template is processed it creates new class definition and stores it in the memory. It may be problematic when someone (like me) renders few millions of templates every day. The only solution for me is to add a crontab job to restart it or use some other hack.

I thought about changing the way the cache classes are created and use the new PHP7 feature called anonymous classes. The problem is that change may cause BR problems with both API (for example Twig_Environment and Twig_CacheInterface classes) and already created caches.

**Comment by jvasseur** [comment]
I'm not totally sure but I don't think anonymous classes would solve anything here. If I recall correctly anonymous classes are handled the same way as classic classes by the PHP engine except they have a special "anonymous" name meaning they will be kept in memory forever event if not used anymore.

**Comment by bkielbasa** [comment]
hmm, so maybe there is another way to solve the problem? Maybe create one object of a class and just change the data there?

**Comment by stof** [comment]
@bkielbasa which data ? the compiled templates have different code in their ``doDisplay`` methods (plus methods for blocks and macros they define). they are not about data.
Not relying on generating PHP code would force rewriting Twig from scratch, which is not planned.

**Comment by fabpot** [comment]
Using anonymous classes would be a huge change in how Twig deal with templates. Closing this issue as it's probably not going to happen anytime soon (FYI, I tried once to do that and gave up).
