### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by koflerdavid** [twigphp/Twig#2396]
As of 2017-02-14 10:00, Twig's website at twig.sensiolabs.com answers with a 404 error to all requests :( (The sensiolabs.org website seems to be down as well and does not answer to requests).

**Comment by javiereguiluz** [comment]
Yes, Twig website is temporarily down because of some issues. We're working on it. Thanks!

**Comment by javiereguiluz** [comment]
Website is back online: http://twig.sensiolabs.org

**Comment by koflerdavid** [comment]
Great work! :-D
