### ISSUE TITLE
RSS on twig homepage now links to some carpenter blog

### ISSUE THREAD

**Issue by TiGR** [twigphp/Twig#2399]
You can find the url in twig pages html:

    <link rel="alternate" type="application/rss+xml" href="http://feeds.feedburner.com/twig-project" />

Formerly it contained blog posts and news about new releases.

**Comment by lyrixx** [comment]
Thanks @TiGR  ; I fixed it and it's now deployed ;)

**Comment by TiGR** [comment]
Well, @lyrixx, doesn't seems so. The code is still there, the url is the same, and RSS feed contents has not changed also. For example, [Twig homepage](http://twig.sensiolabs.org/).

**Comment by lyrixx** [comment]
@TiGR Actually, I just removed the RSS feed link from the homepage because obviously, the RSS feed is dead.

**Comment by TiGR** [comment]
@lyrixx There is still a link to it in the `<head>` section. That link is being detected by various robots, rss-readers and browser extensions.

**Comment by lyrixx** [comment]
@TiGR I'm sorry, I can not find it. Could you show me where it is? (May be you have a cache issue?)

**Comment by TiGR** [comment]
Well,

```bash
$ wget -qO- twig.sensiolabs.org | grep rss
    <link rel="alternate" type="application/rss+xml" href="http://feeds.feedburner.com/twig-project" />
```

Not sure about cache (if it is cache, then not on my computer, tested on few machines around the globe), but it is there, right after css links:

```html
    <title>Home - Twig - The flexible, fast, and secure PHP template engine</title>

    <link href="/css/reset-min.css" rel="stylesheet" type="text/css" />
    <link href="/css/base.css" rel="stylesheet" type="text/css" />
    <link href="/css/colors.css" rel="stylesheet" type="text/css" />
    <link href="/css/code.css" rel="stylesheet" type="text/css" />
    <link href="/css/pygments.css" rel="stylesheet" type="text/css" />

    
    <link rel="alternate" type="application/rss+xml" href="http://feeds.feedburner.com/twig-project" />
```

**Comment by javiereguiluz** [comment]
@TiGR I cannot reproduce it. This is what I get when browsing twig.sensiolabs.org

![twig-head](https://cloud.githubusercontent.com/assets/73419/23016922/97a69b0c-f438-11e6-823a-654b9c04418e.png)

**Comment by lyrixx** [comment]
@javiereguiluz Oh it's weird, I have the same issue as you. But indeed with curl / wget the link is here.

=> @fabpot Could you ensure to redeploy the application?

**Comment by lyrixx** [comment]
Actually, I guess it's in cache.
` curl 'http://twig.sensiolabs.org/' -H 'Accept-Language: fr,en-US;q=0.8,en;q=0.6'   -s |grep rss`  does not show the rss feed.

@TiGR So just wait a bit (at max 86400s), and it will be ok. Sorry about that.
