### ISSUE TITLE
Test Suite Fails in PHPUnit 6

### ISSUE THREAD

**Issue by antonydandrea** [twigphp/Twig#2408]
Twig 2.0 is PHP 7 compatible and so is PHPUnit 6. 

However, the tests currently error with:

"PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/Twig/test/Twig/Tests/Cache/FilesystemTest.php on line 14" 

but on PHPUnit 5.7, the tests work fine.

**Comment by javiereguiluz** [comment]
In PHPUnit 6, the class `PHPUnit_Framework_TestCase` no longer exists, right? They siwtched to PHP namespaces: `PHPUnit\Framework\TestCase`

**Comment by stof** [comment]
The Twig testsuite has not yet been updated for BC breaks in PHPUnit 6

**Comment by xabbuh** [comment]
This should be fixed by #2423.
