### ISSUE TITLE
Get compiled templates 

### ISSUE THREAD

**Issue by djsmithme** [twigphp/Twig#2409]
Considering Twig_Environment::getCacheFilename() has been removed from twig 2 how to do you get the cache name for the compiled templates?

I can check if the cache is valid using Twig_Environment::isTemplateFresh($path, $time) but how can I actually get the name of the cache template? 

If I try Twig_Loader_Filesystem::getCacheKey($path) all that is returned is the original template path not the expected /CacheDir/38/3861bec3153....

**Comment by djsmithme** [comment]
Best way I gave found is to reflect the Twig_Cache_Filesystem and then use that to generate the key.

```       
 Twig_Cache_Filesystem->generateKey($path, Twig_Environment::getTemplateClass($path) );

**Comment by fabpot** [comment]
What would be the use case. In Twig 2, we've tried hard to remove easy access to internal implementation details. That's a very good example. Today, templates are compiled as classes, but that can change, and we want to be able to do it without breaking BC.

**Comment by djsmithme** [comment]
Using twig as a component with a couple of other template engines. It was so we can override/enable/disable/clear on a template by template basis without breaking BC our end. We also push some pages/blocks to memcache and use the cache as a way of checking if it's fresh.

    View::render(string $path, array $data = [], array $options = []) : ResponseInterface
