### ISSUE TITLE
Getting 'cache is corrupted' when not using cache

### ISSUE THREAD

**Issue by belackriv** [twigphp/Twig#2413]
I'm using a custom Twig_Environment and Loader (Loading custom user defined templates from database). I'm setting `'cache' => false` in the Environment settings, but any time I render I get an exception thrown by https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Environment.php#L377 .

**Comment by stof** [comment]
@belackriv make sure that your loader returns a different cache key for each user-defined template (and that it changes when the source is changing, if you ever need to use the new template source code in a PHP process where the old template source code may have been loaded already).
Twig generates a class name based on this key (and a few other settings), and PHP does not allow you to reuse the same class name later for a different class.
I suspect your issue happens in some cases when a user-defined template uses ``{% embed %}`` and reusing a cache key from a template which does not.

**Comment by SpacePossum** [comment]
good points @stof 
I observed the same in this PR https://github.com/twigphp/Twig/pull/2384 (i.e. report corrupt cache while no cache in use)

**Comment by belackriv** [comment]
@stof my cache key is just basically the template name, which is unique.  The templates are for emails that will be sent at a later time, so new and old sources would never be loaded at the same time the template would be rendered or loaded.  The template I was trying to render was literally "test content". 

I dove into this a little and found that on https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Environment.php#L367,  $cls was '__TwigTemplate_731a081ff9e4c740f86c7d4a2df6db2380279110410beb0f4f06af4c9d9545cb', but the evaled $content was 'class __TwigTemplate_264b741b4d2b2158aff1ce6339de552e67c3694b04fe6cb7b3f421d764e638b2 extends Twig_Template'.  It seems like these two should match.

**Comment by belackriv** [comment]
I found the problem.  My template names are a mixture of the $templateEntity->name and $templateEntity->sourceOne or  templateEntity->sourceTwo, etc (one template entity holds the templates for several different emails).  The template name being sent to the loaders was either the base name, or a mashup of the name+sourceXXX.  Thus I could get different cache keys for the same template or something.  I change the loader to just return false for the cache key, and everything works now.
