### ISSUE TITLE
Warning: setlocale()...

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [twigphp/Twig#2416]
PHP 7.1.2, Twig 1.32 (ctype, xdebug enable)

=output=
Warning: setlocale() expects parameter 1 to be integer, string given in 
=/output=

I follow the documents and twig throw this error. What should i do?

If you say "yes we need see this code" i will add code.

**Comment by stof** [comment]
Please give the end of the error message. you cut it just before the location of the error

**Comment by BerkhanBerkdemir** [comment]
OK. This error reason php 7.1 , i m turn back php 5.6 and now i have not a problem. But you want my code?

**Comment by stof** [comment]
I don't need your code, I need the end of the error message (the part after ``in``, where it gives the name of the file in which there is the error)

**Comment by stof** [comment]
Btw, giving the error location part of the error message is good for *any* bug report. It generally allows to identify the issue much faster.

**Comment by BerkhanBerkdemir** [comment]
https://ibb.co/gXVxdv
