### ISSUE TITLE
Decouple Module node from twig environment

### ISSUE THREAD

**Issue by flip111** [twigphp/Twig#2425]
I noticed that this node [requires an environment](https://github.com/twigphp/Twig/blob/5527658f0863d18d3cb7035ce250dbdcf830ad88/lib/Twig/Node/Module.php#L148-L149)

I ran into this when i tried to inspect the compiler renderer without using cache, where i was forced to set a template name like this. The `foo` key has no purpose here but was only required because of the dependency of the node onto the environment.

```php
<?php
$loader = new Twig_Loader_Array([
  'foo' => file_get_contents($template_file),
]);
$twig = new Twig_Environment($loader);

$renderer = $twig->compileSource(new Twig_Source(file_get_contents($template_file), 'foo'));
```

This could be written more clean by giving class name and extends name as parameters to the `compileClassHeader` function

**Comment by fabpot** [comment]
Not sure I understand what you want to do here. Or what we should fix.

**Comment by flip111** [comment]
I mean something like this

```php
    protected function compileClassHeader(Twig_Compiler $compiler, $className, $baseTemplateClass)
    {
        $compiler
            ->write("\n\n")
            // if the template name contains */, add a blank to avoid a PHP parse error
            ->write('/* '.str_replace('*/', '* /', $this->source->getName())." */\n")
            ->write('class '.$className)
            ->raw(sprintf(" extends %s\n", $baseTemplateClass))
            ->write("{\n")
            ->indent()
        ;
    }
```

This way a node doesn't depend on an environment but can just be compiled given a string.

**Comment by fabpot** [comment]
Closing as you should not override the `Module` node (if you read the phpdoc comment at the top, you will see that this class should be considered final).

**Comment by flip111** [comment]
I don't override the `Module` node. The problem is in the original twig code, which does not support rendering without cache. The code in the second comment was about how the method could be fixed. What i'm doing is described in the first comment. You can diff the twig source code with the alternative implementation in the second comment and you will see that the dependency on environment is gone. In particular this piece of code `$compiler->getEnvironment()`.

**Comment by stof** [comment]
I still don't understand why you have an issue with the usage of the Twig_Environment.

**Comment by flip111** [comment]
I just want to call the [compileSource](https://github.com/twigphp/Twig/blob/0dbc6b87dcdfd72b2069b35e56d51d23a1cd5a25/lib/Twig/Environment.php#L541) method, likethis:

```php
$renderer = $twig->compileSource(new Twig_Source(file_get_contents($template_file), 'foo'));
```

This code here

```php
$loader = new Twig_Loader_Array([
  'foo' => file_get_contents($template_file),
]);
```
Doesn't serve any purpose other than being compatible with how the environment should be setup for twig to work. Try calling `compileSource` without this it will just go wrong, no warning (by twig), no comments, no documentation about that. API just says [Compiles a template source code](https://twig.sensiolabs.org/api/2.x/Twig_Environment.html#method_compileSource), which is what i want to do. When you run `compileSource` without loader you hardly get any information, maybe a php notice or you just don't get output. I can try to recreate what i was doing before and then tell "i got no output" or "i got this php notice". But i thought that pointing to the twig code where the chain of dependencies get invoked it would be more obvious.

**Comment by stof** [comment]
Well, even if we pass arguments to the protected method, the calling site (which is in the same class) will still need to get the template class. And this requires getting some info from the loader.
The loader is the one knowing where Twig_Source comes from in the Twig architecture, which is why the environment delegates some logic to the loader.

**Comment by flip111** [comment]
This is true @stof , i wouldn't change this code now, but certainly something to keep in mind at the time of a major overhaul. The `compileSource` method could also take a classname. But i think what is important for twig is not necessarily this particular method. But rather that you have dependencies between functions and classes, you have to call them in a specific order otherwise you mess up the internal state of twig. Method should either check if there is a valid state present or document this behavior in comments for the programmer.

About compile & nodes ... A compiler should have control over AST sure, but the other way around an AST is not in need for a compiler for it already have a meaning on itself. You can use AST for parsers (sometimes part of compiler) and pretty printing of AST. I saw this more often in PHP. Traits are a nice idea here but unfortunately you can't write a trait for a particular class that implements a certain interface :( And inheritance (`CompilerAwareNode extends GeneralNode`) is not nice. I don't see how code here can be grouped in a better way here, but it can be decoupled never the less in terms of control/data flow.

**Comment by stof** [comment]
The compileSource should not take a class name as argument, unless we remove it from the public Twig API. The class name itself is something generated by Twig. This responsibility cannot be moved to the outside (if we allow external code to mess with it, it can break the usage of Twig entirely).

The issue in your case is that you are trying to call `compileSource` with a source you build on your own instead of getting it from the dedicated Twig APIs. This can indeed cause issues if it is impossible to get the same Twig_Source through dedicated APIs.

What is actually your use case for compiling sources you build on your own ?

**Comment by flip111** [comment]
Want to inspect the rendering code while debugging the template.
