### ISSUE TITLE
Fatal error: Class Twig_Loader_Filesystem contains 1 abstract method (PHP 7.1 & Symfony 3.2.6)

### ISSUE THREAD

**Issue by exts** [twigphp/Twig#2430]
Context: Trying the symfony 3 framework for the first time, downloaded the installer from the main site and everything was working fine, then I ran composer update based off the default configuration and I got that error once twig updated.

Error:

> Fatal error: Class Twig_Loader_Filesystem contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSource) in /var/www/sf3.dev/tmi/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 17

> Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Error: Class Twig_Loader_Filesystem contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSource) in /var/www/sf3.dev/tmi/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:17 Stack trace: #0 {main} Next Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "twig", path: "templating -> twig -> twig.loader -> twig.controller.exception". in /var/www/sf3.dev/tmi/var/cache/prod/classes.php:3483 Stack trace: #0 /var/www/sf3.dev/tmi/var/cache/prod/appProdProjectContainer.php(2874): Symfony\Component\DependencyInjection\Container->get('twig') #1 /var/www/sf3.dev/tmi/var/cache/prod/classes.php(3513): appProdProjectContainer->getTwig_Controller_ExceptionService() #2 /var/www/sf3.dev/tmi/var/cache/prod/classes.php(4881): Symfony\Component\DependencyInjection\Container->get('twig.controller...') #3 /var/www/sf3.dev/tmi in /var/www/sf3.dev/tmi/var/cache/prod/classes.php on line 3483

Info:

PHP 7.1.3
nginx 1.4.6
symfony: 3.2.6
environment: vagrant 1.9.2 & VB 5.0.26
vm os: ubuntu 14.02 64bit
os: windows 10

composer dump:

    doctrine/annotations                 v1.4.0  Docblock Annotations Parser
    doctrine/cache                       v1.6.1  Caching library offering an object-oriented API for many ca...
    doctrine/collections                 v1.4.0  Collections Abstraction library
    doctrine/common                      v2.7.2  Common Library for Doctrine projects
    doctrine/dbal                        v2.5.12 Database Abstraction Layer
    doctrine/doctrine-bundle             1.6.7   Symfony DoctrineBundle
    doctrine/doctrine-cache-bundle       1.3.0   Symfony Bundle for Doctrine Cache
    doctrine/inflector                   v1.1.0  Common String Manipulations with regard to casing and singu...
    doctrine/instantiator                1.0.5   A small, lightweight utility to instantiate objects in PHP ...
    doctrine/lexer                       v1.0.1  Base library for a lexer that can be used in Top-Down, Recu...
    doctrine/orm                         v2.5.6  Object-Relational-Mapper for PHP
    incenteev/composer-parameter-handler v2.1.2  Composer script handling your ignored parameter file
    jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
    monolog/monolog                      1.22.1  Sends your logs to files, sockets, inboxes, databases and v...
    paragonie/random_compat              v2.0.10 PHP 5.x polyfill for random_bytes() and random_int() from P...
    psr/cache                            1.0.1   Common interface for caching libraries
    psr/log                              1.0.2   Common interface for logging libraries
    sensio/distribution-bundle           v5.0.18 Base bundle for Symfony Distributions
    sensio/framework-extra-bundle        v3.0.23 This bundle provides a way to configure your controllers wi...
    sensio/generator-bundle              v3.1.4  This bundle generates code for you
    sensiolabs/security-checker          v4.0.2  A security checker for your composer.lock
    swiftmailer/swiftmailer              v5.4.6  Swiftmailer, free feature-rich PHP mailer
    symfony/monolog-bundle               v3.0.3  Symfony MonologBundle
    symfony/phpunit-bridge               v3.2.6  Symfony PHPUnit Bridge
    symfony/polyfill-apcu                v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP ...
    symfony/polyfill-intl-icu            v1.3.0  Symfony polyfill for intl's ICU-related data and classes
    symfony/polyfill-mbstring            v1.3.0  Symfony polyfill for the Mbstring extension
    symfony/polyfill-php56               v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lowe...
    symfony/polyfill-php70               v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lowe...
    symfony/polyfill-util                v1.3.0  Symfony utilities for portability of PHP codes
    symfony/swiftmailer-bundle           v2.5.3  Symfony SwiftmailerBundle
    symfony/symfony                      v3.2.6  The Symfony PHP framework
    twig/twig                            v2.2.0  Twig, the flexible, fast, and secure template language for PHP

Packages updated after running composer update:

    - Updating twig/twig (v1.31.0 => v2.2.0): Downloading (100%)
    - Updating paragonie/random_compat (v2.0.4 => v2.0.10): Downloading (100%)
    - Updating symfony/symfony (v3.2.4 => v3.2.6): Downloading (100%)
    - Updating doctrine/collections (v1.3.0 => v1.4.0): Downloading (100%)
    - Updating doctrine/annotations (v1.2.7 => v1.4.0): Downloading (100%)
    - Updating doctrine/common (v2.6.2 => v2.7.2): Downloading (100%)
    - Updating symfony/swiftmailer-bundle (v2.4.2 => v2.5.3): Downloading (100%)
    - Updating sensio/framework-extra-bundle (v3.0.22 => v3.0.23): Downloading (100%)
    - Updating sensio/generator-bundle (v3.1.2 => v3.1.4): Downloading (100%)
    - Updating symfony/phpunit-bridge (v3.2.4 => v3.2.6): Downloading (100%)
    - Updating sensiolabs/security-checker (v4.0.0 => v4.0.2): Downloading (100%)
    - Updating monolog/monolog (1.22.0 => 1.22.1): Downloading (100%)

**Comment by xabbuh** [comment]
Did you clear the cache after running `composer update`?

**Comment by SpacePossum** [comment]
method is not on the interface (any more) on 2.2.0 (https://github.com/twigphp/Twig/blob/v2.2.0/lib/Twig/LoaderInterface.php),
do you have caching enabled?

**Comment by exts** [comment]
@xabbuh oh man, that fixed it. now I need to figure out how to get cache clear working on windows/vagrant -_- w/out doing it manually thanks

Reading through the comments for #2600 atm
