### ISSUE TITLE
Macros in embed tags

### ISSUE THREAD

**Issue by julienfalque** [twigphp/Twig#2442]
Macros imported in a template are not accessible in `embed` tags of the same template.

With following templates:

**foo.html.twig**
```twig
{% import 'bar.html.twig' as bar_macros %}

{% embed 'baz.html.twig' %}
    {% block baz %}
        {{ bar_macros.bar() }}
    {% endblock %}
{% endembed %}
```

**bar.html.twig**
```twig
{% macro bar() %}
    BAR
{% endmacro %}
```

**baz.html.twig**
```twig
{% block baz %}{% endblock %}
```

trying to render foo.html.twig will throw an exception: `Twig_Error_Runtime: Accessing Twig_Template attributes is forbidden`.

The only workaround I found is to import the macros inside the `embed` tag. Explicitly passing `bar_macros` using `with` keyword does not help. I have this issue with Twig 2.3.0, is it the expected behavior?

**Comment by sstok** [comment]
https://twig.sensiolabs.org/doc/2.x/tags/embed.html

An embed is rendered in it's own contexts, so other then passing variables it doesn't inherit anything from it's parent.

**Comment by julienfalque** [comment]
This is not true: `embed` tags do have access to variables from the context they are declared in unless you use the `only` keyword, just like with `include` tags.

Anyway, passing the imported macro explicitly to the embed tag like this:
```twig
{% embed 'baz.html.twig' with {'bar_macros': bar_macros} %}
    {% block baz %}
        {{ bar_macros.bar() }}
    {% endblock %}
{% endembed %}
```
does not work either.

**Comment by julienfalque** [comment]
This also fails with macros from the same template:

```twig
{% macro bar() %}
    BAR
{% endmacro %}

{% embed 'baz.html.twig' %}
    {% import _self as bar_macros %}

    {% block baz %}
        {{ bar_macros.bar() }}
    {% endblock %}
{% endembed %}
```

but the error is different: `Error: Call to undefined method __TwigTemplate_[...]::macro_bar()`.

**Comment by stof** [comment]
@julienfalque `_self` refers to the anonymous template inside the `{% embed %}` tag, not to the main template. This is why it does not work.

**Comment by julienfalque** [comment]
Wouldn't it be more convenient that `_self` always refers to the actual "main" template it is used in? I suppose this would be a BC break though.

**Comment by Ovissse** [comment]
This solution seems to work

```twig
{% embed 'baz.html.twig' with {'bar': bar_macros.bar()} %}
    {% block baz %}
        {{ bar|raw }}
    {% endblock %}
{% endembed %}
```

**Comment by fabpot** [comment]
In #3012, I've fixed the error message to be more meaningful. #3012 already clarifies the rules. Here, you must import the macros in the `embed` tag.

**Comment by carpabg** [comment]
For more complex macros or macros that it output depends on variables inside the embed block (a for loop for example) I found this solution.

``` 
{% embed 'baz.html.twig' with {'template': _self} %}
    {% import template as bar_macros %}
    {% for x in baz %}
        {{ bar(x) }}
    {% endfor %}
{% endembed %} 
```
