### ISSUE TITLE
Master Branch is quite far behind

### ISSUE THREAD

**Issue by antonydandrea** [twigphp/Twig#2443]
Apologies if this is not the correct place to talk about this. But I was wondering why it has been a long time since changes have been merged to master?
It appears that the contributor page, the community badges and links from the contributor page are all based on master, and so changes are not being correctly reflected here.

Perhaps the 2.0 branch needs to be the new master branch?

**Comment by fabpot** [comment]
Thanks for reaching out. Master will be the 3.0 version, which is not really started. That being said, you're right about the website. I will see how to deal with that. Thanks.

**Comment by stof** [comment]
@fabpot why not keeping the master branch for the development of 2.x as long as the work on 3.0 does not start ?
