### ISSUE TITLE
FatalErrorException in Core.php line 1588: Parse Error: syntax error, unexpected '.'

### ISSUE THREAD

**Issue by giovannilegrandpp** [twigphp/Twig#2444]
dear twig,

when i try to run my symfony application i get the error message as above, when i check the core.php file at line 1588 i see: $ret = $object->$method(...$arguments);

now im wondering how i can fix this problem, i am using php 7.0 so it shouldnt be a problem i think.

**Comment by xabbuh** [comment]
Are you sure that the process emitting this exception is really using PHP 7?

**Comment by giovannilegrandpp** [comment]
yes im very sure, when i check with phpinfo it says: PHP Version 7.0.16, im updating to 7.0.17 atm to see it that fixes it.

**Comment by fabpot** [comment]
Closing as Travis proves that it does work on PHP 7.0.
