### ISSUE TITLE
1.33.0: Twig attempting to redeclare variable

### ISSUE THREAD

**Issue by pugsley** [twigphp/Twig#2445]
I have a Laravel 4.2 app with an existing PHP class called `App\Models\NonProfit`. I'm having issues with Twig `1.33.0` when using a Twig-set string variable with the `default()` filter when the value of the variable is the same as an existing classname. e.g. `NonProfit`;

Here's a simplified version:
```
{# NonProfit class already defined elsewhere #}
{% set blah = "NonProfit" %}
{{ blah|default() }}
```
The `default()` filter calls `twig_test_empty` which in turn uses `method_exists('NonProfit', '_toString')`. This throws the following error in PHP:

```
 Cannot redeclare class App\Models\NonProfit
```

If I remove this newly added block (https://github.com/twigphp/Twig/compare/v1.32.0...v1.33.0#diff-d7378002f67a61c458c1de0468eef74fR1428) from `Core.php` (or downgrade to 1.32.0). It works again.

**Comment by xabbuh** [comment]
Can you check if Twig works for you with the changes from #2433.

**Comment by pugsley** [comment]
Ah yip, that fixes it. Apologies, I should've searched through the closed issues!
