### ISSUE TITLE
[QUESTION] Collision of function/test/filter/tag names

### ISSUE THREAD

**Issue by TheCelavi** [twigphp/Twig#2446]
There is a possibility to create two different twig extensions by two vendors which consists of functions/tests/filters/tags with same name. 

It is clear that it is impossible to use two those extensions in same project, or at least, within the same instance of Twig_Environment. 

In standard PHP (or almost any other prog. language) there are namespaces which should help us to avoid such situations.

I was wondering if there was any discussion about similar thing in Twig? (I was trying to find out in previous issues/tickets, seams that no one has raised that question...).

Thanks.

**Comment by stof** [comment]
The convention today is to prefix your filter names by something identifying your library if you want to avoid conflicts with other libraries.
As I don't think a concept of use statement makes sense in templates (especially if we want to keep it possible for people to work on templates without being PHP developers too), I don't see a way to add a namespacing feature making code less verbose than putting the namespacing directly in the function/filter names as today

**Comment by TheCelavi** [comment]
Personally - I don't like long name functions/tests/filters/tags with a lot of underscores... (my_company_date, my_company_my_library_date, etc...), however, I don't have any proposal that would solve this issue with elegance, and if Twig community does not share same preference, there is no point to search for such solution. 

So, thank you for your instant reply, I will close this issue.

**Comment by stof** [comment]
well, would you prefer seeing the same as `my_company\date` ? It is not shorter

**Comment by TheCelavi** [comment]
Well, to be honest, I was thinking about something like:

1.) if there is no collision, simple `date` can be used, Twig env would implicitly add a namespace from first matching function/test/filter/tag
2.) if there is collision, an exception would be thrown if there is no namespace
3.) user can use either namespace, or 4.) tag `{% namespace 'my_company' %}` could be used so every colliding function/test/filter/tag would use function/test/filter/tag from stated namespace.

4.) is kinda my preferable option.

**Comment by stof** [comment]
what if a template needs to use both ? Your 4.) proposal won't work. And what if multiple namespaces are needed for different functions in the template ? The resolution becomes insane.

And silently selecting one when there is no collision only is a bad DX, because it means that registering a new extension in your project may require you to alter all your existing templates to add an explicit namespace.

**Comment by TheCelavi** [comment]
It is not solution that you have to choose between 1,2,3 and 4, sorry if I gave you that impression because I used enumeration in order to emphasize that 4. is kinda elegant that I will usually use when I want to use, per example, functions from one namespace on template level.

So this statement: "_what if a template needs to use both ? Your 4.) proposal won't work. And what if multiple namespaces are needed for different functions in the template ? The resolution becomes insane._" - well, I can not use a `namespace` tag, but in that case, I can use 3 -> explicitly stating from which namespace to use which call.

"_And silently selecting one when there is no collision only is a bad DX, because it means that registering a new extension in your project may require you to alter all your existing templates to add an explicit namespace._" - ok, I can agree with you on this -> there should not be a silent selection of namespace.

But in order not to introduce BC break, there should be a an "empty" namespace for existing  functions/tests/filters/tags.

So filter `date` would call a core `date` filter, `{% namespace 'my_company' %}{{ 'now'|date }}` would call `date` filter from `my_company` namespace, if exists, or core `date` filter if it does not.

Or you can explicitly call a filter with namespace if you don't want to use a namespace tag.

But, why we are discussing this, you are actually thinking about this? Or you want to shut down me with viable reasoning? If that is the case - you don't need to waste your time, I am not too much into finding some elegant solution, I was just interested in if there are some discussions/plans on that topic in general... I am not going to pursue this with tooth and nails :).

**Comment by stof** [comment]
well, my own vote is still to keep using the existing way based on the name. But I gave you some more insight on it (saying ` the Twig community does not share same preference` based on a single comment from me may be overdone as I haven't asked the whole community before answering, even though I suspect that @fabpot may agree with me that the current prefix-based solution works fine enough).
but if you are fine with the existing solution, I will indeed stop looking for proposals

**Comment by TheCelavi** [comment]
No, I am fine.

There are several similar template engines to Twig (not only PHP based ones) that has same namespace issue and they didn't offered some elegant solution except prefixing (as far as I know), so I was just wondering what was the reason... Like, it wasn't too hard to find few ideas how to solve it... 

Nevertheless, thank you for your time.
