### ISSUE TITLE
Regression on PHP 5 caused by "Enhance perf of Template::getAttribute() #2228"

### ISSUE THREAD

**Issue by Berdir** [twigphp/Twig#2447]
After updating twig from 1.24 to 1.33 in a Drupal project, as part of updating from Drupal 8.2 to 8.3, we were running into a strange fatal error for a developer here that was still running PHP 5.5 and I could not reproduce on PHP 7.

After a lot of debugging, we tracked this down to a behavior change in substr() in PHP 5 vs PHP 7, combined with the refactoring in #2228.

The problematic part are the following lines:

    if ('g' === $lcName[0] && 0 === strpos($lcName, 'get')) {
      $name = substr($method, 3);
      $lcName = substr($lcName, 3);
    }
    // ....
    $cache[$name] = $method;

If you have "get" as method, then the condition above applies, and it runs the substr: https://3v4l.org/K2vhM

Since PHP7, this returns an empty string, in PHP 5, it is false, which is converted to 0 when used as an array key. So now the method cache contains 0 => get on PHP 5 and '' => 'get' on PHP 7.

In Drupal, we have a pretty crazy Entity system, which relies heavily on ArrayAccess, __get()/__set() methods and more. In our project, in a template, we had this condition:

    {% if node.some_field.0.value == 'some_string' %}

Node is a Entity, some_field is a FieldItemList objects which implements ArrayAccess but also has a get() method. In the case where it fails, the list is empty, so the isset() with array access returns false, then it creates that method name cache and now has a match on $item = 0 and calls get(). FieldItemList::get() however expects an argument and if that is not numeric, it throws an exception (we support both $object[0] and $object->get(0)).

I think the fix is quite easy, it makes no sense for that condition there to match just "get" or just "is", but not sure what the most performant way to do so is. Maybe check that the resulting $name is not empty?

**Comment by fabpot** [comment]
@Berdir Can you check if #2449 fixed this issue for Drupal?

**Comment by Berdir** [comment]
@fabpot Thanks for the quick response. The fix looks good to me.
