### ISSUE TITLE
Missing documentation for block rendering

### ISSUE THREAD

**Issue by Koc** [twigphp/Twig#2450]
#2236 was merged but there is no any public incormation about this feature https://twig.sensiolabs.org/doc/1.x/recipes.html

**Comment by fabpot** [comment]
#2236 includes changes in the documentation that explain the new feature. What is missing?

**Comment by Koc** [comment]
IMHO it is better add section incide recipes page.

**Comment by fabpot** [comment]
Feel free to open a PR with some more information, but I don't see why a recipe would be better here.
