### ISSUE TITLE
Improve reusability of Twig_Lexer and Twig_Parser internal classes

### ISSUE THREAD

**Issue by davidmpaz** [twigphp/Twig#2451]
Hello,

By doing some research, this [question](http://stackoverflow.com/questions/43430139/is-possible-to-extend-from-twig-lexer) arose regarding extending Twig internals.

Also since I saw that another new version is getting bumped [4335780](https://github.com/twigphp/Twig/commit/433578085333ed53d4eb98fc4f6d28a737c8e666). I though that maybe this could be introduced for next version.

My request is:

Please could you consider making **members** of related classes **protected**, so extending from `Twig_Lexer` and/or `Twig_Parser` can be more straight forward without repeating not needed code?

thanks in advance for your time and for making Twig great.
David

**Comment by fabpot** [comment]
In Twig 2.0, we have indeed close as much internals as possible. That makes it easier to evolve the code, improve it, and add new features. We won't relax that except when there is a use case that needs to be supported. So, the question is: why would you want to extend the parser or the lexer?

**Comment by davidmpaz** [comment]
Hi @fabpot, 

thank you very much for the fast response. I am using currently `"twig/twig": "^2.3"`.

I am looking for the way to add sugar syntax to Twig to declare in templates **Components** constructs ala [WebComponents](https://www.webcomponents.org/).

Since this is some xml syntax i dont see a way to accomodate it in current extensions points of Twig.

The reason behind this is that i could be able to reuse templates in backend as well in front end, [maybe from angular](https://github.com/manekinekko/angular2-twig) Would this make sense?

Also I think it would be great if such classes could be open for extension allowing people to change them, by implementing an interface or so.

**Comment by fabpot** [comment]
The last sentence of your comment is exactly what I want to prevent. As you might have seen, we don't have interfaces for the lexer and the parser anymore in 2.0. Those classes are written to support Twig and Twig only. So, there should not be cases where you would want to "extend" or rewrite them.

As for you use case, can you give me some examples of what it would look like? Can't you support this via a pre-processor?

**Comment by davidmpaz** [comment]
Yes I noted that :)

Regading use case, I was thinking in something like this in templates:
```
<is-header title="The header" data-id="345">
    <is-banner class="some-banner" />
</is-header>
```
Each of those tag could have some logic behing to use with attributes given or just print atributes as per se. A template will be used also for rendering such "component". This is why I though on having `Twig_Lexer` and `Twig_Parser` extended and also adding later  `Twig_Node` as needed. It did look more natural to me to have it available for configuration later on on Twig and take advantage of Twig API for it.

About your suggestion on using pre-processor, I havent read about it (yet) unfortunately, so I can not tell how far can I get with it. Could you please provide me some resources to chew?

**Comment by fabpot** [comment]
I don't think extending Twig internals is a good idea. Keep in mind that Twig is not just for HTML templates, but for any templates. In your case, what about doing your work after Twig rendering? Or just before. Pre or post processing is really up to you, there are no tools in Twig to help you do that by definition as it really depends on you use case.

**Comment by sstok** [comment]
Usually when you have such a use-case you can create custom Tag, like `{% web-component %}your html-here{% end web-component  %}` 👍

**Comment by davidmpaz** [comment]
Hey @fabpot , @sstok thanks for the feedback!

I know this is an specific case. And quite orthogonal for so to speak, from Twig currently.

@sstok regarding implementing a custom tag I have considered, but one of the first ideas from this was to be able to have the custom html tags, designers can benefit from it.

So for now. I will keep all this in mind and see what can I do, with pre and/or post processors for example. 

Since what I am asking is already asnwered, that will not be possible, I will close this.

Many thanks again.
