### ISSUE TITLE
 Argument 1 passed to Twig_Function::__construct()

### ISSUE THREAD

**Issue by augustoprogramador** [twigphp/Twig#2453]
How can i fix this? Please!
Thank you

**Comment by xabbuh** [comment]
If you want to get help by someone you need to provide more information. What is the complete error message? Which Twig version do you use? Which code is causing this issue?

**Comment by augustoprogramador** [comment]
Sorry... I already solve this problem.. Now i'm trying to fix another, haha. But thanks for answering me.
I'll ask correctly next time =)

**Comment by xabbuh** [comment]
Can you then close here? :)

**Comment by augustoprogramador** [comment]
Yeah ^_^". Sorry, again...
