### ISSUE TITLE
Unable to pass an array as argument of a macro

### ISSUE THREAD

**Issue by mahono** [twigphp/Twig#2458]
Hi, I tried to pass an array as argument to a macro.

Neither `{{ foo.my_macro(['foo', 'bar']) }}` nor `{{ foo.my_macro({ 'foo': 'bar' }) }}` seem to be supported. I get this error:

> „An exception has been thrown during the rendering of a template ("Notice: Array to string conversion").“

Seems to be a problem with output escaping or so (see attached screenshot).
![bildschirmfoto 2017-04-26 um 14 47 03](https://cloud.githubusercontent.com/assets/145898/25435191/85337ce6-2a8f-11e7-876f-5c620722d812.png)
I'm using Twig v1.33.0

I'm not sure about it.. is it a bug or a feature?

**Comment by stof** [comment]
please show us the implementation of your macro too

**Comment by mahono** [comment]
Nevermind.. Problem sits between keyboard an chair.

I tried something like `{% if label.length is defined %}` to check if label is an array which couldn't work. The else did `{{ label }}` with label being an array which caused the error.

I tried `{% if label[0] is defined %}` to check if label is an array which is working perfectly.

Closing the issue. Sorry.

**Comment by mahono** [comment]
`{% if label is iterable %}` seems even better
