### ISSUE TITLE
User Deprecated: The Twig_TokenParser_Include class is considered final. You should not extend it from Twig_TokenParser_Embed

### ISSUE THREAD

**Issue by limitstudios** [twigphp/Twig#2459]
I currently get the following deprecated message in Symfony 3.3-DEV with Twig:

```
User Deprecated: The Twig_TokenParser_Include class is considered final. It may change without further notice as of its next major version. You should not extend it from Twig_TokenParser_Embed.
```

Also related https://github.com/symfony/symfony/issues/22533

**Comment by fabpot** [comment]
fixed in a083db55

**Comment by MetalArend** [comment]
Can this also be merged into the ^1 branch?

**Comment by Oliboy50** [comment]
@fabpot please, could you merge https://github.com/twigphp/Twig/commit/a083db55c242ed30451467c802633cddbad198ed into the `1.x` branch too as it's the only `User Deprecated` error I have in my symfony 3.3 project (and I currently don't have enough time to migrate to Twig 2.x)

**Comment by fabpot** [comment]
There is no `@final` annotation on this class in 1.x anymore. It was removed in a083db5.
