### ISSUE TITLE
Memory leak if twig works as a deamon

### ISSUE THREAD

**Issue by bkielbasa** [twigphp/Twig#2463]
I have a daemon which uses Twig to render templates. I noticed that after few days the process uses a lot of memory.

It renders different template every time. IMO the problem is in Twig_Environment::loadTemplate method. In my case, it creates different temporary class every time. The class is removed when it finishes but the signature of the class still exists in the memory. If it happens about 1-2 million times every hour it may make difference :)

 * My first proposal is to change the way it works to serialise data and save this data to cache instead the whole class. There will be no need to create a new class every time.
 * The second, use anonymous classes but in this case I am not sure if I remove the instance of the class from memory, the signature of it will be removed too.

I know it will be a huge change. For now I solved the problem with restarting the service every time it reaches the memory limit.

**Comment by jvasseur** [comment]
Anonymous classes don't solve the problem, they stay in memory forever the same way standard class stay.

The serialize solution can't work, the compiled twig templates are actual php code that need to be created for the template to be rendered.

As a workaround for you problem you could start a different process that render your template and exit after the rendering.

**Comment by bkielbasa** [comment]
What do you suggest as a solution? I restart the service so I have a workaround for it but the memory leak still exists.

**Comment by stof** [comment]
@bkielbasa the solution is to avoid rendering millions of different templates in the same long-running process. Twig is not built to support this case without the drawback of defining new PHP classes eating memory.
And rebuilding Twig from scratch to support this use case is unlikely to happen, as it requires rewriting Twig entirely, and the current architecture using a PHP class as target of the template compilation was chosen for performance reason (and flexibility in what Twig can support).

**Comment by lyrixx** [comment]
May I ask how can you have  1-2 million templates ?

**Comment by bkielbasa** [comment]
@lyrixx  I have email campaigns sent to many subscribers. Some campaigns are sent to more than 100 k subscribers or sometimes to more than 1M.
Every campaign has his template but I have to render each template for every subscriber separately because of personalization (the templates are dynamical).

**Comment by fabpot** [comment]
Even if you send an email to 1M subscribers, you probably have only one template, no? I don't understand why you would have 1 different template per email.

**Comment by stof** [comment]
@fabpot probably related to #2465
