### ISSUE TITLE
Let macros inherit certain variables from parent scope

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#2474]
It would be nice if it was possible to specify certain variables in the parent template context that should be automatically inherited by a macro, without needing to pass them in when calling the macro.

For example, going with PHP’s [`use` syntax](http://php.net/manual/en/functions.anonymous.php#example-165) for anonymous functions:

```twig
{% set foo = 'foo' %}

{% macro bar(baz) use foo %}
    {{ foo }}: {{ baz }}
{% endmacro %}

{% from _self import bar %}

{{ bar('a') }}
{{ bar('b') }}
{{ bar('c') }}
```

**Comment by stof** [comment]
that cannot work: the scope around the macro definition might never been executed at runtime (if you put the macro in a separate file). Macros are not closures. They are functions (which are defined at compile time, not at runtime)

**Comment by brandonkelly** [comment]
Ah makes sense. Thanks for the quick response!
