### ISSUE TITLE
Extending Twig Lexer

### ISSUE THREAD

**Issue by kiler129** [twigphp/Twig#2475]
I got pretty familiar with Twig internals and I see extending almost anything is easy, excluding lexer. I have a project which needs to support legacy format of templates and I'm planning to do a fluid migration to Twig. In order to do that I have to define new lexer tokens and going further add rest of the puzzle pieces.

I looked at `\Twig_Lexer` class and it seems very logical to me, except it cannot be easily extended. Currently I can extend `\Twig_Lexer`, override `tokenize()` method and parse my custom syntax before calling `\Twig_Lexer::tokenize()` (since unfortunately my old syntax conflicts with Twig one).
That approach should work, except I'm going through the template twice and actually I cannot reuse any parts of `\Twig_Lexer`.

What's the suggested approach for such scenario?

**Comment by robfrawley** [comment]
Just like in https://github.com/twigphp/Twig/issues/2476#issuecomment-302548781 you want to define a `\Twig_Extension` and use the available hooks for registering custom token parsers, node visitors, and operators. Here is your interface for doing such:

```php
<?php

/*
 * This file is part of Twig.
 *
 * (c) Fabien Potencier
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
abstract class Twig_Extension implements Twig_ExtensionInterface
{
    public function getTokenParsers()
    {
        return array();
    }

    public function getNodeVisitors()
    {
        return array();
    }

    public function getFilters()
    {
        return array();
    }

    public function getTests()
    {
        return array();
    }

    public function getFunctions()
    {
        return array();
    }

    public function getOperators()
    {
        return array();
    }
}
```

**Comment by fabpot** [comment]
Or you can create a preprocessor.

**Comment by kiler129** [comment]
@fabpot That's actually more sane solution - that way I can later on automatically convert legacy templates to new ones. Thank you for the suggestion.
