### ISSUE TITLE
Extending \Twig_Function

### ISSUE THREAD

**Issue by kiler129** [twigphp/Twig#2476]
I discovered `\Twig_Function` is marked with `@final` tag - does that mean you're planning to mark this class as `final` in next major release and extending from it is not recommended?
What's the recommended approach of creating new functions in a real application? Currently I planned to just extend `\Twig_Function` and provide custom `getCallable()` and `getName()`. This allows me to create a Twig function which is in reality an entry point to a class generating some sort of a content.

**Comment by stof** [comment]
you don't need to extend this object. `Twig_SimpleFunction` in Twig 1.x and 2.x (and `Twig_Function` in 2.x, which is just the same) are taking the name and callable as arguments. The way to provide custom functions is to instantiate these classes directly with callables (generally happening inside a Twig extension)

**Comment by kiler129** [comment]
So, the recommended way of enclosing more complicated function will be to do something like:

```php
<?php

class FooFunction {
    public function getName(): string {
        return 'foo';
    }
    
    public function execute(): string {
        return 'Hello foo!';
    }
}
```

and than creating factory which basically does:

```php
<?php

$twigEnv = ...;
$function = new FooFunction();
$twigFunc = new Twig_Function($function->getName(), [$function, 'execute']);
$twigEnv->addFunction($twigFunc);
```

My functions require more code than I'm willing to put into inline anonymous function, that's why I wanted to get a class which represents function in Twig. Probably I'm missing something, but for me natural way will be to use `Twig_Function` when I'm doing something simple and I can just specify callback and implementing some sort of interface for function if I need something more advanced. However Twig core typehints for `Twig_Function` everywhere and the class as I said before was marked as `@final`.

**Comment by stof** [comment]
@kiler129 what most packages are doing is to use Twig extensions. They can then implement the logic of the function as a method in their extension. And then, the registration of the Twig_Function itself is handled by the extension. This keeps the knowledge of what the function options are in the same place than the function implementation.

I'm almost sure I *never* used `$twigEnv->addFunction` in any of my projects (I started using Twig in 2010 when it was not even at 1.0 yet). I always register them through extensions (and this is how Twig itself registers its own functions btw)

**Comment by kiler129** [comment]
@stof: Thank you for the time you put to explain that. I've got the `addFunction()` idea from [Twig 2.0 docs](https://twig.sensiolabs.org/doc/2.x/advanced.html), but I have to admin I never looked into Twig core extension.

I looked into `Core.php` file inside of the Twig source code and also a little bit into Twig bridge available in Symfony. While core extension of Twig is a little large piece of code, utilizing global functions, Symfony bridge gave me an idea how functions should be organized.

Correct me if I'm wrong, but it seems that extension class should just act like a proxy for the actual implementation of a function if the logic is more complicate or if the function role is simple (e.g. getting random element from array) the code implementing such functionality should be implemented within the extension itself.
It's natural for me to separate each of the functions I'm adding to Twig into separate classes to archive nice modular design.

**Comment by robfrawley** [comment]
The extension point @stof is talking about is `\Twig_Extension`, which allows you to register functions, filters, token parsers, node visitors, operators, and tests all within the same extension definition. For example, here is an extension I recently wrote for transforming markdown:

```php
<?php

namespace Rf\AppBundle\Templating;

use SR\Cocoa\Transformer\Markdown\MarkdownCacheableTransformer;

class MarkdownExtension extends \Twig_Extension
{
    /**
     * @var array
     */
    static private $environmentOptions = [
        'is_safe' => ['html'],
    ];

    /**
     * @var MarkdownCacheableTransformer
     */
    private $transformer;

    /**
     * @param MarkdownCacheableTransformer $transformer
     */
    public function __construct(MarkdownCacheableTransformer $transformer)
    {
        $this->transformer = $transformer->setExpiresAfter(new \DateInterval('P1D'));
    }

    /**
     * @return \Twig_Filter[]
     */
    public function getFilters(): array
    {
        return [
            new \Twig_Filter('markdown', function (string $string) {
                return $this->transformer->transform($string);
            }, static::$environmentOptions),
        ];
    }

    /**
     * @return \Twig_Function[]
     */
    public function getFunctions(): array
    {
        return [
            new \Twig_Function('markdown', function (string $string) {
                return $this->transformer->transform($string);
            }, static::$environmentOptions),
        ];
    }
}
```

It registers a filter and a function allowing either of the following calls in my Twig templates:

```twig
{{ content|markdown }}
{{ markdown(content) }}
```
