### ISSUE TITLE
let front developer find template easily

### ISSUE THREAD

**Issue by videni** [twigphp/Twig#2477]
Let any commands that include outer template into current one to  show templating hints in debug mode  , like import , include, so the front developer can find the related templates more easily. 

```
<!-- Start Template: SyliusAdminBundle:Crud:create.html.twig (Parent Template: SyliusAdminBundle::layout.html.twig) -->
<html>
//....
</html>
````

**Comment by fabpot** [comment]
Twig can be used for any kind of templates, not just HTML. So, that's not a feature that can be added in Twig core.
