### ISSUE TITLE
Since 1.33.1 Twig is creating cache files indefinitely

### ISSUE THREAD

**Issue by martinsik** [twigphp/Twig#2485]
I've encountered a very strange problem with Twig since 1.33.1 when it's creating new cache files over and over again on every request. I found out this only after depleting all available disk space on our server but the problem occurs also when I test the project locally (it's a Symfony3 website). I switched back to 1.33.0 and everyting is fine.

The following shows what happens:

I install `twig/twig` 1.33.1 (or 1.33.2, it's the same):

```
$ composer require twig/twig 1.33.1
$ rm -rf app/cache/prod/
```

Make 500 requests using `ab` (https://httpd.apache.org/docs/2.4/programs/ab.html) on my local nginx server and check the size of my cache and count twig cache files:

```
$ ab -c 5 -n 500 http://project.loc:8000/
$ du -sh app/cache/prod/twig/
 61M	app/cache/prod/twig/
$ find app/cache/prod/twig/ -type f | wc -l
   13504
```

So after 500 requests the twig cache is over 61MB with 13504 files (The URL runs `app.php` of a Symfony3 project in production environment).

When I dump one of the folders there are many files with the same file size:

```
$ ll app/cache/prod/twig//9d:
total 456
-rw-r--r--  1 martin  staff  2771 24 May 20:39 9d02037e280f436b233956f5cd49f271991bfd7fcc1cbbadbeab4f66f3d0e4aa.php
-rw-r--r--  1 martin  staff  2634 24 May 20:40 9d029239ff4aded39f1e49128f3a92275512669767b49e2d30244402bd30b25c.php
-rw-r--r--  1 martin  staff  2771 24 May 20:40 9d03e74bfe8dd4177f3b64b2a229d820e8939350ac1e75d445e46b1020762bd9.php
-rw-r--r--  1 martin  staff  3667 24 May 20:39 9d08fbd8ad3112bfc2b2fb9f6c422fb674c8909cb6f2c25189fa0ff88c54bcf0.php
-rw-r--r--  1 martin  staff  2613 24 May 20:39 9d0abec32d25579deb62ba96aeb5c4edd4eea71cb2017fe67be015022cf60839.php
-rw-r--r--  1 martin  staff  1596 24 May 20:40 9d114e72103f8996c5f25cae9c2d43fe7e108f5481166f717a29efb1c6dd6b6d.php
-rw-r--r--  1 martin  staff  2120 24 May 20:41 9d16ea7d798af3ea3200967ff99fdae5aaa2eab386f9fc1ba70ffe3c3c82b7ca.php
-rw-r--r--  1 martin  staff  1594 24 May 20:40 9d19977393704a9fffb4aae8f3011cd8b821ebf799471d24ea946f01b0778360.php
-rw-r--r--  1 martin  staff  2858 24 May 20:39 9d1b86d3b3bf001112a11e45e34b65929b63bb6248b98dc13717684c8491d12b.php
-rw-r--r--  1 martin  staff  1911 24 May 20:40 9d1dde68800dea09742eed4e6cdfcfcbcade1da396537bb25a90015aaa0fde88.php
-rw-r--r--  1 martin  staff  2120 24 May 20:40 9d22488da47038e8286eb61a79d34d1067781fc5d591cfb063795a6c8304abdf.php
-rw-r--r--  1 martin  staff  3667 24 May 20:40 9d23cb2b8ed9655384870044da8e1f9fb5439e1a3559054cac3a95edb5956fd2.php
-rw-r--r--  1 martin  staff  2120 24 May 20:39 9d24c030ddf37f2bb1401e45364447af9e138171d7f5c2bc1a0c47e0fd552ce3.php
-rw-r--r--  1 martin  staff  2120 24 May 20:40 9d28c79d79fe5426a92b5cbc65b93cced79f5b21521964b0a611cd51ec3ccfbb.php
-rw-r--r--  1 martin  staff  3667 24 May 20:40 9d4054c0f5265fb5342ebbc0d1d3d3c9c5d8534a816ab0a2a2ace0aef6de49ab.php
-rw-r--r--  1 martin  staff  1911 24 May 20:39 9d482a0371a73616d91dcf2b9a0596c4f94030b00daea97c6aa0bb66fcce8675.php
-rw-r--r--  1 martin  staff  2613 24 May 20:40 9d4d62c4344fe6a831863b8a9c3b644517158624d8b662c68eef8f4f7961587a.php
-rw-r--r--  1 martin  staff  2120 24 May 20:41 9d5167ab7fccbadf4e94c760aa57cf24e43ae2441e4baf003a1586b8470fa867.php
-rw-r--r--  1 martin  staff  2120 24 May 20:40 9d5b7316426e70d3f068da95079004f657e795e9c1a06eece36dabbeaad63ffb.php
-rw-r--r--  1 martin  staff  2613 24 May 20:40 9d6e4710fed5869d795d5f54090d7d9b71830955d9a9f4725b37cd14ba0a8d0c.php
-rw-r--r--  1 martin  staff  2120 24 May 20:40 9d74ce6d0ee426acc741ad183a29040cc2bd819141abffd31afcfdaad421711c.php
-rw-r--r--  1 martin  staff  2634 24 May 20:41 9d7d6c590d2e680cf11ff0e0bffeb7dcf0cf4d01b57932ac8140ff29f9c13ec3.php
-rw-r--r--  1 martin  staff  7259 24 May 20:39 9d8b8f139e6ce1b75134a5d21470a1f899600b5980f4c3203aa4b266f2d05bff.php
-rw-r--r--  1 martin  staff  3667 24 May 20:39 9d8d76ffc1de9220f1628cdfb6c8cd84af5fa41f4c31d872d2276020740e8d98.php
-rw-r--r--  1 martin  staff  5463 24 May 20:39 9d942212b8bf9b447c7566728c6bfc022aab0162b7960731a6aca647974f7949.php
-rw-r--r--  1 martin  staff  7259 24 May 20:40 9d98bd3a5cf7df6beb171204918ba46b82dcd48c6570ae545f14317f84860539.php
-rw-r--r--  1 martin  staff  2120 24 May 20:39 9d991a3791c716f29513f4326f1066e6bf04f00bb719c406d0cdf5834664dd71.php
-rw-r--r--  1 martin  staff  7259 24 May 20:39 9d9fea42d6683d72929d3721e4c3c089d740198265011e25b6ddba7d1b88c8a4.php
-rw-r--r--  1 martin  staff  3289 24 May 20:39 9daa577517ac2b3d395734f48b937281d1e593dff7946b902a5f3303b70829ac.php
-rw-r--r--  1 martin  staff  2120 24 May 20:40 9dadeea98b45a3da188f697859d3818054853d06ae900eab9185b94c5c7d0fe7.php
```

If I do exactly the same with 1.33.0 it works as should:

```
$ composer require twig/twig 1.33.0
...
Loading composer repositories with package information
Updating dependencies (including require-dev)                 
Package operations: 0 installs, 1 update, 0 removals
  - Updating twig/twig (v1.33.1 => v1.33.0): Loading from cache
Writing lock file
...
$ rm -rf app/cache/prod/twig/
$ ab -c 5 -n 500 http://project.loc:8000/
$ du -sh app/cache/prod/twig/
128K	app/cache/prod/twig/
$ find app/cache/prod/twig/ -type f | wc -l
      21
```
Now after 500 requests there are only 21 files with total size of 128K.

This is the complete dump of the cache directory structure:

```
$ find app/cache/prod/twig/ | xargs ls -l
-rw-r--r--  1 martin  staff   1594 24 May 20:46 app/cache/prod/twig//00/00281cc1d2e6280c4b3c505736e7d629868d2282033017b43b75946634c9a616.php
-rw-r--r--  1 martin  staff   2613 24 May 20:46 app/cache/prod/twig//05/053bd4d46fe6b2235513ac532ba961abe3a0ac036d0dd577226ee3b1bdfed540.php
-rw-r--r--  1 martin  staff   2120 24 May 20:46 app/cache/prod/twig//06/067516efcd3aa1fb81a6bbc10e1690dd60296ad087dbd9b2ef546cc7f66383f7.php
-rw-r--r--  1 martin  staff   3845 24 May 20:46 app/cache/prod/twig//12/1256920a278fe56ca8dba0385e9ec1e53e39cde157c703e62abe2deaa317b213.php
-rw-r--r--  1 martin  staff   2771 24 May 20:46 app/cache/prod/twig//14/14b2cb9e0ae6a2898b7b7903f59cbf5fae62bbaef7d8a0a14ca458d126fec5eb.php
-rw-r--r--  1 martin  staff   4881 24 May 20:46 app/cache/prod/twig//25/2508d95f311cf337fae5262b9c3d89cec7a8b044cc16a91b63732d2ac2a531fc.php
-rw-r--r--  1 martin  staff   7231 24 May 20:46 app/cache/prod/twig//27/272e577a383dd72cc53fbc0687b5d9d896881b16c7fabaae79d86c86adad382e.php
-rw-r--r--  1 martin  staff   3667 24 May 20:46 app/cache/prod/twig//28/28449e2b4351e827f42ffb08885de20a68e7ae978dbdc0df80d85de475ebc957.php
-rw-r--r--  1 martin  staff   2021 24 May 20:46 app/cache/prod/twig//39/399e48bd463dbef2642117adec145bfa3f10ef00dd4f21ca48628818a29707bf.php
-rw-r--r--  1 martin  staff   1911 24 May 20:46 app/cache/prod/twig//82/823f3f7287b718f1c7af04cfdf90968a390130c35fdd4fd341db153bb934ad32.php
-rw-r--r--  1 martin  staff   7259 24 May 20:46 app/cache/prod/twig//85/851a5a50cf876e4ec898f17b1959fc07f96bccf6e3c2b8154117a37c19aa1119.php
-rw-r--r--  1 martin  staff   1596 24 May 20:46 app/cache/prod/twig//91/9106c9594f42c3df5956d0b8eaf8a81200ccd4af32e406c27d97eeebe1480d49.php
-rw-r--r--  1 martin  staff   1594 24 May 20:46 app/cache/prod/twig//b2/b21f252a53334499699fd0e814c62ea89c0592dde046856e7e4b81e0eee49a92.php
-rw-r--r--  1 martin  staff   1911 24 May 20:46 app/cache/prod/twig//b9/b929b42914ad38a931d2e62881e031de945ed50f85c19a4ecce855e2cc5bb0ed.php
-rw-r--r--  1 martin  staff   7994 24 May 20:46 app/cache/prod/twig//c7/c78043533de7590af10ab2992ef6466912a9bd03b49455cb2c391a06ca348f61.php
-rw-r--r--  1 martin  staff   3289 24 May 20:46 app/cache/prod/twig//c8/c82567022c7813e3a944a84c9bc5de008f7dcdcb851b40a8741ee865d7e20c74.php
-rw-r--r--  1 martin  staff  26970 24 May 20:46 app/cache/prod/twig//cc/ccb1b54b8b1e849e30cda73da85b1f80a2752f346bfe2a9356c0d381555005c1.php
-rw-r--r--  1 martin  staff   2634 24 May 20:46 app/cache/prod/twig//cf/cf54e20a88cde7ece0437b36be03a1813bb7722605baaa70c8b62a2ba4d56d5e.php
-rw-r--r--  1 martin  staff   2766 24 May 20:46 app/cache/prod/twig//d6/d6c6f488b731cdb911d544ab4f72016e89cf3c27f103faaf7ee3219fd1593788.php
-rw-r--r--  1 martin  staff   5463 24 May 20:46 app/cache/prod/twig//fc/fcb9e833df6d95c8cb77f8274a69c678c1608847e6efcd87f9106e129abea8e0.php
-rw-r--r--  1 martin  staff   2858 24 May 20:46 app/cache/prod/twig//ff/fff412ffb17a05e3d3d16e19d400321588be912c7ed34b7383fab3799fb46e69.php
```

Unfortunately, I wasn't able to reproduce this in a separate demo project.

What I listed here is from an internal company project where for obvious reasons I can't give you access. It thought it had something to do with using custom filters but as I said I wasn't able to reproduce it. Hopefully, you have better knowledge what has changed in recent versions than me.

**Comment by javiereguiluz** [comment]
A while ago we changed how the cache key for templates is generated. Maybe there's a problem that makes the same template have a different key because of some reason. This is the specific PR: https://github.com/twigphp/Twig/pull/2144/files  Maybe you can check why the cache key is different every time for the same template.

**Comment by martinsik** [comment]
I went commit by commit since 1.3.0 and the problem first appears in [`da82b41ac2c3e9a341e85ee50419c4758d715211`](https://github.com/twigphp/Twig/commit/da82b41ac2c3e9a341e85ee50419c4758d715211) (which is not in the change log btw). This is surprising because I don't think I'm using `Twig_Loader_Array`.

Output from `php app/console debug:container`:

```
twig                                                                      Twig_Environment                                                                            
twig.controller.exception                                                 Symfony\Bundle\TwigBundle\Controller\ExceptionController                                    
twig.controller.preview_error                                             Symfony\Bundle\TwigBundle\Controller\PreviewErrorController                                 
twig.exception_listener                                                   Symfony\Component\HttpKernel\EventListener\ExceptionListener                                
twig.loader                                                               Symfony\Bundle\TwigBundle\Loader\FilesystemLoader                                           
twig.profile                                                              Twig_Profiler_Profile                                                                       
twig.translation.extractor                                                Symfony\Bridge\Twig\Translation\TwigExtractor      
```

@dave-newson

**Comment by dave-newson** [comment]
@martinsik thanks for walking the commits, and sorry this has caused you problems.

If your production code is using Twig_Loader_Array then I can totally understand this code causing exactly this kind of problem.

I added microtime to uniquify the template names, as in the test suite the Array Loader behaviour wasn't able to correctly create two different template files if their name was identical (or something like this, my memory is hazy). Obviously every call will generate a new template every time using this code, hence your bug.

I felt this was hairy, but because the top of the file says 
```This loader should only be used for unit testing.```
We thougt we could get away with it.

I'll have a think and see if there's another good way to solve the same problem more gracefully in the Array Loader, but from what I remember there's not much available to work with. Either way, it would be good if others don't trip over this in future.

In the mean time, would you mind xdebugging or `debug_backtrace` from within Array Loader and providing the call stack trace? I'd really like to understand where it's getting included in your code.

Thanks!

**Comment by robfrawley** [comment]
Regardless of the file note that `ArrayLoader` should only be used for unit testing, it **can** be useful outside of this singular constraint, and it would be great if it didn't behave the way this commit changes it to.

**Comment by dave-newson** [comment]
Ok, so I've just run my eyes over it again, and I'm not seeing any obvious ways this change could influence the file cache.

The only functional change is this line:
https://github.com/twigphp/Twig/commit/da82b41ac2c3e9a341e85ee50419c4758d715211#diff-e1197bc1ca3ff0b159d83705c00d95ecR83
The Blackfire.php change is related to microtime() occasionally providing an int and not a float, so the change forces a float-as-a-string.
All other lines are amendments to unit tests. 

The change on line 83 merely prefixes the CacheKey with the filename. 
This change was made because ArrayLoader used to only use the *content* of a source file to determine if the generated code had already been cached.  Because of this it was possible for two files with the same content - but not the same extension - to be cached as one file. This led to one of those templates not having the correct code.  
The change to include the filename makes the behaviour mimic that of `Twig_Loader_Filesystem`.

I don't believe there's any reason you can't use the `Twig_Loader_Array` class outside of unit tests, but you'll miss out on all the file caching, which means using it will be very expensive unless you make your own cache mechanism totally detached from twig.

That said, if someone **did** use this class, and provided a **unique key** every time, **and** implemented their own file caching.. you could end up here.

I'd really like to check out the stack trace says, otherwise we're too in the dark as to what's happening.

**Comment by dave-newson** [comment]
@martinsik One more idea for you:

Check out the latest code (1.33.2), go to `lib/Twig/Loader/Array.php` and modify the line back to:
```return $this->templates[$name];```

There's no functional issue with doing this outside of one specific edge case, so it's totally OK to do.
Take that for a spin and see if you still get the same duplication.

**Comment by martinsik** [comment]
@dave-newson I went through it again and the problem appears to be in using `createTemplate()` method because I'm loading templates from database.

So I thought I'm using just `Twig_Loader_Filesystem` but in fact when calling `createTemplate()` it uses `Twig_Loader_Array` underneath. https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L494-L497

The stack trace looks like this:
```
#0  Twig_Loader_Array->getCacheKey() called at [/path/to/project/vendor/twig/twig/lib/Twig/Loader/Chain.php:123]
#1  Twig_Loader_Chain->getCacheKey() called at [/path/to/project/app/cache/dev/classes.php:3094]
#2  Twig_Environment->getTemplateClass() called at [/path/to/project/app/cache/dev/classes.php:3122]
#3  Twig_Environment->loadTemplate() called at [/path/to/project/app/cache/dev/classes.php:3174]
#4  Twig_Environment->createTemplate() called at [/path/to/project/.../MyCustomComponent.php:34]
#5  MyCustomComponent->render() called at [/path/to/project/MyCustomView.php:31]
```

The `$name` was random every time i called `createTemplate()` because it's generated as:

    $name = sprintf('__string_template__%s', hash('sha256', uniqid(mt_rand(), true), false));

https://github.com/twigphp/Twig/blob/da82b41ac2c3e9a341e85ee50419c4758d715211/lib/Twig/Environment.php#L492

Then when the `$name` is part of the cache key `return $name.':'.$this->templates[$name];` it creates a new cache file every time I use it.

However, this appeas to be already fixed in [`5e190f538c5c328c7473a5cfd3b7cd95`](https://github.com/twigphp/Twig/commit/a7c8b0827018437de2a93ea9fe8211c080dc1bd1#diff-5e190f538c5c328c7473a5cfd3b7cd95) and should be part of `1.34.2` release.

**Comment by martinsik** [comment]
Code to reproduce is for example this:
```
$ composer require twig/twig 1.33.1
```

```
// index.php
require_once 'vendor/autoload.php';

$loader = new Twig_Loader_Filesystem('.');
$twig = new Twig_Environment($loader, array(
    'cache' => __DIR__ . '/cache',
));

echo $twig->createTemplate('<div>{{ title }}</div>')->render(['title' => 'My Title']);
```

**Comment by martinsik** [comment]
I can confirm that `1.34.2` work as should and doesn't generate too many files any more.

**Comment by stof** [comment]
OK, then please close this issue

**Comment by martinsik** [comment]
Maybe it's not a bad idea to remove `1.33.1` and `1.33.2` versions from composer too because somebody might install them unintentionally.

**Comment by stof** [comment]
@martinsik the only way to do that is to delete the tag entirely. and this is a pain, as fetching from any fork containing the tag would re-add it in the local repo of the maintainer, which will then re-add it in the main repo on the next push. Deleting Git tags is not meant to be an easy thing

**Comment by WilliamStam** [comment]
so i ran into this issue on 3.0.0-DEV

`createTemplate` forces a new has hence name. `twig_template_from_string` was removed so we stuck using `createTemplate` with cache.. you are going to have a really bad day with this

    $name = sprintf('__string_template__%s', hash('sha256', uniqid(mt_rand(), true), false)); 

the documentation https://twig.symfony.com/doc/2.x/recipes.html says to use 

    $template = $twig->createTemplate('hello {{ name }}');
    echo $template->render(array('name' => 'Fabien'));

so this is definitely not "closed"
