### ISSUE TITLE
Can't implement i18n

### ISSUE THREAD

**Issue by thingNumber1** [twigphp/Twig#2487]
_Note:_ This issue probably is not about a bug or anything. I just can't implement i18n and I can't find issue. Also, I asked in stackoverflow but I have no answer.

I am learning Twig and I am trying to implement the I18n extention (in a test project that probably is going to be the base of my next real project) but things does not seems to work. I don't really know where the problem is, so I'll paste here my main code for you to see if you find where is the issue (also, you can see or download all the codes from https://github.com/thingNumber1/twig-learning if you need it - You may need to update composer in the model folder to install twig):

**Index.php**

	<?php

	define('LANG', 'es-419');
	//define('LANG', 'en-us');
	
	
	require_once 'model/vendor/autoload.php';
	
	
	// Set language to French
	putenv('LC_ALL=' . LANG);
	setlocale(LC_ALL, LANG);
	
	$text_domain = 'multilingual_twig';
	// Specify the location of the translation tables
	bindtextdomain($text_domain, 'includes/locale');
	bind_textdomain_codeset($text_domain, 'UTF-8');
	// Choose domain
	textdomain($text_domain);
	// Twig
	$loader = new Twig_Loader_Filesystem('view/template');
	$twig = new Twig_Environment($loader, array(
		'cache' => 'view/template/compilation_cache',
		'auto_reload' => true
	));
	// Extensions
	$twig->addExtension(new Twig_Extensions_Extension_Text()); // Text (Truncate AND Wordwrap)
	$twig->addExtension(new Twig_Extensions_Extension_I18n()); // i18n (trans)
	echo $twig->render('section/index.html', array('name' => 'Fabien'));

**Comment by stof** [comment]
the issue is that your translation file provides a translation for `This is my title.`, but the template wants one for ` This is my title. ` (note the spaces before and after)
