### ISSUE TITLE
`format` filter samples cause Notice

### ISSUE THREAD

**Issue by koflerdavid** [twigphp/Twig#2489]
Hello,

today I noticed that one of the examples of the `filter` function causes a notice:
```twig
{{ -9800.333|number_format(2, '.', ',') }} {# outputs : -9 #}
{{ (-9800.333)|number_format(2, '.', ',') }} {# outputs : -9.800,33 #}
```

The first line causes a notice to be thrown: "Notice: A non well formed numeric value encountered". 

I realize that this works as advertised, but IMHO it should also be indicated that it will cause a Notice. The example will only output `9` then if `E_NOTICE` is not set, e.g., in production mode.

What do you think? I would have no problem at all with keeping this behaviour since it aids in debugging, but it should be documented.

Cheers

**Comment by fabpot** [comment]
This is because of operator precedence. The second one is the only correct one. If you have a look at the closed issues, you will find discussion about this issue. Unfortunately, we cannot fix it as it would introduce a big BC break.
