### ISSUE TITLE
IntegrationTestCase does not support runtime loaders

### ISSUE THREAD

**Issue by emodric** [twigphp/Twig#2492]
As far as I can see, it is not possible to write integration tests for Twig extensions using `Twig_Test_IntegrationTestCase` because the class does not support adding runtime loaders.

Is there another way to write tests for extensions that use runtime loader?

**Comment by stof** [comment]
We should add a new protected method allowing to provide runtime loaders, similar to the way we provide extensions. What do you think @fabpot ?

**Comment by fabpot** [comment]
Sure, makes sense to me. @emodric Would you like to propose a pull request for version 1.x?

**Comment by emodric** [comment]
@fabpot Done in #2509
