### ISSUE TITLE
Duplicate class_alias causing `Cannot declare class Twig\TwigFilter` error

### ISSUE THREAD

**Issue by robfrawley** [twigphp/Twig#2499]
This bug is against the `2.x` branch, versus the similar bug #2495 against `1.x`.

---

@nicolas-grekas With the merged of #2486, the test suite for `liip/imagine-bundle` began [throwing a PHP error](https://travis-ci.org/liip/LiipImagineBundle/jobs/238667705#L373) when defining a [custom extension that returns a single Twig filter](https://github.com/liip/LiipImagineBundle/blob/1.0/Templating/ImagineExtension.php#L39) (nothing special there) with the following message.

> Cannot declare class Twig\TwigFilter, because the name is already in use

We are referencing the `Twig_SimpleFilter` class name, but I can confirm using the new namespaced `Twig\TwigFilter` class name also causes the same error. Downgrading to `1.x-dev` *fixes the issue* so it appears only the `2.x` branch contains this problem.

---

Removing the following line from `lib/Twig/SimpleFilter.php` or `lib/Twig/Filter.php` *fixes this issue*.

```php
class_alias('Twig_[Simple]Filter', 'Twig\TwigFilter', false);
```

Based on a cursory examination, it appears both [Twig/SimpleFilter.php:23](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/SimpleFilter.php#L23) and [Twig/Filter.php:142](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Filter.php#L142) declare an alias of the name `Twig\TwigFilter`. Since one includes the other, they cannot do this, AFAIK, without a `class_exists` check or another mechanism in place to ensure `Twig\TwigFilter` isn't aliases twice.

Regarding the #2497, the fix for #2495 that changes as `require` statements to `require_once`, I tryed doing so at the beginning of `Twig_SimpleFilter.php` but this does not resolve the issue, as there are still two duplicate aliases.

This error occurs on Travis and locally on two different machines, so it's unlikely opcache or another PHP or environment issue has any bearing. I do not have the C extension installed in any of these environments and it occurs on PHP 7.0 and 7.1 on all Linux systems (no access to others). If you need additional details, please advise.

---

**To reproduce this issue** (assuming you are using a `twig/twig@2.x` compatible environment, as `1.x` will be pulled in if you are not and this issue only exists on `2.x`)

```bash
git clone https://github.com/liip/LiipImagineBundle.git
cd LiipImagineBundle
composer update
bin/phpunit Tests/Templating/ImagineExtensionTest.php
```

**Comment by nicolas-grekas** [comment]
See #2499

**Comment by robfrawley** [comment]
#2500 fixes the issue; thanks.
