### ISSUE TITLE
 Cannot redeclare class Twig_Node

### ISSUE THREAD

**Issue by anacona16** [twigphp/Twig#2503]
I'm getting this error after upgrade from Symfony 3.3.0 to Symfony 3.3.1

```
 (1/1) FatalErrorException

Compile Error: Cannot redeclare class Twig_Node
in classes.php (line 21780)
```
Here the versions:

```
symfony/symfony                               v3.3.1             The Symfony PHP framework
twig/extensions                               v1.5.0             Common additional features for Twig that do not directly belong in core
twig/twig                                     v1.34.1            Twig, the flexible, fast, and secure template language for PHP

```

I cleared cache, I reinstalled all vendors, I deleted the bootstrap.app.cache file, but the error still exits.

**Comment by anacona16** [comment]
I executed 
```
opcache_reset();
```

And everything is ok now.

**Comment by anacona16** [comment]
-- Update

If I comment this line `$kernel->loadClassCache();` in web/app.php or web/app_dev.php it works.

**Comment by xabbuh** [comment]
Can you try Twig 1.34.2? I think this should be solved by #2502.

**Comment by gremo** [comment]
For me the only way to fix the problem was:

    "conflict": {
        "twig/twig": ">=1.34"
    }

**Comment by stof** [comment]
@gremo have you tried 1.34.2 ?

**Comment by gremo** [comment]
@stof yes and it doesn't work.

**Comment by xabbuh** [comment]
@gremo What is the exact error that you get?

**Comment by anacona16** [comment]
I updated to 

```
symfony/symfony                               v3.3.2             The Symfony PHP framework
twig/extensions                               v1.5.0             Common additional features for Twig that do not directly belong in core
twig/twig                                     v1.34.2            Twig, the flexible, fast, and secure template language for PHP
      
```

And isn't working.

**Comment by gremo** [comment]
@xabbuh same error

> Compile Error: Cannot redeclare class Twig_Node in classes.php (line 19636)

**Comment by GuigZ-** [comment]
Hey,

I've a same error before #2495 and now i've this.

I'm in symfony 2.8.

**Comment by nicolas-grekas** [comment]
Why is Twig_Node inlined in classes.php?
What is on line 19636 in this file?

**Comment by nicolas-grekas** [comment]
Can you share that file in a gist?

**Comment by GuigZ-** [comment]
Personnaly is just a declaration class.

**Comment by anacona16** [comment]
@nicolas-grekas here is the gist [https://gist.github.com/anacona16/747f13eb26fc2bdf98ef85691d656e3d#file-classes-php-cache-L21780](https://gist.github.com/anacona16/747f13eb26fc2bdf98ef85691d656e3d#file-classes-php-cache-L21780)

**Comment by nicolas-grekas** [comment]
Can you please check if #2507 fixes the issue for you?

**Comment by nicolas-grekas** [comment]
Allowed spotting https://github.com/sonata-project/SonataMediaBundle/pull/1261

**Comment by anacona16** [comment]
@nicolas-grekas It worked for me. Thanks

**Comment by GuigZ-** [comment]
It's ok for me too.

Thanks for your reactivity.
