### ISSUE TITLE
BC break? Argument for type-hint "Twig_Environment" points to a service of class "Twig\Environment"

### ISSUE THREAD

**Issue by craigh** [twigphp/Twig#2508]
on updating from Twig 1.33.2 to 1.34.3 I receive this error multiple time

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
PHP Fatal error:  Uncaught exception 'Matthias\SymfonyServiceDefinitionValidator\Exception\InvalidServiceDefinitionsException' with message 'Service definition validation errors (15):

my.favorite.service: Argument for type-hint "Twig_Environment" points to a service of class "Twig\Environment"

here are three 

    - twig.translation.extractor: Argument for type-hint "Twig_Environment" points to a service of class "Twig\Environment"
    - twig.controller.exception: Argument for type-hint "Twig_Environment" points to a service of class "Twig\Environment"
    - knp_menu.renderer.twig: Argument for type-hint "Twig_Environment" points to a service of class  "Twig\Environment"

also note that I updated symfony from 2.8.21 -> 2.8.22 at the same time

**Comment by nicolas-grekas** [comment]
That's a bug in Matthias\SymfonyServiceDefinitionValidator:
Twig_Environment and Twig\Environmenr are aliases from each other.
It looks like this validation engine does handle aliases.

**Comment by fabpot** [comment]
Closing as the bug is not in Twig itself. It should probably be reported on the repo providing Matthias\SymfonyServiceDefinitionValidator. Thanks.

**Comment by craigh** [comment]
Are you aware of other more compatible service validators?

**Comment by stof** [comment]
@craigh well, this library is generally well maintained. And class aliases are not that common, which is probably why this issue was not detected yet. I don't know of any other bundle implementing the same features
