### ISSUE TITLE
Compile Error: Cannot redeclare class Twig_Node after updating to v1.34.2

### ISSUE THREAD

**Issue by MlleDelphine** [twigphp/Twig#2510]
I ran a composer update. Everything worked well before.
Now, while I access to my app I get this error message : 

`FatalErrorException in classes.php line 5859: Compile Error: Cannot redeclare class Twig_Node`

My Twig configuration is simple as that :

```
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
```

Is there any syntaxe update I missed ?

**Comment by nicolas-grekas** [comment]
Please upgrade to 1.34.3

**Comment by MlleDelphine** [comment]
Ok perfect ! You saved my day, many thanks :)

**Comment by xabbuh** [comment]
@MlleDelphine Can you close here then? :)
