### ISSUE TITLE
hasBlock doesn't evaluate variables created in extended template

### ISSUE THREAD

**Issue by klinec** [twigphp/Twig#2517]
I'm getting this error `Variable "bodyTemplate" does not exist.` when calling `hasBlock('stylesheets')`.
I have 2 templates:
*users.html.twig*
```
{% extends '@App/layout_body.html.twig' %}

{% block body %}
...
{% endblock %}
```

*layout_body.html.twig*
```
{% set bodyTemplate = currentUser().isClientUser ? 'AppBundle::layout_client_body.html.twig' : 'AppBundle::layout_main_body.html.twig' %}

{% extends extend_layout_body is defined ? extend_layout_body : bodyTemplate %}
```

When I'm trying to check if  *users.html.twig* template has block *stylesheets* it throws the error `Variable "bodyTemplate" does not exist.`
```
$template = $this->get('twig')->load('users.html.twig');
if ($template->hasBlock('stylesheets')) {
...
}
```

There are 2 workouts how to fix it, but I think it's a bug.
1. add empty block *stylesheets* into *users.html.twig*
2. create inline condition in *layout_body.html.twig*
```
{% extends extend_layout_body is defined ? extend_layout_body : (currentUser().isClientUser ? 'AppBundle::layout_client_body.html.twig' : 'AppBundle::layout_main_body.html.twig') %}
```

**Comment by stof** [comment]
yeah, checking dynamic parents from outside the template cannot support context changes done inside the template, because this would require evaluating the template to know them.

**Comment by klinec** [comment]
ok, thanks
