### ISSUE TITLE
Incorrect documentation for Twig_Environment constructor auto_reload option (says 'autoreload')

### ISSUE THREAD

**Issue by dubaaron** [twigphp/Twig#2520]
In both 1.x and 2.x documentation, the option name to pass to the constructor is stated as 'autoreload', instead of the actual 'auto_reload'.  This can cause a bit of head banging and scratching until one notices the discrepancy with 'auto_reload' in other parts of the class documentation (or looks at the source code) and determines the correct spelling.

https://twig.sensiolabs.org/api/1.x/Twig_Environment.html#method___construct
https://twig.sensiolabs.org/api/2.x/Twig_Environment.html#method___construct

I would submit a pull request, but not sure where to update the documentation, as it's auto-generated.  It looks like the docblocks in the source code state it correctly on the current dev branch of 1.x and 2.x. 

(Of course, there are other ways to toggle auto-reloading; like using the dedicated methods to turn it on and off, but that might not be obvious to someone reading the docs for the constructor option parameters.)

![image](https://user-images.githubusercontent.com/2491006/27494986-73c1c61a-580d-11e7-8a9d-4756ff976761.png)

**Comment by apfelbox** [comment]
It seems that all underscores need to be escaped there, as they are automatically converted to italics because of Markdown rendering.

**Comment by dubaaron** [comment]
aha ... i thought that something like that might be the case, as I noticed the odd italicization, but I couldn't figure it out.  

Thank you very much!

Now, how does one go about escaping things in a docblock in such a way that the documentation auto-renderer?

I was going to try either putting a \ in front of underscores (which might look weird), or encapsulating those words in quotes (still might look weird, but maybe less so than underscores).

**Comment by dubaaron** [comment]
Update: This is an issue with Sami, the documentation generator, also authored by @fabpot . 

When generating the doc with Sami 4, it works fine, doesn't render italics when underscores occur in words.

But when generating the doc with Sami 3, we get the incorrect italics.  

So, apparently, Sami 3 is still being used to generate documentation for Twig.

I'm not sure how that doc build process is managed, but may not be open to a public pull request.  Still, needs fixing/updating at some point.

**Comment by SpacePossum** [comment]
The doc building process and publishing is indeed not open to the public, so all we can do is ping @fabpot to bring this to his attention :)
Well spotted and nicely tracked down :+1:

**Comment by stof** [comment]
@fabpot can you upgrade the Twig doc to use Sami 4, as it looks like the issue is solved there ?

**Comment by fabpot** [comment]
We are already using Sami 4 but an old version. Updated now and fixed.
