### ISSUE TITLE
accessing variables directly in template

### ISSUE THREAD

**Issue by saiballo** [twigphp/Twig#2523]
Hi all,

Is it possible to access php variables in twig template?

for example in my page.php I have

$name = 'myvalue';

and I want to access it in template with something like this:

{{ name }}

without passing it like:

echo $twig->render('index.html', array('name' => 'value'));

thank you

**Comment by stof** [comment]
no this is not possible. Twig cannot have access to local variables defined in your code, and does not try to access global variables (which would require knowing them when writing Twig itself anyway, unless doing some magic with `$GLOBALS` which we don't want)

**Comment by saiballo** [comment]
thank you for reply
