### ISSUE TITLE
PHPUnit class alias in tests/bootstrap.php confuses PHPStorm

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#2526]
In my project, PHPStorm complains about multiple class definitions for `PHPUnit_Framework_TestCase` because it detects the class alias added in `tests/bootstrap.php` in the Twig testsuite.
This breaks all autocompletion for PHPUnit methods for classes using `PHPUnit_Framework_TestCase` as parent in my project using Twig.

It would be great if Twig could avoid defining such alias (either using the `simple-phpunit` script from the bridge to avoid using PHPUnit 6 or switching to using the namespaced PHPUnit class), as done in Symfony for instance.

**Comment by tuliohmendes** [comment]
The same issue is happening here.

**Comment by tmli3b3rm4n** [comment]
Not a fan of any code that messes with my green checkmark.

**Comment by fabpot** [comment]
Now that we dropped support for PHP 5.2, that's indeed possible. See #2544.
