### ISSUE TITLE
Missing documentation for shorthand block emptying

### ISSUE THREAD

**Issue by shanecarmody** [twigphp/Twig#2527]
I noticed that on [the documentation page which describes the `block` function](https://twig.sensiolabs.org/doc/2.x/functions/block.html), there is no details about the shorthand way of emptying a block e.g.

`{% block title '' %}` 

instead of 

`{% block title %}{% endblock %}`

Is the shorthand way documented somewhere?

**Comment by ismael-miguel** [comment]
I believe that this is implied on https://twig.sensiolabs.org/doc/2.x/tags/extends.html#block-shortcuts

You can correct me if I'm wrong, but, I assume you could use any expression that outputs text there (even an empty string).

**Comment by shanecarmody** [comment]
@ismael-miguel thanks!
