### ISSUE TITLE
Why are some TokenParsers marked final?

### ISSUE THREAD

**Issue by mindfullsilence** [twigphp/Twig#2528]
It's so often that I want to extend the functionality of some of these tokens when creating my own and the majority of them are marked final. Why? I understand marking a lot of other classes in the library as final, but can't reason about why TokenParsers would be.

**Comment by stof** [comment]
Can you describe use cases where extending existing token parsers is actually useful ?

**Comment by mindfullsilence** [comment]
Not off the top of my head, but I know I've come across several times that I just want to insert functionality either before or after a tag is parsed, and extending as an aliased tag then calling parent::parse() would have made it really easy. That's a simple use case but there have been more complicated cases involving more advanced embed-like functionality and such.

However, ins't the question backwards? Shouldn't the question be "why _shouldn't_ we allow anyone to ever extend this class"? If it's something that isn't part of the core functionality, and is rather an extension itself of core functionality.

**Comment by fabpot** [comment]
The main reason is that core tags should behave consistently. If you are able to override them, it means that their usage might be different, their behavior might change and that makes support complex and can potentially break templates coming from third-party (think the Web Profiler of Symfony for instance).

If you have a need for tag similar to one in code, a little copy/paste is the way to go. That forces to use another tag name and that's a good thing.
