### ISSUE TITLE
Stacktrace without throw exception

### ISSUE THREAD

**Issue by EneasVVA** [twigphp/Twig#2529]
It would be interesting to have a variable or a function with the ability of printing the stacktrace in order to locate who calls to the active layout

**Comment by ismael-miguel** [comment]
You can use the [Profiler Extension](https://twig.symfony.com/doc/2.x/api.html#profiler-extension).

**Comment by fabpot** [comment]
Closing as this is not something that should be part of Twig, but more in the framework you are using.
