### ISSUE TITLE
Shorthand for passing variables to included templates?

### ISSUE THREAD

**Issue by cviebrock** [twigphp/Twig#2532]
I want to pass a subset of variables from one template to another.  Right now, I think the only way is for me to redefine them all:

```twig
{% include 'sometemplate.twig' with {
    'foo': foo,
    'bar': bar,
    'qua': qua
} only %}
```

It would be nice if there were a shorthand way of doing this, something along the lines of the way PHP's `compact` works.  I don't know what the syntax would look like but maybe:

```twig
{% include 'sometemplate.twig' with vars { foo, bar, qua } only %}
```

or (more typing):

```twig
{% include 'sometemplate.twig' with compact('foo', 'bar', 'qua') only %}
```

My goal is to be a bit more rigid in my templates in terms of the variables they use and expect.  Another option might be some kind of tag at the top of the template that defines the variables it uses (and drops all the others, or throws an error, or something configurable).  e.g.:

```twig
{% expect { foo, bar, qua } %}        // these vars must be present
{% expect { foo, bar, qua } only %}   // same, and all other vars are ignored
```

Is either or both of these options already possible?

**Comment by cviebrock** [comment]
I see this has been brought up before in #502 and #1019.

I'm not trying to beat a (dead?) horse and perhaps more notations isn't the solution as @fabpot suggests.  But this has to be such a common use-case that an "official" solution would be great.

**Comment by fabpot** [comment]
Introducing `compact` or `from_context` as I proposed in #1019 is not for core. We try to limit the amount of filter/tags/functions in core. I think that this addition does not belong to core.

As an aside, I like your `expect tag` :)

**Comment by cviebrock** [comment]
Thanks @fabpot.  I ended up writing a `compact` function that seems to be working just fine: https://gist.github.com/cviebrock/321494afffb2ca22d8705423951d2bf1

Working on `expect` as we speak. :)
