### ISSUE TITLE
Suggestion: make strict_variables true by default

### ISSUE THREAD

**Issue by codedokode** [twigphp/Twig#2537]
Currently `strict_variables` it is set to `false` by default: https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Environment.php#L92

But I think that having it set to `true` is better. I don't even see what are the use cases for `false` (except for compatibility for some broken legacy code). 

Motivation: 

- make templates behave more like PHP code that reports undefined variables by default
- make it easier to discover errors in templates when the developer mistyped or forgot to specify a variable ( [c2 wiki says the earlier defect is discovered the cheaper it is to fix](http://wiki.c2.com/?DiscoverDefectsEarly) )
- it will be easier to write tutorials for beginners so I won't have to mention that they should set `strict_variables` option before using Twig

If this suggestion is approved then I can make a pull request. If you don't like this suggestion then can you please explain the motivation for choosing the `false` default value?

If it breaks compatibility with some other project I suggest to plan adding this change to a newer release or maybe I can make a pull request with a fix to that project too.

**Comment by xabbuh** [comment]
Setting `strict_variables` to `false` makes sense in production. You probably don't want your page to deliver a 500 response just because one variable is missing in your template. I agree however that having this option turned on during development helps to spot mistakes. In Symfony, for example, we have different environments. In `dev` `strict_variables` is turned on to allow to easily spot these mistakes during development while in `prod` we don't want to serve error pages in these cases. I suggest to follow a similar approach in your own application.

**Comment by stof** [comment]
I suggest changing the default of the `strict_variables` option to reflect the debug mode when the user does not configure it explicitly. What do you think @fabpot ?

**Comment by codedokode** [comment]
@xabbuh I don't think that ignoring errors in production is good idea. For example, because of this some important information won't be displayed to the user and there won't be anything in error log. It would be better if the user saw that there is an error rather than saw inprecise information.

Also, a search engine can index the page with missing information (for example, an article page without content displayed). And this can hurt SEO ranking. But if there were an 503 error page, it would not index it and visit the page later. 

@stof I think that `debug` is another variable (it controls whether the template object can be dumped or something like this) and I think it is better to keep those two variables separate.

**Comment by codedokode** [comment]
Ignoring errors only leads to lower quality code. That is why I suggest to keep template engine default behaviour consistent with PHP interpreter behaviour that doesn't ignore mistyped variables.

**Comment by javiereguiluz** [comment]
@codedokode to give some context: most people in the Symfony community prefer to ignore those errors in production. [I recently proposed](https://github.com/symfony/symfony/issues/23532) to remove an option called `strict_requirements` which is similar to `strict_variables` and allows to generate wrong (and even empty) links, but the proposal was rejected.

**Comment by codedokode** [comment]
@javiereguiluz If that is Symfony policy then this variable can be set to `false` in Symfony code, for example somewhere in the Twig Bundle (though I don't like that idea anyway). Twig is often used without Symfony so it would make sence to have `true` as a default value.

I understand that there are use cases when it might make sence to hide errors (for example a  legacy low quality project, or a web agency that doesn't want the client to see the errors, or maybe a project that is short on resources so nobody would fix the errors anyway) but I don't think it should be the default. Let's adapt the best practices as default.

**Comment by ismael-miguel** [comment]
In my personal opinion, what @stof said makes sense. Setting it to reflect the value of the `debug` field makes sense.

As @xabbuh said, it makes no sense to break the entire website just because you missed a variable.
It's **always** better to have a partially functional website that still delivers the content to the client, than having one that jurk borks at every click and does nothing at all.

In production: hide errors and warning, to keep the website running.
In development: let it warn you of all the problems.

Makes sense?

**Comment by codedokode** [comment]
By the way, with `strict_variables` set to `false` undefined variables in templates are not reported at all, even as a warning. I think that is a problem too because developers might be unaware that some pages are displayed incorrectly. Should I create another issue for that or it can be discussed here as well? 

>  it makes no sense to break the entire website just because you missed a variable.

It breaks a single page, not the whole website. And I don't think it is a problem if developers are monitoring error logs and fix the errors (that is what I usually do with my projects). It might be undesirable in some use cases (for example when there is nobody to monitor logs and fix the bugs) but I don't think we should have it as a *default* setting. I think the default setting should be the one that follows the best practices and helps to write a high quality code without missing variables.

Also errros in templates can be dangerous. Imagine an Internet shop that will show a lower price because of error and the customer will demand that they sell an item for that price. Or imagine if the part of the page won't be displayed, search engines will index the incomplete page and over time it will hurt SEO rankings of the site.

Here is Martin Fowler's article about so called "fail fast" principle: https://martinfowler.com/ieeeSoftware/failFast.pdf . Let me quote the article:

> Some people recommend making your software robust by working around problems automatically. This results in the software “failing slowly.” The program continues working right after an error but fails in strange ways later on. 
> A system that fails fast does exactly the opposite: when a problem occurs, it fails immediately and visibly. Failing fast is a nonintuitive technique: “failing immediately and visibly” sounds like it would make your software more fragile, but it actually makes it more robust. Bugs are easier to find and fix, so fewer go into production.

I suggest we adhere to "fail fast" principle by default.

**Comment by ismael-miguel** [comment]
SEO rankings are fixable, with time.
Partial content is still way better than no content or an error message.

Store prices should be handled by PHP or by your prefered Database Engine.
Twig is a template engine: It's just to display data.
Just the face of the website.
The brain is PHP.

And how do you know it won't break the whole website?
Imagine a simple mistake, like, a title missing in a link, which wasnt supplied to the template.
This title is only used when you login into the website, to allow you to logout.
Should the website fail because of that?
Or should it work, regardless of the missing title?

Also, if you're worried about catching your errors, you can use the PHP function [`set_error_handler()`](http://php.net/manual/en/function.set-error-handler.php) to gather all your errors, and use [`register_shutdown_function`](http://php.net/manual/en/function.register-shutdown-function.php) to do something with the errors (for example, writting it into a file with `file_put_contents('path/to/debug/dir/<date>.txt', print_r($errors));` or similar).
Not a pretty solution, but may work for you.
Just figure a way to shove what you need inside that file.

**Comment by stof** [comment]
@ismael-miguel Twig will never trigger a PHP notice in case of using an undefined Twig variable. It will either throw an exception (in strict mode) or return null.

**Comment by ismael-miguel** [comment]
@stof If I recall correctly, it stores all errors somewhere. Passing the twig instance and the loader instance should do it, no?

**Comment by codedokode** [comment]
@ismael-miguel Currently there is not even a notice if a variable is missing in production. So developers are not even aware that something is broken. Obviously a situation where an error is reported is better than this. 

And there still are other cases when an error in the template would be fatal - for example, misspelled method name or filter name, or macro name, or import name. Or calling a method on a `null` variable. It doesn't make sense to ignore a single specific class of errors (misspelled variable) unless the developer explicitly requests it.

The case that you have described is not very realistic - this type of error that breaks the entire site would be easily spotted in the dev environment and never get to the production site. More probable case is an error on some page that has been made long ago and is rarely visited by developers. Of course I, as a developer, would prefer to learn about this error as soon as possible rather than ignore it and leave that page broken until some responsible user reports it.

I have always used `strict_variables = true` (also  `error_reporting = E_ALL` and always converted any errors to exceptions). The situations when there was 500 error because of a missing variable were rare. And I cannot remember when the whole site would break because of this. In my experience most frequent kind of errors in production is something missing in an entity from database, like some field that should not be empty is actually empty.

So I think that `strict_variables = false` should be a special case (like legacy code or a project that is not actively maintained) rather than a default value.

**Comment by ismael-miguel** [comment]
You're drifting away from your point.
Mispelled filters will break imediatelly with a syntax error, and the `strict_variables` option has no effect on that.
Try it on: https://twigfiddle.com/52zcbi (and try enabling and disabling the `strict_variables` option).
This means that you wouldn't even be able to try to render the page.

A missing import name doesn't break the website.
Here's an example that doesn't break: https://twigfiddle.com/2d80b6
`{% include 'z.twig' ignore missing %}Testing`
Even if you include a missing template inside a template called with `ignore missing`, it won't break the site.
Even if it did, this option does nothing for it.

The example I gave is indeed very common.
Something tiny like that can easily be missed.
If you enable that option in production, it will break with an exception.
If twig throws an exception in production, all you can do is either let it go uncaught and have an error 500 or try to handle it some other way that doesn't require re-rendering the same template.
Either way, the effect is the same: the page is broken. It isn't doing/showing what it should.

With the option disabled, it just ignores the missing variable.
You see the page, but some portions may be missing.
The page still mostly works and may deliver most of the content.

<hr>

Also, if you want to learn about those errors, do so in development. Not in production.
Setting `error_reporting = E_ALL` is perfectly fine in development. Not for production.

I don't see what you can do with that value set to true in production, besides replacing the content with a page saying "sorry, this bit doesn't work. go back to homepage".

If I, as a developer, don't find this kind of thing in development, then all hope is lost for production.
Specially with `error_reporting = E_ALL` and `strict_variables = true`.

**Comment by fabpot** [comment]
We won't change the default as this would be a hard BC break. Setting `strict_variables` to `true` is well documented and frameworks are free to choose the default value that suit them best.
