### ISSUE TITLE
 Class Twig_Node contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IteratorAggregate::getIterator) 

### ISSUE THREAD

**Issue by Luishernandez2017** [twigphp/Twig#2540]
Class Twig_Node contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IteratorAggregate::getIterator)

**Comment by stof** [comment]
method is implemented in Twig. So either you have a corrupt opcode cache (try to clear it to see if the issue is solved), or you are using a modified version of the Twig source code (in which case you should not ask us for support)

**Comment by Luishernandez2017** [comment]
Great! Thanks that solve the problem....not sure when or how my opcode cache became corrupted but clearing it resolved the issue!

Thank you.

**Comment by xabbuh** [comment]
@Luishernandez2017 Can you close here then? :)
