### ISSUE TITLE
Convert Twig_Node_Expression_Array to plain old PHP array?

### ISSUE THREAD

**Issue by cviebrock** [twigphp/Twig#2541]
I'm trying to write a new Tag that will be used something like:

```twig
{% mytag { foo: 'bar', qua: 'nu' } %}
```

My parser works and represents the array as an `Twig_Node_Expression_Array`, as expected.

I'd really like to be able to just convert that `Twig_Node_Expression_Array` back to the plain old PHP array it represents.  Is there an easy way to do that?

**Comment by fabpot** [comment]
I'm not sure why you would want to do that. The way it should work is that when compiling the node, Twig will automatically convert the array to plain PHP, which can then be consumed by your own logic.

**Comment by stof** [comment]
thus, if your Twig array is not a constant array, you simply cannot get a PHP array from it at compile time (any dynamic part of the array cannot be known before runtime when evaluating expressions)

**Comment by cviebrock** [comment]
Let me explain what I'm trying to do, and maybe you can make a suggestion.

I'm trying to implement an `expect` tag, as described in #2532.  My goal is to be a bit more rigid in my templates in terms of the variables they use and expect. At the top of the template, I would add the `expect` tag that defines the variables that template uses (and drops all the others, or throws an error, or something configurable). e.g.:

```
{% expect { foo, bar, qua } %}        // these vars must be present
{% expect { foo, bar, qua } only %}   // same, and all other vars are ignored
```

My implementation gets me to the point where I have a `Twig_Node_Expression_Array` that I would  then need to process to get the PHP array `['foo','bar','qua']`.  The idea would be to then compare that to the template context and either drop the other vars, throw an exception, etc..

Maybe a tag isn't the right way to do this.  I kinda forgot that templates get compiled and cached, so I'm not sure how best to catch the fact that in one case I may include the template with `foo`, `bar` and `qua`, and in other case I may not.  The compiled template wouldn't change.

Suggestions?
