### ISSUE TITLE
JSON_UNESCAPED_UNICODE json_encode constant not working as expected

### ISSUE THREAD

**Issue by olets** [twigphp/Twig#2545]
The result of

```twig
{{ "\u20ac"|json_encode(constant('JSON_UNESCAPED_UNICODE')) | raw }}
```

is `"u20ac"`.

The expected result is `"€"`.

Tested in 2.4.3

**Comment by olets** [comment]
My mistake, I see this is a job for `convert_encoding`

**Comment by xabbuh** [comment]
But that's not what `JSON_UNESCAPED_UNICODE` is meant to do: https://3v4l.org/gqFbP
