### ISSUE TITLE
Mark types as "safe"

### ISSUE THREAD

**Issue by lstrojny** [twigphp/Twig#2548]
Today when a value object is inherently safe to output it must extend {{Twig\Markup}} and therefore introduce a hard dependency to Twig. It would be appreciated if one could reverse that relationship and mark a type as safe. Something like:

```
$env = new \Twig\Environment(…, ['object_safelist' => ['js' => [ObjectThatIsSafeForJs::class], 'html' => [Object1ThatIsSafeForOutputInHtml::class, Object2ThatIsSafe::class]]]);
```

`twig_escape_filter()` would use that list to look up if the passed object is considered safe for the current escaping and output the result of `__toString()` as is.

**Comment by fabpot** [comment]
see #3025 for a possible implementation.
