### ISSUE TITLE
overwrite template selection / template minification

### ISSUE THREAD

**Issue by flo-sch** [twigphp/Twig#2551]
Hi, sorry in advance if this issue is confusing, I'm not sure if it concerns this package or more the `symfony\twig-bridge` instead...

I'm using Twig in every Symfony projects, not having any problem with it, it works perfectly.

I'm considering including an HTML minifier in my Symfony stack, to reduce HTML responses.
I know it is possible to rely on the webserver for such tasks, but webservers are not always configurable.

Currently, I have one package able to minify the output of a generated HTML string, removing un-necessary whitespaces, attributes etc.

I was able to use it to minify output at runtime, based on Symfony `kernel.response` event.
But minifying output at runtime doesn't make real sense to me, and I would prefer to try minifying Twig templates instead.

As I'm not familiar at all with Twig's source code, I wonder what's the best way to do it?

I was currently thinking to a Symfony command which would :

1. Locate existing templates

2. Minify templates content

3. Output the minified content in another file, to avoid versionning and environments problems
Something such as `index.html.twig` ---> `index.html.min.twig`

Then, I would like to hook Twig to load the minified version of a given template...
--> I was thinking to hook the Twig\Environment loadTemplate method for instance... But not sure about potential issues (cache... ?)

```
class Twig_Environment
{
    public function loadTemplate($name, $index = null)
    {
        $minifiedTemplate = str_replace('.html.twig', '.html.min.twig', $name);

        if (file_exists($minfiedTemplate)) {
            $name = $minifiedTemplate;
        }

        // ...
    }
}
```

I would greatly appreciate advices and tips, even to know if such plans are even possible to do with Twig, currently :)

**Comment by stof** [comment]
Replacing the name may cause issues (depending at which point you do it, but the place you describe above will definitely cause issues).

However, Twig allows to register multiple paths for each namespace, and will look in each of them until it finds the template source. So what you would have to do is simply to register the folder containing the minified templates first, and then ensure that relative paths in it are matching the relative paths in the original folder.

Btw, be careful that you will need to implement a dedicated minifier library. A library able to minify HTML will not be able to minify the Twig templates, because the Twig source code is not HTML.

**Comment by flo-sch** [comment]
Hey @stof, thanks for your answer :)

I didn't even think to a dedicated folder but it seems indeed a way better idea...

Any idea how to register a new path?
Should I dig more into `twig` itself or into `symfony/twig-bridge` for such a thing?

I'm aware of the difference between HTML and Twig, the minifier already has implementations for other templating engines such as Blade (the one Laravel uses), so I'm confident about successfully porting it to twig.

**Comment by stof** [comment]
Symfony allows you to register extra paths in the config of TwigBundle. These paths are registered with higher priority than the default ones. So they would fit your needs.

If you don't use the bundle but configure Twig yourselves, you are already the one configuring the loader, and so you are in control of the paths

**Comment by flo-sch** [comment]
I'm definitely using TwigBundle :)

Excellent, thanks a lot for the tips, I'll dig into it :)
