### ISSUE TITLE
Rewriting if statements XSLT to Twig

### ISSUE THREAD

**Issue by Fanda36** [twigphp/Twig#2552]
Hi,
I'm rewriting XSLT template to Twig. I have one issue with if statment.
In XSLT have this:
```<xsl:if test="attributes/group/items[attribute_key='counter-date']/content">```
What is best solution this if in Twig?
I found only solution with 2 for cycles (lite version):
```
{% for a in p.attributes.group %}
            {% for it in a.items if it.attribute_key == 'counter-date' %}
            {% endfor %} 
{% endfor %} 
```
Thanks.

**Comment by stof** [comment]
I don't see a simpler solution than that here, if you cannot change the structure of the data you receive.
