### ISSUE TITLE
twig convert

### ISSUE THREAD

**Issue by nik5val** [twigphp/Twig#2553]
<div class="col-sm-10">
                                    <select name="advanced_newsletter_send_for[]" class="form-control" multiple>
                                       <option value="0" <?php echo (!empty($advanced_newsletter_send_for) && in_array(0, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Disabled</option>
									  
									   
									   <option value="1" <?php echo (!empty($advanced_newsletter_send_for) && in_array(1, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Enabled</option>
                                        <option value="2" <?php echo (!empty($advanced_newsletter_send_for) && in_array(2, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Blacklist</option>
                                        <option value="3" <?php echo (!empty($advanced_newsletter_send_for) && in_array(3, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Un-subscribed</option>
                                        <option value="4" <?php echo (!empty($advanced_newsletter_send_for) && in_array(4, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Non-verfied</option>
                                    </select>
									
									
		                        </div>

this code convert in twig so plessssssss solution me.....

**Comment by nik5val** [comment]
<div class="col-sm-10">
                                    <select name="advanced_newsletter_send_for[]" class="form-control" multiple>
                                       <option value="0" <?php echo (!empty($advanced_newsletter_send_for) && in_array(0, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Disabled</option>
									  
									   
									   <option value="1" <?php echo (!empty($advanced_newsletter_send_for) && in_array(1, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Enabled</option>
                                        <option value="2" <?php echo (!empty($advanced_newsletter_send_for) && in_array(2, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Blacklist</option>
                                        <option value="3" <?php echo (!empty($advanced_newsletter_send_for) && in_array(3, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Un-subscribed</option>
                                        <option value="4" <?php echo (!empty($advanced_newsletter_send_for) && in_array(4, $advanced_newsletter_send_for) ? 'selected="selected"' : '')?>>Non-verfied</option>
                                    </select>
									
									
		                        </div>``

**Comment by stof** [comment]
What is it about ?

**Comment by nik5val** [comment]
advance newslatter extetion

**Comment by nik5val** [comment]
this file code convert in twig file so help me..

On Fri, Sep 8, 2017 at 8:13 PM, Christophe Coevoet <notifications@github.com

**Comment by stof** [comment]
OK, please forget about what you know you meant when posting this issue and read it again. Tell ask yourselves whether I have any chance to understand what you were asking.

**Comment by nik5val** [comment]
why

**Comment by nik5val** [comment]
[adv_newsletter.zip](https://github.com/twigphp/Twig/files/1289586/adv_newsletter.zip)
This file code php to convert in twig file ok

**Comment by sstok** [comment]
From what I understand you have a piece of PHP code that you want to convert to Twig?
There is no extension or transformer that can do this, you need to do this conversion yourself.

And **please don't post just code without asking an actual question, we don't have magic crystal ball's (no pun 😂) that can tell us what's wrong).*
