### ISSUE TITLE
Add an option to disable magic object property resolving

### ISSUE THREAD

**Issue by tomasfejfar** [twigphp/Twig#2563]
**Setup:**
* generated getters
* by accident generate getter with incorrect name (like `getIsInStock`)

**Current:**
* `{ product.isInStock() }` calls `$product->getIsInStock()` if it exists. 

**Expected:**
* `{ product.isInStock() }` fails because there is no such method. 

**Motivation:**
* Cut down on magic
* Find bugs early in development phase
* Making it configurable allows to keep backwards compatibility

**Comment by stof** [comment]
Having an option to change the meaning of the Twig syntax has a huge drawback: it forbids you to use any external template (as they would rely on the known Twig behavior).

Btw, if you are using Symfony, this includes not using the webprofiler and the default error pages anymore...

**Comment by tomasfejfar** [comment]
That leaves having this behavior configurable per-resource, which would make it even more confusing and add more edge cases :( That's unfortunate.
