### ISSUE TITLE
Sniffs for Twig files (PHPCS)

### ISSUE THREAD

**Issue by johnbillion** [twigphp/Twig#2564]
When building PHP templates, it's common to use an automated code sniffer such as PHPCS to sniff the files for code quality.

There doesn't appear to be anything similar available for Twig templates, which means code reviews for formatting purposes needs to be done manually, and nothing can be hooked up to a CI environment.

Are there any plans to build a code sniffer for Twig files?

**Comment by stof** [comment]
There is https://github.com/allocine/twigcs but I'm not sure it is feature complete

**Comment by stof** [comment]
Note that it is also possible to write a linter, and Symfony did it: https://github.com/symfony/symfony/blob/v3.3.9/src/Symfony/Bridge/Twig/Command/LintCommand.php

This command won't check coding standards (the default Twig parser does not preserve formatting info). But it will report any syntax error (which involves also ensuring that you don't use filters which are not available, and so the command requires to have a `Twig_Environment` instance configured with all the extensions you will have at runtime).
This is something complementary to the twigcs project.

**Comment by fabpot** [comment]
You can also have a look at this recipe: https://twig.symfony.com/doc/2.x/recipes.html#validating-the-template-syntax
