### ISSUE TITLE
date filter comparison only works with 'Y-m-d' format

### ISSUE THREAD

**Issue by ghost** [twigphp/Twig#2566]
Hi,
date comparison only works when providing an english US date format in the form of d-m-Y. e.g: 2017-12-31 for december 31,

so assuming that date1 and date2 are 2 DateTime instances, this works fine:
`{% if date1|format( 'Y-m-d' ) < date2|format( 'Y-m-d' ) %}`

But changing to au european format of 'dd/mm/YYYY' this does NOT work:
``{% if date1|format( 'd/m/Y' ) < date2|format( 'd/m/Y' ) %}``

The official documentation does not provide any information about this and remains slim about what you can and can't do with the date variable. 
[https://twig.symfony.com/doc/2.x/filters/date.html](https://twig.symfony.com/doc/2.x/filters/date.html)

For example, is it possible to use DateTime methods such as diff() or modify()?

**Comment by xabbuh** [comment]
Well, the `date` filter is meant to turn a date into a human readable format. What's the point in comparing such two strings? If you just want to compare two dates, just compare these two variables:

```twig
{% if date1 > date2 %}
    date2 is before date1
{% endif %}
```
