### ISSUE TITLE
Add a better support to INTL

### ISSUE THREAD

**Issue by lyrixx** [twigphp/Twig#2567]
Hi, 

For now, Twig does not provide any intl related functions.
And it's fairly common to add i18n / l10n features to a website.

So I think it's time to integrate https://github.com/twigphp/Twig-extensions/blob/master/lib/Twig/Extensions/Extension/Intl.php into the core.

More over, even in the twig ext, there are no support for translating language / locale / country.
It's quit common to have a symfony form with a CountryType. The country type set in the model something like "FR". And if you want to render a template with this information, it's better to display "France".

So it would be very nice to have also localized_country, localized_language etc.

This might require a new dependency on symfony/intl, but I don't really think it's an issue.

What do you think?

Obviously, I could work on this feature if it's accepted.

**Comment by stof** [comment]
I don't think adding a dependency to symfony/intl in Twig core makes sense here. The Symfony TwigBridge looks like a better fit (providing Twig extensions for Symfony components is exactly its goal). And there is an abandonned PR on the Symfony TwigBridge to add an extension exposing the symfony/intl data (https://github.com/symfony/symfony/pull/20053). My main issue against it was that it was trying to replace the extension exposing ext-intl features (and in a bad way as it was always using the English-only polyfill...), which would hurt non-Symfony users. I think you could start this over taking the feedback of the PR into account.

For the filters exposing ext-intl formatting features, it may be worth adding them in core. I don't have a particular opinion on this (I'm fine with using the Twig-extensions package). It would be up to @fabpot

**Comment by javiereguiluz** [comment]
~@lyrixx have you seen https://github.com/symfony/symfony/pull/20053 by @HeahDude?~
I'm sorry! I thought you created this proposal in the main Symfony repo!

**Comment by lyrixx** [comment]
@stof I'm ok to add it do the bridge since I never use twig without symfony ... But IMHO it make more sense to have it in the core (for drupal & all others)

**Comment by stof** [comment]
Well, if they need to depend on symfony/intl, they can also depend on symfony/twig-bridge to get the intergation (note that I'm not saying to put it in the TwigBundle).. The TwigBridge is perfectly usable outside a fullstack Symfony project.

**Comment by fabpot** [comment]
Done in #3108
