### ISSUE TITLE
batch filter clobbers array keys when fill parameter is used

### ISSUE THREAD

**Issue by abunch** [twigphp/Twig#2568]
batch filter clobbers array keys when fill parameter is used

On the last array chunk if there are fewer keys than the chuck size when the batch filter fills in the missing value it re-numbers the array keys.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

Could you maybe create a small [twig fiddle](https://twigfiddle.com/) to illustrate the issue?

**Comment by abunch** [comment]
Here ya go!  Let me know if there's anything else I can help with.

https://twigfiddle.com/s99ba0

**Comment by fabpot** [comment]
fixed by #2884

**Comment by ericmorand** [comment]
Why has it been fixed? There is nothing in the documentation about the keys:

https://twig.symfony.com/doc/2.x/filters/batch.html

The values of the keys are undefined, based on the documentation. Your fix is a breaking change.
