### ISSUE TITLE
How add all function of class in twig

### ISSUE THREAD

**Issue by RobertoCalani** [twigphp/Twig#2569]
Hi, I need add all function of Class in Twig but whitout use "Twig_SimpleFunction"

My Class:

> class MyClass {
>       public function getName() {
>                  return 'Roberto';
>       }
>       public function getLastName() {
>                  return 'Calani';
>       }
> }

Regards!

**Comment by AlexNodex** [comment]
You can add it as a global

$twig->addGlobal('Foo',new MyClass());


{% set Bar = Foo.getName() %}
{{Bar}}
