### ISSUE TITLE
ExpressionParser throws exception in parseTestExpression method

### ISSUE THREAD

**Issue by jUnG3** [twigphp/Twig#2573]
I think this is an rare edge case. In the case that the variable ``$class = 'Twig_Node_Expression_Function'`` the ``parseTestExpression`` will throw an exception because the constructor in the ``Twig_Node_Expression_Function`` class expects an object as 2nd parameter but becomes an string. Basically the line ``return new $class($node, $name, $arguments, $this->parser->getCurrentToken()->getLine());`` brakes the whole thing.

One possible fix would be this (before the original return)

````
if ($class === 'Twig_Node_Expression_Function') {
    return new $class($name, $node, $this->parser->getCurrentToken()->getLine());
}
````

**Comment by stof** [comment]
Why would a test use `Twig_Node_Expression_Function` as its node class ? This would cause unexpected behavior in node visitors, as it would not consider this node as a tets but as a function.
Test nodes must use `Twig_Node_Expression_Test`, and so any custom class must be a child class of it.

**Comment by jUnG3** [comment]
I really don't know why. I encountered the problem while trying to make an cache warm up...
