### ISSUE TITLE
Twig_Environment properties should be protected instead of private 

### ISSUE THREAD

**Issue by zessx** [twigphp/Twig#2574]
> :exclamation: This issue is valable for all properties of this class, and I assume it is a wider issue in Twig.

I'll give you a concrete example to highlight the issue. For some reason, I wanted all folders and files created by Twig to have 0775/0664 rights, instead of 0755/0644.

So I came to create my own filesystem inheriting `Twig_Cache_Filesystem`, and my own environment inheriting `Twig_Environment`. Here is the root code:

```php
namespace LocalApp;

class LocalTwigCacheFilesystem extends \Twig_Cache_Filesystem
{

    public function write($key, $content)
    {
        $old = umask(0000);
        parent::write($key, $content);
        umask($old);
    }

}

class LocalEnvironment extends \Twig_Environment
{

    public function setCache($cache)
    {
        if (is_string($cache)) {
            $this->originalCache = $cache;
            $this->cache = new LocalTwigCacheFilesystem($cache);
        } elseif (false === $cache) {
            $this->originalCache = $cache;
            $this->cache = new \Twig_Cache_Null();
        } elseif ($cache instanceof \Twig_CacheInterface) {
            $this->originalCache = $this->cache = $cache;
        } else {
            throw new \LogicException(sprintf('Cache can only be a string, false, or a Twig_CacheInterface implementation.'));
        }
    }

}
```

Only then, I realized `Twig_Environment::$cache` is a private property, which prevents us to override Twig behavior.  

There are two solutions:
1. We can leave `Twig_Environment::$cache` private, but every occurence of `$this->cache` MUST be replaced by `$this->getCache()` in the `Twig_Environment` class (specifically in the `loadTemplate()` function)
2. We make `Twig_Environment::$cache` protected, to allow developers to use it in children classes.

**Comment by stof** [comment]
Well, `setCache` allows passing a Twig_Cache instance. Why not just passing your own LocalTwigCacheFilesystem there ?

**Comment by stof** [comment]
Making things protected means that properties have to be covered by the backward compatibility rules. This basically forbid making any change to them (we cannot remove them, we cannot stop using them, we cannot change the way we use them, we cannot rely on invariants on them as they could be modified in child classes...). This makes maintenance harder.
So we won't do it without a strong reason. The fact that you can pass a Twig_Cache instance to `setCache` means that I don't see a strong use case here (you don't even need LocalEnvironment)

**Comment by zessx** [comment]
Ah, you're totally right!   
I can pass a `Twig_Cache` instance instead of a string, then I won't need my `LocalEnvironment` class. 

Sorry for this, I should had go deeper in my searches.
