### ISSUE TITLE
function in twig

### ISSUE THREAD

**Issue by nimasdj** [twigphp/Twig#2575]
I want to import _money_formatting()_ function into my twig. Here is my code:

```
class Project_Twig_Extension extends \Twig_Extension
{
    public function getFunctions()
    {
        return array(
            new \Twig_Function('money_formatting', array($this, 'money_formatting')),
        );
    }

    public function money_formatting($price) {
               //
               return ....;
   }

}
```

It works fine but my question is that the function must be defined inside class anyway? or is it possible to have it as global function too?

**Comment by xabbuh** [comment]
The second argument of the Twig function constructor is a callable. So for global functions you can just pass its name as a string.

**Comment by nimasdj** [comment]
Do you mean to have this?
Twig_Function(null, 'money_formatting'),

**Comment by nimasdj** [comment]
Do you mean to have below in order to just call a global function?
new \Twig_Function(null, 'money_formatting'),

**Comment by stof** [comment]
the firstargument of `Twig_Function` must still be a string defining the function name on the Twig side though. It cannot be `null`

**Comment by nimasdj** [comment]
If understood correctly, I need to have at least one function in class anyway, then other functions could be global?

**Comment by stof** [comment]
no. you seems to misunderstand the meaning of both arguments of the `Twig_Function` constructor:

- the first argument is the Twig function name (the one you will use in your template
- the second one is the PHP callable used to execute it. This can be *any* callable: a method of the extension (`array($this, 'formatMoney')`), a global function (`'formatMoney'`), a static method (`Money\Util::format`), etc...

**Comment by AlexNodex** [comment]
Easier to just give him an example....

`Twig_Function('template_function_name',array($this,'formatMoney'));`

In template....

`{% set money = template_funtion_name(123) %}`

**Comment by nimasdj** [comment]
Do first and second constructor params accept 'arrays' in order to have several functions?

**Comment by SpacePossum** [comment]
@nimasdj please see the constructor here; 
https://github.com/twigphp/Twig/blob/v2.4.4/lib/Twig/Function.php#L35
in short: they don't, you've create and register each function on its own.

**Comment by nimasdj** [comment]
Do you mean instantiate the class again for another function?

**Comment by SpacePossum** [comment]
>Do you mean instantiate the class again for another function?

The most easy way is to create one (anonymous) class to represent one function to be used in Twig.
There (typically) is no need to instantiate a class acting as filter more than ones.

**Comment by nimasdj** [comment]
Do you mean creating several extenstion classes?

**Comment by SpacePossum** [comment]
I mean one class to represent one function in Twig.
Than instantiate each class one time and register these objects each one time.

**Comment by nimasdj** [comment]
Thanks to all guys.
