### ISSUE TITLE
twig with asset

### ISSUE THREAD

**Issue by nimasdj** [twigphp/Twig#2577]
I don't use symfony nor silex, but just standalone twig and I want to use it with assets.
reading the docs here https://symfony.com/doc/current/components/asset.html, I understand if I uset getURL() in controller, it prints the url, but how to pass the url to twig to get it with {{ asset_ url }}?

**Comment by AlexNodex** [comment]
why do you need twig for asset_url? surely you know this URL yourself?

**Comment by nimasdj** [comment]
I wanted to use asset within twig templates. Doesn't make it sense?

**Comment by AlexNodex** [comment]
$twig->addGlobal('asset_url','path/to/assets');

Also, this isn't really an issue, I would recommend going to Stackoverflow / IRC for questions relating to the use of Twig and not opening a bug/issue request for them

**Comment by nimasdj** [comment]
before posting here, I had googled and found this:
https://github.com/symfony/twig-bridge/blob/master/Extension/AssetExtension.php#L38

So I thought it should be something like:

```
use Symfony\Component\Asset\Packages;
use Symfony\Component\Asset\PackageInterface;
use Symfony\Bridge\Twig\Extension\AssetExtension;
use Symfony\Component\Asset\Package;
use Symfony\Component\Asset\PathPackage;
use Symfony\Component\Asset\UrlPackage;
use Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy;

$versionStrategy = new EmptyVersionStrategy();
$namedPackages = array(
    'img' => new UrlPackage('http://img.example.com/', $versionStrategy),
    'doc' => new PathPackage('somewhere/deep/for/documents', $versionStrategy),
);
$defaultPackage = new Package($versionStrategy);
$packages = new Packages($defaultPackage, $namedPackages);
$twig->addExtension(new AssetExtension($packages));
```

I am not sure why AssetExtension doesn't accept Package and we must pass Packages instance. Then use asset() function in templates? I wanted to be sure if I am in correct path and does it make sense to have asset within twig templates this way?

**Comment by nimasdj** [comment]
Oops, another problem, but it adds a leading / to the path and it causes my css to not be found. When I hardcord the css path without leading / it works fine, but with assets, there is leading / at the beginning of the path so css is not working. How to fix it?

**Comment by xabbuh** [comment]
I guess this can be closed.
