### ISSUE TITLE
stylesheets tag

### ISSUE THREAD

**Issue by nimasdj** [twigphp/Twig#2579]
Does standalone twig accepts stylesheets tag? Please advise for this? https://github.com/kriswallsmith/assetic/issues/862

**Comment by xabbuh** [comment]
Twig doesn't know anything about this node. It's provided by AsseticBundle: https://github.com/symfony/assetic-bundle/blob/master/Twig/AsseticExtension.php#L43

**Comment by nimasdj** [comment]
So I have to pass assetic factory to this class, instead of the one I did? or please give an example.

**Comment by SpacePossum** [comment]
for questions/examples about `symfony/assetic-bundle/` you best try over there I think:
https://symfony.com/community

**Comment by nimasdj** [comment]
@xabbuh If you meant I have to pass assetic factory instance to assetic-bundle AsseticExtension, I did so but it requires a second argument `Error 0: Argument 2 passed to Symfony\Bundle\AsseticBundle\Twig\AsseticExtension::__construct() must be an instance of Symfony\Component\Templating\TemplateNameParserInterface` What should I do now?

**Comment by xabbuh** [comment]
@nimasdj I would have to dig into the code of AsseticBundle myself to help you with that. I suggest to do that yourself or to use the support channels as suggested by @SpacePossum.
