### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by nimasdj** [twigphp/Twig#2580]
I use this:

```
$loader = new Twig_Loader_Filesystem('path/to/theme');
$twig = new Twig_Environment($loader, array(
    'cache' => 'path/to/cache',
    'debug' => true,
    'strict_variables' => true,
));

$template = $twig->load('index.html');
$template->display(array('foo' => 'bar'));
```
And it was working fine but suddenly I got blank page, I did debug and discovered when I use built-in functions like {% include 'blah.html %} or {% if ...... %} I get blank page! Where and what should I look into?

**Comment by AlexNodex** [comment]
Once again this is not a bug

Please refer to Stackoverflow for usage help.

**Comment by SpacePossum** [comment]
Start by adding this to your bootstrap/index.php file:

```php
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting(-1);
//Debug::enable();
```

now the white page should show the error.
Check the server logs for additional details.

Do _not_ leave these lines of code enabled in your production environment.

TBH.: this is basic PHP development and not (directly) related to Twig. Besides this is an issue tracker, not a question/support channel. You probably get better/faster help if you pick a channel that better fits your questions, like as Alex suggested; StackOverflow

**Comment by nimasdj** [comment]
I am getting no error, by further investigation I noticed this is because of {% if .... %}. when I remove all if statements, it works fine! Any idea why?

**Comment by SpacePossum** [comment]
without error details we cannot help

**Comment by nimasdj** [comment]
I created a standalone script as below:

```
<?php
require_once ("vendor/autoload.php");

$loader = new Twig_Loader_Filesystem('/path/to/theme');
$twig = new Twig_Environment($loader, array(
    'cache' =>  '/path/to/cache',
));

$template = $twig->load('test.htm');
//$template->display();
echo $template->render();
```
and I get 

Catchable fatal error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in /twig/twig/lib/Twig/Extension/Core.php on line 139 and defined in /twig/twig/lib/Twig/Filter.php on line 35

**Comment by xabbuh** [comment]
Looks like you are using PHP 5.x, but try to use Twig 2 which requires PHP 7.

**Comment by nimasdj** [comment]
Oops, I apologize for that. I switched to php 7. If you kindly help for this one too, I will be fine with everything. https://stackoverflow.com/questions/47127830/how-to-get-redirected-to-correct-page-with-silex

**Comment by xabbuh** [comment]
Can you close here then please? :)

**Comment by nimasdj** [comment]
Yes, I close and I hope to get your answer to my SO link above! :+1:

**Comment by nimasdj** [comment]
@xabbuh 
EDIT to what I posted on SO:
I guess I discovered the issue, the login form is:

     <form method="post" action="index.php">

instead of posting data to http://www.example.com/new/login
So how the action url must be? I tried action="/new/login" and it doesn't work.
I get no route for POST /login. but this is defined in Routers/Login.php, so why should I get this?
Please advise.

**Comment by stof** [comment]
well, this has nothing to do with Twig, as it is an issue with your routing and the generation of your path (which is not something done by Twig core).

**Comment by nimasdj** [comment]
@stof I know this is my mistake with Silex (not Twig), but I appreciate your help for that.

**Comment by nimasdj** [comment]
I almost got it.
When I use bind() like
` $controllers->get('/', 'Controllers\\Login::index')->bind('login'); 
`I get "No route found for "GET /login":" but without bind() it works fine. What is wrong?

**Comment by SpacePossum** [comment]
`No route` is a clear hint it is not Twig, beside you _also_ reported this over at Silex and on top, most users here keep trying to tell you that this is the wrong channel. Please go to StackOverflow for usage-questions, thanks and good luck!

**Comment by nimasdj** [comment]
Please see "EDIT2" here https://stackoverflow.com/questions/47127830/how-to-get-redirected-to-correct-page-with-silex any advise there?
