### ISSUE TITLE
Twig template doesn't render Resources/public ? 

### ISSUE THREAD

**Issue by Nebojsaa** [twigphp/Twig#2583]
I have added twig template into this directory Resources/public/ which is other then this Resources/views/.. I would like to render also public directory via the twig template. How could I do that ? 
Since we are overriding something inside the public directory from third-party bundle, I can't move it out of it and I need Twig in order to render it. 

How can I achieve this ? 
Or in other words, how can I add something for twig engine to render it ?

**Comment by yceruto** [comment]
You can add your own path to tell Twig where find more templates, see http://symfony.com/doc/current/templating/namespaced_paths.html#registering-your-own-namespaces

**Comment by Nebojsaa** [comment]
Thanks yceruto for the response. 
Yes, in the meantime I have find this source. But still have the same problem. 
So this means that I have added to the app/config/config.yml 
twig:
    paths:
        "%kernel.root_dir%/../src/Iclei/Bundle/BackendBundle/Resources/public/templates": custom_templates

But still have plain html in frontend. This means whatever twig code I add it is going to be displayed as such.

**Comment by yceruto** [comment]
Oh no, the Twig templates need to be rendered before displaying them. Maybe a command or cache warmer that render the template and save it inside `public` directory?
```php
file_put_contents('path/to/public/page.html', $twig->render($twigTemplate, $parameters));
```
thus, ready as pure html page.
