### ISSUE TITLE
title filter error case

### ISSUE THREAD

**Issue by columbian-chris** [twigphp/Twig#2584]
When using the title filter on strings that start with a non-alpha character, for example a street named "4th ave", it will return "4Th Ave", capitalizing the "t" in "4th".  I'm assuming that capitalizing in this filter should be limited to the first character in a word or maybe the first character after a space.

**Comment by stof** [comment]
Well, this is the behavior of PHP's `mb_convert_case($string, MB_CASE_TITLE)`

**Comment by avant1** [comment]
More details on this can be found here: https://bugs.php.net/bug.php?id=65544

**Comment by fabpot** [comment]
Closing as we are relying on PHP for this feature. Nothing we can fix on our side.

**Comment by columbian-chris** [comment]
Judging by @avant1's link, it doesn't look like the PHP community really took the issue seriously and doesn't appear that this issue may be resolved or resolved anytime soon.  Therefore, might I suggest using some alternative solution to `mb_convert_case($string, MB_CASE_TITLE)` like `ucwords(strtolower($string))` instead?

Sorry if I'm answering a closed thread; I've been under the weather since shortly after I opened the ticket.
