### ISSUE TITLE
Infinite loop with custom interpolation syntax

### ISSUE THREAD

**Issue by sonicoder86** [twigphp/Twig#2587]
When I try to compile a template i run into an infinite loop when setting the variable interpolation syntax.

Steps to reproduce:
Set interpolation to `array('#${', '}')` instead of the original `array('#{', '}')` one.
Compile this template: `'Hello {{ " #{'`.

The source of the problem can be that `\Twig_Lexer::lexString` doesn't have an `else` clause.

**Comment by fabpot** [comment]
#2652 fixes the infinite loop. Fixing the underlying issue is more complex as the regexes use in Twig actually do not support changing the interpolation delimiters. I will see if it's easily fixable.
