### ISSUE TITLE
Blocks with the same name should be allowed to promote reuse

### ISSUE THREAD

**Issue by Bilge** [twigphp/Twig#2588]
Consider the following template:

```jinja
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
<body>
    <h1>{% block title %}{% endblock %}</h1>
```

Clearly the goal here is to have the `title` block substituted identically in both places. However, this causes a compile error:

>[Twig_Error_Syntax]: The block 'title' has already been defined line 3.

I propose identical blocks with the same name should be allowed to promote reuse.

**Comment by julienfalque** [comment]
Why not replacing the second one with `{{ block('title') }}`?

**Comment by Bilge** [comment]
Oh, I see, I was not aware of a `block` *function*. It might be useful if that was mentioned in either the [block tag](https://twig.symfony.com/doc/2.x/tags/block.html) or [extends tag](https://twig.symfony.com/doc/2.x/tags/extends.html) documentation, for those unaware. Thanks for the tip!

**Comment by fabpot** [comment]
@Bilge Can you submit a PR to improve the docs?
