### ISSUE TITLE
Dynamic Twig_Test don't seems to work

### ISSUE THREAD

**Issue by Bacteries** [twigphp/Twig#2589]
Hi,
in Twig's documentation it's said "Tests also support dynamic name feature as filters and functions." (filter can be path_* by eg)

But I don't find how to achieve this.
I tried this :

`new \Twig_SimpleTest('format_*', [$this, 'isFormat'])`

but I get this error message :

> Unknown "format_web" test. Did you mean "format_*"

I haven't found an example, so I dig in the codebase. I found a "*" replacement for Filters : 

```
foreach ($this->filters as $pattern => $filter) {
            $pattern = str_replace('\\*', '(.*?)', preg_quote($pattern, '#'), $count);
            if ($count && preg_match('#^'.$pattern.'$#', $name, $matches)) {
                array_shift($matches);
                $filter->setArguments($matches);
                return $filter;
            }
        }
```

But not for test : 

```
public function getTest($name)
    {
        if (!$this->initialized) {
            $this->initExtensions();
        }
        if (isset($this->tests[$name])) {
            return $this->tests[$name];
        }
        return false;
    }
```

So : is it the doc that need to be fixed, or the getTest($name) method? (or do I get it wrong ?)

**Comment by fabpot** [comment]
If we can support dynamic tests, I would fix the code instead of the docs.
