### ISSUE TITLE
0 == '#'

### ISSUE THREAD

**Issue by aaronadal** [twigphp/Twig#2590]
Hi,

When I run the next piece of code, the output is true when I think it should be false. Am I wrong?

```twig
{% if 0 == '#' %}
    true
{% else %}
    false
{% endif %}
```

**Comment by aaronadal** [comment]
Well, I think it is not a Twig issue, but a "normal" PHP behavior: [https://stackoverflow.com/a/6843075](https://stackoverflow.com/a/6843075)

Sorry for the inconvenience.

**Comment by xabbuh** [comment]
That's [how PHP's `==` operator works](https://3v4l.org/1M5DO) (which is used in the background). You can use the [`same as` test](https://twig.symfony.com/doc/2.x/tests/sameas.html) instead:

```twig
{% if 0 same as('#') %}
    true
{% else %}
    false
{% endif %}
```
