### ISSUE TITLE
Force defining variables in template

### ISSUE THREAD

**Issue by bkrukowski** [twigphp/Twig#2591]
I am using [Symfony Plugin](https://plugins.jetbrains.com/plugin/7219-symfony-plugin) for PhpStorm, especially for syntax autocomplete using annotations, e.g.:

```
{# @var foo \SomeClass #}
```

Would be nice to have something like `strict mode` in templates, in this mode programmer would be forced to defining list of all variables used in template. Using undefined variable Twig should report an error.

```
{# @var group #}
{# @var users #}

<h1>{{ group.name }}</h1>
<ul>
    {% for user in users %}
        <li>{{ user.username|e }}</li>
    {% endfor %}
</ul>
```

Annotation @var allows to define type of variable. Would be nice to add an option for validation of input variables, e.g.:

The following example should report an error (template expects instance of `AppNamespace\Person`, array given).

**php**:
```php
$twig->render('template.twig', ['person' => ['name' => 'Jane']]);
```

**template.twig**
```
{# @var person \AppNamespace\Person #}
{{ person.name }}
```

**Comment by stof** [comment]
`{# @var #}` is just a comment as far as Twig is concerned. So this cannot trigger any logic in Twig.

What you could do is implementing a dedicated tag in an extension with something like that:

```twig
{% expect_var variable_name type %}
```

and then, the compilation would add some checks for this in the compiled template (could even be compiled to a no-op in non-debug mode for the prod).
I'm not sure this tag belongs to the core though.

**Comment by fabpot** [comment]
I'm closing this one as this is a topic that is already discussed in other issues.
