### ISSUE TITLE
Verbatim tag ignored by Twig_Sandbox_SecurityPolicy

### ISSUE THREAD

**Issue by jonathanbull** [twigphp/Twig#2594]
If I disallow the `verbatim` tag in a `Twig_Sandbox_SecurityPolicy`, I'd expect  `Twig_Sandbox_SecurityNotAllowedTagError` to be thrown. However the template renders as expected. Is this a bug, or expected behaviour? Thanks.

    $allowedTags = ['if'];
    $allowedFilters = [
        'upper',
        // 'verbatim',
        'escape'
    ];
    $allowedMethods = [];
    $allowedProperties = [];
    $allowedFunctions = [];

    $securityPolicy = new Twig_Sandbox_SecurityPolicy(
        $allowedTags,
        $allowedFilters,
        $allowedMethods,
        $allowedProperties,
        $allowedFunctions
    );
    $sandbox = new Twig_Extension_Sandbox($securityPolicy, true);

    $twig = new Twig_Environment(new Twig_Loader_Array([]));
    $twig->addExtension($sandbox);
    $template = $twig->createTemplate('{% verbatim %} {{ foo }} {% endverbatim %}');
    echo $template->render([]);

**Comment by stof** [comment]
I think this might be related to the fact the `verbatim` is actually a lexer-level feature. In the AST, this is just a Twig_Node_Text

**Comment by stof** [comment]
Btw, you can always produce exactly the same output without using `{% verbatim %}`, at the expense of making the template less readable: for all the verbatim text you had, replace any `{{`, `{#`, `{%`, `%}`, `#}` and `}}` by something like `{{ '{#' }}` (changing the string being rendered based on the replacement being done of course).

This works by ensuring that you never get any tag or any custom printing in this section. The only Twig markup there would be the rendering of these static strings, which would be perfectly allowed by any sandbox (it does not use any tag, any filter, any function, and it does not involve any object property or method).
So I'm not sure making a complex architecture change in Twig to allow forbidding the `{% verbatim %}` tag through the sandbox actually makes sense.

**Comment by fabpot** [comment]
I agree with @stof. Having access to `verbatim` does not give any "power". It's always "safe" to use.
