### ISSUE TITLE
Twig template extending itself

### ISSUE THREAD

**Issue by igneus** [twigphp/Twig#2595]
I have accidentally created a template which `{% extends '...' %}` itself. Twig allows this and as a consequence it spends the rest of the execution time in an infinite loop. I believe it would make sense to forbid self-extending templates altogether, as there is rarely a case where such a construct makes sense.

That would, however, harm those who possibly rely on recursively self-extending templates (I can't think of any case where it would be useful, but it seems to be technically possible, as the recursion can be stopped using [conditional inheritance](https://twig.symfony.com/doc/2.x/tags/extends.html#conditional-inheritance)) *and* it wouldn't handle more complicated cases, like two templates endlessly extending each other. So it may be better to impose some limit on the total depth of the extend stack or to detect cycles in the extend graph.

The behaviour described above was experienced with Twig 2.4.3 in Symfony 3.3.10

**Comment by fabpot** [comment]
This has already been debated. PHP itself does not prevent you from doing an infinite loop. So, it was decided to not complexify the code for such a case.

**Comment by yceruto** [comment]
Since Twig 1.35 and 2.4.4 this kind of situation already throws an exception (https://github.com/twigphp/Twig/commit/d632fd3c33ff2a8115428f9ac3a154cb7d8dc82f)

**Comment by fabpot** [comment]
@yceruto hehe, I already forgot about that :)
