### ISSUE TITLE
[Bug] Title filter

### ISSUE THREAD

**Issue by raul782** [twigphp/Twig#2596]
So this is an issue with Greek characters:
Here is the example:
```
set name= "ΚΥΝΌΣ"|title
```

Expected : Κυνός  (when the sigma character is at the end, the symbol used is ς)
Actual: Κυνόσ

Moreover, I added a twig filter for preg_replace:
```
public function preplace($pattern, $replacer, $text, $limit)
{
    return preg_replace($pattern, $replacer, $text, $limit)
}
```

When using it as a filter:

```
"Κυνόσ"|preplace("/σ\b/u", "ς");
```
It doesn't change it, though it works fine in PHP but not in the template.
Note: the template is utf-8 encoded.

```
"Κυνόσ"|preplace("/σ/u", "ς");
```
This works, but it's not what I'm looking for.

Looking for a workaround, since I doubt the title bug will be fixed in Twig, but probably it's related to a php issue.

Thanks,

**Comment by SpacePossum** [comment]
Hi,

Looking at the implementation of the [title filter](https://github.com/twigphp/Twig/blob/v2.4.4/lib/Twig/Extension/Core.php#L1192) the issue can be tracked to PHP https://3v4l.org/2PEoc
Your sample show one of many issues with `title` which should be fixed on PHP level, but sadly there isn't much process AFAIK.

**Comment by fabpot** [comment]
Closing as this is a PHP bug.

**Comment by raul782** [comment]
Hi @SpacePossum, fair enough about the PHP bug for title.
But , what about the `preg_replace` function I've created to patch this issue, it works in PHP but not when used in Twig as a filter, any hints why this doesn't work as expected?

**Comment by SpacePossum** [comment]
Ho @raul782 ,

I've tried the following setup:

```php
function preplace($text, $find, $replace, $limit = -1)
{
    return preg_replace(
        sprintf('#%s#u', preg_quote($find, '#')),
        $replace,
        $text,
        $limit
    );
}

//..

$twig->addFilter(
    new \Twig_Filter(
        'preplace',
        'preplace'
    )
);
```

```twig
[ {{ "Κυνόσ"|preplace("σ", "ς") }} ]
```

>[ Κυνός ]

Hope it is of any help. I didn't find the time to check what goes wrong with UTF-8 in the replace pattern in a template itself (yet).

**Comment by SpacePossum** [comment]
oh sorry, just found it out/remembered;
you need to escape the `replace` value in the template;

`"Κυνόσ"|preplace("/σ\b/u", "ς");`

should be:

`"Κυνόσ"|preplace("/σ\\b/u", "ς");` 

(just like you would escape the `\` in a PHP double quoted string)

**Comment by raul782** [comment]
Thanks 💯 , that did it 👍
