### ISSUE TITLE
Deprecate templates

### ISSUE THREAD

**Issue by kunicmarko20** [twigphp/Twig#2599]
Hi,

I was doing a PR [here](https://github.com/sonata-project/SonataAdminBundle/pull/4833) as we had to deprecate some templates and I had to provide an extension for this so I was wondering if a feature like deprecating templates could be added directly into twig maybe?

**Comment by fabpot** [comment]
Not sure I understand what "deprecating a template means". Can you tell us a bit more?

**Comment by greg0ire** [comment]
The context is moving a template from a bundle to another. Sonata doctrine ORM to Sonata admin in our case. Except it cannot be a move, because that would be a BC-break, so we copy templates to the admin bundle, and want a way to tell people they should no longer rely on the old ones.

**Comment by fabpot** [comment]
Ok, understood. That's not a feature that should be provided by Twig directly. We don't have any of the infrastructure needed to make it happen anyway, so that's out of scope.

**Comment by yceruto** [comment]
Oh, I had not seen this issue in the past and I think https://github.com/twigphp/Twig/pull/2696 is precisely what this is about.

**Comment by kunicmarko20** [comment]
At the end we created our own https://github.com/sonata-project/SonataCoreBundle/blob/3.x/src/Twig/Node/DeprecatedTemplateNode.php

**Comment by kunicmarko20** [comment]
Would love to deprecate it and move to something more official 😄
