### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by ThibaultMartinPenbase** [twigphp/Twig#2602]
Hello, I have a PHP error :

> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: call_user_func() expects parameter 1 to be a valid callback, no array or string given
> 
> Filename: Extension/Escaper.php
> 
> Line Number: 72
> 
> Backtrace:
> 
> File: /mnt/c/Users/Thibault MARTIN/Documents/sites/Omega/vendor/twig/twig/lib/Twig/Extension/Escaper.php
> Line: 72
> Function: _error_handler

**Comment by Tobion** [comment]
What's the value of https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Extension/Escaper.php#L14 in your case and where does it get set from?

**Comment by ThibaultMartinPenbase** [comment]
I have `private $defaultStrategy;`

**Comment by Tobion** [comment]
I'm interested in the contents of this variable.

**Comment by ThibaultMartinPenbase** [comment]
Sorry,

The contents = TRUE

**Comment by Tobion** [comment]
So that's the problem. It must not be true. Can you debug now why it is true? You can check `setDefaultStrategy` and look in the backtrace.

**Comment by ThibaultMartinPenbase** [comment]
I used Codeigniter, no symfony

**Comment by fabpot** [comment]
Closing as this is apparently not a Twig issue (perhaps a problem with the integration with Codeigniter, but we don't have any information that would help us find the issue).

**Comment by cinder92** [comment]
im having same issue @ThibaultMartinPenbase  did you found any fix for that?

**Comment by kraven30** [comment]
In Escaper.php for Codeigniter 3.*

Remplace te constructor by that

public function __construct($defaultStrategy = true){
     if (true === $defaultStrategy) {
         $defaultStrategy = 'html';
     };
    $this->setDefaultStrategy($defaultStrategy);
}

**Comment by maltekuehl** [comment]
I you did it like me and got the CodeIgniter Twig implementation from an online tutorial and got this error, the solution is to change
`$config['twig']['environment']['autoescape'] = TRUE;`
to
`$config['twig']['environment']['autoescape'] = 'html';`
in the file ./application/config/twig.php as the solution from @kraven30 won't work when Twig is updated.
