### ISSUE TITLE
[feature request] loop variable to return whether the condition `for ... if ...` was ever met

### ISSUE THREAD

**Issue by olets** [twigphp/Twig#2603]
When using `{% for ... if ... %}` I often want to ask "were there any?" and if so do a one-time thing

I can do that easily enough with

```twig
{% set anyFound = false %}
{% for item in items if condition %}
    {% if not anyFound %}
        {% set anyFound = true %}
        ...do x [edit: note this happens at most once]...
    {% endif %}

    ...do y...
{% endfor %}
```

but something like

```twig
{% for item in items if condition %}
    {% if loop.any %}
        ...do x [edit: this would happen at most once]...
    {% endif %}

    ...do y...
{% endfor %}
```

would be really nice

**Comment by willrowe** [comment]
Take a look at the [`for` documentation](https://twig.symfony.com/doc/2.x/tags/for.html#the-else-clause). There is an `else` tag that can be used in `for` loops.

You can see an example similar to the one you proposed [here](https://twigfiddle.com/gzrhe6)

**Comment by olets** [comment]
Hmm take another look at my examples, I'm not sure how an `else` would help? I'm thinking of this as a relative of `loop.index` specifically for `for ... if ...`

**Comment by olets** [comment]
(Added notes to my examples, pointing to what I think makes this different)

**Comment by willrowe** [comment]
Can you link to a twigfiddle that has the desired output?

**Comment by olets** [comment]
Sure! https://twigfiddle.com/df9u1z/5 (edit: fixed a bug, added documentation). the example in that linked twigfiddle compares

```twig
{% set anyFound = false %}
{% for item in items if condition %}
    {% if not anyFound %}
        {% set anyFound = true %}
        <ul>
    {% endif %}
        <li>{{ item }}</li>
{% endfor %}
{% if anyFound %}
    </ul>
{% endif %}
```

to 

```twig
{% for item in items if condition %}
    {% if loop.any %}<ul>{% endif %}
        <li>{{ item }}</li>
    {% if loop.any %}</ul>{% endif %}
{% endfor %}
```

**Comment by deflock** [comment]
```twig
{% if loop.first %}<ul>{% endif %}
...
{% if loop.last %}</ul>{% endif %}
```
I dont understand how `loop.any` works with closing `</ul>` in your latest example. Loop will be closed after first `<li>`

**Comment by olets** [comment]
@deflock you're right, not sure what I was thinking. For that use, it would have to be

```twig
{% set any = false %}
{% for item in items if condition %}
    {% if loop.any %}
      <ul>
      {% set any = true %}
    {% endif %}
    <li>{{ item }}</li>
{% endfor %}
{% if any %}</ul>{% endif %}
```

Not the best example since there `loop.any` isn't a major savings

**Comment by stof** [comment]
`loop.any` does not make any sense in your case. What you want is `loop.first` to do something only during the first iteration. The variable being `true` only for 1 run of the loop body is precisely `loop.first` (and the code is much more readable with it, because you can know that this `<ul>` is added for the first iteration, and not for a random one)

**Comment by stof** [comment]
`loop.last` does not work for `{% for ... if ... %}` btw, because it would force to make the definition of the variable dependent on the conditions for next items (for which conditions will be evaluated only later). The same is true for `loop.length` and `loop.revindex` for the same reason

**Comment by olets** [comment]
@stof `loop.first` is the right solution. Tbh I don't remember what this was for, I would hope I went with that
