### ISSUE TITLE
Capitalize filter capitalizes all letters

### ISSUE THREAD

**Issue by matthewboman** [twigphp/Twig#2604]
My template is being passed a string where the first letter needs capitalized, then it needs concatenated with another string. However, when I apply the capitalize filter, the whole string is capitalized. 

For example:

    {% set heading = type|capitalize ~ ' Status' %}

and 
    
    {% set heading = "#{type|capitalize} Status" %}

both output "WARNING STATUS" event though [the documentation](https://twig.symfony.com/doc/2.x/filters/capitalize.html) says the filter capitalizes only the first letter.

**Comment by stof** [comment]
are you sure that this is the only filter being applied ? `capitalize` is not even applied on `Status` in your snippet.

Here is what I get when using your snippet and displaying the `heading` variable: https://twigfiddle.com/ygqtdi

So please provide a reproducing case to help us debug it. https://twigfiddle.com/ is a good way to provide such reproducing case.

**Comment by matthewboman** [comment]
Strange. Both examples work as they should in Twig Fiddle. 

I believe it's the only filter because it comes through lowercase if I don't use any filter. Also, if I try:

    {% set capital_type = type|capitalize %}
    {% set heading = "#{capital_type} Status %}

    <h2>{{ heading }}</h2>

it prints 'Warning Status' as it should.

**Comment by stof** [comment]
well, your code snippet is incomplete anyway, as it does not display anything (it only defines variable.

I will need a reproducing case to be able to help you (as you can see above, my previous attempt based on what you provided was not reproducing the issue, so I need the full reproducing case rather than an incomplete one that I would need to complete myself).

**Comment by fabpot** [comment]
Closing as there is no more feedback from the @crashspringfield
