### ISSUE TITLE
how to set cookies in Twig

### ISSUE THREAD

**Issue by Ganeshnegi1991** [twigphp/Twig#2605]
how to set cookies in Twig

**Comment by AlexNodex** [comment]
This isn't a twig issue

Please ask elsewhere in places such as Stackoverflow.

**Comment by Ganeshnegi1991** [comment]
ok thanks!!!

**Comment by Ganeshnegi1991** [comment]
Ok Thanks

**Comment by stof** [comment]
Twig cannot set cookies, as Twig is not doing HTTP response. It is only a templating engine.
