### ISSUE TITLE
[Feature Request] Add ability to specify default autoescape strategy for a block in parent/layout template.

### ISSUE THREAD

**Issue by markbeazley** [twigphp/Twig#2608]
In a project I am working on I have a HTML layout.html.twig template file, which has a <script> block which contains a `{% block content %}{% endblock %}` that gets overridden by several different templates, each of which echos out an array of javascript objects including template variables which need to be escaped using the "js" strategy, so as a simplified example:

layout.html.twig
```
<script type="text/javascript">
    cols:[
           {% block content %}{% endblock %}
       ];
</script>
```

view.html.twig
```
{% extends 'layout.html.twig' %}
{% block content %}
    { view:"text", name:"visitDate", value:"{{ date }}", label:"Date/Time:", labelWidth:100, width:285, labelAlign:"right", readonly:true },
{% endblock %}
```

Currently if I wrap the `{% block content %}{% endblock %}` in layout.html.twig in `{% autoescape 'js' %}{% endautoescape %}` the variables aren't escaped using the "js" strategy, it does work if I put the  `{% autoescape 'js' %}{% endautoescape %}` around the contents of the  `{% block content %}{% endblock %}` in view.html.twig, however this makes it a bit harder to maintain, as if you add a new template that extends from layout.twig.html you need to remember to add the `{% autoescape 'js' %}{% endautoescape %}` block to it.

**Comment by fabpot** [comment]
A block is like a PHP method, it cannot be decorated from the outside. So, using the `autoescape` tag within the block is the way to go. What you can do is having two blocks (not tested but should work):

```twig
{% block content_wrapper %}
    {% autoescape 'js' %}
        {% block content %}{% endblock %}
    {% endautoescape %}
{% endblock %}
```
