### ISSUE TITLE
Line-feeds - Which is right, which is wrong: integration tests or TwigFiddle?

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2610]
I've been trying to understand the behavior of Twig with whitespaces and I'm very confused about the discrepencies between the integration tests expectations and what TwigFiddle renders.

Take a look at this fiddle:

https://twigfiddle.com/8pl0nk

Globals excepted, this is the exact same test as fixtures/tags/include/only from the integration tests suite of the project:

```
--TEST--
"include" tag accept variables and only
--TEMPLATE--
{% include "foo.twig" %}
{% include "foo.twig" only %}
{% include "foo.twig" with {'foo1': 'bar'} %}
{% include "foo.twig" with {'foo1': 'bar'} only %}
--TEMPLATE(foo.twig)--
{% for k, v in _context %}{{ k }},{% endfor %}
--DATA--
return array('foo' => 'bar')
--EXPECT--
foo,global,_parent,
global,_parent,
foo,global,foo1,_parent,
foo1,global,_parent,
```

The above test expect the rendered string to be:

```
foo,global,_parent,
global,_parent,
foo,global,foo1,_parent,
foo1,global,_parent,
```

But TwigFiddle renders the same template as:

`foo,_parent,_parent,foo,foo1,_parent,foo1,_parent,`

Notice the lack of line-feeds.

The compiled template doDisplay method confirms that no line-feed is output:

```
protected function doDisplay(array $context, array $blocks = array())
    {
        // line 1
        $this->loadTemplate("foo.twig", "main.twig", 1)->display($context);
        // line 2
        $this->loadTemplate("foo.twig", "main.twig", 2)->display(array());
        // line 3
        $this->loadTemplate("foo.twig", "main.twig", 3)->display(array_merge($context, array("foo1" => "bar")));
        // line 4
        $this->loadTemplate("foo.twig", "main.twig", 4)->display(array("foo1" => "bar"));
    }
```

How can the integration test pass?

What is the real expected result: the one with the line-feeds or the one without the line-feeds?

Thanks to help me clarify this. :)

**Comment by ericmorand** [comment]
To add some confusion, executing the following php script...

```<?php

require_once './vendor/autoload.php';


$loader = new Twig_Loader_Array(array(
  'index' => '{% include "foo.twig" %}
{% include "foo.twig" only %}
{% include "foo.twig" with {\'foo1\': \'bar\'} %}
{% include "foo.twig" with {\'foo1\': \'bar\'} only %}',
  'foo.twig' => '{% for k, v in _context %}{{ k }},{% endfor %}'
));
$twig = new Twig_Environment($loader);
$twig->addGlobal('global', 'global');

echo $twig->render('index', array('foo' => 'bar'));
```

...output:

`foo,global,_parent,global,_parent,foo,global,foo1,_parent,foo1,global,_parent,`

Which is once again different from the expected output of the integration test.

But: PHPUnit pretends that every tests pass with success. How is that possible?

**Comment by fabpot** [comment]
In the test, the `foo.twig` template ends with a newline, which is not the case in your PHP script.
