### ISSUE TITLE
Is the sphinx theme open source?

### ISSUE THREAD

**Issue by slince** [twigphp/Twig#2614]
Hello every one

I want create a chinese document site for twig. [#2597](https://github.com/twigphp/Twig/issues/2597) ; 
 Is the sphinx theme like [https://twig.symfony.com/](https://twig.symfony.com) open source? 

:smiley:

**Comment by stof** [comment]
I don't think it is

**Comment by slince** [comment]
@fabpot   @stof 
Hi, I think this can be open source, which is good for the development of twig. 
Like laravel, there are many mirror sites in China , because laravel.com is open source

**Comment by fabpot** [comment]
The website is indeed not Open-Source yet. I don't really have time to do it now, so I'm closing.
