### ISSUE TITLE
html_attr escaping strategy

### ISSUE THREAD

**Issue by 719media** [twigphp/Twig#2615]
I've looked high and low for an answer to this, and I've come to ask for clarification.

I am using `escape('html_attr')` filter for something like, `<div data-stuff="{{ thing|escape('html_attr') }}" >`. When escaping large strings, this suffers from poor performance.

The best reasons I can find for using `html_attr` instead of `html` is:
1) If you are not using quotes `"` to enclose your attribute (e.g. `<div data-stuff=example>`), then html_attr will work well because it will properly escapes spaces etc. I believe most people avoid this method because, well, it's ugly and horrible. But regardless, browsers do support it.
2) If you are using old versions of IE, it will consider a tick mark \` to terminate the attribute, and html_attr will escape the ticks, avoiding this (e.g. it won't run into the problem of ``<div data-stuff="example`example">``, which would cause `<div data-stuff="example" example>` in old IE)

Can you give me an example of a string which would give undesired outcome if escaped using only the default `escape('html')`, besides the above two scenarios? Thank you for your time.

**Comment by stof** [comment]
instead a quoted HTML attribute, using `html` as strategy is totally fine (except for this old IE behavior that I was not even aware off).

The main use case for using `html_attr` is to be able to display data in an attribute context without quoting it. There might be 2 cases for that:

- displaying an unquoted attribute value (but you could just quote it instead)
- displaying a dynamic attribute **key** (you might still want to forbid some of them to avoid adding a JS event handler, but that's a separate topic here, as even `html_attr` won't prevent it). In this case, using `html_attr` is a must-have as you cannot quote it.

**Comment by 719media** [comment]
OK, thank you for the clarification.
