### ISSUE TITLE
Dump infinite loop

### ISSUE THREAD

**Issue by CoalaJoe** [twigphp/Twig#2619]
At work, we run into the issue that we can not dump in twig, without getting a blank screen and `Fatal Error: Allowed memory size of 268435456 bytes exhausted`.

Found this on StackOverflow:
https://stackoverflow.com/questions/14913859/twigs-dump-function-returns-a-blank-screen#answer-29302069

After applying this patch, it works again. So is this an error on our setup or on the twig lib?

Thanks in advance.

**Comment by stof** [comment]
If you install the DebugBundle, the `dump()` function of Twig will be replaced by an implementation using VarDumper (and you will also get a `{% dump %}` tag which sends the dump to the profiler instead of dumping the variable inline in the output)

**Comment by CoalaJoe** [comment]
@stof Thanks! Adding the debug-bundle explicitly fixed it and added the `{% debug variable %}` is a nice addition.

Why is the change to `dump`not the default?

**Comment by stof** [comment]
Well, Twig cannot require the Symfony VarDumper component. It is independent from Symfony.

**Comment by apfelbox** [comment]
@stof maybe something for the `"suggest"` section in the `composer.json`?
