### ISSUE TITLE
Provide a way to log undefined vars / array indexes / object properties

### ISSUE THREAD

**Issue by ninze** [twigphp/Twig#2622]
Currently twig has 2 modes when dealing with undefined vars: strict or not strict.

If an undefined variable happens in strict mode, an exception is thrown and template rendering is aborted. Even if we catch the exception, there is no way to continue with template rendering.

In case of not-strict mode, the use of undefined var is completely ignored. No notice, warning or any other way to log this event.

By saying "undefined variable" i mean actual undefined variable or an array index or an object property/method. Such undefined vars do happen in life. With complicated template structures (lots of inheritance, includes depending on dynamic data, etc) it is very much possible for a developer to miss those errors (because they are not shown on every page load and testing each possible combination after every template change is tedious) and push the code into production.

It would be very useful to log the use of undefined var and continue with template rendering. Currently there is no such option in twig.

**Comment by fabpot** [comment]
Indeed, there is no way to log undefined vars. That's not something we can implement without a huge performance penalty, so it won't happen.
