### ISSUE TITLE
This value is too long. It should have 8192 characters or less

### ISSUE THREAD

**Issue by aukevann** [twigphp/Twig#2626]
I created a variable with a 350 character text string. When I run this in TwigFiddle I get the error message: "This value is too long. It should have 8192 characters or less.". However, the string is much shorter. When I test a little I can enter a maximum of 274 characters. Is the error message wrong and is the maximum string size 274 characters or does the code not function properly?

Kind regards,
Auke

**Comment by stof** [comment]
The error you get is not an error coming from Twig itself. It is a validation error coming from the form of Twigfiddle. Twigfiddle itself limits the size of templates. It does not allow templates bigger than 8192 chars (see https://github.com/ninsuo/twigfiddle/blob/4eca35f5e2dccd2a60b6b54a91876ce28cc0bb07/web/src/Fuz/AppBundle/Entity/FiddleTemplate.php#L58 for the implementation of this validation constraint).

This issue should be closed, as this is not about Twig but about Twigfiddle, which is a separate project (not maintained by the Twig maintainer, even though it is a cool project)
