### ISSUE TITLE
Help understanding {{ Include }}

### ISSUE THREAD

**Issue by PR4M** [twigphp/Twig#2629]
Hallo, 

I have problem or a question that I already asked on Stackoverflow, is anyone here can help me ? 
[stackoverflow](https://stackoverflow.com/questions/48838636/use-variables-from-extended-template)

I am rendering twig inside head() function for the head.html.twig (this function is getting Course Detail from Database), which is this head.html.twig is included in other 4 templates. But how can I inherit the twig-rendered that already get Course Detail into this 4 templates so I don't have to make Database Queries on these 4 templates just to take or get Course Detail from database?

Thank You!

**Comment by pramanadiputra** [comment]
- 

- [ ] 1.

**Comment by fabpot** [comment]
Using StackOverflow is the way to go.
