### ISSUE TITLE
Sandbox - Range in for loop

### ISSUE THREAD

**Issue by fillmorejd** [twigphp/Twig#2630]
Sandbox allows .. operator for a range even if range function is not allowed.

Fails in sandbox
```
{% for i in range(0, 3) %}
    {{ i }}<br/>
{% endfor %}
```

Works in sandbox
```  
{% for i in 0..3) %}
    {{ i }}<br/>
    {% endfor %}
```

Sandbox setting:
```
$tags = array('if','for');
$filters = array('upper', 'split','capitalize','escape', 'title', 'hello');
$methods = [];
$properties = [];
$functions = [];
$policy = new Twig_Sandbox_SecurityPolicy($tags, $filters, $methods, $properties, $functions);
$sandbox = new Twig_Extension_Sandbox($policy, true);
```

**Comment by fillmorejd** [comment]
In lib/Twig/NodeVisitor/Sandbox.php

Add in doEnterNode function:
```            
if ($node instanceof Twig_Node_Expression_Binary_Range) {
                $this->functions['range'] = $node;
            }
```

Don't know if this is the best fix but it does work.

**Comment by fabpot** [comment]
Operators are always available. There is no way to disable them. I can understand that it seems strange as `..` is purely the equivalent of `range`, but operators are always safe to use. So, I don't think there is any issue to solve here.

**Comment by fillmorejd** [comment]
The issue is that range can be used to create bad loops and should be able to be locked down.

We would like to provide a locked down templating system but a designer can do this and cause issues.

{% for i in 0..9999999) %}
    {{ i }}<br/>
    {% endfor %}

Thanks

**Comment by fabpot** [comment]
@fillmorejd Indeed, you're right. Can you provide a pull request to make `..` and `range` equivalent as far as the sandbox is concerned?

**Comment by fabpot** [comment]
see #2651

**Comment by fillmorejd** [comment]
Thanks you @fabpot !!
