### ISSUE TITLE
Minute format (in date filter)

### ISSUE THREAD

**Issue by nicolallias** [twigphp/Twig#2632]
Hi all,

There seems to be an inconsistence in documentation about the format of a minute of an hour.

[Current twig documentation](https://github.com/twigphp/Twig/blob/2.x/doc/filters/date.rst) and [the previous one](https://twig.symfony.com/doc/1.x/filters/date.html) indicates to follow the  [PHP dateInterval format](http://www.php.net/DateInterval.format), which in turn states:

> I (capitalized i) | Minutes, numeric, at least 2 digits with leading 0 | 01, 03, 59
> -- | -- | --
> i (lowerized i) | Minutes, numeric | 1, 3, 59

But my experience shows that twig uses "lowercase i" for 0-padded and just produces "0" for "uppercase i".

Why is that? Am I facing special cases?

**Comment by stof** [comment]
The DateInterval format is used only when formatting a `DateInterval` object. Most places where you format things are not about DateInterval but about DateTime or timestamp, which use the format of the PHP `date` function, as explained in the doc.

And lowercase i use displaying 0-padded minutes (`date` does not have a way to remove the 0-padding of minutes).

@fabpot thinking about it, I think formatting of DateInterval should have been implemented as a separate filter, as the formats are not the same. What do you think about this ?

**Comment by fabpot** [comment]
The current code for `date` filter makes the difference between `DateInterval` instances and `DateTime` ones. And the docs is quite clear about that behavior: "The format specifier is the same as supported by date, except when the filtered data is of type DateInterval, when the format must conform to DateInterval::format instead."

So, I think there is nothing to change in Twig. Or am I missing something here?
