### ISSUE TITLE
Get the template’s path from a function?

### ISSUE THREAD

**Issue by carlcs** [twigphp/Twig#2634]
In our `Twig_LoaderInterface::getSourceContext()` we return a `Twig_Source` with the template path set. Is there any way to access the path from a Twig function?

I tried a few things and was able to get the path through `debug_backtrace`, basically mimicking `Twig_Error::guessTemplateInfo()` and obviously not my preferred implementation. Another “workaround” I found was to add a tag instead of a function, as it gives access to `Twig_Node::getTemplateName()` which allows me to look-up the path. This is much better, but I need access to the path in a function.

Our use case is to have easy access to non Twig files which are in the same folder as the template. For example a index.css.json file with a mapping of CSS classes, to make [CSS Modules](https://github.com/css-modules/css-modules) possible in Twig projects.

**Comment by stof** [comment]
you could do it by hooking into the way the function gets compiled by using a custom node class (but be careful that you will have to handle of the logic about named arguments in your custom implementation too if you want to keep the same user experience).
There is no built-in way to make Twig inject the source context in the function call.

**Comment by carlcs** [comment]
@stof your answer has put me in the right direction. Thanks much!

**Comment by shoomyth** [comment]
@stof custom node class + `getTemplateName()` worked until v2.8. Now in 2.8+ `getTemplateName()` and `getSourceContext()` in `compile()` return `null`. Is this an expected behaviour?
