### ISSUE TITLE
[Suggestion] Delete the master branch from the repo

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#2638]
Currently, the `master` branch of the repo contains a dev version for 3.0 with only the version updated but outdated compared to 2.x.

As development of Twig 3 has not yet started at all (and we still have room for doing 2.x changes without the need to start a 3.x version removing BC layers), I think this branch causes more harm than good (composer still considers it as the highest available dev version, which can create some harm and there is no good to outweight it currently).
what do you think about deleting it for now ?

**Comment by fabpot** [comment]
Arg, I've just done that but as a consequence, all PRs that targeted master were auto-closed :(
