### ISSUE TITLE
Deviant if tag behavior

### ISSUE THREAD

**Issue by jakulov** [twigphp/Twig#2646]
I've notices a strange result of rendering template

`{% set a = {`
`    'one': 'one',`
`    'two': 'two',`
`    1: 'one1',`
`    2: 'two2'`
`} %}`
`{% set selected = 0 %}`
`<select>`
`{% for id, name in a %}`
`    <option value="{{ id }}" {% if selected == ('' ~ id) %}selected{% endif %}>{{ name }}</option>`
`{% endfor %}`
`</select>`

Looks like:

`<select>`
`<option value="one" selected>one</option>`
`<option value="two" selected>two</option>`
`<option value="1" >one1</option>`
`<option value="2" >two2</option>`
`</select>`

It seems to bee deviant result, cause different values 'one' and 'two' are both equals to empty string 

**Version v1.34.4**

**Comment by jvasseur** [comment]
This isn't a bug in twig but "normal" PHP behavior : https://3v4l.org/ZL9VF.

When comparing a string and an integer PHP converts the string into an integer, since `'one'` and `'two'` are not valid numerical strings they are converted to `0`.

**Comment by jakulov** [comment]
My bad, thanks @jvasseur . 
It seems like I should use `{% if ('' ~ selected) == ('' ~ id) %}selected{% endif %}` to get result I needed.
