### ISSUE TITLE
New related project: Twing is TwigPHP in TypeScript, with full Twig support!

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2653]
Hi,

Some months ago I took the decision to write my own implementation of Twig for Node.js, using TypeScript as source language. You may have noticed that I've been asking some strange (and uneducated) questions here and this is why:

https://github.com/ericmorand/twing

It is basically a transpiling of TwigPHP in TypeScript with obviously some language specifics here and there (yes `Twig_Error::guessTemplateInfo`, I'm looking at you) so every class implemented in TwigPHP is present in Twing (or will be once I'm done with the unit tests). But the most important part is that I wanted Twing to pass all the integration tests of TwigPHP without compromise - and it's been a great success.

Like TwigPHP, Twing create an intermediate template, but in JavaScript, and is able to cache it on the filesystem. Here is for example what the intermediate template of `Hello {{ name }}!` looks like:

```javascript
const Twing = require('twing/lib/runtime');

module.exports = {};


/* index.twig */
module.exports.__TwingTemplate_c1154b7f7a0a3a5ca75a0d05890893195ae6b165952aaa0912ded45b5342cb75 = class __TwingTemplate_c1154b7f7a0a3a5ca75a0d05890893195ae6b165952aaa0912ded45b5342cb75 extends Twing.TwingTemplate {
    constructor(env) {
        super(env);

        this.parent = false;

        this.blocks = new Twing.TwingMap([
        ]);
    }

    async doDisplay(context, blocks = new Twing.TwingMap()) {
        // line 1
        Twing.echo("Hello ");
        Twing.echo(await this.env.getFilter('escape').getCallable()(...[this.env, (context.has("name") ? context.get("name") : null), "html", null, true]));
        Twing.echo("!");
    }

    getTemplateName() {
        return "index.twig";
    }

    isTraitable() {
        return false;
    }

    getDebugInfo() {
        return new Map([[19,1]]);
    }

    getSourceContext() {
        return new Twing.TwingSource(``, "index.twig", "");
    }
};
```

As you can see it's very close to the PHP equivalent. Of course since autoloading is not a thing in JavaScript and Node.js, Twing also comes with a lightweight runtime library to fuel the templates. It obvisouly also comes with the complete discrete library. And Twing is natively asynchronous - which explains the usage of `async `and `await `keywords.

1.0 milestone is just a few weeks away and it will come with 100% code coverage, full documentation and a catch-up with the latest relase of TwigPHP - currently, Twing is based on TwigPHP 2.4.4. By the way I can't wait to see what improvements TwigPHP 2.4.6 brings to the table.

And later that year, we'll have source map support.

Anyway, now that the presentation is done, I want to talk about the potential copyright issues. Being a transpilation for the most part, and the future documentation being basically a copy and paste from TwigPHP documentation, I want to make sure it's very clear for everybody that Twig is not a new thing but is a port of TwigPHP in TypeScript.

Of course, my first move will be to update the README to make that clearer. But I'm wondering if I should keep the names of the original author in the code comments, if I need to put some copyright mentions on the documentation and more generally, what the TwigPHP maintainers and community think is the most fair way to ensure that TwigPHP authors gets all the credit they deserve.

I'd be super glad if I could receive some input from the community on that subject. And of course on Twing more generaly.

Thanks for your time.

**Comment by fabpot** [comment]
I'm no lawyer, but I think you need to keep the copyright (both code and docs), especially in the docs as it will be more or less the same.
