### ISSUE TITLE
convert_encoding is not checking iconv accessibility, not using mbstring by default

### ISSUE THREAD

**Issue by 13DaGGeR** [twigphp/Twig#2654]
despite [docs](https://twig.symfony.com/doc/2.x/filters/convert_encoding.html), 
**iconv** used without check of **mbstring**
[check here](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Extension/Core.php#L1124)

**Comment by stof** [comment]
The doc is outdated. As of Twig 2, iconv is required (was done in https://github.com/twigphp/Twig/pull/1895)

**Comment by fabpot** [comment]
@13DaGGeR Can you update the docs and submit a pull request?

**Comment by 13DaGGeR** [comment]
@fabpot [done](https://github.com/twigphp/Twig/pull/2655)
