### ISSUE TITLE
|default doesn't override strict variable checks for some array expressions in Twig >=2.4.5

### ISSUE THREAD

**Issue by 00dani** [twigphp/Twig#2657]
I think it's #2618 that's caused the issue. If you have strict variables turned on, an expression like this is perfectly harmless in Twig 2.4.4, but causes an error in 2.4.5 and 2.4.6 because `nonExistentArray` isn't defined.
```twig
{{ nonExistentArray[0] | default(null) }}
```
It looks like Twig's now not safely checking whether `nonExistentArray` actually exists, only whether it's an array or arraylike?

**Comment by fabpot** [comment]
It works for me. See https://twigfiddle.com/8zn20g

If that does not work for you, can you give us more details?

**Comment by 00dani** [comment]
Ah, my fault for not testing that the above really is a minimal example, sorry. It doesn't occur with `nonExistentArray[0]` but it *does* occur if you attempt to perform further navigation, such as property access or indexing. Both of these fail - see https://twigfiddle.com/8zn20g/3
```twig
{{ nonExistentArray[0][1] | default(2) }}
{{ nonExistentArray[1].uncool | default('cool') }}
```
