### ISSUE TITLE
[Feature Request] include_once Template

### ISSUE THREAD

**Issue by homersimpsons** [twigphp/Twig#2662]
Thank you for this great templating engine but I miss a feature : `include_once`

I have a js script that should be included only once with a component.
Currently I have to think to include this js each time I use the component, but I would like to include this only once in my component (if used)

I can't find something like that in the [doc](https://twig.symfony.com/doc/2.x/)

I tried to do
- `include_once` in my files (of course this doesn't exist)
```
{{ include_once('component/date.js.twig') }}
```
- Declare a variable if included inside template (This doesn't work because variables are locals)
```
{% if TEMPLATE_INCLUDED is not defined %}
  {% set TEMPLATE_INCLUDED = true %}
  ...
{% endif %}
```

**Comment by ericmorand** [comment]
@homersimpsons, you can use global variable for this, Twig supports that:

`$twig->addGlobal("included", false);`

Then:

```twig
{% for i in 1..10 %}
    {% include "index.js.twig" %}
{% endfor %}

```

```twig
{# index.js.twig #}
{% if not included %}
    DEPENDENCY INCLUDED
    {% set included = true %}
{% endif %}
```

Would render...

`        DEPENDENCY INCLUDED
`
...only once.

Not super ideal because you have to declare those variables outised of the templates themselves and have to add a new one eveytime you need to include once something.

I think that having the option to set a variable globally in the template itself would solve your problem and a lot of others.

**Comment by ericmorand** [comment]
@homersimpsons, doesn't seem to work. When removing the `addGlobal `line, DEPENDENCY INCLUDED is still rendered only once. So hacving a global variable here doesn't make a difference.

**Comment by homersimpsons** [comment]
I'm on symfony... So I tried:
`twig.globals.TEMPLATE_INCLUDED: false`
and: 
```
{% if not TEMPLATE_INCLUDED %}
    DEPENDENCY INCLUDED
    {% set TEMPLATE_INCLUDED = true %}
{% endif %}
```

This doesn't work, removing the `twig.globals.TEMPLATE_INCLUDED: false` I've got an error: `
Variable "TEMPLATE_INCLUDED" does not exist.`

**Comment by stof** [comment]
setting a variable will not replace the global variable anyway. It will only shadow it locally.

**Comment by ericmorand** [comment]
Would a PHP object sent as data keep its state?

I think about something like this:

```
// assume IncludeManager class exists somewhere
$includeManager = new IncludeManager();

$twig->render('index', array(
    includeManager => $includeManager
));
```

And then in the template, something like this:

```
{% if not includeManager.isIncluded('foo') %}
    {% include 'foo' %}
    {% do includeManager.setIncluded('foo') %}
{% endif %}

```

**Comment by xabbuh** [comment]
The simplest solution probably is a Twig extension which exposes two functions: one to register files and to retrieve the collected files. Whereever want to trigger the inclusion of a file you will then call the adder and have some code that would use the collected data to render them all. If the extension treats the collection of templates as a set, you will ensure to render templates only once.

**Comment by fabpot** [comment]
I'm closing this issue as this is not something I want to implement in core. Thanks for opening the discussin
