### ISSUE TITLE
Perfomance of Twig_NodeTraverser::traverseForVisitor

### ISSUE THREAD

**Issue by covex-nn** [twigphp/Twig#2665]
I tried to find out why `cache:clear` command takes so much time. I created a project and then execuded a clear cache command with xdebug.profiler:
```
composer create-project symfony/skeleton . ^3.4
composer require sonata-project/doctrine-orm-admin-bundle doctrine/doctrine-bundle
php -d xdebug.profiler_enable=1 -d xdebug.profiler_output_dir=. bin\console cache:clear
```

I found, that [Twig_NodeTraverser::traverseForVisitor](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/NodeTraverser.php#L62) was called 242594 times, and it took 15.5% of all execution time (on Windows, PHP 7.1)

![Twig_NodeTraverser::traverseForVisitor was called 242594 times](https://joxi.net/zAN4qGRtlpbLpm.jpg)

Here is method code:

```php
private function traverseForVisitor(Twig_NodeVisitorInterface $visitor, Twig_Node $node)
{
    $node = $visitor->enterNode($node, $this->env);
    foreach ($node as $k => $n) {
        if (false !== $n = $this->traverseForVisitor($visitor, $n)) {
            $node->setNode($k, $n);
        } else {
            $node->removeNode($k);
        }
    }
    return $visitor->leaveNode($node, $this->env);
}
```

I found, that `traverseForVisitor` never returns `false` actualy, it always returns `Twig_Node`! So i guess main loop could be replaced with this:

```php
    foreach ($node as $k => $n) {
        $node->setNode($k, $this->traverseForVisitor($visitor, $n));
    }
```
Am i right? Or i missed something?
Even if i am wrong, this method should be optimized, 15% is to much =)

**Comment by fabpot** [comment]
"Even if i am wrong, this method should be optimized, 15% is to much =)" -> not sure what you mean here. But it you find ways to optimize that part of the code, I would be more than happy to have a look.

Regarding the optimization you proposed, it's not possible as returning `false` is actutally possible when a node should be removed from the tree (see the `Twig_BaseNodeVisitor` phpdocs). Anyway, I doubt that removing the check to `false` would bring any performance improvement.

**Comment by covex-nn** [comment]
@fabpot i found, that `traverseForVisitor` often returns a same node (a same object!). So, i added a check if a node was changed:

```php
if (false !== $m = $this->traverseForVisitor($visitor, $n)) {
    if ($m !== $n) {
        $node->setNode($k, $m);
    }
} else {
    $node->removeNode($k);
}
```

With a new check `traverseForVisitor` became a little faster: 14.7% of all execution time against 17.47%. This happened because ~75K calls to `Twig_Node::setNode` were skipped!

* ![with a check](http://joxi.ru/a2XD5E8cyE4ND2.jpg)
* ![original](http://joxi.ru/krD4nGVt0Q4RYr.jpg)

That is all i can do. Unfortunately 2.5-2.8% is not much =(

// Also i tried to [walk a node tree without recursion](https://gist.github.com/covex-nn/5a42c98402cb95f4125cae4ac2531c31), but it became even worse (22% of all execution time).

**Comment by fabpot** [comment]
It's indeed not that much (and even less without xdebug as you are mainly measuring the overhead of instrumenting the function call). Anyway, I think this is a good small optimization. Can you submit a pull request on the 1.x branch?

**Comment by covex-nn** [comment]
Done =)
