### ISSUE TITLE
For loop incrementation

### ISSUE THREAD

**Issue by 12345678--** [twigphp/Twig#2666]
{% set images = images|split('\n') %}
				{% set links = links|split('\n') %}
				{% set titles = titles|split('\n') %}
				{% set descriptions = descriptions|split('\n') %}
			 
			    {% for images1 in images %}
                 		<div class="slideshow_item">
				<div class="image">
						<a href="---------link"">
						<img src="{{ images1 }}" width="600" height="400" /></a>

					</div>
					<div class="data">
					
					<h4>
					--------title
					</h4>
				
					<p>-------description</p>
				</div>
			    </div>
		
				{% endfor %}
			</div>
		</div>

Like images how to get all other values like link. titles, descriptions inside the loop. 

Please help me.

**Comment by xabbuh** [comment]
It looks like what you are looking for is the special `loop` variable that is provided by Twig:

```twig
{{ links[loop.index0] }}
```

see https://twig.symfony.com/doc/2.x/tags/for.html#the-loop-variable

**Comment by 12345678--** [comment]
Thank you very much.

It works.

**Comment by stof** [comment]
another way is to also use the index in your array when iterating:

```twig
{% for index, images1 in images %}
    {{ links[index] }}
{% endfor %}
```
