### ISSUE TITLE
Defective functions/date test

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2667]
This test https://github.com/twigphp/Twig/blob/092871ad2d511b29191f4684bbd6b803e2f80aed/test/Twig/Tests/Fixtures/functions/date.test#L4 is not reliable.

It's possible that `date()` and `date('now')` differ from 1 second if `date()` is executed close enough to the shift to the next second - for example at 8:00:00.999. It's then possible for the test suite to fail with a false positive.

The following code demonstrates that:

```
<?php

require_once './vendor/autoload.php';

$loader = new Twig_Loader_Array(array(
  'index.html.twig' => "{{ date().format('r') == date('now').format('r') ? 'OK' : 'KO' }}"
));
$twig = new Twig_Environment($loader);

$r = '';
$ok = true;

while ($ok) {
  $r = $twig->render('index.html.twig');

  $ok = ($r === 'OK');
}

echo $r;
```

Were `date()` and `date('now')` always equal, that code would execute forever. It actually last just a few seconds before failing.

**Comment by fabpot** [comment]
We could use the `@group time-sensitive` annotation from Symfony PHPUnit Bridge, but that only works with namespaced code, which we don't have yet.

**Comment by fabpot** [comment]
I'm closing for now as I don't see any easy solution.
