### ISSUE TITLE
v2.4.5+ regression: is defined

### ISSUE THREAD

**Issue by Bilge** [twigphp/Twig#2669]
The following code compiles fine in v2.4.4:

```php
{% if games[0].movement is defined %}
```

In v2.4.7 it emits the following error in strict mode:

>  Variable "games" does not exist.  

It is true the variable does not exist, but the `is defined` check is supposed to check that without stopping with an exception.

**Comment by Bilge** [comment]
The regression started in v2.4.5.

**Comment by xabbuh** [comment]
Looks like this could be caused by the same as #2657.

**Comment by fabpot** [comment]
Closing as a duplicate
