### ISSUE TITLE
Between test

### ISSUE THREAD

**Issue by JulienRAVIA** [twigphp/Twig#2675]
A between test would be awesome !
I know we can use a function for that or a >= <= condition but a test is better i think
Example : 
`{% if '2018-05-14' is between '2018-05-10' and '2018-05-20' %}  {# return false %}`
`{% if 5 is between 0 and 10 %}  {# return true %}`
`{% if 'b' is not between 'a' and 'c' %} {# return false %}` 

better than
`{% if 2 >= 0 and 2 <= 4 %}`

**Comment by stof** [comment]
I fear this syntax will become a nightmare to implement, but repurposing `and` with a totally different operator priority (and having to deal with a complex operator syntax being `<expr>` is between <expr> and <expr>`).

Thus, I'm not even sure whether it is possible to make such syntax unambiguous regarding the `and` (as it can be part of expressions as a boolean operator)

**Comment by jvasseur** [comment]
This could be implemented as a test, this will give us a syntax like `if value is between(min, max)`.

**Comment by JulienRAVIA** [comment]
jvasseur, still nice to implement as a test !

**Comment by fabpot** [comment]
@JulienRAVIA Thanks for the suggestion. We try to limit the number of tests/functions/filters/... in core. I don't think this one should be added for a couple of reasons, but mainly because of the complexity of the implementation and the verbosity that does not feel like anything else in Twig.
