### ISSUE TITLE
Documentation for `if` has innacurate/incomplete edge cases

### ISSUE THREAD

**Issue by ismael-miguel** [twigphp/Twig#2677]
Currently, there's the following list of edge cases, on https://twig.symfony.com/doc/2.x/tags/if.html

![edge cases](https://user-images.githubusercontent.com/10207857/39183829-3e420954-47b9-11e8-8dad-e395398bf177.png)

This is innacurate/incomplete, as these edge cases have edge cases.

These are my findings:
- empty string: `false`
- numeric zero: `false`
- whitespace-only string: `false`?
    Running `echo !!'          ';` shows 1
    Running `echo '          ' == 0;` shows 1 
    Running `echo '          ' == '0';` doesn't display anything
    The whitespace-only string (or any string) will be casted to a number when compared for equality with a number. Otherwise, everything is casted to a string.
- empty array: `false`
    Everything is casted to an array when comparing to an empty array, except boolean values. In that case, the empty array is casted to the boolean value (`false`)
- null: `false`
    Null is a special value. Null will cast to a string when comparing with a string, to a number when comparing to a number **but** won't be cast to an empty array when comparing to an empty array.
    My guess is due to the fact that you can write `function xyz(array $arg = null){ [...] }`, to distinguish between an empty array and a function with an optional parameter.

Everything below is correct.

You can see it in action on http://sandbox.onlinephpfunctions.com/code/e4dc15a4f29cd6ef6a7498ad27ac202f5f874612

Should this information be added to the documentation? Is it fine the way it is?

**Comment by xabbuh** [comment]
You are mixing two things here. The table is not about comparing the values with other arbitrary values, but how they will be evaluated in a context where a boolean is expected.

So basically in a construct like this:

```twig
{% if value %}
    value evaluates to true
{% else %}
    value evaluates to false
{% endif %}
```

**Comment by stof** [comment]
your sandbox code is not covering the behavior of the boolean evaluation, but of the `==` operator, which is a totally different things (and is not what the `{% if %}` documentation needs)

**Comment by ismael-miguel** [comment]
Then there are some edge cases missing.

The string `'0'` is a falsy value in PHP, and isn't mentioned in the table.
Also, `NAN` and `INF` are truthy, which may happen from some mathematical calculations.

**Comment by xabbuh** [comment]
Would you like to contribute the missing edge cases? :) The file to edit would be https://github.com/twigphp/Twig/blob/1.x/doc/tags/if.rst.
