### ISSUE TITLE
 call_user_func() expects parameter 1 to be a valid callback, no array or string given ....

### ISSUE THREAD

**Issue by silsuer** [twigphp/Twig#2679]
I use twig with swoole extension, and the swoole http server can run when I access the page,but It always print a Warning like this : `PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /var/www/Aceberg/vendo
r/twig/twig/lib/Twig/Extension/Escaper.php on line 72` in my terminal  .

I need Help

**Comment by stof** [comment]
Can you show you configured the default strategy for your Twig instance ?

**Comment by fabpot** [comment]
Closing as there is no feedback.
