### ISSUE TITLE
Is the line tag officially supported?

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2682]
There is a `line `tag in the TwigPHP implementation:

`{% line 5 %}`

It's actually working (https://twigfiddle.com/j620v9) and even has a test in the Lexer test suite.

But the documentation makes zero mention of it and it's not quite clear what it does even from reading the sources: it seems to just add some _virtual_ lines to the output (look at the compiled template in the TwigFiddle above).

What is the exacte purpose of this tag? Is it supported? Should we update the doc? Remove it entirely?

**Comment by fabpot** [comment]
That's supported but only for very specific use cases. See #353 for more details about why it was added. I don't think it should be documented.

**Comment by stof** [comment]
See https://twigfiddle.com/j620v9/2 for a fiddle showing this usage. If you look at the location of the error being reported, you will see that it says `main.twig:6`

**Comment by ericmorand** [comment]
Thanks to both of you.
