### ISSUE TITLE
Marker in condition

### ISSUE THREAD

**Issue by labby** [twigphp/Twig#2683]
Hi there
searched the docs but couldn't find anything.
If I user a marker within a condition I get a punctuation error:
`{%  if marker1.my_marker == {{ marker2.my_marker2 }} %}`
I tried several type of writings for the second marker but always get an (different) error.
How can I write this to get it work?

**Comment by xabbuh** [comment]
I don't know what you mean with marker, but if you just want to compare two properties from different objects it's as easy as `{% if marker1.my_marker == marker2.my_marker2 %}`.

**Comment by labby** [comment]
mmh. thanks.
As I often used this I am not quite sure if that was my question. :-)
I have obvoiusly worked too long :-(
