### ISSUE TITLE
Seconds part gets lost in combination of doctrine scalarresult and date filter

### ISSUE THREAD

**Issue by Gwynei** [twigphp/Twig#2684]
My query function
```php
    public function testQuery()
    {
        return $this->createQueryBuilder('test')
            ->select('
           test.created
          ')
            ->getQuery()
            ->getScalarResult();
    }
```

The 'created' attribute
```php
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;
```

But because I'm using getScalarResult here for reasons, this is how the dump() looks like:
```php
array:1 [▼
  0 => array:10 [▼
    "created" => "2018-05-17 09:37:23"
  ]
]
```

Then, I need a datatype date inside Twig for my own custom filter. But when doing this in Twig inside a for loop:
`
{{ dump(row.created|date }}
`

I get:
`
string(18) "May 17, 2018 09:37"
`

Looks like I'm losing the seconds part. Even when I'm doing this:

`
{{ dump(row.created|date('Y-m-d H:i:s')) }}
`

I get:

`
	string(19) "2018-05-17 09:37:23"
`

Is this a bug or a feature? In a way I'm looking for a way to convert a string value into a date value inside of twig. Chaining filters an idea?

**Comment by stof** [comment]
The default format for the `date` filter does not include seconds (but you can configure it): https://github.com/twigphp/Twig/blob/v2.4.8/lib/Twig/Extension/Core.php#L14
So this is not a bug at all. It is only the format being used for the formatting.

Btw, the `|date()` filter is not about converting a string into a date, but about formatting a date as a string.
If you want to create a DateTime object in Twig (either from a string containing a date, or from the current time), use the `date()` function.

**Comment by Gwynei** [comment]
You're totally right. Turns out I was looking for the date function instead of the date filter. So this fixed my problem:

`
{{ date(row.created)|createdAgo }}
` 

Thanks a bunch.
