### ISSUE TITLE
Symfony not loading runtime Twig extension

### ISSUE THREAD

**Issue by numediaweb** [twigphp/Twig#2692]
I followed the example on Symfony 3.4 docs: [Creating Lazy-Loaded Twig Extensions][1] in order to load a Twig extension at runtime but it doesn't load: the function is not known

**IN: src/PlotlyBundle/Twig/AppRuntime.php**

    <?php
    namespace PlotlyBundle\Twig;
    
    class AppRuntime
    {
        public function __construct()
        {
        }
    
        public function biDraw()
        {
            return 'awesome text here';
        }
    }

**IN: src/PlotlyBundle/Resources/config/services.yml**

    services:
        plotly.twig_runtime:
            class: PlotlyBundle\Twig\AppRuntime
            public: true
            tags:
                - { name: twig.runtime }

**IN: src/PlotlyBundle/Twig/AppExtension.php**

    <?php
    namespace PlotlyBundle\Twig;
    
    use PlotlyBundle\Twig\AppRuntime;

    class AppExtension extends \Twig_Extension
    {
        public function getFunctions()
        {    
            return [
                new \Twig_SimpleFunction(
                    'bi_draw',
                    array(AppRuntime::class, 'biDraw')
                ),
            ];
        }
    }

**IN: src/AppBundle/Controller/DashboardController.php**

       $twig = $this->get('plotly.twig_runtime');
        return $this->render(
            'dashboard/index.html.twig'
        );

**IN: app/Resources/views/dashboard/index.html.twig**

    {{ bi_draw() }}

  [1]: https://symfony.com/doc/3.4/templating/twig_extension.html#creating-lazy-loaded-twig-extensions

**Comment by stof** [comment]
I think the part you missed is the registration of the Twig extension itself. This step (described in the previous section of the doc chapter) is still necessary, even if the implementation uses a lazy-loaded runtime.

**Comment by numediaweb** [comment]
Thanks @stof I fixed it by autowiring as [I posted here](https://stackoverflow.com/a/50564237/232082) and also sent a [PR](https://github.com/symfony/symfony-docs/pull/9841) to update the docs.
