### ISSUE TITLE
Twig matrix

### ISSUE THREAD

**Issue by Korbeil** [twigphp/Twig#2693]
Hello !

Here is my first issue for `Twig`, and I'm gonna talk about matrix (this is the word I choosed to describe my problem, it's only a first draw, he can change with time).

## What are matrix ?
Basically, a matrix is a set of global variables that can modulate the content of a set of views.

Like that we can compile all views based on matrix (actually, Symfony framework do all compilation work on `cache:warmup`, which does not allow us to have all possible context variables such as current language).

All the matrix would be passed to `\Twig_Environment` on `__construct(Twig_LoaderInterface $loader, $options = array())` inside `$options` array as following:
```php
$options['matrix'] = [
  [
    'name' => 'belgium',
    'dataset' => [
      'link' => 'https://www.my-lawyer.be/',
      'logo-light' => 'https://www.my-lawyer.be/img/logo/my-lawyer.be/logo-light.svg',
    ]
  ],
  [
    'name' => 'france',
    'default' => true,
    'dataset' => [
      'link' => 'https://www.mon-avocat.fr/',
      'logo-light' => 'https://www.mon-avocat.fr/img/logo/mon-avocat.fr/logo-light.svg',
    ]
  ]
];
```
(I took example on a website I already worked for that is running multiple website on same codebase, the idea is to have a full preset of variables matching each hostname)

A matrix variable would be same as actual global variable when compiling (`\Twig_Environment()->addGlobal($name, $value)`).
Only difference is that each matrix set runs a different compilition for every views and matrix set is also considered in `\Twig_Environment::$optionsHash` variable to make this compiled view unique.
On rendering, first matrix would be define as default used matrix and you will be able to choose which matrix you want with something like: `\Twig_Environment->setMatrix($name)`

## Why matrix ?

Like that, we would be able to compile templates based on variables preset and making everything faster ! :muscle:

Following my example, the idea is to make things simpler for codebase that are managing more than one environment (another possible name for this feature ?) on production.

## Follow up
- What you guys thinks about the "matrix" concept ?
- Is it something we could / should apply to Twig ?
- If not, is there any way to make this works with actual Twig behavior ?

**Comment by stof** [comment]
Global variables don't impact the compilation of templates. Variable values are used only at rendering time.

so there is actually no need for this feature at all.

**Comment by curtchan** [comment]
Technically, it is slowing down (something for sure) instead of speeding up. As stof mentioned, variables are used during render time - and you are working with a matrix of variables instead, which imo is wrong to keep in your repository (because technically you are passing shared variables to all pages that use same configuration), what you should do instead, is make use of `parameters.yml` which is meant for use of custom variables, server dependent, and pass them as global to Twig.

**Comment by fabpot** [comment]
Thanks for the proposal. I'm going to close the issue because that's not something that I want to add to Twig core.
