### ISSUE TITLE
[RFC] Rename (or alias) Environment -> Twig

### ISSUE THREAD

**Issue by lyrixx** [twigphp/Twig#2694]
It always a bit weird to write the following code:

```php
    public function __construct(Environment $twig)
    {
        $this->twig = $twig;
    }
```

I would prefer to type-hint with Twig instead of Environment. 

WDYT ?

**Comment by ericmorand** [comment]
Wouldn't this be better:

```php
public function __construct(Environment $env)
{
    $this->env= $env;
}
```

**Comment by lyrixx** [comment]
@ericmorand `$this->env` does not make me think about twig :/ `$env` usually refers to environment variables

**Comment by fabpot** [comment]
That would be `Twig\Twig` then, right? `Twig_Environment` worked better for sure.

**Comment by fabpot** [comment]
`as TwigEnvironment` works well enough to not break BC.

**Comment by fabpot** [comment]
will be fixed by #2857 :)

**Comment by lyrixx** [comment]
Thanks 😁

**Comment by fabpot** [comment]
see https://github.com/twigphp/Twig/pull/2857#issuecomment-469601425 for the reasons why I won't do it.
