### ISSUE TITLE
Grapheme cluster boundary support

### ISSUE THREAD

**Issue by mogsie** [twigphp/Twig#2703]
First of all, thanks for twig!  :1st_place_medal: 

## Background

The [Unicode Technical Report 29](http://unicode.org/reports/tr29/) describes how to segment text.  It describes how to understand the unicode string "🇫🇷" as being one character long:  I'm sure you're aware of TR29 and grapheme cluster boundaries, but for any readers who don't know, the "french flag emoji" (🇫🇷) is called a "grapheme cluster" and TR29 describes how this and other emojis are encoded and how they are detected.

``` php
var_dump(unpack('C*', '🇫🇷'));
array(8) {
  [1]=>int(240)  [2]=>int(159)  [3]=>int(135)  [4]=>int(171)
  [5]=>int(240)  [6]=>int(159)  [7]=>int(135)  [8]=>int(183)
}
```

php-intl supports grapheme cluster boundaries, with a concise set of string manipulation functions:

``` php
strlen('🇫🇷') // 8
mb_strlen('🇫🇷') // 2
grapheme_strlen('🇫🇷') // 1
```

## Question

Twig uses the multibyte string library to calculate lengths, but this only counts codepoints.  This has the consequence that a string might be chopped in the middle of a single character.  In some use-cases strings must be split along grapheme cluster boundaries, rather than unicode codepoints.

*I'd like to hear what the maintainers think about this issue*.  I opened this issue since the twig repo has no mention of grapheme clusters, and I'd like future people to have at least one hit in the Twig repository.

We will probably implement what we need in PHP-space, using the grapheme_ functions directly, exposing the functionality as twig filters or similar.

## Comments

My own thinking is that if you're doing grapheme cluster boundary splitting in twig, you're probably doing it wrong; that you should be doing this elsewhere, avoiding the need to do string manipulation in twig-space at all.

**Comment by nicolas-grekas** [comment]
You're 100% right, string management in a template language like Twig should work at the grapheme cluster level.
*Yet*, doing so is technically complex if we want to achieve both portability and performance. The current situation is a compromise for both.
There is lower level work ongoing on https://github.com/symfony/symfony/pull/22184 to provide a generic UTF-8 library that could be plugged in Twig later on maybe.
