### ISSUE TITLE
Custom twig tag

### ISSUE THREAD

**Issue by christophemassin** [twigphp/Twig#2705]
Hello, 

I m trying to make a custom twig tag. 

The output in the compiled file that i m trying to get is this  : 

` if( twig_escape_filter($this->env, $this->getAttribute(($context["registeredUser"] ?? $this->getContext($context, "registeredUser")), "hasRole", array(0 => "admin"), "method"), "html", null, true)) {
`
However, i can't manage to have my node give me that out : 

```
class HasRoleNode extends Twig_Node
{
	protected $_registeredUser;

	public function __construct($role, $garde, $lineno, $tag)
	{

		parent::__construct([], ['role' => $role, 'garde' => $garde], $lineno, $tag);
	}

	public function compile(Twig_Compiler $compiler)
	{

		$compiler
			->addDebugInfo($this)
			->write('if( twig_escape_filter($this->env, $this->getAttribute(($context["registeredUser"] ?? $this->getContext($context, "registeredUser")), "hasRole", array(0 => "'.$this->getAttribute('role').'"), "method"), "html", null, true)) {
')
			->raw("\n")
		;
	}
}
```

Whatever i try, i can't find a way to have it compile without error. 

Any help / doc would be appreciate ! 

Thanks

**Comment by delboy1978uk** [comment]
how **does** it output?

**Comment by christophemassin** [comment]
Currently, it give me an error when displaying the twig file : 

An exception has been thrown during the rendering of a template ("Method Illuminate\Database\Query\Builder::hasRole does not exist.") in "/var/www/src/resources/views/organisation/profiles/show.twig" at line 59. 

and it give me this in the compiled file 

```
        // line 59
        if( twig_escape_filter($this->env, $this->getAttribute(($context["registeredUser"] ?? $this->getContext($context, "registeredUser")), "hasRole", array(0 => "admin"), "method"), "html", null, true)) {

        // line 60
        echo "\t\t\t\t<a href=\"";
        echo call_user_func_array($this->env->getFunction('route')->getCallable(), array("settings.access_right.edit", array("profile" => $this->getAttribute(($context["profile"] ?? $this->getContext($context, "profile")), "id", array()))));
        echo "\" class=\"ui left labeled green right floated icon button admin-bp-btn--info button\">
\t\t\t\t\t";
        // line 61
        echo twig_escape_filter($this->env, $this->getAttribute(($context["misc"] ?? $this->getContext($context, "misc")), "iconFA", array(0 => "remove", 1 => array("color" => "#fff", "class" => "color-bg--success")), "method"), "html", null, true);
        echo "
\t\t\t\t\t";
        // line 62
        echo call_user_func_array($this->env->getFilter('trans')->getCallable(), array("profiles.show.role"));
        echo "
\t\t\t\t</a>
\t\t\t";
        // line 64
        }
        // line 65
        echo "\t\t";
    }
```

the issue is that the function was not called on the good object :) Thanks for the help !

**Comment by delboy1978uk** [comment]
no problem, i just saw you were trying it on a laravel query builder, and indfeed it has no method! https://laravel.com/api/5.3/Illuminate/Database/Query/Builder.html
