### ISSUE TITLE
RegEx: {{ dump(' ' matches '/\s/') }} returns 0

### ISSUE THREAD

**Issue by KajdeMunter** [twigphp/Twig#2711]
in RegEx `/\s/` should match any whitespace character. Twig matches none:

```
{{ dump(' ' matches '/\s/') }}
```
Returns 0 when it should return 1.

**Comment by stof** [comment]
you issue is that Twig strings require the `\` to always be escaped to produce a `\` in the string (unlike PHP strings). Your regex is not `/\s/` but `/s/` due to that.
For the proof, see https://twigfiddle.com/0smdr1 and look at the compiled template.

**Comment by KajdeMunter** [comment]
I see! thank you.
