### ISSUE TITLE
[Proposal] Deprecate the usage of unescaped backslashes not belonging to an escape sequence

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#2712]
Currently, using a backslash without escaping it and without being part of an escape sequence is silently ignored (as if any unknown escape sequence `\<char>` would produce `<char>`).
This is often confusing for PHP developers (see #2711), as this is not how PHP works in single-quoted strings (it considers it as a backslash).

I suggest triggering a (compile-time) deprecation warning for such case (and turn it into a syntax error in 3.0).
Making it produce a backslash would be a BC break (as it would change existing strings). Thus, it would make it impossible to add new escape sequences without BC break.

**Comment by stof** [comment]
The implementation actually relies on PHP to handle this, thanks to https://php.net/stripcslashes so this might not be easy to implement actually.

Maybe using `$rawSource === addcslashes($strippedSource)` could allow detecting this case though for the deprecation case (this will not make it easy to implement keeping the backslash, but this is not my proposal anyway)

**Comment by stof** [comment]
hmm, `addcslashes` is a pain, as it requires passing it a charlist, but `stripcslashes` has a list of builtin escape sequences, which would have to be duplicated...

**Comment by stof** [comment]
and the case of `\x<code>` will also be a pain...

**Comment by fabpot** [comment]
@stof Are you working on a pull request?

**Comment by stof** [comment]
Well, due to the way `addcslashes` and `stripcslashes` are not symmetrical, it won't be easy to implement. https://3v4l.org/4jf9N shows me that I can detect things for most cases (while keeping the usage of the native implementation of `stripcslashes`) by hardcoding the list of built-in chars plus our own escaped chars (`\`, `'` and `"`), but the handling of `\x<code>` will be a pain (see the last case which fails while it should not).

So either we also deprecate that support, or we reimplement `stripcslashes` in userland in the lexer, allowing us to trigger the deprecation directly in the processing (instead of having to detect it after the fact)

**Comment by fabpot** [comment]
We should see if reimplementing cstripcslashes in userland would make lexing much slower for typical templates.

**Comment by stof** [comment]
do you have an existing benchmark for the Twig template compilation that I could reuse ?

**Comment by stof** [comment]
I found https://github.com/twigphp/twig-perf but this does not seem to have "typical" templates, as it does not have much usage of Twig strings there (and so no usage of `stripcslashes` that would be replaced)

**Comment by fabpot** [comment]
@stof What do we do here?

**Comment by stof** [comment]
@fabpot do you have any twig benchmark which could be used to evaluate the impact of moving to a userland stricter stripcslashes ?

**Comment by fabpot** [comment]
No, I don't have anything except the repo you already mentioned.

**Comment by stof** [comment]
hmm, maybe it would be worth improving this repo with some more typical templates.

**Comment by fabpot** [comment]
As this is limited to the compile time and will only impact string parsing, I doubt the impact would be significant. We can micro-benchmark if you want to the 2 implementations.

**Comment by fabpot** [comment]
@stof What do we do here?

**Comment by fabpot** [comment]
Let's close?

**Comment by stof** [comment]
I'd like to reopen that, as I was hit by such case once again (coming from PHP, it is very easy to write an unescaped backslash in a string).
