### ISSUE TITLE
[RFC] Allow Filter, Function and Test implementions

### ISSUE THREAD

**Issue by SpacePossum** [twigphp/Twig#2716]
On Twig 2.x you are not supposed to extend the `Twig_Filter` (and `Function` and `Test`).

However the `Environment` only allows these concrete implementations. Therefore in order to register a custom `Filter` you must create an instance of `Twig_Filter` (and not something that extends from it).

If you want to reuse the logic in the filter, either in one project or across multiple, you have two options:
- extract the logic into a `callable` class and letting all the users of the filter still create a `Twig_filter` passing the logic as second argument
- create some sort of Factory to get the filter, with extra logic/overhead
- create a Extension, this comes with the overhead of filling in all other methods the `Twig_ExtensionInterface` enforces

I would like to propose adding;
- `Twig_FilterInterface`
- `Twig_FunctionInterface`
- `Twig_TestInterface`
- update the `Environment` (and where needed) to reply on these interfaces, similar as `Twig_ExtensionInterface`

With these; writing, reusing, testing and sharing `Filters`, `Functions` and `Test` becomes for more easy.

What do you guys think?

**Comment by stof** [comment]
what kind of shared logic are you talking about ?

**Comment by SpacePossum** [comment]
For example:
https://github.com/GeckoPackages/GeckoTwig/blob/v2.1/src/Twig/Filters/FilePermissionsFilter.php

This class can lo longer be (re)used because it triggers a deprecation notice.
I would like to prevent putting all the `functions`, `tests`, etc. in one big `Extension` and redefine those as `Twig_Filter`'s in it together with all the code of all the `Filter`s.

**Comment by stof** [comment]
@SpacePossum if you want to share the callable, put it as a static method rather than a Closure, and it will be reusable. There is no need to create a child Filter class to make a callable reusable.

**Comment by stof** [comment]
and btw, for reusable filters or tests, using a Twig extension might be a better idea than asking users to register filters manually. and then, the extension class can also be the host of the callable.

**Comment by SpacePossum** [comment]
Putting all the logic of all the `Filters`, `Tests` and `Functions` in on `Extension` class creates really big classes and you can still not share filters among different `Extension` classes.

Maybe what I really wondering is, why enforce this composition, why not allow for other implementations of Filter's as long as these implement an interface?

**Comment by stof** [comment]
@SpacePossum you can still put the callable where you want. and btw, using a closure as the callable is the less efficient way at runtime, as calling it requires initializing all extensions to get the Filter objects to be able to get the callable, while callable implemented as a static method can call the static method directly in the compiled template.

**Comment by SpacePossum** [comment]
For me it is not as much about getting the most performance, but more about composition of the code; so maintainability, single responsibility and testing.
It is nice to be able to put the callable elsewhere, which I would do to prevent putting all the code in one big extension, but it detaches it from the filter name and the options.

For example:

```php
final class SomeProjectExtension implement Twig_ExtensionInterface
{
//    public function getTokenParsers()
//    public function ...
  public function getFilters()
  {
    return [
        new Twig_filter(
            some3rdPartyFilter::getName(),
            some3rdPartyFilter::getCallable(),
            some3rdPartyFilter::getOptions(),
       ),
       someOther3rdPartyFilterFactory::buidFilter(),
       new Twig_Filter(
              'some name',
              function() {
                     // lot of code, or reference to a static function in this file or else where
              },
              $options,
       ),
  }
}
```

vs 

```php
final class SomeProjectExtension implement Twig_ExtensionInterface
{
//    public function getTokenParsers()
//    public function ...
  public function getFilters()
  {
    return [
       new some3rdPartyFilter(),
       new someOther3rdPartyFilter(),
       new myProjectFilter(),
  }
}

```

All of Twig can already work with the `Twig_filter` class so abstracting it to an interface shouldn't be hard and you would still have people stopped from overriding the `Twig_Filter` class.

**Comment by stof** [comment]
creating an interface would forbid us to add any new feature for filters relying on new getters on the class (as adding new methods in an interface is a BC break). And we had to do such things in the past. Creating an interface for a value object does not really make sense.

and regarding third-party packages, they can provide extensions registering the filters, to make it easy to use them (this is what all third-party packages extending Twig I know of are doing). So this becomes a matter of registering their extension (so `$twig->addExtension(new some3rdPartyExtension());`

> create a Extension, this comes with the overhead of filling in all other methods the Twig_ExtensionInterface enforces

that's why Twig provides an abstract class with empty implementations of all methods, allowing you to override only the methods for which you need to return non-empty lists.

**Comment by SpacePossum** [comment]
Thanks @stof , I fail to explain my case here in a good matter.
