### ISSUE TITLE
{{ if object }} with objects implementing __toString()

### ISSUE THREAD

**Issue by MalteWunsch** [twigphp/Twig#2717]
https://twig.symfony.com/doc/2.x/tags/if.html states the rules that determine whether an if expression is true or false. For objects, it always returns true.

One could argue that this is perfectly fine, as the objects are provided by some PHP folks that probably know what they're doing.

But as Twig tries to be nice to frontend developers, one could also argue that objects with a __toString() method should be casted to string before checking the rules from above. To me it seems this would be in line with https://github.com/twigphp/Twig/commit/f5193e92c50c89f19121771ca800aad55b97aff7 (respecting __toString() in length filter ans empty test).

If you'd agree to the latter, I'd be happy to write a PR.

**Comment by fabpot** [comment]
The big difference with the referenced commit is that there is an explicit call, whereas here, there is no explicit call. `if object` is probably not something we want to support (using `__toString()` is arbitrary and very opinionated in the sense that it's not meaningful for all objects).

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
