### ISSUE TITLE
Proposal: tag that compiles to PHP 'use' (for namespaces)

### ISSUE THREAD

**Issue by drjayvee** [twigphp/Twig#2718]
I see several issues regarding use of namespaced classes in twig templates (#954, #1100, etc). The `constant` function and test work fine when an instance is available, but that's not always the case.

### Problem
Consider this situation
```php
namespace Really\Deep\Project;

class Base {
  const CO = 'Sup';
}

class Sub extends Base {
  const CO = 'Sub';
}
```

```twig
{# context: $ob instanceof Base (or Sub) #}
{{ constant('Really\Deep\Project\Base::CO') }} or {{ constant('Really\Deep\Project\Sub::CO') }}?
{{ ob.name }} is
{% if ob is instanceof('Really\Deep\Project\Base') %}
  {{ constant('CO', ob) }}
{% endif %}
```

We have to type the FQNs everywhere, which can get really repetitive (and error-prone since they're written in strings, and therefore IDE's can't check).

Line 4 uses the `instanceof` test, which Twig doesn't have, but which is fortunately trivial to add as a `new Twig_Test` (Go Twig!). We do have to type the FQN again, however.

On line 5, we can fortunately use the object to access its constant.

### Workarounds
There are certainly workarounds, such as passing FQNs to the template:
```php
use Really\Deep\Project\Base;

$tpl->display([
    'BaseClass' => Base::class,
    // etc
]);
```
These variables have to be passed string-concatenated sometimes, and passed on to `macro`s, which makes templates a bit messy:
```twig
{% macro show(BaseClass, SubClass, ob) %} {# instead of show(ob) #}
  {% if ob is instanceof(BaseClass) %}
    {{ constant('CO', ob) }}
  {% endif %]
{% endmacro %}

{{ constant(BaseClass ~ '::CO') }} {# constant('Base::CO') would be _much_ prettier #}
{{ show(BaseClass, SubClass, ob) }}
```

### Proposal
I would propose a tag which compiles to PHP's `use`. `use` is already taken, so we have to use something else (pun not intended).
```twig
{% usens 'Really\Deep\Project\{Base, Sub}' %}
{{ constant('Base::CO') }} or {{ constant('Sub::CO') }}?
{{ ob.name }} is
{% if ob is instanceof('Base') %}
  {{ constant('CO', ob) }}
{% endif %}
```
This would then compile to a template like:
```php
<?php
use Really\Deep\Project\{Base, Sub};

/* ./tehmplates/foo.twig */
class __TwigTemplate_w00t1337pwn extends Twig_Template
{
    // ...
}
```

I'd be happy to give implementation a shot!

### Sidenote: instanceof implementation
For our project, I've implemented the `instanceof` test as follows:
```php
// To make access to namespaces easier in twig templates, this test tries doesn't require $class to be fully qualified
// (\Fully\Qualified\Name\Space::create()) is instanceof('Name\Space')
$twig->addTest(
    new Twig_Test('instanceof', function ($object, $class) {
      return substr(get_class($object), -strlen($class)) == $class;
    })
);
```

I would prefer to use PHP's `instanceof` operator, but really don't want to write FQN in templates.

**Comment by ericmorand** [comment]
It would make Twig an even less agnostic and generic templating language than it already is. Just my two cents.

**Comment by stof** [comment]
and it would force to implement a lot of magic, as you expect these imports to have an effect inside strings (which is not the case in PHP)

**Comment by fabpot** [comment]
Closing as this won't be implemented in Twig.
