### ISSUE TITLE
Twig\Loader\FilesystemLoader should be called Twig\Loader\Filesystem

### ISSUE THREAD

**Issue by szepeviktor** [twigphp/Twig#2719]
Introduction says `$loader = new Twig_Loader_Filesystem('/path/to/templates');`

`new Twig\Loader\Filesystem();` fails,
but `new Twig\Loader\FilesystemLoader();` works.

Please advise.

**Comment by szepeviktor** [comment]
Thus these files should not have "Loader" in their names
https://github.com/twigphp/Twig/tree/2.x/src/Loader

**Comment by apfelbox** [comment]
These files were added to enable autowiring in Symfony. I would argue (and probably it's the same argumentation as when this was introduced) that `FilesystemLoader` is way better than `Filesystem` for the loader imo.

So if Twig someday changes to only support PSR-4 (Twig 3.0 maybe?) these would be better class names going forward.

(*edit*  my previous explanation was bogus, of course)

**Comment by szepeviktor** [comment]
Thank you @apfelbox 
My thinking is PSR-4 only.
