### ISSUE TITLE
Twig\Source can't be used

### ISSUE THREAD

**Issue by maikelsalazar** [twigphp/Twig#2720]
The class Source in the namespace twig can't be use because \Twig_Source is a final class and can't be extended.

```php
<?php

namespace Twig;

class_exists('Twig_Source');

if (\false) {
    class Source extends \Twig_Source
    {
    }
}
```

**Comment by lyrixx** [comment]
Hello @maikelsalazar 

Could you create a small reproducer please?

**Comment by nesl247** [comment]
Is it really necessary? You can't extend a final class, and `Twig_Source` is final.

https://github.com/twigphp/Twig/blob/60a8f465d6f259c92a8fe0fb61cf8f767bd8d025/lib/Twig/Source.php#L17

> If the class itself is being defined final then it cannot be extended. http://php.net/manual/en/language.oop5.final.php

**Comment by fabpot** [comment]
But you should not extend Twig_Source, this is an internal class. What would be your use case?

**Comment by maikelsalazar** [comment]
We are not looking extend it. We want to use Twig\Source instead of Twig_Source, we in particular don't like the "_" on the class name.

**Comment by fabpot** [comment]
But again, that class is not meant to be extended. That's not something we are going to change. Depending on your use case, there is probably another way.

**Comment by nesl247** [comment]
@fabpot We aren't trying to extend it, we are trying to use `Twig\Source` instead of the `\Twig_Source` class name.

However, it looks like this may just be a PhpStorm issue because it's assuming `src/Source.php` instead of reading the `class_alias` and gives a warning/error.

Thanks for your time.

**Comment by maikelsalazar** [comment]
As @nesl247 said, it is phpstorm issue. 

Thanks for your time.
