### ISSUE TITLE
Named for loops

### ISSUE THREAD

**Issue by predakanga** [twigphp/Twig#2722]
While the `loop` variable is extremely helpful in template design, it can get confusing when dealing with deep nesting, or irregular nesting.

I've found myself using a simple shortcut to make things a lot more manageable:
```twig
{% for section in sections %}
{% set section_loop = loop %}
    <!-- ... -->
    {% for subsection in section %}
    {% set subsection_loop = loop %}
        <!-- ... -->
        {% for item in subsection.items %}
        {% set item_loop = loop %}
            <!-- ... -->
        {% endfor %}
    {% endfor %}
{% endfor %}
```

This pattern helps avoid expressions similar to `cycle([...], loop.parent.loop.parent.loop.index0)`, making the template a lot more readable and maintainable.

I would like to propose introducing this as a feature of the for tag, something like `{% for varname in collection with loop_varname=loop %}` or `{% for varname in collection as loop_varname %}`.

**Comment by fabpot** [comment]
I understand the use case, but it should be pretty rare. As defining a temporary variable is simple enough, I propose to close this issue.
