### ISSUE TITLE
Is there a way to parse html in twig

### ISSUE THREAD

**Issue by samspired** [twigphp/Twig#2724]
Is there a way by which html can be parsed in twig and nodes, children nodes obtained?

**Comment by lyrixx** [comment]
Hello @samspired 

There a not way to parse HTML in order to produce an AST because it does not really make sens. 
The twig AST is composed a Text Node (static text or html) and almost all others Nodes are related to Twig's "internals" (like if / else / include / ...)

So my question is: What do you want do?

**Comment by samspired** [comment]
Thanks @lyrixx 

Suppose, I have the following HTML structure.
```
<div>
  para 1
  <div>
    para 1a
  </div>
</div>
<div>
  para 2
  <div>
    para 2a
  </div>
</div>
<div>
  para 3
  <div> para 3a </div>
  <div> para 3b </div>
  <div> para 3c </div>
</div>
```

I want to split this HTML and get first level of matching divs.
Example - I need below three separate blocks from above structure:
 
```
<div>
  para 1
  <div>
    para 1a
  </div>
</div>
```
```
<div>
  para 2
  <div>
    para 2a
  </div>
</div>
```
```
<div>
  para 3
  <div> para 3a </div>
  <div> para 3b </div>
  <div> para 3c </div>
</div>
```

This has been really hard to solve with just Regex because it matches the first inner nested child `</div>`.
Checked some stack-overflow answers and some of them suggest using HTML parser.

- I cannot use a client side parsing, because I need this before rendering is done.
- Adding classes to divs OR adding placeholders after first level closing divs is also not an option.

So, ideally, we wanted this to work with twig.

**Comment by lyrixx** [comment]
Indeed twig can not dot that. 
You can do it with symfony Dom crawler (and CSS selector) instead

**Comment by samspired** [comment]
Cool, thanks, I'll checkout those options 👍
