### ISSUE TITLE
make AST public (or provide a RecursiveArrayIterator)

### ISSUE THREAD

**Issue by drzraf** [twigphp/Twig#2725]
I'd like to inspect the AST of a source.
* `$nodes` is [protected](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Node.php#L20)
* [getIterator](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Node.php#L167 ) only returns a `simple` iterator rather than a `RecursiveArrayIterator`.
Unless workaround exist, it would be nice to make `$nodes` available for reading.

**Comment by nicolas-grekas** [comment]
~Did you try using toArray? It should allow what you want I think.~

**Comment by yceruto** [comment]
> Unless workaround exist, it would be nice to make $nodes available for reading.

A recursive function with:
```php
foreach($node as $name => $childNode)
```

**Comment by fabpot** [comment]
Inspecting an AST should be done with a node visitor. Any issue with them?

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.

**Comment by drzraf** [comment]
I didn't understand the reference to `toArrray` and didn't know about node visitors (No mention of them is made at https://twig.symfony.com/doc/2.x/internals.html#the-parser).
I ended up using basic hand-made [recursion](
https://github.com/wp-cli/i18n-command/pull/59/files#diff-5653ee201a665d33b4054d056326904bR42)
thank you

**Comment by nicolas-grekas** [comment]
(misleading comment about toArray, it's something in the `ExpressionLanguage` component)
