### ISSUE TITLE
Escaping issue with shortcut block syntax

### ISSUE THREAD

**Issue by simshaun** [twigphp/Twig#2728]
Twig v2.5.0

I've been using the shortcut block syntax quite a bit, but just noticed an issue where the site name is being encoded even with `|raw`. I ended up needing to use the full-form syntax.

Given `site_name = Brown's`
Calling `$subject = $template->renderBlock('subject', $context);`

- With `{% block subject 'Analytics nag - ' ~ site_name|raw %}`  
Results in `Analytics nag - Brown&#039;s`

- With `{% block subject 'Analytics nag - ' ~ (site_name|raw) %}`  
Results in `Analytics nag - Brown&#039;s`

- With `{% block subject ('Analytics nag - ' ~ site_name|raw) %}`  
Results in `Analytics nag - Brown&#039;s`

- With `{% block subject %}Analytics nag - {{ site_name|raw }}{% endblock %}`  
Results in `Analytics nag - Brown's`

---

The Twig template itself looks something like this:
```twig
{% extends 'Email/email_template.html.twig' %}

{% block subject 'Analytics nag - ' ~ site_name|raw %}
{% block title site_name %}

{% block content %}
....
{% endblock %}
```

**Comment by jvasseur** [comment]
Did you try `{% block subject ('Analytics nag - ' ~ site_name)|raw %}` ? The others can't work because the concatenation operation marks the string as unsafe and thus it has to be escaped before outputing.

**Comment by simshaun** [comment]
Interesting. I would never have expected the concatenation operator to affect the escaping.

**Comment by simshaun** [comment]
So the docs say it "converts all operands into strings and concatenates them".

I assume it's the string casting that forces the escaping. I'm just a little puzzled as to why.

**Comment by stof** [comment]
Your shortcut is not equivalent to `{% block subject %}Analytics nag - {{ site_name|raw }}{% endblock %}`. It is equivalent to `{% block subject %}{{ 'Analytics nag - ' ~ site_name|raw }}{% endblock %}`

And here, the value being output is not mark as safe (due to the precedence between the concatenation and filtering operators). Marking a string as safe before the concatenation does not make the output of the concatenation safe.

**Comment by simshaun** [comment]
@stof I understand the differences now. I just don't get why concatenation marks it "not safe".

It'd be nice to somehow have some control over this, maybe with a new operator like `~~`.
At the very least, maybe I should make a docs PR that makes it clear using `~` will mark the operands "unsafe" after they're converted to strings.

**Comment by fabpot** [comment]
@simshaun Would you like to submit a PR to update the docs?

**Comment by stof** [comment]
@simshaun The output of a concatenation between 2 safe string can be unsafe. Marking a concatenation operator as safe would open the door to XSS issues depending on what you are concatenating.

**Comment by simshaun** [comment]
Gotcha. What are the chances of introducing a "dangerous concatenation" operator like `~~` where we know the two operands can be safely joined? In many cases I'm concatting dynamic values that I know are already safe. I'd work on the PR if I knew it had a chance of being accepted.
