### ISSUE TITLE
Path function auto-escapes { and } signs to %7B and %7D

### ISSUE THREAD

**Issue by bentcoder** [twigphp/Twig#2729]
Hi,

I am having problems when creating a href link from parameter value below with `path` function. It auto-escapes `{` and `}` as you can see below. I tried `autoescape false` and `raw` as well but no luck. Any solution for this problem?

Thanks

Using Twig `4.1` with Symfony `4.1` if it helps.

```
{{ ep }}

# Result: patch-users-{id}
```

```
{{ path('home', {endpoint: ep}) }}

Result: patch-users-%7Bid%7D
```

**Comment by Tobion** [comment]
The `path` function is a Symfony feature and is bound to the routing. According to RFC 3986, the characters `{}` need to be percent escaped in a URI. 
So this is not a bug. Why do you not want to have it escaped?

**Comment by bentcoder** [comment]
It is because I just want the URL to look "better" rather than odd to users. Nothing special.

For example Mozilla Firefox doesn't mind keeping `{` and `}` signs rather than encoding them if you just manualy type the URL.

**Comment by Tobion** [comment]
Chrome autoencodes those chars if you type them manually. If you don't care about standards and specifications, you can just write a function that replaces the encoded version back to its original char. But that does not need to be provided by Twig or Symfony.

**Comment by k9ne257** [comment]
you need to use `` instead of "" or ''.

e.g

not :

"http://localhost:8080/api/v1/user-profile/${userProfileID}/image/upload"

but replace the quotation marks "" with accent the marks ``
