### ISSUE TITLE
max function behavior when passed empty value

### ISSUE THREAD

**Issue by dpagini** [twigphp/Twig#2733]
Consider the following twig code, with the values coming back from PHP as 5 and NULL for value1 and value2, respectively.

```twig
{{ max(value1, value2) }}
```

The output is blank. I would sort of expect the output to be 5. To fix this, I was able to do:
```twig
{{ max(value1|default(0), value2|default(0))) }}
```` 

I have to admit, I'm not 100% confident this wasn't some sort of user error as I was a bit rushed fixing this... and maybe it's the intended behavior. I think if it is the intended behavior, it might be nice to see a note about it on the documentation page. 
If I have some time I will begin to look at any suggested fix I can attempt, but I haven't done anything in this repo before, so I thought I would start with the bug report.

**Comment by fabpot** [comment]
Just tested and works as expected: https://twigfiddle.com/hobbg4
