### ISSUE TITLE
[FEATURE] Multiple sandbox policies.

### ISSUE THREAD

**Issue by Warxcell** [twigphp/Twig#2735]
I'm thinking for multiple sandbox policies. 
Something like 

```php
$sandbox = new Twig_Extension_Sandbox([
   'emailFromDatabase' => $emailFromDatabasePolicy,
   'smsFromDatabase' => $smsFromDatabasePolicy
]);
$twig->addExtension($sandbox);
```

```twig
{% sandbox emailFromDatabase %}
    {% include 'user.html' %}
{% endsandbox %}
```

and of course keep the old syntax with single policy to keep BC.

What do you think? I can try to implement it these days?

**Comment by fabpot** [comment]
Not sure usage would be widespread enough. It would basically mean that you want to use 2 different sandbox strategies in the same template, which sounds weird. If not, you really need to different Twig instances.
