### ISSUE TITLE
php7 Compatibility problem

### ISSUE THREAD

**Issue by oasfuyou** [twigphp/Twig#2737]
twig/twig/lib/Twig/Compiler.php

 218 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

twig/twig/lib/Twig/Lexer.php

 87 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 91 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

**Comment by xabbuh** [comment]
This does not look like a bug to me. The directive is only read here to adjust the behaviour of the code depending on this setting. And since you can still use it on PHP 7.2 the code must not be changed as users could still make use of this setting.

**Comment by stof** [comment]
What is giving you this warning ?

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
