### ISSUE TITLE
add a new condition to only render a block once

### ISSUE THREAD

**Issue by ecwio** [twigphp/Twig#2738]
different than `defined` that just checks if a block exists this new function would only allow a block to be rendered once

so if the content of a given block is present in the dom, do not render it
Useful to avoid duplicates of embedded javascript functions

Suggested name:
`once`
`unique`
`single`

`{% block "block name" once  %}`
 
`{% endblock %}`

**Comment by stof** [comment]
This would require to introduce state in Twig to remember which blocks were already rendered. This would cause issues as we would then have to reset this state properly.

Btw, `loaded` looks really weird to me. Blocks are not loaded, they get rendered.

**Comment by stof** [comment]
Thus, this cannot even be implemented reliably:

```twig
{% set foo = block('foobar') %}
{# don't actual display the content of the "foo" variable #}
```

Is the block `foobar` rendered or no then at this point ? If the answer needs to be `no`, this becomes a nightmare, as we now have to track what happens with the string returned by `block` to see whether it gets rendered or no (and we cannot attach metadata to a string, so this is not even really possible). If the answer is `yes`, then you cannot really rely on this (as it makes it rendered "at most once", not "once".

**Comment by ecwio** [comment]
@stof I updated my question with new names and syntax

Some sort of internal list with unique ids maybe ? It does not have to be a complete state; only some blocks could "subscribe" so that would make the feature easier to implement

Do you have an alternative by any chance ? I would love to be able to embed my javascript functions with the corresponding template

**Comment by stof** [comment]
even if blocks have to opt-in, we still have to manage a state storing which one were rendered (and resetting them in the right time, as rendering another template later using the same Environment object should avoid being impacted by the previous rendering, which becomes hard in case of recursion).

**Comment by ecwio** [comment]
Im not sure you even have to "track anything" inside twig; could just be just an internal simple list anywhere that does not change with page loading so every time a block with the tag "once" tries to render if it finds its own id in the list then it does not.

I was thinking about this feature specifically for javascript functions. those functions do not need to be "tracked" in any way. they just need to load once. 

At the moment it is not possible to embed javascript functions inside a twig template; they get duplicated every time.

**Comment by stof** [comment]
@signmeuptwice we need to track the state of blocks being rendered, to be able to answer the question about whether it has already been done. If the list does not change, the answer would not change, and so it would not work (your feature request requires to have a different behavior for the first rendering of the block).

And this state needs to be resettable, as multiple usages of Twig should not be impacted by the fact that the block was rendered in the *other* rendering (that would be a huge WTF, and would break any code which would not stop the PHP process after sending a HTTP response).

**Comment by ecwio** [comment]
Not sure what you mean by "multiple usages of Twig" you mean different users of the same server ? because in that case is it possible to associate the block id to the php session id or something else if sessions are disabled ?

I do not know all the inner workings of twig and I understand there are challenges to the simplest requests. 

I am only suggesting this feature to embed javascript functions inside templates. Is it currently possible to it ? Im not the biggest twig expert...  

if not I'll have to create separate JS files and that makes my code a lot more spread out and that makes big projects harder to manage for me. It would be a nice feature to keep related JS function inside the template.

In traditional PHP workflow using an `include` it is possible to mix html and javascript without duplication. I really like twig and for me that is the only thing missing.

Could you please let me know if there is a way of embedding javascript. I have been trying for days.

if you find the feature useful I hope you consider its implementation. IMO this would really add a lot of possibilities.

**Comment by ericmorand** [comment]
@signmeuptwice, it's actually quite easy to create a stateful extension that solves your problem.

From the top of my head, something like this should work:

```
class State_Extension extends Twig_Extension
{
    protected $state = [];

    function getFunctions()
    {
        return array(
            new Twig_Function('get_state', [$this, 'getState']),
            new Twig_Function('set_state', [$this, 'setState']),
        );
    }

    public function getState($key)
    {
        if (array_key_exists($key, $this->state)) {
            return $this->state[$key];
        }
        else {
            return null;
        }
    }

    public function setState($key, $value)
    {
        this->state[$key] = $value;
    }
}
```

Now you have a generic extension that provides a state for your Twig templates.

You could have a "embed script" macro that checks and set the state accordingly:

```
{% macro embed_script() %} 
    {% if (get_state("script_has_already_been_embedded") == false) %}
        <script></script>
        {% do set_state("script_has_already_been_embedded", true) %}
    {% endif %}
{% endmacro %}
```

If you can add custom extension to your Twig environment, it's worth a try.

**Comment by stof** [comment]
> Not sure what you mean by "multiple usages of Twig" you mean different users of the same server ?

I mean multiple calls to `Twig_Environment::render` in the same PHP process.

Note that the extension suggested by @ericmorand still suffers from this issue about needing to reset the state properly (if you render multiple times, they would current share their state in this extension). But as long as it is inside your project, this limitation might be fine for you. But it is not fine for bringing this into Twig itself.

**Comment by fabpot** [comment]
Closing as this is not a feature we can/want to implement in Twig core.
