### ISSUE TITLE
Batch filter on undefined variable throws a PHP warning

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2739]
Consider the following Twig template:

```
{% for item in items|batch(3) %}
{% endfor %}
```

https://twigfiddle.com/j8oao4

Rendering this template with no variables set leads to an empty output. But it throws a PHP warning:

`PHP Warning:  array_chunk() expects parameter 1 to be array, null given`

Not much of an issue but I have the feeling the batch filter should check that the array received as parameter is set and should return an empty array in the opposite case.

**Comment by ericmorand** [comment]
It only happens when strict_variables is set to false, obviously. An exception is thrown when strict_variables is set to true, as expected.

**Comment by stof** [comment]
Well, when disabling strict_variables, any undefined variable is replaced by `null`. But there is no guarantee that using `null` will work fine everywhere.

**Comment by fabpot** [comment]
Closing as explained by @stof
