### ISSUE TITLE
Make Twig_Environment extensible 

### ISSUE THREAD

**Issue by smougel** [twigphp/Twig#2746]
Hello

Twig_Environment class is not extensible with members visibility set to private. Is there any reason to keep that private ?

Thx

**Comment by smougel** [comment]
```
class Twig_Environment
{
    const VERSION = '2.5.0';
    const VERSION_ID = 20500;
    const MAJOR_VERSION = 2;
    const MINOR_VERSION = 5;
    const RELEASE_VERSION = 0;
    const EXTRA_VERSION = '';

    private $charset;
    private $loader;
    private $debug;
    private $autoReload;
    private $cache;
    private $lexer;
    private $parser;
    private $compiler;
    private $baseTemplateClass;
    private $globals = array();
    private $resolvedGlobals;
    private $loadedTemplates;
    private $strictVariables;
    private $templateClassPrefix = '__TwigTemplate_';
    private $originalCache;
    private $extensionSet;
    private $runtimeLoaders = array();
    private $runtimes = array();
    private $optionsHash;
    private $loading = array();
```

**Comment by fabpot** [comment]
All extension points are exposed via methods.

**Comment by smougel** [comment]
To give more context : 
```
    public function loadTemplate($name, $index = null)
    {
        $cls = $mainCls = $this->getTemplateClass($name);
        if (null !== $index) {
            $cls .= '_'.$index;
        }

        if (isset($this->loadedTemplates[$cls])) {
            return $this->loadedTemplates[$cls];
        }
```
when using the same template name multiples time (with array loader or a custom loader) there is a memory leak with $this->loadedTemplates[$cls] and no control to clear this cache.

**Comment by smougel** [comment]
when you want to refresh the content of a template w/ a given name, you have to tweak the cacheKey in the loader to force cache avoidance (like in array loader).

**Comment by stof** [comment]
Well, forcing to refresh the content of the template is not a supported use case in Twig, as that would make it much harder to implement caching (which is a must-have for performance for all common cases). Twig compiles templates the template to a PHP class. For caching support, the class name has to be deterministic. But refreshing would mean then redefining the class, and that's not supported by PHP.

**Comment by smougel** [comment]
TT
Caching mecanism by PHP class... I'm so sad. It's pretty annoying when you are in the context of a worker.. or a long running process... The best I could do is to kill the process after "n" given iterations.

**Comment by stof** [comment]
Well, Twig is compiling templates into PHP code. That's what is making it as fast as it is.

**Comment by stof** [comment]
and making everything protected will make it impossible to refactor Twig without breaking BC (as child classes could mess with anything they want), which has a huge maintenance cost. This is why Twig migrated from protected to private between 1.x and 2.x (while keeping explicit extension points in many places)

**Comment by fabpot** [comment]
Closing as we won't change private to protected without a valid use case.
