### ISSUE TITLE
Recursive template embed/include

### ISSUE THREAD

**Issue by pkly** [twigphp/Twig#2748]
I have some code, that, let's say creates blocks of a website.

Each block is a single item, that has text (optional), gallery (optional), type (mandatory)
If type is 'text', it renders text, if type is 'gallery' it renders a gallery, but if type is 'block container', i'd like it to simply read it's children, and create more blocks that follow the same rules.

Simple example below

```twig
{% set type = block.type %}
{% set text = block.text %}
{% set gallery = block.gallery %}
{% set children = block.children %}
{% set id = block.id %}

<section class="block block-type-{{ type }} {% if children|length %}has-children{% endif %} {%if isChild %}is-child{% endif %}" id="block_{{ id }}">
 {# render text if needed #}
 {# render gallery if needed #}
 {% block someBlock %}{% endblock %}

 {# problematic part here #}
 {% for cItem in children %}
  {% embed _self with {block: cItem, isChild: true} %}
   {% block someBlock %}
    This is another embeded block
   {% endblock %}
  {% endembed %}
 {% endfor %}

</section>
```

This code produces a 503 when ran from a template like below

```twig
{% extends 'base.twig' %}

{% block content %}
 Content here!<br>
 {% set blocks = load_from_whatever() %}
 {% embed 'template_above.twig' with {block: blocks} %}
  {% block someBlock %}
   Whatever block here
  {% endblock %}
 {% endembed %}
{% endblock %}
```

It seems to produce the same error when doing some trickery to get more or less the same effect with `{% include %}`
I tried both _self and actual file path, but apparently they're the same, so of course the effect is the same.

Tested on 2.4.8 (but 2.5.0 doesn't have any changes relating to the include/embed mechanisms as far as I'm aware)
PHP: 7.1.20-1+0~20180725103117.2

Any chance you could fix it? I could try having a look myself and seeing if it's feasible during the weekend maybe.

**Comment by stof** [comment]
Well, you need to make sure that you don't create an infinite loop with your recursion. That's the first idea I have here.

Providing a reproducing case would be great.

**Comment by pkly** [comment]
Okay, so you were right and I'm a retard.

Basically the issue was as following: the list of items I was going to run the template on again was actually loaded inside a template, and was not reset on embed, causing, as you said, an infinite loop.
I looked at my code again after creating an extremely similar scenario on twigfiddle which runs fine [fiddle with limited scenario here](https://twigfiddle.com/dw4xjt)

So yeah, sorry for causing you trouble and thanks for the help. Much love.
