### ISSUE TITLE
Feature to prerender all templates to generate the cache for readonly file systems?

### ISSUE THREAD

**Issue by cypherbits** [twigphp/Twig#2752]
Hello, some sites use readonly filesystem for security purposes, Twig use a cache directory to render the templates. How could a developer prerender all templates to the cache directory and then make it readonly?

**Comment by yceruto** [comment]
This is what Symfony does to warm up the Twig cache:
* Search all files inside each path (directory) registered (you can get this info from the Twig loader)
* Using the namespace data, creates the correct template name (e.g. `@Foo/bar.twig`) for each file found
* Try to load each template name and catch the `Twig\Error\Error` if problem during compilation, syntax error or it's a non-Twig template.

This class would help you understand what to do to achieve it:

```php
// make sure to do this after all namespace/paths are registered.
$warmer = new FilesystemCacheWarmer($twig);
$warmer->warmUp();
```
See class implementation  https://gist.github.com/yceruto/041116e266c064484edcd8343045f4fc

**Comment by fabpot** [comment]
Closing as @yceruto gave the answer.
