### ISSUE TITLE
Is functions/undefined_block test correct?

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2753]
While working on improving error location handling in Twing, I stumbled upon this test:

```
--TEST--
"block" function with undefined block
--TEMPLATE--
{% extends "base.twig" %}
{% block foo %}{{ parent() }}{{ block('unknown') }}{{ block('bar') }}{% endblock %}
--TEMPLATE(base.twig)--
{% block foo %}Foo{% endblock %}
{% block bar %}Bar{% endblock %}
--DATA--
return array()
--EXCEPTION--
Twig_Error_Runtime: Block "unknown" on template "base.twig" does not exist in "base.twig" at line 2.
```

It's inside `Fixtures/functions/undefined_block.test` and it looks wrong to me. The error actually happens in `index.twig` at line 3 but the test expected error message is:

> Twig_Error_Runtime: Block "unknown" on template "base.twig" does not exist in "base.twig" at line 2.

I'd expect it to be:

> Twig_Error_Runtime: Block "unknown" on template "base.twig" does not exist in "index.twig" at line 3.

**Comment by stof** [comment]
Well, I think the existing test was written taking into account the existing error location handling. I totally agree it should be improved.

**Comment by ericmorand** [comment]
Thanks for the clarification. I was hesitant to fix this on Twing if it was the expected result - well, it is according to the current error location handling but it's not exactly what is expected from a UX point of view.

Anyway, I think it will be much easier to improve in TwigPHP than in Twing due to the nature of stack traces in node.js/V8.

**Comment by ericmorand** [comment]
Well, it happened to be very difficult to fix in node.js and impossible in a browser - without any form of filesystem available the guessing logic of TwigPHP and Twing@1 is impossible to implement.

I ended up removing the whole error guessing logic and rely on wrapper functions everywhere a runtime error is expected. For example, instead of calling getCallable() of a filter/function/test, I call a "location aware" wrapper function that call getCallable() and manage the exception handling. Something like this is PHP:

```
function getLocationAwareCallable($lineno, $source) {
    return function($args) use ($lineno, $source) {
        try {
            return call_user_func_array($this->getCallable(), $args);
        }
        catch (Exception $e) {
            if ($e instanceof Twig_Error) {
                if ($e->getTemplateLine() === -1) {
                        $e->setTemplateLine($lineno);
                        $e->setSourceContext($source);
                }
            }

            throw $e;
        }
    }
}
```

And of course the compiled template now look like this:

```
// line 7
call_user_func_array($this->env->getFilter('escape')->getLocationAwareCallable(7, this.source), array(...));
```
(untested code, may be not perfect)

Performances didn't suffer at all with node.js and I'm very happy to have got rid of what I consider a very dark and smelly part of TwigPHP: the error guessing logic - and all the satellite code that was spread in other classes that handled specific logic for guessing like having lineno set to false for loader errors and such.

And now the above test is throwing the expected error message:

`Twig_Error_Runtime: Block "unknown" on template "base.twig" does not exist in "index.twig" at line 3.`

**Comment by stof** [comment]
Well, over time, we removed as much need as possible for the guessing logic, as it is indeed performing badly in many case. But we haven't got rid of it entirely yet (and not sure we can do it without performance impact).

**Comment by ericmorand** [comment]
I'll have a benchmark soon to compare the current implementation to a "location aware wrapper" solution. It's actually quite easy to implement (from the top of my head, some minor changes to "Call", "BlockReference", "Block" and "Parent" nodes plus adding the wrapper to Twig_Template). I'll let you know.
