### ISSUE TITLE
Date Filter Outputs UTC Instead of Timezone Common Name

### ISSUE THREAD

**Issue by kmgdevelopment** [twigphp/Twig#2763]
When running a European date through Twig's date filter, I pass `Europe/London` as the timezone argument:

`{{ post.time | date('g:ia T', 'Europe/London') }}`

I expect to get back 'BST' for the outputted timezone, but instead I get 'UTC+1'. The same goes for if I pass a Central European timezone like `Europe/Paris` - I get 'UTC+2' instead of 'CEST'. 

If I pass `America/Los_Angeles`, however, I get 'PST' instead of 'UTC-8'. Same for 'CST' with `America/Chicago`.

Twig should output the "common name" timezones for every timezone.

I'm running Twig 2.5.0 on Craft CMS.

**Comment by fabpot** [comment]
The behavior is the same as PHP here.

**Comment by kmgdevelopment** [comment]
Is it? Running this script on the same server produces "CEST":

````
<?php
$datetime = new DateTime('2018-10-12 09:25:00');
$timezone = new DateTimeZone('Europe/Paris');
$datetime->setTimezone($timezone);
echo $datetime->format('Y-m-d H:i:s T');
````

**Comment by xabbuh** [comment]
@kgrote Maybe that's related to your PHP version, but in https://twigfiddle.com/y2jggs the behaviour is as you would expect it, isn't it?

**Comment by kmgdevelopment** [comment]
Yeah it must be the PHP version because I'm getting `5:25pm GMT+1 6:25pm GMT+2` from that Twig code on both PHP 7.1 and 7.2. But like I said using pure PHP `DateTime` and `DateTimeZone` produces the expected result. Since the Twig `date` filter is supposed to just be piggybacking off of those classes it seems like something that needs to be adjusted to make Twig compatible with PHP 7.
