### ISSUE TITLE
show how to set a value of a dict (hashed array)

### ISSUE THREAD

**Issue by SimonHeimberg** [twigphp/Twig#2768]
This is invalid syntax:
```twig
{% set someArgs.anElement = 5 %}

{% set someArgs['anElement'] = 5 %}
```

### To resolve this bug, do one of
 * support setting a value of a hashed array, numeric array and a php object
 * document how to do it instead in [doc/tags/set.rst](https://github.com/twigphp/Twig/blob/b081e3f1ed64b8246bfcadef3e66233ab2c0ffd9/doc/tags/set.rst)

### WorkAround
Possible work-around for ``someArgs = {'oneEl': 1}``:
```twig
 {% set someArgs = someArgs|merge({'anElement': 5})
```
For setting a public object property, add a setter method to this object and call it
```twig
{% do aPhpObject.setAnElement(5) %}
```

work-arounds from https://stackoverflow.com/questions/7719838/updating-object-properties-in-twig/19160237

**Comment by ericmorand** [comment]
Yes, I think it should be in the docs.

**Comment by fabpot** [comment]
You should never have the need for setting a hash value, that's why there is no easy way to do that. We introduced the `merge` filter for that purpose, but that's a workaround you should avoid of possible.

**Comment by SimonHeimberg** [comment]
Should be mentioned in the doc that trying to set a hashed value looks like doing things in the wrong place (busines logic in twig)?
