### ISSUE TITLE
FAQ Autoescape works not correctly?

### ISSUE THREAD

**Issue by BonBonSlick** [twigphp/Twig#2771]
```
 {% autoescape false %}
                  {{ form_widget(searchForm.field)|raw }}
                {% endautoescape %}
...
 'choice_label' => function ($choiceValue, $key, $value) {
                    return '<font>' . strtoupper($key) . '</font>';
                },
```

result is escaped.

 Only global settings for twig
`  autoescape: false` works, but this expose  all templates strings.

**Comment by stof** [comment]
the output of `form_widget` is already marked as safe, as it outputs HTML. So `|raw` will have no effect there (marking a safe value as safe does not change anything).

But the place displaying the label itself does *not* mark the label as safe, and so escaping happens in that place. You would have to disable escaping in the form theme (but that would open the door to XSS, so this is not recommended).

**Comment by BonBonSlick** [comment]
So there is no safe way to modify choice label text, best option is to render field manually without form component?

**Comment by stof** [comment]
well, you would have to disable autoescaping in your form theme (or, in that case, rely on CSS rather than `<font>`)

**Comment by BonBonSlick** [comment]
Thank you, I used js, not best solutions, but works

**Comment by lyrixx** [comment]
The best solution is to use a form theme.

**Comment by BonBonSlick** [comment]
Ok, thanks
