### ISSUE TITLE
Reusing a template, changing a "block" (?) in several locations

### ISSUE THREAD

**Issue by mpdude** [twigphp/Twig#2772]
Consider a template as follows:

```twig
    {# lots of markup removed for clarity #}
    {% for node in list %}
        {% if someCondition %}
            XX {{ node }} XX
        {% else %}
            YY {{ node }} YY
        {% endif %}
    {% endfor %}
```

I would like to allow others to re-use this. The challenge is that they might need to change the `{{ node }}` part, for example to read `{{ node | someFilter }}`.

How could I approach this so that the template is useable as-is, but also with this variation?

First approach: Use `{% extends ... %}`. But as we have two places with `{{ node }}`, this would need to have two blocks, named differently. 🙁 

Second approach: Define the block in the first place, call `{{ block(...) }}` in the second to use it again. Confusing.

Third approach: Use `{{ block(...) }}` in both places. Re-use the template with `{% embed ... %}`, passing in the `{% block ... %}` definition. Looks "clean" inside, but does not work when you want to re-use the template without passing in a definition.

Better suggestions? 🤷‍♂️

**Comment by alexander-schranz** [comment]
@mpdude with [embed](https://twig.symfony.com/doc/2.x/tags/embed.html) you have a behaviour like include and extend.

e.g.: https://twigfiddle.com/20ttsg

**Comment by mpdude** [comment]
@alexander-schranz Your suggestion seems to work 👏 

So, the basic template is:

```twig
    {# lots of markup removed for clarity #}
    {% for node in list %}
        {% if someCondition %}
            XX {% block node %}{{ node }}{% endblock %}XX
        {% else %}
            YY {{ block('node') }} YY
        {% endif %}
    {% endfor %}
```

At first, I found this a little confusing, as the actual implementation of the `node` block happens in the first half of the condition block, whereas the second (or even more following ones) just "call" it. But at least it avoids duplicating the code.

This template can then be embedded without further ado:

```twig
  {% embed 'the-above-template.twig' %}
  {% endembed %}
```

But, you can also "pass in" an alternate definition of the `node` block:

```twig
  {% embed 'the-above-template.twig' %}
     {% block node %}
        {{- node|some_filter -}}
      {% endblock %}
  {% endembed %}
```
