### ISSUE TITLE
dump() gets escaped when using custom autoescape strategy

### ISSUE THREAD

**Issue by danielpost** [twigphp/Twig#2774]
When enabling autoescape using the default `html` strategy, using `dump` gives the correct output.

However, when using a custom autoescape strategy, the output of `dump` gets escaped as well (for example, showing HTML entities when Xdebug is enabled instead of nice markup). Is this a bug or am I doing something wrong?

**Comment by stof** [comment]
well, `dump` is marked as safe for HTML. If you have a custom strategy, this function is not safe for it (as we don't know about what that strategy is when implementing `dump`).

**Comment by danielpost** [comment]
Thanks for the reply—that makes a lot of sense. Is it possible to mark a custom strategy as safe for `dump`?

**Comment by stof** [comment]
a strategy is not safe for a function. It is a function being safe for some strategies (and this is controlled by the definition of the function).

Btw, you will probably have issues with lots of other functions here. What is your custom strategy doing ?

**Comment by danielpost** [comment]
I'm using Timber, so I was trying to implement [`esc_html`](https://codex.wordpress.org/Function_Reference/esc_html) to stay closer to the way WordPress does it. It seems like this might be a ton of hassle for minimal gain though.

**Comment by stof** [comment]
Looking at the code of `esc_html`, the difference with Twig's `html` strategy are these:

- integration with WP's filter system (no idea what happens during that step, as I haven't checked the whole codebase)
- using the charset from WP settings, while the Twig code uses the charset configured in `Twig_Environment` (which you could configure based on WP settings)
- skipping the escaping of `&` in existing entities, considering the input could be a mixed of unespaced and escaped content. That's something Twig does not allow, on purpose (and btw, the WP behavior is the non-default behavior of `htmlspecialchars`).

I'm not sure the hassle is worth it. You would have to replace the definition of all functions being safe for `html` to mark them as safe for `esc_html` too (and that would make it harder for using open-source extensions).

**Comment by danielpost** [comment]
Thanks so much for the research and the extensive answer! I will look into this more, but it does indeed seem like it wouldn't be worth the hassle.

**Comment by fabpot** [comment]
Let's close.
