### ISSUE TITLE
Some twig features doesn't work with Snuffleupagus sloppy comparison enabled.

### ISSUE THREAD

**Issue by cypherbits** [twigphp/Twig#2776]
Snuffleupagus is a PHP7 hardening extension. It has a feature to prevent sloppy comparisons that could cause security issues. If I enable this feature, Twig stops working in some template cases like:

{{ something + 1}}

{% for i in range(1,number) %}
{%endfor%}

**Comment by stof** [comment]
What error do you get ?

**Comment by cypherbits** [comment]
@stof 
Unexpected character "+".
Unexpected token "name" of value "in" ("operator" expected with value "in").

Sloppy comparison is about comparing with == and not === . Snuffleupagus converts all == to === so many dangerous comparisons don't happen.

**Comment by stof** [comment]
please give the full errors, including the location and the stack traces. Otherwise, they are useless for us to understand them.

**Comment by cypherbits** [comment]
I can't find more stack traces. It fails parsing the data. Again, it is related to sloppy comparisons somewhere in Twig. Snuffleupagus converts all == to === and the strict comparison on in_array() to true automatically.
in_array(something, something, true);

**Comment by stof** [comment]
Well, if you cannot provide us any details about the failure, there is nothing we can do to help you.

And you said you get a `Unexpected character "+".`. But what is this message ? Is it a PHP error/warning or an exception ? And which kind ?
And all PHP errors and exceptions have a stack trace. So if you are getting one, you can get a stack trace for it (with the appropriate reporting level so that it is displayed, which depends on the stack you use).

**Comment by cypherbits** [comment]
It is a PHP exception from Twig source. There is no more error info. It fails because somewhere in Twig when parsing (for example https://github.com/twigphp/Twig/blob/84b2eb541026dbd39590ba80269ae7676b1bfc46/lib/Twig/Lexer.php) Snuffleupagus force it to not use sloppy comparisons and even if the Twig syntax is ok, it cannot detect the command.

Somewhere in there it makes that the lexer do not find `{{ number + 1 }} `as a correct syntax. And if the syntax seems to be incorrect, Twig triggers an error like `Unexpected character "+" on line X` from the template html, but I have no more stack trace.

**Comment by stof** [comment]
Well, if it is a PHP exception, there **is** more details:
- a class name for the exception
- a location where it happens
- a stack trace

*all* PHP exceptions have these things, not only a message. If you cannot get anything else than the message, it means that your logging/reporting of exceptions is a crap, as it hides lots of useful info for debugging it.

**Comment by fabpot** [comment]
Closing as there is no more feedback from the reporter.
