### ISSUE TITLE
Resetting cache without rendering the template

### ISSUE THREAD

**Issue by creativefctr** [twigphp/Twig#2779]
Hi,
I need a method to force a recompile of templates without rendering them. Current force-reload option only works for me when I render the template. Is there a way to achieve this, without executing the template code?
The problem is that, for me, rendering the templates requires a special environment set up but I am clearing the cache in the admin module not connected to the frontend engine.
Thanks

**Comment by yceruto** [comment]
Using `$twig->loadTemplate('name')` should force-reload without render the template, that work for you?

**Comment by fabpot** [comment]
Closing as there is no feedback from the reporter.

**Comment by creativefctr** [comment]
Sorry for the delay, yeah that did the trick!
Many thanks @yceruto

**Comment by creativefctr** [comment]
@fabpot Please mark this as solved
