### ISSUE TITLE
Warning: Illegal offset type in PHP 7.3.0

### ISSUE THREAD

**Issue by NoodlesNZ** [twigphp/Twig#2781]
Using Twig 2.5.0 with PHP 7.3.0 I start getting errors like this:
```
Warning: Illegal offset type in /home/example/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 80
```
https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Loader/Filesystem.php#L80

Stemming from initialising Twig as per usual:
```
$twigLoader = new Twig_Loader_Filesystem(__DIR__ . '/../resources/views/');
```
If I `var_dump($namespace)` just before this line: https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Loader/Filesystem.php#L80 then I get this:

```
/home/example/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:80:NFC
```
And using `gettype($namespace)` shows "Unknown type".

If I change back to PHP 7.2 then I never get this issue. I'm not sure whether this is a bug in PHP or in Twig. Looking at the code, there doesn't seem to be any time where `$namespace` should be anything except a string.

**Comment by stof** [comment]
`Unknown type` ? This looks like a bug in PHP itself. I don't know how a variable could be of unknown type. Please report it to PHP instead.

**Comment by fabpot** [comment]
Let's close until it is confirmed to be an issue with Twig.

**Comment by NoodlesNZ** [comment]
For what it's worth, it might be an issue with Xdebug and opcache in PHP 7.3. I have logged a ticket.
