### ISSUE TITLE
Combination of `set`/`with` and `if`

### ISSUE THREAD

**Issue by gharlan** [twigphp/Twig#2783]
I would be happy to have a shortcut for this:

```twig
{% with {foo: obj.foo} %}
    {% if foo %}
        {{ foo.bar }}
        {{ foo.baz }}
    {% endif %}
{% endwith %}
```

which is similar to this:

```twig
{% set foo = obj.foo %}
{% if foo %}
    {{ foo.bar }}
    {{ foo.baz }}
{% endif %}
```

So I want to do something with `obj.foo` (`foo` is a nullable getter), if available (not null), but I want to call `obj.foo` only once. For this I want to use a (scoped) variable.

---

It could look like this:

```twig
{% if foo = obj.foo %}
    {{ foo.bar }}
    {{ foo.baz }}
{% endif %}
```

But this could confuse because of `=` vs `==`.

So maybe something like this:

```twig
{% if set foo = obj.foo %}
    {{ foo.bar }}
    {{ foo.baz }}
{% endif %}
```

Just some ideas.. 
What do you think? Is it worth it? Any better idea for a syntax?

**Comment by gharlan** [comment]
Or:

```twig
{% if obj.foo as foo %}
    {{ foo.bar }}
    {{ foo.baz }}
{% endif %}
```

**Comment by fabpot** [comment]
Re-reading this issue, I don't think that adding support for a set/if shortcut is something I want in core. It's always a trade-off between expressiveness and simplicity. Thanks for proposing.
