### ISSUE TITLE
Nested embeds, cannot detect custom blocks from outer file.

### ISSUE THREAD

**Issue by bs-thomas** [twigphp/Twig#2784]
Sorry I've been doing this for the last 2 days, and scratching me head and on the verge of committing suicide (note that I'm not really committing suicide).

I have some nested embeds.  In terms of use-case, you think see below as it's a real life example, to encourage code reuse for checkbox field generator with grid generator, but yet allowing customization in case end-developer wants to do something wacky.

**There are 3 files:**

(a) example.twig - This file is to be used by end developer to generate the checkbox field.  It embeds (b) and pass in a custom "parseItem" block to do some overriding behavior.

(b) checkbox.twig - This file generates the checkbox fieldset and things based on what is passed by (a). 
 Then then embeds (c) by passing in a custom block of the checkbox <input> code.

(c) layout-6-6.twig - This file generates the grid layout based on the block "component" passed by (b).

**So basically,** 
* a embeds b with custom blocks
* b embeds c with custom blocks

**Here is the code for each:**

(a) example.twig

    {% set exampleUserStatuses  = [
        { value: 'enabled' },
        { value: 'disabled' },
        { value: 'deleted' },
    ] %}
    {% embed 'Console::components/field/checkbox' with {
        items: exampleUserStatuses,
    } only %}
        {% block parseItem %}
            I EXPECT TO BE RENDERED, AND OVERRIDE ALL OUTPUT SO NO CHECKBOXES APPEAR.
        {% endblock %}
    {% endembed %}

(b) checkbox.twig

    <fieldset class="field checkbox">
        <legend>Checkbox Fieldset</legend>
        {% embed "Console::components/grid/layout-6-6" with {components: items} %}
            {% block component %}
                {% set item = component %}
                {% block parseItem %}
                    <label>
                        <input type="checkbox" name="{{ item.value }}" value="{{ item.value }}">
                        <span><span>{{ item.value }}</span></span>
                    </label>
                {% endblock %}
            {% endblock %}
        {% endembed %}
    </fieldset>

(c) layout-6-6.twig

    <div class="grid layout-6-6">
        <div class="grid-container">
            {% for component in components %}
                <div class="grid-item">
                    {% block component %}
                    {% endblock %}
                </div>
            {% endfor %}
        </div>
    </div>

**Expected Output**

I EXPECT TO BE RENDERED, AND OVERRIDE ALL OUTPUT SO NO CHECKBOXES APPEAR.
I EXPECT TO BE RENDERED, AND OVERRIDE ALL OUTPUT SO NO CHECKBOXES APPEAR.
I EXPECT TO BE RENDERED, AND OVERRIDE ALL OUTPUT SO NO CHECKBOXES APPEAR.

**Actual Output**
![image](https://user-images.githubusercontent.com/2464920/49858141-273c9580-fe2f-11e8-92a0-9286576f4645.png)

**What I Think The Problem Is (but with no WorkAround)**

The "parseItem" block in (a) is not visible to (b), possibly due to scope differences, and so it was not overrided.

Any help would be greatly appreciated, as I'm already completely lost and out of ideas and workarounds.

Thank you very much guys!

**Comment by stof** [comment]
a `embed` tag is exactly the same than a `include` tag for a template extending the embedded template (except it is an anonymous inline template and so cannot be reused). As such, these blocks don't below to the main template (and so cannot be overriden by a child of the main template).

**Comment by rybakit** [comment]
@bs-thomas Maybe this extension can help you: https://github.com/rybakit/twig-deferred-extension. It allows modifying the main template from the included one even if there is no parent-child relation.
