### ISSUE TITLE
The deprecated tag is missing in the documentation

### ISSUE THREAD

**Issue by stof** [twigphp/Twig#2789]

**Comment by yceruto** [comment]
https://github.com/twigphp/Twig/blob/2.x/doc/tags/deprecated.rst ?
https://twig.symfony.com/doc/2.x/tags/deprecated.html ?

Even though it's missing in Tags list https://twig.symfony.com/doc/2.x/

**Comment by yceruto** [comment]
Also it's here https://github.com/twigphp/Twig/blob/2.x/doc/tags/index.rst 

Probably the homepage Twig documentation require manual update?

**Comment by stof** [comment]
@fabpot how is the homepage managed ?

**Comment by fabpot** [comment]
It's managed manually. Fixed now.
