### ISSUE TITLE
Error Unclosed comment on minified CSS

### ISSUE THREAD

**Issue by BernardA** [twigphp/Twig#2791]
On Symfony 4.2.1 Twig throws Unclosed comment error on minified CSS on <style> tag.

Specifically this seem related to @media queries and I got to that conclusion first by placing the whole unminified CSS in place, which worked fine, and then manually placing line break after each CSS rule so to find out which one was the culprit. As usual the error was on the last few lines, ie, the media queries in my case:)

This will throw the error: 
`@media only screen and (min-width:1024px){#hero_img{background-image:url(/img/hero-img-1024.webp)}}`

This WILL NOT:

`        @media only screen and (min-width:1024px){`
            `#hero_img{background-image:url(/img/hero-img-1024.webp)}}`

I have several media queries and each one will throw the error unless I manually place the line break as above.
    
It is probably irrelevant, but the CSS is generated by Webpack's `HtmlWebpackInlineSourcePlugin()`.

Heres a .txt version of the twig file with some CSS lines already broken. 

[twig-error.txt](https://github.com/twigphp/Twig/files/2710040/twig-error.txt)

**Comment by xabbuh** [comment]
Can you explain why Twig needs to render your CSS file?

**Comment by BernardA** [comment]
Standard CSS inline for the obvious performance reasons. Plenty of [literature on that](https://www.smashingmagazine.com/2015/08/understanding-critical-css/).

**Comment by fabpot** [comment]
`{#` is used to start a comment in Twig, so it needs to be escaped to avoid it being processed.

**Comment by BernardA** [comment]
If you had been thoughtful enough to ask I could have told you that the first thing I tried when investigating this was to take out that line. 
No, it does not solve the issue.
I know it's Sunday and you are trying to close issues, but please try another method.

**Comment by fabpot** [comment]
If there is another issue, please give more information.

**Comment by BernardA** [comment]
There is not another issue. There is the same original issue. Your proposed solution does not solve it.

As I pointed out on my question above, the work around to make it work is to introduce line breaks at the `@media` attribute, like below:

 This will throw the error:

        @media only screen and (min-width:1024px){#hero_img{background-image:url(/img/hero-img-1024.webp)}}

This WILL NOT:

    @media only screen and (min-width:1024px){
       #hero_img{background-image:url(/img/hero-img-1024.webp)}}

As per why that's the case I certainly do not know.

Not sure what additional information I can provide. Please be specific.

**Comment by fabpot** [comment]
My comment was (I think) clear: `{#` is used to start a comment in Twig, so it needs to be escaped to avoid it being processed. That's the solution.

**Comment by xabbuh** [comment]
@BernardA If manually escaping Twig markup isn't a viable solution for you, you can write your own Twig function that just returns the minified CSS as a string to prevent it from being interpreted as Twig syntax.

**Comment by BernardA** [comment]
This is standard CSS:

     @media only screen and (max-width:760px){
          #hero_img{
              background-image:.....
          }
      .......
    }

What you seem to be saying is that, to avoid issues with Twig, one should avoid having media queries where the first selector is an id.

I hope this is not the actual solution that you are proposing.  
The actual solution would seem to be that within the `<style>` tag, Twig should not read `{#` as initiating a comment.

**Comment by stof** [comment]
If you put your CSS inside a Twig template, the source code is a Twig template **before** being CSS. Twig has no reason to ignore things inside a `<style>` HTML tag:

- Twig is not specific to HTML, so there is no reason for that
- the HTML is the output of the rendering, so having Twig markup there is a totally valid use case

If you don't want to escape each thing manually in your CSS, you can also wrap it in a `{% verbatim %}` tag, to tell Twig that nothing is a Twig markup until the next `{% endverbatim %}`

**Comment by sonyarianto** [comment]
Today I have similar problem, very confusing at first since no error log (I am using Twig only as a component not in Symfony on my bare-bone PHP framework). My website suddenly become blank. I have large inline CSS on my Twig file and I am using CSS compressor and some fragment become `{#`. But to realize this is very time consuming. Then I came to this issue thread and thanks God, it save my website :)

Use `{% verbatim %}` and `{% endverbatim %}` to include anything raw to your Twig layout. @stof comment I think should be highligthed here :)

Thank you for all Twig developers and maintainers for such a great solution.

**Comment by ghost** [comment]
> Today I have similar problem, very confusing at first since no error log (I am using Twig only as a component not in Symfony on my bare-bone PHP framework). My website suddenly become blank. I have large inline CSS on my Twig file and I am using CSS compressor and some fragment become `{#`. But to realize this is very time consuming. Then I came to this issue thread and thanks God, it save my website :)
> 
> Use `{% verbatim %}` and `{% endverbatim %}` to include anything raw to your Twig layout. @stof comment I think should be highligthed here :)
> 
> Thank you for all Twig developers and maintainers for such a great solution.

Thank you, It works.

**Comment by IdrissSaid** [comment]
You can just add a space between { and # like this {# => { #
