### ISSUE TITLE
Make Twig_Markup an interface so I can decide which custom classes to make safe

### ISSUE THREAD

**Issue by rudiedirkx** [twigphp/Twig#2792]
I have a chainable `Link` class that can't extend `Twig_Markup`, because it's used outside of Twig too. It has a `__toString()` to render the result. It's chainable to collect properties. Twig function `link_to_route` returns it, and it can be marked safe.

Works:

    {{ link_to_route('home', 'Go home') }}

but the power of the Link class is the chain:

    {{ link_to_route('home', 'Go home').fragment('prices').add('class', 'special') }}

But that's not safe anymore, because it's not direct `link_to_route()` output and doesn't extend `Twig_Markup`.

(See https://stackoverflow.com/questions/53933080/make-method-of-twig-safe-function-also-twig-safe)

If `Twig_Markup` were an interface, or implemented that new interface, and that interface would be checked in `twig_escape_filter()` instead of a class (like good OO design, right?), I could have my Link class implement that too, and it would be safe.

Or #2548. I like that too, and it's even more uncoupled.

**Comment by rudiedirkx** [comment]
PR: https://github.com/twigphp/Twig/pull/2793

**Comment by rudiedirkx** [comment]
No? Bad idea? Fix PR first? Anyone?

**Comment by fabpot** [comment]
If we were to implement something in this regard, I think I would prefer #2548 (I'm working on an implementation right now to see how it feels). So, closing this one.
