### ISSUE TITLE
Contradiction in the docs?

### ISSUE THREAD

**Issue by michaelKaefer** [twigphp/Twig#2794]
[twig.symfony.com](https://twig.symfony.com/ ) states that:

"Twig supports everything you need to build powerful templates with ease: multiple inheritance, ..."

[twig.symfony.com/doc/2.x/tags/extends.html](https://twig.symfony.com/doc/2.x/tags/extends.html) states that:

"Like PHP, Twig does not support multiple inheritance."

Which one is true? And isn't that contradictory?

**Comment by jvasseur** [comment]
Multiple inheritance is handled with the [use tag](https://twig.symfony.com/doc/2.x/tags/use.html) instead of the extends tag.

But yeah the statements are a bit contradictory, maybe they could be reworded.

**Comment by fabpot** [comment]
The first sentence is a broad description of Twig.

The note you are referring to explictely compare to PHP, but then goes on to says it is supported via the use tag: "However, Twig supports horizontal reuse."
