### ISSUE TITLE
Stream Twig template

### ISSUE THREAD

**Issue by loevgaard** [twigphp/Twig#2800]
I have a Twig template like this:

```xml
<?xml version="1.0"?>
<items>
    {% for item in items  %}
        <item>{{ item.id }}</item>
    {% endfor %}
</items>
```

but items is a collection of several million rows. Is it possible output the rendering continuously instead of saving the output to memory and saving that to a file?

**Comment by stof** [comment]
Yes it is:

- use `Twig_Environment::display` instead of `Twig_Environment::render`, so that it outputs the rendering instead of buffering it in a string and returning it
- use the `{% flush %}` if needed: https://twig.symfony.com/doc/2.x/tags/flush.html

**Comment by stof** [comment]
hmm, if you want to send it to a file, and not send to the browser, this might be more complex. I'm not sure how to deal with that. Maybe PHP's output buffering system can achieve that.

**Comment by loevgaard** [comment]
Just for future people finding this issue, I made a test command to test it out. This works:

```php
<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Twig\Environment;

final class TestCommand extends Command
{
    private $environment;

    public function __construct(Environment $environment) {
        parent::__construct();

        $this->environment = $environment;
    }

    protected function configure(): void
    {
        $this
            ->setName('test')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): void
    {
        $fp = fopen('template.xml', 'wb+');

        ob_start(function($buffer) use ($fp) {
            fwrite($fp, $buffer);
        }, 1024 /* remove this number to see the difference in memory usage ;) */);

        $this->environment->display('template.xml.twig', [
            'items' => range(0, 500000),
        ]);

        ob_end_clean();

        echo memory_get_peak_usage(true) / 1024 / 1024 . " MB\n";
    }
}
```

Thank you so much for your fast response and great help, @stof!
