### ISSUE TITLE
"Function () does not exist" error

### ISSUE THREAD

**Issue by maverabilisim** [twigphp/Twig#2807]
I'm using custom function in twig defined php side. I receiving just "Function () does not exist"  error.  I can't see function name in Exception reason of error.

**Comment by xabbuh** [comment]
Can you show the exact exception message and its stack trace and can you also show how you registered the function and how you call it?

**Comment by maverabilisim** [comment]
@xabbuh  you can see below link error detail. 
I register custom function like this method. 
$GLOBALS['twig']->addFunction(new Twig_SimpleFunction('getMenuByAttr','getMenuByAttr'));

And other custom function does work. One of them is causing this error. But I can't find it.

![no-func-error-1](https://user-images.githubusercontent.com/8980578/51078964-a55eb700-16cf-11e9-84f6-fddaa1065906.jpg)

**Comment by maverabilisim** [comment]
Hi. Fixed this error. I'm using register wrong method. And I forgot just one parameter.
Wrong register method: 
$GLOBALS['twig']->addFunction(new Twig_SimpleFunction('getMenuByAttr'));
Correct register method: 
$GLOBALS['twig']->addFunction(new Twig_SimpleFunction('getMenuByAttr','getMenuByAttr'));
Thank you @xabbuh
