### ISSUE TITLE
Fatal error after updating to Twig 2.6.1: vars not found

### ISSUE THREAD

**Issue by lukepass** [twigphp/Twig#2810]
Hello, I have a project with Symfony 3.4 and today I updated my composer packages:

```
Package operations: 0 installs, 1 update, 0 removals
  - Updating twig/twig (v2.6.0 => v2.6.1): Loading from cache
```

After this all the pages where I am using the "vars" version in forms are throwing an exception:

```
{# Lessons #}
<div id="accordion">
    {% for lesson in form.lessons %}
        <p>{{ dump(teacher_lesson.vars) }}</p>
    {% endfor %}
</div>
```

`An exception has been thrown during the rendering of a template ("Notice: Undefined index: vars").`

What happened?

Thanks.

**Comment by shinyvision** [comment]
Having the same issue. It seems like Twig is prioritizing ArrayAccess keys above native properties which shouldn't happen.

**Comment by weberdominik** [comment]
I have the same problem but couldn't find any infos about this. Maybe it's a bug?

**Comment by shinyvision** [comment]
Temporary workaround until this is fixed in composer.json:
```
    "conflict": {
        "twig/twig": "2.6.1"
    },
```

**Comment by rpkamp** [comment]
Same here, and `parent` property of `Symfony\Component\Form\FormView` class can't be accessed either, even though it's public.

It would indeed seem that when a class implements `ArrayAccess` -which  `Symfony\Component\Form\FormView` does- only that will be tried to resolve variables, and public vars are no longer checked.

**Comment by hgabka** [comment]
Same problem here

**Comment by symfonyaml** [comment]
Same here
**An exception has been thrown during the rendering of a template ("Notice: Undefined index: vars").**

**Comment by bmxpikr** [comment]
This change causes it:
https://github.com/twigphp/Twig/commit/78a158b21193606270d625d9de88a9703f605c25#diff-d7378002f67a61c458c1de0468eef74fR1466
Trying access `\ArrayAccess` object var like it was an array `$object[$arrayItem]`

**Comment by xabbuh** [comment]
see #2813 which should fix this issue

**Comment by raphaelMalie** [comment]
Same problem here

**Comment by gremo** [comment]
Same problem, waiting for a new release (in the meanwhile, conflict section).
