### ISSUE TITLE
TemplateWrapper::render() fails with "func_get_arg():  Argument 1 not passed to function"

### ISSUE THREAD

**Issue by marcoliverteschke** [twigphp/Twig#2811]
Using 1.37.0 the following call currently fails:

`$twigTemplate->render($variables);`

with the error 

```
func_get_arg():  Argument 1 not passed to function
vendor/twig/twig/lib/Twig/TemplateWrapper.php:45
```

As far as I see it line 45 in TemplateWrapper.php is logically wonky:

`return $this->template->render($context, func_num_args() >= 1 ? func_get_arg(1) : []);`

This says "if we have one or more arguments always use the second one". But "one or more" means there is no guarantee we actually have a second argument.

So I guess it should be `>` instead of `>=`, no?

**Comment by fabpot** [comment]
fixed in 361d864178ea6abb86722633b6c9bd509a6e9930
