### ISSUE TITLE
BC Break for 2.6.1. Can't access public properties for \ArrayAccess instances

### ISSUE THREAD

**Issue by BoShurik** [twigphp/Twig#2814]
The code below now throws exception `Notice: Undefined index: parent`
```twig
{% block form_widget_compound %}
    {% spaceless %}
        <div {{ block('widget_container_attributes') }}>
            {% if form.parent is empty %}
                {{ form_errors(form) }}
            {% endif %}
            {{ block('form_rows') }}
            {{ form_rest(form) }}
        </div>
    {% endspaceless %}
{% endblock form_widget_compound %}
```
`form` is an instance of https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormView.php

`parent` and `children` are properties of the class but tries to be accessed thru `offsetGet` method

Also
```
{% if form.parent is defined %} {# true #}
   {{ form.parent }} {# Exception #}
{% endif %}
```

**Comment by stof** [comment]
that's a know bug, which is already solved in the dev version. See #2810

**Comment by andrew-demb** [comment]
I have the same problem for '.vars'
