### ISSUE TITLE
Getting the parent instance as "Twig_Markup" instead of the expected "__TwigTemplate_yyyyy" using _self.getParent([])

### ISSUE THREAD

**Issue by bs-thomas** [twigphp/Twig#2818]
**Edited and reworded a little as I had some errors and wasn't very clear in my original question**

I noticed a weird behavior which I'm not sure if it's expected, or if there is some sort of issue with it.

Let's so I have two templates:
(a) Template A
(b) Template B (extends (a)

-----

**Scenario A (Working)**

If I am rendering and displaying (b), and inside, I have a line where I pass in the "_self" variable (to my understanding the _self is something similar to $this) when calling some sort of global PHP function (let's call that someFunc) and then "dump" that variable inside someFunc, the variable class type is "__TwigTemplate_xxxxxxx" :

`{% set result = someFunc(_self) %}`

```
function someFunc($_self)
{
    dump($_self)  // type __TwigTemplate_xxxxx
    dump($_self.getParent([]))  // the extended parent template, __TwigTemplate_yyyyy
    dump($_self.getParent([]).getParent([]))  // the extended grandparent template, __TwigTemplate_zzzzz
}
```

The above is all expected.  And then cool thing is, I could keep chaining with getParent([]) to get all my ancestry names by using ->getTemplateName() or simply cast it as (string) and get the equivalent.

-----

**Scenario B (Not Working)**

My issue, however, is with the twig template itself below.

Let's say if I want to do something very similar directly inside the Twig template first.  Instead of resolving the parent using $_self->getParent() inside my global PHP function, I do that in Twig before passing over to someFunc() by using _self.getParent([])

Like this:
`{% set result = someFunc(_self.getParent([])) %}`

Then, I dump this in the global PHP function someFunc():
```
function someFunc($_self)
{
    dump($_self)  // expected __TwigTemplate_yyyyy, but type Twig_Markup
    dump($_self.getParent([]))  // Call to undefined method Twig_Markup::getParent()
    dump($_self.getParent([]).getParent([]))  // won't get here, but obviously won't work.
}
```

My question is, why does calling `_self.getParent([])` (which I expected to do the same thing as that of the former scenario in PHP) returned me a class of type "Twig_Markup" instead of the expected class type "__TwigTemplate_yyyyy"?

Is this an expected behavior?

If so, is there any possible way of getting the real parent instance "__TwigTemplate_yyyyy" inside the Twig template?

Your help is appreciated.

**Comment by ericmorand** [comment]
I don't even know how your first attempt works. From the documentation:

https://twig.symfony.com/doc/2.x/templates.html#global-variables

> The following variables are always available in templates:
>
> _self: references the current template name;

Something is very strange there.

**Comment by fabpot** [comment]
As of Twig 2, the `_self` variable is a string. Using it as an object in Twig 1 is deprecated. So, let's close as won't fix.
