### ISSUE TITLE
twig_date_converter timezone with time

### ISSUE THREAD

**Issue by anuri73** [twigphp/Twig#2819]
Hello, I want to understand the logic of code in file twig/twig/lib/Twig/Extension/Core.php, line 433:

> $asString = (string) $date;
    if (ctype_digit($asString) || (!empty($asString) && '-' === $asString[0] && ctype_digit(substr($asString, 1)))) {
        $date = new DateTime('@'.$date);
    } else {
        $date = new DateTime($date, $env->getExtension('Twig_Extension_Core')->getTimezone());
    }

Why we initialize Datetime on second condition with default timezone if we got it in **$timezone** variable earlier? 

When I used this function with only times ("H:i") this function returns value in another timezone(UTC) and not what I expected(Ex: Asia/Almaty).

Steps to reproduce:
{{ train.Departure.Time | date('H:i', 'Asia/Almaty') }} return time in UTC timezone. But as you can see, I want to get time in Asia/Almaty timezone
where train.Departure.Time is some DateTime value

**Comment by xabbuh** [comment]
Are you sure that `train.Departure.Time` is a `DateTime` object? Because in this case the function should exit earlier and never reach that point.

**Comment by anuri73** [comment]
I think, You mean:
> if ($date instanceof DateTimeInterface) {

I'll check it again, but I'm pretty sure that $date was instance of DateTime

**Comment by fabpot** [comment]
@anuri73 I'm closing as you weren't sure. Feel free to reopen if needed.
