### ISSUE TITLE
Twig 1.37 can't used in php5.4

### ISSUE THREAD

**Issue by reatang** [twigphp/Twig#2820]
The rendered template file USES the syntax of php7

![image](https://user-images.githubusercontent.com/8022923/51592658-210bff80-1f2b-11e9-8ef8-b2e6936f1d09.png)

**Comment by xabbuh** [comment]
Did you by any chance run the compiling process with PHP 7? The compiler generates different PHP code depending on the PHP version used during compilation.

**Comment by reatang** [comment]
yes run in php7 😨 。
Is this a compatibility feature ?!

**Comment by xabbuh** [comment]
I don't understand what you mean. If your environment rendering the templates uses PHP 5.4, you should also use PHP 5.4 to compile your templates. Does that answer your question?

**Comment by stof** [comment]
The compiled template indeed uses features available in the PHP runtime used to compile the template. Compiling templates on a PHP version and then copying them to a different PHP runtime is not supported (btw, the cache should even consider it as a cache miss and recompile the template, as the PHP major and minor versions are part of the cache key)
