### ISSUE TITLE
Misleading error message when using an unknown tag inside an "if" tag

### ISSUE THREAD

**Issue by ureimers** [twigphp/Twig#2821]
Hi,

when you use an undefined tag in your template like:

`{% undefined_custom_tag %}`

You'll get the error message:

> `Unknown "undefined_custom_tag" tag.`

Which is clear and understandable. But as soon as you wrap that undefined tag inside an "if" tag like:

```
{% if true %}
    {% undefined_custom_tag %}
{% endif %}
```

The error message becomes:

> `Unexpected "undefined_custom_tag" tag (expecting closing tag for the "if" tag defined near line 2).`

I had this in a very large file down in some nested "if"s and the error message made me think that I forgot to close an "if" tag somewhere but they where all correct. So I removed them one by one until all nested "if"s where gone and I finally had the real error message:  `Unknown "undefined_custom_tag" tag.`

I marked this issue [UX] at first but while writing it I came to the conclusion that the error message is actually wrong. The tag isn't just unexpected, it's unkown.

It seems that because it's unknown, Twig's parsing of the surrounding "if" tag gets broken/confused and then produces this misleading error message.

Best regards

Ulf

The Twig version this occurred was  v2.6.2.

**Comment by SpacePossum** [comment]
for reference: https://github.com/twigphp/Twig/issues/2390#issuecomment-281556395

**Comment by ureimers** [comment]
@SpacePossum, Thanks for the reference.

Dang, and I really looked for a similar issue before creating this. But I only searched the open issues. As Fabien already stated that this remains a wont-fix for the foreseeable future, I'll close this ticket because in the end it's a duplicate.
