### ISSUE TITLE
Twig auto cast "id" to "0" instead of value in Eloquent array.

### ISSUE THREAD

**Issue by ogwugo** [twigphp/Twig#2822]
I am getting "0" instead of the string value of data that is key "id".

$counties = Countries::all();

// twig
 {% for country in countries %}
                 {{ country.name }} ({{ country.id }}) 
                        {% endfor %}

here, the model table the country has colums "id" and "name"
the "name" prints and the "id" is showing "O" instead of the normal country ID which is eg. NG, US, etc.
if I rename the "id" to "my_id" it works. MY QUESTION IS "is this a bug or what is twig doing to 'id' in my loop."

**Comment by xabbuh** [comment]
What does your `Country` class (or whatever class `country` refers to) look like?

**Comment by ogwugo** [comment]
I just discovered its Eloquent side: Eloquent auto cast "id" to int i have fixed that with 
    protected $casts = ['id' => 'string'];
 in her model class
