### ISSUE TITLE
Bug in containment operator?

### ISSUE THREAD

**Issue by ovgray** [twigphp/Twig#2824]
it seems that 
`{% if 'text' in [0] %}bug{% else %}no bug{% endif %}`
and 
`{% if 'text' in {0: 0} %}bug{% else %}no bug{% endif %}`
return 'bug', whereas
`{% if 'text' in ['0'] %}bug{% else %}no bug{% endif %}`
and 
`{% if 'text' in {0: '0'} %}bug{% else %}no bug{% endif %}`
return 'no bug'

Shouldn't `'text' in [0] ` evaluate as false?

**Comment by jvasseur** [comment]
It's the normal PHP behavior here: `in_array('test', [0])` return `true`, that's because when comparing an int and a string php cast the string into an int and compare the result, thus for PHP `'test' == 0`.

**Comment by ovgray** [comment]
I see. 
It might be helpful for the documentation to say that the Twig 'in' operator does not use, and does not provide, the strict checking option that php provides for its `in_array` function.

**Comment by ericmorand** [comment]
@jvasseur this is the normal PHP behavior but this is a TwigPHP bug nonetheless. 

Here is the official Twig spec for the in operator:

https://twig.symfony.com/doc/2.x/templates.html#containment-operator

> The in operator performs containment test.
> It returns true if the left operand is contained in the right:

"text" in _not_ contained in [0], so the specs are not respected there. As a language, Twig enforces it owns specifications. Template developers read the specifications to know what each language construct does. TwigPHP should accomodate to those specifications. Or this is a bug.

**Comment by jvasseur** [comment]
> "text" in _not_ contained in [0]

That's not exactly true, in the sense of PHP equality `"text"` is contained in `[0]` since `"text" == 0`.

**Comment by ericmorand** [comment]
So it should be explictely documented by the Twig specifications.

I could write a language that defines an '==' operator that returns true if left and right operands are equal. And everybody would implicitely understands that 1 == 0 would return false. If 1 == 0 returns true, this is a bug and the following explanation "well, in our implementation of the language, 0 is considered equal to everything so deal with it" would be considered bad faith.

Sensiolabs needs to sanitize their PHP implementation.

**Comment by ericmorand** [comment]
@jvasseur and by saying this

> That's not exactly true, in the sense of PHP equality `"text"` is contained in `[0]` since `"text" == 0`.

You talk about the PHP implementation. I'm talking about the language itself.

**Comment by fabpot** [comment]
The current behavior is indeed the same as the one for PHP. The most common complaint is indeed the one reported here.

Note that it might change in PHP 8: https://wiki.php.net/rfc/string_to_number_comparison

What about implementing this new "algorithm" in Twig (only for the `in` test -- doing it for all comparison would make Twig too slow)?

**Comment by fabpot** [comment]
see #2954 for a possible improvement.
