### ISSUE TITLE
Twig 2 requires PHP >= 7.2.0

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2827]
Some bug fixes broke compatiblity of Twig 2 with PHP < 7.2.0. Namely, the usage of [mb_ord](http://php.net/manual/fr/function.mb-ord.php) in Core.php.

Twig 2 documentation still explicitly say that it needs onlt PHP 7.0.0 to function.

This is a breaking change if this is confirmed. A minor version bump should not create breaking changes.

**Comment by xabbuh** [comment]
This shouldn't be an issue. Twig as a dependency on the `symfony/polyfill-mbstring` package which provides a polyfill of this function for older PHP versions (see also #2750 where the usage was introduced).

**Comment by ericmorand** [comment]
Yes, good catch. Thanks for the clarification.
