### ISSUE TITLE
What is the rational behing the existence of Twig_TemplateWrapper

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#2828]
As I'm planning Twing@3 that will come with some cleaning, I am wondering what Twig_TemplateWrapper is supposed to be used for? I know that you can load a template by passing another template instead of a name and that it returns a template wrapper.

But I'm wondering what is the use case for that. And what are the benefits of returning a wrapper instead of the template itself.

**Comment by jvasseur** [comment]
That's because the `Template` class is internal to Twig. The `TemplateWrapper` allow exposing a public subset of the `Template` class.

**Comment by fabpot** [comment]
@jvasseur is correct.
