### ISSUE TITLE
twig tags as attributes aka `<div twig:if="">`

### ISSUE THREAD

**Issue by sod** [twigphp/Twig#2835]
You ever considered allowing twig tags also used via html attributes?

```twig
// instead of:
{% if value %}
    <div>
        {{ text }}
    </div>
{% endif %}

// You could also do:
<div twig:if="value">
    {{ text }}
</div>
```

```twig
// instead of:
<input type="{{ type|default('text') }}"
       class="form-control{% if has_error %} has-error{% endif %}"
       {% if checked %} checked{% endif %}></a>

// You could also do:
<input type="{{ type|default('text') }}"
       class="form-control"
       twig:class.has-error="has_error"
       twig:attr.checked="checked">

// or:
<input class="form-control"
       twig:attr="{type: type|default('text'), checked: checked}"
       twig:class="{'has-error': has_error}">
```

```twig
// instead of:
{% if values %}
    <ol twig:if="values">
        {% for value in values %}
            <li>{{ value }}</li>
        {% if values %}
    </ol>
{% endif %}

// You could also do
<ol twig:if="values">
    <li twig:for="value in values">{{ value }}</li>
</ol>

<ol twig:if="values" twig:for-inner="value in values">
    <li>{{ value }}</li>
</ol>
```

Benefits
* less indentation changes if you introduce an if => nicer code history
* no need to close tags - the html element defines it already
* easier to combine with vuejs or angularjs

Would twig be open for pull requests to allow such a feature? I guess the hard part would be, that twig doesn't parse the content at all and this would require the templates to be parsed by an html parser (that also understands the current syntax).

**Comment by fabpot** [comment]
That would be a totally different template engine. And currently, Twig is not just for HTML, but for any type of files. So, I'm going to close this issue as it won't happen. Thank for the suggestion.
