### ISSUE TITLE
Alias Twig_Environment as Twig_Twig & Twig\Twig

### ISSUE THREAD

**Issue by ro0NL** [twigphp/Twig#2856]
Twig is a concept, but its main entry point `Environment` (im using the namespaced classes) looks 100% arbitrary.

We fix it using `Environment $twig`, but ideally this be `Twig $twig` (or `TwigEnvironment` if you like) IMHO.

Im here to see if putting `Environment as TwigEnvironment` everywhere can be avoided by doing it in core :) if not  i guess we'll settle with  `Environment $twig` for convenience :cry: 

It could also be an alternative alias to avoid deprecation hassle.

WDYT?

**Comment by fabpot** [comment]
hehe, something I've been thinking of for a long time... and I actually started to work on it (more classes need to be renamed).

**Comment by fabpot** [comment]
will be fixed by #2857

**Comment by fabpot** [comment]
see https://github.com/twigphp/Twig/pull/2857#issuecomment-469601425 for the reasons why I won't do it.
