### ISSUE TITLE
Documentation website is not responsive

### ISSUE THREAD

**Issue by garak** [twigphp/Twig#2867]
Sad to say, https://twig.symfony.com/ is not responsive at all.
I couldn't find a way to contribute to such problem, since it looks like only documentation source is present on this repository, while the building process is likely elsewhere.

**Comment by stof** [comment]
/cc @javiereguiluz @fabpot 
I think you are the only ones who could fix this.

**Comment by SeinopSys** [comment]
Site appears to be back up and running now.

**Comment by garak** [comment]
@seinopsys up and running, but still not responsive

**Comment by SeinopSys** [comment]
@garak Oh, sorry, my bad. I thought you meant the site went down.

**Comment by fabpot** [comment]
The website is now responsive \o/
