### ISSUE TITLE
random () in between two integers not working as exected

### ISSUE THREAD

**Issue by dirkjf** [twigphp/Twig#2876]
When I use `{{ random(50, 100) }} ` a random number between 0-50 will be generated, not between 50-100, such as described [here](https://twig.symfony.com/doc/2.x/functions/random.html).

**Comment by SpacePossum** [comment]
Hi,
Can you share the Twig version you are using? For example when installed using composer:
> $ composer info|grep twig/twig

I just tested with:

```php
<?php
require_once __DIR__.'/vendor/autoload.php';

$loader = new \Twig\Loader\ArrayLoader([
    'index' => str_repeat("{{ random(50, 100) }}\n", 100),
]);

$twig = new \Twig\Environment($loader);

echo $twig->render('index');
```

and 

```php
<?php
require_once __DIR__.'/vendor/autoload.php';

$loader = new \Twig\Loader\FilesystemLoader(__DIR__);
$twig = new \Twig\Environment($loader);

echo $twig->render('test.twig');
```

```twig
{{ random(50, 100) }}
{{ random(50, 100) }}
{{ random(50, 100) }}
{{ random(50, 100) }}
{{ random(50, 100) }}
{{ random(50, 100) }}
{{ random(50, 100) }}
```

on tag v1.9.2 and all seems fine

**Comment by dirkjf** [comment]
V2.6.2 is what I use. I tried it in two different projects and get the same bad result.

**Comment by stof** [comment]
`New in version 2.7: The "max" argument was added in Twig 2.7.`. So 2.6.2 does not have it. It only has the signature with 1 argument
