### ISSUE TITLE
Is 1.38.1 broken? 

### ISSUE THREAD

**Issue by bobdenotter** [twigphp/Twig#2892]
Was the release of Twig 1.38.1 correct? It seems like a _huge_ delta for a minor release, and some things broke for us. 

One of the things that's breaking is that this doesn't work anymore: 

```php
$template = $twig->resolveTemplate($template);
$template->getTemplateName();
```

Would give something like this on 1.37.1: `"@bolt/dashboard/dashboard.twig"`

On 1.38.1 it gives: 

![Schermafbeelding 2019-03-12 om 18 05 48](https://user-images.githubusercontent.com/1833361/54220346-7c04b080-44f1-11e9-94bc-37d12561cf91.png)

Same for `$var = (string) $template;`. On 1.37.1 it works, on 1.38.1 it gives: 

![Schermafbeelding 2019-03-12 om 18 06 50](https://user-images.githubusercontent.com/1833361/54220414-a2c2e700-44f1-11e9-96c7-760745f4126c.png)

It's hard to pinpoint where it broke, because of the huge delta of the update. I assume it's because of this: 

> That's why, starting from the next 2.x version, all non- namespaced classes will be deprecated and > they will be removed in Twig 3.x, which is expected to be released during 2019.

Was this intentional for the 1.x patch?

**Comment by fabpot** [comment]
I think that's because `resolveTemplate()` now returns a `TemplateWrapper` instance instead of a `Template` instance in previous releases. The `Template` class is marked as internal, so, calling methods on it is not supported.

**Comment by bobdenotter** [comment]
Hmm. Do you have suggestion for a workaround to get the filename of a resolved template?

**Comment by JarJak** [comment]
Looks like more projects are affected by this change: https://github.com/twigphp/Twig/issues/2889

**Comment by fabpot** [comment]
@JarJak Does not seem to be the same issue (that one has been fixed and released).

**Comment by fabpot** [comment]
@bobdenotter Can you add the method manually and see if that's the only method needed to make the system work again? If yes, I might add it to avoid the BC break for you.

**Comment by stof** [comment]
@fabpot why did you change the return value of `resolveTemplate` in Twig 1.38 ? I think using TemplateWrapper was done only in 2.0 previously precisely because of BC.

**Comment by fabpot** [comment]
As I said, `Template` is marked as internal. Anyway, if it is just about that method, I suppose it does not hurt to add it to `TemplateWrapper`.

**Comment by stof** [comment]
Well, the issue also reports using the string casting.

**Comment by bobdenotter** [comment]
@fabpot Thanks! 

Adding the following method to `Twig\TemplateWrapper` does indeed fix it:

```php
    /**
     * @return string
     */
    public function getTemplatename()
    {
        return $this->template->getTemplateName();
    }
```

**Comment by fabpot** [comment]
see #2893
