### ISSUE TITLE
Loader is broken on all 1.38.x Releases

### ISSUE THREAD

**Issue by toxpal** [twigphp/Twig#2895]
Upgraded from 1.37.1 to 1.38.2 and get fatal error about loader now. I used this line to start loader in the past and it worked great:
`$loader=new Twig_Loader_Filesystem("/my/templates/dir");`

Now it returns error:
`Fatal error: Uncaught Error: Class 'Twig_Loader_Filesystem' not found`

Since 1.38.x changelog mentions some important changes, I opened documentation ( https://twig.symfony.com/doc/1.x/api.html ) and changed loader code into this (as per documentation example):

`$loader=new \Twig\Loader\FilesystemLoader("/my/templates/dir");`

And it still returns fatal error:
`Fatal error: Uncaught Error: Class 'Twig\Loader\FilesystemLoader' not found`

Tried with 1.38.0, 1.38.1 and 1.38.2 - exactly the same error. 

So how do I start loader in 1.38.x, if examples in official documentation don't work? Thanks.

P.S. Obviously, I include these lines before trying to start loader:

```
require_once '/path/to/lib/Twig/Autoloader.php';
Twig_Autoloader::register();
```

**Comment by fabpot** [comment]
You should not use the `Twig_Autoloader` class. Are you (not) using Composer?

**Comment by toxpal** [comment]
No, I don't. I manually included Twig files in my project, and it always worked great.

**Comment by fabpot** [comment]
ok, so now I understand the issue. I will need to patch the current autoloader. I will do it today or tomorrow.

**Comment by toxpal** [comment]
Thank you for your super-fast response. Will downgrade back to 1.37.1 for now...

**Comment by fabpot** [comment]
@toxpal Can you confirm that #2896 fixes your issue?

**Comment by toxpal** [comment]
Unfortunately, I still have exactly the same error after downloading 1.38.2 and using your modified Autoloader.php file. Tried:

`$loader=new Twig_Loader_Filesystem("/my/templates/dir");`
and
`$loader=new \Twig\Loader\FilesystemLoader("/my/templates/dir");`

**Comment by fabpot** [comment]
I've just tried again with your code and it works for me.

Here is the bootstrap sequence I'm using:

```php
<?php

require_once __DIR__."/lib/Twig/Autoloader.php";
Twig_Autoloader::register();

```

I'm going to make a release with my patch.

**Comment by toxpal** [comment]
> I've just tried again with your code and it works for me.

That's nice. Unfortunately, it still doesn't work for me. And I didn't make any changes to my code for months, and it only happens when I upgrade to 1.38.x.

I also slightly modified your code for debugging reasons, and I found that code example from documentation doesn't even start autoloader (while my old code does). Here's your modified code:

```
public static function autoload($class)
    {
        if (0 !== strpos($class, 'Twig')) {
            return;
        }
        if (is_file($file = __DIR__.'/../'.str_replace(['_', "\0"], ['/', ''], $class).'.php')) {
            echo "this is debug line 1";
            require $file;
        } elseif (is_file($file = __DIR__.'/../../src/'.str_replace(['Twig\\', '\\', "\0"], ['', '/', ''], $class).'.php')) {
            echo "this is debug line 2";
            require $file;
        }
    }
```

If I use code right from current documentation:
`$loader=new \Twig\Loader\FilesystemLoader("/my/templates/dir");`

only message **Fatal error: Uncaught Error: Class 'Twig\Loader\FilesystemLoader' not found** is displayed.

If I use my old code (which I got from old documentation a lot of time ago):
`$loader=new Twig_Loader_Filesystem("/my/templates/dir");`

at least I get this:
**this is debug line 1
Fatal error: Uncaught Error: Class 'Twig_Loader_Filesystem' not found**

**Comment by fabpot** [comment]
@toxpal Can you share with me an archive that exhibits the issue? I'm not able to reproduce it, so I don't really know what to do.

**Comment by toxpal** [comment]
Absolutely. https://nofile.io/f/CZZvpxzaBwm/twig_test.zip

It now uses Twig 1.37.x and works perfectly. Once you replace /lib/Twig with 1.38.x (even including your modified autoloader), you should see fatal errors.

**Comment by fabpot** [comment]
@toxpal Thank you, that helps a lot! You need the `lib/` and the `src/` directory. That will fix the error.

**Comment by toxpal** [comment]
Thanks, it really did the trick (had to apply your modified autoloader too). Just not very sure why all previous releases (using Twig for about 2 years) worked without /src. Anyways, tahnks again for your help.

**Comment by stof** [comment]
@toxpal previous releases had the non-namespaced classes (in `lib`) be the main code, and the namespaced classes (in `src`) be the alias. 1.38 and 2.7 reversed that (as 3.x will not have non-namespaced classes anymore).
So for previous releases, removing the `src` folder would work as long as you never used the namespaced classes (which were already available since a long time when using the composer autoloading)

**Comment by toxpal** [comment]
Thanks, it's super clear now.
