### ISSUE TITLE
Loader function undefined on new install

### ISSUE THREAD

**Issue by adendrag** [twigphp/Twig#2903]
Hi,

I've just installed twig using composer on an nginx server running php 7.0.33-5. Created a simple php file just to make sure it was working:
```
<?php
require_once 'vendor/autoload.php';

$loader = \Twig\Loader\FilesystemLoader('templates/');
$twig = new \Twig\Environment($loader);
?>
```
However I am getting the below error on the page:
 `Fatal error: Uncaught Error: Call to undefined function Twig\Loader\FilesystemLoader()`

I've updated composer and made sure nginx is actually using php7 in the config file, but I can't think of anything else that would cause this. Suggestions?

Thanks!

**Comment by fabpot** [comment]
You forgot to use `new` when creating the load: `$loader = new \Twig\Loader\FilesystemLoader('templates/');`
