### ISSUE TITLE
Error must be instance of AbstractExpression, instance of CheckToStringNode given

### ISSUE THREAD

**Issue by scotteuser** [twigphp/Twig#2908]
Apologies if this is related to Drupal's implementation of Twig rather than Twig itself. 

We get this error:

> TypeError: Argument 1 passed to Twig\Node\Expression\ArrayExpression::addElement() must be an instance of Twig\Node\Expression\AbstractExpression, instance of Twig\Node\CheckToStringNode given, called in /var/www/html/vendor/twig/twig/src/Node/Expression/CallExpression.php on line 193 in Twig\Node\Expression\ArrayExpression->addElement() (line 59 of vendor/twig/twig/src/Node/Expression/ArrayExpression.php).

In vendor/twig/twig/src/NodeVisitor/SandboxNodeVisitor.php there is:
```
private function wrapNode(Node $node, $name)
{
    $expr = $node->getNode($name);
    if ($expr instanceof NameExpression || $expr instanceof GetAttrExpression) {
        $node->setNode($name, new CheckToStringNode($expr));
    }
}
```
Both NameExpression and GetAttrExpression extend AbstractExpression.

CheckToStringNode does not extend AbstractExpression; if it does, the error goes away. I am not confident at all that that is a good solution though or whether this is related to our implementation of Twig within Drupal and not Twig itself - apologies if so!

Proposed resolution:
```
diff --git a/src/Node/Node.php b/src/Node/Node.php
index d60367ff..79325e06 100644
--- a/src/Node/Node.php
+++ b/src/Node/Node.php
@@ -13,13 +13,14 @@
 namespace Twig\Node;
 
 use Twig\Compiler;
+use Twig\Node\Node\AbstractExpression;
 
 /**
  * Represents a node in the AST.
  *
  * @author Fabien Potencier <fabien@symfony.com>
  */
-class Node implements \Twig_NodeInterface
+class Node extends AbstractExpression implements \Twig_NodeInterface
 {
     protected $nodes;
     protected $attributes;
```

Related Drupal issue:
https://www.drupal.org/project/devel/issues/3040310#comment-13032344

Patch:
[twig-must-be-abstractexpression-checktostringnode-given-1.txt](https://github.com/twigphp/Twig/files/2991097/twig-must-be-abstractexpression-checktostringnode-given-1.txt)

**Comment by stof** [comment]
the proposed solution is wrong, as it would make all nodes extend AbstractExpression (and btw, AbstractExpression currently extends Node)

@fabpot shouldn't CheckToStringNode extend AbstractExpression ?

**Comment by fabpot** [comment]
@scotteuser Can you give me more information about when that happens? A template that fails for instance?

**Comment by stof** [comment]
Well, as it is used inside expressions, it should be an expression node though

**Comment by fabpot** [comment]
I understand that, but I fail to see how this can happen.

**Comment by scotteuser** [comment]
Sorry I haven't been able to post more details yet, managed to reproduce this morning before work, just writing out steps and maybe creating a sample git repo to demo, will try to have this to you tomorrow.

**Comment by scotteuser** [comment]
Okay I have created a repo to reproduce the issue without the need to install Drupal 8 in any way.

Steps to reproduce:
```
git clone git@github.com:scotteuser/twig-issue-2908.git
cd twig-issue-2908
composer install
# View in browser
```

In index.php I am loading the following:

1. Drupal 8's default Twig Sandbox found at web/core/lib/Drupal/Core/Template/TwigSandboxPolicy.php
1. Drupal 8 Devel module's Kint class which the twig extension requires found at web/modules/contrib/devel/kint/kint
1. Drupal 8 Devel module's Kint twig extension found at web/modules/contrib/devel/kint/src/Twig/KintExtension.php

If you comment out the sandbox in index.php the error goes away so I imagine it has something to do with that.

To reproduce in Drupal 8:
```
composer create-project drupal-composer/drupal-project:8.x-dev twig-issue-2908 --no-interaction
cd twig-issue-2908
composer require drupal/devel
# Install Drupal eg in browser or with drupal console with `drupal site:install`
drush pm-enable devel,kint -y
# Add the following to any twig template.
{% set some_var = {
    'test'   : 'Testing',
    'test2' : 'Test 2',
} %}
{{ kint(some_var) }}
```

**Comment by fabpot** [comment]
@scotteuser Great! THANK YOU, I would have never found the issue without your code. So, there is indeed a bug in Twig, pull request coming soon now.

**Comment by fabpot** [comment]
PR ready #2913

**Comment by scotteuser** [comment]
Great, glad it helped - thanks for sorting so quickly!

**Comment by fabpot** [comment]
@scottasmith New versions released.
