### ISSUE TITLE
Match case

### ISSUE THREAD

**Issue by alex-ception** [twigphp/Twig#2911]
Hi everyone,

Using Twig with some ESI, in dev env, I have two sources of informations which (I assume) are not using any cache. The first data key is uppercase, let say "FOO", and the other one rendered by `render_esi(controller('MyBundle:MyController:MyAction'))` is having a lowercased key for another template named "foo". Having the both of them cause an exception on further business oriented code.

First of all, am I right when I say there is no match case on twig variables ? And then, if I'm right, is it possible to have a fix on it ? I don't know Twig source code enough to do it.

Any help and comments are appreciated. 

Thanks ;)

**Comment by xabbuh** [comment]
I am not sure I understand what you mean. Variable names are case-sensitive in Twig if that's your question (see https://twigfiddle.com/11al3k).

**Comment by alex-ception** [comment]
Let say there is a controller rendering one twig template like "index.html.twig" having a variable called "foo" (value is an array for example).
On the other hand a controller rendering another twig template "menu.html.twig" having a variable also called "foo" (value is an int).
Each controllers with their templates works fine on their own.

Now, imagine the first template is doing this `{{ render_esi(controller('secondControllerRenderingSecondTemplate')) }}`

Here is what happens :
![conflict](https://user-images.githubusercontent.com/636722/54835447-6138f580-4cc2-11e9-95d6-11145c394704.png)

Using the "foo" variable in the second template (menu.html.twig in this case) is resolved as being an array.

**Comment by xabbuh** [comment]
I am not sure what you are doing there. Maybe you can extract a small example application that allows to reproduce so someone can take a look at it.

**Comment by fabpot** [comment]
Closing as there is no more feedback.
