### ISSUE TITLE
Somethin new in 2.7.x?

### ISSUE THREAD

**Issue by labby** [twigphp/Twig#2915]
Hi there
up to 2.6.2 we used the folder lib/Twig from your released zips as a library and created our own loader/autoloader.
Starting with 2.7x this doesn't work anymore.
I tried to find out what happend but didn't succeeded.
Are there some hints to what was modified tp prevent our lib from working?
Thanks

**Comment by iammichiel** [comment]
Hi, 

I think that starting from 2.7, Twig has become namespaced. See this blog-post for more information : https://symfony.com/blog/new-in-twig-namespaced-classes

**Comment by stof** [comment]
you need to autoload the `src` folder of Twig as well, which contains the namespaced code (which is now the actual codebase as of 2.7 while `lib` contains aliased legacy classes, which was the opposite before 2.7)

**Comment by labby** [comment]
So we have to use the folder src in addition to the lib/Twig folder or instead?

**Comment by stof** [comment]
Well, if you still use the non-namespaced class names in your code (which are deprecated and will be removed in 3.0), the answer is "in addition"

**Comment by labby** [comment]
Thanks for info

**Comment by labby** [comment]
We just fixed it, thanks
