### ISSUE TITLE
Indentation Plugin

### ISSUE THREAD

**Issue by prohde** [twigphp/Twig#2917]
Hi,

I am quite knew to Twig. One thing that bothers me is the wrong indentation of the generated output. I found a [gist](https://gist.github.com/urraka/ccd1812570ca4b278b9f) with a plugin for Twig to correct the indentation of the output. Unfortunately this works only for Twig <2.0.0 because all members of Twig_Lexer were changed from protected to private.

So my questions are as follows:
* Is there any reason why the Lexer members are private now?
* Is there a way to get this plugin running with Twig > 2.0.0?
* How could one correct the indentation of the output?

**Comment by fabpot** [comment]
See #2925

**Comment by prohde** [comment]
This doesn't fix my problem. I am still not able to produce output with correct indentation.

I have the following code in my template:
```
  <form action="?login=1" method="post">
    {{ macros.table(rows) }}
  </form>
```

The macro is defined as:
```
{# creates a table with the given rows, each row has to contain cells with alignment, content and optional width #}
{% macro table(rows, width) %}
  <div class="table"{% if width %} style="width: {{ width }}"{% endif %}>
    {% for row in rows %}
      <div class="table-row">
        {% for cell in row %}
          <div class="{% if cell.align == 'center' %}table-cell-centered{% elseif cell.align == 'right' %}table-cell-right-aligned{% elseif cell.align == 'right-top' %}table-cell-right-aligned-top{% else %}table-cell{% endif %}"{% if cell.width %} style="width: {{ cell.width }}"{% endif %}>{{ cell.content|raw }}</div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{%- endmacro %}
```

The generated output is:
```
    <form action="?login=1" method="post">
      <div class="table">
          <div class="table-row">
                  <div class="table-cell-right-aligned"><label>user name:</label></div>
                  <div class="table-cell"><input type="text" name="username" placeholder="" required /></div>
              </div>
          <div class="table-row">
                  <div class="table-cell-right-aligned"><label>password:</label></div>
                  <div class="table-cell"><input type="password" name="password" required /></div>
              </div>
      </div>
      <div class="table">
          <div class="table-row">
                  <div class="table-cell-centered"><button type="reset">clear</button>&nbsp;<button type="submit">log in</button></div>
              </div>
      </div>
  </form>
```

First thing I do not understand is why in the output the difference between indentation levels is 4 spaces, when I use 2 in my php and twig files. The closing div tag for the rows is one level higher than the opening one and cells are indented two levels instead of one. Also `</form>` is missing 2 spaces to match the indentation of the start of the form.
I tried many different places for `-` and `~` for controlling the whitespaces but this is the best result I am able to produce.

The desired output would be:
```
    <form action="?login=1" method="post">
      <div class="table">
        <div class="table-row">
          <div class="table-cell-right-aligned"><label>user name:</label></div>
          <div class="table-cell"><input type="text" name="username" placeholder="" required /></div>
        </div>
        <div class="table-row">
          <div class="table-cell-right-aligned"><label>password:</label></div>
          <div class="table-cell"><input type="password" name="password" required /></div>
        </div>
      </div>
      <div class="table">
        <div class="table-row">
          <div class="table-cell-centered"><button type="reset">clear</button>&nbsp;<button type="submit">log in</button></div>
        </div>
      </div>
    </form>
```

How could one achieve the desired output?

**Comment by stof** [comment]
Well, Twig does not know about the HTML being rendered, so it won't try to re-indent it. The 4 spaces come from the indentation of your `<div class="table-row">` line compared to the `<div class="table"{% if width %} style="width: {{ width }}"{% endif %}>` line in your Twig template.

If you really want to provide beautifully indented HTML, I suggest you to run an HTML formatter on the rendered HTML after running Twig (or stop caring about that indentation in favor of avoiding the overhead of such formatting).
This indentation is not something which can be solved by Twig itself, because Twig is not specific to rendering HTML.

**Comment by prohde** [comment]
True, but the plugin linked in the first post achieves re-indentation of the rendered HTML. But this approach is no longer working since all members of Twig_Lexer are private since version 2.0.

**Comment by stof** [comment]
well, this "plugin" was not using official extension points of Twig, and would break also when we change things in the parent class (for instance, I'm quite sure that the change done to introduce line-level whitespace control also breaks it, or that it breaks the feature, or maybe both)

**Comment by prohde** [comment]
Okay, I see that point!

**Comment by stof** [comment]
Oh, and that plugin also does not work well as soon as include gets involved for instance (and it might totally break non-HTML templates as it applies to all templates)

**Comment by prohde** [comment]
@stof Do you know any good HTML formatter in PHP? The ones I found aren't really maintained anymore and have issues.
