### ISSUE TITLE
Twig 1.38.4 with Drupal 8.6.13 breaking the theme

### ISSUE THREAD

**Issue by guardiola86** [twigphp/Twig#2920]
I've just upgraded Drupal to 8.6.13 and Twig to 1.38.4 and I'm using a theme which has classy as base theme. I'm getting these errors: 
https://www.drupal.org/project/drupal/issues/3039408#comment-13042402

Also, see:
https://www.drupal.org/project/drupal/issues/3040269#comment-13042506

Any idea how to fix this? Thanks.

**Comment by guardiola86** [comment]
The error disappears if I edit the file src/NodeVisitor/SandboxNodeVisitor.php and in the function wrapNode I add "if ($name == 0) return;" in the first line.
I'm not sure how the issue is caused and if it's specific to my case, but sometimes $name is empty.
@fabpot

**Comment by fabpot** [comment]
According to the issue upstream, everything should be ok now. Closing.
