### ISSUE TITLE
Length filter not working with iterators or traversables

### ISSUE THREAD

**Issue by dmolineus** [twigphp/Twig#2922]
The build in length filter works with objects implementing `ArrayIterator` but not with objects implmenting `Iterator` or `Traversable`.

https://github.com/twigphp/Twig/blob/7597a742b7a5d3d11f4568b0da64e0d94e46efe3/src/Extension/CoreExtension.php#L1243-L1245

Is there any reason for this limitation? I saw that the `loop.length` property was removed on purpose but when using `|length` filter is a different case. As `iterator_count` is used here, I propose also support  `Iterator` and `Traversable`.

**Comment by stof** [comment]
hmm, limiting it to IteratorAggregate is probably a mistake here, indeed.

**Comment by xabbuh** [comment]
IIRC the reasoning was that `iterator_count()` would not play well with iterators that are not rewindable.
