### ISSUE TITLE
Variable declared inside spaceless filter is unknown outside the filter

### ISSUE THREAD

**Issue by kevinpapst** [twigphp/Twig#2929]
Hi,

due to the recently introduced deprecation I changed all occurrences from `{% spaceless %}` to `{% filter spaceless %}` in my bundle, just to find out that this [introduced a bug](https://github.com/kevinpapst/AdminLTEBundle/issues/56). 

Before:
```
{% spaceless %}
{% set item = 'foo' %}
{% endspaceless %}
{{ dump(item) }}
```
results in `"foo"`

After the switch:
```
{% filter spaceless %}
{% set item = 'foo' %}
{% endfilter %}
{{ dump(item) }}
```
results in an Exception `Variable "item" does not exist.`.

I searched the docs whether this is intended behavior or not, but couldn't find anything.
Looking at the compiled source I see why that happens, everything between the filter tags becomes its own renderBlock function, while before it was inside the original block function... so I guess its by design. 

But: I think the information about changed scopes should be included in here: https://twig.symfony.com/doc/2.x/deprecated.html#tags
Is that worth a PR?

**Comment by stof** [comment]
@fabpot why is `filter` creating its own block ? That's a bad idea IMO.

**Comment by fabpot** [comment]
Changing the behavior is a BC break. So, not sure if we can do something.

**Comment by fabpot** [comment]
see #2977

**Comment by kevinpapst** [comment]
Thanks for that quick solution!
