### ISSUE TITLE
Suggestion: Optional argument for `template_from_string()` to give the template a meaningful name in error messages

### ISSUE THREAD

**Issue by ThomasLandauer** [twigphp/Twig#2930]
Right now, when `template_from_string()` goes wrong, you get an error message that reads something like that:

> Unexpected "}" in __string_template__676d06acde42f6beaa9fb80b493aba37df95ed9d96985370531d24150a908d8d at line 1

When using this function often in your project, it's hard to figure out *which* string-template is causing the problem.

So what I'm suggesting is an optional second argument to provide a "name" for the string-template:
```twig
{{ include(template_from_string("Hello {{ name }", 'foo')) }}
```
Which would then result in a better error message:
> Unexpected "}" in string_template 'foo' at line 1

**Comment by fabpot** [comment]
Great idea. Would you like to work on a PR for that (on 1.x ideally)?

**Comment by ThomasLandauer** [comment]
Um, I've never done that... ;-)

Please take a look and tell me what's next: https://github.com/twigphp/Twig/pull/2931
