### ISSUE TITLE
In operator with integers and strings gives unexpected results

### ISSUE THREAD

**Issue by Alienpruts** [twigphp/Twig#2938]
Hello, 

first and foremost, apologies if this has been mentioned before in the Issues, did a search, but could not find any Issue related to my problem.

Yesterday, I ran against a strange behavior problem in Twig : 

I am looping through an array which contain integer keys and possible string keys ('added' , 'removed', to be precise). When the loop encounters one of these keys, it should not execute the code it executes when the keys are numerical. That did not seem to work because of this : 

Code : 

```twig
{% if 0 in ['test','ezae','rere','zeaze','zeae','ezae','zeaez'] %}
```

This returns TRUE and executes the code in the IF block, which is unexpected, to my knowledge.

Another example:  

```twig
{% if 0 in ['1','2','3','4','5','6','7'] %}
```
This returns FALSE, as expected.

Is this expected behaviour or am I missing something?

**Comment by stof** [comment]
this is due to using PHP's comparison under the hood. Comparing an integer to a string is casting the string to a number, not the opposite. And in your first example, all strings are casting to `0`

**Comment by Alienpruts** [comment]
Ah, that explains it.

I thought indeed it was going to be the other way around  (integer being typecast to string to perform the comparison).

Tnx for the explanation, @stof .

**Comment by Alienpruts** [comment]
For the curious people among us, this will be addresses in PHP 8 :  

https://wiki.php.net/rfc/string_to_number_comparison

**Comment by stof** [comment]
The right message here is that it *might* be addressed in PHP 8. Nothing is sure about that yet, as that RFC has not been voted yet.
