### ISSUE TITLE
Infinite loop on exception re-throw

### ISSUE THREAD

**Issue by stormwulfren** [twigphp/Twig#2956]
This one has me stumped.
I'm using PHP 7.2 fpm with xdebug. Latest version of twig, standalone, imported with composer: "twig/twig": "^2.8"

Take for instance, a simple syntax error `{{ url] }}`. It should throw a SyntaxError Exception with the message, Unexpected token "]". It does. This is thrown in Lexer.php:334. 

The exception is caught in Environment.php:596, whereupon the source context is added to the exception object. The next line 598, the exception object is re-thrown. At this point, it hangs indefinitely. As far as I can tell, the throw itself is hanging, which is utterly bizarre to me.
More frustratingly, this happens for any sort of template error, making debugging incredibly tedious.

Out of curiosity, I tested exception re-throwing outside of twig to rule out my own code or an environmental issue and it appears to work fine. Anyone have any insight?

**Comment by fabpot** [comment]
I'm not able to reproduce. See https://twigfiddle.com/bspnjp

Can you create a small snippet that helps reproduce the error?
