### ISSUE TITLE
[3.0] Fatal error with Declaration of AbstractNodeVisitor::leaveNode

### ISSUE THREAD

**Issue by ghost** [twigphp/Twig#2987]
Fatal error: Declaration of Twig\NodeVisitor\AbstractNodeVisitor::leaveNode(Twig\Node\Node $node, Twig\Environment $env) must be compatible with Twig\NodeVisitor\NodeVisitorInterface::leaveNode(Twig\Node\Node $node, Twig\Environment $env): ?Twig\Node\Node in D:\Laragon.4.0.13\www\Twig\3\Twig\NodeVisitor\AbstractNodeVisitor.php on line 24

My Solution at this time:

NodeVisitorInterface.php
 /* public function leaveNode(Node $node, Environment $env): ?Node;
 */

Did we need the NodeVisitorinface ?

My Solustion works, the rendering goes on.

**Comment by xabbuh** [comment]
How does your setup look like when you run into this issue? Looking at the code in the `3.x` branch it seems to me that the signatures are identical.

**Comment by ghost** [comment]
With the last update of Twig 3.x, i havent´t the problem, but i think the problem comes from my Twig-Switcher. Now with my new Twig 1.x komatibilitie code it works.

I can switch between Twig 1.x, 2.x and 3.x easy with settings 1,2 or 3 at my programm. I need only to copy the src path of a distribution and rename it to Twig, that´s all.

Thanks for the nearly feedback!
