### ISSUE TITLE
Drupal 8.6.x is broken by 1.40.0

### ISSUE THREAD

**Issue by alexpott** [twigphp/Twig#2990]
The recent release of Twig has broken Drupal 8.6.x - the current release. The commit that broken it appears to be https://github.com/twigphp/Twig/commit/bf3781c9c1fc678110d5f4e5659d0d70c88ee774

We are tracking this issue on https://www.drupal.org/project/drupal/issues/3051269

The future branches of Drupal 8 are not affected because they already have work done to try to be more compatible with Twig 2.

**Comment by fabpot** [comment]
@alexpott Do you have any idea why this commit break Drupal? It should not and I don't see how this can break anything. Anyway, I will install Drupal to see if I can understand what's going on. I think it's time for me to add Drupal in Twig CI to avoid such breaks in the future. Do you know what would be the best way to do that?

**Comment by alexpott** [comment]
It's because we are expecting Twig to ignore us when we provide a NULL in the place of a node in the \Twig\Node\Node::__construct() ie something like... 

```
$nodes = [
  'options => NULL
];
new \Twig\Node\Node::__construct($nodes);
```

We've refactored the code in 8.7.x and up to not do this but that fix never made it back to 8.6.x because it was not a bugfix.

**Comment by fabpot** [comment]
Ok, I understand what's going on. Working on a fix now.

**Comment by fabpot** [comment]
Reverting the change and preparing new releases.

**Comment by alexpott** [comment]
@fabpot thanks! Unfortunately Drupal is not the simplest target to test against because installation requires a DB. You can do something like
```bash
$ composer create-project drupal-composer/drupal-project:8.x-dev twigbreak --no-interaction
$ # Some commands to swap it to use your twig instead of the one brought down by using composer create-project
$ cd twigbreak
# The command below will install drupal using sqlite and spin up the php development server to server the site.
$ php ./web/core/scripts/drupal quick-start demo_umami
```

**Comment by fabpot** [comment]
Instead of reverting, I propose to fix the regression in 1.x (as 2.x is not affected): https://github.com/twigphp/Twig/pull/2991/files

I've tested and that fixes the issue on Drupal. @alexpott Can you confirm that this is good on your side?

**Comment by fabpot** [comment]
@alexpott Regarding testing Drupal, is there is a way to have the exception details instead of "The website encountered an unexpected error. Please try again later." in the browser? I've hacked `FinalExceptionSubscriber` for now but if there is a setting for that, that would be even better.

**Comment by alexpott** [comment]
The installer will create a settings.php in web/sites/default - if you append `$config['system.logging']['error_level'] = 'verbose';` you'll get verbose logging.

**Comment by fabpot** [comment]
1.40.1 is released now.
