### ISSUE TITLE
Twig print's template source instead of render!

### ISSUE THREAD

**Issue by mehdico** [twigphp/Twig#2994]
i setup twig (version 2) like this :

```
$loader = new \Twig\Loader\FilesystemLoader($PANEL_ROOT_DIR . 'templates/');
$twig = new \Twig\Environment($loader, [
'cache'       => false,
'debug'       => true,
'auto_reload' => true,
]);
```

then run this :

```
echo $twig->render('login.html',[]);
```

and this is what i get in the browser :

![Screen Shot 1398-02-12 at 21 51 55](https://user-images.githubusercontent.com/1978735/57094037-b5ed7880-6d24-11e9-8a13-a9f53c980cf1.png)

**Comment by stof** [comment]
can you check what the HTTP response is, to see exactly what gets transmitted ?

**Comment by mehdico** [comment]
status code is 200
also my web is on http

![Screen Shot 1398-02-12 at 22 15 08](https://user-images.githubusercontent.com/1978735/57095335-d5d26b80-6d27-11e9-96a5-e4728ec0c94b.png)


![Screen Shot 1398-02-12 at 22 13 32](https://user-images.githubusercontent.com/1978735/57095224-94da5700-6d27-11e9-9f7d-cfbe8ed78e1f.png)

**Comment by stof** [comment]
but content-type is `application/json`. So the browser has no reason to try parsing that as HTML.

**Comment by stof** [comment]
this is not an issue in Twig, but in your php application using it.

**Comment by mehdico** [comment]
thank you dude. it's because of my stupidity.
