### ISSUE TITLE
Add support for ES6 string interpolation

### ISSUE THREAD

**Issue by hason** [twigphp/Twig#3000]
Twig adopts Ruby's style of string interpolation. It would be nice to support ES6 string interpolation:

```twig
{{ `foo ${bar} baz` }}
{{ `foo ${1 + 2} baz` }}
```

**Comment by fabpot** [comment]
I don't think this is worth it. We don't want to support two ways of doing the same thing and deprecating the current one would lead to unneeded effort for current users. As the format is "almost" the same, let's close as a "won't fix". Thanks for proposing.
