### ISSUE TITLE
 Twig 1-3: Deprecated: Unparenthesized

### ISSUE THREAD

**Issue by ghost** [twigphp/Twig#3003]
Deprecated: Unparenthesized comes with PHP 7.4-dev & 8.0.0-dev

File: Twig/Node/Node.php

At Twig 1-3:
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in D:\Laragon.4.0.13\www\Twig\1\Twig\Node\Node.php on line 43

At Twig 1:
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in D:\Laragon.4.0.13\www\Twig\1\Twig\Node\Node.php on line 199

Solution:

@trigger_error(sprintf('Using "%s" for the value of node "%s" of "%s" is deprecated since version 1.25 and will be removed in 2.0.', \is_object($node) ? \get_class($node) : (null === $node ? 'null' : \gettype($node)), $name, \get_class($this)), E_USER_DEPRECATED);

**Comment by fabpot** [comment]
Will be fixed by #3004

**Comment by ghost** [comment]
You forgot at Twig 1.x the correction on line 199!

**Comment by fabpot** [comment]
indeed, fixed in 44f02b22

**Comment by ghost** [comment]
Thanks for the quickly fix!
