### ISSUE TITLE
No exception thrown when having DateTime value without a date filter

### ISSUE THREAD

**Issue by NesCafe62** [twigphp/Twig#3028]
Hello! Great thanks for so awesome template engine. If someone forgot to add date filter when outputing a `DateTime` (or `DateTimeImmutable` or custom `DateTimeInterface`, `Carbon`, etc.) object in template, there will be no exception, and script execution will be terminated. It seems due to recusion. I browsed the sources to figure out, but not succeeded. Tested on 2.x-dev and 3.x-dev versions. And made a short test to reproduse the situation.
```
ini_set('display_errors', 1);
$loader = require(__DIR__ .'/vendor/autoload.php');

register_shutdown_function(function() {
	$error = error_get_last();
	if ($error && ($error['type'] & (E_ERROR | E_USER_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR | E_RECOVERABLE_ERROR))) {
		echo '<pre>'; var_dump($error); echo '</pre>';
	}
});

$twig = new \Twig\Environment(new \Twig\Loader\ArrayLoader([
    'index.html' => 'Hello {{ name }}! {{ date }}',
]));
try {
	var_dump(1);
	echo $twig->render('index.html', ['name' => 'Fabien', 'date' => new DateTime('now')]); echo "\n";
	var_dump(2);
} catch (Throwable $ex) {
	var_dump($ex);
}
```

**Comment by fabpot** [comment]
The error I get when running your script is "Object of class DateTime could not be converted to string", which is expected as you are trying to output a Date object. But I don't get your "It seems due to recursion". I don't see any recursion when running the script. Can you explain a bit more?

**Comment by NesCafe62** [comment]
Hmm, it is very strange. Because I have this on my remote development linux server (CentOS, php 7.2.14, twig 2.x-dev installed with composer) and also on local windows server (wamp, php 7.2.14, twig 2.x-dev also tried 3.x-dev, running from console). On remote I have `int(1)` in browser. On local running this php script from console gives me same `int(1)` and no errors. Tested again now on local (for php 7.1.26, 7.2.14 and 7.3.1), have same result. Maybe I can test this with TravisCI.

**Comment by NesCafe62** [comment]
If I add
```
$date = new DateTime('now');
echo $date.' sss';
```
inside try block, I have `Recoverable fatal error: Object of class DateTime could not be converted to string` of course.

**Comment by NesCafe62** [comment]
I can reverse-engineer this error, if you tell me in what file and line of Twig source code this error is happen.

**Comment by fabpot** [comment]
This error is expected. You need to convert the date to a string via the date filter for instance. Nothing we can do in Twig.

**Comment by NesCafe62** [comment]
I'm developing a framework and using twig as general template engine for now (plan add support for others in future). And I want to catch any errors that will occure during template rendering, if I or programmers from my team forgot to use date filter. It is not urgent thing, all is working well if we dont forget to use date filter. If you have "Object of class DateTime could not be converted to string" message I want to know in which line (maybe stacktrace) is it happen, to make it work for us too.

**Comment by stof** [comment]
this is PHP itself triggering this message, not Twig.

**Comment by NesCafe62** [comment]
Hmm, you mean it is occurring not on parsing or compiling stage but on execution? And there is now particular line in twig that is trying to concatenate DateTime with string. But I still not understand why there is no exception on both machines.. I will try on some other environments.

**Comment by stof** [comment]
maybe you don't have the same PHP configuration regarding error reporting

**Comment by fabpot** [comment]
Let's close here as the error is expected and there is nothing we can do on Twig's side.
