### ISSUE TITLE
The "defined" test only works with simple variables.

### ISSUE THREAD

**Issue by insaurabh** [twigphp/Twig#3029]
I am trying to trim the spaces from both sides of a variable in the craftcms template.

```
{{ dump(options.ulClass) }}
{# output 
	string(10) "pagination"
 #}
```

`{% set ulClass = (options.ulClass|trim) ?? '' %}`

Not sure its the best way but  this way it work,

```
{% set ulClass =  options.ulClass|trim %}
{% set ulClass = ulClass ?? '' %}
```

**Comment by stof** [comment]
Well, the defined test works for variable access. But here, you don't apply it on a variable access but on the output of a filter. So that's too late to handle undefined variable (the filter needs to have an input available).

**Comment by insaurabh** [comment]
> the filter needs to have an input available 

I am getting the values above the trim.

For filter you mean **|trim**

**Comment by stof** [comment]
I don't understand what you mean.

**Comment by insaurabh** [comment]
> So that's too late to handle undefined variable.

 How it's too late to handle ??
All the variable is defined.

**Comment by stof** [comment]
OK, then please describe exactly what your issue is.

**Comment by fabpot** [comment]
The `??` operator used the `defined` test under the hood. The defined test only works for simple constructs (like the PHP equivalent). So `options.ulClass ?? ''`, but `options.ulClass|trim ?? ''` cannot work as `trim` is a function call.

`(options.ulClass ?? '')|trim` would work though.
