### ISSUE TITLE
Live docs state feature is available in a version that does not exist

### ISSUE THREAD

**Issue by Bilge** [twigphp/Twig#3030]
The current [live docs](https://twig.symfony.com/doc/2.x/tags/macro.html#importing-macros) claim: _Auto-import is only available as of Twig 2.11_, but there is no such version `2.11`.

**Comment by BackEndTea** [comment]
2.11 is the next version that will be released. The docs just prepare for that.

**Comment by Bilge** [comment]
I would suggest the live docs should be in sync with the reality. If they
are out of sync it can be very misleading, creating the false expectation
that a feature is available when in reality it isn't.

**Comment by fabpot** [comment]
2.11 is out now.
