### ISSUE TITLE
Missing composer require for iconv extension

### ISSUE THREAD

**Issue by phoenix1337** [twigphp/Twig#3034]
https://github.com/twigphp/Twig/blob/2.x/src/Extension/CoreExtension.php#L412

Iconv is used in this file but it is not listed as a dependency in composer.json.

**Comment by nicolas-grekas** [comment]
Because it's not mandatory to use it, eg https://github.com/symfony/polyfill-iconv work fine too.

**Comment by phoenix1337** [comment]
The polyfill isn't listed as a requirement either.

**Comment by nicolas-grekas** [comment]
Neither are requirements. (and we cannot say "this or that" to composer.)

**Comment by phoenix1337** [comment]
Neither are 'polyfill-mbstring' and 'polyfill-ctype' but they are also added to composer.json.

Problem is that when you run a 'check-platform-reqs' and enable only the modules returned by composer, and there is no other package listing iconv or the polyfill as a requirement, you end up with a system that is not working properly.

**Comment by nicolas-grekas** [comment]
Oh, OK, sorry, I missed something: the iconv polyfill is a heavy one. We don't want to force ppl downloading it when the majority already has the extension.

**Comment by fabpot** [comment]
Let's close for reasons given by @nicolas-grekas. Even Symfony does not list `iconv` as a requirement.
