### ISSUE TITLE
Data Attributes breaks template

### ISSUE THREAD

**Issue by cpreston321** [twigphp/Twig#3036]
I am using [Glide.js](https://glidejs.com/docs/setup/) and my code looks like.

```
<div id="glide" class="wrapper">
        <div class="glide__track" data-glide-el="track">
            <ul class="glide__slides">
                ......
            </ul>
            <div class="glide__arrows" data-glide-el="controls">
                <button class="glide__arrow glide__arrow--left" data-glide-dir="<"></button>
                <button class="glide__arrow glide__arrow--right" data-glide-dir=">"></button>
            </div>
        </div>
    </div>
```

I figured out when you comment out `data-glide-dir="<"` or remove both then it works so it seems that breaks the template. Something to do when it renders it down.

**Comment by stof** [comment]
what do you mean by "it break templates" ?

**Comment by cpreston321** [comment]
@stof so when it renders it it looks like this when you have `data-glide-dir="<"` and `data-glide-dir=">"`

"Broken Html.."
![image](https://user-images.githubusercontent.com/6619884/58606709-a9e4d000-826a-11e9-904a-e9fdf2ccb7ba.png)

and without `data-glide-dir="<"` and `data-glide-dir=">"`

![image](https://user-images.githubusercontent.com/6619884/58606784-ec0e1180-826a-11e9-8547-1442aa87c11c.png)

it's like doing something werid I don't know. Seems like a compiling problem with twig its self

**Comment by stof** [comment]
I think this has nothing to do with Twig itself, but with missing escaping of the `<`  and `>` in your HTML (Twig won't automatically escape them for you if they are part of the template source rather than coming from variables being displayed).

**Comment by cpreston321** [comment]
@stof I've tried setting it as a variable and set nothing I can't find answers to how to fix it. You have a solution ?

**Comment by fabpot** [comment]
It looks like an HTML issue, not related to Twig. Closing.

**Comment by devusvulgaris** [comment]
Using html entities &lt; and &gt; instead of '<' and '>' would solve the issue with glide markup in twig.
