### ISSUE TITLE
Twig 1.x EOL? Twig 3.x Release?

### ISSUE THREAD

**Issue by krzysztof-pyrzyk-ah** [twigphp/Twig#3039]
Hi all,
I use Twig v1.x in one of my ongoing projects.
When should I expect an end of support for this version?
I can see that there's a branch for v3.x and I guess that you won't support 3 major versions of Twig at the same time, so release date of v3 will be more or less related to EOL of v1, am I right?
What's the expected date for releasing v3?

Thanks!

**Comment by ghost** [comment]
I think, that the Twig v1.x is still necessary, but we can set the minimum version from 1.12 to 1.38. The best solution could be the following:

Set the minimum version at Twig 1.50 to 1.38 and remove some obsolete interface definitions.

I have at my project following snip set for Twig 1.x compatibility and i don´t need the directory lib:


`// Twig 1 compatibility - Start
interface Twig_TemplateInterface{const ANY_CALL = 'any';const ARRAY_CALL = 'array';const METHOD_CALL = 'method';}
interface Twig_ParserInterface{}
interface Twig_CompilerInterface{}
interface Twig_LexerInterface{}
interface Twig_NodeInterface extends \Countable, \IteratorAggregate{}
class Twig_TokenParserBroker
{	protected $parser;
	protected $parsers = [];
	function addTokenParser($parser)
	{	$this->parsers[$parser->getTag()] = $parser;
	}
	function getTokenParser($tag)
	{	if (isset($this->parsers[$tag]))
		{	return $this->parsers[$tag];
		}
	}
	function setParser($parser)
	{	$this->parser = $parser;
		foreach ($this->parsers as $tokenParser)
		{	$tokenParser->setParser($parser);
		}
	}
}
// Twig 1 compatibility - End`

At my project can i switch between Twig 1.x, 2.x and 3.x and it works fine.

If we take this interface definitions away and dissolve the class Twig_TokenParserBroker, we have a new minimum set and don´t need the libs directory.

**Comment by fabpot** [comment]
Twig 1.x is not EOLed and there is no plan to end its support anytime soon. What could happen is that we don't add new features though.
