### ISSUE TITLE
Can a Twig template be evaluated in a parallel fashion?

### ISSUE THREAD

**Issue by PolyPik** [twigphp/Twig#3040]
I'm member of the twig.js repo and I'm looking to improve the performance of that port of Twig.

I just want to know if it is possible for the evaluation of a template AST to be parallelized using multiple threads or child processes.

I suspect it would be difficult due to tags like `set` which can change the context, and thus one would need to await the evaluation of that particular tag before starting new parallel evaluations lest subsequent evaluations yield incorrect results.

**Comment by fabpot** [comment]
I don't think this is possible for all templates as you already figured out.
