### ISSUE TITLE
Variable wrongly interpreted as operator when used as assignment of a for tag

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3041]
It is usually totally possible to use an operator as a variable, like in the following examples:

```
{{ matches }}
{% for match of matches %}
```

Although `matches` is a core operator, using `matches` as a variable name works.

There is one notable exception:

```
{% for matches of data %}
```

This template throws a `Only variables can be assigned to. Unexpected token "operator" of value "matches" ("name" expected).` error.

**Comment by fabpot** [comment]
see #3044

**Comment by ericmorand** [comment]
Amazing!!! Thanks.
