### ISSUE TITLE
BC break in 2.11 when importing macros inside an embed

### ISSUE THREAD

**Issue by pontus-mp** [twigphp/Twig#3045]
Imports are no longer in scope inside nested blocks within embeds.
Example: https://twigfiddle.com/fhfwr0
The block "inner" causes it to fail. The example works fine before Twig 2.11.

**Comment by fabpot** [comment]
It worked by chance (and was not documented).  Making it work with the new implementation is quite impossible. I've just tried.

You can either move the `import` call outside of the `block` call or duplicate the call in the "sub-"`block`.

**Comment by pontus-mp** [comment]
Alright, that's understandable. Would it be possible to catch this during linting instead?

**Comment by fabpot** [comment]
@pontus-mp That might be possible to catch this situation with the AST, but I don't think this is worth it. That would be (I think) quite a huge work.

**Comment by pontus-mp** [comment]
Okay, in that case the only thing I can think of is a line or two of documentation that this behavior no longer works. We assumed that imports were scoped in blocks similarly to "curly brace"-scopes in programming languages, so others might have done the same thing.

**Comment by fabpot** [comment]
see #3050
