### ISSUE TITLE
For + generator + filter does not work

### ISSUE THREAD

**Issue by lyrixx** [twigphp/Twig#3048]
As you can see on this [fiddle](https://twigfiddle.com/kj3jvs) this does not work as expected.

On the fiddle, we did not see the real error.
Actually, a notice is trigerred:

>[2019-06-03 16:10:07] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Object of class Generator could not be converted to int")." at /home/app/Resources/views/account/booking/_booking_list.html.twig line 75 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Object of class Generator could not be converted to int\"). at /home/app/Resources/views/account/booking/_booking_list.html.twig:75, PHPUnit\\Framework\\Error\\Notice(code: 8): Object of class Generator could not be converted to int

**Comment by fabpot** [comment]
You missing the parentheses around `x..y` -> https://twigfiddle.com/kj3jvs/2

**Comment by lyrixx** [comment]
Ahhh, Thanks.
