### ISSUE TITLE
2.11 error - Template cannot be used as a trait

### ISSUE THREAD

**Issue by acrobat** [twigphp/Twig#3051]
After upgrading to twig 2.11.1 (from 2.10.x) the code below throws an error, in previous versions it worked fine.

```twig
{% block datetime_widget %}
    {% use 'form_div_layout.html.twig' with datetime_widget as base_datetime_widget %}    
    <div class="form-group date-time-group">
        {{ block('base_datetime_widget') }}
    </div>
{% endblock %}
```

The error:
```
Template "form_div_layout.html.twig" cannot be used as a trait.
```

**Comment by fabpot** [comment]
Can you create a template that reproduce this issue (via https://twigfiddle.com/ if possible)?

**Comment by daum** [comment]
FYI I am getting this too after upgrading, this is coming from the symfony 4.2.9 bootstrap_4 form theme template (globally), specifically the base one causes the error.  Downgrading to 2.10.0 fixes the issue.  Working on making a reproducible example that I can make public.

@fabpot  one thing I did notice is if I load via a request to my application with no cache, it works fine and the isTraitable is true, but if going from CC it is showing as false.

Will report back when I have a way to reproduce, but most likely won't have time to look until later this week.

**Comment by fabpot** [comment]
I had the issue on one of my projects and upgrading to v2.11.1 and removing the cache did work.

**Comment by acrobat** [comment]
@fabpot manually removing the cache does indeed seem to work, strange that a cache-clear after composer update didn't resolve this issue

**Comment by acrobat** [comment]
@fabpot It seems that manually removing the cache or a `cache:clear --no-warmup` doens't trigger this error but a regular `cache:clear` will trigger it.

**Comment by fabpot** [comment]
#3051 should fix the problem. @acrobat Can you confirm?

**Comment by acrobat** [comment]
@fabpot #3054 seems to fix the issue! The exception is not throw after a regular `cache:clear`. Thanks!

**Comment by daum** [comment]
confirmed fixes here too.

**Comment by fabpot** [comment]
2.11.2 with the fix released

**Comment by lchhieu** [comment]
same error. How to fix this error?

**Comment by acrobat** [comment]
@lchhieu Updating twig to atleast 2.11.2 should fix this issue.
