### ISSUE TITLE
Blank screen when die() in an AbstractExtension

### ISSUE THREAD

**Issue by janhenckens** [twigphp/Twig#3058]
I have a package that wraps [larapack/dd](https://github.com/larapack/dd) in a Twig Extension and I'm having a problem on projects that are using Twig 2.11 (issue on my [repo](https://github.com/studioespresso/craft3-dumper/issues/10))

Larapack has a 'dump & die' method (`dd`) and using that results in a blank screen, no matter where in the template the extension gets called.

Further debugging reveals that it is not related to larapack/dd of my extension specifically, any extension with a `die()` or an `exit()` in it results in a blank screen. 

For reference, this is built as a  plugin for [craftcms/cms](http://github.com/craftcms/cms). 

This worked on 2.81, but yesterday's Craft update bumped Twig from 2.8.1 to 2.11, which is why the issue shows up now. 

Is this an intentional change and if so how can I make this work again? Thanks!

**Comment by fabpot** [comment]
This is indeed "expected" in recent versions of Twig. See #2995 for the PR and #1962 for the reason behind the change.

**Comment by lyrixx** [comment]
@fabpot I noticed that too. I did not take time to report this issue. Actually this make developing twig extension much harder (almost impossible).

I often do that (I just tested it with a fresh symfony 4.3 install):
```php
class FoobarExtension extends AbstractExtension
{
    public function getFilters(): array
    {
        return [
            new TwigFilter('foobar', [$this, 'foobar']),
        ];
    }

    public function foobar($value)
    {
        dump($value);die;
    }
}
```

Now it display a blank page.

Maybe, we can use the `$debug` flag to display or not a fatal error.

**Comment by fabpot** [comment]
@lyrixx That is an option indeed. In debug mode, don't flush the output. Would you like to work on a PR?

**Comment by lyrixx** [comment]
Let's go :)

**Comment by janhenckens** [comment]
Thanks for jumping in on this @lyrixx!
