### ISSUE TITLE
Symfony integration requires translation-contracts

### ISSUE THREAD

**Issue by nwittmaier** [twigphp/Twig#3060]
I'm a bit new to Symfony so there's a chance it's an issue with my implementation, but it appears that the Twig integration for Symfony 4 requires translation-contracts, but it wasn't included in the requirements by running composer require twig on a symfony/skeleton project. I was working through the Up and Running with Symfony 4 tutorial at this page https://www.youtube.com/watch?v=t5ZedKnWX9E and when I got to the part in video 3 about adding a form, it stopped working for me. Turns out that is tries to call TranslatorTrait, but translation-contracts wasn't required with the composer package. Once ran a composer require translation-contracts, it worked just fine.

**Comment by stof** [comment]
I think this should be reported to symfony, as this is more about TwigBundle than about Twig itself.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/31761 and linked issue.

**Comment by fabpot** [comment]
So,  problem solved in 4.3.1.

**Comment by nwittmaier** [comment]
OK. Cool. Thanks!
