### ISSUE TITLE
cannot traverse an already closed generator

### ISSUE THREAD

**Issue by ricohumme** [twigphp/Twig#3063]
This behavior occurs when applying the following:

1. Filter a collection in twig and store the Generator in a variable
2. Check the Generator having iterable content by applying the filter `length`
3. Iterate the Generator in a for loop in twig

In some cases there is nothing to iterate over, so by checking the size of the Generator and seeing there is something to iterate over, I render some content previous to the for loop and then iterate the Generator.

However, the Generator is being closed after applying the filter `length`, rendering the Generator useless after that.

Example:
```
    {% set collection = ['property1', 'property2'] %}
    {% set generator = collection|filter(v => v is same as('property1')) %}
    {% if generator|length > 0 %}
        {% for item in generator %}
            {{ item }}
        {% endfor %}
    {% endif %}
```

Is this intent?

**Comment by stof** [comment]
well, computing the length of an iterator requires iterating over it.
So using a generator for the implementation of the `filter` filter indeed looks like a bad idea.
/cc @fabpot

**Comment by fabpot** [comment]
fixed in #3065

**Comment by ricohumme** [comment]
Thnx @fabpot

**Comment by benbor** [comment]
Hi! @stof  
Displaying  a stub for empty collection is a very common task. 

Do you have some ideas,  how to check is Generator are not empty in the twig? 

```twig
{% if generator %}  {# <----- `is not empty` ? #}
        {% for item in generator %}
            {{ item }}
        {% endfor %}
{% else %}
        <div> The collection is empty</div> 
{% endif %}
```

**Comment by stof** [comment]
@benbor checking whether a generator is not empty is not doable **in PHP** without consuming it. So there is no way to do it in Twig either.

**Comment by ricohumme** [comment]
Hi @benbor 
Maybe this will put you in the right direction?
https://twig.symfony.com/doc/3.x/tags/for.html#the-else-clause

**Comment by stof** [comment]
for that particular example, the `else` clause is indeed a solution that avoids checking separately whether the generator is empty (but it does not work if your `if` contains more stuff than the loop)

**Comment by benbor** [comment]
@ricohumme  @stof  thanks. It's exactly what I was looking for!
