### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Warning: file_get_contents(/home/file/html/public//uploads/pic/bouquet.svg): failed to open stream: No such file or directory").

### ISSUE THREAD

**Issue by rescobarca** [twigphp/Twig#3067]
I'm getting Twig_Error_Runtime error with twig 2.4.6.
  
Apparently this issue was resolved on the new update, as said in this thread 
https://github.com/twigphp/Twig/issues/2643?fbclid=IwAR2R_XwU3U_8ImY-vfYTWp8gYhOSX2ZyTuObSOINC1hnZAsle5y6l0Dk6_8
  
It seems the svg icon is there so I'm not sure why it's giving me an error.
  
But it may be a different bug. Would anyone know how I can fix this? I'm new to symfony and coding in general so I apologize for my naivety.

**Comment by fabpot** [comment]
As said in the error message, it looks like the `/home/file/html/public//uploads/pic/bouquet.svg`does not exist. Next time, please, use stackoverflow for support.
