### ISSUE TITLE
Twig website is broken when visiting from search result

### ISSUE THREAD

**Issue by logarytm** [twigphp/Twig#3068]
When searching for Twig in Google, the first result points to `/index.html`, which is now broken. (Sorry for the screenshots, I only have my phone at the moment.)

![Screenshot_20190619-122947](https://user-images.githubusercontent.com/2938672/59758331-f893f180-928d-11e9-8040-ab0698bf8d5f.png)

![Screenshot_20190619-123131](https://user-images.githubusercontent.com/2938672/59758442-398c0600-928e-11e9-9272-909e8c2ddccd.png)

**Comment by fabpot** [comment]
I cannot reproduce. What keywords do you have in your search?

**Comment by logarytm** [comment]
Just "twig php". But it does not necessarily require searching, just try to go to https://twig.symfony.com/index.html.

**Comment by fabpot** [comment]
Yeah, the `index.html` page does not exist, that's not an issue if nobody links to that page.
Just tried again with `twig php` on a private tab, and I don't seem to be able to get a link to that page.

**Comment by lyrixx** [comment]
I can not reproduce too (private an not private) :/

**Comment by fabpot** [comment]
Let's close. The `index.html` page does not exist anyway, I suppose Google will remove it at some point.
