### ISSUE TITLE
Probably wrong behaviour in split-function

### ISSUE THREAD

**Issue by adriansuter** [twigphp/Twig#3072]
Hi there

If the delimiter is the string `"0"`, then the `split` function might not work as expected.
```twig
{% set foo = "hello0world"|split('0') %}
```
We get an array of chars, but shouldn't `foo` be an array of two items only?

## Proposition

Maybe we should change the line
https://github.com/twigphp/Twig/blob/fb5a1f43e653ba4af08333e8ba3f6330b1017d34/src/Extension/CoreExtension.php#L781
into
```php
    if (strlen($delimiter)) {
```

What do you mean?

**Comment by stof** [comment]
indeed, this looks wrong.

**Comment by fabpot** [comment]
That's why `empty` should **never** be used in PHP.

@adriansuter Can you submit a PR to fix this bug (adding your example as a test case)? Thank you.

**Comment by adriansuter** [comment]
Of course.
