### ISSUE TITLE
Unclosed verbatim tag is lexically incorrect while other unclosed tags are valid 

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3073]
When lexing a Twig template, unclosed tags are considered as valid:

`{% foo %}`

Is tokenized to:

```
BLOCK_START_TYPE()
NAME_TYPE(foo)
BLOCK_END_TYPE()
EOF_TYPE()
```

Except the verbatim tag that can't be left unclosed:

`{% verbatim %}`

> PHP Fatal error:  Uncaught Twig\Error\SyntaxError: Unexpected end of file: Unclosed "verbatim" block in "index" at line 1.

Why is the verbatim tag treated differently? There is nothing in the documentation that distinguish the `verbatim` tag from the others lexically wise:

https://twig.symfony.com/doc/2.x/tags/index.html

**Comment by jvasseur** [comment]
This is probably because the verbatim tag modify the behavior of the lexer (since everything inside has to be treated as pain text instead of interpreted as twig code) so the verbatim tag is handled at the lexer level while other tags are handled latter.

**Comment by stof** [comment]
The verbatim tag is a lexer-level feature, because it disables lexing inside itself.

Other tags are parser-level features. So they would be considered valid or no by the parser, not by the lexer (and whether they need a corresponding closing tag is up to each tag parser).

**Comment by ericmorand** [comment]
Makes sense. I guess this is needed because there is no enforcement on what a closing tag looks like relatively to its opening relative - `{% if %}{% fi %}` is perfectly acceptable in the current state of the language.

**Comment by stof** [comment]
and some tags don't have a closing tag at all (look at `{% extends %}` for instance)

**Comment by ericmorand** [comment]
Good point. It's perfectly rational that the lexer doesn't expect a closing tag. Thanks for your time.
