### ISSUE TITLE
Twig_Error_Runtime: An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by jchah090** [twigphp/Twig#3079]
Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Entity of type 'MDDb\Models\Medium' for IDs id(1) was not found") in "Releases/_table.twig" at line 32.
								in /usr/share/mddb/releases/20180715235450/vendor/twig/twig/lib/Twig/Template.php on line 447

**Comment by stof** [comment]
This is not a error coming from Twig. This is an error coming from what you do in your `Releases/_table.twig` template at line 32
