### ISSUE TITLE
Feature Request: Metadata Support

### ISSUE THREAD

**Issue by markhalliwell** [twigphp/Twig#3082]
I'm aware that something like this has been requested before: #2440.

I don't think that issue really gave solid reasoning behind _why_ this is needed though.

Templates can be quite complex, especially in a CMS like environment where there can literally be hundreds, if not thousands, of templates when all is said and done (especially when a site-specific sub-theme is involved).

### Use Case 1 (UI: Flags/Layout/Relationships)

Recently the need for metadata in templates came up in Drupal core:
https://www.drupal.org/project/drupal/issues/2920309

It was solved by using PHP's [get_meta_tags()](https://www.php.net/manual/en/function.get-meta-tags.php):

```html
<meta name="help_topic:label" content="Changing basic site settings"/>
<meta name="help_topic:top_level"/>
<meta name="help_topic:related" content="user.security_account_settings"/>
```

This, of course, means that these tags can thus be rendered as part of the template (Drupal core currently subverts this by stripping them during the XSS filtering phase, but I digress).

I [discovered that these tags could be wrapped](http://ideone.com/hfOcQO) with Twig comments and still be able to be parsed using `get_meta_tags()` easily enough:

```twig
{#
  <meta name="help_topic:label" content="Changing basic site settings"/>
  <meta name="help_topic:top_level"/>
  <meta name="help_topic:related" content="user.security_account_settings"/>
#}
```

It was [brought up](https://www.drupal.org/project/drupal/issues/3064854) that this mixes two existing syntaxes and, because the wrapper is a comment, prevents an IDE from syntax checking the internal markup (which could lead to ignored metadata and general pain of tracking it down).

> maybe we should propose an upstream change to support template metadata like this is Twig in some completely better way.

So I'm creating this issue in response to that if only to start a proper discussion around this and gain a better idea about what "some completely better way" may actually be.

I've thought about this a bit and feel that this could be implemented like the following (using the possible `{@` solution from below):

```twig
{@ help_topic = {
  top_level: true,
  label: "Changing basic site settings"|t,
  related: "user.security_account_settings"
} @}
```

### Use Case 2 (Versioning)

https://www.drupal.org/project/bootstrap/issues/2547363

When dealing with an external front-end framework, like Bootstrap, templates can be added or changed between subsequent newer versions.

For a base theme like [Drupal Bootstrap](https://www.drupal.org/project/bootstrap), knowing the version the template is actually quite important.

I've attempted to use arbitrary file naming schemes in the past but severely limited in what is actually possible (e.g. no complex constraints like `>= 3.0.0 <3.4.0`).

I've also attempted to use, in conjunction with arbitrary file names, an internal PHP map that has these constraints. This creates a constant disassociation between the template and the mapped constraints; often missing or forgetting to update one or the other.

Being able to package some sort of metadata with the template itself would be greatly beneficial, if only from a management standpoint:

```twig
{@ bootstrap = { version: ">= 3.0.0 <3.4.0" } @}
```

### Possible Solution (`{@`)

At first, I proceeded down the existing syntax route using comments `{#` as I mentioned in the Drupal.org issue (similar to #2440).

Another issue with this approach, however, is that a template could have multiple comment blocks and may not intend to use any of them as metadata; thus causing a BC break as was stated in #2440.

Instead, I believe a new opening/closing symbol could easily be introduced to denote "metadata". This new tag should only be allowed once at the beginning of a template.

I chose `{@` as it's the one symbol that I didn't feel was widely used in any sort of "syntax" like manner:

```twig
{@ property = "value" @}
```

More complex/nested metadata can just use additional objects:

```twig
{@ property = {
  nested: "value"
} @}
```

```twig
{@
  property = {
    nested: "value"
  },
  another = {
    sibling: "value"
  }
@}
```

I considered other symbols, but many already have uses in Twig or mathematics and would likely just confuse matters:

`{! property = "value" !}` (used to negate conditions)
`{- property = "value" -}` (used to manage whitespace, used to subtract)
`{~ property = "value" ~}` (used to concatonate strings)
`{* property = "value" *}` (used to multiply)
`{+ property = "value" +}` (used to add)

### Why does this need to be in Twig?

Primarily: performance and standarization.

#2440 mentioned that this kind of functionality could be easily added by 3rd party extensions.

I don't believe this is true though. An extension doesn't address the performance of actually having to parse an entire template (which can be quite expensive especially when attempting to build a registry of templates).

Retrieving metadata shouldn't require passing context (variables) to the template. The need to extract this information is purely a one-way prospect: to provide metadata information about said template, not the entire template itself. Once the metadata has been extracted from the template, it shouldn't need to continue any further.

Thus, a need for some sort of `parseMetadata` method, separate from normal parsing, will be needed.

Then there's the matter of adding a new `{@` lexical syntax. This will require Twig to actually be modified to support this kind of functionality as this kind of modification isn't something that is extensible.

This will also allow a standardized way of providing metadata rather than relying on some arbitrary custom/3rd party implementations that can impact performance.

---

The main reason I bring this up again is that I feel that this needs more discussion rather than a simple dismissal.

The need for injecting metadata into Twig templates is real.

I know I probably didn't get every technical aspect exactly right or perhaps I didn't expand on something that needed to be; I am attempting to be as concise as possible about what the issue is.

There are likely to be bugs with my approach as well, this is just a rough draft idea; hence the need for discussion 😄

**Comment by andypost** [comment]
Probably `parseMetadata($context)` could allow using filters inside of proposed metadata section

**Comment by stof** [comment]
All the solution you propose involve adding a new reserved syntax, which is a BC break (they can currently be used to render this output). So this is not possible.



> Then there's the matter of adding a new `{@` lexical syntax. This will require Twig to actually be modified to support this kind of functionality as this kind of modification isn't something that is extensible.

Third-party extension can add a `{% metadata %}` tag to define them. And this would probably also be the only way the core could be adding that feature in a BC way anyway.
But then, this does not allow parsing only metadata

> Retrieving metadata shouldn't require passing context (variables) to the template. The need to extract this information is purely a one-way prospect: to provide metadata information about said template, not the entire template itself. Once the metadata has been extracted from the template, it shouldn't need to continue any further.

I don't see how the syntax you propose could avoid parsing the template though (unless it gets restricted to being the very first thing in the template, in which case it could maybe stop the parsing after it).

Anyway, what #2440 mentioned is that front matter are generally implemented around a given syntax, not inside it. So you could have a special Twig loader which would strip the front matter from the template source during loading (and inject a `{% line %}` tag to get the original line numbers in the error messages) so that the Twig parser never sees it. And then, you could have a metadata loader which resolves the template the same way, but then reads the front matter. And this does not need to be in Twig core.

**Comment by fabpot** [comment]
I agree with @stof reasoning. I still don't think that this belongs to Twig and there are ways to implement that outside of core.

**Comment by markhalliwell** [comment]
Well, that certainly wasn't given much thought I hoped it would.

I guess I should at least thank you for saying anything at all.

😞 

---

> All the solution you propose involve adding a new reserved syntax, which is a BC break (they can currently be used to render this output). So this is not possible.

So bump a major... isn't that what semver is for? I don't understand why it seems like just the possibility of a "BC break" somehow warrants an immediate dismissal of any idea.

> Third-party extension can add a `{% metadata %}` tag to define them.

No, that would require the template to be rendered, which requires context (variables) to be passed. In a template registry scenario, the context isn't known because it's not attempting to render the templates. It's only attempting to gain additional metadata from them, that's all.

> I don't see how the syntax you propose could avoid parsing the template though (unless it gets restricted to being the very first thing in the template, in which case it could maybe stop the parsing after it).

Yes... which is why I said this needs a separate parsing method that stops after it detected/parsed the metadata.

> I still don't think that this belongs to Twig and there are ways to implement that outside of core.

Sure, if you subclass almost every aspect of Twig just to add this type of functionality.

That wasn't and still isn't the point.

The point I was trying to make is that there is a need for this and it would be better and easier if this was something that Twig could support out of the box rather than having to hack it in afterward.

Nevermind the performance impact of supplementing this kind of added functionality as merely an afterthought or the lack of any standardization in the community of how to provide proper metadata for a template.

I was attempting to avoid fragmenting the community on this topic.

At the very least, providing a way to do a partial parse (even if you don't want to add the `{@` metadata logic) would go a long way towards supporting this kind of external functionality you are so eager to dismiss. That certainly wouldn't create any "BC breaking issues" now would it.

I was hoping to create ideas, discuss possibilities, and come to some sort of consensus on what a "better way" would actually look like; rather than being given a basic line as "this can be done elsewhere" and ultimately given the boot all within 24hrs. Sad.

**Comment by stof** [comment]
Well, the thing is, the *only* use case we ever got for associating metadata to a template is from Drupal, for which we already suggested ways to do that (either with a tag in the template, or with a front matter stripped by the loader).
We haven't seen the benefits of adding that in Twig core (and having to maintain the feature for that), and even less when that would involve breaking BC (BC breaks have a cost for the whole community).

**Comment by markhalliwell** [comment]
Again, it's not about whether we can do it locally or not. This was primarily about performance and standardization. Not sure why I have to keep repeating that.

**Comment by markhalliwell** [comment]
Create #3141 instead, since this issue was about actually adding metadata support... which seems this project is unwilling to do.
