### ISSUE TITLE
Can macros be used in arrow functions?

### ISSUE THREAD

**Issue by gmhenderson** [twigphp/Twig#3083]
Twig v2.11.2. I would like to be able to use macros inside of the new arrow functions made possible with the `map` and `filter` filters. Based on the documentation, I would expect the following to work. This is a contrived example but illustrates the issue:

In file `macros.twig`:

```twig
{% macro makeLower(string) %}
  {{ string|lower }}
{% endmacro %}
```

In file `myTemplate.twig`:

```twig
{% from 'macros' import makeLower %}
{% set myArray = ['ONE', 'TWO'] %}
{% set lowercased = myArray|map(val => makeLower(val)) %}
```

Result:

```
Undefined variable: macros
```

In the compiled output, the arrow function becomes:

```php
$macros = $this->macros;

// ...

function ($__val__) use ($context) { 
    $context["val"] = $__val__;
    return twig_call_macro(
        $macros["__internal_42b310282a3e29c585e477b29e2f22e7a6845cb80a0e9c92fac2e7e09afe84a3"],
        ...
};
```
`$macros` is defined outside the closure but not included with `use`. Is this expected? Is there any way to make my example work?

**Comment by fabpot** [comment]
See #3084 for a fix.
