### ISSUE TITLE
RuntimeError: Macro alias variable does not exists

### ISSUE THREAD

**Issue by aaronadal** [twigphp/Twig#3088]
I am experiencing an error and I don't know if it is a bug or not. I have this function in a TwigExtension:

```php
public function dynamicMacro($macro, $method, $args)
{
    $method = "macro_$method";
    return $macro->$method(...$args);
}
```

This function takes a reference to a Twig macro alias, a method and the args of the method and calls it programatically:

```twig
{% import '@App/macro/input.macro.twig' as mInput %}

{{ dynamicMacro(mInput, field[1], field[2:]) }}
```

I just updated Twig from v2.7.4 to v2.11.3 and now this doesn't work. It raises an error with the following message: "Variable "mInput" does not exist."

Is there something broken?

**Comment by fabpot** [comment]
Passing macros as argument is not supported and should be considered as an implementation detail.

**Comment by aaronadal** [comment]
Oh, bad news... And is there any alternative or workaround to achieve the behaviour of the code above? If not, I'm afraid my code will get stuck in v2.7.4.

**Comment by fabpot** [comment]
@aaronadal You can probably have a look at the new implementation and see how you can make it work, but we won't support it.
