### ISSUE TITLE
Add filter for generation of valid HTML id attributes from strings

### ISSUE THREAD

**Issue by polarbirke** [twigphp/Twig#3089]
I need to generate anchor link ids from strings in my project, e. g. create an ID from  "Basic API Usage" for URLs like https://twig.symfony.com/doc/2.x/intro.html#basic-api-usage.

Ideally, the filter would create strings that adhere to the requirements outlined here: https://www.w3.org/TR/html401/types.html#type-name. I prefer using HTML 4.01 over the laxer requirements of HTML 5.1 for BC reasons.

The usage might looks as follows (`htmlid` being the new filter):

```twig
<h1 id="{{ page.title|htmlid }}">{{ page.title }}</h1>
```

I can of course implement this with a custom Twig Extension, but I believe the use case is common enough that more people might benefit from this.

What do you think?

**Comment by stof** [comment]
I don't think this belongs to Twig core. A complete implementation probably needs to be stateful to avoid generating duplicate ids, and stateful filters are avoided in core (because the core would then have to be responsible for managing this state properly too).

**Comment by stof** [comment]
Btw, a proper implementation which can also work when generating URLs to these ids is even more complex, as the handling of duplicate ids per page needs to remember the ids which would be generated on the *other* page too. That would be a pain to implement in a Twig extension, as it won't know about the rendering on the other size. This looks more like a tool for the page generation system (which can have knowledge about the ids generated on the other pages).

**Comment by mpdude** [comment]
@stof Not sure if you’re reading too much into this... Yes, if you want to integrate it with routing and stuff, your points are all valid.

On the other hand, if it’s just about generating `@id`s, it’s not much different from a filter like `|title`. Most pages (think of the Symfony docs) come with IDs for the main elements like headlines to make referencing easier.

**Comment by stof** [comment]
you still need to avoid generating duplicate ids, as that would make the DOM invalid (and would prevent referencing the right headline).
And if it gets added to the core, some other users will expect to be able to use it when generating a link to the page too. I guarantee you that if this gets added to the core, the assumption `if it’s just about generating ids` will not be a good assumption in the long run.
This is easy enough to implement as an external extension (at which point you can decide to make it supporting only generating ids but not links, and users might choose a different extension if it does not suit their need).

**Comment by olets** [comment]
> I believe the use case is common enough that more people might benefit from this.

In my experience, HTML 4 support is a very niche need these days. For everyone else something like `|lower|replace({' ': '-'})|url_encode` (or that with `~ random()` if you anticipate similar input strings) should do the trick, because in HTML 5 the only restriction is no spaces ([spec link](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute)).

Out of curiosity, what browsers are giving you trouble, and what trouble exactly? I don't have an IE<10 setup handy for experimentation.

**Comment by polarbirke** [comment]
> Out of curiosity, what browsers are giving you trouble, and what trouble exactly? I don't have an IE<10 setup handy for experimentation.

Hey @olets, my BC reference was not targeted at Browsers but legacy implementations. We have a few long-running (up to ~17yrs) customer projects in production that harness _really_ old practices and stacks to churn out HTML 4.01 or even XHTML 1.0 😱 for either the whole website or just parts of it. I wanted a filter that doesn't produce invalid IDs when I use it in those projects (yes, there's Sf and Twig in there, we built a few bridges…).

**Comment by polarbirke** [comment]
Closing as per @stof's accepted concerns.

**Comment by olets** [comment]
Got it, makes sense. What are BC and Sf?

**Comment by olets** [comment]
Know your closed the issue 👍.. so, independent of the closed feature request, I wonder if `random('abcdefghijklmnopqrstuvwxyz') ~ random()` would do it

**Comment by stof** [comment]
@olets Sf is probably Symfony, I would say.

**Comment by polarbirke** [comment]
> Got it, makes sense. What are BC and Sf?

Apologies, I entered lousy acronym mode. I used "BC" to mean "backwards compatibility" in this context and abbreviated "Symfony" to "Sf".

> Know your closed the issue 👍.. so, independent of the closed feature request, I wonder if `random('abcdefghijklmnopqrstuvwxyz') ~ random()` would do it

I'm not familiar with using `random()` for this. Here's what we did for a German website (so the focus is on a-z plus German umlauts like ä, ö, ü, etc.:

```
    public function getHtmlId(string $string): string
    {
        $string = preg_replace('~[^\\pL0-9]+~u', '-', $string);
        $string = trim($string, '-');
        $string = mb_strtolower($string, 'utf-8');
        $string = str_replace(['ä', 'ö', 'ü', 'ss', ' '], ['ae', 'oe', 'ue', 'ss', '-'], $string);
        $string = iconv('utf-8', 'us-ascii//TRANSLIT//IGNORE', $string);
        $string = preg_replace('~[^-a-z0-9_]+~', '', $string);
        $string = preg_replace('(\-+)', '-', $string);
        $string = trim($string, '-');
        return $string;
    }
```

**Comment by Chi-teck** [comment]
Drupal 8 offers `clean_id` filter based on the following code.
https://git.drupalcode.org/project/drupal/blob/8.8.1/core/lib/Drupal/Component/Utility/Html.php#L204

**Comment by sebastiankugler** [comment]
> Know your closed the issue 👍.. so, independent of the closed feature request, I wonder if `random('abcdefghijklmnopqrstuvwxyz') ~ random()` would do it

If this is meant as "generating a random id", this has the downside of the ids being different each time the page is rendered, so you would loose the possibility to share URLs that link to this id.
