### ISSUE TITLE
Twig not working in default configuration

### ISSUE THREAD

**Issue by jonaskohl** [twigphp/Twig#3092]
I installed Twig into an empty project using composer.
I then used the following code from the examples:

```php
<?php
require_once './vendor/autoload.php';

$loader = new \Twig\Loader\FilesystemLoader('./templates');
$twig = new \Twig\Environment($loader, []);

echo $twig->render('index.html', [
  "foo" => "bar"
]);
```

But I get the following exception:

```
Fatal error: Uncaught Error: Class 'Twig\Loader\FilesystemLoader' not found in C:\path\to\my\project\index.php:8 Stack trace: #0 {main} thrown in C:\path\to\my\project\guideshout\index.php on line 5
```

Why does this happen in a blank, empty project right after installing.

**Comment by xabbuh** [comment]
Which version of Twig did you install (i.e. what is the output of `composer show`)?

**Comment by jonaskohl** [comment]
I used [this guide](https://twig.symfony.com/doc/2.x/intro.html#installation). The command I used was `composer require "twig/twig:^2.0"`.

The output of `composer show` is
```
symfony/polyfill-mbstring v1.11.0 Symfony polyfill for the Mbstring extension
twig/twig                 v2.0.0  Twig, the flexible, fast, and secure template language for PHP
```

**Comment by xabbuh** [comment]
I wonder why you ended up with 2.0.0 being installed. Can you show the whole content of your `composer.json` file?

**Comment by jonaskohl** [comment]
```json
{
    "require": {
        "twig/twig": "2.0"
    }
}
```

**Comment by Tobion** [comment]
You are requiring 2.0. You want to require something like `^2.0` to get more recent versions.

**Comment by stof** [comment]
be careful. On windows, `^` is a custom char in the terminal, and so it requires some escaping.

**Comment by jonaskohl** [comment]
@stof That's what I suspected. Although I used PowerShell and not the standard command line. I'll try and update Twig to the latest version now and see if this solves the problem.

Also, maybe add a heads up to the docs so Windows users are aware of the caret being a reserved character?

**Comment by stof** [comment]
AFAICT, it is also a special char in Powershell.

**Comment by jonaskohl** [comment]
Okay, I now updated Twig using the command `composer require "twig/twig:^2.0"` again, but this time, I used **`cmd.exe` instead of Powershell!**. The caret should automatically be escaped because it is inside a double quoted string. Powershell does not seem to handle that as gracefully as cmd does.

**Comment by toxpal** [comment]
Being a developer, I also received exactly the same complain from 2 clients.

In my situation, Twig (always the latest version of 1.x branch) is manually bundled with script for years. That is to say, Composer isn't used, I download Twig libraries and bundle them with script. Works great. Except for some users who try to install script on localhost running Windows. They have the same error:

`Fatal error: Uncaught Error: Class 'Twig_Environment' not found in C:\server_dir\www\file.php:999 Stack trace: #0 {main} thrown in C:\server_dir\www\file.php on line 999`

Line 999 is not actual line, I just added some some random number in example. As soon as user moves the same script to Linux, it starts working. Some users also run it with great success on Windows servers, so I guess it's related to server setup. But the fact is that problem exists on some Windows servers.

If someone wants a test script for debugging, I'll be happy to send.

**Comment by fabpot** [comment]
@jonaskohl I think the best we can do is to add a warning in the documentation. Can you propose a change via a pull request?
