### ISSUE TITLE
Unfortunate naming of twig "Tests"

### ISSUE THREAD

**Issue by linaori** [twigphp/Twig#3093]
The naming of [Tests](https://twig.symfony.com/doc/2.x/advanced.html#id5) has bothered me for quite some time now. The name is ambiguous and it's really hard to find what it is and how to use it by using a search engine.

The feature itself is really powerful and useful and I've implemented it a couple of times to hide implementation details that don't belong in twig templates, and due to the name, finding out how this works took longer than required.

I'm not sure what to call it otherwise, though I wanted to raise the issue to increase discoverability for this awesome feature.

**Comment by fabpot** [comment]
@linaori Thanks for the report. I agree with you that Tests is confusing, but I have a hard time finding a better name. Also, changing this name now would be a massive BC break (we can of course provide a migration path but the new name would need to be 10 times better IMHO).

Anyone with a better name?

**Comment by Pierstoval** [comment]
Assertions?

**Comment by sstok** [comment]
Assertions will usually result in an exception/error.

boolean operator/condition, criterion? 
check or trailing? (not really similar).

evaluation? might be bit confusing with eval 😄 

https://www.thesaurus.com/browse/test
https://www.wordhippo.com/what-is/another-word-for/test.html

**Comment by fabpot** [comment]
Let's close. I think I won't have the energy to deprecate the current naming, update the docs, release a new major, ...
