### ISSUE TITLE
Twig - evaluating array length and compare

### ISSUE THREAD

**Issue by gavinkalika** [twigphp/Twig#3095]
php code:

$userList = [0,1,2];
$pageSize = 3;

twig code:
{% set isPaginatable = (userList|length) >= pageSize %}
{% dump(isPaginatable) %}

result:
isPaginatable  is false

expected:
isPaginatable  is true

**Comment by apfelbox** [comment]
Can't reproduce: https://twigfiddle.com/pvo99r
