### ISSUE TITLE
[Docs] range operator appears twice in precedence list

### ISSUE THREAD

**Issue by danburzo** [twigphp/Twig#3099]
In the [box about operator precedence](https://twig.symfony.com/doc/2.x/templates.html#twig-expressions), the `..` operator appears twice. I am assuming the first appearance is the correct one?

**Comment by fabpot** [comment]
It's not listed twice. The second time, the operator is `.` and then there is the final dot of the sentence :) I'm going to see how to avoid the confusion.

**Comment by danburzo** [comment]
Ah, makes total sense now 😅 Thanks!
