### ISSUE TITLE
`is empty` and `is not empty` doesn't work with `CallbackFilterIterator` on Doctrine's `PersistentCollection`

### ISSUE THREAD

**Issue by keichinger** [twigphp/Twig#3101]
I was implementing a template a backend for one of our entities and I wanted to use the new `|filter(…)` filter.

### Prerequisites

A small example entity

```php
/**
 * @ORM\Entity()
 * @ORM\Table(name="foos")
 */
class Foo
{
	/**
     * @var CareerTeaserBlockEntry[]|Collection
     * @ORM\OneToMany(targetEntity="Bar", mappedBy="foo")
     * @ORM\OrderBy({"sortOrder"= "ASC"})
     */
    private $bars;

    public function __construct ()
    {
        $this->bars = new ArrayCollection();
    }

    /**
     * @return CareerTeaserBlockEntry[]|Collection
     */
    public function getLinkEntries () : Collection
    {
        return $this->bars;
    }
}


class BarController extends AbstractController
{
    /**
	 * Use the default ParamConverter to fetch `Foo` from an URL placeholder.
	 *
     * @param Foo $foo
     *
     * @return Response
     */
	public function list (Foo $foo) : Response
	{
		return $this->render("admin/bar/list.html.twig", [
			"foo" => $foo,
		]);
	}
}
```

And in our template, I was using something along the lines:

```twig
{%- set filteredBars = foo.bars|filter(bar => bar.something == "else") -%}
{%- set barsCount = filteredBars|length -%}
// …
{% if filteredBars is not empty %}
	// …
{% else %}
	// …
{% endif %}
```

Since I was testing all cases, I noticed that the `else`-case was never being displayed. So I was quickly dumping `barsCount` and `filteredBars` and noticed, that `filteredBars` is of type `CallbackFilterIterator`. Quickly inverting the if-statement from `is not empty` to an `is empty` was also changing the output.

Before I was submitting this issue, I was trying to reduce the reproducible to a minimum using the following code:

```twig
{% set arr = [1,2,3,4,5] %}
{% set filteredArr = arr|filter(x => x > 2) %}
{% if filteredArr is not empty %}
	<h1>Hooray! Our list contains {{ filteredArr|length }} entries!</h1>
{% endif %}
```

However, this one is working as expected. The same is true for using Doctrine's `ArrayCollection` instead of a `PersistentCollection`. This is the reason why it seems like it's only having difficulties with the `PersistentCollection`. I'm just guessing as I haven't had a look at the implementation, but it might be related that PHP's `empty()` isn't working with `PersistentCollection`s as well.

**Comment by fabpot** [comment]
fixed by #3104
