### ISSUE TITLE
Auto-import all macros from a template in all macros of current template

### ISSUE THREAD

**Issue by mudrayna** [twigphp/Twig#3114]
I was in the following situation:

- I had a `helpers.twig` template with helpful functions for rendering SVGs, images etc.
- I was making an `objects.twig` template with macros for rendering objects, some of which contain SVGs.
- I used this line to import `helpers.twig` and use its functions:
```
{% import 'helpers.twig' as h %}
```
But then, `h` wasn't available in the macro functions written thereafter. I got the following error:

![image](https://user-images.githubusercontent.com/53216898/62715581-b28b1c80-b9f8-11e9-91a3-5f24e9d0ca03.png)

The `import` did work, as without it the error was different:

![image](https://user-images.githubusercontent.com/53216898/62715679-e0706100-b9f8-11e9-9060-4380764ed31b.png)

After lots of unsuccessful guesses as to what the issue might be, I realised that I needed to put the `import` statement inside _every_ macro.

I think it would be logical to import the macros from `h` into the macros in the current template by default. Due to the strange error message, I can't tell whether this is actually a bug.

Thanks!

**Comment by fabpot** [comment]
Which version are you using? It should be better with the latest versions.

**Comment by mudrayna** [comment]
2.11.3

**Comment by susnux** [comment]
This looks like something I also discovered:
https://twigfiddle.com/igy8s5/2

the issue it throws is that the second template importing from is null (but it exists).

**Comment by fabpot** [comment]
Closing as I've just tested and it works well.
