### ISSUE TITLE
Possible inconsistency with language_name twig filter between implementation and documentation

### ISSUE THREAD

**Issue by FloAgator** [twigphp/Twig#3127]
Hello, first thanks for your work (first issue for me, please be indulgent).
While the twig documentation (https://twig.symfony.com/doc/2.x/filters/language_name.html) give example of 5 characters locales (eg. fr_FR) working with this filter, the readme explicitly says that it handles only the two-letters code. I tried it and it seems that the readme version is the correct one.
Should the documentation be corrected or the code itself?

**Comment by fabpot** [comment]
Which README?

**Comment by FloAgator** [comment]
<img width="1048" alt="Capture d’écran 2019-08-13 à 16 34 22" src="https://user-images.githubusercontent.com/49229573/62950402-3e7db980-bde8-11e9-8910-bdc7a7148da3.png">

This one, visible on the package page (https://packagist.org/packages/twig/intl-extra)
https://github.com/twigphp/Twig/blob/2.x/extra/intl-extra/README.md

**Comment by fabpot** [comment]
fixed in #3197
