### ISSUE TITLE
Feature Request: New way to hook into template rendering

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#3129]
Craft’s implementation of Twig is using the now-deprecated `base_template_class` environment setting in order to wrap `display()` with profiling calls:

https://github.com/craftcms/cms/blob/620fa9e16ae1d6d205868754959c459f55128da2/src/web/twig/Template.php#L30-L36

Now that `base_template_class` is deprecated, I’m trying to figure out another way to do this. One option would be to override `Environment::display()` and add the logic there, e.g.

```php
$template = $this->load($name);
$name = $template->getTemplateName();
Craft::beginProfile($name, __METHOD__);
$template->display($context);
Craft::endProfile($name, __METHOD__);
```

However `Template::display()` is also called by `Template::render()`, which is called directly by `twig_include()` without going through the environment, so I’d also need to override the `include()` template function to account for that as well, plus any future callees of `Template::display()` and `Template::render()`. Not great.

So I’m hoping Twig can be updated to include events/hooks that get fired before and after render, that I could hook into to add my profiling logic without overriding the base class.

**Comment by ericmorand** [comment]
There are two nodes that could serve as hooks for what you need: `display_start` and `display_end`. They are injected by each module node at the beginning and end of the display method of the template.

https://github.com/twigphp/Twig/blob/163f6a0979e3011eaacffa57602e9143d84c4cfb/src/Node/ModuleNode.php#L315

By default, the module node comes with two empty nodes for `display_start` and `display_end`
but attaching a custom node visitor to your environment would allow you to replace them with the custom node of your choice.

Untested, just out of my head.

Edit: I was sure the profiler extension was already using that strategy:

https://github.com/twigphp/Twig/blob/163f6a0979e3011eaacffa57602e9143d84c4cfb/src/Profiler/NodeVisitor/ProfilerNodeVisitor.php#L42

**Comment by fabpot** [comment]
The `display_start` and `display_end` are indeed the way to go. There is an example very similar to yours in the codebase: https://github.com/twigphp/Twig/blob/2.x/src/Profiler/NodeVisitor/ProfilerNodeVisitor.php

**Comment by brandonkelly** [comment]
Awesome, I’ll give that a go! Thanks both.
