### ISSUE TITLE
Some errors in macros

### ISSUE THREAD

**Issue by CatAnonymous** [twigphp/Twig#3130]
How to return an array or a json string without error due to html encode in macros?

Test: https://twigfiddle.com/8gf2k2

**Comment by khaiphan9x** [comment]
{% macro test() %}{% apply spaceless %}
  {% set arr = {'foo': 'bar'} %}
  {{ arr|json_encode }}
{% endapply %}{% endmacro %}

{{ _self.test()|raw }}

{# Desire {"foo":"bar"} #}

**Comment by stof** [comment]
the escaping happens inside the macro, not on the output of the macro call, so that's where you need the `|raw` filter.
