### ISSUE TITLE
Feature Request: Arrow function support in the Sort filter

### ISSUE THREAD

**Issue by rungta** [twigphp/Twig#3131]
It would be great if the [`sort`](https://twig.symfony.com/doc/2.x/filters/sort.html) filter could be used with arrow functions to tap into PHP's [`uasort`](https://www.php.net/manual/en/function.uasort.php) function. It would enable a ton of sorting use cases, such as:

```twig
{% set list = [
  { title: 'Apples', quantity: 5 },
  { title: 'Oranges', quantity: 2 },
  { title: 'Grapes', quantity: 4 },
] %}
{% set sorted = list|sort(
  (a, b) => a.quantity == b.quantity ? 0 : (a.quantity > b.quantity ? 1 : -1)
) %}

{# `sorted` is now
[
  { title: 'Oranges', quantity: 2 },
  { title: 'Grapes', quantity: 4 },
  { title: 'Apples', quantity: 5 },
] #}
```

**Comment by fabpot** [comment]
Great idea! Implemented in https://github.com/twigphp/Twig/pull/3132

**Comment by fabpot** [comment]
Even better, I added support for the spaceship operator, so you can now simplify your code to:

```twig
{% set sorted = list|sort((a, b) => a.quantity <=> b.quantity) %}
```

see #3133

**Comment by rungta** [comment]
Wow, that was quick. Thanks @fabpot, and great idea about the `<=>` operator!
