### ISSUE TITLE
No release notification

### ISSUE THREAD

**Issue by toxpal** [twigphp/Twig#3135]
Not a problem of Twig itself, but a minor inconvenience. I'm using Twig in my projects, so I'm watching releases (Github option set to "Releases only" - be notified about new releases...). I don't know if you publish releases in some different way, but Twig is the only project on Github that doesn't notify me of new releases. As a result, I need to manually check changelog and/or releases page every week or so to see if a new version is available.

I'm also watching releases of many other Github projects and see notifications without any problems. So my best guess is that Github has some option (for publishers) to enable/disable individual release notifications maybe, and you don;'t use this option? Sorry if that sounds dumb, I never published projects on GH myself, and I'm not sure how it works.

**Comment by stof** [comment]
well, releases are tagged, but github releases are not created for the tags. Github does not automatically create a github release when you create a tag.

**Comment by toxpal** [comment]
Yes, I always can find new release under "Releases" tab, and for this reason I was wondering why Twig is the only project that doesn't notify me...

**Comment by stof** [comment]
well, the "releases" tabs of github also lists tags without a proper github release attached to them, with a different rendering. That's why you still see something in the list. But notifications are related to the *manual* creation of the release object, which is not something that @fabpot is doing when tagging a release.

**Comment by fabpot** [comment]
Indeed, I'm not using the "Releases" feature of Github.
