### ISSUE TITLE
 Warning: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by reggin** [twigphp/Twig#3138]
In ArrayLoader.php line 64:
                                                  
      [ErrorException]                                
      Warning: Illegal offset type in isset or empty 

It's happened in `twig/twig/src/Loader/ArrayLoader.php:64`:
     
    return isset($this->templates[$name]);

Variable `$name` is object type. Just need to add strict type `(string)` (object `$name` has method `__toString()`)

    return isset($this->templates[(string)$name]);

**Comment by stof** [comment]
question is, how could an object end up here ? And what kind of object ?

**Comment by stof** [comment]
@reggin Can you provide more details to allow reproducing this ?

**Comment by fabpot** [comment]
Closing as there is no answer from the reporter.
