### ISSUE TITLE
Rename "markdown" and "inky" filters?

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#3142]
I've been reviewing the [features of the upcoming Twig 1.12 version](https://github.com/twigphp/Twig/compare/v2.11.3...2.x) and I have some comments about some of the added features. This is the first of some issues discussing those comments.

-----

I like how short the `markdown` and `inky` filter names are ... but I wonder if they are fully understandable in all cases:

For example, what does this template?

```twig
{{ content|markdown }}
```

Does it format the `content` as Markdown? Does it transform the `content` Markdown into something else? Into what?

However, if it were written like this, it cannot be mistaken:

```twig
{{ content|markdown_to_html }}
```

I'm not fully convinced about this. I prefer shorter names ... but adding `_to_html` "only" adds 8 characters.

BEFORE:

```twig
{{ user.comment|markdown }}
{{ uploaded_content|html_to_markdown }}
{{ email_template|inky }}
```

AFTER:

```twig
{{ user.comment|markdown_to_html }}
{{ uploaded_content|html_to_markdown }}
{{ email_template|inky_to_html }}
```

**Comment by fabpot** [comment]
As Twig is not all about HTML, I think it makes sense. I thought about the same when implementing `html_to_markdown`.

**Comment by stof** [comment]
:+1: for that too

**Comment by fabpot** [comment]
For `markdown`, this is already the case :) Where did you see `markdown`?

**Comment by fabpot** [comment]
`inky` renamed in #3148

**Comment by javiereguiluz** [comment]
If you go to https://twig.symfony.com/doc/2.x/ and click on "markdown" you are redirected to https://github.com/twigphp/markdown-extension, which uses `markdown` and `html_to_markdown`.

I guess there is some confusion because we have "markdown-extra" (https://github.com/twigphp/markdown-extra) and "markdown-extension" (https://github.com/twigphp/markdown-extension).

**Comment by fabpot** [comment]
`markdown-extension` is the current library that will be deprecated in favor of the new `markdown-extra`.
