### ISSUE TITLE
Alternative to arrow functions and spaceship operator in the "sort" filter

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#3143]
I'm not fan of the "arrow function" added to the `sort` filter (#3132). Although it solves a common user need, it introduces unnecesary complexity to templates ... which had to be solved partially with the spaceship operator (#3133) which I'm not fan either.

Here's my proposal: remove arrow functions in `sort` and the spaceship operator too. Instead, add two arguments for the `sort` filter.

Example: sort this list by quantity in ascending order:

```twig
{% set list = [
    { name: 'Apples', quantity: 5 },
    { name: 'Oranges', quantity: 2 },
    { name: 'Grapes', quantity: 4 },
] %}
```

BEFORE:

```twig
{% for fruit in fruits|sort((a, b) => a.quantity <=> b.quantity) %}
    {{ fruit.name }}
{% endfor %}
```

AFTER:

```twig
{% for fruit in fruits|sort(by = 'quantity', order = 'ASC') %}
    {{ fruit.name }}
{% endfor %}
```

What if I want to sort by multiple properties? ~~Chain more than one `sort` filter~~ **Update**: if you need that, sort in PHP instead of Twig.

**Comment by stof** [comment]
> What if I want to sort by multiple properties? Chain more than one `sort` filter.

That's wrong. The second sort will sort everything again, not only items being ties on the first sorting properties.
A sort on a tuple is not the same than 2 subsequent sorts.

**Comment by stof** [comment]
also, note that the first reason to introduce arrow functions was not the `sort` filter, but the `filter` filter.

**Comment by javiereguiluz** [comment]
@stof I'm not saying that we should remove arrow functions ... only in the "sort" filter. Arrow functions are great ... in other cases.

**Comment by ericmorand** [comment]
Well, one may wonder why there are sort and filters functions in a templating language and why the upstream context is not sent to the template with the data already sorted and filtered. Isn't data manipulation supposed to come from the data provider?

I think Twig is more and more getting out of touch about what a templating language is.

**Comment by mhcwebdesign** [comment]
Coming from the OpenCart project which has been using Twig as the template engine since OpenCart V3.x, I can only confirm that the Twig filters using the arrow functions don't make much sense. The syntax used for this is a disaster, and the complexity carried out by an arrow function shouldn't be part of the template is the first place. Complex variables are to be set in the controller, and not be set or manipulated in the view. The view is for the rendering.

Time to go back to a proper MVC design!
