### ISSUE TITLE
Allow to pass file paths not only file contents to data_uri filter?

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#3145]
I love the `data_uri` filter. However, looking at my own experience in real Symfony projects, I couldn't use it like it is now.

I needed to embed some images (and other files) inside a Twig template that was used to generate a PDF via an HTML-to-PDF converter.

This is an example of the Twig code I had to use:

```twig
<img src="{{ embed_image(asset('images/symfony-corp-logo.png')) }}" class="logo" />
```

The `embed_image()` function was a custom Twig function which looked roughly like this:

```php
// ...

return sprintf('data:image/png;base64,%s', base64_encode(file_get_contents($absoluteImageFilePath)));
```

However, the current `data_uri` filter only accepts the contents to embed, not the path to the file to embed so I couldn't use it to replace my custom `embed_image()` function.

In any case, I don't know if my use case is common enough. Thanks.

**Comment by fabpot** [comment]
`source(image_path)|data_uri`?

**Comment by fabpot** [comment]
That's documented by the way.

**Comment by javiereguiluz** [comment]
I can't remember why I couldn't use the `source()` function in this case. Anyway, I see that it's possible to do what I wanted to do ... so let's close this. Thanks!

**Comment by Sajito** [comment]
> 
> 
> `source(image_path)|data_uri`?

Unfortunately that way won't work always. If you pass an absolute path containing dots, then source won't handle the path as absolute path.
For example try to load a file from `/var/www/subdomain.domain.tld/image/test.png`.
`source` will throw an exception saying, that it can't find the file.

**Comment by fabpot** [comment]
@Sajito Sure, that's the Twig security model, you can never use an absolute path. You should add the directory to the loader instead. And perhaps create a namespace for images, so that you can use something like `source("@images/test.png")`

**Comment by Sajito** [comment]
That totally makes sense to me, didn't think about that.
It would be nice to have that information in the documentation.

BTW: I actually can use an absolute path, as long as there's only one dot in the path. So if the path was like this `/var/www/html/image/test.png`. Twig actually loads the image. So maybe that's a bug instead?

**Comment by mmarton** [comment]
Found this issue with the same problem... Unfortunately the suggested source function no longer works.

I'm using: `<img src="{{ source(asset('build/images/logo.svg'))|data_uri }}">` and get an exception:

`Unable to find template "/public/build/images/logo.67cb76bb.svg" (looked into: /var/www/html/templates, /var/www/html/templates, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form).`

which is correct, it's not a template and it's in the build folder... 

Am I using it wrong or did something changed?

**Comment by mmarton** [comment]
+ details: I'm usint the lastest versions of symfony6 and twig3 

@javiereguiluz can you help/reopen or should I create a new issue about it?

**Comment by fabpot** [comment]
Can you create a small reproducer? If yes, please open a new issue.
