### ISSUE TITLE
Allow traits to set variables

### ISSUE THREAD

**Issue by fzaninotto** [twigphp/Twig#315]
Traits can only have blocks, and I'd love them to also be able to set variables. Let me explain the use case.

In an ActiveRecord generator, I use traits to enable (or not) the ArrayAccess interface.

So the ActiveRecord template looks like:

``` php
<?php

{% use 'BaseActiveRecord/ArrayAccess.php' %}

/**
 * Base class providing ActiveRecord features to {{ classname }}.
 * Do not modify this class: it will be overwritten each time you regenerate ActiveRecord.
 */
class {{ classname }}{% if implements %} implements {{ implements }}{% endif %} 
{
  // some code
{{ block('ArrayAccess') }}

}
```
And the ArrayAccess provides the implementation:

``` php
{% block ArrayAccess %}

    /**
     * Set a property of the entity by name.
     *
     * @param string $offset The property name.
     * @param mixed  $value  The value.
     *
     * @see setByName()
     */
    public function offsetSet($offset, $value)
    {
        return $this->setByName($offset, $value);
    }

    // etc
{% endblock %}
```

Problem: I'd like to add an interface to the main class, but from the trait. In other words, I'd like to do something like:

```
{% set implements = 'ArrayAccess' %}
```

...inside the ArrayAccess trait.

But if I put this inside the ArrayAccess block, it is not executed until I call block() (and that's too late), and if I put it outside the block, Twig complains loudly:

```
Uncaught exception 'Twig_Error_Runtime' with message 'Template "BaseActiveRecord/ArrayAccess.php" cannot be used as a trait.'
```
Is there a workaround?

**Comment by fabpot** [comment]
Closing as nobody expressed the same need in the last 4 years.
