### ISSUE TITLE
[2.x] array_key_exists() is deprecated on objects in PHP 7.4

### ISSUE THREAD

**Issue by iotch** [twigphp/Twig#3151]
Seems like it has been [fixed for 1.x](https://github.com/twigphp/Twig/pull/3097), but not for 2.x

**Comment by fabpot** [comment]
It has been fixed for both. Do you have any issue in 2.x?

**Comment by iotch** [comment]
Yes, I'm getting deprecation warning on latest PHP 7.4 beta and Twig 2.11.3:

`An exception has been thrown during the rendering of a template ("array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead")`

I believe it is coming from [here](https://github.com/twigphp/Twig/blob/v2.11.3/src/Extension/CoreExtension.php#L1325) and [here](https://github.com/twigphp/Twig/blob/v2.11.3/src/Extension/CoreExtension.php#L1396)

Well, it was fixed actually, but not released, so in v2.11.3 it is still there.

**Comment by Tobion** [comment]
There is no new 2.x release since then https://github.com/twigphp/Twig/commit/03dbdb9683a74379491d237504c1021ff3864b5b

**Comment by fabpot** [comment]
So, it will be part of the next release.

**Comment by teohhanhui** [comment]
We're eagerly waiting for the next Twig 2.x release. It's the only remaining incompatibility for our test suite to pass on PHP 7.4 in API Platform. :laughing:

**Comment by n3storm** [comment]
Here too!

**Comment by nicolas-grekas** [comment]
This is already fixed, please upgrade.

**Comment by n3storm** [comment]
sorry and thank you very much!
problem is rcrowe/twigbridge for laravel has not updated minimum version.

**Comment by jonatan12328** [comment]
tengo este problema, me podrian ayudar. **En desuso: array_key_exists (): el uso de array_key_exists () en objetos está en desuso. Use isset () o property_exists () en su lugar en C: \ xampp \ xamppp \ htdocs \ miotratienda \ src \ Adapter \ EntityMapper.php en la línea 90**

este es el codigo de la linea 90.

if (array_key_exists($key, $entity)) {
                        $entity->{$key} = $value;
                    } else {
                        unset($object_datas[$key]);
                    }
                }
                if ($should_cache_objects) {
                    Cache::store($cache_id, $object_datas);
                }
            }
        } else {
            $object_datas = Cache::retrieve($cache_id);
            if ($object_datas) {
                $entity->id = (int)$id;
                foreach ($object_datas as $key => $value) {
                    $entity->{$key} = $value;
