### ISSUE TITLE
Redundant renderBlock() call when using block() function with ?? default

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#3154]
The following template line:

```twig
{{ block('foo') ?? 'bar' }}
```

will be compiled to this PHP code: (formatted for clarity)

```php
echo 
    (
        $this->hasBlock("foo", $context, $blocks) &&
        !(null === $this->renderBlock("foo", $context, $blocks))
    )
    ? $this->renderBlock("foo", $context, $blocks)
    : "bar";
```

Notice how `renderBlock()` is called twice there, when once should have been enough.

```php
echo
    (
        $this->hasBlock("foo", $context, $blocks)
            ? $this->renderBlock("foo", $context, $blocks)
            : null
    )
    ?? "bar";
```

If it’s too much trouble to avoid the redundant `renderBlock()` call, perhaps at least `renderBlock()` could internally memoize its results, in case it is called more than once.

**Comment by fabpot** [comment]
That's a tough one as the each piece of the generated expression comes from many different nodes that are not aware of the context. I will see what can be done, but it won't easy IMO.

**Comment by fabpot** [comment]
@brandonkelly Can you have a look at #3155?

**Comment by stof** [comment]
`renderBlock` always return a string, so this could even be optimized further (transforming it to be the same `block('foo') is defined ? block('foo') : 'bar'`

**Comment by fabpot** [comment]
@stof You're right, that makes the code much simpler :)

**Comment by brandonkelly** [comment]
@stof Unfortunately that syntax is not supported either; you will get an error saying that `is defined` can only be used for simple variable types.

**Comment by fabpot** [comment]
@brandonkelly It is "equivalent" in the sense that this is how it is compiled now :) See the PR.

**Comment by fabpot** [comment]
So,  `{{ block('foo') ?? 'bar' }}` is now "optimized" but `{{ block('foo') is defined ? block('foo') : 'bar' }}` also works for me. Can you double-check?

**Comment by brandonkelly** [comment]
Ah you’re right. When I got the error, I actually had that ternary expression _within_ with a null coalescing chain, such as:

```twig
{{ (block('foo') is defined ? block('foo') : null) ?? 'bar' }}
```

If you do that, you will get the error, `The "defined" test only works with simple variables.` I didn’t even think to test it with the `?? 'bar'` part removed, since the error gave me the impression that it was the ternary expression that was to blame.

**Comment by brandonkelly** [comment]
I just cherry-picked the PR to the 2.x branch and tested with that, and it works like a charm!

```php
echo ((        $this->hasBlock("foo", $context, $blocks)) ? (        $this->renderBlock("foo", $context, $blocks)) : ("bar"));
```

(The extra whitespace was a problem before this change as well, by the way.)
