### ISSUE TITLE
batch filter documentation is missing preserve_keys argument

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3159]
https://twig.symfony.com/doc/2.x/filters/batch.html

The third argument added by https://github.com/twigphp/Twig/pull/2884 is missing from the doc.

**Comment by stof** [comment]
I suggest you to open a PR fixing the doc (the doc is maintained in the `doc` folder of this repo)

**Comment by ericmorand** [comment]
Will do. I'll finish my review of the doc and provide some PRs.
