### ISSUE TITLE
Newline not preserved after tag when using line whitespace trimming

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3162]
Consider the following template:

```twig
{% do 1 + 2 ~%}
    foo
```

When rendered, we get:

```    foo```

https://twigfiddle.com/oxixzf

But according to the [documentation](https://twig.symfony.com/doc/2.x/templates.html#whitespace-control):

> Line whitespace trimming via the ~ modifier: Removes all whitespace (excluding newlines). **Using this modifier on the right disables the default removal of the first newline inherited from PHP**.

Shouldn't the newline after the `do` tag be preserved?

**Comment by stof** [comment]
The compiled template (which can be displayed on twigfiddle) shows that it is rendering a newline char. So this might actually be an issue of Twigfiddle itself not support an output starting with a newline char, or something like that.

**Comment by stof** [comment]
See https://twigfiddle.com/0nw355 for a fiddle having the same issue in the rendered output, while there is definitely a newline char being rendered.

**Comment by ericmorand** [comment]
Oh, thanks. I should have checked with TwigPHP itself.

**Comment by stof** [comment]
Well, twigfiddle is a nice tool, but it might have bugs too. I reported it there

**Comment by ericmorand** [comment]
Yes, thanks for that. The "Show raw result" button is quite confusing to me. Very nice tool though but I'll  double-check with my local TwigPHP environment in the future.

**Comment by ninsuo** [comment]
Hi there,

Sorry about that guys, will fix the tool soon.

Cheers,
Alain
