### ISSUE TITLE
Twig + Eloquent Relationship Issues

### ISSUE THREAD

**Issue by ed-iv** [twigphp/Twig#3165]
Just ran into an issue in my project which uses Twig and Eloquent ORM. This issue involves the relationship types which return a single model (e.g. hasOne, belongsTo). When referencing a relationship for which no matching model exists, the relationship resolves to an instance of the relationship itself (for example: Illuminate\Database\Eloquent\Relations\BelongsTo) instead of to NULL as expected.

This leads to false positives in cases where the truthiness of the relationship is used in conditionals. For example, assuming User->sibling is NULL, the content in the conditional below will be displayed:

```twig
{% if user.sibling %}
     <p>Tell your sibling I said hello</p>
{% endif %}
```
This does not appear to be an issue with relationships which return collections as they simply return empty collections when no matching models are found.

**Comment by ericmorand** [comment]
I assume this is the responsibility of your data provider (i.e. the system that provides the context to the Twig template for rendering) to ensure that `user.sibling` is _NULL_ when there is no sibling.

How could Twig guess that when `user.sibling` is an instance of `Illuminate\Database\Eloquent\Relations\BelongsTo` then it should consider it as _NULL_?

**Comment by stof** [comment]
this is indeed not something that Twig can change (just like you would not open an issue in the PHP bug tracker complaining that `if ($user->sibling) { echo '<p>Tell your sibling I said hello</p>' }` would display something when using Eloquent)

**Comment by ed-iv** [comment]
Yea, understood.

**Comment by NesCafe62** [comment]
I also encountered this issue. temporary solved by using `user.getRelation('sibling')`
