### ISSUE TITLE
import syntax causing fatal error with nested blocks after upgrade to v1.42.3

### ISSUE THREAD

**Issue by ThomWilhelm** [twigphp/Twig#3167]
After upgrading twig from v1.41.0 to v1.42.3 the following code is now giving a fatal error:

```
{% from '@vivid_frontend/macros/modal.twig' import header as modal_header %}

{% block content %}
  {% block user_modal %}
    {{ modal_header(user_form_title, 'userModalLabel') }}
  {% endblock %}
{% endblock %}
```

I'm getting the error **Unknown "header" function**. This worked fine on v1.41.0. If I put the modal header function not inside a nested block it still works:

```
{% block content %}
  {{ modal_header(user_form_title, 'userModalLabel') }}
  {% block user_modal %}
    <div>etc</div>
  {% endblock %}
{% endblock %}
```

Interestingly, I've found the following syntax does work with nested blocks on both versions.

```
{% import '@vivid_frontend/macros/modal.twig' as modal_header %}

{% block content %}
  {% block user_modal %}
    {{ modal_header.header(user_form_title, 'userModalLabel') }}
  {% endblock %}
{% endblock %}
```

From the 1.42.0 changelog I noticed some changes regarding macros in nested blocks: https://fossies.org/linux/Twig/CHANGELOG

Is this a bug or expected behaviour?

**Comment by stof** [comment]
this is clearly not an expected behavior.

**Comment by ThomWilhelm** [comment]
this is clearly not going to be fixed
