### ISSUE TITLE
Testing a non-existent variable with "is not empty" throws error in dev, returns null in prod

### ISSUE THREAD

**Issue by stephane-lou** [twigphp/Twig#3169]
Hi. 

I'm facing a problem and I don't know if its a wanted behavior in twig or not.

In one of my templates, I have a test like this:

`{% if form.content.vars.data is not empty and form.content.vars.data.images is not empty %}`

In my context, `form.content.vars.data` contains a int `2` (which is not wanted).

In `dev` mode, the page crashes on the fact that I cannot read a property `images` on `data` and it's the wanted behavior. But in `prod` mode , it fails silently and `form.content.vars.data.images is not empty` returns `null`.

I know there's two problem here, my test do not handle the case in which an `int` is inside `data`, but in my understanding of tthe context, it should also throw an error in `prod` mode.

WDYT ?

**Comment by stof** [comment]
When running in non-strict variable mode, accessing an undefined variable returns `null` rather than failing (that's the very meaning of this configuration).

**Comment by stephane-lou** [comment]
I didn't even know `strict_variables `.

My problem here is the difference between prod and dev. For me, it should break the same way in prod or dev, because if not, how would you know where the error comes from ? Honestly it took me way more than it should to catch the problem (it's not my code).

**Comment by stephane-lou** [comment]
I didn't know `strict_variables` and I've just seen that it's setup in symfony with `%kernel.debug%`.
