### ISSUE TITLE
merge filter with multiple parameters

### ISSUE THREAD

**Issue by mmarton** [twigphp/Twig#3172]
Hi!

https://twig.symfony.com/doc/2.x/filters/merge.html
the docs sais `Internally, Twig uses the PHP array_merge function.`
but it doesn't work with multiple arguments.

```php
var_dump(array_merge(['a' => 1], ['b' => 2], ['c' => 3]));
var_dump(array_merge(['a' => 1], array_merge(['b' => 2], ['c' => 3])));

/*
both is:
array(3) {
  ["a"]=>
  int(1)
  ["b"]=>
  int(2)
  ["c"]=>
  int(3)
}*/
```

but in a template:

```
{% dump {'a': 1}|merge({'b': 2}, {'c': 3}) %}
{% dump {'a': 1}|merge({'b': 2})|merge({'c': 3}) %}

/*
array:2 [▼
  "a" => 1
  "b" => 2
]

array:3 [▼
  "a" => 1
  "b" => 2
  "c" => 3
]

*/
```

> composer show | grep twig
symfony/twig-bridge                 v4.3.5             Symfony Twig Bridge
symfony/twig-bundle                 v4.3.5             Symfony TwigBundle
twig/twig                           v2.12.0            Twig, the flexible, fast, and secure template language for PHP

**Comment by fabpot** [comment]
Indeed, can you submit a PR to fix the documentation?

**Comment by ericmorand** [comment]
Well, it says that it uses the `array_merge` function, not that it accepts the same number of parameters or outputs the same result.

It raises some concerns about the relevance of the `Internally, Twig uses the PHP array_merge function` information. Those implementation details can be found in many places in the documentation and they basically don't serve any valuable purpose.

**Comment by stof** [comment]
well, given that array_merge has a different behavior depending on whether the array contains numeric keys or string keys, this implementation detail is still relevant IMO, as the `merge` filter of Twig inherits that behavior.
