### ISSUE TITLE
Null-coalescing operator missing in doc homepage

### ISSUE THREAD

**Issue by JakeFr** [twigphp/Twig#3176]
Hi
I notice that the null-coalescing operator missing in doc homepage
https://twig.symfony.com/doc/1.x/
https://twig.symfony.com/doc/2.x/

Others (.., |, ~, ., [], ?:)
should be
Others (.., |, ~, ., [], ?:, ??)

The source of this page is not in this repo, afaik

**Comment by fabpot** [comment]
Good catch, will be online at the next deploy later today.
