### ISSUE TITLE
[Documentation] final dash - in filter docs

### ISSUE THREAD

**Issue by flaushi** [twigphp/Twig#3177]
Hey, is the final `-` on https://twig.symfony.com/doc/2.x/filters/filter.html correct?
Should't it be 
```
{% for v in sizes|filter(v => v > 38) %}
    {{ v }}
{% endfor %}
{# output 40 42 #}
```
instead of the current
```
{% for v in sizes|filter(v => v > 38) -%}
    {{ v }}
{% endfor %}
{# output 40 42 #}
```

**Comment by stof** [comment]
that `-` is the whitespace control feature.

**Comment by flaushi** [comment]
Ok, thanks. Didn't know about that.
