### ISSUE TITLE
\n in translation.yml file and nl2br filter issue on Edge browser

### ISSUE THREAD

**Issue by MatthieuMan** [twigphp/Twig#3181]
Hi

when using ` | nl2br ` filter in a twig template to get a string from a translation file in a symfony project ( using the `|` ) eg:
```yaml
    body: |
      Caution,
      blablablablablablabla
      blablablablablablabla

      best regards ?
```
 , I can see `lsep` pattern on Microsoft edge browser, instead of having a `<br />` tag  at the end of each line!

is there another way to make it work

**Comment by stof** [comment]
What do you mean with `I can see lsep pattern` ?

Also, please give us a reproducing case:

- what does you template look like ?
- what does the generated HTML look like ?

note that if the generated HTML is fine but the Edge rendering is wrong, that's not something that Twig can fix, as it generates the HTML.
