### ISSUE TITLE
setRendered and disabled bug

### ISSUE THREAD

**Issue by Stifeux** [twigphp/Twig#3185]
Hi,

When I use
`{% do form.setRendered %}`
And submit my form, I get an error that says that values cannot be null. And if I disable the cell it's the same thing.

My form turns the value into null when I use "setRendered" or "disabled". Is this normal or did I misconfigure Twig?

Twig version : 2.12.0

**Comment by fabpot** [comment]
Hi, this is probably related to Symfony, not Twig. I'm going to close it here. I would recommend using Stackoverflow for your questions instead of Github that we are not using for support. Thank you.
