### ISSUE TITLE
Extending a template that includes another one breaks block overriding

### ISSUE THREAD

**Issue by theredled** [twigphp/Twig#3189]
I have a child template inheriting from a mother template, and that mother template includes `included.html.twig`, which cointains a block `ablock`.
I can't override that block from the child.

`mother.html.twig`
```twig
Mother
{% include "included.html.twig" %}
```

`included.html.twig`
```twig
Included
{% block ablock %}
    Foo
{% endblock %}
```

`child.html.twig`
```twig
{% extends '@Test/embed2.html.twig' %}

{% block ablock %}
    Bar
{% endblock %}
```

I'm expecting:
```
Mother
Included
Bar
```

I'm getting:
```
Mother
Included
Foo
```

The real situation is that I have to use `include` as that `include` is included multiple times.

Can that be fixed?

**Comment by stof** [comment]
Including a template does not bring the structure of that template into the structure of your own template. It includes the output of rendering that template at the place where the inclusion happens.

**Comment by theredled** [comment]
Right, won't fix then. So what if I have a menu M in my main frame template F, M being in a `include` so that F is not too huge, an a page P `extend`ing F wants to override a breadcrumbs in M?

Quite classic case, what would be the recommended way of doing this?

**Comment by stof** [comment]
that's not possible directly. You would have to wrap the include in a block of F, so that P can override the block to replace the included template with another one (or do whatever it wants as using an include in the replacement block won't be required btw).

**Comment by theredled** [comment]
Maybe that could be a feature request?

**Comment by stof** [comment]
Merging structures of separate templates is **totally** different from what `include` does. We cannot just turn including into importing the structure.

We already have `{% use %}` which allows importing block definitions from another template btw, which might also be useful in your case. And `{% use %}` puts some restriction on templates which can be used with it, to make sure we don't have other things than block definitions happening in them.

**Comment by theredled** [comment]
Right, I'll check this.

**Comment by fabpot** [comment]
Closing
