### ISSUE TITLE
Template outputting only "0" don't render anything

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3191]
Consider the following template:

```twig
0
```

Rendering that template outputs nothing:

https://twigfiddle.com/ayv6cz

The compiled template looks like this:

```php
protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        // line 1
        echo "0";
    }
```

This is strange: echoing 0 or "0" in PHP ouputs "0".

**Comment by xabbuh** [comment]
Maybe that's just an issue of twigfiddle.com.

**Comment by ericmorand** [comment]
Good point. Let me check with command line.

**Comment by ericmorand** [comment]
@xabbuh You are absolutely right. It works ex expected from the command line. Closing this issue and opening one on twigfiddle repository. Thanks for your help.

**Comment by ninsuo** [comment]
Thanks @ericmorand & @xabbuh I've fixed the issue on twigfiddle side.
Apologies for the noise.

Have a good day,
Alain
