### ISSUE TITLE
Arrow function are not allowed outside filters

### ISSUE THREAD

**Issue by alex-dev** [twigphp/Twig#3192]
Arrow functions currently can only be used in a filter as per ExpressionParser.
This prevents multiple functionalities such as
- passing arrows to an include context so it can forward it to an actual filter;
- passing arrows to a macro or a function;
- defining and setting a callable so it can be used in subsequent expressions;

**Comment by fabpot** [comment]
The limitations you list are on purpose to limit usage of arrow functions to simple use cases.

**Comment by khalwat** [comment]
To make this work this one line: <https://github.com/twigphp/Twig/blob/3.x/src/ExpressionParser.php#L483> from: 
```php
                    foreach ($this->parseArguments() as $n) {
```
 to: 
```php
                    foreach ($this->parseArguments(false, false, true) as $n) {
``` 
then closures all work in the context we want, e.g.: 
```twig
    {% set collection = collect(['a', 'b', 'c']) %}
    {% set contains = collection.contains((value, key) => value == 'a') %}
```
 with a nice, clean, normal syntax. I'd love to see this happen, too.

**Comment by fabpot** [comment]
See #4378
