### ISSUE TITLE
Feature Request: new function html_attr to output html attributes the easy way

### ISSUE THREAD

**Issue by axten** [twigphp/Twig#3193]
Hi, I would suggest to add a new helper function to manage html attributes in a simple way.

twig example:
```
    {% set attr = {
        'aria-expandend': 'false',
        disabled: true,
        hidden: false,
        id: 123,
        title: 'cli"<ck',
    } %}

    <button{{ html_attr(attr) }}>Test</button>
```
output: 
```
<button aria-expandend="false" disabled id="123" title="cli&quot;&lt;ck">Test</button>
```

PR: #3199

**Comment by emr** [comment]
I think this feature is required for html twig files. I was thinking about opening a pr for it. But I think it have to be added to [html-extra](https://github.com/twigphp/html-extra) repository.

**Comment by fabpot** [comment]
Closing as there is a PR; let's discuss there.
