### ISSUE TITLE
The string to escape is not a valid UTF-8 string.

### ISSUE THREAD

**Issue by uginroot** [twigphp/Twig#3194]
Problem escape not utf-8 string from html_attr string

Twig:
```html
title="{{ "D�cor Chalk"|e('html_attr') }}"
```

Problem src ([link](https://github.com/twigphp/Twig/blob/08ea68c89dff3b64dbc33aaf2935b20523a868df/src/Extension/EscaperExtension.php#L328)):
```php
if (!preg_match('//u', $string)) {
    throw new RuntimeError('The string to escape is not a valid UTF-8 string.');
}
```

Solution:
```php
if (!preg_match('//u', $string)) {
    $string = mb_convert_encoding($string, 'UTF-8', 'UTF-8');
}
```

**Comment by stof** [comment]
trying to convert an invalid UTF-8 string from UTF-8 to UTF-8 looks wrong to me.

You should rather fix your code to use a valid UTF-8 string.

**Comment by fabpot** [comment]
I agree with @stof.

**Comment by uginroot** [comment]
Original string is utf8mb4_unicide_ci from database:
"FolkArt Home Décor Chalk Finish Paint Set (2 Ounce), Top Colors (New Version)"
![image](https://user-images.githubusercontent.com/2391460/69524272-d9616480-0f8f-11ea-942d-28952ad36821.png)

Template:
![image](https://user-images.githubusercontent.com/2391460/69524693-d74bd580-0f90-11ea-8009-b48fac82f1c3.png)

Browser (dump function displays the string correctly):
![image](https://user-images.githubusercontent.com/2391460/69524649-b6838000-0f90-11ea-9130-090d588c3b56.png)

If I call filter |e('html_attr'), I get the following error:
![image](https://user-images.githubusercontent.com/2391460/69525373-2e9e7580-0f92-11ea-97f2-1ae6af742b1d.png)

**Comment by uginroot** [comment]
The problem is that any user can write the "é" character (and others) to the database and after that the server gives an error of 500. My solution is not correct, but it prevents the site from working completely on data that is correct from the point of view of users. It is better to let the user see the � symbol and continue to work than the 500 error and the complete inoperability of the site.

Проблема в том что любой пользователь может записать символ "é"(и другие) в базу и после этого сервер выдаёт ошибку 500. Моё решение не правильное, но оно предотвращает полную неработоспособность сайта на корректных, с точки зрения пользователей, данных. Лучше пусть пользователь увидит символ � и продолжит работать, чем ошибку 500 и полную неработоспособность сайта.

**Comment by uginroot** [comment]
Github correctly displays the "é" symbol. I want something that the twig would not break the site when he comes across this symbol.

**Comment by uginroot** [comment]
I found out what is the reason for this behavior.

Symfony (.env.local), add сharset=utf8mb4 to constant DATABASE_URL:
```DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name?сharset=utf8mb4```

For PDO:
```$pdo = new \PDO('mysql:dbname=dbname;host=127.0.0.1;charset=utf8mb4', 'user', 'password');```
