### ISSUE TITLE
Cannot combine form vars and filter

### ISSUE THREAD

**Issue by Schyzophrenic** [twigphp/Twig#3195]
Hello,
It seems we cannot combine form variables and the currency_symbol filter for an odd reason.
Here are some working examples:
{{ 'EUR'|currency_symbol }} > Displays €

{{ 'form.currency.vars.value }} > Displays EUR

Unfortunately the follwing generates an exception (I just could not pin point why)
{{ form.currency.vars.value|currency_symbol }}

An exception has been thrown during the rendering of a template ("Couldn't read the indices [Names][][0] for the locale "fr" in "D:\dev\apps\i-wish\vendor\symfony\intl/Resources/data/currencies". The indices also couldn't be found for the fallback locale(s) "en", "root".").

**Comment by stof** [comment]
Can you share a small project reproducing this ?

**Comment by Schyzophrenic** [comment]
It seems I cannot reproduce the error on a simple scenario, which makes me think it is on my end. I will keep digging and eventually close the issue if I cannot replicate on a simple environment.

**Comment by Schyzophrenic** [comment]
Closing this issue as it does not occur when proper testing of the variable is in place:
```twig
{% if form.currency.vars.value %}
    {{ form.currency.vars.value|currency_symbol }}
{% endif %}
```
