### ISSUE TITLE
Support Native Web components 

### ISSUE THREAD

**Issue by alannungaray** [twigphp/Twig#3201]
Pre-render web components in to an initial state precompiled

```html
  {% for item in navigation %}
        <custom-tag  custom-attr=" {{ item }}"></custom-tag>
 {% endfor %}       

```

**Comment by stof** [comment]
Twig is a templating engine which does not care about the output format. you can output any HTML you want.

For this template to work as-is, you would have to make sure that casting `item` to string produces the format you expect in `custom-attr` (and careful with the space before it in `custom-attr`). If you need a specific format, you can write some filters instead.
but to me, there is nothing to change in Twig to allow this to work. native custom elements are not different from native built-in element from the HTML point of view.
