### ISSUE TITLE
Deprecate "spaceless", "filter" and "for if" in Twig 1

### ISSUE THREAD

**Issue by Chi-teck** [twigphp/Twig#3202]
The following features were deprecated in Twig 2 and removed in Twig 3. As Twig 3 has already been released projects that still run on Twig 1 will likely jump directly to Twig 3 when updating.
So that it makes sense to deprecate it in Twig 1 to let developers to prepare for Twig 3 update.

1. "spaceless" tag
2. "filter" tag
3. "if" condition support on the "for" tag

**Comment by fabpot** [comment]
You should do the migration from 1 to 2 then to 3. We cannot deprecate features in 1 as this would mean removing them in 2, which is not possible.
