### ISSUE TITLE
condition in loop

### ISSUE THREAD

**Issue by Beaujolweb** [twigphp/Twig#3203]
Since v3.0, it's not possible to break a loop by a condition like this :

{% set selected = '' %}
{% for value in values if selected == '' %}
    {% if value == 2 %}
        {%set selected = 'selected' %}
    {% endif %}
{%endfor %}

version 3 requires to go through the entire 'values' variable...

**Comment by stof** [comment]
This was *not* breaking the loop in Twig 2. It would still loop over all values.

The old syntax was equivalent to this:

```twig
{% set selected = '' %}
{% for value in values %}
  {% if selected == '' %}
    {% if value == 2 %}
      {% set selected = 'selected' %}
    {% endif %}
  {% endif %}
{% endfor %}
```

The only difference between that code and the original one using `for-in-if` is related to the `loop` special variable (as `for-in-if` would increment the loop index only inside the if).
