### ISSUE TITLE
File check and PHP open_basedir warning

### ISSUE THREAD

**Issue by mvorisek** [twigphp/Twig#3209]
In this line https://github.com/twigphp/Twig/blob/ac0f512553fab5a685aa0ed1e357d20a644b81bf/src/Loader/FilesystemLoader.php#L212 PHP throws a warning about accessing file outside `open_basedir` on Windows if:
1. PHP `open_basedir` is set
2. `$name` is an absolute path

example:
```
ErrorException: is_file(): open_basedir restriction in effect.
File(C:/dev\ps_17\app/Resources/views/C:/dev/ps_17/mails/themes/modern/core/account.html.twig)
is not within the allowed path(s): (C:/dev)
in C:/dev\ps_17\vendor\twig\twig\src\Loader\FilesystemLoader.php:233
```

Issue presented in all major versions (1.x - 3.x).

**Comment by fabpot** [comment]
Closing as nobody else has ever had this issue. Feel free to submit a PR if you want it to be fixed.

**Comment by mvorisek** [comment]
name passed to `loadTemplate` must NEVER be an absolute path, right?

**Comment by stof** [comment]
it must be a template name, not a path

**Comment by mvorisek** [comment]
@stof thanks, @fabpot here is the PR ;-)
