### ISSUE TITLE
Twig Team/Contributors homepage leads to a 404

### ISSUE THREAD

**Issue by kick-the-bucket** [twigphp/Twig#3210]
`"authors": [
    {
        "name": "Twig Team",
        "homepage": "https://twig.symfony.com/contributors",
        "role": "Contributors"
    }
]`
![Screenshot from 2019-12-03 09-54-49](https://user-images.githubusercontent.com/7068596/70031028-0bd41880-15b3-11ea-9bdf-d88c0f834b7f.png)

**Comment by fabpot** [comment]
Where did you see the link to this page? It does not exist.

**Comment by stof** [comment]
@fabpot it is referenced in the composer.json in the list of authors.

**Comment by fabpot** [comment]
Removed the page from composer.json.
