### ISSUE TITLE
Date PHP 7.4 backward compatibility issue

### ISSUE THREAD

**Issue by SirSova** [twigphp/Twig#3217]
Hi
Yesterday after migration on php 7.4 i got a issue, that dates renders not correctly in some cases.
Example : 
```
<?php
require __DIR__ . '/vendor/autoload.php';

$twig = new \Twig\Environment(
    new \Twig\Loader\ArrayLoader(
        [
            'index.html' => 'Hello {{ name }}! {{ date.date | date("Y", false) }}',
        ]
    )
);

echo $twig->render('index.html', ['name' => 'Fabien', 'date' => new DateTime('2007-07-06')]); echo "\n";
```
Php7.3 output: 
`Hello Fabien! 2007`
Php7.4 output:
```
PHP Notice:  Undefined property: DateTime::$date in home/user/project/vendor/twig/twig/src/Extension/CoreExtension.php on line 1415
PHP Stack trace:
....
Hello Fabien! 2019
```
I have found only one mention in update about DateTime : 

> Calling var_dump() or similar on a DateTime or DateTimeImmutable instance will no longer leave behind accessible properties on the object.
Comparison of DateInterval objects (using ==, <, and so on) will now generate a warning and always return FALSE. Previously all DateInterval objects were considered equal, unless they had properties.

Can i fix it in easy way?

**Comment by stof** [comment]
Well, don't use `date.date` in your template. That's not Twig accessing the internal `$date` property of the DateTime object. That's your own code (written in a Twig template)..

**Comment by stof** [comment]
and due to accessing an undefined property, the value you are formatting is actually `null` now, which is why the year is 2019 (`new DateTime(null)` is the same than `new DateTime('now')`).

**Comment by SirSova** [comment]
I am interested how it worked previously. Why Twig gave access to  `date` property?
Default code `(new DateTime())->date` will return null && Notice in php7.3 also

**Comment by stof** [comment]
See this in the PHP changelog:

> Calling var_dump() or similar on a DateTime or DateTimeImmutable instance will no longer leave behind accessible properties on the object.

There are a bunch of things that would create these properties on DateTime objects when being used. `var_dump` is one of them mentioned in the changelog. But another case trigger the leak of these properties is casting the object to an array, which is used internally in Twig to identify available properties. See https://3v4l.org/pMoEl The second access after casting to an array correspond to what Twig does.

**Comment by SirSova** [comment]
Okay, thank you
