### ISSUE TITLE
Including list of template names no longer works in Twig 3.0.0

### ISSUE THREAD

**Issue by umulmrum** [twigphp/Twig#3219]
In a template I use a line like this:

`{% include [template1, template2] %}`

If template1 does not exist, a PHP error occurs:

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Twig\Environment::getTemplateClass() must be of the type string, null given, called in /home/web1/vendor/twig/twig/src/Environment.php on line 309 and defined in /home/web1/vendor/twig/twig/src/Environment.php:259`

This is because that line in the template is compiled to something that passes an array like `[null, 'template2']` to `\Twig\Template::loadTemplate()` which eventually leads to a call of `\Twig\Environment::getTemplateClass()`. Latter method expects a string as template name but receives `null` (scalar type hint added in Twig 3.0.0).

A simple fix is to check for null in `\Twig\Environment::load()` and throw a `LoaderError` - let me know if this fix is acceptable and I'll file a PR.

**Comment by stof** [comment]
the issue is not about passing an array being unsupported. It is about passing `null` inside that array. And that was never officially supported. The phpdoc for this argument in `load` is `string|TemplateWrapper` already in 2.x, so passing `null` is not meant to work.

**Comment by umulmrum** [comment]
OK for me (although not quite easy to spot when using `include` in a template).
