### ISSUE TITLE
Compress/minify Twig v3 output

### ISSUE THREAD

**Issue by toxpal** [twigphp/Twig#3220]
This is not an issue with Twig itself, but I hope devs might suggest some solution.

As many Twig users, I was using 3rd party extensions (like https://github.com/nochso/html-compress-twig) to auto-optimize (minify) Twig output. Unfortunately, that extensions seems not to be maintained anymore. As a result, it doesn't work with Twig 3.

Maybe devs have some plans to add option in Twig itself to minify output? If not, maybe someone can suggest another extension, which is compatible with Twig 3? A quick research wasn't successful for me (only found extensions that were updated 5 years ago).

**Comment by lyrixx** [comment]
This kind of extension are almost useless because (almost) everyone use HTTP compression. 

Server like Nginx, Apache and all browsers (>IE6) support that for ages. So the gain of removing white space is really minimal and does not worth it.

**Comment by stof** [comment]
and these servers are probably faster at compressing these whitespaces than the html-compress library is at removing them. So applying this compression in PHP might actually  make things slower (especially when considering that the web server will probably still apply its gzip compression on the anyway if you care about size, so you won't even reclaim that time)

**Comment by lyrixx** [comment]
I think we can safely close this issue
