### ISSUE TITLE
markdown-extra doesn't include dependencies

### ISSUE THREAD

**Issue by Guite** [twigphp/Twig#3227]
The vendors used for processing markdown need to be added to the `require` section instead of `require-dev`: https://github.com/twigphp/markdown-extra/blob/3.x/composer.json#L22-L25

A similar change has been done for the html-extra extension already in https://github.com/twigphp/html-extra/commit/835a1f02e01b5d82a31c521a78ce74abc31fff46

Also `michelf/php-markdown` is fixed to `1.8` while version `1.9.0` is available.

**Comment by fabpot** [comment]
There is no Markdown lib in the `require` section as the user needs to make a choice. We cannot do it for themselves.

**Comment by Guite** [comment]
Would it be worth considering shipping a lightweight lib by default while other alternatives could be added for advanced use cases manually?

**Comment by fabpot** [comment]
This could be considered indeed. This lightweight lib should have no dependencies though to avoid dep conflicts.

**Comment by Guite** [comment]
https://github.com/michelf/php-markdown/blob/lib/composer.json looks quite promising then.

**Comment by Guite** [comment]
Both `erusev/parsedown` and `michelf/php-markdown` have no dependencies.
I can do a PR of course, but what are the preferences?
