### ISSUE TITLE
Can we detect dump function

### ISSUE THREAD

**Issue by nevercodealone** [twigphp/Twig#3228]
Hi,

often i forget to delete dump functions in twig templates. Is there a way to detect them and use this in a prehook in git?

See you
Roland

**Comment by xabbuh** [comment]
If you use Symfony, you could run the `lint:twig` command in the `prod` environment which should error when the `dump()` function is used but not defined (which should be the case in the `prod` environment).

**Comment by nevercodealone** [comment]
So maybe this is a feature request ;) Or should we close it?

**Comment by dsentker** [comment]
A feature request is not necessary since @xabbuh has shown a way to detect a `dump()` call. Just use `php bin/console lint:twig templates --env=prod` in the CLI.

**Comment by tacman** [comment]
I'm running into something when I try that:

bin/console lint:twig templates/ --env=prod

In Container.php line 264:
                                                                                 
  You have requested a non-existent service "debug.error_handler_configurator".  
                                                                                 
Any ideas?  I can't tell what that's related to.  It happens when I try to clear the cache too.

**Comment by xabbuh** [comment]
@tacman might be fixed by symfony/symfony#50498 (which was not released yet)
