### ISSUE TITLE
Behavior change between 2.6.2 and 2.7.0 for macro in sandbox

### ISSUE THREAD

**Issue by amenophis** [twigphp/Twig#3242]
I'm upgrading dependencies in one of my project, the behavior changed if I import and use a macro inside a template included in a sanbox tag.

The code to reproduce the issue
![image](https://user-images.githubusercontent.com/2158235/72210750-894b4c80-34c0-11ea-882d-8f6ac650dce3.png)
![image](https://user-images.githubusercontent.com/2158235/72210776-e5ae6c00-34c0-11ea-8069-e8d43b6be548.png)

With twig 2.6.2, the code produce this output
![image](https://user-images.githubusercontent.com/2158235/72210786-ff4fb380-34c0-11ea-9bc4-34a0a058df3b.png)

With twig 2.7.0, the code produce this output
![image](https://user-images.githubusercontent.com/2158235/72210802-31f9ac00-34c1-11ea-872d-830531b73667.png)

If i add the macro to the allow tags with twig 2.7.0, it works like in 2.6.2 without adding it.

Is it an expected behavior change ?

**Comment by fabpot** [comment]
Having to explicitly allow the ``macro`` tag in a sandbox seems the right behavior to me, and should have been the case in 2.6 as well. I've not looked at 2.6 to understand why it was not the case though.

**Comment by amenophis** [comment]
I see the same if i use the default filter in my macro, works well without trusting it in the policy in 2.6.2, but in 2.7.0, i need to trust default and escape filters.

Weird no ?

**Comment by amenophis** [comment]
The cache for 2.6.2:
![2 6 2](https://user-images.githubusercontent.com/2158235/72241355-ee995d80-35e6-11ea-8688-359bf1aae81d.png)

The cache for 2.7.0:
 ![2 7 0](https://user-images.githubusercontent.com/2158235/72241353-ee00c700-35e6-11ea-81c4-bd9d24609374.png)

**Comment by amenophis** [comment]
@fabpot do you agree this is a BC break ? Should it be fixed ?

**Comment by fabpot** [comment]
Closing as there is nothing we can do.
