### ISSUE TITLE
Twig_SimpleFunction does not inherit TwigFunction

### ISSUE THREAD

**Issue by olleharstedt** [twigphp/Twig#3244]
Twig_SimpleFunction does not inherit TwigFunction, but this is the interface that is checked in addFunction(). Thus, Twig_SimpleFunction can never be used?

Version: 1.42.4.

**Comment by stof** [comment]
In 1.x, `addFunction` checks for either `TwigFunction` or the (deprecated) `Twig_FunctionInterface`. `Twig_SimpleFunction` is part of the deprecated layer.

**Comment by olleharstedt** [comment]
Meaning Twig_SimpleFunction should not (can not) be used?

**Comment by stof** [comment]
if you want to use the forward-compatible way, use the `Twig\TwigFunction` class.

In 1.x, `Twig_SimpleFunction` is a BC class_alias for it. And it is the class name working in all 3 major versions of Twig (Twig 2.x renamed `Twig_SimpleFunction` to `Twig_Function` in replacement of the old deprecated `Twig_Function` of Twig 1.x, but when introducing the namespaced class names after that in both 1.x and 2.x, we made it be the future-proof class name in both 1.x and 2.x)
