### ISSUE TITLE
Made escaping smarter with static string

### ISSUE THREAD

**Issue by lyrixx** [twigphp/Twig#3246]
I have the following content:
```jinja
<code>{{ crawl.marking|keys|join('</code>&nbsp<code>')|raw }}</code>
```

Since I use `<code>` in the `join` I must add `|raw`.
But `<code>` is a static string, so it could be not escaped: Only pieces from `crawl.marking|keys` needs to be escaped.

I did not look at the twig code for a while, so I don't remember if it will be easy to achieve that.
If not, fell free to close the issue. Not a big deal.

**Comment by xabbuh** [comment]
To achieve this a filter must not only be able to declare that the result is always safe it must have the possibility to declare that the result is safe, but only when the input is already safe. This might become quite complex to implement/configure when the filter accepts several arguments.

**Comment by lyrixx** [comment]
Wep ! Let's close this
