### ISSUE TITLE
truncate filter fails with null string

### ISSUE THREAD

**Issue by garak** [twigphp/Twig#3250]
I found this change when upgrading from old Symfony 4 project with TextExtension to Symfony 5 (with extensions in Twig core and String component).

In old extension, you can use `truncate` filter with a null string, you simply get an empty string.
This is not working anymore with `u.truncate`, you get the following exception:
> Argument 1 passed to Twig\Extra\String\StringExtension::createUnicodeString() must be of the type string, null given

I'm not sure if the new behavior is on purpose. In case, it's fine to me, but it should be documented somewhere

**Comment by xabbuh** [comment]
`null` is not a string. So I'd say this is at least not completely unexpected.

**Comment by garak** [comment]
The point is the BC

**Comment by nicolas-grekas** [comment]
There is no BC applicable here as that's two different calls.
But I would personally have no issue always patching `null` to the empty string in the string-extra extension. PR welcome.
