### ISSUE TITLE
Twig can't access typed property with public access

### ISSUE THREAD

**Issue by treyssatvincent** [twigphp/Twig#3254]
If I want to display a typed property from a class in Twig it result in an error.

With a class with the following property :
``` php
public string $description;
```

``` php
{{  object.description }}
```

will result in the following error : 
https://github.com/twigphp/Twig/blob/76352a037db381fd688f0d3b81faf48fe74fdbd4/src/Extension/CoreExtension.php#L1513

But if the property is declared without typing :
``` php
public $description;
```

the same template will display the value of the property without throwing the RuntimeError

**Comment by fox34** [comment]
This does only affect uninitialized typed properties, which is also not possible in pure PHP.
PHP would raise the error _Typed property must not be accessed before initialization_.

**Comment by fabpot** [comment]
@fox34 IIUC, there is nothing to fix in Twig, right?

**Comment by fox34** [comment]
Yes. At most, the error message could be clarified for typed properties.

**Comment by JohJohan** [comment]
> Yes. At most, the error message could be clarified for typed properties.

@fox34 I would like to see a more clear error message when accessing a un-initialized typed property, should there be a issue created for this? Or should someone just pick that up?
