### ISSUE TITLE
Dependency on symfony/intl

### ISSUE THREAD

**Issue by enumag** [twigphp/Twig#3258]
I'm trying to update my project from Twig 2 to Twig 3. As required, instead of `twig/extensions` I'm trying to install `twig/intl-extra`.

I noticed however that `twig/intl-extra` has a dependency on `symfony/intl`. But the readme of `symfony/intl` says that it's just a replacement if I'm not using `ext-intl` - which I am using since I do need other than eng locale support. Because of that I added a conflict with `symfony/intl` to my project in the past to make sure it won't clash with `ext-intl`. But now `twig/intl-extra` is forcing me to install it anyway. Shouldn't this dependency be removed from twig to support other locales then english?

**Comment by jvasseur** [comment]
`symfony/intl` is more than just a replacement for `ext-int`, it provides access some localization data that isn't exposed by the C extension. It's that data that is used by `twig/intl-extra`.

You should'nt add a conflict with `symfony/intl`, the pollyfilling part of the package is automatically disabled when `ext-intl` is installed.

**Comment by enumag** [comment]
Hmm in that case maybe `symfony/intl` docs should be rewritten somehow. At the moment it suggests that using it together with `ext-intl` isn't a good idea.

**Comment by jvasseur** [comment]
The cleanest move would probably be to move the polyfill part of the intl component into https://github.com/symfony/polyfill/, the problem is doing it without breaking BC somewhere in the process.

**Comment by nicolas-grekas** [comment]
Can you please open a doc issue or PR @enumag?
@jvasseur that's extra work nobody is likely willing to spend time on...
