### ISSUE TITLE
On introducing the === operator

### ISSUE THREAD

**Issue by PrinsFrank** [twigphp/Twig#3261]
What is the reason currently the `===` operator is not available, and the `is same as()` is? I can't seem to find documentation about the reasoning behind it. Would you accept a pullrequest introducing it?

```
{% if foo.attribute is same as(false) %}{% endif %}
```

Could then be written as:
```
{% if foo.attribute === false %}{% endif %}
```
Which IMHO would much cleaner.

**Comment by fabpot** [comment]
It has been discussed more than once (in some issues and PRs). You should avoid using strict comparisons in Twig templates in the first place. Simplifying or encouraging its usage is not something I want to do.

**Comment by fabpot** [comment]
See #4736
