### ISSUE TITLE
Remove whitespace in expected result from integrationTestCase

### ISSUE THREAD

**Issue by Louzet** [twigphp/Twig#3270]
I recently created a new twig function, and during my test phase. I noticed a small bug.
**Whitespaces** are not correctly removed.

symfony version 5.0.99
twig version 3.0.3

```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing Project Test Suite
App\Tests\Service\Twig\TwigCustomFunctions
 ✘ Integration with data set #0
   │
   │ "dateInterval" function (in C:\Users\mickael-dev\Desktop\dev\open-source\symfony-reproducer\bug-integration-test-case\tests\Service\Twig\Fixtures\Filter\DateIntervalTest.test)
   │ Failed asserting that two strings are equal.
   │ --- Expected
   │ +++ Actual
   │ @@ @@
   │ -'\r\n
   │ -1'
   │ +'1'
   │
   │ C:\Users\mickael-dev\Desktop\dev\open-source\symfony-reproducer\bug-integration-test-case\vendor\twig\twig\src\Test\IntegrationTestCase.php:251
   │ C:\Users\mickael-dev\Desktop\dev\open-source\symfony-reproducer\bug-integration-test-case\vendor\twig\twig\src\Test\IntegrationTestCase.php:82
   │
Compiled templates that failed on case 1:
Template: index.twig
```

Reproducer : https://github.com/Louzet/bug-integration-test-case
Just clone and run tests (vendor/bin/simple-phpunit)

I already think I know how to fix, but i would like to be sure that this is a bug.

**Comment by stof** [comment]
Could it be related to the usage of CRLF newlines in your fixture file ?

**Comment by Louzet** [comment]
my fixture file looks like this:

```
--TEST--
"dateInterval" function
--TEMPLATE--
{{ dateInterval(dateIntervalSpec).format('%m') }}
--DATA--
return ['dateIntervalSpec' => '1 months']
--EXPECT--
1
```

Yes, it's come from CRLF new line, but i thought they were stripped before posting.
Here in Twig\test\IntegrationTestCase.php line 241 !
`$expected = trim($match[3], "\n ");`

if we remove '\n ' or add '\r ' to character_mask, my test pass correctly.

**Comment by fabpot** [comment]
Removing \r is the way to go.
