### ISSUE TITLE
PHP Notice: Undefined index when using a {% for in %} tag on an undefined variable which is shadowed in the loop

### ISSUE THREAD

**Issue by csnover** [twigphp/Twig#3272]
If the variable used for a `{% for item in seq %}` tag is not defined, and the `item` variable name shadows the `seq` variable name, Twig assumes the `seq` variable is defined and does not generate a guard in [this `$this->getNode('seq')` call](https://github.com/twigphp/Twig/blob/73f5ef259026a6b28f4a203ec096f491c8a94787/src/Node/ForNode.php#L46). Since the guard is what is responsible for throwing in strict mode, this also means that undefined variables will be allowed in strict mode in this case.

Reproduction:

Template:
```twig
{% for foo in foo %}{% endfor %}
```

Render call:
```php
$template->render([]);
```

This problem exists from at least version 1.42.2 through 3.0.3.

PHP 7.3.14.

**Comment by csnover** [comment]
This is caused by [optimize access to loop targets](https://github.com/twigphp/Twig/blob/73f5ef259026a6b28f4a203ec096f491c8a94787/src/NodeVisitor/OptimizerNodeVisitor.php#L148-L150).

1. Optimizer visits ForNode and adds loop target nodes to `$this->loopsTargets`;
2. Optimizer visits the `seq` sub-node, which is a `NameExpression` with a `name` attribute matching one in the array of `$this->loopsTargets`;
3. Optimizer incorrectly marks the `seq` node as always defined.

Optimizer needs to be aware of the `seq` node and explicitly exclude it from this optimisation. Something like this:

```diff
diff --git a/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php b/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php
index 9f7cae4d..c7094cb2 100644
--- a/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php
+++ b/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php
@@ -147,7 +147,10 @@ final class OptimizerNodeVisitor extends AbstractNodeVisitor
         }
 
         // optimize access to loop targets
-        elseif ($node instanceof NameExpression && \in_array($node->getAttribute('name'), $this->loopsTargets)) {
+        elseif ($node instanceof NameExpression
+            && $this->loops[0]->getNode('seq') !== $node
+            && \in_array($node->getAttribute('name'), $this->loopsTargets)
+        ) {
             $node->setAttribute('always_defined', true);
         }
 
```

**Comment by stof** [comment]
Optimizer should actually be aware of the `body` node of the loop. the loop target variable is guaranteed to be defined only in the body child node, not in all child nodes.

**Comment by csnover** [comment]
Yes, that certainly makes more sense. Thanks for your feedback! So I guess it would be more like this?:

```diff
diff --git a/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php b/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php
index 9f7cae4d..f5bf6c7c 100644
--- a/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php
+++ b/vendor/twig/twig/src/NodeVisitor/OptimizerNodeVisitor.php
@@ -131,11 +131,12 @@ final class OptimizerNodeVisitor extends AbstractNodeVisitor
             // disable the loop variable by default
             $node->setAttribute('with_loop', false);
             array_unshift($this->loops, $node);
-            array_unshift($this->loopsTargets, $node->getNode('value_target')->getAttribute('name'));
-            array_unshift($this->loopsTargets, $node->getNode('key_target')->getAttribute('name'));
         } elseif (!$this->loops) {
             // we are outside a loop
             return;
+        } elseif ($node === $this->loops[0]->getNode('body')) {
+            array_unshift($this->loopsTargets, $this->loops[0]->getNode('value_target')->getAttribute('name'));
+            array_unshift($this->loopsTargets, $this->loops[0]->getNode('key_target')->getAttribute('name'));
         }
 
         // when do we need to add the loop variable back?
@@ -193,6 +194,7 @@ final class OptimizerNodeVisitor extends AbstractNodeVisitor
     {
         if ($node instanceof ForNode) {
             array_shift($this->loops);
+        } elseif ($this->loops && $this->loops[0]->getNode('body') === $node) {
             array_shift($this->loopsTargets);
             array_shift($this->loopsTargets);
         }
```
```

**Comment by csnover** [comment]
Sorry for not doing this as a PR, I am ignorant of Twig and wasn’t expecting to actually make a working solution. I will open a PR if you want, or leave this here for you to take care of, just let me know what you prefer.

**Comment by fabpot** [comment]
@csnover Can you open a PR? That would make review easier I suppose.
