### ISSUE TITLE
Old PHP 7.0 errors

### ISSUE THREAD

**Issue by dyanakiev** [twigphp/Twig#3279]
Hello,
Unfortunately on one of my hosting accounts is still on php 7.0 and with twig v3.0.3 i get the following error:
```
An uncaught Exception was encountered
Type: TypeError

Message: Return value of Twig\Loader\FilesystemLoader::addPath() must be an instance of Twig\Loader\void, none returned

Filename: /vendor/twig/twig/src/Loader/FilesystemLoader.php

Line Number: 96
```
Is this comptability issue with php 7.0?

I dont have this error on php 7.3/7.4 not tested 7.2.

**Comment by stof** [comment]
Version 3 of Twig requires PHP 7.2+, as described in the composer requirement. If you are deploying to PHP 7.0, you will need to stick to Twig 2 (if you run `composer update` on a PHP 7.0 runtime or with `config.platform.php` set to `7.0`, it will do that automatically).

**Comment by EtienneSultan** [comment]
@stof I have the exact same error running php 7.4.3 with twig 3.0.3

**Comment by xabbuh** [comment]
@EtienneSultan You won't see this error on PHP 7.4. I'd rather guess that the PHP version used on the CLI differs from the one used when your application is accessed through HTTP.

**Comment by EtienneSultan** [comment]
You are absolutely right, clumsy me !
