### ISSUE TITLE
How to include JSON LD Markup in Twig Template?

### ISSUE THREAD

**Issue by andjelboskovic** [twigphp/Twig#3285]
After some time researching, I couldn't find the answer nether in the documentation or elsewhere online.

I've added to a jsonTemplate.twig file:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "EventReservation",
  "reservationNumber": "E123456789",
  "reservationStatus": "http://schema.org/Confirmed",
  "underName": {
    "@type": "Person",
    "name": "John Smith"
  },
  "reservationFor": {
    "@type": "Event",
    "name": "Foo Fighters Concert",
    "startDate": "2027-03-06T19:30:00-08:00",
    "location": {
      "@type": "Place",
      "name": "AT&T Park",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "24 Willie Mays Plaza",
        "addressLocality": "San Francisco",
        "addressRegion": "CA",
        "postalCode": "94107",
        "addressCountry": "US"
      }
    }
  }
}
</script>
```

and included with
`{% include 'path/to/jsonTemplate.twig' %}`

but the template is not loaded. Is there a special way to include the script with JSON into twig?

[In this post](https://stackoverflow.com/questions/53856206/twig-template-adds-json-ld-duplicate) it looks like a regular usage but for some reason, it doesn't work in my case.

Thank you in advance for helping out

**Comment by stof** [comment]
Without details about what `the template is not loaded` means (do you get an error ?), there is nothing we can do for you. https://twigfiddle.com/644aol is the proof that this works.

Twig does not care about the content of your template (outside the Twig markup which is wrapped in `{% %}`, `{{ }}` or `{# #}`). So including a template containing some JSON-LD is not different from including a template including some HTML.

**Comment by andjelboskovic** [comment]
Thanks @stof, this is all I needed. I'll investigate further
