### ISSUE TITLE
Twig doesn't show error, just blank screen

### ISSUE THREAD

**Issue by Jiri-Mihal** [twigphp/Twig#3293]
Hi,

Twig shows only blank screen when Twig syntax in template is wrong. Is there way to enable displaying this kind of errors?

An example:

Error settings:
```php
ini_set('log_errors', '0');
ini_set('display_startup_errors', '1');
ini_set('display_errors', '1');
ini_set('error_reporting', (string)E_ALL);
```

Environment:
```php
$env = new \Twig\Environment($loader, array(
'cache' => false,
'debug' => true,
));
```

Template with error:
```twig
{% iff %}Hello World!{%endif %}
```

Rendering the template:
```php
echo $twig->render('template.twig');
```

**Comment by stof** [comment]
Twig will throw an exception when something goes wrong. How exceptions are rendered in your PHP script is out of the scope of Twig.

**Comment by Jiri-Mihal** [comment]
@stof How can I catch exceptions thrown by Twig? The following code doesn't catch anything.

```php
try {
    echo $twig->render('template.twig');
} catch (\Exception $e) {
    echo $e->getMessage();
}
```

**Comment by fabpot** [comment]
Your snippet is exactly what you should do. If that does not work, then, it probably means that there is something wrong in your own code/framework.
