### ISSUE TITLE
Inconsistencies in declared types

### ISSUE THREAD

**Issue by phansys** [twigphp/Twig#3294]
Trying to allow version 3 in a project which already supports version 2, I've found some issues derived from inconsistent type declarations.
I think this situation is currently hidden here, because `strict_types` declaration is not enabled.
By instance, in `MacroTokenParser::__construct()` a new instance of `BodyNode` (which extends from `Node` without overriding any method) is created, and the array passed as argument 1 has the integer `0` as implicit name for its first element:
https://github.com/twigphp/Twig/blob/6384ba6c3ca7695ef0aec93bdf3b55c9bb18b5de/src/TokenParser/MacroTokenParser.php#L50
Since `Node::__construct()` has no check against the types used as array indexes, the concept of "named nodes" is easily violated:
https://github.com/twigphp/Twig/blob/6384ba6c3ca7695ef0aec93bdf3b55c9bb18b5de/src/Node/Node.php#L33-L50
Later, all the methods involved with the node's manipulation are declared with "string" as the only possible type for its names:
https://github.com/twigphp/Twig/blob/6384ba6c3ca7695ef0aec93bdf3b55c9bb18b5de/src/Node/Node.php#L124-L146
Finally, tests are passing integers when calling `Node::getNode()`:
https://github.com/twigphp/Twig/blob/6384ba6c3ca7695ef0aec93bdf3b55c9bb18b5de/tests/ExpressionParserTest.php#L67
https://github.com/twigphp/Twig/blob/6384ba6c3ca7695ef0aec93bdf3b55c9bb18b5de/tests/Node/ForTest.php#L36
https://github.com/twigphp/Twig/blob/6384ba6c3ca7695ef0aec93bdf3b55c9bb18b5de/tests/NodeVisitor/OptimizerTest.php#L43

Is this situation on purpose or there is a plan to fix it?

**Comment by greg0ire** [comment]
So to be clear, what happens right now? Because of `strict_types`, you get an error when using `getNode` with `0`, and without, you an exception because it was registered as an integer and it's being coerced as a string?

**Comment by phansys** [comment]
>So to be clear, what happens right now? Because of strict_types, you get an error when using getNode with 0

Yes. As expected, I get the exception `\TypeError` with `strict_types=1` and no error without that declaration.

**Comment by stof** [comment]
With `strict_types=1` applied where ?

**Comment by phansys** [comment]
With `strict_types=1` applied in the file where the call to `Node::getNode()` is made [[ref](
https://github.com/sonata-project/twig-extensions/blob/c88c18236735b5560258f6ec4cc27354c8381d5e/tests/TokenParser/DeprecatedTemplateTokenParserTest.php#L3)].

**Comment by stof** [comment]
Then make it `getNode('0')` in your file rather than relying on the implicit casting.

**Comment by phansys** [comment]
Thank you!
TBH, passing an integer as a string seems more like a workaround.
But if this is the best way to deal with this scenario at this moment, please feel free to close the issue.
