### ISSUE TITLE
Consider renaming Twig filters into something more appropriate 

### ISSUE THREAD

**Issue by Chi-teck** [twigphp/Twig#3298]
I think "filter" term is misused. A filter is something that filters out incoming input but Twig filters are more than that. They may change the incoming data and even create new data. I suppose they are more like converters or transformers.

**Comment by fabpot** [comment]
A filter should not change the input and should never create new data.
In any case, we won't change the name now as it would be a major BC break.
The term filter is also used in many other Twig-like templating system in other languages,

**Comment by Chi-teck** [comment]
> A filter should not change the input

Well, most of core Twig filters do change the input. Technically filters like `html_to_markdown`  are converters not filters. And filters like `default` do create new data.
Anyway I agree changing the name without BC break would be really hard.
