### ISSUE TITLE
Using u filter with apply tag

### ISSUE THREAD

**Issue by chas-mafli** [twigphp/Twig#3299]
I get a syntax error when I try to use `{% apply u.wordwrap(80) %}`. Works fine with `{{ text|u.wordwrap(80) }}` but with the apply tag I get a `"Unexpected token "punctuation" of value "." ("end of statement block" expected).` error.

Don't know if it's just a doc error (https://twig.symfony.com/doc/3.x/filters/u.html) but I can't figure out what you're supposed to do if that's the case.

**Comment by stof** [comment]
The filter is `u`, not `u.wordwrap`. `.wordwrap(80)` is a method call on the return value of the filter.

**Comment by chas-mafli** [comment]
@stof Yeah sure makes sense but the documentation says otherwise

**Comment by stof** [comment]
hmm, there is indeed a mistake in the doc here

**Comment by nicolas-grekas** [comment]
would it make sense / be possible to support these with apply?

**Comment by stof** [comment]
Well, this would require it to support not only a filter list, but also expressions on the output of the filter. I'm not sure how this would work.
@fabpot what do you think ?
