### ISSUE TITLE
FR: |first and |last filters should support arrow functions

### ISSUE THREAD

**Issue by brandonkelly** [twigphp/Twig#3303]
It would be helpful if it was possible to pass an arrow function into the `|first` and `|last` filters , which would result in the first/last element where the arrow function returns `true` (or any non-empty value) being returned.

So this:

```twig
{% set item = items|filter(x => x.featured)|first %}
```

Could be simplified to:

```twig
{% set item = items|first(x => x.featured) %}
```

In addition to being a bit simpler syntax, this would also improve performance as the arrow function would only need to be run up until a non-empty value is returned, rather than for all items in the array.

**Comment by stof** [comment]
I see no benefit for `|last`: it would still have to apply the filter on the whole array to find the last matching item, making it exactly the same than `|filter(x => x.featured)|last`

**Comment by apfelbox** [comment]
In `|last` your arrow function could start from the end and move to the beginning?

**Comment by brandonkelly** [comment]
Right – the array could be traversed in reverse order for better performance. It would be awkward to add arrow function support to `|first` but not `|last`.

**Comment by stof** [comment]
iteration in Twig works with iterators too, not only arrays.

**Comment by apfelbox** [comment]
Then we can add an optimization for some code paths, and don't do it for others? I understand the general point, but this one is really simple to optimize for a lot of paths?

And the unoptimized path is the same as now, so... I don't see the downside.

**Comment by jvasseur** [comment]
I personally find the `|filter|first` clearer. Maybe we could simply optimize the case when those two filters are use consecutively without introducing an new option in the `first` filter (it would be strange to have the `first` filter support it and not the `last`).

**Comment by fabpot** [comment]
I prefer composition as well.
