### ISSUE TITLE
twig issue

### ISSUE THREAD

**Issue by bg2k** [twigphp/Twig#3306]
Uncaught PHP Exception Twig\\Error\\SyntaxError: "Unexpected token "operator" of value "%" in "__string_template__736f26fa7de6aa9a47985e5a1d2ffa1760d3ee47dd4b70367e725e748025a0c2" at line 1." at /home/xxx/public_html/vendor/twig/twig/src/ExpressionParser.php line 295

Twig V: 1.42.3 (2019-08-24)

**Comment by stof** [comment]
Well, you have a string template (using either `$environment->createTemplate()` in PHP or `template_from_string()` in Twig) containing an invalid syntax. That's not a bug in Twig, but an issue in your project.
And without seeing the content of that string, there is nothing we can do to help anyway.
