### ISSUE TITLE
[intl-extra] Japanese date format issue

### ISSUE THREAD

**Issue by sylvaindeloux** [twigphp/Twig#3310]
When using `format_datetime` on a DateTime object with `$locale` parameter set to `ja` (Japanese) the result does not comply with Japanese date format.

Result:

    2020/04/05 13:40:26

Expected result:

    2020年04月05日 13:40:26

**Comment by stof** [comment]
Do you have the PHP intl extension installed ? If no, that's expected as the polyfill implements the English format only.

**Comment by sylvaindeloux** [comment]
Ok, my bad, I've just found the problem (intl is present) :

`{{ my_DateTime_object|format_datetime }}` will return `2020/04/05 13:40:26`
`{{ my_DateTime_object|format_datetime('full') }}` will return `2020年4月5日日曜日 13:40:26`
