### ISSUE TITLE
How to limit the active position of the tag?

### ISSUE THREAD

**Issue by CatAnonymous** [twigphp/Twig#3312]
I have tag {% mycustomtag %}
I want it to be used only inside of If and For, if used outside it will report a Systax error.  Is there any way to deal with Token Parser?

**Comment by stof** [comment]
I don't think the TokenParser can do it, as it is not aware of the full context. I think you will need to use a NodeVisitor to apply such check after the parsing.

**Comment by CatAnonymous** [comment]
> I don't think the TokenParser can do it, as it is not aware of the full context. I think you will need to use a NodeVisitor to apply such check after the parsing.

I did not find the document for NodeVisitor

**Comment by stof** [comment]
I don't think the doc describes them. Look in the source code for examples.

**Comment by CatAnonymous** [comment]
> I don't think the doc describes them. Look in the source code for examples.

seems to have to interfere with the twig core

**Comment by CatAnonymous** [comment]
> I don't think the doc describes them. Look in the source code for examples.

I see FOR tag creates the context _seq _key and _parent is there any way to capture the context in Token Parser?

**Comment by stof** [comment]
Well, I don't understand what you are asking for.

**Comment by CatAnonymous** [comment]
$context contains variables of Twig

**Comment by CatAnonymous** [comment]
I want to capture variables created by FOR loop (_parent, _seq, _key) in {% mycustomtag %} TokenParser

**Comment by fabpot** [comment]
Have a look at the existing `NodeVisitor` classes. You can capture the context there as all nodes are visited from the top one named `ModuleNode`.
