### ISSUE TITLE
Operator issue "="

### ISSUE THREAD

**Issue by CatAnonymous** [twigphp/Twig#3313]
Operator "=" is equivalent to the tag {% set%}.  If you don't want to use it right from the first Twig version, why create an "==" Operator like PHP?

**Comment by stof** [comment]
I don't understand what you mean.

**Comment by CatAnonymous** [comment]
> I don't understand what you mean.

Example:
{% if a == b %} should be {% if a = b %}

**Comment by fabpot** [comment]
For consistency with other languages, including PHP. Not something that can be changed anyway now.
