### ISSUE TITLE
 throwable throws in Twig 1.x

### ISSUE THREAD

**Issue by hansbogert** [twigphp/Twig#3317]
There are references to Throwable (only valid in Php 7) in the 1.x branch whereas 1.x should be compatible with php 5.6 (right?)

Static analysis fails on these files:

https://github.com/twigphp/Twig/blob/1.x/src/TemplateWrapper.php#L117
https://github.com/twigphp/Twig/blob/1.x/src/Template.php#L446

**Comment by fabpot** [comment]
That's perfectly valid code. Do you have any real-world issue? If the class does not exist in some PHP version, then the catch block is never reached. I don't see any issues here, but I might be missing something.

**Comment by stof** [comment]
non-existent classes are perfectly fine in `catch` clauses (just like in `instanceof` checks)
