### ISSUE TITLE
Why twig negative (not) conditional works like this?

### ISSUE THREAD

**Issue by thlbaut** [twigphp/Twig#3318]
I don't understand why Twig `not` is working like this : 

```
{{ dump( false ) }}
{{ dump( not(false) ) }}

{{ dump ( date1.timestamp > date2.timestamp ) }}
{{ dump ( not(date1.timestamp > date2.timestamp) ) }}

{% set comp = date1.timestamp > date2.timestamp %}
{{ dump ( comp ) }}
{{ dump ( not(comp) ) }}
```

Result : 

```
false
true

false
false

false
true
```

https://twigfiddle.com/udjjti/2

Thank's for your help :)

**Comment by thlbaut** [comment]
It seems that this behaviour was introduced with version 3 of twig

**Comment by stof** [comment]
I guess this is a bug in the compiled code, due to the PHP precedence of `!` vs `===` (see https://3v4l.org/VbWHX)

**Comment by fabpot** [comment]
Anyone willing to work on a PR to fix this bug?
