### ISSUE TITLE
Error : Class 'Twig_Environment' not found ^3.0

### ISSUE THREAD

**Issue by Rouret** [twigphp/Twig#3319]
Hello, I am working on a project with Silex and Twig. So I followed the [Silex documentation](https://silex.symfony.com/doc/2.0/providers/twig.html) to use twig, but when I enter the url I get this error:

> PHP Fatal error:  Uncaught Error: Class 'Twig_Environment' not found 

here are the commands:

> $ composer require silex/silex "^2.0"
> $ composer require twig/twig

composer.json:
`
{
    "require": {
        "silex/silex": "^2.0",
        "twig/twig": "^3.0"
    }
}
`

app.php:
`<?php
require_once './vendor/autoload.php';

$app = new Silex\Application();
$app->register(new Silex\Provider\TwigServiceProvider(), array(
    'twig.path' => __DIR__.'/views',
));
$app->get('/hello/{name}', function ($name) use ($app) {
    return $app['twig']->render('hello.twig', array(
        'name' => $name,
    ));
});

$app->run();
?>`

views/hello.twig :
`{{ name }}`

**Comment by xabbuh** [comment]
Since Twig 2.7 using the non-namespaced classes is deprecated (they don't exist anymore in 3.0). You should now use the `Twig\Environment` class instead.

**Comment by Rouret** [comment]
Thanks you, it works for me :
`{
    "require": {
        "silex/silex": "^2.0",
        "twig/twig": "^2.7"
    }
}
`

**Comment by brandon8696** [comment]
> Since Twig 2.7 using the non-namespaced classes is deprecated (they don't exist anymore in 3.0). You should now use the `Twig\Environment` class instead.

I know this is an old thread, but could you help me format a depreciated php file to properly use the class? 

`$twig = new Twig_Environment($loader, array(
		    'cache' => false
		));`

This is currently throwing out the same error, and I'm not sure how to fix it properly.

**Comment by xabbuh** [comment]
`$twig = new \Twig\Environment($loader, array( 'cache' => false ));`
