### ISSUE TITLE
Use Slugger in Twig

### ISSUE THREAD

**Issue by seb-jean** [twigphp/Twig#3320]
Hi,
It would be great to be able to use Slugger (AsciiSlugger) in twig.
Thanks :)

**Comment by fabpot** [comment]
Is there any use cases for creating a slug in a template?

**Comment by seb-jean** [comment]
When generating URLs.

**Comment by mmarton** [comment]
If I remember correctly I needed this to create anchors in a long category->product list months ago... But I have no idea why I needed to create the slug in the template...

**Comment by fabpot** [comment]
I do understand this is for URLs, but I fail to see when that's useful. If you are using a URL generator, the slugifi-cation is probably done elsewhere. My question is when do you need this **in a template**.

**Comment by mmarton** [comment]
I wasn't needed to generate routes, I just needed url friendly strings for `<h1 name="slugged-string-from-name"> ... <a href="#slugged-string-from-name">`

**Comment by fabpot** [comment]
@mmarton  That's indeed a great use case, my last comment was more about @seb-jean comment :)

**Comment by fabpot** [comment]
Anyone willing to create a PR to add this feature?

**Comment by seb-jean** [comment]
I created a PR :wink:

**Comment by fabpot** [comment]
Closing as there is a PR now. Discussion should happen there now.
