### ISSUE TITLE
Call to undefined function Twig\\json_encode() in 

### ISSUE THREAD

**Issue by williamdes** [twigphp/Twig#3335]
```
Call to undefined function Twig\\json_encode() in 
vendor/twig/twig/src/ExtensionSet.php:116\nStack trace:\n#0 
vendor/twig/twig/src/Environment.php(984): Twig\\ExtensionSet->getSignature()\n#1 
vendor/twig/twig/src/Environment.php(703): Twig\\Environment->updateOptionsHash()\n#2 
vendor/twig/twig/src/Environment.php(128): Twig\\Environment->addExtension(Object(Twig\\Extension\\CoreExtension))\n#3 
libraries/classes/Template.php(72): Twig\\Environment->__construct(Object(Twig\\Loader\\FilesystemLoader), Array)\n#4 
libraries/classes/Core.php(299): PhpMyAdmin\\Template->__construct()\n#5 
libraries/classes/Core.php(376): PhpMyAdmin\\Core::fatalError('The [a@./url.ph...')\n#6 
librari in 
vendor/twig/twig/src/ExtensionSet.php on line 116
```

I am starting with a very minimal alpine with apache and I am adding extensions by extensions for some issues reproducing reasons.

Yes: wrong repo but you did not define a way or an URL to report bugs ..
```
Call to undefined function Symfony\\Polyfill\\Mbstring\\iconv_strpos() in 
vendor/symfony/polyfill-mbstring/Mbstring.php:501\nStack trace:\n#0 
vendor/symfony/polyfill-mbstring/bootstrap.php(60): Symfony\\Polyfill\\Mbstring\\Mbstring::mb_strpos('&', ';', 0, 'UTF-8')\n#1 
libraries/classes/Url.php(257): mb_strpos('&', ';')\n#2 
libraries/classes/Url.php(208): PhpMyAdmin\\Url::getArgSeparator()\n#3 
libraries/classes/Url.php(171): PhpMyAdmin\\Url::getCommonRaw(Array, '?')\n#4 
libraries/classes/Core.php(765): PhpMyAdmin\\Url::getCommon(Array)\n#5 
libraries/classes/Core.php(338): PhpMyAdmin\\Core::linkURL('https://secure....')\n#6 
libraries/classes/Core.php(367): PhpMyAdmin\\Core::ge in 
vendor/symfony/polyfill-mbstring/Mbstring.php on line 501
```

feel free to say you will not fix this 2 errors (yes they are missing extensions and so false positives ;)), I will understand.
I am still reporting it.

**Comment by stof** [comment]
You need the json extension (btw, you will have a hard time doing anything useful without supporting json. PHP 8 will even forbid disabling it).

then, you need to install either `ext-mbstring` or `ext-iconv` or `symfony/polyfill-iconv`.
Twig installs the mbstring polyfill by default, which uses iconv, but we don't install the iconv polyfill automatically, due to its size (it bundles all data about each encoding).
Note that for performance, I suggest you to install the extensions rather than relying on the polyfills.

**Comment by williamdes** [comment]
https://github.com/twigphp/Twig/commit/f0ccbfc2fdf2f7be5b03709ac0794ac7e143a424
https://github.com/twigphp/Twig/commit/158a8530c5865b319fcfe1c2ddcc31131e8efce1

Where checks added for iconv by @fabpot 
I understand that not all functions can be safe guarded by such checks

**Comment by stof** [comment]
yeah, that's for direct usages of `iconv`. The `symfony/polyfill-mbstring` package does not have similar checks.

**Comment by MACnus** [comment]
I also have the same problem, and I know I have json installed I use it all the time. What might error be?
Thanks!
