### ISSUE TITLE
[intl-extra] Issue with format_currency

### ISSUE THREAD

**Issue by Caucorico** [twigphp/Twig#3347]
When using `format_currency` on an int object with any $locale parameter, the result does not have the right number of digits.
My line is copied from the documentation :  (https://twig.symfony.com/doc/3.x/filters/format_number.html)

Code :
```twig
3500|format_currency('EUR', {fraction_digit: 4})
```
Expected result : 
`€3,500.0000`

Result :
`€3,500.00`

The twig extensions :
```
twig/intl-extra                     v3.0.3             A Twig extension for Intl
twig/twig                           v2.12.5            Twig, the flexible, fast, and secure template language for PHP
```

**Comment by stof** [comment]
@Caucorico your link is broken, as the url of the link is `url`. When adding a link on an issue, either paste the link without any special markup, or fill the markdown markup properly.

**Comment by Caucorico** [comment]
@stof ok, I edited the link.

**Comment by stof** [comment]
IIRC, for the currency formatting, the number of fraction digits is controlled by the rules of that currency.

**Comment by Caucorico** [comment]
So the intended behavior is to use the default currency formatting and ignore this parameter ?

**Comment by stof** [comment]
Well, these filters are about exposing features from PHP's `NumberFormatter` class. We won't reimplement the formatting logic.

**Comment by fabpot** [comment]
This is a bug on old versions of intl/icu.
