### ISSUE TITLE
Sandbox is not working if used in conjunction with {{ include(template_from_string()) }}

### ISSUE THREAD

**Issue by Warxcell** [twigphp/Twig#3350]
I added test for that: https://github.com/twigphp/Twig/pull/3349

**Comment by Warxcell** [comment]
@stof do you have any clues for this?

**Comment by stof** [comment]
no. This requires some investigation to debug why the test does not fail.

**Comment by Warxcell** [comment]
@stof the test does not fail, because it doesn't exists. I created one - and it fails. It's here: https://github.com/twigphp/Twig/pull/3349

**Comment by stof** [comment]
I meant "why the test does fail"

**Comment by Warxcell** [comment]
Tried to dig in - as far as I see -  `Twig\NodeVisitor\SandboxNodeVisitor::enterNode` does not receive used filters. Any idea where to continue digging?
