### ISSUE TITLE
Sandbox is not disabled if syntax error occurs within {% sandbox %} tag

### ISSUE THREAD

**Issue by Warxcell** [twigphp/Twig#3351]
I added test for that: https://github.com/twigphp/Twig/pull/3348

**Comment by stof** [comment]
We probably need to add some `try/finally` in the compiled code of the `{% sandbox %}` tag...

**Comment by Warxcell** [comment]
@stof I can try that, if you point me the location where that happens. :)

**Comment by stof** [comment]
It happens in SandboxNode

**Comment by Warxcell** [comment]
@stof yes, it's ok like that. I will push actual code to same PR. :)
