### ISSUE TITLE
replace fails to replace strings that start with * (splat)

### ISSUE THREAD

**Issue by redreinard** [twigphp/Twig#3356]
twig seems to refuse to replace strings that start with a splat if they are in a variable.
Example to reproduce:

```
{% set test = '*' %}
{% set source = '* string that starts with star' %}
test:#{{ test }}#
source:#{{ source }}#
replace-fail:#{{ source|replace({test: ''}) }}#
what-should-happen:#{{ source|replace({'*': ''}) }}#
```
output:
```
test:#*#
source:#* string that starts with star#
replace-fail:#* string that starts with star#
what-should-happen:# string that starts with star#
```

expected output:
```
test:#*#
source:#* string that starts with star#
replace-fail:# string that starts with star#
what-should-happen:# string that starts with star#
```

(missing splat on the replace-fail line)

Twig 3.0.3

**Comment by xabbuh** [comment]
Using a variable as a key name in a hash does not work as you expect it here. You need to enclose it with parentheses like this (see also https://twigfiddle.com/dn2sv1 and https://twig.symfony.com/doc/3.x/templates.html#literals):

```twig
{{ source|replace({(test): ''}) }}
```

**Comment by redreinard** [comment]
Thanks for that. Could you elaborate a little on why this is the case? I'd be happy to create a pull request for adding a sample about this to the documentation. I feel that's a rather big gotcha.

Edit: I see it's mentioned in the documentation here..
https://twig.symfony.com/doc/3.x/templates.html#literals
TIL i guess. i still think it could be mentioned in a couple other places in the docs maybe.
