### ISSUE TITLE
backslashes in single-quoted strings are lost

### ISSUE THREAD

**Issue by olets** [twigphp/Twig#3360]
I find this unexpected:

```twig
{% set str = '\-' %}
{{ str }}
```

Actual output: `-`
Output I expect: `\-`

This too:

```twig
{% set str = '\' %}
```

Actual output: `Unexpected character "'".`
Output I expect: `\`

This came up in a case where a string not in the developer's control includes `+\-`. Because the `\` is treated as if it escaping the following character we have to `{{ str|replace({'+-': '+\\-'}) }}` which is brittle, for example given the string `+- +\-'.

I expect this escaping inside double quotes ( `{% set str = "\-" %}` ) but not inside single quotes or when the string is coming from a data source outside of the templates.

Is this intentional? Would a behavior change be considered?

**Comment by stof** [comment]
backslashes **must** be escaped in Twig strings.

**Comment by olets** [comment]
Yup, which means single backslashes in arbitrary strings (such as coming from a CMS) will always be lost. Training content editors on what escaping is and that backslashes must be escaped is a workaround in some scenarios.

**Comment by xabbuh** [comment]
Well, in your CMS you probably don't let your editors write Twig templates, right? In that case this will work as expected (see https://twigfiddle.com/czcvs4 for example).

**Comment by olets** [comment]
The YAML twigfiddle works because YAML escapes backslashes.

YAML
```yaml
str: \
```
is JSON
```json
{
  "str": "\\"
}
```

**Comment by xabbuh** [comment]
That doesn't matter. What is important is how or what string is passed to Twig. If the user of your CMS enters a backslash in a text field and you store it as such you can simply forward it to Twig using PHP without having to do anything else. Only if you hardcode it in your template, you need to take of escaping it properly.
