### ISSUE TITLE
Allow trailing commas

### ISSUE THREAD

**Issue by apfelbox** [twigphp/Twig#3362]
After PHP now allows trailing commas nearly everywhere...

see
* https://wiki.php.net/rfc/trailing-comma-function-calls
* https://wiki.php.net/rfc/trailing_comma_in_closure_use_list
* ...

it would be great if Twig would allow them as well.
The typical pro arguments apply (just like in the cases of PHP itself).

Example: https://twigfiddle.com/tufnb6

It would be great if this could be added for all calls, like functions, filters, macros, .. as well as array / map definitions, etc...

**Comment by stof** [comment]
array and map definitions already support trailing commas

**Comment by fabpot** [comment]
Sounds like a good idea. Would you want to work on a PR?

**Comment by apfelbox** [comment]
@fabpot I will give it a try!

**Comment by apfelbox** [comment]
PR implementation in #3363
