### ISSUE TITLE
Twig v2.13.0 b/c break - An opened parenthesis is not properly closed

### ISSUE THREAD

**Issue by PhilETaylor** [twigphp/Twig#3364]
Sorry to be late to the party.

I have just `composer update` and received v2.13.0

The update broke my code rendering a twig template that works before the update (with v2.12.5)

Im uncertain what the b/c promise is when it comes for Twig :) I could not find it documented. 

On debugging, I get to the commit 5663351a49f5ad49778dd9a4cbf30a6d7b29f429 which seems to have broken my otherwise working code.

The comment above that commit makes it clear 

> an operator that begins with a character must have a space before

and although my code DID NOT HAVE a space before the operator `and` it *did* work prior to 5663351 with v2.12.5

The if statement I have looks valid (and worked) (Albeit not the prettiest example of my work)

```twig
 {% if (row.developeremail != '' and 'No de' not in row.developeremail) or (row.developerurl != ''and 'No de' not in row.developerurl) %}                                 
```

And the error message is 

> An opened parenthesis is not properly closed. Unexpected token "name" of value "and" ("punctuation" expected with value ")").

**I understand that the problem is that the second `and` doesnt have a space before it** (and a quick fix for me was to add a space), but that was valid syntax and worked before 5663351a49f5ad49778dd9a4cbf30a6d7b29f429 :) 

If you are happy then I'm happy lets just close this. I just wanted to note it here incase this was a b/c break someone else hits.

**Comment by PhilETaylor** [comment]
Another one/example  - no space before `or` was ok and valid and working before https://github.com/twigphp/Twig/commit/5663351a49f5ad49778dd9a4cbf30a6d7b29f429 but not after

`{% elseif payment.txnType == 'recurring_payment'or payment.txnType == 'subscr_payment' %}`

**Comment by fabpot** [comment]
@PhilETaylor Can you check that #3365 fixes your issue?

**Comment by PhilETaylor** [comment]
Hey @fabpot I can confirm that #3365 fixes the regression, although I appreciate that my code is ultimately at fault for being badly written :)

**Comment by PhilETaylor** [comment]
Tested again after your `force push` change - still working fine :)
