### ISSUE TITLE
Anchors to Symfony "Twig reference" documentation are not working

### ISSUE THREAD

**Issue by fancyweb** [twigphp/Twig#3366]
On https://twig.symfony.com/doc/2.x/ and https://twig.symfony.com/doc/3.x/, the links to the Symfony documentation have invalid anchors (`_` needs to replaces with `-`).

Also some anchors does not exist at all, the page it redirects to is wrong (eg: https://twig.symfony.com/doc/2.x/tests/rootform.html redirects to https://symfony.com/doc/current/reference/twig_reference.html#rootform instead of https://symfony.com/doc/current/form/form_customization.html#form-twig-rootform).

**Comment by fabpot** [comment]
I've fixed the first issue for now.
For forms, I have a global strategy right now but that does not work well, I think I need to hardcode the anchor instead.

**Comment by fabpot** [comment]
Should be fixed now.
