### ISSUE TITLE
Does Parameter for String Need to Be Added?

### ISSUE THREAD

**Issue by ma077146** [twigphp/Twig#3368]
https://github.com/twigphp/Twig/blob/57ca24c5f3a079aced47dc1b8688ee5752367f15/src/RuntimeLoader/RuntimeLoaderInterface.php#L23

This is an incredibly small thing.  PHPStorm does not like that there is no parameter argument for $class.

Would it be worth adding "@param string $class" to the comment block?  If so, I will be more than happy to do a PR.

Thank you,

Mark

**Comment by xabbuh** [comment]
PhpStorm is able to derive the required type from the argument type hint. Could this be related to your config?

**Comment by ma077146** [comment]
I agree on deriving the required type.  This is an inspection for docblock that is squawking.

As I said, it's very minor, I just mentioned it in case it needs to be addressed for conformation to commenting standards.

**Comment by fabpot** [comment]
Let's close then.

**Comment by stof** [comment]
The documentation standard of Twig is to avoid unnecessary phpdoc. When the phpdoc does not provide any extra value compared to the type hint, the type hint is considered enough.
