### ISSUE TITLE
`inline_css` filter shouldn't insert line breaks

### ISSUE THREAD

**Issue by pgorod** [twigphp/Twig#3370]
Hi

I am having a problem with line-breaks. Using Twig 3.0 with CssInlinerExtension.

Compare the two following outputs. 

```html
{% apply spaceless %}
<table>
<thead>
    <tr>
        <th>Name</th><th>Value</th>
    </tr>
</thead>
<tbody>
    {% for letter in 'a'..'c' %}
        <tr>
            <td>{{ letter }}</td>
            <td>{{ letter }}</td>
        </tr>
    {% endfor %}
</tbody>
</table>
{%- endapply -%}
```

This will produce a **correct** 😄 output:

```html
<table><thead><tr><th>Name</th><th>Value</th></tr></thead><tbody><tr><td>a</td><td>a</td></tr><tr><td>b</td><td>b</td></tr><tr><td>c</td><td>c</td></tr></tbody></table>
```
The `spaceless` filter did its job and I don't have any line breaks.

But now I need to use inline CSS to send this in an email. So I add that to the template:

```html
{%- apply inline_css(source("mycss")) -%}
{% apply spaceless %}
<table>
<thead>
    <tr>
        <th>Name</th><th>Value</th>
    </tr>
</thead>
<tbody>
    {% for letter in 'a'..'c' %}
        <tr>
            <td>{{ letter }}</td>
            <td>{{ letter }}</td>
        </tr>
    {% endfor %}
</tbody>
</table>
{%- endapply -%}
{%- endapply -%}
```
This will produce an **incorrect** 😢 output:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><table style="border: solid 1px #DDEEEE; border-collapse: collapse; border-spacing: 0; font: normal 13px Arial, sans-serif;">
<thead><tr>
<th style="background-color: #DDEFEF; border: solid 1px #DDEEEE; color: #336B6B; padding: 10px; text-align: left; text-shadow: 1px 1px 1px #fff;">Name</th>
<th style="background-color: #DDEFEF; border: solid 1px #DDEEEE; color: #336B6B; padding: 10px; text-align: left; text-shadow: 1px 1px 1px #fff;">Value</th>
</tr></thead>
<tbody>
<tr>
<td style="border: solid 1px #DDEEEE; color: #333; padding: 10px; text-shadow: 1px 1px 1px #fff;">a</td>
<td style="border: solid 1px #DDEEEE; color: #333; padding: 10px; text-shadow: 1px 1px 1px #fff;">a</td>
</tr>
<tr>
<td style="border: solid 1px #DDEEEE; color: #333; padding: 10px; text-shadow: 1px 1px 1px #fff;">b</td>
<td style="border: solid 1px #DDEEEE; color: #333; padding: 10px; text-shadow: 1px 1px 1px #fff;">b</td>
</tr>
<tr>
<td style="border: solid 1px #DDEEEE; color: #333; padding: 10px; text-shadow: 1px 1px 1px #fff;">c</td>
<td style="border: solid 1px #DDEEEE; color: #333; padding: 10px; text-shadow: 1px 1px 1px #fff;">c</td>
</tr>
</tbody>
</table></body></html>
```
**Note the line breaks inserted after each HTML tag.** My CSS just includes a few straight-forward styles, nothing strange, doesn't set any content.

I know I can use further filtering to change these, but it's getting too convoluted; this is user-provided content that will get sent as an HTML email. I need to run a `nl2br` on it at the end, and I can't easily manage all this back and forth of line-breaks. I need to respect user-provided line-breaks, and I won't be able to tell them apart from stuff added afterwards. It would be easier if `inline_css` didn't add them - why should it?

**Comment by xabbuh** [comment]
Couldn't you solve this by swapping the `spaceless` and `inline_css` filters?

**Comment by pgorod** [comment]
The `inline_css` should be the last one I call, to ensure that the CSS is applied to the entire email content. In real life people won't be using spaceless for all of it, they would just use the `spaceless` filter when needed, i.e. around tables to avoid broken rendering.

This is closer to the sample template I've been trying, and which I would like my users to be able to provide:

```html
{%- apply inline_css(source("mycss"))|nl2br -%}

Dear {{ contact.name }},

thank you for contacting us.

Your recent quote is: {{ (contact|related('quotes')|first).name }}

{%- apply spaceless -%}
<table>
<thead>
    <tr>
        <th>Name</th><th>Value</th>
    </tr>
</thead>
<tbody>
    {% for aQuote in contact|related('quotes') %}
        <tr>
            <td>{{ aQuote.name }}</td>
            <td>{{ aQuote.total_amt|format_currency('EUR') }}</td>
        </tr>
    {% endfor %}
</tbody>
</table>
{%- endapply -%}
{%- endapply -%}
```
The nice parts about this:

* the `nl2br` will ensure that the user's line breaks at the top part will be included in the HTML and displayed in the resulting email (`\n` won't do)

* I get to use line breaks for clarity in the `<table>` part. But I can't have them get turned into `<br/>` in the end, otherwise the table will render broken. To achieve that, I use Twig's `spaceless` filter for _part_ of my content, not all.

I can work around this by splitting the `nl2br` filter on its own `apply` tag, encompassing only the top part. Then I use the `spaceless` only for the bottom, and the `inline_css` for the entire thing.

But it gets really clumsy, and it seems to me that it would be much better if there were no unintended side-effects of `inline_css`. Each part should do its function, and only its function, so that we can combine all the elements elegantly.

**Comment by stof** [comment]
Well, I'd rather suggest you to apply `nl2br` only around the relevant part.
`spaceless` has no guarantee that it will remove all newlines (as it removes spaces only between tags) so you might have unintended line breaks with your solution.

And if you really want to keep this way of doing that, I suggest you to swap the `nl2br` and `inline_css` filters. The CssToInlineStyles library (used by the `inline_css` filter) parses the HTML, modifies it and dumps it again, which is not guaranteed to preserve the exact formatting.

**Comment by pgorod** [comment]
Ah this is an external library, I see.

I don't want to be too insistent on this, I think I can work around it with these suggestions (thank you!), so don't worry about my particular use case (and I don't mind if somebody closes this issue).

But I do still get a nagging feeling we should _Do The Right Thing_ and make sure each directive does what it says, and nothing more. It's these small concessions that can turn an excellent, clean solution like Twig into a messy jumble of workarounds.

**Comment by stof** [comment]
Well, using a parser and the DOMDocument AST to modify the HTML is actually the right thing to do. Inlining CSS by modifying the input string directly would be very fragile (and very hard to do).

**Comment by pgorod** [comment]
I guess I was hoping that "using a parser and the DOMDocument AST" didn't have to mess with white-space, or could be tweaked to output HTML without line-breaks. Maybe not. I confess my ignorance of what is happening "under the hood" in this processing.

Thanks to all who participated - feel free to close this Issue if you think that is appropriate. 😃

**Comment by stof** [comment]
Well, then report that to PHP itself that using `DOMDocument` to load and save HTML does not preserve the original formatting.
