### ISSUE TITLE
array_key_exists error for 2.12.5

### ISSUE THREAD

**Issue by lwebzem** [twigphp/Twig#3372]
I upgraded Twig to latest 2.12.5  from 2.1.0 because of deprecation array_key_exists in php 7.4 but I still see using array_key_exists in 2.12.5 new rev.    Per previous comments on this site it looks like it should be resolved in 2.x .  But why I still see array_key_exist function which will fail in php 7.4?
Will be there new 2.x with fix?
Thanks.

**Comment by nicolas-grekas** [comment]
Did you experience any actual issue? Because this is fixed afaik. Yes it still uses array_key_exists(), but in a new way that is not deprecated.

**Comment by fabpot** [comment]
Closing as there is no feedback.
