### ISSUE TITLE
What's the replacement of twig/extensions for Twig3?

### ISSUE THREAD

**Issue by tripbnb66** [twigphp/Twig#3374]
I used twig/extensions to do the internation and location of translation.
In the twig/extensions, I can use  {% trans "hello" %} in my *.html files  to do the translation which is supported by **gettext to generate .po and .mo files**.
After upgrading from twig/twig:2 to twig/twig:3, I can't install the twig/extensions.
I read the official documentation of twig/extensions and it said that twig/extensions is not supported by twig3.

My question is:
Can anyone suggest an alternative solution of twig/extension for twig/twig:3.0?
Thank you.
Best regards
-------

**$ composer require twig/extensions**

Using version ^1.5 for twig/extensions
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - twig/extensions v1.5.4 requires twig/twig ^1.27|^2.0 -> satisfiable by twig/twig[1.x-dev, 2.x-dev .... but these conflict with your requirements or minimum-stability.
    - Installation request for twig/extensions ^1.5 -> satisfiable by twig/extensions[v1.5.0, v1.5.1, v1.5.2, v1.5.3, v1.5.4].

my composer.json file is:
----
{
    "require": {
        "mpdf/mpdf": "^8.0",
        "phpmailer/phpmailer": "^6.1",
        "gettext/gettext": "^5.5",
        "twig/twig": "^3.0"
    }
}
-----

**Comment by stof** [comment]
The gettext-based I18nExtension extension of `twig/extensions` has no official replacement, because it was unmaintained for years (Twig is maintained by the Symfony core team, and Symfony has a separate translation extension based on the `symfony/translation` component).

Some other extensions of `twig/extensions` have replacements in the `twig/*-extra` packages.

**Comment by tripbnb66** [comment]
@stof thanks to your reply.
Do you know which package that support the similar function like twig/extensions especially the "trans" function for i18n?
Thank you.
Best regards.

**Comment by stof** [comment]
As I said, there is no official replacement for a gettext-based trans extension. There are multiple third-party Twig extensions using gettext but I don't know them (I'm not using gettext) so I cannot advice you for a choice between them: https://packagist.org/?query=twig%20gettext

The extension based on `symfony/translation` is implemented in `symfony/twig-bridge`.
