### ISSUE TITLE
Feature request: node parser offsets

### ISSUE THREAD

**Issue by muglug** [twigphp/Twig#3375]
Hey!

This is a _very_ niche request, but would it be possible to include the cursor position in tokens created by the lexer, and subsequently in parser nodes (start position and end position)?

I'm looking at static analysis of Twig templates, and adding this information would improve the error reporting.

I'd be happy to create a PR.

**Comment by fabpot** [comment]
If this feature is not too invasive and if it does not have a significant performance impact (CPU/memory), I would be happy to review a pull request (on the 1.x branch).

**Comment by fabpot** [comment]
Closing as there is no more feedback.
