### ISSUE TITLE
Symfony debug toolbar broken with Twig 3.0.4

### ISSUE THREAD

**Issue by enumag** [twigphp/Twig#3376]
After last composer update I noticed that Symfony's debug toolbar didn't load. After some trial and error I found out that it is broken by Twig 3.0.4 but works fine with Twig 3.0.3.

What kind of BC break did you make that could break it?

**Comment by nicolas-grekas** [comment]
You just reminded me this tweet from @fabpot ;)
https://twitter.com/fabpot/status/1270266315379539971?s=19

**Comment by xabbuh** [comment]
Do you see any errors in the log?

**Comment by enumag** [comment]
After some more digging this was likely a false alert on my part, sorry.

**Comment by enumag** [comment]
@nicolas-grekas I didn't mean to imply that anyone broke anything intentionally of course. :unamused:
