### ISSUE TITLE
Crashes on string under double curly handles {{=}}

### ISSUE THREAD

**Issue by alexmityuk** [twigphp/Twig#3380]
I have an issue when string {{=}} comes in a twig temlate and it's crashes
verbatim, raw, autoescape sections does not helps

so, just put in a template {{=}} and it will crash

**Comment by stof** [comment]
Can you please share a reproducer ?

**Comment by alexmityuk** [comment]
> Can you please share a reproducer ?

https://twigfiddle.com/56qrji
or something like this https://twigfiddle.com/mbs9d2

**Comment by apfelbox** [comment]
Verbatim works? https://twigfiddle.com/56qrji

**Comment by fabpot** [comment]
Both examples are invalid Twig code, so an exception is expected. You said that it crashed, that's not the case in Twig fiddle.

**Comment by alexmityuk** [comment]
yes, this is invalid code, but in my case i have template {{ someValue }}, where someValue gets a value {{=2}}
so my question was - how i can process this case ?

**Comment by stof** [comment]
Having that string inside a variable is not the same at all than having it in the source of the template. That's precisely why we need a reproducer of *your* issue.

**Comment by stof** [comment]
And when putting that value in a variable, there is no crash when I try: https://twigfiddle.com/t8xxkf

**Comment by alexmityuk** [comment]
I have not open examples, sorry, will think
thanks for replies!

p.s. seems like it's Vue.js crashes when compiling this html 
Twig is ok :+1:
