### ISSUE TITLE
"not" with ternary operator broken in 2.13.0

### ISSUE THREAD

**Issue by soukicz** [twigphp/Twig#3383]
This code was working in 2.12.5 but throws exception in 2.13.0

Code:
```twig
{{not true ? 'yes' : 'no'}}
```
Error:
`Unexpected token "name" of value "true" ("end of print statement" expected).`

Fiddle: https://twigfiddle.com/91wt3u

**Comment by stof** [comment]
Note that putting a space between `{{` and `not` solves this, so there is an easy workaround.

**Comment by xabbuh** [comment]
Fixed by #3365?

**Comment by stof** [comment]
possibly.
@fabpot when do you plan to to release that fix ?

**Comment by fabpot** [comment]
I confirm that it's already fixed. I'm about to make new releases.

**Comment by soukicz** [comment]
Wow, that was fast :) I have created this issue mainly to not forget about it and add failing test later. When I checked back, everything is already resolved!

Thank you!
