### ISSUE TITLE
Index page of Twig 1.x documentation listed not available filters 

### ISSUE THREAD

**Issue by reneroboter** [twigphp/Twig#3398]
Hey,

today I noticed, that the Twig documentation for version 1.x listed filters which implemend in 2.x and higher. The documention files for 1.x seems to be okay. However is it's confusing to see not available features at the docs.

Thats should be rendered:

* https://github.com/twigphp/Twig/tree/1.x/doc/filters

But this is the result:

* https://twig.symfony.com/doc/1.x/

Greeting
René

**Comment by tekNorah** [comment]
Any idea when/how this might get updated?

**Comment by stof** [comment]
@fabpot any chance to fix the documentation homepage (which is maintained in the website source code and not here) ?

**Comment by lacatoire** [comment]
@stof @fabpot I can't find the repo, do you have the url? or is it abandoned?

**Comment by fabpot** [comment]
@lacpandore Not sure what you're looking for. The doc for 1.x is still here: https://twig.symfony.com/doc/1.x/ and in this repository for the source.
