### ISSUE TITLE
How to use arrow functions as callable?

### ISSUE THREAD

**Issue by I-Valchev** [twigphp/Twig#3402]
I'd be really great if Twig arrow functions can be passed as arguments.

e.g. [Laravel collections unique method](https://laravel.com/docs/8.x/collections#method-unique) accepts a callable.

I'd like to do something like this:

```twig
{{ mycollection.unique(item => item.id) }}
```

Is that possible? Or an RFC?

**Comment by fabpot** [comment]
It's not supported. Arrow functions are limited in scope.

**Comment by I-Valchev** [comment]
@fabpot okay... but why not keep this is an RFC?

It would be _very_ useful to have more flexibility to filter/sort arrays or collection objects.

**Comment by timkelty** [comment]
I'd love to see this as well! Specifically, would use here: https://github.com/timkelty/craftcms-classmate#arrow-functions

**Comment by michaelrog** [comment]
@fabpot Would you consider making `$allowArrow` _configurable_, i.e. opt-in on a per-Environment basis?

The ability to pass tiny little closures to [Collection](https://laravel.com/docs/8.x/collections) methods would be really nice. I definitely appreciate the spirit of limiting arrow functions to narrow usage, but the Collections use case is very compelling.

**Comment by khalwat** [comment]
To make this work this one line: <https://github.com/twigphp/Twig/blob/3.x/src/ExpressionParser.php#L483> from: 
```php
                    foreach ($this->parseArguments() as $n) {
```
 to: 
```php
                    foreach ($this->parseArguments(false, false, true) as $n) {
``` 
then closures all work in the context we want, e.g.: 
```twig
    {% set collection = collect(['a', 'b', 'c']) %}
    {% set contains = collection.contains((value, key) => value == 'a') %}
```
 with a nice, clean, normal syntax. I'd love to see this happen, too.

**Comment by brandonkelly** [comment]
Would really love to see this as well. When writing templates, it’s really confusing why arrow functions work in some cases but not others, when you know the underlying method accepts a callable.

**Comment by khalwat** [comment]
Here's a solution for Craft CMS: https://github.com/nystudio107/craft-closure

**Comment by tbreuss** [comment]
Would really love to see this as well.

**Comment by khalwat** [comment]
Anyone who is interested in this, I added it here: https://github.com/twigphp/Twig/issues/3951#issuecomment-1922578351

**Comment by fabpot** [comment]
See #4378
