### ISSUE TITLE
_context | merge() creates a recursion

### ISSUE THREAD

**Issue by evanwarner** [twigphp/Twig#3403]
Twig version: 2.13.1
PHP version: 7.4.2

While attempting to figure out ways to declare dynamically-named variables, I tried this code:
```twig
{% set _context = _context | merge({
    'hello': 'world'
}) %}
```

Checking the results with `{{ dump(_context | keys) }}` shows the expected context variables except the last key is `'_context'` and there is no `'hello'` key.

Then checking `{{ dump(_context._context | keys) }}`, I get the result I would have expected the first time: all normal context keys, plus the merged `'hello'` key.

So it seems that running an object merge on `_context` causes the entire object to be duplicated as a child of itself.

**Comment by jvasseur** [comment]
This has nothing to do with the merge filter. It's just that `{% set _context %}` doesn't set the full context but instead set the `_context` key in it (like any call to set).

Not sure if using `set` to replace the full context is something we want to support but indeed this behavior is unexpected. I think the right thing is probably throw an error in this case.

**Comment by evanwarner** [comment]
Ahhhh, that makes total sense. I suspected that attempting to directly extend `_context` was a no-no, and this felt like a weird solution to the issue anyway, so I'm totally fine with this not being supported.

**Comment by fabpot** [comment]
Closing as you shouldn't change the `_context`.
