### ISSUE TITLE
twig 3 - datetime to string error

### ISSUE THREAD

**Issue by nightw0lv** [twigphp/Twig#3404]
i got crash when using {{ date('+3days') }}

**Comment by stof** [comment]
The function `date('+3days)` returns a `DateTime` object, which cannot be casted to string. So you must use a filter to format it for display. Twig has several such filters:

- `|date` which is in core
- `|format_date`, `|format_time` and `|format_datetime` in `twig/intl-extra` which supports localized formatting based on IntlDateFormatter
