### ISSUE TITLE
Twig - towebp filter issue : convert issue

### ISSUE THREAD

**Issue by magalieyang** [twigphp/Twig#3405]
Hello, 

I am using **Twig** with **Wordpress** and I have an issue with the filter "**towebp**".
my part is pretty commun (i guess) : 
```
                <picture>
                  <source type="image/webp" media="(min-width:897px)" srcset="{{ member.image.url | towebp }}">
                  <img class="" src="{{ member.image.url }}" alt="{{ member.image.alt }}">
                </picture>
```

I have no visible image is displayed on the final rendering, in fact I have the **.webp** file created on **_uploads/_** but if I open it on the _Chrome_ web browser, I have no image visible (but if I open the webp on _Firefox_, I have an image displayed.)
member.image.url is never empty and always have the right path.

My Chrome web browser does support webp format, I have a banner with the same script and it works well.

I don't know where and why sometimes the towebp filter doesn't work well ...
Is there a way to avoid or fix this issue ? 

Thank you for any reply and help!

**Comment by stof** [comment]
`towebp` is not a native feature of Twig. You need to find which package provides this filter in a twig extension and ask for support there.
