### ISSUE TITLE
Possible improvements in .gitattributes

### ISSUE THREAD

**Issue by garak** [twigphp/Twig#3423]
In a production project, I see the following content in `vendor/twig/twig':
```
CHANGELOG
composer.json  
doc  
drupal_test.sh  
.editorconfig  
.gitattributes  
.gitignore  
LICENSE  
.php_cs.dist  
README.rst  
src  
.travis.yml
```

I think we should get rid of following, at least:

```
drupal_test.sh  
.editorconfig  
.gitattributes  
.gitignore  
.php_cs.dist  
.travis.yml
```

Not sure if we want to keep changelog and documentation...

**Comment by garak** [comment]
Of course, I can submit a PR

**Comment by fabpot** [comment]
There is no point in adding small files (and there are drawbacks).
