### ISSUE TITLE
Checking if value IS NOT in array using filter - a bug?

### ISSUE THREAD

**Issue by Proxxx23** [twigphp/Twig#3426]
Hello,

can't find any info if it's possible to check whether given value is not in array. I've created code like this:

`{% for attr, value in meta|filter(attr => attr not in ['useRaw', 'prefix']) %}`

But it does not work. But this piece of code:

`{% for attr, value in meta|filter(attr => attr in ['useRaw']) %}`

Works perfectly fine.

What's more, this works fine too:

`{% for attr, value in meta %}{% if attr not in ['useRaw', 'prefix'] %}{{ attr }} [...]`

Is that because one cannot negate array key existence in Twig, or it's a bug?

**Comment by stof** [comment]
Can you share a full reproducer (i.e. including what you have in your variables) ? https://twigfiddle.com/ is a great tool for that.

**Comment by stof** [comment]
hmm, I think I understood. The `|filter` filter calls the callback with the value as first argument and the key as second argument. So in, in `meta|filter(attr => attr in ['useRaw'])`, your `attr` argument is actually the value.

**Comment by Proxxx23** [comment]
> hmm, I think I understood. The `|filter` filter calls the callback with the value as first argument and the key as second argument. So in, in `meta|filter(attr => attr in ['useRaw'])`, your `attr` argument is actually the value.

But IN works properly, NOT IN does not...

**Comment by stof** [comment]
please share a reproducer including the conten of the `meta` variable. Otherwise, I'm doing guess work.

**Comment by Proxxx23** [comment]
> please share a reproducer including the conten of the `meta` variable. Otherwise, I'm doing guess work.

Here you go: https://twigfiddle.com/glmz8l

Dump is made by dump() twig function. I think it's readable.

**Comment by apfelbox** [comment]
Seems to work properly?
with `in`: https://twigfiddle.com/glmz8l/3
with `not in`: https://twigfiddle.com/glmz8l/2

**Comment by Proxxx23** [comment]
But I speak about `filter`, not about `if` condition. Can't use fiddle, as filters are disabled here.

Try to run something like this:

```
{% for meta in headMeta %}
    <{{ meta {% for attr, value in meta|filter(attr => attr not in ['useRaw', 'prefix']) %}{{ attr }}="{% if meta.useRaw %}{{ value|raw }}{% else %}{{ value }}{% endif %}"{% endfor %}>
  {% endfor %}
```
Having this bunch of data for one record:
'name': 'description'
'content': 'asd'
'useRaw': false
'prefix': 'meta'

This will ignore NOT IN and set {{ attr }} = 'meta', but should consider only name and content.

That's the case.

**Comment by stof** [comment]
@Proxxx23 please read my comment above. The first argument of the callback for `filter` is the **value** of the array, not the key. They hey is the second argument. So even if you name the argument `attr`, it is **not** the same than your `attr` from the iteration but the same than your `value` variable of the iteration.

Also, the twigfiddle you shared is not a reproducing case:
- it does not define the content of `meta` (which makes the execution fail). The right column is where you define that (or you use `{% set my_var = { ... } %}` in the template directly)
- it uses `{% if %}`, not `{% filter %}`, which is probably why @apfelbox's fixed version also uses it.

**Comment by SpacePossum** [comment]
```twig
{% set meta = {
    '123': 1,
    'foo': 2,
    'bar': 3
} %}

- loop 1 Reported as "bugged"

{% for attr, value in meta|filter(attr => attr not in ['foo', 'bar']) %}
    {{ attr }} - {{ value }}
{% endfor %}

- loop 2 Reported as ""working"

{% for attr, value in meta %}
    {% if attr not in ['foo', 'bar'] %}
        {{ attr }} - {{ value }}
    {% endif %}
{% endfor %}

- loop 3 Suggested as fix

{% for attr, value in meta|filter((value, attr) => attr not in ['foo', 'bar']) %}
    {{ attr }} - {{ value }}
{% endfor %}
```

renders:

```
- loop 1 Reported as "bugged"

    123 - 1
    foo - 2
    bar - 3

- loop 2 Reported as ""working"

            123 - 1
            
- loop 3 Suggested as fix

    123 - 1

```

**Comment by Proxxx23** [comment]
Okay, many thanks - I understand it now! :)
