### ISSUE TITLE
Cannot redeclare __TwigTemplate_xyz::checkSecurity if adding both SandboxNodeVisitor and SandboxExtension

### ISSUE THREAD

**Issue by mbessolov** [twigphp/Twig#3445]
I encountered this issue when upgrading from v2.13.1 to 2.14.0

```php
<?php
require __DIR__ . '/vendor/autoload.php';
$twig = new \Twig\Environment(new \Twig\Loader\ArrayLoader(['template' => 'content']));

$twig->addExtension(new \Twig\Extension\SandboxExtension(new \Twig\Sandbox\SecurityPolicy()));
$twig->addNodeVisitor(new \Twig\NodeVisitor\SandboxNodeVisitor());

echo $twig->render('template');
```
produces
```
PHP Fatal error:  Cannot redeclare
__TwigTemplate_4d22a90d60e84fc10eff1f053099f13449bfe617a048aee5fcfb6c9154c218ca::checkSecurity()
in /home/michael/tmp/twig-bug/vendor/twig/twig/src/Environment.php(418) : eval()'d code on line 87
```
The compiled template looks like this (non-relevant lines stripped for brevity):

```php
class __TwigTemplate_4d22a90d60e84fc10eff1f053099f13449bfe617a048aee5fcfb6c9154c218ca extends \Twig\Template
{
    /* ... */
    public function __construct(Environment $env)
    {
        /* ... */
        $this->sandbox = $this->env->getExtension('\Twig\Extension\SandboxExtension');
        $this->checkSecurity();
        $this->sandbox = $this->env->getExtension('\Twig\Extension\SandboxExtension');
        $this->checkSecurity();
    }

    /* ... */

    public function checkSecurity()
    {
        /* ... */
    }
    
    public function checkSecurity()
    {
        /* ... */
    }
}
```

On the surface it looks like a result of #3413, but after digging a bit into it I think that #3413 simply revealed the side effects of  somewhat special treatment given to parsers and visitors in ExtensionSet initExtension - https://github.com/twigphp/Twig/blob/v2.14.1/src/ExtensionSet.php#L458

Both visitors and parsers are prone to such duplication, as they are not de-duped when initializing extensions and the staging.

**Comment by stof** [comment]
you should not be adding a SandboxNodeVisitor yourselves. The SandboxExtension is already managing the SandboxNodeVisitor, so you end up with running the SandboxNodeVisitor twice.

**Comment by mbessolov** [comment]
@stof the code above is just an over simplified example to reproduce the problem.
In the real code (it was a test in a complex application) we do not know what visitors have already been added by the extensions. And I see no way to check whether or not a certain visitor was added, as calling getVisitors() on an Environment instance causes initialization of all extensions, and even if that visitor was not added yet, it will not be possible to add it after the initialization anyway.

**Comment by stof** [comment]
@mbessolov but why do you need to know that ? In general, all open-source extensions of Twig I know of are exposing their features with an Extension to register things instead of making you register node visitors, token parsers, functions or filters manually.

@fabpot should we mark the core node visitors used by extensions as `@internal` ?

**Comment by fabpot** [comment]
@stof Good idea, done in #3448 (should not be a problem as these classes are already marked as `final`)
