### ISSUE TITLE
Twig column should work with entity objects?

### ISSUE THREAD

**Issue by fire1** [twigphp/Twig#3446]
This example from documentation works:

```
{% set items = [{ 'fruit' : 'apple'}, {'fruit' : 'orange' }] %}
 {% set fruits = items|column('fruit') %}
```

But when I replace the content with a Doctrine entity object  Twig fails to retrieve values from the column.

The repository method `getArrayResult` fixes the issue...

Twig version "^2.12|^3.0"  (from Symfony 5.1)

**Comment by stof** [comment]
`column` is not meant to work on objects, no. It is exposing `array_column`
