### ISSUE TITLE
Mark safe object based on prop/method

### ISSUE THREAD

**Issue by I-Valchev** [twigphp/Twig#3455]
Hi, I need to be able to mark an object as safe based on a prop value.

Following the docs, I can successfully add a safe class/interface. However, the use case is different. For example:

Field $a has `safeHtml` prop set to `false` -> not safe
Field $b has `safeHtml` prop set to `true` -> should be safe (html rendered without using `|raw` in Twig itself).

I've looked at the code and [PR](https://github.com/twigphp/Twig/pull/3025/files) that implements it, and tried the following:

1. Custom escaper -> does not work, because by the time the escaper is called, the value is already cast to string, since the object implements `__toString()`. Hence, there's no longer access to `safeHtml`
2. If the object does not implement `__toString()` then things like `{{ a ~ ' something else' }}` fail (`a` and `b` cannot be cast to string)
3. Overriding `html` escaper -> does not work, since it's behaviour is hard-coded (see PR linked above)

Any guidelines to what can be done to support this? Thanks.

**Comment by stof** [comment]
Twig supports making some classes as safe regarding auto-escaping (`Twig\Markup` is always like that, but custom classes or interfaces can be registered too). But it does not have a way to make this safety conditional based on a property

**Comment by I-Valchev** [comment]
hi @stof, thanks for the info! Do you have any pointers of what needs to be done to get this to work? Either downstream in the app I'm working on, or as a PR in twig itself?

**Comment by apfelbox** [comment]
Would it make sense to create a VO that encapsulates "safe" markup? So that if you pass in a value of this type, it won't be escaped?

**Comment by stof** [comment]
such VO already exist. What does not exist is the VO encapsulating "sometimes-safe" markup

**Comment by I-Valchev** [comment]
Sorry @stof  and @apfelbox but... what is a VO? 🙈

**Comment by stof** [comment]
a value object
