### ISSUE TITLE
Cannot use macro inside cache tag

### ISSUE THREAD

**Issue by JakeFr** [twigphp/Twig#3466]
Hello

I encountered an error `Undefined variable: macros` with macro call inside cache tags
```
{% cache "test1" %}
    {% macro foo(bar) %}
        {{ bar }}
    {% endmacro %}

    {{ _self.foo('baz') }}
{% endcache %}
```

With a macro defined in another template and imported, it works fine.
Importing current template works too `{% import _self as macro %}`

Is it a limitation with the scope of the cache tag or a bug ?

**Comment by stof** [comment]
> Is it a limitation with the scope of the cache tag or a bug ?

I would say a mix of both :smile:

**Comment by JakeFr** [comment]
I try to add $macros in the context of the cache closure.
The simple use case is solved
~~But after some tests I found lot of side effects due to multiple and imbricated calls to ob_start~~
My bad i made errors/confusion with new lines and indentation
