### ISSUE TITLE
Support for setting cache tags inside cache block

### ISSUE THREAD

**Issue by andrerom** [twigphp/Twig#3468]
Feature: https://twig.symfony.com/doc/3.x/tags/cache.html

Often cache tags are determined when generation the cache, so support for setting tags inside the block would be beneficial.

Example would be loading data either by means of dynamic (fat) entity properties or by means of template operators, where you'd prefer not to have to do that outside of the cache block.

---

Related feature request, support for setting "persisted" output variables: https://github.com/twigphp/Twig/issues/3467

cc @bdunogier

**Comment by fabpot** [comment]
Closing as this is not something we will implement in core.
