### ISSUE TITLE
[Feature Request] Write nested array keys using set

### ISSUE THREAD

**Issue by ro0NL** [twigphp/Twig#3471]
See https://twigfiddle.com/9syeq5
Vs. https://3v4l.org/Ucuos

seems reasonable to allow `{%set arr.key = 'val' %}` rather than boring array merge :}

**Comment by stof** [comment]
the issue is that `arr.key` is not guaranteed to be accessing an array key in Twig. So that would be a syntax that *sometimes* work but not always

**Comment by fabpot** [comment]
I'm against adding such a feature. Changing things in a template should not be the norm, so I don't want to make it easier.
