### ISSUE TITLE
website: filter "format_datetime": arguments

### ISSUE THREAD

**Issue by EarthDweller** [twigphp/Twig#3477]
Maybe on page "https://twig.symfony.com/doc/3.x/filters/format_datetime.html" add info that for filter `format_datetime` is possible to use argument `timezone`.

 exp.:
```
{{ "2020-02-02"|format_datetime(pattern="YYYY-MM-dd HH:mm (VV)") }}
<br>
{{ "2020-02-02"|format_datetime(pattern="YYYY-MM-dd HH:mm (VV)", timezone='Pacific/Enderbury') }}
```

**Comment by fabpot** [comment]
Can you submit a PR to add that?

**Comment by EarthDweller** [comment]
👨‍🔬…
https://github.com/twigphp/Twig/pull/3486

But I'm not a native English speaker :)
