### ISSUE TITLE
Wrong tag 3.2.0 for twig/extra-bundle was published again

### ISSUE THREAD

**Issue by sylvia-vdv** [twigphp/Twig#3485]
The version twig/extra-bundle 3.2.0 contained a bug because it was not compatible with twig v2. The tag had been removed and a fixed 3.2.1 was introduced.
Within the last few days, the tag was republished, resulting in a broken application when running composer update with twig v2. 
For now we will manually pin version 3.1.1 of twig/extra-bundle

**Comment by fabpot** [comment]
Fixed.
