### ISSUE TITLE
Passing a numeric variable name rewrites the variable name as "0"

### ISSUE THREAD

**Issue by Bilge** [twigphp/Twig#3490]
```twig
{{ include('foo.twig', {123: true}) }}
{# OR #}
{{ include('foo.twig', {"123": true}) }}

{# foo.twig #}
{{ dump(_context) }}
```

>array:1 [▼
  0 => true
]

**Comment by stof** [comment]
Variables names starting with a number are not supported. You won't be able to use such variables normally (i.e. without going through the special `_context` variable), as their names are not valid identifiers.

So to me, that's a won't fix. But I'll let @fabpot give its opinion there.

**Comment by Bilge** [comment]
It's also not an error. If it's not supported, it should be clear, instead of exhibiting weird behaviour.

**Comment by stof** [comment]
Well, checking all array keys when passing variables to another template will have a performance impact.

but maybe some of these cases could be solved by replacing a few `array_merge` with `array_replace` in the codebase.

**Comment by fabpot** [comment]
I've tried it today and it works well. I've also tried with very old versions of Twig and it works. So, I'm missing something here, but I don't know what.
