### ISSUE TITLE
Documentation should reflect Intl Extra Extension

### ISSUE THREAD

**Issue by trickeyone** [twigphp/Twig#3493]
The documentation says that various filters (i.e. `format_number`, `format_currency`) are available. However, if you attempt to use them, you're given the error that they do not exist. It's only after doing a lot of troubleshooting and digging in Twig's history to find out that, at some point in the past, they were moved to a completely different repo.

If a separate repo is needed for listed filters, tests, etc., it should really be mentioned somewhere. For those new to Twig (of which I am not), this would likely lead to an extreme amount of frustration.

I did do a fair amount of searching in an attempt to figure out why the filter was missing (i.e. using different search engines looking for stuff like "twig format_number" "twig missing filter" etc.) but very little came up anywhere, including Stackoverflow.

**Comment by fabpot** [comment]
If you go to the docs: https://twig.symfony.com/doc/3.x/filters/format_number.html, there is a paragraph at the end that says it's part of an extension and explain how to install it. Isn't it enough? What would you like to add?

**Comment by trickeyone** [comment]
Apologies, I did not see that. I must have skipped right over it as it appeared to be part of the rest of the usage documentation. Do you think it would be beneficial to highlight it a little differently than the blue-border? Maybe a header that calls out that it's related to installation?
