### ISSUE TITLE
Passing variable to tags

### ISSUE THREAD

**Issue by Seb33300** [twigphp/Twig#3496]
It seems to not be possible to pass variables to tag parameters.
For example, if we want to enable `autoescape` depending on a condition:

``` twig
{% set enable_auto_escape = false %}

{% autoescape enable_auto_escape %}
    ...
{% endautoescape %}
```

Result:

> An escaping strategy must be a string or false.

**Comment by stof** [comment]
autoescaping is something that impacts the compilation of the template. That's why using variables is not supported. You don't want to recompile your template each time you change the value of the variable.

**Comment by fabpot** [comment]
Closing as explained by @stof
