### ISSUE TITLE
Environment should implement `ResetInterface` to reset globals

### ISSUE THREAD

**Issue by ruudk** [twigphp/Twig#3497]
I have a long running Symfony application that is booted once and handles multiple requests. There is also a custom TwigExtension that implements the `GlobalsInterface`. 

I noticed that the globals are only read once, the first time the Twig Environment is used.

It would be great if the `Environment` could somehow implement the `Symfony\Contracts\Service\ResetInterface` so that it will re-read globals from extensions every time it's reset. 

Would that make any sense? I could try to draft a PR.

**Comment by ruudk** [comment]
Solved it differently.

**Comment by hellomedia** [comment]
@ruudk How did you solve this ? I am trying to reset/update globals as well.

**Comment by stof** [comment]
Twig does not support registering new globals after extensions have been initialized either. The available globals are not really meant to be mutable.

If you have a need to have mutable state in global variables, my suggestion is to expose a global variable being an object (with appropriate getters for the various pieces of the state you want to expose) and to make *that* object mutable and resettable.

**Comment by hellomedia** [comment]
@stof Thanks for the suggestion.

Can I clarify my use case ? I have a multi-site setup with a single codebase and a `site` twig global variable. Works great in http context, where I use an environment variable to set the site. However, in the messenger queue, a worker handles messages from different sites and it needs to update the `site` globals for each message (for rendering email templates).

Is there a better way to handle this ?

**Comment by stof** [comment]
Well, you would have to use a mutable object storing the current site, as suggested in my previous message.

**Comment by hellomedia** [comment]
I guess what I am trying to say is adding an intermediary object feels like a hack, which might cause questions to futur devs working on the project. Kind of feels like adding technical debt.

Multi-site setup and handling emails in a queue is not a very exotic use case.

Doesn't `Twig\Environment::updateGlobal()` feel like a cleaner way to handle it ?

**Comment by stof** [comment]
Actually, `Twig\Environment::addGlobal()` can already be used to modify the version of a global after initialization (but it will throw if trying to add a *new* global). It will update the resolved globals in that case.

But extensions cannot be the source of a mutable global as they won't be called again to get a different value (the extension might be used to perform the initial registration of the global to have an easy way to ensure that the global is always registered before the end of the initialization though)

**Comment by hellomedia** [comment]
Oh great !

I didn't realize `Twig\Environment::addGlobal()` could be used this way. Exactly what I need, thank you !

**Comment by hellomedia** [comment]
@stof Can I rely on Twig\Environment::addGlobal() to always give the ability to update an existing global or should I be weary that it might change ?

Also, I wonder if it could be made more explicit and save you a few support questions in the process.

I can submit a PR if you think it's a good idea.
