### ISSUE TITLE
`slug` filter not working in Twig 3

### ISSUE THREAD

**Issue by ThomasLandauer** [twigphp/Twig#3500]
I'm getting:
> Unknown "slug" filter.

Could it be that the PR didn't make it into Twig 3? https://github.com/twigphp/Twig/pull/3478

I have:
```
$ composer show | grep twig
symfony/twig-bridge                  v5.2.6    Provides integration for Twig with various Symfony components
symfony/twig-bundle                  v5.2.4    Provides a tight integration of Twig into the Symfony full-stack framework
twig/twig                            v3.3.0    Twig, the flexible, fast, and secure template language for PHP
```

Or do I need to do anything special to activate it? Then this would be missing at https://twig.symfony.com/doc/3.x/filters/slug.html :-)

**Comment by stof** [comment]
The slug filter exists. But it is part of the `twig/string-extra` package (where the PR added it).

The note about needing an extension of an extra package is indeed missing in this doc page. Contributions are welcome to fix it (look at the `format_datetime` doc for an example)

**Comment by ThomasLandauer** [comment]
Done :-) https://github.com/twigphp/Twig/pull/3501
