### ISSUE TITLE
Optimize for packagist production

### ISSUE THREAD

**Issue by luukvhoudt** [twigphp/Twig#3503]
When downloading the Twig package from packagist a lot of files are included which are never used in production or even by the developer itself. Have a look, this is what I get in my `vendor/twig/twig` folder after `composer require "twig/twig:^3.0"`:

```
CHANGELOG
composer.json
doc
drupal_test.sh
.editorconfig
.gitattributes
.github
.gitignore
LICENSE
.php_cs.dist
README.rst
src
```

Files and directories I think can be ignored:

```
.github
doc
drupal_test.sh
.editorconfig
.gitattributes
.gitignore
.php_cs.dist
```

These files together are 640kb, while the whole package is about 1700kb. That's about 48% of the total file size.

Please fix this. Love the package, thank you <3

**Comment by stof** [comment]
excluding the doc source code from the archive indeed probably makes sense (that's probably the bulk of these 640KB as others are small files)

**Comment by luukvhoudt** [comment]
Yes it's now 620KB

**Comment by williamdes** [comment]
Here is a list of the useless files: https://github.com/code-lts/doctum/blob/b2fca74060ba1a84c1dac23eec21221fbc589524/releases/5.4.0-dev/manifest.json#L3712

Files:
```json
        "vendor/twig/twig/.gitignore",
        "vendor/twig/twig/CHANGELOG",
        "vendor/twig/twig/composer.json",
        "vendor/twig/twig/README.rst",
        "vendor/twig/twig/.gitattributes",
        "vendor/twig/twig/drupal_test.sh",
        "vendor/twig/twig/.php_cs.dist",
        "vendor/twig/twig/.editorconfig",
```

Folders:
```json
        "vendor/twig/twig/doc",
        "vendor/twig/twig/.github",
```

**Comment by fabpot** [comment]
Most files mentioned above do not contribute significantly to the size of the archive. Can some create a PR to exclude the doc/ directory as this is indeed contributing significantly?

**Comment by kaznovac** [comment]
@fabpot please look again at #3570 - it excludes the doc along with the rest of unusable files in prod

**Comment by williamdes** [comment]
> Most files mentioned above do not contribute significantly to the size of the archive. Can some create a PR to exclude the doc/ directory as this is indeed contributing significantly?

Multiply it by the number of installs of twig ;)

**Comment by chapterjason** [comment]
@williamdes But these aren't installed in one system.
