### ISSUE TITLE
how can I compile a template and then get the result as PHP code

### ISSUE THREAD

**Issue by XfaonXE** [twigphp/Twig#3506]
how may I do such without modifying my code too much

**Comment by stof** [comment]
what is the use case you want to solve ?

**Comment by XfaonXE** [comment]
Due to my custom framework I am using a custom caching method and would not like to use the built in one, I want to be able to load a template then compile it.

I tried doing the whole interpretation process my self but could not understand what input these functions need, I cant get ahead of this

```php

$twig->tokenize(???, ???);

```

**Comment by XfaonXE** [comment]
@stof

**Comment by stof** [comment]
See `$twig->compileSource()` to compile a source to PHP code.

**Comment by XfaonXE** [comment]
alright thank you!

**Comment by XfaonXE** [comment]
one problem @stof how do i get source object

**Comment by stof** [comment]
@XfaonXE `$twig->getLoader()->getSourceContext($templateName)` is the one returning it.

Note however that if your use case is to do your own caching layer, you should probably be implementing the CacheInterface instead of replacing all the logic about loading and compiling templates. This way, you can keep using existing `Twig\Environment` APIs to load template

**Comment by XfaonXE** [comment]
Alright! I'll give it a try right now, thanks for the help! :D

**Comment by XfaonXE** [comment]
It Worked!! Thanks for the help :)

**Comment by XfaonXE** [comment]
One more question, i was able to get the class name of the template and create it via eval, one prob tho, on doDisplay and the contructor it needs 2 params and 1 called env.  how can i fill thos in

**Comment by stof** [comment]
I fail to see what you are trying to achieve. You should not be calling `doDisplay` yourselves.

**Comment by XfaonXE** [comment]
Yes, i think iv got it all running, i just evaluated the class and did this, $template->render([]); works great!

**Comment by stof** [comment]
@XfaonXE why are you trying to call the generated classes yourselves ? The public API of Twig is to use the `Twig\Environment`. the `Twig\Template` API is an internal one.

**Comment by XfaonXE** [comment]
Well my framework structure is a bit different as I have a custom api handler and stuff so uhh,when I used twigs normal metho, it didnt rlly liek it. also sorry late reply, i didnt relise there was a reply sorry

**Comment by XfaonXE** [comment]
also im not calling the class,i used eval so it actualy existsed and not living in a var lol, then i made object of the class and used twig to render
