### ISSUE TITLE
format_datetime filter formats NULL value as current date and time

### ISSUE THREAD

**Issue by joaomarcoslemos** [twigphp/Twig#3510]
Applied the following code, for an array of values with NULL values, however Twig shows the current date and time:

<td>{{ usuario.UltimoAcesso|format_datetime(locale='pt_BR') }}</td>

Values:
+----------------------------------------------------------------------------+
| UltimoAcesso                                                                      |
+----------------------------------------------------------------------------+
| NULL                                                                                   |
| NULL                                                                                   |
| NULL                                                                                   |
| NULL                                                                                   |
| 2021-04-16 21:12:11                                                           |
| NULL                                                                                   |
| NULL                                                                                   |
| NULL                                                                                   |
+----------------------------------------------------------------------------+

Twig shows:
16 de abr. de 2021 22:09:52
16 de abr. de 2021 22:09:52
16 de abr. de 2021 22:09:52
16 de abr. de 2021 22:09:52
16 de abr. de 2021 21:12:11
16 de abr. de 2021 22:09:52
16 de abr. de 2021 22:09:52
16 de abr. de 2021 22:09:52

The date and time the page was rendered is 16 de abr. de 2021 22:09:52. 

Best regards!

**Comment by stof** [comment]
That's because `new DateTime(null)` gives you the current date in PHP.

If your field is nullable and you want it formatted in a particular way, you should handle it before calling the `format_datetime` filter, which is specially expecting a datetime.
