### ISSUE TITLE
Format_currency does not format 'JPY' currency in 'fr' locale

### ISSUE THREAD

**Issue by Gerikk** [twigphp/Twig#3513]
Hello,

On a test template in symphony 5.2.6, I tried to format a number using 'format_currency' from IntlExtension.

`{{ '1000'|format_currency('JPY') }}`

The number is not formatted with a 'fr' locale.

![Screenshot_format_currency_fr](https://user-images.githubusercontent.com/51398853/116083743-47d2b680-a69d-11eb-802f-88f6b42d4fdc.png)

But is formatted correctly in other locales.

![Screenshot_format_currency_en](https://user-images.githubusercontent.com/51398853/116083760-4dc89780-a69d-11eb-983d-28de8bf65320.png)

 
(twig version : 3.3.0)

**Comment by alexandre-daubois** [comment]
Couldn't reproduce :confused:  Can you provide a reproducer?

**Comment by Gerikk** [comment]
There it is : 
https://github.com/Gerikk/bug-reproducer-twig-locale

the /en/home route displays the appropriate format while the /fr/home displays JPY.

**Comment by alexandre-daubois** [comment]
Couldn't reproduce it, even with your project. It might be a configuration problem on your side. Is php-intl extension installed on your system?
