### ISSUE TITLE
Custom escaper ignored when passed empty string

### ISSUE THREAD

**Issue by natecollins** [twigphp/Twig#3514]
When updating from v2.4.3 to v2.14.4, my custom escaper for JSON data no longer worked as expected:
```
$twig->getExtension('Twig_Extension_Core')->setEscaper('json', function($twigEnvironment, $val, $charset) {
    return json_encode($val);
});
```
When escaping an empty string (length 0), expected output would be quoted empty string `""` (length 2). 

The issue appears to be from code in `src/Extension/EscaperExtension.php` lines 204 - 206 in `twig_escape_filter`:
```
if ('' === $string) {
    return '';
}
```
Issue appears to exist in the 3.x branch as well.

**Comment by stof** [comment]
to me, this looks like abusing the escaping system. Encoding in json is not the same than escaping (btw, there is a builtin filter for `json_encode`)

**Comment by natecollins** [comment]
For the example case, adding the escape rather than using `json_encode` filter was so that it could be set default with `autoescape`. Maybe not the best example, but it's what I have.

Still, the issue of the escaper not being called when given an empty string doesn't seem to be documented and was a surprising, unexpected behavior.

**Comment by fabpot** [comment]
I think @stof is right, you're not escaping the input. Whatever the escape, escaping an empty string is a noop.

**Comment by natecollins** [comment]
I can work with the change in functionality from earlier versions of 2.x, but it was a change so I felt it was worth bringing up. It would be nice if the noop on empty string was mentioned in the documentation.

**Comment by fabpot** [comment]
Closing as the current behavior is the right one.
