### ISSUE TITLE
SIGSEGV when extending from itself 

### ISSUE THREAD

**Issue by zalexki** [twigphp/Twig#3517]
PHP segfault when trying to extend a twig template from itself.

not sure if this issue has its place here but maybe twig can handle this case to let user know there is a mistake ?

Tried on PHP 7.3.27 & 7.4.16 on FPM and apache mod with twig 3.2.1

**Comment by fabpot** [comment]
The same goes if you do an infinite loop in PHP, so that"s not related to Twig itself. Adding safeguards would add some overhead, so let's do the same as PHP.
