### ISSUE TITLE
 I get it, but it's not true ("source file was not found").

### ISSUE THREAD

**Issue by curruwilla** [twigphp/Twig#3519]
Hello, you beautiful ones

I get this exception sometimes.

And I don't understand why, can someone help me?

It is not something that disturbs the application I think, but if I get this error then the application should probably crash for the user and he has to reload the page to function normally.

It's very strange, because it happens only sometimes ..

`Line: 31 - File: /home/uiliacom/public_html/loja/view/templates/useflorabela/defaults/product_grid.twig - An exception has been thrown during the rendering of a template ("source file was not found").`

**Comment by stof** [comment]
Well, make sure your error page also renders linked exceptions (i.e. `$exception->getPrevious()`) and you might have more details about where the error actually happened during the rendering of the template.
Or maybe just look at the stack trace (if it is enough to get details).

Here, there is simply not enough details to allow us to help you (we cannot even know what the line 31 of the `product_grid.twig` file contains as we don't have the file)

**Comment by curruwilla** [comment]
LIne 31:
![image](https://user-images.githubusercontent.com/7454081/118000182-f6bcf680-b31b-11eb-919a-0ec07aebde2e.png)
