### ISSUE TITLE
Template "/v2/xyz.html.twig" is not defined in "v2/scriptwrapper.html.twig"

### ISSUE THREAD

**Issue by addefend** [twigphp/Twig#3523]
The recently released 1.44.3 produces the following error:

`Template "/v2/xyz.html.twig" is not defined in "v2/scriptwrapper.html.twig" at line 4.`

When including /v2/xyz.html.twig from scriptwrapper.html.twig. Same code works with version 1.44.2.

**Comment by rnuernberg** [comment]
I am guessing this is due to this change here https://github.com/twigphp/Twig/commit/3a67fc7dc577515dda3ee0887d71d542e82fc0b8#r50719251

**Comment by addefend** [comment]
yes, i guess so too. 

changing:
`{% include '/v2/xyz.html.twig' %}`

to:
`{% include 'v2/xyz.html.twig' %}`

makes the include work in 1.44.3

**Comment by jennypns** [comment]
I just spent hours debugging this issue. I'm glad I'm not the only one who has it, but for such a minor update, I am surprised this would break.

**Comment by berridgeab** [comment]
> I just spent hours debugging this issue. I'm glad I'm not the only one who has it, but for such a minor update, I am surprised this would break.

@jennypns 
Yep its broken all versions of Twig, IMHO it should never have been rolled out, it needs reverting back. You can either try and find EVERY leading slash in your templates / code or extend the Filesystem loader to fix the issue - 

    namespace \Twig\Loader;
    class LeadingSlashLoader extends \Twig\Loader\FilesystemLoader
    {
        protected function findTemplate(string $name, bool $throw = true)
        {
            return parent::findTemplate(ltrim($name, '/'), $throw);
        }
    }

**Comment by rnuernberg** [comment]
> Yep its broken all versions of Twig, IMHO it should never have been rolled out, it needs reverting back. You can either try and find EVERY leading slash in your templates / code or extend the Filesystem loader to fix the issue -

I would agree - @fabpot are we missing something here? To be honest, I fail to see why #3209 is an issue in the first place, so I would consider the change to be debatable. But even if the consensus is that the change is sensible, then I would still argue that the change represents a BC break und should be rolled back.

**Comment by fabpot** [comment]
The PR introducing this behavior has been reverted in all branches.
New releases have also been made accordingly.
That being said, I would still recommend people upgrade their code.
