### ISSUE TITLE
Error `An opened parenthesis is not properly closed` in the `include` function

### ISSUE THREAD

**Issue by alex-pravdin-sn** [twigphp/Twig#3528]
Twig 3.3.2

I'm trying to pass variables to a sub-template:

```twig
{% include('@Layout/navigation.twig', {foo: 'bar'}) %}
```

But getting the following error:

```
An opened parenthesis is not properly closed. Unexpected token "punctuation" of value "," ("punctuation" expected with value ")").
```

What I'm doing wrong?

**Comment by btinet** [comment]
Isn't it that way:

{{ include('template.html.twig',{'foo': bar}) }}

**Comment by alex-pravdin-sn** [comment]
@btinet Yes, I messed up function and operator... Thank you for pointing out.
