### ISSUE TITLE
Best way to load stylesheets through source() for use with inline_css

### ISSUE THREAD

**Issue by sanderdlm** [twigphp/Twig#3531]
The documentation for the [inline_css](https://twig.symfony.com/doc/3.x/filters/inline_css.html) filter has a section on passing stylesheets to the filter: 

> You can also add some stylesheets by passing them as arguments to the filter:
```twig
{% apply inline_css(source("some_styles.css"), source("another.css")) %}
    <html>
        <body>
            <p>Hello CSS!</p>
        </body>
    </html>
{% endapply %}
```
but it's my understanding that the source() method is intended for templates and only looks in the templates/views folders you have in your Twig path. What is the intended solution for this? Place the stylesheet in the template folder? Do I register a custom Twig path for my assets or public/build folder?

Adding 
```yaml
twig:
    paths:
        "%kernel.project_dir%/public/": ~
```
to my config and using it inside the template like so:
```twig
{% apply inline_css(source(asset('build/mail.css'))) %}
```
works, but is this considered good practice? If so, should I make a PR to the docs clarifying this use case?

Any feedback would be helpful, thanks.

**Comment by stof** [comment]
Well, if you want to load them through `source()`, they indeed need to be in a folder that is configured for the loading of templates. If they are elsewhere, you might indeed register an additional path (maybe with a namespace to separate them from actual template).
Alternatively, you can provide your own way of getting the CSS content.

**Comment by fabpot** [comment]
Closing as @stof gave the right answer.
