### ISSUE TITLE
How can I move macros to a global scope?

### ISSUE THREAD

**Issue by wvhn** [twigphp/Twig#3532]
Hello,
First of all thanks for maintaining twig v1.x for quite some time. This gave me the chance to keep our software up to date without big architectural measures  and breaking changes for the users. Now, the announcement of the support end in November is raising the question again how to proceed with global availability of macros. I‘ve been searching the docs and the web for days now and did find a hint, that moving macros to a global scope would be possible, but no further info on how to achieve this. 

We provide a framework for smart home visualization (https://github.com/Martin-Gleiss/smartvisu) where users can create their own visu pages using different layout templates. Widgets for control elements like switches, sliders or display fields are provided as twig macros which the users can call from everywhere.  Macros are centrally imported in a parent template which the users pages address by {% extends %}  statements. The parent also handles the import of jQuery libraries, CSS and JavaScript code for the widgets.

To make it even more complex, users can create their own widget macros and put them in a dropins folder. The central template finds them and imports them automatically.

So the global availability of macros is essential for our framework. How can I achieve this with twig v3.x for known macros that come with the package and also for user defined dropin macros?

thanks!
Wolfram

**Comment by stof** [comment]
You cannot make macros available globally. They need to be imported explicitly (btw, even in Twig 1.x, it would only partially work to rely on macros imported by the parent as that was not designed to work but relied on leaking part of them due to the implementation)

For features provided by the package, you might want to expose them as Twig functions rather than as Twig macros to make them available globally.

**Comment by fabpot** [comment]
Closing as explained by @stof

**Comment by wvhn** [comment]
@stof Thanks for the quick answer, even if it is not totally satisfying of course ;)

Well, then the docu of v2 is a bit misleading: 
![IMG_0107](https://user-images.githubusercontent.com/17801971/120291758-f339e100-c2c3-11eb-861b-429df5896b79.jpeg)

Would it be possible to move the imports into a twig function or an extension which is then being called in every template?

**Comment by stof** [comment]
this is talking about blocks and sub-blocks, not about parent templates.

**Comment by wvhn** [comment]
It is talking about global scope which users like me might be looking for, whose code has been broken by the changes. But I don‘t want to re-open this discussion which might be annoying for you.
Maybe phrasing ‚global scope within the template‘ would avoid misunderstandings.
