### ISSUE TITLE
Access to context variables after render

### ISSUE THREAD

**Issue by cosmorob** [twigphp/Twig#3539]
Hi!

Is it possible to retrieve the context (possibly updated due to `{% set last_name = (first_name + last_name) %}`) variables **after** the template has been fully rendered?
I would like to give users the option to define certain logic with the twig templates and I am interested in the variable values afterwards.

Cheers!

**Comment by stof** [comment]
no, there is no way to do that (btw, note that even if this was possible, it might still not be useful for your case due to the scoping behavior of various Twig tags, which would not make variables being changed at the root of the template)

**Comment by cosmorob** [comment]
Ok, thank you anyways for the quick reply!
