### ISSUE TITLE
Add html_entity_decode as a native filter

### ISSUE THREAD

**Issue by DocFX** [twigphp/Twig#3542]
Hello :)

Maybe I missed something but at the moment there are only two ways to handle HTML strings:
- raw
- escaped

When we use the striptags filter, PHP converts html entities automatically. I.e. "`é`" becomes "`&eacute;`".

Then there's no way to fall back to the original string.

The best way is to implement a custom Twig filter to do that when needed on a project.
The other way around is to use `{% autoescape %}` strategy.

But since that means that Twig natively has a way to convert a string with side effects that can't be reverse through it, shouldn't there be a native `html_entity_decode` filter, with parameters?

I suppose the second parameter is a little tricky since it's an "or'ed" mask of PHP constants, and the last one the encoding.

This is for Twig 3+.

```
{% autoescape 'html' %}
    {{ '&eacute;'|raw }} {# outputs: &eacute; #}
    {{ '&eacute;'|e }} {# outputs: &amp;eacute; #}
    {{ '&eacute;'|striptags }} {# outputs: &amp;eacute; #}
    {{ '&eacute;'|raw|striptags }} {# outputs: &amp;eacute; #}
    {{ '&eacute;'|striptags|raw }} {# outputs: &eacute; #}
{% endautoescape %}

{% autoescape false %}
    {{ '&eacute;'|e }} {# outputs: &amp;eacute; #}
    {{ '&eacute;'|raw|striptags }} {# outputs: &eacute; #}
    {{ '&eacute;'|striptags|raw }} {# outputs: &eacute; #}
{% endautoescape %}
```

**Comment by stof** [comment]
In 10+ years using Twig, I never had a need for `html_entity_decode` in a Twig template. What is your use case exactly ?

**Comment by DocFX** [comment]
- Use CKeditor (like fos-ckeditor-bundle)
- Use paste or any text.
- CKeditor transforms the text in HTML entities (i.e. é becomes &eacute;)
- Use any text preview (like a view-list of items, like a home page or news list)
- Use twig `|slice` for that, like "My new content preview teasing with cut down te...", and add "..."
- Break on any HTML entity
- Have a text like "My new content preview teasing is now brok&eac..."

**Comment by stof** [comment]
Well, you could have the same issue if `|slice` cuts text inside a HTML tag rather that inside a HTML entity. The actual issue is that you are trying to get a slice of a HTML source with a filter that is not aware of HTML.

**Comment by DocFX** [comment]
True, which is why:
- HTML tag problem is natively solved with [`striptags`](https://twig.symfony.com/doc/3.x/filters/striptags.html) filter.
- HTML entity problem is not natively solved.

**Comment by DocFX** [comment]
For the record, this is what I've done so far all the time I needed this, until I decided to open this PR. :) 

```php
    /**
     * @return array
     */
    public function getFilters(): array
    {
        return [
            new TwigFilter('html_entity_decode', 'html_entity_decode', ['is_safe' => ['html']]),
        ];
    }
```

**Comment by stof** [comment]
@DocFX the `html_entity_decode` function does not perform HTML escaping. So it should definitely not be marked as safe for HTML if you want to avoid XSS issues.

**Comment by DocFX** [comment]
That's probably true. I do trust user input (VERY exceptionnally) on this particular use. 

Thanks for the note!

**Comment by stof** [comment]
@DocFX trusting user input on a particular use is better done with `|raw`, because it makes it visible to other devs (and the future you) that you have trusted it. And it avoids mistakes where the same filter is reused elsewhere where it should not have been trusted.

**Comment by fabpot** [comment]
Closing as this is not something we will add in core.

**Comment by HolgerNetgrade** [comment]
use case:

we obtain a string with HTML entities from the database, e.g. a product title:

`This &amp; That`

then we need to pass this string as an URL argument, but we can't have the `amp;` part. for example, this is what we need:

`mailto:a@b.c?subject=This%20%26%20That`

so it seems we first should decode `&amp;` into `&` to then filter it through `url_encode` for the desired result.

assembling query strings in twig seems common enough to justify `html_entity_decode` in core.

there is no twig alternative to `&amp;` -> `%26`, is there?

**Comment by stof** [comment]
Storing HTML entities in your database for the product title is not the good practice (as this also means you will have to disable auto-escaping in Twig when displaying the title, which then increases security risk in case some database content is not properly pre-escaped).
If your project has such need, you can define a custom filter.

**Comment by HolgerNetgrade** [comment]
as for good practice for database storage, sure, if only that was applicable to 99% of real world applications where we have no control over how the frameworks we build on do things.

will do the custom filter then, but twig failed me in saving time on this one, which ultimately is its purpose.
