### ISSUE TITLE
Warning: property_exists() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by williamdes** [twigphp/Twig#3544]
```
Warning: property_exists() expects parameter 2 to be string, array given
#4 ./../../php/Twig/Extension/CoreExtension.php(380): display
#3 ./../../php/Twig/Extension/CoreExtension.php(372): displayWithErrorHandling
#2 ./../../php/Twig/Extension/CoreExtension.php(395): doDisplay
#1 ./../../php/Twig/Extension/CoreExtension.php(57): twig_get_attribute
#0 ./../../php/Twig/Extension/CoreExtension.php(1537): property_exists
```

Reported to our Sentry back-end. Affects only one user (estimated number) and 3 events where sent

**PHP**: 7.4.20
**Server Os**: Linux
**Webserver**: Apache 2
**phpMyAdmin**: 5.1.1

**Comment by stof** [comment]
Well, this looks like a case where you passed an array as the attribute name in the `attribute()` function (or as the key in the `foo[my_var]` notation)

**Comment by fabpot** [comment]
Are you able to reproduce the error?

**Comment by williamdes** [comment]
> Are you able to reproduce the error?

No, I had a try but could not
Maybe you can or just add a line of code to avoid the warning
As I said it seems to affect nobody so you can also close it

**Comment by fabpot** [comment]
Thank you for your fast reply. Let's close then.
