### ISSUE TITLE
Accessing numeric index: dot notation vs array notation

### ISSUE THREAD

**Issue by DarkBee** [twigphp/Twig#3549]
When using the dot notation on a numeric indexed array I'm getting strange results when using the dot notation to access the value:

`{{ Items[0][0].Value }}` **vs** `{{ Items.0.0.Value }}`

I'd imagine this would yield the same output for both statements, however this is not true as the dot notation throws an exception (e.g. example below).

Not sure if this is the desired behaviour or a bug when using the dot notation on an array.
Especially because when I use an extra `0` for the index, I get the "correct" output, which I'd expect would throw an error

The strange part I see in the compiled code, see attached below, is the `0.0` part after `$this->source`. 
This also occurs when using `{{ Items.1.0.Value }}`

**Input array:**
```
array(2) {
  [0]=>
  array(2) {
    [0]=>
    array(2) {
      ["Value"]=>
      string(7) "Value 1"
      ["Value2"]=>
      string(8) "Value2 1"
    }
    [1]=>
    array(2) {
      ["Value"]=>
      string(7) "Value 2"
      ["Value2"]=>
      string(8) "Value2 2"
    }
  }
  [1]=>
  array(2) {
    [0]=>
    array(2) {
      ["Value"]=>
      string(7) "Value 2"
      ["Value2"]=>
      string(8) "Value2 2"
    }
    [1]=>
    array(2) {
      ["Value"]=>
      string(7) "Value 2"
      ["Value2"]=>
      string(8) "Value2 2"
    }
  }
}
```

**Template:**
```
{{ Items[0][0].Value }}
{{ Items.0.0.Value }}
```

**Expected output**
```
Value 1
Value 1
```
**Actual output**

```
Twig\Error\RuntimeError
Key "Value" for array with keys "0, 1" does not exist.
```

------

**Template with extra zero as index**

```
{{ Items[0][0].Value }}
{{ Items.0.0.0.Value }}
``` 

**Unexpected output**
```
Value 1
Value 1
```

[Demo 1: assumed correct dot notation](https://twigfiddle.com/o26oty/2)

[Demo 2: assumed incorrect dot notation](https://twigfiddle.com/o26oty)

-----

**Compiled source for this issue**

- dot notation (`Items.0.0.Value`) 

```
echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, twig_get_attribute($this->env, $this->source, twig_get_attribute($this->env, $this->source, (isset($context["Items"]) || array_key_exists("Items", $context) ? $context["Items"] : (function () { throw new RuntimeError('Variable "Items" does not exist.', 1, $this->source); })()), 0.0, [], "any", false, false, false, 1), 0, [], "any", false, false, false, 1), "Value", [], "any", false, false, false, 1), "html", null, true);
```

- array notation (`Items[0][0].Value`)

```
echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, twig_get_attribute($this->env, $this->source, twig_get_attribute($this->env, $this->source, (isset($context["Items"]) || array_key_exists("Items", $context) ? $context["Items"] : (function () { throw new RuntimeError('Variable "Items" does not exist.', 1, $this->source); })()), 0, [], "array", false, false, false, 1), 0, [], "array", false, false, false, 1), "Value", [], "any", false, false, false, 1), "html", null, true);
```
- dot notation (`Items.1.0.Value`) 
``` 
echo twig_escape_filter($this->env, twig_get_attribute($this->env, $this->source, twig_get_attribute($this->env, $this->source, (isset($context["Items"]) || array_key_exists("Items", $context) ? $context["Items"] : (function () { throw new RuntimeError('Variable "Items" does not exist.', 2, $this->source); })()), 1.0, [], "any", false, false, false, 2), "Value", [], "any", false, false, false, 2), "html", null, true);
```

**Comment by stof** [comment]
The issue is that `0.0` is parsed as a float here.
The `.` operator is meant to be used with an identifier following it, which excludes numbers. Your attempt is entering undefined land.

**Comment by DarkBee** [comment]
That makes sense, I mean I wouldn't use the dot notation here myself. But it made me wonder because of a [question](https://stackoverflow.com/questions/68489271/translating-json-into-twig-looping-arrays) on stackoverflow that was asked.
So I guess this means this issue will not be solvable and one should not use the dot notation for this purpose?

**Comment by stof** [comment]
yeah, the `[]` notation should really be used for that use case.

**Comment by DarkBee** [comment]
Alright updated my answer on SO for future reference. Thanks for the insight
