### ISSUE TITLE
Static call in TwigFunction

### ISSUE THREAD

**Issue by jodou92** [twigphp/Twig#3551]
Hello, 

I'm using PHP8 and I have an issue with `src/TwigFunction.php`
The line 97 `return $this->options['is_safe_callback']($functionArgs);` can raise Fatal error when the method called is not static. 
It seems that `TwigFilter.php` has this issue too.

Not sure how to handle this ?

**Comment by stof** [comment]
`is_safe_callback` must be a PHP callable. All PHP callables can be called this way (by definition of being callables)
