### ISSUE TITLE
Cryptic Node "1" does not exist for Node "Twig\Node\Node" error when extending with if-statement outside blocks

### ISSUE THREAD

**Issue by 7ochem** [twigphp/Twig#3553]
If I do:

`sub.twig`:
```twig
{% extends 'main.twig' %}
world Hello!
```

with `main.twig`:
```twig
{% block main %}
    Hello world!
{% endblock %}
```

I get the error:
> A template that extends another one cannot include content outside Twig blocks. Did you forget to put the content inside a {% block %} tag?

Which is great! 👍🏻 

Now I got the following error when having a similar situation, but then with an empty if node:

`sub.twig`:
```twig
{% extends 'main.twig' %}

{% if some_condition %}

{% endif %}
```

with `main.twig`:
```twig
{% block main %}
    Hello world!
{% endblock %}
```

I get the cryptic error:
> An exception has been thrown during the compilation of a template ("Node "1" does not exist for Node "Twig\Node\Node".") in "sub.twig".

Surprisingly, when I remove the blank line from within the if, then I get the `Did you forget a {% block %} tag?` error again.

Although the `Node "1"` error told me in which template the error took place, it was still a bit confusing and hard to discover what was wrong.

-----

Twig fiddle: https://twigfiddle.com/1819h5
Encountered this on Twig 2.14.6 (latest) and Twig fiddle also shows the same error on v3.

**Comment by fabpot** [comment]
Closing as this has been fixed in 3.x
