### ISSUE TITLE
Option to change Cache-File Structure

### ISSUE THREAD

**Issue by magicW** [twigphp/Twig#3555]
We use Ext4 as FileSystem-Type. After read this Benchmark (https://medium.com/@hartator/benchmark-deep-directory-structure-vs-flat-directory-structure-to-store-millions-of-files-on-ext4-cac1000ca28) we tried to change the directory structure to a flat structure without using the directories in twig-folder.

This give us a 10% better Performance (we have >1.000 Templates). But i think my Implementation is not very clean. This is because I couldn't adjust an own FilesystemCache through the option 'cache' - it is only Possible by Calling "setCache" on Environment.

I think it will be better to define a own cache-Class over the option or to introduce an option to use a flat directory-structure.

**Comment by lyrixx** [comment]
According to the blog post you linked, 

> Conclusion 2: stick to custom wisdom and use a deep directory file system. However, be wary of the performance cost of too many directory levels.

Do you really notice a performance boost?

**Comment by stof** [comment]
Twig only uses a depth of 1 for its directory structure, which seems fine according to that blog post (and keeps things good also for servers that don't use ext4)

**Comment by magicW** [comment]
I'm afraid I was too hasty. The performance was significantly improved, but deteriorated again over time. I think we have rather a problem because there are more and more files (templates come from the DB and are constantly updated). More likely I have to write a cache derived from the TagAwareCacheInterface and remove old files. Or do you have another idea where that can come from? (The TTFB increases by approx. 10-20% in the first 24 hours - after Cache Clear the times are "normal" again)
