### ISSUE TITLE
Commonmark extensions

### ISSUE THREAD

**Issue by kbond** [twigphp/Twig#3558]
Is there any interest in a general way to attach commonmark extensions to the converter (via a di tag)?

**Comment by lyrixx** [comment]
I'm sorry, but I did not understand your issue. Can you elaborate? Thanks

**Comment by kbond** [comment]
Sorry, should have elaborated more. It is currently a bit difficult to add commonmark extensions when using the twig-markdown/extra-bundle. This is what I had to do:

```php
final class LeagueMarkdownFactory
{
    private iterable $extensions;

    /**
     * @param \League\CommonMark\Extension\ExtensionInterface[] $extensions
     */
    public function __construct(iterable $extensions)
    {
        $this->extensions = $extensions;
    }

    public function __invoke(): LeagueMarkdown
    {
        $converter = new CommonMarkConverter();

        foreach ($this->extensions as $extension)
        {
             $converter->getEnvironment()->addExtension(extension);
        }

        return new LeagueMarkdown($converter);
    }
}
```

The above is wired up with all the commonmark extensions I'd like to use as `league.markdown.factory`. Then I override the `twig.markdown.default` from twig/extra-bundle:

```yaml
twig.markdown.default: # override service from twig/extra-bundle
    class: Twig\Extra\Markdown\LeagueMarkdown
    factory: '@league.markdown.factory'
```

It'd be ideal if this could be handled in the twig/extra-bundle itself so multiple 3rd party bundles could register their own commonmark extensions.

I'm thinking the above factory could live in twig/markdown-extra and, in twig/extra-bundle, if commonmark is detected, use that factory for creating the `LeagueMarkdown` service and a DI tag for adding extension services.

Hope that makes more sense.

**Comment by stof** [comment]
Well, having a factory to create the LeagueMarkdown looks weird to me here. The factory responsible for registering extensions is only necessary to instantiate the CommonMarkConverter (which can then be injected as a dependency in the LeagueMarkdown instantiated normally by the DI container)

**Comment by kbond** [comment]
Correct, the factory would only be for commonmark.

For context, I'm working on a bundle that provides a commonmark extension. The only way I've found to wire it up and utilize these libraries is to completely take over the `twig.markdown.default`.

**Comment by fabpot** [comment]
@kbond Would you like to work on a PR?

**Comment by kbond** [comment]
Yep, absolutely 🙂
