### ISSUE TITLE
Testing if filter is defined / exists

### ISSUE THREAD

**Issue by DocFX** [twigphp/Twig#3560]
Hello!

This is more a question than an issue (probably): is there any way to have a ```filter_exists()``` function in Twig, or to test ```{% if filter is defined %}``` (or anything like that), and if not, shouldn't there be one?

Thanks! :)

**Comment by stof** [comment]
there is no such features. Filter definitions are something that impact the compile-time of the template.

**Comment by DocFX** [comment]
So in short, you mean it can't be implemented a generic way?

I tried to do it myself, but stopped at the point I was wondering if anything actually existed. :)

**Comment by stof** [comment]
Well, I don't think it can be implemented without changing the whole Twig architecture, as Twig currently cannot compile a template using an undefined filter.

**Comment by fabpot** [comment]
Twig can compile a template with an undefined filter, just call `registerUndefinedFilterCallback()` on your env and implement the logic you want.
I have not had a look at how it would be possible to implement what you are asking for, but at first sight, that's not something I would want to add to Twig even if possible.

**Comment by DocFX** [comment]
Yeah, just close it, no pb. I was just wondering if I missed anything or so. :)
