### ISSUE TITLE
PHP extension "twig.so"

### ISSUE THREAD

**Issue by louisyssel** [twigphp/Twig#3561]
Hi,

I am not a developer, but is installing Phaseanet, and it requires the PHP extension for twig. Typically like dnf install php-twig.

I have twig installed on the server, but need it as a .so to add to the extensions section in the php.ini.

Please assist.

Thanks
Louis

**Comment by stof** [comment]
The PHP extension of Twig was an optional feature of Twig 1.x to improve performance on PHP 5.x. It is not necessary to use Twig and it does not exists anymore in recent Twig versions (the performance improvements of PHP 7 made the extension unnecessary and it had a high maintenance cost).
