### ISSUE TITLE
FilesystemCache.php -> mkdir(): File exists

### ISSUE THREAD

**Issue by nickbo90** [twigphp/Twig#3564]
Sometimes we've got an error in our errorlog saying 'mkdir(): File exists'. 

file        : /composer/vendor/twig/twig/src/Cache/FilesystemCache.php
line        : 50
message     : mkdir(): File exists

Possible solution
`if (!is_dir($dir) && !is_file($dir)) {
`
Twig version: # 3.3.3 (2021-09-17)
PHP: 8.0.x

**Comment by stof** [comment]
The `mkdir` call is already inside a `is_dir` check. But that does not avoid race conditions where the directory gets created by another process between the 2 calls.

And that's exactly why the `mkdir` call on line 50 of FilesystemCache is using the silencing operator to silence the PHP warning and handle the error reporting on its own (rechecking whether the directory exists before complaining).

If your logging infrastructure logs silenced warnings, that's where you have an issue, not in Twig (if silencing the error is not enough to hide it from your logging, there is strictly *nothing* that can be done by Twig to avoid it).
