### ISSUE TITLE
Extraneous whitespace left between HTML tags in compiled output?

### ISSUE THREAD

**Issue by downhiller** [twigphp/Twig#3565]
I asked this on S.O. many years ago:

https://stackoverflow.com/questions/33921439/can-we-make-twig-remove-whitespace-when-its-compiled-rather-than-when-its-ren/33922380

In essence, I didn't like that twig would output unnecessary whitespace between the HTML tags in the output it generated.  E.g. 

```
    <section>
                            <h2>blah blah</h2>    
    </section>
```

when I would rather `<section><h2>blah blah</h2></section>`

My one-liner fix is detailed in the accepted answer on that page.

I wonder if someone would like to make a PR for it.  I've never done one, and frankly don't have the time/inclination to learn how to do so right now.  But as a one-liner it would presumably take seconds for someone who knows what they're doing!

**Comment by stof** [comment]
Well, Twig is not a templating engine for HTML. It is a generic templating engine (you can use it to output something else than HTML). Removing irrelevant HTML whitespaces automatically would require tying Twig to HTML (and it is very hard, as whitespaces are not always irrelevant in HTML, which also depends on the CSS rules being applied). Your one-liner will break all those use-cases of Twig

Twig already has some features allowing to remove some whitespaces at compile time (which then cannot remove whitespaces coming from displayed values of course): https://twig.symfony.com/doc/3.x/templates.html#whitespace-control

**Comment by fabpot** [comment]
This topic has been discussed many times here (you can use other libraries in combination with Twig to achieve what you want). Closing for the same reasons as before.
