### ISSUE TITLE
Unexpected behavior with booleans

### ISSUE THREAD

**Issue by sylvaindeloux** [twigphp/Twig#3579]
When using boolean vars in Twig templates, `false` value is misinterpreted with `default()` function:

    {% set my_boolean = true %}
    {{ dump(my_boolean|default(true)) }} // true => OK
    {{ dump(my_boolean|default(false)) }} // true => OK

    {% set my_boolean = false %}
    {{ dump(my_boolean|default(true)) }} // true => KO, should be false
    {{ dump(my_boolean|default(false)) }} // false => OK

Tested with Twig v3.3.3.

**Comment by jderusse** [comment]
This is the expected behavior.

From [the documentation](https://twig.symfony.com/doc/3.x/filters/default.html)

> The default filter returns the passed default value if the value is undefined or empty, otherwise the value of the variable:

`false` is evaluated to `empty` and the value of default is used.

**Comment by stof** [comment]
What you need in your case is probably the `??` operator rather than then `default` filter
