### ISSUE TITLE
Documentation Website's version alert should link to different version, same topic 

### ISSUE THREAD

**Issue by sheanhoxie** [twigphp/Twig#3580]
**Issue**
Looking up documentation for twig's _include_ statement, & clicking the alert message "... Switch to the documentation for Twig 1.x, 2.x" **link takes the user away from the topic to the documentation root**. This happens on all documentation pages.

**Expected**
When browsing a topic, and offered a link to switch to another version, one expects to be kept on topic where possible.

**Actual**
All links point to their version's documentation root

**Supporting info**
This alert is present at the top of all twig.symfony.com/doc documentation pages:
> You are reading the documentation for Twig 3.x. Switch to the documentation for [Twig 1.x](https://twig.symfony.com/doc/1.x/). [2.x](https://twig.symfony.com/doc/2.x/).

The "switch to" links offered for each version, always point to their version's documentation root:
* 1.x - https://twig.symfony.com/doc/1.x/
* 2.x - https://twig.symfony.com/doc/2.x/

Many like pages exist between versions
- Extending Twig documentation
-- https://twig.symfony.com/doc/1.x/advanced.html
-- https://twig.symfony.com/doc/3.x/advanced.html
- Include statement documentation
-- https://twig.symfony.com/doc/2.x/tags/include.html
-- https://twig.symfony.com/doc/3.x/tags/include.html

**Comment by axel37** [comment]
Yes please ! Especially since many search engine queries point to older versions.

This always happens to me :

- Search the web for a twig topic
- Realize it brought me to the Twig `2.x` docs
- Click the `3.x` link
- Must now navigate manually to the desired topic

**Comment by fabpot** [comment]
Fixed now.
