### ISSUE TITLE
Suggestion: Allow `constant()` as `array` name in `attribute()`

### ISSUE THREAD

**Issue by ThomasLandauer** [twigphp/Twig#3583]
I have a constant `App\Entitiy\User::FOO = 'bar'`
In the template, I have an array `bar`. And I want to access its values like so:
```twig
{{ attribute(constant('App\\Entitiy\\User::FOO'), 'name') }}
```
But this isn't working:
> Impossible to access an attribute ("name") on a string variable ("bar").

So I'm suggesting to allow passing a `constant()` there too.

It is already allowed as *second* argument of `attribute()`:
```twig
{{ attribute(bar, constant('App\\Entitiy\\User::NAME')) }}
```

**Comment by stof** [comment]
The first argument of `attribute` is the value in which you want to read the attribute. Passing the string `bar` there (the value of your constant) does not make sense.
So there is no bug here. Twig does exactly what you asked it to do, and reports that it is a mistake.
