### ISSUE TITLE
Using `literal-string` type for Static Analysis

### ISSUE THREAD

**Issue by craigfrancis** [twigphp/Twig#3589]
Regarding [PR 3573](https://github.com/twigphp/Twig/pull/3573).

I appreciate you're busy, but I'm not sure what to do now?

I'm hoping that it's a small change, that shouldn't cause anyone any issues... on the basis that `$template` for `createTemplate()` (the template source), is already defined as a string, and it should come from the developer (not containing unsafe user data)... where the `literal-string` type does support concatenation (to reduce the amount of false positives, and help adoption)... and anyone doing anything different, which causes an error, should probably be checked (and I'm happy to help with that).

**Comment by fabpot** [comment]
Closing as there is already a PR. What's the point of creating an issue?

**Comment by craigfrancis** [comment]
It's been open a month, and I don't know how to progress the PR?

**Comment by fabpot** [comment]
That's how open-source works. I'm doing that in my free time.

**Comment by craigfrancis** [comment]
And I *really* appreciate you, and this project... we use Twig all the time, and it makes templating much easier, and is why I'm trying to contribute (personally, I'm more on the security side, where my background is in auditing, and this patch is to try and address an issue that comes up occasionally).
