### ISSUE TITLE
Using PHP 7.4 the variable inside the html tag is joining with the previous value.

### ISSUE THREAD

**Issue by brennosacramento** [twigphp/Twig#3591]
Code
```
<div class="main-row {{ rows.class }}">
        <div class="container">
            <div class="row">
            </div>
        </div>
  </div>
```
  
  {{ rows.class }} = full-width

Result
```
<div class="main-rowfull-width">
        <div class="container">
            <div class="row">
            </div>
        </div>
  </div>
```

After rendering, the engine does not respect the space between classes and joins the 2 values.

This error I saw happen in PHP 7.4, when switching to PHP with a version lower than 7.4, it worked fine.

**Comment by stof** [comment]
I cannot reproduce this. Are you running this with Twig directly or as part of a bigger stack where other things can affect it (either something that runs after the Twig rendering on the output, or a custom Twig loader changing the input, or a customization of Twig) ?

**Comment by brennosacramento** [comment]
This is taking place within OpenCart 3.0.2.0. I exemplified a code. In OpenCart when I change the PHP version the rendering modifies. I've tested up to PHP 7.2 successfully working. When I use it in PHP 7.4, the result fails because CSS classes merge (doesn't respect spaces between them)

**Comment by stof** [comment]
if you cannot reproduce this with pure Twig (which I could not), it means it is something that depends on the whole OpenCart setup, and so should be reported to OpenCart.

Also, are you using the latest version of Twig ? When searching the issue tracker, I found some references saying that older versions of Twig were affected by something like that (before we worked on fixing compat with PHP 7.4 around the time of the PHP 7.4 release). Latest releases are 1.44.5, 2.14.7 and 3.3.3.

**Comment by feedmeastraycat** [comment]
I have this issue on PHP 7.4.33 and Twig 1.44.7.

Examples:
* `class="button {{ classes|join(' ') }}"` generates `class="buttontiny"` for example.
* `{{ "Global"|trans }}: {{ tickets_last_30_days_all|number_format(0) }}` generates `Global:30` *(or whatever the tickets variable contains)*

I took an example from the documentation: `{{ foo ?: 'no' }} is the same as {{ foo ? foo : 'no' }}` 
Which outputs: `<div>no is the same asno</div>`

The only fix I have found is to make sure I concat it within the same {{ }}. 

I understand this is a very tiny cry for help. 🙂 I have this old service I need to keep running for some more time. But I have to change the server. And I'm not sure I can downgrade to PHP 7.3. I feel like 7.4 is bad enough. There is a lot of twig files to go through and fix this on.

So Im just posting this just in case.


Edit: 
[This fix](https://stackoverflow.com/a/62554618) seems to be working. But I dont feel confident enough to validate that it wouldnt cause any other issues. 🙂 *(And it's on line number 178 in Lexer.php in twig 1.44.7).*

**Comment by stof** [comment]
We still need a reproducer, because none of us was ever able to reproduce that with Twig and PHP 7.4 alone, so there must be something else involved in it. Previous report was about OpenCart, not about raw Twig, without any info about what kind of customizations OpenCart might be doing to Twig (the Twig core team does not know about OpenCart)

**Comment by feedmeastraycat** [comment]
@stof Ok, thanks for a quick reply! I will see if I can reproduce it more "clean". My setup runs on Silex 2 and Twig 1 (Symfony 3.4). I don't have OpenCart. Maybe its something with Silex somehow. Even though I can fix it within Lexer.php in the Twig source code. 

It might take me a couple of days before I have the time but I will see if I can reproduce it in a fresh project using Silex. 🙂 


Edit one hour later:
Couldnt leave it alone but it might be something related to the server or something. I noticed that the issue does not appear in my local docker env. I have a test app I will test on the same server and see how that goes.

**Comment by feedmeastraycat** [comment]
@stof Thanks for your time but it looks like it was indeed my bad. 🙂 Not sure how, if it was some cache or just a misstake, but I did NOT have 1.44.7 on the server. Once I figured it out and upgraded it worked as expected.
