### ISSUE TITLE
Maybe twig_to_array should array cast scalars

### ISSUE THREAD

**Issue by chx** [twigphp/Twig#3597]
Right now `|merge(something)` just fails if `something` is a scalar. If `twig_to_array` ran the `(array)` cast over scalars then it would work and perhaps even you could even call it working correctly. 

If this is not desirable, perhaps rename it to `twig_iterable_to_array`?

**Comment by GromNaN** [comment]
Hello @chx. A naive question: why not wrap the value in an array? Like this: `|merge([something])`

**Comment by chx** [comment]
Because, alas, `something` is coming from a large number of upstream sources and it isn't type safe :( sometimes it is already an array.

**Comment by GromNaN** [comment]
The [iterable](https://twig.symfony.com/doc/2.x/tests/iterable.html) test can be used for such situation.

`list|merge(something is iterable ? something : [something])`

Regarding your suggestion, I think it will not be accepted: strict types provide early feedback to the developers and reduce bugs.

**Comment by stof** [comment]
I agree with @GromNaN here

**Comment by fabpot** [comment]
I agree as well, that's not a behavior we want in Twig.
