### ISSUE TITLE
bug: rendering 2 templates concurrently causes twig to return completely wrong results when a non-blocking operation takes place.

### ISSUE THREAD

**Issue by azjezz** [twigphp/Twig#3599]
ref: symfony/symfony#41520

Twig uses output buffer when rendering the template, this causes issues when rendering multiple templates at once, as one template will capture the output buffer of another.

The fix that needs to happen is to make `doRender` abstract in the `Template` class, and `display` would simply `echo` the result of `doRender`.

meaning that instead of echoing the result in the rendered template, we store it in a variable, and return that instead.

However, one BC-break resulting from this is that twig functions that print/echo content, will no longer work.

---

To reproduce:

```php
<?php

declare(strict_types=1);

use Psl\Async;
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

require __DIR__ . '/../vendor/autoload.php';

final class User {
    public function getUsername(): string {
        return 'azjezz';
    }
}

final class Account {
    public function getUser(): User {
        // simulate a lazy query, the database driver is non-blocking
        Async\sleep(0.02);
        return new User();
    }

    public function getThings(): array {
        // simulate a lazy query, the database driver is non-blocking
        Async\sleep(0.02);
        return [];
    }
}

Async\main(function (): int {

    $loader = new FilesystemLoader(__DIR__ . '/templates');
    $twig = new Environment($loader);

    $account = new Account();

    [$a, $b, $c, $d] = Async\parallel([
        static fn() => $twig->render('user.html.twig', ['account' => $account]),
        static fn() => $twig->render('user.html.twig', ['account' => $account]),
        static fn() => $twig->render('user.html.twig', ['account' => $account]),
        static fn() => $twig->render('user.html.twig', ['account' => $account]),
    ]);

    var_dump($a, $b, $c, $d);

    return 0;
});
```

where `user.html.twig` template contain the following:

```twig
{% extends 'layout.html.twig' %}

{% block cotnent %}
  {% for something in account.things %}

  {% endfor %}
{% endblock %}
```

and `layout.html.twig` contains the following:

```twig
<div>
Hello, {{ account.user.username }}
<hr />
{% block cotnent %}{% endblock %}
</div>
```

The result:

```
> php example/main.php
string(128) "<div>
    Hello, azjezz
    <hr />
        azjezz
    <hr />
        azjezz
    <hr />
        azjezz
    <hr />
        </div>
"
string(24) "<div>
    Hello, </div>
"
string(24) "<div>
    Hello, </div>
"
string(24) "<div>
    Hello, </div>
"
```

What happens in the example above is that when twig starts rendering a template, and reachs a non-blocking I/O call ( in this case, it's the sleep() ), it suspends the current fiber, and `Async\parallel` will switch to another task, `ob_start()` could have been called by 1 task, and another task can finish first and call `ob_get_clean()`, but it will also get all the content that has been outputed.

**Comment by azjezz** [comment]
The example above uses `azjezz/psl:2.0.x` to run the tasks concurrently, same could be reproduced with `amphp/amp:v3`

**Comment by azjezz** [comment]
to simplify, here's a pure php 8.1 example: https://3v4l.org/TlMHE ( the async/await functions in there are not correct implementations of async/await, but they serve their purpose )

**Comment by azjezz** [comment]
another "fix" ( at the application level ) is to render templates in a queue using a wrapper.

using Revolt ( works with Amphp, Psl, and any other Revolt based library ):

```php
use Revolt\EventLoop;
use Twig\Environment;

final class Twig {
    private array $queue = [];
    private bool $busy = false;

    public function __construct(
      private Environment $environment
    ) {}
  
    public function render(string $template, array $context = []): string
    {
        if ($this->busy) {
            $suspension = EventLoop::createSuspension();
            $this->queue[] = $suspension;
            $suspension->suspend();
        }

        $this->busy = true;
        
        try {
            return $this->environment->render($template, $context)
        } finally {
            $suspension = array_shift($this->queue);
            if (null !== $suspension) {
              $suspension->resume();
            } else {
              $this->busy = false;
            }
        }
    }
}
```

This means that every call to render will wait for anything previous render operation to finish, while not blocking the event loop.

**Comment by stof** [comment]
Removing the usage of the output buffer for building the output will likely not be possible in a minor version, as it will break any Twig extension relying on the usage of `echo` to render things in the output. It will force all compiled code to return things instead of displaying them.
Also, I fear that this will force to remove the `Environment::display()` method (which relies on the usage of `echo`, without applying output buffering).

**Comment by azjezz** [comment]
> Also, I fear that this will force to remove the Environment::display() method (which relies on the usage of echo, without applying output buffering).

Not really, we can keep it and do `echo $this->render(...);`, but it is kinda of useless at that point.

**Comment by azjezz** [comment]
I'm closing this issue as i personally have no effort to put into working on it.

I think it would a good idea to document that the behavior in a concurrent application is unpredictable, and twig should be avoided in such an environment.

more information: https://twitter.com/azjezz/status/1476295773616848896?s=20

**Comment by fabpot** [comment]
Latest versions of Twig 3 and Twig 4 use `yield` instead of output buffers. I suppose this fixes this issue.
