### ISSUE TITLE
Feature request: Block syntax for calling macros

### ISSUE THREAD

**Issue by midnightmonster** [twigphp/Twig#36]
For a macro defined like this:

```
{% macro fancy_box(content,title) %}
  <div class="box">
    <div class="top"><h3>{{ title }}</h3></div>
    <div class="content">{{ content }}</div>
    <div class="bottom"></div>
  </div>
{% endmacro %}
```

Instead of having to define all arguments first (or type them inline), it would be more natural to call it like this:

```
<div class="sidebar">
  {% layout.fancy_box('Recent Posts') %}
    <ul>
      {% for link in recentPosts %}
        <li><a href="{{ link.href }}">{{ link.title }}</a></li>
      {% else %}
        <li>No recent posts</li>
      {% endfor %}
    </ul>
  {% end layout.fancy_box %}
</div>
```

Something like this lets designers easily build up abstractions on unavoidably messy chunks of HTML, such as one may often end up with when (e.g.) building resilient layouts that support older browsers. Of course we can already achieve the same thing with macros if we're willing to define the content chunk with a {% set %} tag first, but that hides the structure of the document: A 'fancy_box' is essentially an elaborate wrapper of its main content, and its better if it can look like it. We could also achieve something more like my desired calling syntax by writing fancy_box as a filter, but then we have design matters wrapped up in our PHP extension to Twig.

As far as the actual behavior of this syntax, the block content should become the first argument, pushing other arguments down. (So the block content becomes 'content', the first argument becomes 'title'.) This won't always make sense for macros not designed to be used this way, but I don't think that matters very much. I don't know if the tags can be implemented like I've suggested. Maybe it has to be:

```
{% use layout.fancy_box('Recent Posts') %}
  ...
{% enduse %}
```

Or something like that.

**Comment by seb-jean** [comment]
Can we reconsider this issue please?

**Comment by emarthinsen** [comment]
I'm running into an issue where this would be super helpful also. My idea syntax would look something like this:

```twig
{% import "timeline.twig" as timeline %}

{% run timeline.ascending %}
  {{ timeline.startNode ... }}
  {{ timeline.milestoneNode ... }}
  {{ timeline.contentNode ... }}
  {{ timeline.contentNode ... }}
  {{ timeline.contentNode ... }}
  {{ timeline.completedNode ... }}
{% endrun %}
```

I'm not sure "run" is the right word, but the idea is the same. There is some HTML that is required at the top of my timeline (e.g., the opening UL tag) and some that is required at the end of the timeline (similarly, the closing UL tag).
