### ISSUE TITLE
embed array has null value throws error

### ISSUE THREAD

**Issue by kitsguru** [twigphp/Twig#3603]
In earlier versions of Twig you could have an empty (null) value as one of the array elements.

I recently upgraded to Twig 3.3 and the following code broke:
`
{% embed  [site.folder  ~ '/header_hp.twig', module.header.template_hp , "header/nav-plus-branding.twig"] ignore missing %}{% endembed %}
`
**module.header.template_hp** is empty so an error is thrown: 

Argument 1 passed to Twig\Environment::getTemplateClass() must be of the type string, null given, called in /Volumes/J/@projects/yaaws5/html/www/lib/classes/vendor/twig/twig/src/Environment.php on line 309

In resolveTemplate I added a simple check on $name to see if it is empty and skip to next value if it is.

`
    public function resolveTemplate($names): TemplateWrapper
    {
        if (!\is_array($names)) {
            return $this->load($names);
        }

        foreach ($names as $name) {
            try {
                if (empty($name)) {
                    continue;
                }
                return $this->load($name);
            } catch (LoaderError $e) {
            }
        }

        throw new LoaderError(sprintf('Unable to find one of the following templates: "%s".', implode('", "', $names)));
    }
`

This is a fast fix from my point of view. I have not done pull requests before so if someone could address this, It would be appreciated. OR if there is a better approach I would like to hear any suggestions.

**Comment by GromNaN** [comment]
Hello, have you tried to apply `|filter` on the list to remove empty values before sending them to the `embed` tag?

Types where added in the branch 3.x in April 2019 #2971

**Comment by stof** [comment]
Passing `null` in that array was never intended to work. It only worked by "luck" due to not having type checks

**Comment by kitsguru** [comment]
yet the error message says must be of type and includes null as a value. It is somewhat misleading then if you can pass null by itself but not within the array. Changing hundreds of embeds to add a filter as opposed to 3 lines in twig to avoid the error seems to me to be the obvious fix.

Error checking is the function of the code not the template imho.

**Comment by stof** [comment]
Well, do you actually have hundreds of embeds producing `null` values ?

**Comment by kitsguru** [comment]
Actually yes, it is a very large application used by 50 clients. I configure the app using yaml files. I depended on the functionality of the null value since it was accepted and not documented to not use it. It worked up to Twig 2.14 and broke in 2.15. Recently I decide to update to Twig 3

The first value is a site custom template value, the second is the configuration value from the yaml file and the last one is the fall back. 

I have multiple variants of the embedded file from which the client can choose. If there is no custom template, it uses the selected variant if selected, otherwise uses the fallback.

I guess the other thing to do would be to set the config value in the yaml file to the fallback. OR I can fork twig and maintain my fix myself. I still wish the fix could be added though.

**Comment by kitsguru** [comment]
This might be related to an earlier report on ignore missing not working:
https://github.com/twigphp/Twig/issues/3085
