### ISSUE TITLE
Check data types in default CoreExtension

### ISSUE THREAD

**Issue by shyim** [twigphp/Twig#3609]
I am currently upgrading a project for PHP 8.1. I get lot of mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/twig/twig/src/Extension/CoreExtension.php on line 1098

It's pretty hard to find which template/variable is triggern this. Maybe it makes sense to check the type in the CoreExtension and throw an error?

**Comment by spackmat** [comment]
I have that with the `trim` filter.

Would it be against a best practice to allow and handle `null` for the several string filters? In PHP 8.1 I get a deprecation notice for `trim`:

> Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated

That is correct, as PHP's `trim()` only wants to work on strings, but from my point of view the corresponding Twig filter should simply return `null` or an empty string on a `null` input to avoid verbose workarounds for nullable strings.

I can provide a PR implementing this small change, maybe also for the other affected string related filters as mentioned in the first post. Returning an empty string in that cases would reflect the current behavior, but in an explicit way: `trim(null)` returns an empty string and raises the deprecation notice mentioned above.

Another and maybe better solution would be a `?|` construct just like PHPs `?->` null safe operator to handle those type issues. But I don't know how complicated this would be to implement. Maybe that is another issue.

Edit: That nullsafe operator stuff already is another issue 😉: #3260

**Comment by fabpot** [comment]
See #3617
