### ISSUE TITLE
Php 8.1

### ISSUE THREAD

**Issue by BackuPs** [twigphp/Twig#3612]
Please fix php 8.1 deprecated issues   Twig Version 1

            `function twig_number_format_filter(Environment $env, $number, $decimal = null, $decimalPoint = null, $thousandSep = null)`

number_format function does not allow NULL for decimal.  It needs a empty string or 0

**Comment by GromNaN** [comment]
Hello @BackuPs. Thank you for reporting this issue. Could you please take some time to contribute a fix.

**Comment by BackuPs** [comment]
the solution is simple.... just change

`function twig_number_format_filter(Environment $env, $number, $decimal = null, $decimalPoint = null, $thousandSep = null)`

into 

`function twig_number_format_filter(Environment $env, $number, $decimal = 0, $decimalPoint = '' , $thousandSep = '')`

**Comment by xabbuh** [comment]
Did you encounter any issues with the current code? From what I can see, `$decimal` is overwritten with `0` inside `twig_number_format_filter()` if `null` is passed so that `null` is never passed to `number_format()`.

**Comment by BackuPs** [comment]
if somebody calls twig_number_format_filter with only $env and $number the filter will raise a warning in php 8 and in php 9 a fatal.  Changing the function filter as suggested will prevent future issues.

**Comment by BackuPs** [comment]
You are right..... it revert to $defaults[0];  i completely missed that one.  Thanks for pointing that out to me.  I figured it out.... someone had called set NumberFormat to 'NULL' ,' ,' , '.'

Please close.

**Comment by stof** [comment]
@BackuPs as the other of the issue, you are able to close it yourselves.

Anyway, closing this issue.
