### ISSUE TITLE
release a PHP 7.1 and PHP 8.1 Twig version

### ISSUE THREAD

**Issue by williamdes** [twigphp/Twig#3613]
As said in by @fabpot (https://github.com/phpmyadmin/phpmyadmin/issues/16746#issuecomment-993014793) "we can probably re-add PHP 7.1 support for a "special" release."

Problem explained: https://github.com/phpmyadmin/phpmyadmin/issues/16746#issuecomment-991394796
PHP version drop: https://github.com/twigphp/Twig/pull/3410

Here is the commit list that should be picked on a branch to be released before the PHP 7.2 version restriction. Other solution, remove the PHP version restriction, release and put it back.

Commit/PR/issues list (used https://github.com/twigphp/Twig/search?q=8.1&state=closed&type=issues):
- https://github.com/twigphp/Twig/pull/3536
- https://github.com/twigphp/Twig/pull/3535
- https://github.com/twigphp/Twig/issues/3534
- https://github.com/twigphp/Twig/issues/3494
- https://github.com/twigphp/Twig/pull/3554
- https://github.com/twigphp/Twig/pull/3505
- https://github.com/twigphp/Twig/pull/3552
- **parts of this commit: https://github.com/twigphp/Twig/commit/47201dc3bccf6ebfa507612f8e5402ad0570820f**

Let me know what I can do.

This is the last step for us to provide a PHP 7.1 and 8.1 compatible version in a clean way. Else I will have to apply patches manually after composer install. Everyone would agree that it would be way less clean than a special release.

**Comment by fabpot** [comment]
Which branch do you need? 1.x, 2.x, or 3.x?

**Comment by williamdes** [comment]
> Which branch do you need? 1.x, 2.x, or 3.x?

Seems like 3.x was never PHP 7.1 compatible: https://github.com/twigphp/Twig/commit/70dc9983097202bcd2be86064b75b1ff8da3e292

This is why we require Twig 2.9+ or 3.x at phpMyAdmin 5.1.x: https://github.com/phpmyadmin/phpmyadmin/blob/679eca275ae31d986c6caf0f6d16898b0e52ac9a/composer.json#L60

So that would be from 2.x
