### ISSUE TITLE
twig/extra-bundle 3.3.5: Warning: Undefined array key 1 when clearing cache

### ISSUE THREAD

**Issue by stephanvierkant** [twigphp/Twig#3620]
I've just upgraded to twig/extra-bundle 3.3.5 and I get this error message:

> In XmlDumper.php line 178:
>                                   
>   Warning: Undefined array key 1  

Content of `$callable` (from [here](https://github.com/symfony/dependency-injection/blob/ba94559be9738d77cd29e24b5d81cf3b89b7d628/Dumper/XmlDumper.php#L178)) is:

```
array:1 [
  0 => Symfony\Component\DependencyInjection\Reference {#12667
    -id: "twig.markdown.league_common_mark_converter_factory"
    -invalidBehavior: 1
  }
]

```

I'm using CommonMark in my project (without using `markdown-extra`). I think #3559 is related.

**Comment by kbond** [comment]
I've confirmed the issue, working on a fix.

**Comment by fabpot** [comment]
New release with the fix published.

**Comment by insekticid** [comment]
Same error here - Symfony 5.4 and PHP 8.1 when Twig\Extra\TwigExtraBundle\TwigExtraBundle is enabled - twig/extra-bundle 3.3.6, league/commonmark 2.1.1

edit: same problem in Symfony 6.0 🐱‍👤

**Comment by kbond** [comment]
Ugh... you're right, it isn't fixed - looking into it. Sorry about this.
