### ISSUE TITLE
Make template line number passing in GetAttrExpression to twig_get_attribute optional

### ISSUE THREAD

**Issue by chx** [twigphp/Twig#3624]
https://github.com/twigphp/Twig/pull/2944 have added this feature but if it is not desirable for some reason there's no way to switch it off.

Even a method inaccessible from the templates would be enough for me -- I have a [node visitor](https://www.drupal.org/project/twig_capture) which tries to get a good representation of expressions like `{{ foo.bar }} ` and it compiles `foo.bar` for this reason and it worked with older Twig versions because I got a string

    twig_get_attribute($this->env, $this->source, ($context["foo"] ?? null), "bar", [], "any", false, false, true)

which, while valid PHP code, is also a string and I used it as an array key.

but now the representation is line bound and can no longer be used as an identifier:

    twig_get_attribute($this->env, $this->source, ($context["foo"] ?? null), "bar", [], "any", false, false, true, 178)

which is a problem :/ 

Note `ag 'raw.*getTemplateLine' vendor/twig/twig/src/Node/` returns this only one so I think there are no other problems.

**Comment by stof** [comment]
Well, the compilation output is not meant to produce the same PHP code for Twig code being at different locations. This would forbid us to have an accurate error reporting in Twig (which was requested in many issues at the time it was **not** accurate due to relying on guessing the line number), while adding this restriction for no benefit for Twig itself

**Comment by stof** [comment]
@chx for your use case, maybe using the string representation of the AST as key would work better.

**Comment by stof** [comment]
side note: I saw the PR on your fork removing the line number for non-debug compilations. But we do want the location in errors in prod too.

**Comment by chx** [comment]
I am intrigued by the "string representation of the AST" please tell me more.

However, please also note https://github.com/symfony/symfony/issues/41025

**Comment by stof** [comment]
`Node::__toString` dumps only attributes and child nodes. If your container-aware service is not stored in one of them, it won't be dumped there.
