### ISSUE TITLE
Deprecated - round() - CoreExtension - 547

### ISSUE THREAD

**Issue by Parovozzzik** [twigphp/Twig#3625]
Hello, colleagues!

<b>Deprecated</b>:  round(): Passing null to parameter #1 ($num) of type int|float is deprecated in <b>/code/vendor/twig/twig/src/Extension/CoreExtension.php</b> on line <b>547</b><br />

Thanx!

**Comment by fabpot** [comment]
Can you create a pull request to fix the issue? We've fixed similar issues in the past, so past PRs can help you find how to do it.

**Comment by Parovozzzik** [comment]
Done.

**Comment by danielkerr** [comment]
fixed last night.

**Comment by danielkerr** [comment]
just use composer to update to the latest twig
