### ISSUE TITLE
Problem with showing the right day of the week with date code

### ISSUE THREAD

**Issue by paulemailoctopus** [twigphp/Twig#3632]
I just tested the date code in the following format: {{ date_time_variable | date("FORMAT_STRING", "OPTIONAL_TIMEZONE") }}

I wanted to use Chicago time zone, so I did it like that:

{{ "now"| date("l", "America/Chicago") }}

Unfortunately, the code displayed "Thursday", while it should show "Wednesday".

Any ideas why that might have happened?

**Comment by fabpot** [comment]
As we are mostly proxying t the PHP Intl functions, the issue cannot come from Twig.
