### ISSUE TITLE
Suggestion: New strategy for `escape` filter for Vue.js expressions `{{ foo }}`

### ISSUE THREAD

**Issue by ThomasLandauer** [twigphp/Twig#3633]
When a text contains strings like `{{ foo }}`, Vue.js runs wild. What about a dedicated strategy for this?

(The `js` strategy does escape it, but since it escapes everything, the resulting text is unreadable.)
https://twig.symfony.com/doc/2.x/filters/escape.html

**Comment by stof** [comment]
I'm not convinced this should be in Twig core (the EscaperExtension allows registering custom strategies, although I'm not sure TwigBundle makes that easy in Symfony projects).
