### ISSUE TITLE
Allow expressions in apply tag

### ISSUE THREAD

**Issue by Bilge** [twigphp/Twig#3634]
I have come across an interesting problem where I want to conditionally apply an `apply` block. Consider the following example adapted from [the documentation](https://symfony.com/doc/current/mailer.html#inky-email-templating-language):

```twig
{% apply inky_to_html|inline_css(source('@styles/foo.css'), source('@styles/bar.css')) %}
    {# ... #}
{% endapply %}
```

This is fine in theory, but suppose we want to toggle between inlining and not based on the presence of a `debug` variable. Twig is not very well equipped to accommodate this. First, we should need to extract our CSS content to a `set` tag so they can be inserted at various positions without duplicating the CSS source files list.

```twig
{% set css %}
{{ source('@styles/foo.css') }}
{{ source('@styles/bar.css') }}
{% endset %}

{% apply debug ? inky_to_html : inky_to_html|inline_css(css) %}
<head>
    {% if debug %}
    <style>{{ css }}</style>
    {% endif %}
</head>
{% endapply %}
```

However, this is invalid since expressions are not parsed in this context.

>Twig\Error\SyntaxError 
>Unknown "debug" filter.

**Comment by stof** [comment]
I suggest you do that with separate `{% apply %}` tags in a if instead (potentially using a block to reuse the content between 2 places. Allowing expressions there is hard, because the condition is not something we can resolve at compile time to apply the filters in the AST.
