### ISSUE TITLE
Named argument support

### ISSUE THREAD

**Issue by kbond** [twigphp/Twig#3635]
As @weaverryan and I have been working on Twig/Live components in `symfony/ux`, we've come across a few areas where named argument support would be valuable. This issue is intended to track/discuss adding/improving support for this in twig.

1. (probable bug) Filters/functions using `is_variadic` snake-cases the keys. This issue (and a possible solution) is explained fully in https://github.com/twigphp/Twig/issues/3475.
2. Support in `twig_get_attribute` for PHP8+
    ```twig
    {{ object.method(prop1='value', prop2='value') }}
    ```
3. Support in filters/functions without `is_variadic` for PHP8+
    ```twig
    {{ var|filter(prop1='value', prop2='value') }}

    {{ function(prop1='value', prop2='value') }}
    ```
4. Could `:` be used as an assignment operator instead of `=`?
    ```twig
    {{ var|filter(prop1: 'value', prop2: 'value') }}

    {{ function(prop1: 'value', prop2: 'value') }}

    {{ object.method(prop1: 'value', prop2:'value') }}
    ```

I understand there might be technical limitations that make supporting any/all of these impossible. This was the case with [named argument support in macros](https://github.com/twigphp/Twig/issues/929#issuecomment-493525160).

**Comment by Bilge** [comment]
~~Your link to the macro issue just links back to this issue.~~

**Comment by kbond** [comment]
Thanks @Bilge, fixed.

**Comment by tacman** [comment]
@kbond Any chance of seeing this before Symfony 6.2 goes into beta?  As mentioned in a linked issue here, this format wouldn't break anything, and looks quite clean.

```twig
{{ foo(barValue: 'bar', booValue: 'boo') }}
```

**Comment by kbond** [comment]
Twig has different release schedule than Symfony so this can be added to twig in a feature release (anytime). There is a plan to migrate twig to Symfony core and I believe this is issue is on the radar.

**Comment by joeworkman** [comment]
I am creating a global that references a class. I would love to be able to have named parameters with my class functions. I assume that your suggested features would also cover that? This look perfect to me. I have a couple of functions that could potentially have a lot of parameters. It would be nice to be able to selectively only use parameters as I see fit.

**Comment by xabbuh** [comment]
Given that Twig 4 will require PHP 8.2+ (see #3881) named arguments support for macros could also be an option then.

**Comment by DenuxPlays** [comment]
It is possible now: https://twig.symfony.com/doc/3.x/templates.html#named-arguments

**Comment by tacman** [comment]
> It is possible now: https://twig.symfony.com/doc/3.x/templates.html#named-arguments

Yes, but many of us are waiting for an alternative to the = syntax and the more typical 

(edit: fix syntax)

     {{ data|convert_encoding(from:'iso-2022-jp', to:'UTF-8') }}

**Comment by fabpot** [comment]
See #4209 for named args using a colon instead of an equal sign.

**Comment by Bilge** [comment]
> It is possible now: https://twig.symfony.com/doc/3.x/templates.html#named-arguments

Why can't I find the PR that introduced this?

**Comment by fabpot** [comment]
> > It is possible now: https://twig.symfony.com/doc/3.x/templates.html#named-arguments
> 
> Why can't I find the PR that introduced this?

It has been introduced here: https://github.com/twigphp/Twig/commit/a59dcde3

**Comment by Bilge** [comment]
It's been supported for circa 12 years?

**Comment by tacman** [comment]
yes.  And it's really helpful for something like the translation filter, since the count argument comes after the domain, so unless I need the domain, I use

```twig
{{ 'num_of_obj'|trans(count=data.object_count)|title }}
```

Also, it makes the code clearer sometimes when there are multiple arguments.

**Comment by stof** [comment]
@tacman the syntax you show is not about named arguments. It uses a single positional argument containing an associative array (and it is already a valid syntax in Twig since Twig 1.0).

I think you consider this as named arguments because of inspiration from Javascript. However, Javascript does not support named arguments at all (and because of that, APIs are often designed using a single `options` object taking a JS object instead of using optional arguments).

**Comment by tacman** [comment]
Hmm, in
```twig
      trans(count=data.object_count)
      {{ 'owner_browse'|trans(domain='routing') }}
```

Aren't _count_ and _domain_  named arguments here?  

```php
    public function trans(string|\Stringable|TranslatableInterface|null $message, array|string $arguments = [], ?string $domain = null, ?string $locale = null, ?int $count = null): string
```

Perhaps my terminology is wrong.  Regardless, I look forward to the named argument support in https://github.com/twigphp/Twig/commit/a59dcde3, which as a (huge) bonus also includes passing arguments to block, which I'm _really_ excited about.  Currently I use `with` to pass data to a block, and it's always felt awkward.

**Comment by stof** [comment]
@tacman I meant the proposal you suggested in https://github.com/twigphp/Twig/issues/3635#issuecomment-2291342429

**Comment by tacman** [comment]
oops!  Fixed.

**Comment by fabpot** [comment]
> Perhaps my terminology is wrong. Regardless, I look forward to the named argument support in [a59dcde3](https://github.com/twigphp/Twig/commit/a59dcde3), which as a (huge) bonus also includes passing arguments to block, which I'm _really_ excited about. Currently I use `with` to pass data to a block, and it's always felt awkward.

a59dcde3 is nothing new as it was committed 12 years ago ;)

**Comment by tacman** [comment]
Sigh....

Indeed, https://github.com/twigphp/Twig/commit/9e6f5a76189e82b6dd812b85749d016da28aa231 is exciting, named arguments AND 

* Add support for named arguments to the `block`, and `attribute` functions

which I'm hoping means that I can replace

```twig
                        {% with {data: museum} %}
                            {{ block('museumInfo') }}
                        {% endwith %}

                            {{ block('museumInfo', {data: museum) }}
```

**Comment by fabpot** [comment]
>     * Add support for named arguments to the `block`, and `attribute` functions
> 
> 
> which I'm hoping means that I can replace
> 
> ```
>                         {% with {data: museum} %}
>                             {{ block('museumInfo') }}
>                         {% endwith %}
> 
>                             {{ block('museumInfo', {data: museum) }}
> ```

No, it "just" means that `block` and `attribute` are not special anymore in the way their arguments are parsed; they will behave like any other function. So `block(name: "foo")` for instance will become valid.

**Comment by stof** [comment]
@tacman no. The `block` function does not have any argument to replace the context. This does not change.

**Comment by tacman** [comment]
Thanks for the clarification.  I guess I should find that thread about 4.0 features and make a request...

**Comment by tacman** [comment]
Does this only work when calling twig functions?  I'm passing a service into my twig template, I'm getting an error when calling it using named arguments (equals or colons).

```twig
                {% for item in kv.select(table.name).iterate(table.name, [], 3) %} {# works #}
                {% for item in kv.select(table.name).iterate(table.name, max=3) %} {# fail #}
```

>> Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",").

The method:

```php
    public function iterate(string $table = null,
                            ?array $where = [],
                            int    $max = 0,
                            array $order = [],
                            ?bool  $associative = null,
                            int    $depth = 512,
                            int    $flags = PDO::FETCH_ASSOC,
    ): \Generator
    {
```

Tried with both latest twig and 3.x-dev

update: fixed in #4391

:-)  Thanks!

**Comment by fabpot** [comment]
@tacman See #4391
@kbond #4391 adds support for named arguments on macros, which I think is the last missing piece of everything you asked for in the issue.

**Comment by kbond** [comment]
Awesome! Let's close this as complete. Thanks Fabien! ❤️
