### ISSUE TITLE
Cache invalidateTags issue with twig/extra-bundle and Redis

### ISSUE THREAD

**Issue by PanzerLlama** [twigphp/Twig#3636]
I noticed a problem when using the {% cache "cache_name" tag('tag_name') %}.

This creates an entry in Redis in a form of:
`"...:tag_name\x00tags\x00"`

while "Adapter/AbstractTagAwareAdapter.php" `invalidateTags()` seems to look for`"...:\x00tags\x00tag_name"` so calling that method always fails to invalidate the tagged entries.

The "Adapter/TagAwareAdapter.php" uses the key name as `$tag.static::TAGS_PREFIX` in InvalidateTags while the other `self::TAGS_PREFIX.$tag.`

How to replicate:
1) Create a template with `{% cache "cache_name" tag('tag_name') %}`
2) Call `RedisTagAwareAdapter->invalidateTags(['tag_name']);`

No tagged entries get invalidated.

        "symfony/framework-bundle": "5.4.*",
        "twig/cache-extra": "^3.3",
        "twig/extra-bundle": "^3.3",
        "twig/twig": "^3.0"

**Comment by edouardgat** [comment]
Have the same issue.
@PanzerLlama I solved it by using this config in `services.yaml`, most specifically `.twig.cache.inner` and `twig.cache`

```
  Symfony\Component\Cache\Adapter\RedisAdapter:
    arguments: ['@snc_redis.default']

  Symfony\Component\Cache\Adapter\RedisTagAwareAdapter:
    arguments: ['@snc_redis.default']

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments: ['@snc_redis.session']

  .twig.cache.inner:
    class: Symfony\Component\Cache\Adapter\RedisTagAwareAdapter
    arguments: ['@snc_redis.default']

  twig.cache:
    class: Symfony\Component\Cache\Adapter\RedisTagAwareAdapter
    arguments: ['@snc_redis.default']
```

For the Arguments of RedisTagAwareAdapter, you choose the one you use. `snc_redis.default` is my Redis client :
```
snc_redis:
  clients:
    default:
      type: phpredis
      alias: default
      dsn: '%env(REDIS_HOST_URL)%/%env(int:REDIS_DB_DEFAULT)%'
      logging: '%kernel.debug%'
```

**Comment by fabpot** [comment]
Looks like something related to Symfony, not Twig.
