### ISSUE TITLE
Feature request: allow comments within twig code

### ISSUE THREAD

**Issue by tremby** [twigphp/Twig#3637]
I frequently want to add comments in areas comments aren't currently allowed, for example alongside options passed to filters, alongside parameters passed to macros, or alongside data passed to include calls.

Sometimes a chunk of data passed to a filter or include statement is several lines long, or a macro has several parameters which are easily mixed up at a glance. At present the only option I have to add hints to the code is to add a comment before or after the entire block of code. For object literals I could add dummy extra properties to serve as comments, but this doesn't seem like a good idea. That doesn't help with macro arguments, either.

Example:

```
{# I can currently comment here #}
{{ my.macro(
  # It would be nice to be able to comment here
  "whatever", # Or here
)|attr({
  # It would be nice to be able to comment here
  class: "whatever", # Or here
}) }}

{% include "whatever" with {
  # It would be nice to be able to comment here
  data: "whatever", # Or here
} %}
```

**Comment by fabpot** [comment]
As we have never had this request before and because it would complexity the code a lot, I suggest closing here.
