### ISSUE TITLE
Filename is not shown in input on file selection

### ISSUE THREAD

**Issue by LucileDT** [twigphp/Twig#3643]
### Scenario
- create a Symfony 4.4 project
- enable Bootstrap 4 Twig theme `form_themes: ['bootstrap_4_layout.html.twig']`
- create an entity with an attribute containing a filepath (e.G. `Post` which has `id` and `picture`)
- create a form with a FileType (e.G. `PostType` with `$builder->add('picture', FileType::class, [])`
- create a controller to display and manage the form (e.G. `PostController`)
- open the corresponding page in your web browser
- on the File input, click on Browse, select a picture and validate the selection

### Expected behavior
When the file manager pop up closes, the file name is written in the file input to show it as been selected and will be submitted.

### Current behavior
Nothing shows the picture has been selected: its corresponding input has the same look as before file selection. The file selection works as expected and it is send on form submission.

### Comment
According to [this post](https://stackoverflow.com/questions/65330180/filename-not-shown-in-symfony-5-2-in-form), it seems to also be a problem under Symfony 5

**Comment by fabpot** [comment]
This should be posted on Symfony as nothing here is hosted in this repo.
