### ISSUE TITLE
Wrong result in format_date filter

### ISSUE THREAD

**Issue by garak** [twigphp/Twig#3646]
Quick reproducer:

* create a new project and require` "twig/intl-extra": "^3.3"`
* use the following script

```php
<?php

require_once 'vendor/autoload.php';

$twig = new \Twig\Environment(new \Twig\Loader\ArrayLoader([]));
$twig->addExtension(new \Twig\Extra\Intl\IntlExtension());
$date = new \DateTime('2022-01-01');
echo $twig->getExtension(\Twig\Extra\Intl\IntlExtension::class)->formatDate($twig, $date, null, 'LLLL Y', null, 'gregorian', 'it');
```

Expected output: "Gennaio 2022" (Italian for "January 2022")
Actual output: "Gennaio 2021" 

The same applies to French (output "janvier 2021"). I didn't try further languages. English is fine.

**Comment by fabpot** [comment]
This cannot be related to Twig as we are mostly proxying to PHP Intl functions.

**Comment by stof** [comment]
To me, this is the same issue than #3669: confusing the `Y` and `y` placeholders in the pattern. The calendar year is `y`.
