### ISSUE TITLE
[BC-Break] Twig 2.14.9 broke `filter` tag with `spaceless`

### ISSUE THREAD

**Issue by althaus** [twigphp/Twig#3647]
Hi,

we've upgraded our (legacy) code base with the security release Twig 2.14.11 and suddenly had an issue with totally strange rendering on some pages. I've tracked the issue down to the 2.14.9 release.

We've got some old templates using the `filter` tag with the `spaceless` filter:

~~~
{% filter spaceless %}
  something A
{% endfilter %}

{% filter spaceless %}
  something B
{% endfilter %}

{% filter spaceless %}
  something C
{% endfilter %}
~~~

Quote simpliefied but basically multiple tags in a bunch of blocks and template inheritance. The result is that all tags render the content of the **first** tag:

~~~
something A
something A
something A
~~~

I've checked the commits and found nothing obvious which could result in such a strange behaviour. 😕 

Cheers
Matthias

**Comment by fabpot** [comment]
There is something else going on. It works well for me:

https://twigfiddle.com/n0az6m

**Comment by janpetersen** [comment]
The setup has to be a bit different: https://twigfiddle.com/n0az6m/2

This reproduces the bug.

**Comment by xabbuh** [comment]
I am looking into it.

**Comment by xabbuh** [comment]
#3654 will probably fix this
