### ISSUE TITLE
PHP 8.0: @ Error Suppression operator does not silent fatal errors

### ISSUE THREAD

**Issue by psociety** [twigphp/Twig#3648]
TY FOR CREATING TWIG!!

Since PHP 8.0, the following errors are not longer suppressed:

[E_ERROR](https://www.php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-error) - Fatal run-time errors.
[E_CORE_ERROR](https://www.php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-core-error) - Fatal errors occurred in PHP's initial startup.
[E_COMPILE_ERROR](https://www.php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-compile-error) - Fatal compile-time errors (from Zend engine).
[E_USER_ERROR](https://www.php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-user-error) - User-triggered errors with [trigger_error()](https://www.php.net/manual/function.trigger-error.php) function.
[E_RECOVERABLE_ERROR](https://www.php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-recoverable-error) - Catchable fatal error.
[E_PARSE](https://www.php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-parse) - Compile-time parse errors.
(Extracted from https://php.watch/versions/8.0/fatal-error-suppression)

And twig seems to like @ a lot:
![Screenshot from 2022-02-17 12-20-37](https://user-images.githubusercontent.com/29523682/154471232-4097c006-7566-436f-8207-a01da8e20354.png)

Are there any plans to stop using @?

**Comment by fabpot** [comment]
I don't think this is related to PHP 8.0. Maybe you have an error handler that behaves incorrectly.
Not using @ is not possible (yet), even in recent PHP versions.
