### ISSUE TITLE
Warnings with PHP 8.1.2

### ISSUE THREAD

**Issue by rivets** [twigphp/Twig#3649]
There some missing return types on functions  in Node.php that cause warnings to appear.

**Comment by nicolas-grekas** [comment]
Please be more specific, or better: send a fix.

**Comment by rivets** [comment]
In Markup.php count should return an int and jsonSerialize mixed (I think - it works)
In Node.php count should return an int

**Comment by nicolas-grekas** [comment]
That's fixed since Twig v2.14.7 see https://github.com/twigphp/Twig/pull/3552

If you're using Twig 1, it's not maintained anymore. Otherwise please upgrade.

**Comment by rivets** [comment]
I did a composer update to 3.3.8 (from 3.3.2) and it wasn't fixed in the code that resulted, so I don't know what happened there
