### ISSUE TITLE
Please update the `.gitattributes` on each branch

### ISSUE THREAD

**Issue by williamdes** [twigphp/Twig#3658]
Could you update the `.gitattributes` on each branch ?

I often have to add some of your files to a delete list before creating release tarballs at phpMyAdmin

Thank you in advance ;)

**Comment by williamdes** [comment]
```
        vendor/twig/twig/doc/ \
        vendor/twig/twig/test/ \
        vendor/twig/twig/.github/ \
        vendor/twig/twig/README.rst \
        vendor/twig/twig/.travis.yml \
        vendor/twig/twig/.editorconfig \
        vendor/twig/twig/.php_cs.dist \
        vendor/twig/twig/drupal_test.sh \
        vendor/twig/twig/.php-cs-fixer.dist.php \
        vendor/twig/twig/src/Test/ \
```
Source: https://github.com/phpmyadmin/phpmyadmin/blob/6f6913855f11f8fc3f5f03a31dc739b6d35d0eda/scripts/create-release.sh#L180-L189

Here is the current list but I do not expect all to be excluded, some are because I know they are not useful for anyone in production

This is the script I use to detect such files in vendor folders: https://github.com/phpmyadmin/phpmyadmin/blob/QA_5_1/scripts/check-release-excludes.sh

**Comment by fabpot** [comment]
Does it make a difference? We are already excluding the "bigger" files/directories:

```
/doc/** export-ignore
/extra/** export-ignore
/tests export-ignore
/phpunit.xml.dist export-ignore
```

If you want to filter more, I suppose you can do so on your side, but I would not remove the README file for instance by default.

**Comment by williamdes** [comment]
> Does it make a difference? We are already excluding the "bigger" files/directories:
> 
> ```
> /doc/** export-ignore
> /extra/** export-ignore
> /tests export-ignore
> /phpunit.xml.dist export-ignore
> ```
> 
> If you want to filter more, I suppose you can do so on your side, but I would not remove the README file for instance by default.

Yeah, it makes a difference not having your dev files on all production servers of the world
I think if you multiply to the twig installs it makes quite a lot of data ^^

Removing the Readme never was my request ;)
There is some files to be kept: LICENCE, README, CHANGELOG
All other useless files should be removed
Most libraries already do that for the same purpose
Let me know your thoughts

Some libs keep test and phpunit configs for Debian packaging people to be able to run the tests but that's mostly the only exception

> I suppose you can do so on your side

Nope, normal users can not do that :/

**Comment by fabpot** [comment]
So, can you tell me which files should be excluded on top of what we already excluded? We are already removing doc and tests files for instance.

**Comment by williamdes** [comment]
> So, can you tell me which files should be excluded on top of what we already excluded? We are already removing doc and tests files for instance.

Sure, sorry for the delay

I checked each branch using the ZIP file (built with `git archive` command on GitHub servers)

### 1.x 2.x 3.x

Ref: https://github.com/twigphp/Twig/archive/refs/heads/3.x.zip
Ref: https://github.com/twigphp/Twig/archive/refs/heads/2.x.zip
Ref: https://github.com/twigphp/Twig/archive/refs/heads/1.x.zip

- `.github` folder
- `.editorconfig` file
- `.gitattributes` file
- `.gitignore` file
- `.php-cs-fixer.dist.php` file
- `doc` folder (yeah it is there but empty..)

**Comment by fabpot** [comment]
see #3728
