### ISSUE TITLE
Twig source with data_uri

### ISSUE THREAD

**Issue by mmarton** [twigphp/Twig#3659]
Hi!

I've run into a bug with the source filter when I tried to inline images as data_uri. The referenced solution in the doc: https://twig.symfony.com/doc/3.x/filters/data_uri.html (and here https://github.com/twigphp/Twig/issues/3145) is

```twig
{{ source('path_to_image')|data_uri }}
```
however this gives me a

> Unable to find template "/build/images/symfony-logo.37a94574.svg" (looked into: <path>/templates, <path>/vendor/symfony/twig-bridge/Resources/views/Form).

I've created a reproducer: 
https://github.com/mmarton/twig-source-image

1st commit is the standards symfony install,
2nd commit is all the modifications I made (https://github.com/mmarton/twig-source-image/commit/5198b559f31ff656810ab8afd8a424c403a36dca)

A solution could be to
- fix the source to work outside of template folders
- or to allow the data-uri to work with paths as requested here: https://github.com/twigphp/Twig/issues/3145 Imho this would make more sense because the filter starts with dumping the filecontent to a tmp file to guess it's content-type (https://github.com/twigphp/html-extra/blob/2.x/HtmlExtension.php#L59).

**Comment by fabpot** [comment]
Shouldn't it be `{{ source('build/images/symfony-logo.svg')|data_uri }}` instead? Abd the `build` directory should be defined as a template path.

**Comment by mmarton** [comment]
That's what I'm doing here: https://github.com/mmarton/twig-source-image/blob/main/templates/base.html.twig#L20
except the build directory defined as a template path. It doesn't feel right, it has nothing to do with templates.

**Comment by fabpot** [comment]
No, you're using `asset` in your example.

**Comment by mmarton** [comment]
Yes, because I'm using asset versioning.

I've added `public/build` to the template paths (still feels a bit hacky) and tried 7 different versions, and only one was sortof working. But I had to hardcode the version number

```twig
<!-- without version -->
<img src="{{ source('symfony-logo.svg')|data_uri }}" alt="Symfony inlined 1"><br>
<img src="{{ source('images/symfony-logo.svg')|data_uri }}" alt="Symfony inlined 2"><br>
<img src="{{ source('build/images/symfony-logo.svg')|data_uri }}" alt="Symfony inlined 3"><br>

<!-- with version -->
<img src="{{ source('symfony-logo.37a94574.svg')|data_uri }}" alt="Symfony inlined 4"><br>
****works: <img src="{{ source('images/symfony-logo.37a94574.svg')|data_uri }}" alt="Symfony inlined 5"><br>
<img src="{{ source('build/images/symfony-logo.37a94574.svg')|data_uri }}" alt="Symfony inlined 6"><br>

<!-- with encore -->
<img src="{{ source(asset('build/images/symfony-logo.svg'))|data_uri }}" alt="Symfony inlined 7">
```

so there is no way to use encore + asset versioning + source + data_uri together?

**Comment by stof** [comment]
@mmarton `source` is about getting the source code of something that can be found by a template loader. So you need to make sure that what you pass as argument respects that rule.

**Comment by mmarton** [comment]
@stof Yeah, and it feels weird to use it for anything else other than templates. I don't want to add my build folder as a template path, because it's not. I would like to use the data_uri filter with a path as It is suggested in my opening comment.

> allow the data-uri to work with paths as requested here: https://github.com/twigphp/Twig/issues/3145 Imho this would make more sense because the filter starts with dumping the filecontent to a tmp file to guess it's content-type (https://github.com/twigphp/html-extra/blob/2.x/HtmlExtension.php#L59).

**Comment by fabpot** [comment]
The template paths are not just for templates. You can also use it for images for instance. The goal is to control where Twig can read files. So, letting any path in Twig is not something we will support.

**Comment by mmarton** [comment]
I didn't say any, the build folder is already in the docroot and accessible. And there are already encore_* twig helpers for it.
It would be nice to be able to use encore and data_uri together

**Comment by stof** [comment]
The encore functions are not letting you read arbitrary file. they produce *paths* to them, not the content

**Comment by mmarton** [comment]
I feel I'm running circles here.
I don't want encore to read files, and I don't van source() to access any part of my project. I understand the security risks.
All I wanted was to use the data_uri filter for a file that is inside my build folder to inline some images. But seeing the resistance I will continue to use a userland solution for it.
I just thought it would be a nice to have capability for the framework and for data_uri

**Comment by stof** [comment]
Well, to generate a data-uri, you need the content of the file. So you definitely want to read it.

**Comment by fabpot** [comment]
In any case, you can also create your own filter/function to achieve what want very easily. Here, we are just saying that it won't be part of Twig core.
