### ISSUE TITLE
Provide a `|dedup` filter to remove duplicate values from an array?

### ISSUE THREAD

**Issue by mpdude** [twigphp/Twig#3660]
Would you support a new `|dedup` filter that could remove duplicate values from an array based on `array_unique`? Or is there a policy in place that limits what kinds of filters you accept here in core Twig?

**Comment by fabpot** [comment]
The rule of thumb is that we don't want people to manipulate arrays in the templates themselves as they should be "prepared" in the PHP code. I know that we have the merge function, but I don't want to add more of them.
So, I would say that adding dedup is probably not a good fit for the official repo.

**Comment by mpdude** [comment]
Thank you @fabpot for the clarification!
