### ISSUE TITLE
twig 3.0.0 and php 8.1: depeicated messages

### ISSUE THREAD

**Issue by hannesdorn** [twigphp/Twig#3661]
Hi!

I fixed some deprecated messages which are related to php 8.1
[twig-3.0-depricated-in-php-8.1.patch.txt](https://github.com/twigphp/Twig/files/8231760/twig-3.0-depricated-in-php-8.1.patch.txt)

**Comment by stof** [comment]
Looking at the patch you attached, those deprecated have all been fixed already in Twig 3.x. Use an uptodate version of Twig instead of 3.0.0 (the latest version is 3.3.8)
