### ISSUE TITLE
Test failure for format_date.test

### ISSUE THREAD

**Issue by bryceharrington** [twigphp/Twig#3662]
```
There was 1 failure:

1) Twig\Extra\Intl\Tests\IntegrationTest::testIntegration with data set #8 ('format_date.test', '"format_date" filter', '', array('\n{{ '2019-08-07 23:39:12'|fo...ime }}'), false, array(array('--DATA--\nreturn [];\n--EXPEC...:12 PM', '\nreturn [];\n', '', '\nAug 7, 2019, 11:39:12 PM\n7...:12 PM')), '')
"format_date" filter (in format_date.test)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'Aug 7, 2019, 11:39:12 PM\n
-7 août 2019 à 23:39:12\n
+7 août 2019, 23:39:12\n
 23:39\n
 07/08/2019\n
-mercredi 7 août 2019 à 23:39:12 Temps universel coordonné\n
+mercredi 7 août 2019 à 23:39:12 temps universel coordonné\n
 11 oclock PM, Coordinated Universal Time\n
 \n
 Aug 7, 2019\n
 7 août 2019\n
 11:39:12 PM'

/tmp/autopkgtest.X712UD/build.dFd/src/src/Test/IntegrationTestCase.php:254
/tmp/autopkgtest.X712UD/build.dFd/src/src/Test/IntegrationTestCase.php:82

```
This test run was on ubuntu 22.04, which has libicu70 installed.  I'm guessing icu 7.0 has some format changes for dates.  I notice the 'Temps/temp' change appears to be reflected in this java testsuite:

    https://android.googlesource.com/platform/libcore/+/master/luni/src/test/java/libcore/java/text/SimpleDateFormatTest.java

I wonder if the discrepancy with the comma might relate to one of the date formatting CLDR's in 7.0, listed here:

    https://cldr.unicode.org/index/downloads/cldr-40

CLDR-13425 sounded like it at least touches on the formatting style, so it seems at least plausible this was an intentional change.  I've patched Ubuntu's php-twig format_date.test to make the above alterations, and the testsuite seems happier, but if there's a better way to fix it, advice would be welcomed.

**Comment by fabpot** [comment]
Let's close as we cannot maintain tests for all ICU versions.
