### ISSUE TITLE
"Illegal offset type" when I set an array variable using as key a previous setted var

### ISSUE THREAD

**Issue by manuelcanga** [twigphp/Twig#3663]
Hello,

## Twig error

This is a valid example:

```twig
{% set myvar = "this is ok" %}

{% set array = { (myvar): "myvalue" } %}
```

This is an error example which produces a "Illegal offset type" :

```twig
{% set myvar %}
this is ok
{% endset %}

{% set array = { (myvar): "myvalue" } %}
```

Last line produces an error due to `myvar` is `Twig\Markup` type instead of `string`. 

 
## PHP error

Error line in auto-generated template:

```php
        $context["array"] = [(isset($context["myvar"]) || array_key_exists("myvar", $context) ? $context["myvar"] : (function () { throw new RuntimeError('Variable "myvar" does not exist.', 14, $this->source); })()) => "myvalue"];
```

Maybe a concatenation could be used in order to resolve the problem:

```php
....context) ? $context["myvar"] . '' : (function (.....
```

## About my twig version:

```  
public const VERSION = '3.3.8';
public const VERSION_ID = 30308;
```

Regards

**Comment by fabpot** [comment]
You've found the issue yourself. When using the set tag, you end up with a string that can only be used as an HTML element.
