### ISSUE TITLE
Allow `===`/`!==` in addition to `same as`. PHP is not the only language that supports those comparison operators.

### ISSUE THREAD

**Issue by AndreasA** [twigphp/Twig#3666]
I know that there was a discussion once that `!==` and `===` is not supported because it is known only by PHP developers.

However, those are the ones that use twig most. Also it is not only that way in PHP.  It is also supported e.g. by ES2015 (and also TypeScript): 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality

which is something that use twig and are not PHP developers know about. Most others don't care about the type difference at all and to be honest `same as` will not help there. 

Furthermore, I think `same as` is quite long and cumbersome to use, especially also regarding negations.

See one of the previous issue: https://github.com/twigphp/Twig/issues/2358 and the reason what it was not implemented is e.g. this https://github.com/twigphp/Twig/issues/2358#issuecomment-271988617

However, as mentioned it is not just PHP.

**Comment by fabpot** [comment]
It's also because it's quite difficult to read: "===" vs "==".
As we already have "same as", I don't want to add another way.

**Comment by fabpot** [comment]
FYI #4736
