### ISSUE TITLE
format_datetime issue resulting in wrong year

### ISSUE THREAD

**Issue by arnoldjan** [twigphp/Twig#3669]
There is an issue in the format_datetime filter. Pretty easy to demonstrate:

```
{{ '2021-12-28 12:31:58'|format_date(pattern="dd MMM YYYY", locale='en') }} -> 28 Dec 2022

{{ '2021-12-28 12:31:58'|format_date(pattern="dd MMM YYYY", locale='de') }} -> 28 Dez. 2021
```

The year changes from 2021 to 2022 at the 26th of Dec. Skipping the patern seems to be avoiding the issue.

**Comment by stof** [comment]
This is related to what `Y` means. It is not the calendar year (that's `y`) but the year of "week of year": https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table

And different locales might have a different definition of when the weeks ends.
