### ISSUE TITLE
Page collection : Random but not self

### ISSUE THREAD

**Issue by ValentinBossens** [twigphp/Twig#3674]
Hey all,

I'm currently developing an agency portfolio website where, on the projects pages, I'm displaying a random picked project at the end of the page. The idea is to have the user to be redirected to a random project in order to discover more about what the agency is doing.

The problem is that, sometimes, the displayed project is the same that we're currently looking at ... 

Is there a way to "exclude self" so the random picked project is always another one than the current one?

Here's the code I'm using for now:
```
{% set random = random(page.find('/projects').children().published()) %}
```

Thanks in advance

**Comment by stof** [comment]
Well, you need to exclude it from the list passed to the `random` filter, which is not something related to Twig, put to the PHP library you use to do those `find()` calls.
