### ISSUE TITLE
Trivial arrow filter

### ISSUE THREAD

**Issue by donquixote** [twigphp/Twig#3677]
There are a few twig filters that allow arrow functions as argument: `map`, `filter`, `reduce`.
All of these apply the arrow function to array values (or keys).

I wonder, could we make a trivial filter that applies the arrow function to the original piped argument?

```twig
{{ set object = value|arrow(val => val ? {value: val} : {}) }}
```

The main purpose would be as part of a longer pipe chain.

I noticed this can already be done in userland, but it seems like a useful addition to core, or not?

```php
      new TwigFilter('arrow', [self::class, 'arrow'], ['needs_environment' => true]),
```
```php
  public static function arrow(Environment $env, $arg, $arrow) {
    twig_check_arrow_in_sandbox($env, $arrow, 'arrow', 'filter');
    return $arrow($arg);
  }
```

**Comment by donquixote** [comment]
Related:
- #3192 was rejected.
- #3402 was rejected.

I think the `arrow()` filter proposed here is quite basic and uncontroversial, is it not?

**Comment by stof** [comment]
I don't think this filter belongs to the core. In most cases, the same result can be achieved by using a Twig expression directly.

**Comment by donquixote** [comment]
> I don't think this filter belongs to the core. In most cases, the same result can be achieved by using a Twig expression directly.

But then we can't chain it up with other filters easily.
E.g. to have a macro inside a pipe.

```twig
{{ items
    |filter(item => ..)
    |map(item => ..)
    |join(', ')
    |arrow(markup => (markup|trim is not empty) ? _self.wrap('div'))
}}
```

Or to call a macro from apply:
```twig
{% set title %}
<h3>Hello</h3>
{% endset %}
{% apply arrow(markup => (markup|trim is not empty) ? title ~ markup : '') %}
  {{ output }}
{% endapply %}
```

(btw the `~` operator loses the TwigMarkup class, but this is another story - see #3679)

**Comment by khalwat** [comment]
To make this work this one line: <https://github.com/twigphp/Twig/blob/3.x/src/ExpressionParser.php#L483> from: 
```php
                    foreach ($this->parseArguments() as $n) {
```
 to: 
```php
                    foreach ($this->parseArguments(false, false, true) as $n) {
``` 
then closures all work in the context we want, e.g.: 
```twig
    {% set collection = collect(['a', 'b', 'c']) %}
    {% set contains = collection.contains((value, key) => value == 'a') %}
```
 with a nice, clean, normal syntax. I'd love to see this happen, too.

**Comment by MattWilcox** [comment]
+1 for this.

As a consumer of Twig, I just want it to work as it looks like it should. And it looks like it should support closures. Why does it matter if there are other ways of doing it?

**Comment by khalwat** [comment]
This is a solution for Craft CMS users: https://github.com/nystudio107/craft-closure

**Comment by thupsi** [comment]
+1 from me on this too!

The change proposed by @khalwat seems clean!

**Comment by fabpot** [comment]
Here, the comments are talking about something different from the ticket description. The description talks about having an `arrow` function whereas the rest is about supporting arrow functions as arguments. Is that correct?

**Comment by khalwat** [comment]
@fabpot correct, the discussion is more directly related to the unfortunately **Rejected** issue here: https://github.com/twigphp/Twig/issues/3192

**Comment by fabpot** [comment]
Closing here and reopening #3192

**Comment by donquixote** [comment]
Hello @fabpot 

> Here, the comments are talking about something different from the ticket description. The description talks about having an arrow function whereas the rest is about supporting arrow functions as arguments. Is that correct?

Indeed the comments are somewhat off track, I don't really see how they relate to the original request.

For me, the original request is still valid, it would provide more possibilities in filters and pipe expressions, which would otherwise require cluttered code blocks.
