### ISSUE TITLE
Concat operator removes Twig\Markup class

### ISSUE THREAD

**Issue by donquixote** [twigphp/Twig#3679]
When joining two Markup objects with the `~` concatenation operator, the result no longer is a Markup object.
The same is true for `join()` filter.

```twig
{% set title %}
  <h3>Example title</h3>
{% endset %}
{{ dump(title) }} -> Markup
{{ dump(title ~ title) }} -> string
{{ dump([title, title]|join('') }} -> string
```

I suppose this is intended.
But what is the alternative?

A macro works, but it is not as convenient as a built-in filter or function or operator:
```twig
{% set title %}
  <h3>Example title</h3>
{% endset %}
{% macro concat(a, b) %}
  {{ a }}{{ b }}
{% endmacro %}
{{ dump(_self.concat(title, title)) }} -> Markup
```

**Comment by donquixote** [comment]
I also saw this, which was closed: #316

> Looks like you have automatic output escaping turned on. In this case, this is indeed the expected behavior. You can use the raw filter to disable output escaping.

That's right, I could use a raw filter somewhere.
But if I want to use the output value for further processing, I really need a markup object.

**Comment by donquixote** [comment]
Btw, Drupal has a similar effort going on since a long time: https://www.drupal.org/project/drupal/issues/2579091
There the problem is one level more complex because Drupal has its own MarkupInterface objects.

**Comment by stof** [comment]
Concatenating 2 safe strings might not produce a safe string.

**Comment by donquixote** [comment]
But we can already do this with capture in a template.

```twig
{% set ab %}{{ a }}{{ b }}{% endset %}
```

Do you have an example where the result is not safe?
