### ISSUE TITLE
Template not defined when using Root Filesystem

### ISSUE THREAD

**Issue by marmz** [twigphp/Twig#3680]
I am trying to load templates using their **full path**:

```
$fs_loader = new \Twig_Loader_Filesystem('/');

$twig = new \Twig_Environment($fs_loader, [
  "cache" => false,
  "debug" => true
]);

$data = [];

$twig->display( "/var/www/html/MZTEST/maze/.plugin/__core/static/templates/admin/home.twig", $data);
```

And i get the **error**:

`Fatal error: Uncaught Twig\Error\LoaderError: Template "/var/www/html/MZTEST/maze/.plugin/__core/static/templates/admin/home.twig" is not defined .........`

Instead if i specify **project path**:

```
$fs_loader = new \Twig_Loader_Filesystem('/var/www/html/MZTEST/maze/');

$twig = new \Twig_Environment($fs_loader, [
  "cache" => false,
  "debug" => true
]);

$data = [];

$twig->display( ".plugin/__core/static/templates/admin/home.twig", $data);

```

Then, everything works **fine** :/
Any ideas??

PS:: I am using Twig 2.8.1 (maybe i'll go for Twig 3.x.x , but i don't think this is a version problem)

**Comment by fabpot** [comment]
I'm going to close as your use case is not supported. Exposing the entire filesystem as a template path is not recommended.
