### ISSUE TITLE
Question about inheritance

### ISSUE THREAD

**Issue by fabswt** [twigphp/Twig#3682]
Consider this minimal template hierarchy:

```twig
{# parent.twig #}
<!doctype html>
<html>
{{ include('mvce/twig-inheritance/nested.twig') }}
<body>{% block body %}{% endblock %}</body>
</html>
```

```twig
{# nested.twig #}
{% block head %}
<head>
  <title>{% block title %}[Default title]{% endblock title %}</title>
</head>
{% endblock head %}
```

```twig
{# child.twig #}
{% extends "mvce/twig-inheritance/parent.twig" %}

{% block title %}
Title set from the child.
{% endblock title %}

{% block body %}
Hello, world.
{% endblock body %}
```

Now, when rendering child.twig, I get:

```html
<!doctype html>
<html>
<head>
  <title>[Default title]</title>
</head>

<body>Hello, world.
</body>
</html>
```

In other words:

- The `title` block from child.twig is ignored;
- The `body` block from child.twig is used.

I want the `title` block from child.twig to be rendered instead. I found workarounds:

- Get rid of child.twig, putting its content directly inside of parent.twig instead (but I don't like it: I want to neatly chunk my code into small, digestible templates.)
- Use this in place of the `include`:

```twig
{% use "mvce/twig-inheritance/nested.twig" %}
{% block head %}
  {{ parent() }}
{% endblock %}
```

It works fine. But I still do not understand why the include is not achieving what I want. I read the docs but do not see where this is mentioned.

Could anyone help clarify what's going on?

Thank you for the help.

**Comment by stof** [comment]
Child blocks work only in relation with inheritance, not with composition. So it is totally expected that you cannot override the block of an included template. In PHP, a protected method in a child class does not override a method of a related object either.

**Comment by GromNaN** [comment]
For such composition, there is [`use`](https://twig.symfony.com/doc/3.x/tags/use.html):
https://twigfiddle.com/gyyzdv

Edit: You found that yourself.

**Comment by fabswt** [comment]
"totally expected or not", I still don't see where this is documented.

Okay, so I still have to use `use()`and in place of:

```twig
{% block head %}
  {{ parent() }}
{% endblock %}
```

I can use a mere 

```twig
{{ block('head') }}
```

**Comment by stof** [comment]
`include` is **not** documented as being part of the template inheritance feature either. It is explicitly documented as returning the rendered content of another template.
