### ISSUE TITLE
Illegal character U+AD

### ISSUE THREAD

**Issue by bobitza** [twigphp/Twig#3684]
I got error on firefox: `Uncaught SyntaxError: illegal character U+00AD` after rendering an htm template which include js part, then append in body from ajax repsponse
`let payLoadArr = JSON.parse('{{ payload|raw }}');`
That char not exist in my code
This is the code rendered by twig: `let payLoadArr = JSON.parse('[{"code":"backup4all","quantity":1,"price":{"USD":49.99}­}]');`

Php: 8.0.15
# [Smart.Framework.Modules](https://github.com/unix-world/Smart.Framework.Modules): TplTwig r.20220331 #
## Symfony Twig Templating Engine v.3.3.8

![image](https://user-images.githubusercontent.com/1919467/163359072-79e4ce1c-7c72-4438-96a0-d5e9b9eb27de.png)

**Comment by stof** [comment]
Well, don't put that unicode char in your payload then (looking at whether it is, it is clearly inside the payload).

This issue comes from the code generating the payload, not from Twig itself.

**Comment by bobitza** [comment]
i don't have that char in payload, this is the html rendered by twig i don;t have that char in code

**Comment by bobitza** [comment]
This is my code: 
![image](https://user-images.githubusercontent.com/1919467/163369204-bf6ea0de-f132-43a3-8166-3ffe150fb645.png)

**Comment by bobitza** [comment]
That invisible char is inserted by twig escape }}

**Comment by bobitza** [comment]
I think is a bug in framework..not twig

**Comment by stof** [comment]
there is no Twig autoescaping being done, as you applied the `raw` filter.
