### ISSUE TITLE
Date comparison not working?

### ISSUE THREAD

**Issue by program-the-brain-not-the-heartbeat** [twigphp/Twig#3686]
See example: 
https://twigfiddle.com/c98bq3

if comparsions with just date filter are producing wrong result. 

date('U') works though.

**Comment by GromNaN** [comment]
The `date` filter formats to string: alphabetically April is before March. You should use the `date` function instead. https://twigfiddle.com/c98bq3/2

```twig
{% if date('now') < date(end) %}
```
