### ISSUE TITLE
Call to undefined function Twig\ctype_alpha()

### ISSUE THREAD

**Issue by Luisehahne** [twigphp/Twig#3692]
There was an uncatched exception
Call to undefined function Twig\ctype_alpha()
in line (469) of (/include/twig/twig/src/Lexer.php):
and include/twig/twig/src/Loader;FilesystemLoader.php line 276 
missing the global backslash before function call, because is a php function

**Comment by stof** [comment]
Including the `\` won't solve the error for you. It will only change the error message. PHP automatically uses the global function as a fallback when there is no namespaced function (but the error message reports the namespaced function when none exists).

The issue in your case is that `ctype_alpha` does not exist in your system. You need to make sure that the ctype extension is loaded (it is an extension that is enabled by default when compiling PHP, but it is still possible to disable it).
Alternatively, if you cannot enable the extension, you can install the `symfony/polyfill-ctype` composer package which provides a userland implementation of the ctype functions (but be aware that they are slower than using the extension, so if you care about performance, you should definitely work on enabling the extension instead).

Note that Twig even requires `symfony/polyfill-ctype` in the composer dependencies to avoid such kind of errors by default (so you are either on a totally outdated version of Twig or not using composer to install it or doing advanced usage of composer in a broken way)
