### ISSUE TITLE
Improve support for PHP that does not shut down

### ISSUE THREAD

**Issue by Zarthus** [twigphp/Twig#3693]
I have a setup where PHP does not shut down (a webserver that renders twig on the fly), I use Twig to compile templates on request in a dev mode. I think twig was written with the idea in mind that PHP exits at some point, but parts of PHP are moving more and more towards not shutting down (amphp, react, ...).

On compilation, Twig creates a class with an unique name based on several factors.
However, if you then change that file in the same PHP runtime, the class name will be the same.

## Problem Statement

The class name twig generates is not unique if the file is modified between the time it's rendered the first time, and succeeding times.

I have isolated the issue to two problematic statements:

https://github.com/twigphp/Twig/blob/8442df056c51b706793adf80a9fd363406dd3674/src/Environment.php#L334-L336
https://github.com/twigphp/Twig/blob/8442df056c51b706793adf80a9fd363406dd3674/src/Environment.php#L338-L365

## Minimal Reproduction Steps

```php
$fsLoader = new \Twig\Loader\FilesystemLoader(__DIR__ . '/templates', __DIR__ . '/templates');
$twig = new \Twig\Environment($fsLoader, ['debug' => true, 'auto_reload' => true, 'cache' => false]);

// Render the template the first time.
$renderA = $twig->render('example.twig');

// User writes something to the file.
file_put_contents('templates/foo.twig', random_int(0, PHP_INT_MAX), FILE_APPEND);

// Render the same template, but it now has different content.
$renderB = $twig->render('example.twig');

if ($renderA === $renderB) {
    echo "Assertion failed: Since template's contents have modified the expectation is that the output is different";
    exit(1);
} else {
    echo "All is good :)";
}
```

## Solutions

I have thought of a few solutions:

- Consider file contents class names twig generates. (lots of IO, possibly?)
  - `mtime` won't be ideal as it doesn't have microsecond precision
  - `hash_file()` works but is expensive
  - Extending twig's `Environment` to consider class name uniqueness 
  - Extending twig's `Loader::getCacheKey()` to consider class name uniqueness
- A new option that always generates unique template names

Is this something you consider an issue you'd like to solve within Twig, or did I miss the nail and is there already something in Twig that helps mitigate this? I'll be happy to help :)

----

For complete reproduction steps: https://github.com/Zarthus/twig-reproduction-3693

**Comment by stof** [comment]
Supporting reloading compiled template in a long-running server would require moving away from classes. However, note that if you modify a class in your own source code, you also need to restart the PHP process for it to be taken into account. So you would have the same issue here for the dev experience.
If those tools support a way to automatically restart the server when a PHP file is modified in dev mode, the proper solution is probably to extend that system so that it also tracks twig files and do the same reloading.
