### ISSUE TITLE
Twig\Markup doesn't convert to string when used as object key

### ISSUE THREAD

**Issue by alinnert** [twigphp/Twig#3696]
When using a `Twig\Markup` as an object key it doesn't get converted to a string automatically.

```twig
{% set someClasses %}
  {{ html_classes(...) }}
{% endset %}

<div class="{{ html_classes({
  (someClasses): someCondition,
}) }}"></div>
```

In a twigfiddle the property doesn't get added at all ([Here's an example](https://twigfiddle.com/9f614g/2)). In my local CraftCMS installation this throws a `Illegal offset type` error instead.

After looking at the source code of `Twig\Markup` I found that I can call `__toString` to make it work:

```twig
<div class="{{ html_classes({
  (someClasses.__toString()): someCondition
}) }}"></div>
```

By now I found out that it makes a lot more sense and solves this entire problem to define `someClasses` like this:

```twig
{% set someClasses = html_classes(...) %}
```

But I wanted to point that out in case this should work nonetheless.

**Comment by ju1ius** [comment]
Or you could do:
```twig
<div class="{{ html_classes({
  ('' ~ someClasses): someCondition
}) }}"></div>
```
A bit shorter, but still not perfect.
The `html_classes` function seems to be missing some sort of `if($key instanceof \Stringable)` check somewhere...
