### ISSUE TITLE
Missing SVGs after trans filter?

### ISSUE THREAD

**Issue by littleAmused** [twigphp/Twig#3701]
Hey there, I've got a bit of a special problem here. I am creating a new theme for a shop software that uses Twig as the theming framework. A custom function of the shop allows a nice icon handling. Now I want to combine those handy functionality with the translation filter `|trans`. For that, I create a placeholder, like `%iconHeart%`, in the translated string and my target is to replace this placeholder with the icon from the handy function.

To provide the icon's code safely to the placeholder-replacement, I created a set/endset block with the icon's function in it.

This process is no problem, as the `dump()` function shows the whole SVG Code in the dumped area.

My struggling starts with the replacing in the filter `|trans`. Something seems to be cut off there, or something similar happens. In any case, the result is that the code of the SVG icon is simply no longer there. I've also checked the source code beside from the developer console. There are also empty spans printed out, but no SVG. It seems to me like the SVG is filtered from the output - but why?

I'm hoping for some help, because I want the theme to be as dynamically as possible and the little perfectionist in me wants some icons in Text 😅 

Please feel free to ask me things, if you need to know something. I haven't tested this issue in an independent Twig-setup, but I am pretty sure, that this is no problem with the shop software, because of the existing SVG code in the dumped variable.

Best regards!

**Comment by stof** [comment]
could it be your `sw_sanitize` filter that removes the SVG rather than the `trans` filter ?

**Comment by littleAmused** [comment]
> could it be your `sw_sanitize` filter that removes the SVG rather than the `trans` filter ?

Ha, yes! Doesn't think about that one 🤦 

Using `raw` brings the desired result. `sw_sanitize` is in fact a custom filter of the shop ... So here thematically wrong after all, sorry about the confusion.

Thanks alot for your help!
