### ISSUE TITLE
New named callable handling breaks for private methods

### ISSUE THREAD

**Issue by Jean85** [twigphp/Twig#3703]
As reported in https://github.com/getsentry/sentry-symfony/issues/627 + https://github.com/getsentry/sentry-symfony/pull/628, the Sentry bundle breaks with Twig 3.4.0. This seems related with #3702 and to the fact that our bundle used a closure to invoke a private method: https://github.com/getsentry/sentry-symfony/blob/6177d71f2fd65f4f0f77036a1ca910aa9326767f/src/Twig/SentryExtension.php#L29-L39

Is this intended? Or does it require a fix?

**Comment by stof** [comment]
the case of using a private method was not thought about when doing that PR.

@nicolas-grekas this would be solved by checking the visibility of the method before using the optimized mode, right ?

@Jean85 note that using public methods in a Twig extension (or functions or public static methods or a public function in a runtime class) allows Twig to skip the initialization of extensions at runtime, unlike using a closure as implementation.

**Comment by Jean85** [comment]
> allows Twig to skip the initialization of extensions at runtime, unlike using a closure as implementation.

So you're suggesting us to use the public method way to obtain a more optimized execution, did I understand correctly?

**Comment by stof** [comment]
yeah, that would be better

**Comment by nicolas-grekas** [comment]
Fixed in #3704
But @stof is right: using non-public methods there means we cannot optimize the call. Might be better making the method public.
