### ISSUE TITLE
Renamed blocks cannot be overwritten

### ISSUE THREAD

**Issue by m-vo** [twigphp/Twig#3709]
When renaming blocks in the use statement (`{% use "blocks.twig" with bar as baz %}`), the renamed blocks cannot be adjusted/overwritten in the template. Same goes for extenders of this template.

This scenario is not covered [in the docs](https://twig.symfony.com/doc/3.x/tags/use.html) where blocks are only renamed or output but never altered.

### Reproducer
See the following example https://twigfiddle.com/kxljnw:

*main.twig*
```twig
{% use "blocks.twig" with bar as baz %}

{% block foo %}{{ parent() }}+{% endblock %}
{% block baz %}{{ parent() }}+{% endblock %}

{# works as expected #}
{{ block('foo') }}

{# fails #}
{{ block('baz') }}
```

*blocks.twig*
```twig
{% block foo %}Foo{% endblock %}
{% block bar %}Bar{% endblock %}
```

**Comment by ghost** [comment]
The 1st part of your example is really an issue, the `{% block baz %}` doesn't work.
But the `{{ block('baz') }} `function  works correctly on my side.
