### ISSUE TITLE
Elegant way of outputing arrays, 

### ISSUE THREAD

**Issue by hekep** [twigphp/Twig#3717]
I have array in php
```
var $options =  array(
        'findOpts' =>
        array(
            'findOpts' =>
            array(
                0 => 'title',
                1 => 'created',
                2 => 'id',
            ),
            'order' =>
            array(
                'created' => 'DESC',
            ),
            'limit' => 10,
        ),
    )
);

```
In twig template I want to
```
{{ options.findOpts }}
```
to output string

```
 array(
            'findOpts' =>
            array(
                0 => 'title',
                1 => 'created',
                2 => 'id',
            ),
            'order' =>
            array(
                'created' => 'DESC',
            ),
            'limit' => 10,
        )

```
Is is possible without any debug mode ?

**Comment by stof** [comment]
You would need to register some dumping function or filter. There is no such filter available in core.

**Comment by hekep** [comment]
I solved it like this:

```
$options['findOptsVarExportStr']  = var_export( $options['findOpts'] , true );
``` 
and in template:
```
{{ options.findOptsVarExportStr| raw  }}
```
I wish there would be nicer way built in.

**Comment by stof** [comment]
Well, you can create a custom Twig filter and register it.

**Comment by stof** [comment]
Btw, don't use `|raw`. `var_export` is not escaping HTML special chars, so disabling the Twig auto-escaping is not safe (it could allow a XSS issue)

**Comment by hekep** [comment]
> Btw, don't use `|raw`. `var_export` is not escaping HTML special chars, so disabling the Twig auto-escaping is not safe (it could allow a XSS issue)

In my use case  `| raw` and `var_export` are going to be fine.

I hope to see  built in `var_export` in future version.

**Comment by GromNaN** [comment]
If the format don't have to be exactly like your example, the [`json_encode` filter](https://twig.symfony.com/doc/2.x/filters/json_encode.html) is available.

**Comment by stof** [comment]
> In my use case `| raw` and `var_export` are going to be fine.

Well, `|raw` does not work fine: it disables HTML escaping, meaning that if the exported variable contains some HTML string, it will create a XSS security issue. `var_export` is not producing safe HTML, so you should remove the `|raw` filter
