### ISSUE TITLE
Error when including twig files without absolute links

### ISSUE THREAD

**Issue by HJPoyntz** [twigphp/Twig#3730]
### What steps will reproduce the problem?

![Screenshot 2022-07-28 at 15 17 35](https://user-images.githubusercontent.com/87074073/181533242-86186f37-78de-47d6-8913-1a79f7830e22.png)

With the following file structure. 
If I inside of masterTwig.twig include twig-test/A.twig.
Then, inside of A.twig, I reference B.twig with a relative path `{% include "B.twig" %}`. 

### What's expected?

This should give me the content of B.twig.
It should also looking inside of the folder twigTest, however it looks in the folder twigContainer

### What do you get instead?

The error message that is thrown is:

`Unable to find template "B.twig"(looked into: twigContainer)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0
| Yii Twig version | 2.4
| Twig version     | 
| PHP version      | 8.1
| Operating system | MacOS

**Comment by fabpot** [comment]
There is no such concept of a "relative" path in Twig. All templates must be referenced from the path you configured in Twig.

**Comment by developedsoftware** [comment]
Ah okay! We use the yii2 implementation of it and it gives the impression that relative paths are possible. 

https://www.yiiframework.com/extension/yiisoft/yii2-twig/doc/guide/2.3/en/template-syntax#referencing-other-templates

```
There are two ways of referencing templates in include and extends statements:

{% include "comment.twig" %}
{% extends "post.twig" %}

{% include "@app/views/snippets/avatar.twig" %}
{% extends "@app/views/layouts/2columns.twig" %}
In the first case the view will be searched relatively to the current template path. For comment.twig and post.twig that means these will be searched in the same directory as the currently rendered template.
```

**Comment by fabpot** [comment]
The yii2 doc should indeed be updated as we never load a template relatively.

**Comment by developedsoftware** [comment]
Fair enough, understood !
