### ISSUE TITLE
Issues with the Twig documentation, missing/unavailable functions

### ISSUE THREAD

**Issue by sandoba** [twigphp/Twig#3732]
I've noticed a few issues with the documentation, especially in regards to additional functionality provided by Symfony:

1) the tag "**transchoice**" mentioned at https://twig.symfony.com/doc/3.x/ is not part of the Symfony documentation, e.g. not mentioned in https://symfony.com/doc/current/reference/twig_reference.html or in any other page of the documentation

2) various functions and filters from https://symfony.com/doc/current/reference/twig_reference.html aren't listed at https://twig.symfony.com/doc/3.x/, e.g. "**impersonation_exit_path**", "**impersonation_exit_url**", "**sanitize_html**" and "**serialize**"

3) https://symfony.com/doc/current/form/form_customization.html mentions an additional function "**form_parent**" which is also not listed at https://twig.symfony.com/doc/3.x/

4) the function "form" links to https://symfony.com/doc/current/reference/twig_reference.html#form with an incorrect anchor, probably best to link directly to https://symfony.com/doc/current/form/form_customization.html as well

5) the link "Logic" at https://twig.symfony.com/doc/3.x/ refers to the wrong paragraph "Math"

**Comment by fabpot** [comment]
I think I've fixed all issues. Bonus: this page is now auto-generated based on the docs (Twig and Symfony), so I don't need to update it manually, which should limit such issues.

**Comment by sandoba** [comment]
Thank you!
