### ISSUE TITLE
Wrong version constraint for security release?

### ISSUE THREAD

**Issue by Jelle-S** [twigphp/Twig#3746]
https://symfony.com/blog/twig-security-release-possibility-to-load-a-template-outside-a-configured-directory-when-using-the-filesystem-loader states that

> The issue has been fixed in Twig 1.44.7, 2.15.3 and 3.4.3.

~But the version constraint doesn't reflect it~ (I read the constraint wrong, it actually does reflect it):

> Twig >1.0.0,<1.44.7 || >2.0.0,<2.15.3 || >3.0.0,<3.4.3 are affected by this security issue.

~which means~ *but* https://github.com/enlightn/security-checker detects 2.15.3 as an insecure version. This is also reflected on https://packagist.org/packages/twig/twig:
![image](https://user-images.githubusercontent.com/1828542/192741004-989f0a9b-9e78-429f-ba45-900bec0e6cff.png)

**Comment by stof** [comment]
the mistake is in https://github.com/FriendsOfPHP/security-advisories/pull/650

**Comment by fabpot** [comment]
Typo fixed there.
