### ISSUE TITLE
v2.15.3 breaks Drupal Core's claro theme

### ISSUE THREAD

**Issue by jurgenhaas** [twigphp/Twig#3747]
Just updated from 2.15.2 to 2.15.3 and then received this exception in Drupal 9.4.46:

```
Twig\Error\LoaderError: Template "@claro/../images/src/hamburger-menu.svg" is not defined in "core/themes/claro/templates/navigation/menu-local-task.html.twig" at line 30. in Twig\Loader\ChainLoader->getCacheKey() (line 98 of /var/www/html/vendor/twig/twig/src/Loader/ChainLoader.php). 
```

The line 30 in the twig file contains `{% include "@claro/../images/src/hamburger-menu.svg" %}` and the referenced file is present.

Downgrading to 2.15.2 fixes the issue for me again.

**Comment by stof** [comment]
Well, accessing files outside the configured template folder was never intended to be supported. This theme seems to rely explicitly on the bug that has been fixed in 2.15.3 (because it could have been a security issue in some cases)

**Comment by jurgenhaas** [comment]
Turns out, this is already dealt with downstream and I was too quick reporting this.

**Comment by johandenhollander** [comment]
Just want to mention that I came here for the same reason, but in some other theme and had to find out where this downstream solution was located.

It's here: https://www.drupal.org/project/drupal/issues/3312270
