### ISSUE TITLE
Code completion and static analysis

### ISSUE THREAD

**Issue by RobinDev** [twigphp/Twig#3748]
Hi there,

I was woondering what are you using for code ccompletion and static analysis.

Except the abandonned package (https://packagist.org/packages/symplify/phpstan-twig-rules) from @tomasvotruba, I can't find a lot of ressources.

## About code completion

It would be interesting to be able to defined type hint for variable. 

It will ease code completion (and static analysis if twig equally manage to parse type hint and convert it to phpdoc)

Eg: 
```twig
{% set ?MyClassObject|string|int my_var_name = my_var_name is defined ? my_var_name : 'default Value OR null' %}
```
Or without BC : 
```twig
{# @var ?MyClassObject|string|int #}
{% set my_var_name = my_var_name is defined ? my_var_name : 'default Value OR null' %}
```

It would permits to equally define the required var in a template file at the beginning of the file with a type hint. Eg

**Comment by fabpot** [comment]
We have many other issues about type hints. Let's close this one.
