### ISSUE TITLE
twig\lib\Twig\Environment.php "Unparenthesized `a ? b : c ? d : e` is deprecated"

### ISSUE THREAD

**Issue by ksoftinformatik** [twigphp/Twig#3752]
05.10.22 10:23:51 Exception 0 in Datei C:\inetpub\wwwroot\kurt-kleindienst\vendor\twig\twig\lib\Twig\Environment.php Zeile 579
An exception has been thrown during the compilation of a template ("Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`") in "Home/index.twig".
#0 C:\inetpub\wwwroot\kurt-kleindienst\vendor\twig\twig\lib\Twig\Environment.php(368): Twig_Environment->compileSource()
#1 C:\inetpub\wwwroot\kurt-kleindienst\vendor\twig\twig\lib\Twig\Environment.php(289): Twig_Environment->loadTemplate()
#2 C:\inetpub\wwwroot\kurt-kleindienst\Core\View.php(57): Twig_Environment->render()
#3 C:\inetpub\wwwroot\kurt-kleindienst\App\Controllers\Home.php(28): Core\View::renderTemplate()
#4 [internal function]: App\Controllers\Home->indexAction()
#5 C:\inetpub\wwwroot\kurt-kleindienst\Core\Controller.php(79): call_user_func_array()
#6 C:\inetpub\wwwroot\kurt-kleindienst\Core\Router.php(128): Core\Controller->__call()
#7 C:\inetpub\wwwroot\kurt-kleindienst\index.php(38): Core\Router->dispatch()
#8 {main}

???

**Comment by ksoftinformatik** [comment]
Error on PHP 7.4!
On php 7.3 work!

**Comment by ksoftinformatik** [comment]
Error happens in Extension/Core.php in function getTokenParsers()

**Comment by stof** [comment]
which version of Twig are you using ?

**Comment by ksoftinformatik** [comment]
3.4.2

**Comment by xabbuh** [comment]
I do not see anything in Twig code that could trigger this error. Can you try to debug where the exception is being thrown?

**Comment by ksoftinformatik** [comment]
lib/ExtensionSet.php

    private function initExtension(Twig_ExtensionInterface $extension)
    {
        // filters
        foreach ($extension->getFilters() as $filter) {
            $this->filters[$filter->getName()] = $filter;
        }

        // functions
        foreach ($extension->getFunctions() as $function) {
            $this->functions[$function->getName()] = $function;
        }

        // tests
        foreach ($extension->getTests() as $test) {
            $this->tests[$test->getName()] = $test;
        }

        // token parsers
// Error:
       foreach (**$extension->getTokenParsers()** as $parser) {

**Comment by xabbuh** [comment]
Looks like your last comment was truncated.

**Comment by ksoftinformatik** [comment]
//****Error: ******
foreach (**$extension->getTokenParsers()** as $parser) {

**Comment by stof** [comment]
There is no ternary operator on that line. So it cannot be the source of the deprecation.
