### ISSUE TITLE
Prevent variable inheritance when including templates

### ISSUE THREAD

**Issue by saminton** [twigphp/Twig#3754]
This or more of a question than anything else but I have scoured the web and couldn't find anything so I am posting this here.

Say I have a page
```twig
<div class="page">
   {# This is a page #}
   {% include "section.twig" with {
      class: "parent--subclass",
      data: "page data"
   }%}
</div>
```
That applies a class `parent--subclass` to a section
```twig
<div class="section {{class}}">
   {# This is a section #}
   {% include "component.twig" with {
      data: "section data"
   }%}
</div>
```
That calls another component capable of retrieving a class
```twig
<div class="component {{class}}">
   {# This is a component #}
   <pre>
      {{ dump() }}
      {# Dumps variables from all parents #}
      {# class => "parent--subclass" #}
      {# data => "section data" #}
   </pre>
</div>
```
My component retrieves all previous variables defined from all parents are will therefor also have to class `parent--subclass` which is not what I want. I don't really want to define `class: ''` on every single include, especially as this is just an example with class. Many other components may have unexpected behaviour if by chance a variable it uses was defined higher up in the tree.

Is there any way of disabling variable inheritance when including or embedding templates ?

**Comment by jdreesen** [comment]
There's an `only` keyword you can use, see: https://twig.symfony.com/doc/3.x/tags/with.html

**Comment by stof** [comment]
to be exact, the right doc is https://twig.symfony.com/doc/3.x/tags/include.html (but the name is also `only` for the `{% include %}` tag)

**Comment by saminton** [comment]
Oh thanks that's perfect. Is there a way of setting this to the default behaviour ?

**Comment by stof** [comment]
no

**Comment by saminton** [comment]
Ok thanks for the help 😀
