### ISSUE TITLE
Problem with display asset with source function

### ISSUE THREAD

**Issue by Glancu** [twigphp/Twig#3756]
Hi,
I'm using Shopware 6 and after upgrade twig to version 3.4.3, then I have problem with render my .svg image with the source() function in twig.
I found that problem is with [this](https://github.com/twigphp/Twig/commit/f8009347c438bef22ef0603ab3d3ccb44bb10bed) commit. How do I can now render my svg file? 

I have code
`
source('@MyNamespaceTheme/../app/storefront/src/assets/icons/my-icon.svg', ignore_missing = false)
`

The problem is because in twig 3.4.3 we have validation by $shortName (in my example is: '../app/storefront/src/assets/icons/my-icon.svg') and then in [validateName function](https://github.com/twigphp/Twig/blob/3.x/src/Loader/FilesystemLoader.php#L251) I get throw LoaderError, because the first part of my string is '..'.

So how I can render my svg file in twig 3.x?

**Comment by stof** [comment]
Going outside the namespace folder is forbidden. In older version of Twig, a bug in the validation logic allowed to go one level up.

The solution is to store your files in a folder registered to be accessible by Twig if you want to access them through a template name.
