### ISSUE TITLE
example needed: `registerUndefinedTokenParserCallback()`

### ISSUE THREAD

**Issue by therealpecus** [twigphp/Twig#3762]
I am looking for a way to shim unknown tags from a loaded Twig file, while preserving internal nodes available to the parser/walker.

Are there code examples of how to use `registerUndefinedTokenParserCallback()`? It's rather trivial to shim with `registerUndefinedFunctionCallback()` and `registerUndefinedFilterCallback()`, but I have not found a way to skip unknown tags.

This code works for functions and filters, i.e. `$env->registerUndefinedFunctionCallback(shimTwig(TwigFunction::class))`

```php
    function shimTwig(string $type) {
        return function ($name) use ($type) {
            return new $type($name);
        };
    }
```

**Comment by fabpot** [comment]
The simple answer is no.

Have a look at #3458 to understand the use case for which we added this feature.
And #4296 where I try to clarify the use cases.

**Comment by therealpecus** [comment]
Thanks for chiming in. I did expect this to be non-trivial. My original goal was to build a bare bone string extractor, walking the AST when a specific filter was used. Skipping custom tags would have allowed generalizing the parser/extractor for any twig file, regardless of the extensions that the specific implementation adopted.

I ended up coding it with RegExp's
