### ISSUE TITLE
"Unknown "transchoice" filter

### ISSUE THREAD

**Issue by xyz1123581321** [twigphp/Twig#3767]
Why is transchoice missing?

**Comment by stof** [comment]
Are you using Twig alone ? `transchoice` is not a core Twig filter. It is a filter that was part of the Symfony framework. And that filter has been deprecated and then removed from Symfony.

**Comment by xyz1123581321** [comment]
Is there an alternative method for this?

**Comment by VincentLanglet** [comment]
https://symfony.com/doc/4.2/translation/templates.html
```
The transchoice tag is deprecated since Symfony 4.2 and will be removed in 5.0. Use the [ICU MessageFormat](https://symfony.com/doc/4.2/translation/message_format.html) with the trans tag instead.
```
