### ISSUE TITLE
Twig cache inside if statement

### ISSUE THREAD

**Issue by mrfsrf** [twigphp/Twig#3772]
I'm having following situation where I need to check for global ENV variable (dev || prod)
Using twig v1.x

```
{% if is_prod %}
 {% cache 'homepage;#{hash_key};' post %)
{% endif %}
...code
{% if is_prod %}
 {% endcache '%)
{% endif %}
```

**_Fatal error: Uncaught Exception: Unexpected "endif" tag (expecting closing tag for the "cache" tag_**

Is there a workaround for that. tnx

**Comment by mrfsrf** [comment]
My bad Twig caching was implemented from v.2x. Im using Timber

**Comment by stof** [comment]
`{% if %}` is for runtime condition, not parse-time conditions (comparing it to C, it corresponds to the `if ()` syntax, not to macros)

**Comment by mrfsrf** [comment]
You are right. Found solution using unix timestamp for cache key if development ENV
