### ISSUE TITLE
What happened to the shuffle filter?

### ISSUE THREAD

**Issue by kitsguru** [twigphp/Twig#3773]
I believe shuffle was added to the old twig/extensions but now missing from the twig core extensions.

What is the current position/status of the shuffle filter?

**Comment by GromNaN** [comment]
According to this issue #1038, the filter was provided by `twig/extensions`: https://github.com/twigphp/Twig-extensions/blob/master/src/ArrayExtension.php

**Comment by kitsguru** [comment]
That was in the old extensions which is no longer supported.

**Comment by xabbuh** [comment]
There is no replacement inside Twig for the `shuffle` filter (see https://github.com/twigphp/Twig-extensions/blob/master/README.rst).
