### ISSUE TITLE
AlexaCRM msdyncrm_twig shortcode produces critical error in WordPress

### ISSUE THREAD

**Issue by EC-Paul** [twigphp/Twig#3778]
The AlexaCRM Dynamics 365 Integration WordPress Plugin, using Twig templates, is causing a 500 error on pages using the msdyncrm_twig shortcode. Issue was reported by our client on 2022-12-12, and was working normally beforehand.

**Comment by stof** [comment]
You should report that to the issue tracker of the wordpress plugin implementing the `msdyncrm_twig` shortcode. This repo is for the Twig library itself, which knows nothing about wordpress.
