### ISSUE TITLE
Loop statements with if conditionals don't work anymore

### ISSUE THREAD

**Issue by wbEasy** [twigphp/Twig#3782]
I updated my Twig to version 3 (from 1) and many of my templates break because of this issue.

```
# worked with Twig 1 but not with Twig 3
 {% for user in users if user.active %}
        <li>{{ user.username|e }}</li>
    {% endfor %}

```

The error I am getting is:
```
2022-12-18T01:18:43+00:00
         [Exception] There was an unknown exception: 
         Unexpected token "name" of value "if" ("end of statement block" expected). 
         in line (163) of \templates\theme_fallbacks\twig\access_users.twig

```

I looking for a long time for a solution but I don't seem to get it resolved.
Any suggestions or explanation?
TIA

**Comment by SpacePossum** [comment]
https://twigfiddle.com/gohx30

works on Twig 2, however it shows the deprecation warning:

```
Using an "if" condition on "for" tag in  "main.twig" at line 3 is deprecated since Twig 2.10.0, 
use a "filter"  filter or an "if" condition inside the "for" body instead
(if your  condition depends on a variable updated inside the loop).
```

so the suggestion is to change your template to something like

```twig
{% for user in users %}
    {% if user.active %}
        <li>{{ user.username|e }}</li>
    {% endif %}        
{% endfor %}
```

or setup a `filter`

If you are upgrading from Twig 2 to 3 (great idea btw. :) ) you can see all the (breaking) changes and suggested upgrade paths here:
https://github.com/twigphp/Twig/blob/2.x/doc/deprecated.rst
