### ISSUE TITLE
Official VS Code extension

### ISSUE THREAD

**Issue by mrleblanc101** [twigphp/Twig#3785]
There are a lot of outdated, unmaintained VS Code extension for Twig,, most of them have major issue.
It would be nice to have an official one.

https://marketplace.visualstudio.com/items?itemName=whatwedo.twig&ssr=false#review-details
https://marketplace.visualstudio.com/items?itemName=mblode.twig-language-2&ssr=false#review-details

**Comment by fabpot** [comment]
That's outside the scope of this repository.
I agree that having a good extension for VScode would be nice, but that's not something I will work on.
