### ISSUE TITLE
Upgrade inky-extra required library

### ISSUE THREAD

**Issue by SiMoSiMo2** [twigphp/Twig#3799]
Consider to upgrade `lorenzo/pinky` to 1.0.7 due to deprecated `mb_convert_encoding` (used on `pinky/src/pinky.php` on line 115) on PHP 8.2

**Comment by fabpot** [comment]
There is nothing to do in Twig itself. Running `composer update` in projects is enough to get the newest version.

**Comment by fabpot** [comment]
But we are still waiting for upstream to release 1.0.8 to fix this deprecation. See https://github.com/lorenzo/pinky/pull/27

**Comment by genby8** [comment]
do not update, there is a serious problem https://github.com/lorenzo/pinky/issues/28
