### ISSUE TITLE
reduce filter doesn't pass the key to the arrow function

### ISSUE THREAD

**Issue by ju1ius** [twigphp/Twig#3802]
Hi,

The `filter` and `map` filters both pass the value and the key of the iterable to their callback.
However the `reduce` filter does not.
And _should_, at least WRT api consistency.

An example where it's useful:
```twig
{% set status_classes = {
  'success': 200,
  'warning': 400,
  'error': 500,
} %}

<span class="{{ status_classes|reduce((acc, v, k) => response.status_code >= v ? k : acc, '') }}">
  {{ response.status_code }}
</span>
```

**Comment by stof** [comment]
PHP's `array_reduce` does not support receiving the key in the callback (unlike `array_map` and `array_filter`): https://www.php.net/array_reduce

**Comment by ju1ius** [comment]
> PHP's array_reduce does not support receiving the key in the callback (unlike array_map and array_filter): https://www.php.net/array_reduce

Indeed, but then `twig_array_reduce` shouldn't be implemented using `array_reduce`.
Just like `twig_array_map` doesn't use `array_map`.
