### ISSUE TITLE
A way to keep safe and unsafe parts separate in a filter

### ISSUE THREAD

**Issue by m-vo** [twigphp/Twig#3807]
I would like to pitch a concept for Twig filters, that would allow keeping content, that was once identified as safe/unsafe, separated until the very end.

## The problem

Filters can operate on unsafe content, that is later (automatically) escaped:

```twig
{{ user_data|my_filter|escape('html') }}
```

But sometimes, the filter needs to add things that should *not* be escaped (think of the `nl2br` filter for example, that adds `<br>` tags, that the filter considers safe). There are currently only 2 standard ways to solve this:

1) pre-escape everything in the filter (and declare it safe)
2) add `|raw` and also trust the input

Both options have their downsides. The first being very stiff, because, now, chaining multiple filters gets difficult, the second being potentially dangerous.

## An example for a solution

In [Contao CMS](https://github.com/contao/contao) we had a similar need: Users can add so-called "insert tags" into some back end text inputs. These are little short codes, that for instance replace a text reference with a HTML link. Our insert tag parser dissects the user input and performs the replacements, but before recombining the text, we end up with a list of tokens like so:

```php
[
  'Here is  ', // user input
  '<a href="foo">one link</a>', // generated (trusted)
  ' and  ', // user input
  '<a href="bar">another one</a>', // generated (trusted)
  '.', // user input
]
```

As you can see, at this point we still know which things we want to trust (the generated things) and which not (the user input). Wouldn't it be nice to keep these chunks separate instead of imploding the list?

In fact, that is what we did: We created a stringable class `ChunkedText`, that holds the (separated) data and adjusted the escaper filter to handle instances of the class - effectively skipping the filter for the parts that were considered safe. And this worked out beautifully. 

Now we could use something like the following in our templates (assume the `description` contained a user controlled input; the link was inserted by the insert tag filter):

```twig
{# Outputs:  For more about the &lt;i&gt; tag, refer to the <a href="https://developer.mozilla.org/…/i">mdn web docs</a>.
{{ description|insert_tags }}
```

## Conclusion
I wonder if something like the above solution would be a worthwhile addition to Twig itself:

* We would add a class that represents a string with safe and unsafe chunks and handle it when escaping.
* Then filters could be more concise in their output by returning an instance of the class instead of a ([re]combined) string. 
* Maybe subsequent filters could also be evaluated on the individual chunks and their output also wrapped: Basically, so that no implementer has to work with the class as an input, but *can* optionally return it.
* As a fallback - the class would be stringable.

**Comment by stof** [comment]
Auto-escaping is purely a compile-time concern (which is also what allows to have with zero impact on performance). There is no way to trust parts of values, as this is not something that is stored in the values themselves.

**Comment by m-vo** [comment]
> There is no way to trust parts of values

Of course there is. That is exactly what I outlined above. :upside_down_face: 

There is no performance hit, because the *evaluation* of the escaper is happening at runtime anyways. You would not need to differentiate beforehand, you can simply branch when encountering the class in the escaper. In the simplest form, safe and unsafe content are just interwoven (= the fallback string is just a join). An `[s, u, s, u]|filterA|escape` is identical to `[s|filterA, u|filterA|escape, s|filterA, u|filterA|escape]|join`. 

Only the filter application needs to keep chunks intact - but this is works independent of the runtime output (pseudo code):

```php
function apply($value, $filter) {
	if(!$value instanceof ChunkedText) {
        return $filter($value);
    }

	return new ChunkedText(array_map(
        static fn($value) => $filter($value),
        $value->getIterator()
    );
}

// An application of $filterA($filterB($filterC($value))) is unfolded to:
apply(apply(apply($value, $filterC), $filterB), $filterA);
```

Then the `twig_escape_filter` can handle the rest (pseudo code):

```php
function old_twig_escape_filter(…) {
    … 
}

function twig_escape_filter($value, …) {
    if (!$value instanceof ChunkedText) {
        return old_twig_escape_filter($value, …);
    }

    $parts = [];
 
    foreach ($value->getAsChunks() as [$raw, $chunk]) {
		$parts[] = $raw ? $chunk : old_twig_escape_filter($value, …);
    }

    return implode('', $parts);
}
```

**Comment by stof** [comment]
Your code assumes that working with an array should implode it. That's **not** a behavior of Twig (and that would be very weird to introduce it IMO). We don't automatically inject a `join` filter in expressions working with an array.

And forcing any filter applied on an array to become a filter applied on each value would be a **huge** BC break and a huge WTF as it would forbid to actually write a filter that operates on the array (the `join` filter would become impossible to implement btw).

And the evalution of escaping is done at runtime indeed, when we know we need to have it. But there is no condition of `is it needed or no ?` at runtime. So there is nothing like your `getAsChunks()` where you return both the safety of the value and the value itself (which would make every expression a lot harder by having to wrap every PHP value)

**Comment by m-vo** [comment]
> Your code assumes that working with an array should implode it. […]

No, that's not at all what the code does. Could you please re-read what I wrote? I have the feeling you completely misunderstood my point. Maybe I also need to clarify things some more. In this case, sorry for that.

Let's try: The example above specifically handles a class (I called it `ChunkedText`). For **everything else**, the behavior is **identical to before** (see the early returns). The class is tailored to contain both controlled/safe (`S`), and uncontrolled/potentially unsafe (`U`) input. In its simplest representation both forms are just alternating, because that is what you would get when parsing and interpreting a linear text: `U,S,U,S,U…`. `U` is - by definition - the thing under control, while `S` is everything else. For this simple, linear, form, the resolution is the concatenation (therefore the `implode` in the example). 

A filter that has knowledge over the processed data, can now return an instance of the class, instead of a string:
```php
// … we injected some generated things into the input string (user data)

// before
return '<user data><thing we generated><more user data><more things we generated>';

// now
return new ChunkedText([
	'<user data>', // U
   '<thing we generated>', // S
   '<more user data>', // U
   '<more things we generated>', // S
   …
]);
```

<sup>Please ignore the non-existing API design, it's just an example.</sup>

What's the benefit? Now everything after the filter can handle both parts individually or put differently: the information is preserved. Btw.: you do not need to inspect the data - the structure directly implies the "`is it needed or not?`".

Example: Instead of building a filter that preescapes and then is globally marked as being *safe*, we can now build one that **a)** does not need preescaping, because it is delegated to a later stage (safe analysis will say: the output is not safe), and **b)** the generated parts can still be passed through as *safe* chunks and thus left as they are.

The concept also works with a more complex and non-linear form of composition. Then the application and the resolution need to be adjusted. I intentionally kept it simple in the above code examples.

Did the idea get any clearer?

**Comment by stof** [comment]
> Now everything after the filter can handle both parts individually or put differently: the information is preserved.

Everything after the filter must now accept a `ChunkedText` as argument. Otherwise, the result is not parts handled individually but a TypeError. Also, many changes are *not* equivalent when performed on each chunk vs on the whole string. That's why this is not something that can go in the core IMO. It forces all filters to decide what to do with that special value.

**Comment by stof** [comment]
And wrapping all filter calls into a special `apply` function at runtime to transparently handle ChunkedText would have 2 effects:

- probably a huge performance hit by adding hundreds of function calls during the rendering of a template (and I'm talking about an impact for projects *not* using ChunkedText and so getting slower with no benefit)
- making it impossible to implement a filter that actually operates on that ChunkedText because `apply` would not call the filter in that case (which means that your proposal for `twig_escape_filter` is actually broken as it would never be called that way).

**Comment by fabpot** [comment]
Closing as I don't think this is something we can add in core. And as far as I understand, this is something that can be added in userland/thrid-parties.
