### ISSUE TITLE
Unclosed issue with the word form-inline

### ISSUE THREAD

**Issue by arrowdesign** [twigphp/Twig#3814]
We are upgrading our cms platform from twig 1 to 3.
Fixed some issues but this one used a lot and looks fine to me.

Sample
```
<div class="col-sm-6 {% if item.type == "checkbox" or item.type == "radio" %} form-inline {% endif %} ">
```
Get error Unclosed """ in "content" with or without removing spaces.

Change it 
```
<div class="col-sm-6 {% if item.type == "checkbox" or item.type == "radio" %} test-inline {% endif %} ">
```
No problem

```
<div class="col-sm-6 
{% if item.type == "checkbox" or item.type == "radio" %} 
form-inline 
{% endif %} ">
```
Also works.

Hope you guys can help me out so I can continue my update.

**Comment by xabbuh** [comment]
This does not seem to be happening using pure Twig:

- [form-inline](https://twigfiddle.com/zsk9ce)
- [test-inline](https://twigfiddle.com/zsk9ce/2)

**Comment by arrowdesign** [comment]
Thanks Christian for this handy online test tool and support. I know enough and happy it's actually in my code somewhere.
