### ISSUE TITLE
inline_css should not remove classes

### ISSUE THREAD

**Issue by reflexator** [twigphp/Twig#3817]
When is inline_css filter combined with inky_to_html, css is correctly inlined, but zurb ink responsiveness is driven by media query and classes

example
```
{% apply inky_to_html|inline_css(source('@css/email.css')) %}
```

**Comment by sanderdlm** [comment]
See https://github.com/symfony/symfony/discussions/44923#discussioncomment-1914104.

> That's because foundations-emails.css contains media queries, which cannot be inlined (this is not a limitation of the inliner, but of HTML itself). When using a style tag, this tag is preserved by the inlining, so email clients that support style tags will have the full styles with media queries. When passing the CSS directly to the inliner without having it in the HTML, those media queries are lost.

**Comment by stof** [comment]
inline_css does not remove classes. But in this case, the output HTML does not have styles applied on those classes
