### ISSUE TITLE
Error with php8.1/2 and twig 3.5.1

### ISSUE THREAD

**Issue by maxleistner** [twigphp/Twig#3818]
Hi, i get the following error on a php8.1/2 env. Any ideas?

![Bildschirmfoto 2023-03-10 um 16 05 00](https://user-images.githubusercontent.com/7567185/224355269-437bcc39-ff4d-40ab-a190-05a4474f7182.png)

**Comment by stof** [comment]
My guess is that you have an older version of Twig lying around that gets prefered (or an existing OPCache cache that was not invalidated after the update, keeping an old definition of classes available in the old version), as the signature of `NodeVisitorInterface::enterNode` is the wrong one in the error message.

**Comment by maxleistner** [comment]
Thanks for the hint. I was an "older" (1.22.*) Timber Plugin installed. I deleted it and it worked :)
