### ISSUE TITLE
Called to undefined method ReflectionFunction::getClosureCalledClass() after updating to PHP 8.2

### ISSUE THREAD

**Issue by rooselle** [twigphp/Twig#3819]
After updating my project to PHP 8.2, I have now following error:

```
11:54:05 CRITICAL  [php] Uncaught Error: Call to undefined method ReflectionFunction::getClosureCalledClass() ["exception" => Error { …}]

In CallExpression.php line 307:
                                                                                                      
  Attempted to call an undefined method named "getClosureCalledClass" of class "ReflectionFunction".  
  Did you mean to call "getClosureScopeClass"?
```

And indeed, if I believe PHP doc, `getClosureCalledClass` doesn't exist. https://www.php.net/manual/en/class.reflectionfunction.php, but it is called in `/src/Node/Expression/CallExpression.php` at line 307 when PHP version is equal to or higher than 8.1.11: `elseif (\PHP_VERSION_ID >= 80111 && $class = $r->getClosureCalledClass())`

Could you please help me understand how I can fix this?
(Going back to PHP 8.1.10 fixed the problem)

**Comment by nicolas-grekas** [comment]
I'm not sure what's going on, the method exists since PHP 8.1.11 and it exists also in 8.2+, see
https://3v4l.org/h8BQf

**Comment by rooselle** [comment]
Thank you for your fast answer (and for this 3v4l website that I didn't knew of). :)

So that you could reproduce my problem, I did again step by step my update process on my "base" repo... and I think it doesn't actually come from Twig. :thinking:

I use docker to run my project, and I used `lavoweb/php-8.2:composer`; when doing the process again, I used instead `lavoweb/php-8.2:latest`, and the twig error didn't occur. I found out that the `:composer` image uses PHP 8.2.0beta3 and `:latest` PHP 8.2.0RC4. Since the first one (with which I have the error) is a beta version, it's maybe normal that it's buggy... and maybe the twig error hides something else.

If you happen to have time and are curious, here's the repo: https://github.com/rooselle/symfony-base (`main` works, and `twig-error` has the error)

Otherwise if you do think it has nothing to do with Twig, you can close the issue :)

**Comment by nicolas-grekas** [comment]
Thanks for investigating. It's definitely because of the beta/rc versions. 8.2 is at 8.2.3, beta/rc shouldn't be used anymore.
