### ISSUE TITLE
How to setup local development environment and run the tests?

### ISSUE THREAD

**Issue by szabgab** [twigphp/Twig#3820]
I could not find details describing this but after some experiments I managed to do it and wrote a [blog post](https://dev.to/szabgab/setup-local-development-environment-and-run-tests-of-php-twig-34d3) describing it. If there is already a (better) explanation, I'd appreciate a pointer. 

If there is no such description yet, I'd be happy to send a PR to include such description in the project documentation.

**Comment by stof** [comment]
All you need is to run `composer update` to install the dependencies, and then run `vendor/bin/simple-phpunit` (as done in the CI: https://github.com/twigphp/Twig/blob/78c18ad58e48d3fff2f7812bb60b6176ee52689a/.github/workflows/ci.yml#L56-L57)
