### ISSUE TITLE
Date converstion with format_datetime

### ISSUE THREAD

**Issue by pascalbeynel** [twigphp/Twig#3821]
If i create a new Datetime for January 1st 2023 :
`$date = new \Datetime('2023-01-01');`

and then use it in my twig template with **format_datetime**
`{{ date|format_datetime(locale='fr', pattern="EEEE dd MMMM YYYY") }}`

it returns "dimanche 01 janvier **2022**" instead of **2023**

Dumping datetime object gives:
```
DateTime @1672527600 {#805 ▼
  date: 2023-01-01 00:00:00.0 Europe/Paris (+01:00)
}
```

Dumping object with date filter returns **2023**
`{{ dump(day|date('Y')) }}`

**Comment by stof** [comment]
In the ICU patterns, `Y` means "Year of the weak of year". The calendar year of that date is produced by `y`, not by `Y`: https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table

**Comment by stof** [comment]
side note: the best way to use `format_datetime` is to use one of the predefined format instead of hardcoding a pattern (because different locales are using different patterns)

**Comment by pascalbeynel** [comment]
Thank you for your response, I have learned something today :)
