### ISSUE TITLE
is there a way to create a string without quotes?

### ISSUE THREAD

**Issue by Phoenix1112** [twigphp/Twig#3824]
Hello, I'm new to the twig template engine and I have a question for the masters here. I'm looking for a method that I can use without quotes when specifying a string value. I saw an example online.

```
{{ 42|string }}
```

output:

```
{# returns '42' #}
```

but when I try the above example with online editors, I get errors like ```Unknown "string" filter in "main.twig" at line 1. on line 1```.
can you help me?

**Comment by stof** [comment]
There is no `string` filter in Twig itself. It might come from an extension though.
