### ISSUE TITLE
'replace' filter with PHP 8.1

### ISSUE THREAD

**Issue by maliouba** [twigphp/Twig#3825]
After upgrading to PHP 8.1 I have the following error with the replace filter

`TypeError: strtr(): Argument #1 ($string) must be of type string, array given in strtr() (line 571 of /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php).`

Twig Version : 2.15.4

**Comment by stof** [comment]
The Twig `replace` filter is documented as taking a string as argument, not an array: https://github.com/twigphp/Twig/blob/78c18ad58e48d3fff2f7812bb60b6176ee52689a/src/Extension/CoreExtension.php#L522-L530

So this is a wrong usage in some of your templates

**Comment by maliouba** [comment]
> The Twig `replace` filter is documented as taking a string as argument, not an array:
> 
> https://github.com/twigphp/Twig/blob/78c18ad58e48d3fff2f7812bb60b6176ee52689a/src/Extension/CoreExtension.php#L522-L530
> 
> So this is a wrong usage in some of your templates

Found the issue, thank you!
