### ISSUE TITLE
Use bbclone in my CMS

### ISSUE THREAD

**Issue by ghost** [twigphp/Twig#3852]
Hi!

BBclone is a web counter in PHP. I like it very much.

You can see a demo in the link bellow:

[http://www.bbclone.de/demo/](http://www.bbclone.de/demo/)

To activate it, we need to paste the following code in our pages:

```
 define("_BBC_PAGE_NAME", "Test");
 define("_BBCLONE_DIR", "bbclone/");
 define("COUNTER", _BBCLONE_DIR."mark_page.php");
 if (is_readable(COUNTER)) include_once(COUNTER);
```
The CMS that I installed does not use PHP, it use Twig...

How can I use this code inside Twig?

**Comment by stof** [comment]
You should ask that to the BBClone support or to the support of your CMS. Twig is a library used in a bigger context, so we cannot know how BBClone would fit in the architecture of your CMS.

**Comment by ghost** [comment]
Hi Christophe Coevoet!

Thank you for your tip.
The forum from the BBClone users community helped me to fix this.
All I needed to do was to paste the following code inside the "index.php" file (inside the root directory)

`<?php

define("_BBCLONE_DIR", "bbclone/");
define("COUNTER", _BBCLONE_DIR."mark_page.php");
if (is_readable(COUNTER)) include_once(COUNTER);

require __DIR__  . '/system/vendor/autoload.php';

require __DIR__  . '/system/system.php';

$app->run();
?>`

Now BBClone is working fine.

Thank you again!
(=
