### ISSUE TITLE
PHP 8.3 Constant NumberFormatter::TYPE_CURRENCY is deprecated

### ISSUE THREAD

**Issue by PhilETaylor** [twigphp/Twig#3874]
This is a report of the twig/intl-extra code which has no issues tab in its repo, hope this is the right place you want this, if not sorry please move or close

Just put PHP 8.3.0-RC1 live on production of a large high traffic SaaS (I know I know I know - dockerized so easy to switch.swap.play) and this showed up in sentry.io

relates https://github.com/twigphp/intl-extra/blob/4f4fe572f635534649cc069e1dafe4a8ad63774d/IntlExtension.php#L70

![ScreenShot-2023-09-01-10 51 39](https://github.com/twigphp/Twig/assets/400092/491d4aa5-df9f-43f9-a6fc-3f0a3f37f171)

(Not looking for support, just logging this)

**Comment by stof** [comment]
Side note: you should not turn deprecations into an ErrorException in your error handler (otherwise, you're not actually making them deprecations)

**Comment by PhilETaylor** [comment]
I do dumb things daily - like running PHP 8.3.0-RC1 in production on a large SaaS with thousands of paying users :) but it's helpful to find the real issues quicker haha. 

I don't actually know what is turning deprecation in to ErrorException, Im using standard symfony error handling, but maybe sentry or sentry-bundle is doing that - its helpful to bring things from a hidden log file to "in your face" though :) 

its cool though, Im not looking for support at all here.

**Comment by fabpot** [comment]
Fixed by #3894
