### ISSUE TITLE
missing a feature to easily change the order of blocks in a child template when extending from a parent template twig

### ISSUE THREAD

**Issue by patarok** [twigphp/Twig#3875]
however this could be done... I really dont care 

I am pretty sure someone could have a better idea or improve this one, but we have to start somewhere:

My 2 cents on this would be:
there could be something like {{ blocks.order }} available in each twig with the scope just to the current twig you are addressing/setting it in...
just as a key-value array
which you can dump and then rearrange by setting it like:

--DECLARATION--
{% set blocks.order = {
    1: 'header_block',
    2: 'content_block',
    3: 'footer_block'
} %}
--DUMP--
array(3) {
  [1]=>
  string(12) "header_block"
  [2]=>
  string(13) "content_block"
  [3]=>
  string(12) "footer_block"
}

I guess, one should also reconsider a lot of things about this...
what comes to my mind after the first 2 mind-hops... is that it should be availabel scoped to each block? 
so in each block a new "blocks.order" ... if it has more than 1 child blocks...
???
So I know the problem is with the block levels... 
(because we can go as deep as we want.... nonetheless:)
I guess we could also nest and go as deep as at least 2 levels, 
and the feature itself could bring a lot of comfort and would spare many people 
to rewrite a whole load of blocks all the time. no matter how it works and how it is implemented exactly in the end...
 
 .. so this is just some input for someone really working on twig.

**Comment by stof** [comment]
What do you mean by block order ?

Twig does not have a concept of order for blocks. Blocks are rendered in the place where they are referenced in a template.

**Comment by stof** [comment]
Twig has 2 different concepts related to blocks: block declarations (which are purely a compile-time thing) and block references (which are resolved during rendering, to display the context of a block).

the [`block()` function](https://twig.symfony.com/doc/3.x/functions/block.html) creates a block reference
The [`{% block %}` tag](https://twig.symfony.com/doc/3.x/tags/block.html) has 2 effects:
   - it always declares a block
   - it creates a block reference, *except for top-level blocks in a child template* (the top-level content of a child template is special in Twig)

During the rendering, what matters for the order of rendering is in which order you reference templates. And here, if you use the `block()` function, you are free to put some dynamic logic in your own template based on some variables. But Twig does not have any magic there. It renders things in the order where the template asks to render things.
