### ISSUE TITLE
Allow all methods of class while sandboxing

### ISSUE THREAD

**Issue by tomadmiraal** [twigphp/Twig#3899]
I have a class that has to use the Magic Method __call.

Is it possible to allow ALL methods of a specific class in the SecurityPolicy? Maybe with a wildcard?

Right now I have to write down all the posible methods, but they will be variable loaded from a database depended on the handle that has been set by the constuctor.

At this moment I load the methods like:

```
$methods    = ['MyClass'=>['data','second_method']];

$policy     = new \Twig\Sandbox\SecurityPolicy($tags, $filters, $methods, $properties, $functions);
$sandbox    = new \Twig\Extension\SandboxExtension($policy, true);
```

**Comment by stof** [comment]
This is not supported by the SecurityPolicy class of Twig. But you can achieve it by using a custom implementation of the interface.

**Comment by fabpot** [comment]
It's not something we want to support in core as this is probably not something you want for a sandbox.
