### ISSUE TITLE
file_exists function

### ISSUE THREAD

**Issue by sebcar** [twigphp/Twig#3904]
Hi, I think it would be cool to have a function that uses PHP file_exists function, what do you think?

**Comment by fabpot** [comment]
What would be the use case?

**Comment by sebcar** [comment]
I had to implement a custom function in a specific project in which had to check if an image exist in a path using PHP native file_exists function.  The value of the parameter bag is the absolute path of the public folder. 

```
<?php

namespace App\Twig;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class AppExtension extends AbstractExtension
{
    public function __construct(private ParameterBagInterface $parameterBag)
    {
        
    }

    public function getFunctions(): array
    {

        return [
            new TwigFunction('file_exists', [$this, 'fileExists']),
        ];
        
    }

    public function fileExists(string $path): bool
    {
        $public = $this->parameterBag->get('public_absolute');

        return file_exists($public. DIRECTORY_SEPARATOR . $path);
    }
}
```

**Comment by GromNaN** [comment]
Your implementation requires a `public_absolute` parameter that doesn't exist in Twig. It seems complex to implement in a generic way for something you were able to implement in a few lines with your specific need.

Your use-case looks like the [`asset`](https://symfony.com/doc/current/reference/twig_reference.html#asset) helper. But you would have to implement your own `Package` class that would check if the file exists. That's a bit more complex than what you already made.

**Comment by sebcar** [comment]
Yes, in the case that the feature is accepted, this code need changes to receive the absolute path to the file.

**Comment by fabpot** [comment]
I don't think this should belong to core. Thank you for proposing.
