### ISSUE TITLE
Using the parent function doesn't throw an error when the block is missing in the parent template...but an error exist in the codebase about that

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3906]
I have the feeling that some part of the code are never reached. Consider the following TwigFiddle:

https://twigfiddle.com/252pf2

## main.twig
```twig
{% extends "parent.twig" %}
{% block foo %}
Child plus {{ parent() }}
{% endblock %}
```

## parent.twig
```twig
{% block bar %}
{% endblock %}
```

It does not throw an error, which seems legit since the block is never executed.

But, it seems related to the error thrown there:

https://github.com/twigphp/Twig/blob/9f42a763069e46a0911d0ca2ad0d2f558124af54/src/Template.php#L136

What is strange is that it is not possible to even pass the parsing phase if a template use the `parent` function without having a parent (see there: https://github.com/twigphp/Twig/blob/9f42a763069e46a0911d0ca2ad0d2f558124af54/src/ExpressionParser.php#L445), how is it possible that this error is reached?

There is no test covering it, so maybe it just doesn't work.

Can someone please clarify this? Is there a way to reach that error?

Thanks.

**Comment by stof** [comment]
There is no error because the `foo` block is never executed in your case.

See https://twigfiddle.com/252pf2/2 where I made the parent template *render* the foo block even if it does not define it. And there, the error gets reported.

**Comment by ericmorand** [comment]
Amazing, thanks a lot. The call to `block()` what I was missing to trigger the error.

EDIT: Actually, this is not the error that I mentionned that is thrown:

```php
throw new RuntimeError(sprintf('The template has no parent and no traits defining the "%s" block.', $name), -1, $this->getSourceContext()); 
```

Do you think maybe this error is never triggered because either the parser error _or_ the one of your example trigger before this one can even trigger? I have this error thrown by Twing code base and I'm unable to cover it with integration tests which make me think it is a legacy error that is not thrown anymore.

**Comment by stof** [comment]
this error happens when your template has no parent but has some `{% use %}`: https://twigfiddle.com/4ia6ok

When there is no `{% extends %}` and no `{% use %}`, this is indeed caught at compile time as a SyntaxError. And when there is a parent template, we get a different error message.

**Comment by ericmorand** [comment]
Nailed it! Thank you.
