### ISSUE TITLE
Setup CI on intl-extra

### ISSUE THREAD

**Issue by ruudk** [twigphp/Twig#3910]
It seems that [intl-extra](https://github.com/twigphp/intl-extra) doesn't have any CI set-up. Is this on purpose? 

Also, it doesn't seem to have Issues enabled, that's why I'm reporting it here.

**Comment by ruudk** [comment]
I see it now. It seems that this is a read only repository split from this one.

It would be great if that was a bit more clear in the description of that (and other) repositories.

**Comment by fabpot** [comment]
You're right, same as for Symfony. We have a mono repository and then split for individual "components".
