### ISSUE TITLE
Issue with Environment.php at line 358 eval() after PHP 8 update. 

### ISSUE THREAD

**Issue by aliahmedopf** [twigphp/Twig#3915]
Hi since PHP 8 update we are facing an issue with twig /src/Environment.php on one line 358. 
The issue we encounter is 
"vendor/twig/twig/src/Environment.php(358) : eval()'
err: Array to string conversion "

![image](https://github.com/twigphp/Twig/assets/38085503/77194483-ed0d-4988-86ae-984d64f78c25)

**Comment by GromNaN** [comment]
Can you find the complete backtrace of this error? It seems that the error comes from the template execution.

**Comment by stof** [comment]
The issue you get is not at that line. It is inside code that was eval'd at that line.

**Comment by jkildea** [comment]
Hi there, was there a solution to this problem? I am also encountering it now.
Thank you,

**Comment by alam807** [comment]
Any solution? I am seeing it in Ubuntu 22.04 with php 8.4

**Comment by fabpot** [comment]
To help you, we'd need more information about the templates you're trying to render.
