### ISSUE TITLE
The `autoescape` tag escapes already escaped value by the escape filter

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3918]
According to the [documentation of the autoescape tag](https://twig.symfony.com/doc/3.x/tags/autoescape.html):

> Twig is smart enough to not escape an already escaped value by the [escape](https://twig.symfony.com/doc/3.x/filters/escape.html) filter.

But, when testing TwigPHP, it seems like the `autoescape` tag actually _do_ escape already escaped value by the escape filter:

```twig
{% set br = "<br/>" %}
{% autoescape "css" %}
{{ br|escape('html') }}
{% endautoescape %}
```

> \26 lt\3B br\2F \26 gt\3B 

https://twigfiddle.com/qtyoxi

So, which one is correct: TwigPHP implementation or the documentation?

**Comment by smnandre** [comment]
> When using automatic escaping, Twig tries to not double-escape a variable **when the automatic escaping strategy is the same as the one applied by the escape filter**;

> css: escapes a string for the CSS context. CSS escaping can be applied to any string being inserted into CSS and **escapes everything except alphanumerics**.

Both are correct.

https://twig.symfony.com/doc/3.x/filters/escape.html

**Comment by ericmorand** [comment]
So one of the page of the documentation is wrong.

**Comment by stof** [comment]
The note on the autoescape documentation is not explicit enough. But `value|escape('css')` is not already escaped for html. So it is not wrong per se.

**Comment by fabpot** [comment]
Would #4342 be enough to clarify the docs?
