### ISSUE TITLE
Shouldn't the sandbox tag be "unrecommended", just like the "include" tag is?

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3921]
The `include` tag is "unrecommended" since Twig 1.12:

> It is recommended to use the [include](https://twig.symfony.com/doc/3.x/functions/include.html) function instead as it provides the same features with a bit more flexibility:

https://twig.symfony.com/doc/3.x/tags/include.html

And the `sandbox` tag only applies to the `include` tag:

> The sandbox tag can only be used to sandbox an include tag

https://twig.symfony.com/doc/3.x/tags/sandbox.html

So, shouldn't the `sandbox` tag also come with a note that says that it is recommended to use the `include` function (that comes with an `include` parameter) instead?

About that, is it planned to deprecate these two tags for good at one point?

**Comment by stof** [comment]
Technically, the `{% sandbox %}` tag also applies to other cases:

- it applies to the `{% embed %}` (which is an include of an anonymous template extending a base template)
- it also impacts the `include` function as include anything inside a sandbox is still restricted by the sandbox (`sandbox=false` in the `include` function does not disable the sandbox. It only avoids turning it on for that include. there is no way to disable a sandbox applied by a caller).

**Comment by stof** [comment]
the documentation should be updated to say `can only sandbox an included template` instead of saying `an include tag`, as the `include` tag is not the only way to include a template anymore.

**Comment by ericmorand** [comment]
But doesn't it throw an error when its direct child is not an include tag?

Maybe I'm misreading this code, but it looks like it only accepts nodes that inherit `IncludeNode` - or text node:

https://github.com/twigphp/Twig/blob/aeeec9a5e907a79e50a6bb78979154599401726e/src/TokenParser/SandboxTokenParser.php#L42C38-L42C38

```php
 // in a sandbox tag, only include tags are allowed
        if (!$body instanceof IncludeNode) {
            foreach ($body as $node) {
                if ($node instanceof TextNode && ctype_space($node->getAttribute('data'))) {
                    continue;
                }

                if (!$node instanceof IncludeNode) {
                    throw new SyntaxError('Only "include" tags are allowed within a "sandbox" section.', $node->getTemplateLine(), $stream->getSourceContext());
                }
            }
        }
```

Typically, shouldn't it throw when one of its direct child is a function node - like the "include" function?

> there is no way to disable a sandbox applied by a caller).

That's what I was assuming, thanks for confirmation. Conceptually, the `sandbox` parameter only accepts `true` as a legit value.

**Comment by stof** [comment]
ah, I forgot about this restriction in it at parse-time.

Then indeed, it should be unrecommended.

> That's what I was assuming, thanks for confirmation. Conceptually, the `sandbox` parameter only accepts `true` as a legit value.

The `sandbox` attribute could be named `enableSandbox` if we wanted a longer name, not `runSandboxed` (btw, that's why it is not name `sandboxed` either). `false` is a legitimate value (but there is not much reason to pass it explicitly instead of relying on the default). But `not enabling the sandbox here` is not the same than `disabling the sandbox here`.

**Comment by ericmorand** [comment]
> Then indeed, it should be unrecommended.

Not sure. If it accepts an embed node - which seems to be the case as EmbedNode inherits from IncludeNode - then your first point remains valid: it should not be unrecommended since it can be used to wrap an `embed` tag.

**Comment by stof** [comment]
`class EmbedNode extends IncludeNode`. So it is accepted.

**Comment by ericmorand** [comment]
Thanks, there is no point at "un"recommending it. I close.
