### ISSUE TITLE
`cycle` function on an empty hash / array throws an exception

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#3925]
https://twigfiddle.com/2scom6

```twig
{{ cycle({}, 1) }}
```

> An exception has been thrown during the rendering of a template ("Modulo by zero").

Note that the same exception is thrown when passing an empty array:

```twig
{{ cycle([], 1) }}
```

I assume the output here should be a blank string - this is what Twing outputs organically.

**Comment by xabbuh** [comment]
Having an empty array as the input of the `cycle()` function doesn't make much sense to me (we could even argue that one-element-arrays are quite useless). But an empty array should be handled by the `cycle()` function and lead to a proper error triggered by Twig instead of a PHP error.

**Comment by ericmorand** [comment]
The thing is you usually can't guess by advance if the value that you cycle on is empty or not: the example is the shortest possible way to showcase the issue but the usual case is that you cycle on a variable that was passed to the template at render-time.

Not allowing cycling on empty array means that everytime we use the `cycle` function, we have to first do an `is empty` check.

**Comment by xabbuh** [comment]
If you really do not know what is passed to `cycle()` you will indeed have to check that first. The usages that I typically see for this function look something like `cycle(['odd', 'even'], loop.index1)` where one knows in advance that the passed argument is not empty.

**Comment by ericmorand** [comment]
> If you really do not know what is passed to cycle() you will indeed have to check that first

That's exactly the point: either it is mandatory and then it must be in the documentation; or it is not and the function must handle gracefully empty iterables.

**Comment by xabbuh** [comment]
PR welcome to improve the documentation and the function's error handling I guess. :)

**Comment by ericmorand** [comment]
I don't have access to the specification of the language, so I can't propose anything without likely being rejected because I'm not implementing the spec. My issue is just for the maintainers to maybe take the problem into account and improve on the specification.

**Comment by stof** [comment]
@ericmorand there is **no** specification of the language.

**Comment by ericmorand** [comment]
Fair enough, but how are tests written if there ain't?

This example is quite typical: what is the expected behaviour of the cycle function on an empty iterable? If I was to propose a fix, how would it be decided that it is legit or not?
