### ISSUE TITLE
[Intl] format to feminine ordinal numbers

### ISSUE THREAD

**Issue by JorickPepin** [twigphp/Twig#3931]
As mentioned in [this issue](https://github.com/twigphp/Twig-extensions/issues/211), the addition of the Intl extension should have enabled the display of feminine ordinal numbers through the `format_ordinal_number` filter (e.g. `1re` instead of `1er` in French), but is this really the case? If so, how could this be achieved? Thanks in advance.

**Comment by smnandre** [comment]
In the _current_ implementation, i think you'd code it quicker by yourself in a dedicated extension... than with the IntlExtension.

As you can see in the [createNumberFormatter](https://github.com/twigphp/Twig/blob/4c179c8a64fece77e17ef299d1a2a3f908993107/extra/intl-extra/IntlExtension.php#L460)() method, the only way to set textAttributes would be to [inject a $prototype](https://github.com/twigphp/Twig/blob/4c179c8a64fece77e17ef299d1a2a3f908993107/extra/intl-extra/IntlExtension.php#L153) ... but even then, you'd only can set "feminine" or "masculine" once.

Or you can try to find another way to add this behaviour line 511 (if the $textAttrs in not usable as right now) 

```php

        foreach ($textAttrs as $name => $value) {
            $this->numberFormatters[$hash]->setTextAttribute(self::NUMBER_TEXT_ATTRIBUTES[$name], $value);
        }

        foreach ($symbols as $name => $value) {
            $this->numberFormatters[$hash]->setSymbol(self::NUMBER_SYMBOLS[$name], $value);
        }

+        $this->numberFormatters[$hash]->setTextAttribute(self::NUMBER_TEXT_ATTRIBUTES['default_ruleset'], '%digits-ordinal-feminine');

        return $this->numberFormatters[$hash];
    }
}
```
