### ISSUE TITLE
Title: Feature Request: Add optional Filter-Closure to 'first' Filter in Twig

### ISSUE THREAD

**Issue by rkrx** [twigphp/Twig#3962]
Twig already offers a [`first`](https://twig.symfony.com/doc/3.x/filters/first.html) filter that is used to retrieve the first value of a list (array, iterable). This feature request proposes an enhancement to the `first` filter by adding an _optional_ parameter that allows users to specify a filter closure. This closure would enable the `first` filter to skip over entries that do not match the expression defined in that filter closure.

## Use Case

This enhancement would be particularly useful in scenarios where users need to fetch the first item from a list that meets certain criteria, rather than just the first item in the list. For example, in a list of numbers, a user might want to retrieve the first number that is greater than 10, or in a list of strings, the first string that contains a certain substring.

## Example
Here's an example of how this might look in practice:

```twig
{% set numbers = [1, 2, 13, 4, 5] %}
{% set firstAboveTen = numbers|first(value => value > 10) %}
```
In this example, `firstAboveTen` would be `13`, as it's the first number in the list that is greater than `10`.

### Another example:

```twig
{% set attributes = [{name: 'a', value: 1}, {name: 'b', value: 2}, {name: 'c', value: 2}] %}
{{ attributes|first(a => a.name == 'b').value }}
```
Output: `2`

**Comment by smnandre** [comment]
You probably meant "first" instead of "filter" in your last example ? 

```twig
{{ attributes|first(a => a.name == 'b').value }}
```

But that is related to what i was going to say: is this really a gain compared to `|filter(..)|first` ?

**Comment by rkrx** [comment]
> You probably meant "first" instead of "filter" in your last example ?

Thank you, fixed that. 

> But that is related to what i was going to say: is this really a gain compared to `|filter(..)|first` ?

Yes, but that's more verbose and a predicate for first is a pretty obvious read. [This](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/first.html) is how Kotlin defines a [first](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/first.html)-"filter".

**Comment by smnandre** [comment]
> Yes, but that's more verbose and a predicate for first is a pretty obvious read. [This](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/first.html) is how Kotlin defines a [first](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/first.html)-"filter".

Similar to "[Array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)" in JS too

**Comment by smnandre** [comment]
I tried something in [this PR](https://github.com/twigphp/Twig/pull/3963), let's see what the Twig team think about it :)
