### ISSUE TITLE
Use throw expressions in compiled templates?

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#3984]
I was checking the source code of a compiled Twig template and I saw a lot of code similar to this _(reformatted for clarity)_:

```php
$context['_seq'] = twig_ensure_traversable(
    twig_get_attribute(
        $this->env,
        $this->source,
        (
            isset($context["paginator"]) || array_key_exists("paginator", $context)
                ? $context["paginator"]
                : (function () { throw new RuntimeError('Variable "paginator" does not exist.', 6, $this->source); })()
        ),
        "results",
        [],
        "any",
        false,
        false,
        false,
        6
    )
);
```

Since PHP 8.0, `throw` can also be used in expressions (https://wiki.php.net/rfc/throw_expression). So, we could reformat this code:

```php
(
    isset($context["paginator"]) || array_key_exists("paginator", $context)
        ? $context["paginator"]
        : (function () { throw new RuntimeError('Variable "paginator" does not exist.', 6, $this->source); })()
),
```

into this:

```php
$context["paginator"] ?? throw new RuntimeError('Variable "paginator" does not exist.', 6, $this->source),
```

If the new code is truly equivalent in all cases, my guess is that this could improve runtime performance.

**Comment by fabpot** [comment]
That's already the case on the 4.x branch. See https://github.com/twigphp/twig/commit/583d7b2d2

**Comment by stof** [comment]
Note that your suggested `??` is not equivalent (any variable containing `null` would throw with your proposal)
