### ISSUE TITLE
markdown_to_html Strikethrough is not working

### ISSUE THREAD

**Issue by choarau-craft** [twigphp/Twig#3995]
Hello.

When trying to render a `~~Strikethrough~~`, it's rendered as `~~Strikethrough~~` instead of `<strike>Strikethrough</strike>`

I'm using latest version with symfony 6.4

**Comment by sstok** [comment]
https://twig.symfony.com/doc/3.x/filters/markdown_to_html.html

This depends on which Markdown library is used, Twig itself doesn't provide markdown rendering.
You need to enable this markdown extension https://commonmark.thephpleague.com/2.4/extensions/strikethrough/ 👍🏼
