### ISSUE TITLE
Allow comments within components / function calls

### ISSUE THREAD

**Issue by tacman** [twigphp/Twig#4001]
It is so natural to comment out HTML attributes that it's easy to think that Twig supports this. So easy that even the Symfony UX documentation has an example.

```twig
// ...

<div class="toggle-password-container"> // Add "toggle-password-container" or a class that applies position: relative to this container.
    <label for="password">Password</label>
    <input
        id="password"
        name="password"
        type="password"
        {{ stimulus_controller('symfony/ux-toggle-password/toggle-password', {
                {# visibleLabel: 'Show password', // If you want to modify this label. #}
                {# visibleIcon: 'Some svg icon', // If you want to modify this icon. #}
                {# hiddenLabel: 'Hide password', // If you want to modify this label. #}
                {# hiddenIcon: 'Some svg icon', // If you want to modify this icon. #}
                buttonClasses: ['toggle-password-button'], // Add as many classes as you wish. "toggle-password-button" is needed to activate the default CSS.
        }) }}
    >
</div>

// ...
```

https://symfony.com/bundles/ux-toggle-password/current/index.html#usage-without-symfony-forms

I started to make a PR to fix the docs, but it's not easy to decide where to move it.  It'd be awesome if twig allowed this, as I frequently use it for in-line comments as well as disabling attributes.

**Comment by eokic** [comment]
Not sure what the best way forward is, but I would also like to point out this extremely painful [TwigComponent](https://symfony.com/bundles/ux-twig-component/current/index.html) usecase for us where we have to resort to writing prop explanations above the whole thing instead of inline. It becomes increasingly less readable the more props we have of course.

```twig
{# props
  propOne: Lorem ipsum dolor sit amet
  propTwo: Lorem ipsum dolor sit amet
  propThree: Lorem ipsum dolor sit amet
#}
{% props
  propOne = 1, // This is not a valid comment
  propTwo = null, /* nor is this */
  propThree = null, {# nor is this of course #}
%}
```

**Comment by fabpot** [comment]
Allowing `{#` within `{{` or `{%` looks weird to me. That would be the only time when we allow such embeddings.
I think we need to find another notation for inline comments.

I had a look at Jinja and they don't support it.

Liquid has a syntax though, they use `#`:

```liquid
{% liquid
  # this is a comment
  assign topic = 'Learning about comments!'
  echo topic
%}
```

I think it could work. IIUC, such comments in Liquid must be on their own line.

**Comment by tacman** [comment]
@fabpot  Thanks for considering this.  That would work fine for my common use cases.

**Comment by fabpot** [comment]
3 lines of code, 130 lines of tests and docs 😂
