### ISSUE TITLE
install twig manualy without use composer or other way?

### ISSUE THREAD

**Issue by wwwbarnamehadotnet** [twigphp/Twig#4012]
hi,i am new at twig ,still i am not sure about use twig , i just want change my html pages to template and use them for php ,i dont know which engin wil be better and which one will be simple for use ,if i  want use twig only for my site so i installed wamp on my pc and my php version is 7.3.5 , i  installed last version of composer fron main site, after run **composer require "twig/twig:^3.0"** or **composer require "twig/twig:^2.0"**  this error : 

```
H:\html\new\code\twig>composer require "twig/twig:^3.0"
./composer.json has been created
Running composer update twig/twig
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - twig/twig v3.0.0 requires php ^7.2.9 -> your php version (5.6.40) does not
 satisfy that requirement.
    - twig/twig[v3.0.1, ..., v3.0.3] require php ^7.2.5 -> your php version (5.6
.40) does not satisfy that requirement.
    - twig/twig[v3.0.4, ..., v3.8.0] require php >=7.2.5 -> your php version (5.
6.40) does not satisfy that requirement.
    - Root composer.json requires twig/twig ^3.0 -> satisfiable by twig/twig[v3.
0.0, ..., v3.8.0].


Installation failed, deleting ./composer.json.
```
how can i solve this problem or possible to i just download vendor folder (my means twig files) if its enough ?
this is my screen shot of my wamp and versions info : 
![001002003](https://github.com/twigphp/Twig/assets/12879605/1a9bead7-07d0-4084-9165-51f49f3fc852)

**Comment by lyrixx** [comment]
You should not use the latest version of twig '^3'. Let composer choose [the best version](https://packagist.org/packages/twig/twig#v1.42.5) for your platform



```console
$ composer require twig/twig
```

then, read the [appropriate documentation](https://github.com/twigphp/Twig/blob/v1.42.5/doc/api.rst#twig-for-developers)

**Comment by stof** [comment]
It looks like your PHP CLI uses PHP 5.6.40 while your wampserver uses PHP 7.3.5 when running the server. If you intent to use PHP 7.3.5, make sure to also use it in the CLI.

**Comment by wwwbarnamehadotnet** [comment]
thanks guys , my problem solved with CLI (by change in environment variables  || not worked with right click on wamp and change CLI php version) ,i have to start learn this engine now , still i am not sure about am i on right way for choiced this engine or better idea? i just have some html pages used css jquery js and etc and i wanna make tempale with simple codes and simple ways to use by php

**Comment by lyrixx** [comment]
Twig is the best template engine. Among all languages. You won't regret it. 

If we have answered your questions, could you close this issue? Thank
