### ISSUE TITLE
PDF generation with headless Chrome from Twig HTML using assetMapper and css_inliner, CSS/JS not loaded

### ISSUE THREAD

**Issue by Shotman** [twigphp/Twig#4013]
Hello,
I'm making a Symfony service to generate PDF from HTML with a headless chrome install (spiritix's package) , the HTML generated is good (ie works if I just return it to my normal web browser) but the issue is that when sent to the headless chrome seems like the css/js files created by the `importmap("app")` Twig function aren't loaded.

I tried wrapping everything in the `apply inline_css` but no success.

So is there any options to make the url absolute to have the headless chrome still get the assets or any way to make the inline_css extentsion to work with assetMappern or maybe something completly different I'm missing ? 

Thank you

**Comment by stof** [comment]
I don't see how this is related to the Twig project, which is just a templating engine.
