### ISSUE TITLE
Generating random/minimized class names (obfuscate) for production in Twig

### ISSUE THREAD

**Issue by sovetski** [twigphp/Twig#4015]
Hi,

It is a feature request (if it does not exists already), to get the ability to randomize the class names on production.

The idea is exactly the same as here: https://github.com/tailwindlabs/tailwindcss/discussions/10593 (or also here https://stackoverflow.com/questions/55856411/replace-css-classes-everywhere-when-building-for-production-css-html-twig-j)

Even if we use front end tools to randomize it, the twig will still get the hardcoded class names. On the production, if we are using Tailwind for example, any one can copy paste our components/entire website.

There is also an issue about HTML sizes, we can get very big HTML code with Tailwind, and if it is not obfuscated it can be also an issue for performances

Thanks in advance!

**Comment by WebMamba** [comment]
> There is also an issue about HTML sizes, we can get very big HTML code with Tailwind, and if it is not obfuscated it can be also an issue for performances

Why do you think this can reduce the DOM size? In my understanding, we just changing the className to a hash.

**Comment by ericmorand** [comment]
@sovetski out of curiosity, what is the benefit of obfuscating class names? Do you have some resources that demonstrate that obfuscating class names bring performance improvements?

**Comment by yguedidi** [comment]
> any one can copy paste our components/entire website.

I think this is still possible for people who want to copy components, they will just have to keep the obfuscated names 😅

**Comment by sovetski** [comment]
Hi everyone,

Thank you for your feedback.

I'll try to explain my point of view, I want to clarify that it's solely based on my experience with projects and my research on the internet.

Of course, everyone will say what they believe to be true and defend their ideas.

@WebMamba I was mainly referring to cases like Tailwind, I'm not sure if you've ever used it, but you can have huge class names. Let me give you this example:

```html
<button class="bg-indigo-600 px-4 py-3 text-center text-sm font-semibold inline-block text-white cursor-pointer uppercase transition duration-200 ease-in-out rounded-md hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-600 focus-visible:ring-offset-2 active:scale-95">
    Tailwind Button
</button>
```

With obfuscation, it can become this (thus reducing its size):

```html
<button class="yz56q1z">
    Tailwind Button Obfuscated
</button>
```

If you don't believe me, create a test.html file, first add the first Tailwind button with the large class name, load the file, and look in your browser's "Network" and note the size of the test.html file, then add the second button with the obfuscated class, you will see that the size decreases. So, of course, here we are talking about just one button so the difference is negligible, but on large websites, it can have a big impact.

@ericmorand as I just mentioned above, it reduces the size of the DOM. Here are some resources on the subject:

https://web.dev/articles/dom-size-and-interactivity
https://stackoverflow.com/questions/23497780/does-css-class-name-length-affect-browser-performance
https://web.dev/articles/reduce-the-scope-and-complexity-of-style-calculations
https://www.commercegurus.com/dom-size/

They don't often directly address class names, but it's related to the size of the DOM.

@yguedidi yes, unfortunately, it's almost impossible to prevent visual components from being stolen, anyway, it remains something processed on the user's side so logically they can do whatever they want. But obfuscating the classes will reduce the readability of the components. Look at my example above with the button. It also reduces the effectiveness of bots that come to scrape. Please note, I'm not saying that it makes anything impossible, but it does intimidate or demoralize many who will be curious to look into the source code.

**Comment by fabpot** [comment]
Thank you @sovetski for the detailed follow-up. I'm going to close as this is not something in the scope of Twig (Twig being a general templating system).

**Comment by ericmorand** [comment]
@sovetski, maybe you could use SASS, create a class for your component and import there all the mixins that you pass as classes. I have a very hard time to understand what are the benefits of passing classes that actually describe the style instead of one single class that is composed from a set of SASS mixins.
