### ISSUE TITLE
Deferred blocks broken with 3.9.0/3.9.1

### ISSUE THREAD

**Issue by fashxp** [twigphp/Twig#4026]
### Template: 

```twig
<html>

<body>
    {% block content deferred %}
        <h1>hello world</h1>
    {%  endblock %}
</body>

</html>
```

### Error message: 
![image](https://github.com/twigphp/Twig/assets/8792145/da3cdd6c-1958-42f6-a691-abb933ee490d)

example works with twig/twig < 3.9.0

see also https://github.com/twigphp/Twig/issues/4024

**Comment by stof** [comment]
Defered blocks are not a concept that exist in Twig core.

**Comment by fashxp** [comment]
Sorry, my bad. Created a ticket here too: https://github.com/rybakit/twig-deferred-extension/issues/20.

I'm still wondering, if the changes of twig/twig 3.9.0 which break that concept should/could be considered as BC break?

**Comment by stof** [comment]
This extension does quite weird tricks, replacing the parsing and compilation of Twig blocks. Making such case covered by the BC promise would actually require never doing any internal refactoring in Twig, as extensions doing such weird thing will break

**Comment by fashxp** [comment]
I understand. Is there some other concept that provides a similar result as this extension for deferred blocks does?

**Comment by stof** [comment]
I'm closing this issue as this is about an issue in an unofficial extension, which is where this should be solved.

Note that the deferred-extension is a huge hack to me, and I don't think it is even possible to make it yield-ready to fit in the updated architecture of Twig. This is because it fundamentally changes the execution model of Twig (looking at what it does, it is not just about deferring the execution of the deferred block, but also about deferring the output of everything coming after the display of that block to be able to still have the block output in the right place, while still not deferring the _execution_ of what comes after the block)

**Comment by ericmorand** [comment]
@stof while I agree that the extension is a hack - and I'm not even sure what it factually brings to the language - it is still in my opinion debatable that a minor version of Twig breaks it. You mention the updated architecture of Twig but is this updated architecture anything else than an arbitrary technical choice? Said differently: was this change of architecture required to implement something new in Twig 3.9?

If not, then I don't see why this change was included considering that it would break a lot of things written by the community. Wouldn't 4.x have been more appropriate for such a technical change?

**Comment by fabpot** [comment]
Again, things are deprecated in minor versions to let people upgrade to the new way and removed in the next major.
But there is no guarantee about the inner workings of Twig itself. Only the public API is covered by the backward compatibility policy. And to be honest, I'm not sure it's going to break a lot of things.

**Comment by ericmorand** [comment]
Fair point. And if only the public API is covered by the backward compatibility policy, then one may ask why some non public API are covered by the policy (like the _display_end_ node) and why some others are not. Considering the important number of issues that are opened by the community about 3.9, I think that some clarification is due about what is covered and what is not.

**Comment by stof** [comment]
The `display_end` block is a public extension point of Twig for extensions. Replacing the way blocks are parsed and executed is not. That's the difference.
