### ISSUE TITLE
[3.9] Cannot assign the output of a custom tag to a variable using `set`

### ISSUE THREAD

**Issue by MauricioFauth** [twigphp/Twig#4039]
After Twig 3.9.0, it's not possible to capture the output of a custom tag (that uses `echo`) and assign it to a variable using `set`.

```twig
A {% set variable %}{% trans 'value' %}{% endset %} B {{ variable }} C
```

With Twig 3.9.0+, that will print:
```
A value B  C
```

Instead of the expected:
```
A  B value C
```

It works as expected if the custom tag output is not the only content, for example:
```twig
A {% set variable %}some {% trans 'value' %}{% endset %} B {{ variable }} C
```
Outputs:
```
A  B some value C
```

**Comment by fabpot** [comment]
If the `trans` tag comes from Symfony, I've tried `A {% set variable %}{% trans %}value{% endtrans %}{% endset %} B {{ variable }} C` and it works as expected. Can you confirm that you're not using the `trans` tag from Symfony? If yes, then, I would need something I can reproduce.

**Comment by MauricioFauth** [comment]
It was from [phpmyadmin/twig-i18n-extension](https://github.com/phpmyadmin/twig-i18n-extension/tree/4.1.x) that is a fork of [Twig's `I18nExtension`](https://github.com/twigphp/Twig-extensions).

I "fixed" this in the phpmyadmin/twig-i18n-extension 4.1.1 by adding support for yield if Twig 3.9 is detected, but phpmyadmin/twig-i18n-extension 4.1.0 doesn't work with Twig 3.9 because of that.

- https://github.com/phpmyadmin/twig-i18n-extension/pull/12

**Comment by fabpot** [comment]
For reference: https://github.com/phpmyadmin/twig-i18n-extension/pull/12/files
