### ISSUE TITLE
[cssinliner-extra] CssToInlineStyles implicit nullable types deprecations (PHP 8.4)

### ISSUE THREAD

**Issue by smnandre** [twigphp/Twig#4056]
[CssToInlineStyles](https://github.com/tijsverkoyen/CssToInlineStyles) (used in [twig-extra](https://github.com/twigphp/Twig/blob/3.x/extra/cssinliner-extra/composer.json)) package triggers deprecations on PHP 8.4

```console
  1x: TijsVerkoyen\CssToInlineStyles\Css\Property\Processor::convertToObject(): Implicitly marking parameter $specificity as nullable is deprecated, the explicit nullable type must be used instead
    1x in IntegrationTest::testIntegration from Twig\Extra\CssInliner\Tests

  1x: TijsVerkoyen\CssToInlineStyles\Css\Property\Processor::convertArrayToObjects(): Implicitly marking parameter $specificity as nullable is deprecated, the explicit nullable type must be used instead
    1x in IntegrationTest::testIntegration from Twig\Extra\CssInliner\Tests

  1x: TijsVerkoyen\CssToInlineStyles\Css\Property\Property::__construct(): Implicitly marking parameter $specificity as nullable is deprecated, the explicit nullable type must be used instead
    1x in IntegrationTest::testIntegration from Twig\Extra\CssInliner\Tests
```

I would have created a PR on the package repo, but as the package is compatible with PHP 5.5 i'm not sure what to do ... 

AFAIK there is [no simple solution](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated) for librairies supporting PHP < 7.1 (where nullable argument was introduced)

How is it possible to deal with such situation ?

**Comment by fabpot** [comment]
At this point, I would recommend that the project drops such old versions of PHP.

**Comment by smnandre** [comment]
I've just realised @stof is one of the maintainer (or can merge PR at least - not sure) of CssToInlineStyles. What do you think ? Do we have other alternatives ?

**Comment by xabbuh** [comment]
see tijsverkoyen/CssToInlineStyles#247

**Comment by fabpot** [comment]
Closing here then.
