### ISSUE TITLE
Twig lint throw error

### ISSUE THREAD

**Issue by trsteel88** [twigphp/Twig#4057]
May relate to https://github.com/twigphp/Twig/issues/4025

The `bin/console lint:twig src/ templates/ --show-deprecations` command currently throws an error for a deprecation:

```
Error: The "Symfony\Bridge\Twig\NodeVisitor\TranslationNodeVisitor" class extends "Twig\NodeVisitor\AbstractNodeVisitor" that is deprecated since 3.9 (to be removed in 4.0).
  ERROR  in templates/base.html.twig (line 0)
  >> The "Symfony\Bridge\Twig\NodeVisitor\TranslationNodeVisitor" class extends "Twig\NodeVisitor\AbstractNodeVisitor" that is deprecated since 3.9 (to be removed in 4.0). 
Warning: ] 0 Twig files have valid syntax and 1 contain errors.                 
Error: Process completed with exit code 1.
```

You can view an example repo here: https://github.com/trsteel88/Broken-Twig
Here is a failing test: https://github.com/trsteel88/Broken-Twig/actions/runs/8871380718/job/24354277478

The repository was created with: `symfony new --webapp my_project`

**Comment by fabpot** [comment]
It's a deprecation, not an error. It will be fixed in Symfony, nothing to do in Twig itself.

**Comment by trsteel88** [comment]
Thanks @fabpot - is this something that will only be fixed in Symfony 8 or will it be resolved in 7? This is currently making our test useless as this error occurs on all our applications

**Comment by trsteel88** [comment]
Ignore this. Looks like it's resolved in the latest release. Thank you.
