### ISSUE TITLE
[RFC] deprecate tag `include` in favor of function `include`

### ISSUE THREAD

**Issue by 94noni** [twigphp/Twig#4067]
hey 👋🏻 

Regarding [this PR](https://github.com/VincentLanglet/Twig-CS-Fixer/pull/218)
and the comments/twigs/docs linked (listed down below)

I would like to know what is the best way to deprecate the tag in this root repo.
I am open to work on it, just wanted to know the proper way to make review easy

thank you

---

- https://github.com/VincentLanglet/Twig-CS-Fixer/pull/218
- https://twitter.com/lyrixx/status/1765694838756807153
- https://github.com/VincentLanglet/Twig-CS-Fixer/issues/140
- https://twig.symfony.com/doc/3.x/tags/include.html
- https://twitter.com/fabpot/status/1765719169662648337

friendly ping @VincentLanglet

**Comment by VincentLanglet** [comment]
> Regarding [this PR](https://github.com/VincentLanglet/Twig-CS-Fixer/pull/218) and the comments/twigs/docs linked (listed down below)

The TwigCsFixer is not directly related to the twig repository, I decide nothing about it ^^.

But some PR can be quoted as showing some direction the twig repository is taking about the include tag:
- https://github.com/twigphp/Twig/pull/2016
- https://github.com/symfony/symfony/pull/52126

**Comment by 94noni** [comment]
> I decide nothing about it ^^

👍🏻 of course, just pointing out our discussion which leads to this issue ;)

**Comment by fabpot** [comment]
I don't think this is worth it for 2 reasons: first, this tag exists in Jinja, then, as this is widely used, upgrading would be painful. That's why I've never deprecated the include tag.
