### ISSUE TITLE
Warning in compiled Twig template : "Warning: Undefined variable $blocks"

### ISSUE THREAD

**Issue by jkgroupe** [twigphp/Twig#4079]
With the version 3.9.3, I get this warning when I'm using variable on cache tag on my symfony project (version 6.4.7)
> An exception has been thrown during the rendering of a template ("Warning: Undefined variable $blocks").

You can find bellow a small example 
```
{% cache 'project_%s_%s'|format(project.id, project.updatedAt.timestamp) ttl(36000) %}
   {% set list %}
      <div class="list-group list-group-flush"></div>
   {% endset %}
   {{ list }}
{% endcache %}
```

Here is my composer.json file about twig packages with the current versions in my project

> "twig/cache-extra": "3.9.0",
> "twig/cssinliner-extra": "3.9.0",
> "twig/extra-bundle": "3.9.3",
> "twig/intl-extra": "3.9.2",
> "twig/string-extra": "3.9.0",
> "twig/twig": "3.9.3"

![Capture d’écran 2024-05-07 à 16 40 12](https://github.com/twigphp/Twig/assets/4007104/359c3864-5080-4d77-b435-93ce6a41caef)

Hope it can help

**Comment by fabpot** [comment]
I don't get the warning with the snippet you've shared.

**Comment by kriskoch** [comment]
I am also getting the same error, and I also use the cache tag

The compiled template has this line
`$___internal_parse_0_ = ('' === $tmp = \Twig\Extension\CoreExtension::captureOutput((function () use (&$context, $macros, $blocks) {
`
and blocks does not exist in this context..

The function has this format 
   ```
 // line 6
    public function block_body($context, array $blocks = [])
.....

// line 27
        yield $this->env->getRuntime('Twig\Extra\Cache\CacheRuntime')->getCache()->get(((CoreExtension::getAttribute($this->env, $this->source, CoreExtension::getAttribute($this->env, $this->source, ...... , function (\Symfony\Contracts\Cache\ItemInterface $item) use ($context, $macros) {

...
       // line 44
$___internal_parse_0_ = ('' === $tmp = \Twig\Extension\CoreExtension::captureOutput((function () use (&$context, $macros, $blocks) {
```

So you can see that the cache function on line 27 is not capturing the $block variable from block_body so the inner function for line 44 does not have access to the variable


Line 27 in my twig file is this  {% cache siteContext.site.id~'view-generics-'~generic.id %}
And line 44 is  {% apply spaceless %}

Something in the  3.9 release  broke this as  I downgraded to 3.8 and it worked fine

Downgrading twig/twig (v3.9.0 => v3.8.0): Extracting archive
  - Downgrading twig/cache-extra (v3.9.0 => v3.8.0): Extracting archive

**Comment by fabpot** [comment]
@kriskoch Without the Twig template that allows me to reproduce, there is little I can do.

**Comment by fabpot** [comment]
Reproduced now :)

**Comment by kriskoch** [comment]
Thanks @fabpot .  Sorry that I forgot to include a reproducible case
