### ISSUE TITLE
cache-extra: Serialization-error caused by the yield mode

### ISSUE THREAD

**Issue by mkrauser** [twigphp/Twig#4080]
Using the cache-tag with Twig 3.9 leads to a serialization error:

```
An exception has been thrown during the rendering of a template ("Serialization of 'Generator' is not allowed").
```

IMHO the problem is, that the yield-statements generated by twig cannot be serialized. Here's an example of this:

```
$cached = $this->env->getRuntime('Twig\Extra\Cache\CacheRuntime')->getCache()->get("xyz", function (\Symfony\Contracts\Cache\ItemInterface $item) use ($context, $macros) {
            ob_start(function () { return ''; });
            // line 5
            yield "\t\t\ttest
\t\t";
            
            return ob_get_clean();
        });
```

**Comment by fabpot** [comment]
Can you give us a Twig template that would allow us to reproduce this issue?

**Comment by fabpot** [comment]
Are you using 3.9.3?

**Comment by mkrauser** [comment]
Yes, I used 3.9.3. 

The error occurs with basically every use of the cache node:

```
{% cache "test" %}
    test
{% endcache %}
```

**Comment by fabpot** [comment]
Are you sure you're using the latest version (3.9.0) of the Cache extension? Because the code you pasted still uses `ob_start` which has been removed in 3.9.0 (see https://github.com/twigphp/Twig/commit/6ebbc305)

**Comment by mkrauser** [comment]
@fabpot Your suspicion was correct, because the app in which the issue occured still uses symfony 6.3, composer only installed 3.8.
```
twig/cache-extra v3.9.0 requires symfony/cache ^5.4|^6.4|^7.0
```

I upgraded everything to Symfony 6.4 and the cache-extension to 3.9, then the cache tags works as expected.

To prevent others from this issue, the cache-extension 3.8 should not be installable with twig 3.9. But that would require a 3.8.1 release. 

Anyway, thanks for pointing me in the right direction!
