### ISSUE TITLE
An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by andreybolonin** [twigphp/Twig#4084]
`An exception has been thrown during the rendering of a template ("Twig\Extension\CoreExtension::constant(): Return value must be of type string, App\Enum\TransactionFinType returned").`

```
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Twig\Extension\CoreExtension::constant(): Return value must be of type string, App\Enum\TransactionFinType returned").
```

`{{ constant('App\\Enum\\TransactionFinType::FIN_TYPE_RESULT').value }}`

After upgrade Twig from 3.9 to 3.10

**Comment by ninsuo** [comment]
This is due to #4063 which changed the `constant` method prototype:

```
public static function constant($constant, $object = null): string
```

Constants may also return most of the scalar types, arrays, native enums etc.

**Comment by fabpot** [comment]
See #4085

**Comment by ninsuo** [comment]
aha you are too fast buddy, I'll close https://github.com/twigphp/Twig/pull/4086 then :)

Have a good weekend!
