### ISSUE TITLE
twig/twig v3.10.1 release bug reports

### ISSUE THREAD

**Issue by TheCartpenter** [twigphp/Twig#4089]
If it can help the community, followed are the attached logs produced by PHPStan for twig/twig v3.10.1 release used with ```composer```.
[twig_v310_1_logs.txt](https://github.com/twigphp/Twig/files/15293050/twig_v310_1_logs.txt)

**Comment by fabpot** [comment]
I'm going to close as it does not really help.

**Comment by TheCartpenter** [comment]
That's on you to leave those error messages on but, since this was my first post on this repository, I'll clarify:

- Ran with ```composer```
- Successfully installs but ending up with the provided error messages from PHPStan
- Version: provided on the topic's title

**Comment by TheCartpenter** [comment]
User-defined errors:

 ------ ---------------------------------------
  Line   twig\twig\src\Template.php
 ------ ---------------------------------------
  :391   Variable $level might not be defined.
  :461   Variable $level might not be defined.
 ------ ---------------------------------------

**Comment by fabpot** [comment]
@TheCartpenter But in reality, it's always defined (just have a look at the code).
Tools like phpstan are great but they are not perfect, they have bugs and they have a limited ability to reason about complex code. It gets better but as PHP is very dynamic, it will never be perfect and it will never replace human developers.

**Comment by TheCartpenter** [comment]
Except that these error messages long existed before the appearance of PHPStan as it is still showing in your codes which is the reason why I am reporting the issue since PHPStan has been used to diagnose this issue but has nothing to do with PHPStan specifically.

The variable needs to be declared first when users are using PHP files under Windows / Virtual Servers as opposed to Linux / Unix where variables don't need to be declared.

**Comment by fabpot** [comment]
Again, there’s no issues as the variable is always defined. Always. No bug == no fix. I won’t change code just to please a tool. But feel free to prove I’m wrong with some code.

**Comment by fabpot** [comment]
Twig is used by many developers on windows and nobody ever complained.

**Comment by xabbuh** [comment]
> Except that these error messages long existed before the appearance of PHPStan as it is still showing in your codes which is the reason why I am reporting the issue since PHPStan has been used to diagnose this issue but has nothing to do with PHPStan specifically.

This is an issue with PhpStan specifically (or static analysis tools in general) as you cannot get the same error when actually executing the PHP code. `$level` is only read in the `finally` block when `$useYield` is `false`. But in in this case `$level` was initialised with the result `ob_get_level()` before. PhpStan in your case simply is not able to infer that the value of the `$useYield` property will never change after this before the `finally` block is executed.

> The variable needs to be declared first when users are using PHP files under Windows / Virtual Servers as opposed to Linux / Unix where variables don't need to be declared.

PHP does not behave differently on Windows compared to Linux in this regard when the runtime configuration is the same.

**Comment by TheCartpenter** [comment]
In twig/twig/src\Template.php file,

find:

```$blocks = array_merge($this->blocks, $blocks);```

add below:

```$level = '';```

Then, find:

```if (null !== $template) {```

Add below:

```$level = '';```

Error is gone.

**Comment by fabpot** [comment]
The thing reported by phpstan is gone, but it does not fix a real-world bug. And your code is not even correct as the level should be an integer. Anyway, you should maybe report this issue to phpstan to see if they can improve their algorithm in the future.

**Comment by TheCartpenter** [comment]
> The thing reported by phpstan is gone, but it does not fix a real-world bug. And your code is not even correct as the level should be an integer. Anyway, you should maybe report this issue to phpstan to see if they can improve their algorithm in the future.

It does. ```might not defined``` error message originates from PHPStan where the 'sentence' has been renamed from the original PHP error trigger message: ```undefined variable``` which existed long before than the publication of PHPStan. By checking the server error logs, you should see the difference straight ahead.

**Comment by xabbuh** [comment]
> By checking the server error logs, you should see the difference straight ahead.

If you don’t believe that this error cannot occur at runtime, please prove us wrong by providing a test or an example application.

**Comment by fabpot** [comment]
Let's stop the discussion here. There are no errors, nobody ever had "undefined variable" in their logs, at this point, this is just FUD. Closing the conversation.
