### ISSUE TITLE
Custom tag compiler no longer works

### ISSUE THREAD

**Issue by Chi-teck** [twigphp/Twig#4090]
I have [a compiler](https://github.com/Chi-teck/drupal-code-generator/blob/3.5.0/src/Twig/TwigSortSetNode.php#L18) for custom tag that is using output buffer. It worked well for years until Twig 3.9.0 was released.

Apparently there was some regression introduced in #3999.

**Comment by fabpot** [comment]
The problem in your code is that you're using the `ob_*` functions, which is an internal implementation detail.

**Comment by nicolas-grekas** [comment]
Unfortunately your implementation relies on output buffering, which is not used anymore internally.
You might want to consider using a CaptureNode instead since this one should be compatible with all versions of Twig.
I'm closing because there's nothing we can do here.

**Comment by ericmorand** [comment]
@nicolas-grekas so, if using `ob_*` was an internal implementation detail, what was the non internal way to achieve what the OP achieved?

**Comment by nicolas-grekas** [comment]
Using CaptureNode I suppose?

**Comment by ericmorand** [comment]
There is no CaptureNode in Twig 3.8. So, if `ob_*` were internal details, how were people supposed to write capture-like nodes before 3.9?

**Comment by nicolas-grekas** [comment]
Ah OK, so yes, ob_start was the way to go. Note that I'm just trying to help. Yes, we could consider some BC break here. Unfortunately, that's the kind if low-level stuff that's really hard to deal with. Twig needs to move forward and using yield makes it way better. Some extensions do need to adapt, that's true.

**Comment by chesn0k** [comment]
I used SetNode https://github.com/Chi-teck/drupal-code-generator/pull/150/commits/89a6b47193c2683fb4ced940daffba2c49d76b85#diff-659f570da976dbf4397a186b8703135e6aad1de658e365e4dd882d8bf06336d5R36

It not be the best solution, but maybe it will be useful for someone.

BTW I think we will abandon the tag in favor of a filter

**Comment by ericmorand** [comment]
@nicolas-grekas 

> Twig needs to move forward

That's why major version bump exists. There is no reason not to having pushed a new major version here.

**Comment by onlinesid** [comment]
@nicolas-grekas any handy documentation / link / example of this 'CaptureNode' thing?
