### ISSUE TITLE
loop.last with generator should throw an exception

### ISSUE THREAD

**Issue by Geolim4** [twigphp/Twig#4096]
Hello,

I painfully discovered that `loop.last` is indeed impossible to access when your looping over a generator (after a couple of hours of painful debug), but I was wondering if there's any possibility for Twig to instead throw an exception when people are accessing to `loop.last` which is currently "undefined" (obviously) to make the error clearer about WHY is `loop.last` undefined :)

**Comment by fabpot** [comment]
See #4131 for a potential fix.

**Comment by fabpot** [comment]
As of Twig 4.0, `loop.last` will always be available. See #4134
