### ISSUE TITLE
Inconsistency between EscaperExtension and EscaperRuntime

### ISSUE THREAD

**Issue by fgm** [twigphp/Twig#4102]
I got a problem in Drupal 10 code with the webprofiler collecting Twig configuration, and AIUI the problem might actually be present upstream here in Twig, using version 3.10.3 with PHP 8.3.7, and I could not find it in the issues already listed on this repo.

- `Twig\Extension\EscaperExtension::getFilters()` returns an array of `TwitFilter` for `escape`, `e` and `raw`
- These filters expect a not-type-hinted `callable` as the second parameter to their constructor, which is why the Webprofiler in Drupal type-hints them as `callable` 
- The problem lies in the definition of these "callables" for `escape` and `e` as: `[EscaperRuntime::class, 'escape']` 
  - that syntax defines a callable if `escape` is a `static` method
  - but `EscaperRuntime::escape` is actually an instance method, and that is not just a modifier oversight, as it uses `$this` internally
  - as a result `[EscaperRuntime::class, 'escape']` fails the `callable` type hint, confirmed by `is_callable([EscaperRuntime::class, 'escape'])` returning `false`.

The implementation is:

```php
    public function getFilters(): array
    {
        return [
            new TwigFilter('escape', [EscaperRuntime::class, 'escape'], ['is_safe_callback' => [self::class, 'escapeFilterIsSafe']]),
            new TwigFilter('e', [EscaperRuntime::class, 'escape'], ['is_safe_callback' => [self::class, 'escapeFilterIsSafe']]),
            new TwigFilter('raw', [self::class, 'raw'], ['is_safe' => ['all']]),
        ];
    }
```

an apparent fix would be to change it to return actual callables by creating an instance:

```php
    public function getFilters(): array
    {
        $escaper = new EscaperRuntime();
        return [
            new TwigFilter('escape', [$escaper, 'escape'], ['is_safe_callback' => [self::class, 'escapeFilterIsSafe']]),
            new TwigFilter('e', [$escaper, 'escape'], ['is_safe_callback' => [self::class, 'escapeFilterIsSafe']]),
            new TwigFilter('raw', [self::class, 'raw'], ['is_safe' => ['all']]),
        ];
    }
```

But maybe I overlooked something, or we need to use an existing runtime as mentioned in `deprecated.rst`: `[$env->getRuntime(EscaperRuntime::class), 'escape']`, but then we would have a problem since the extension does not carry an environment on which to call `getRuntime()` .

**Comment by xabbuh** [comment]
> These filters expect a not-type-hinted `callable` as the second parameter to their constructor, which is why the Webprofiler in Drupal type-hints them as `callable`

I think that's the culprit in the Drupal implementation if I understand the issue correctly. The `TwigFilter` class deliberately allows to pass an array where the key is a class name and the value a method that does not necessarily have to be a public method.

**Comment by fgm** [comment]
Interesting. Isn't it strange that that constructor parameter is still called `$callable` if it may something which is not a `callable` and the PHPdoc says the parameter is  _a callable implementing the filter_  

OTOH its PHPdoc type hint is `callable|array{class-string, string}|null`, not just `callable|null`. 

Also not that the method is public, but not static, preventing its call from just the class, which makes it a non-`callable`.

**Comment by mbabker** [comment]
> Interesting. Isn't it strange that that constructor parameter is still called `$callable` if it may something which is not a `callable` and the PHPdoc says the parameter is _a callable implementing the filter_
> 
> OTOH its PHPdoc type hint is `callable|array{class-string, string}|null`, not just `callable|null`.

Before the introduction of runtime loaders, those callable parameters effectively did have to match the PHP `callable` type.  When the runtime loaders were introduced to allow lazy loading the backing implementation of a function/filter/whatever, that's where the pseudo-callable array syntax became a thing.  So the result still has to be callable once the runtime is resolved, but for the purposes of declaring the filter, it doesn't have to immediately pass a `is_callable($callable)` check.  https://twig.symfony.com/doc/3.x/advanced.html#definition-vs-runtime explains it a bit more.

**Comment by fgm** [comment]
OK, so it's a feature, not a bug, then, I guess ? I suppose it can be closed at this point.

**Comment by mfrieling** [comment]
There is an issue in the webprofiler issue tracker about the exact same problem, but without the cause. As I just found it and subsequently this issue with the cause and explanation (thanks to @mbabker), I'm linking the webprofiler issue here for reference: https://gitlab.com/drupalspoons/webprofiler/-/issues/100
