### ISSUE TITLE
Performance regression since v3.9.0

### ISSUE THREAD

**Issue by vbrouet** [twigphp/Twig#4103]
What is the performance impact of the runtime check combined with yield ?

_Originally posted by @stof in https://github.com/twigphp/Twig/pull/3999#pullrequestreview-1875847101_
            

Hello,

While investigating a performance regression in a symfony app (6.4) I found that the source was twig/twig version 3.9.0.

I made a small repro and used git bissect to find this pull request #3999 where performance is briefly discussed.

After some trial and error, performance was partially restored by passing `'use_yield' => true` to the twig Environment constructor.

Not sure if this is a bug but in certain cases the performance impact was pretty huge (from 800 ms to 2200ms).

**Comment by j0r1s** [comment]
Probably related to [this discussion](https://github.com/twigphp/Twig/discussions/4101) I opened a few days ago

**Comment by fabpot** [comment]
Fixed by #4216
