### ISSUE TITLE
Ability to mark nodes as implicitly safe

### ISSUE THREAD

**Issue by m-vo** [twigphp/Twig#4119]
What is considered safe or not in the AST, is currently hardcoded in the `SafeAnalysisNodeVisitor`. For instance, a node that is an instance of `ConstantExpression`, is considered safe in all contexts. So when I'm creating my own expressions (that are safe by definition), I need to extend from `ConstantExpression` for the safe analysis to still work and the escaper node visitor not affecting the output. 

In https://github.com/twigphp/Twig/commit/c44bd1ff627d98dfd2ee1ed944af004b656d534e we're suddenly making assumptions about the class from outside. This will break child classes: In the above example a `PrintNode` wrapping a `FooConstantExpression` now gets converted to a `TextNode` ignoring the custom implementation.

How to deal with this? IMHO the ideal way would be to mark the `ConstantExpression` as `@final` and introduce an interface/flag for nodes, that marks them as safe in a certain or all contexts. Alternatively the optimizer should probably use `get_class` instead of `instanceof`.

**Comment by stof** [comment]
marking `ConstantExpression` as `@final` is probably a good idea in any case (there were already several cases doing special logic for ConstantExpression at compile time, either in Twig itself or in symfony/twig-bridge)

If you need to generate an extension that is analysed as safe, it would be a lot safer to generate it wrapped in a FilterExpression using the `raw` filter (which is purely about marking the expression as safe for the auto-escaping analysis and gets compiled to a no-op so has no overhead at all at runtime)

**Comment by fabpot** [comment]
In Twig 3.11, we introduced a new `RawFilter` that simplifies such use cases.

An example can be found in the 4.x branch (https://github.com/twigphp/Twig/commit/1a83f2c95b781b8b4c9a88aa1f48816355d16f94):

**Before**

```php
new FilterExpression($expr, new ConstantExpression('raw', $line), new Node(), $line);
```

**After**

```php
new RawFilter($expr);
```

**Comment by fabpot** [comment]
In #4178, I've added a recipe about this and marked `ConstantExpression` as `@final`.

**Comment by m-vo** [comment]
> In Twig 3.11, we introduced a new RawFilter that simplifies such use cases.

Thanks for the hint and the added recipe. :heart:
