### ISSUE TITLE
Site Repository ?

### ISSUE THREAD

**Issue by smnandre** [twigphp/Twig#4129]
Is there a website repository somewhere ? 

I'd like to suggest a set of small improvments regarding SEO (to better find what i look for when i search in Google), HTML (some tags) and layout (a lot of space available to breath on screens > 1200px).

(A good start would be what i did for the php-cs-fixer website)

If no repository i can prepare a list with detailled code but that would be easier to test locally :)

**Comment by fabpot** [comment]
Invite sent :)
