### ISSUE TITLE
Is the `_parent` value present in the context supposed to be iterated on by the `for` tag?

### ISSUE THREAD

**Issue by ericmorand** [twigphp/Twig#4152]
This is related to https://github.com/twigphp/Twig/issues/1584.

When iterating on the context, one of the iterated element is the parent context, identifier by the `_parent` key. TwigFiddle being down, here is a quick Twig sample:

```twig
{% for key, value in _context %}
  {{ key }}
{% endfor %}
```

The output of this template, with an empty context, is:

```
  _parent
```

Is it something that is contractual per TwigPHP specification? If not, why is it there, and why do developers have to know that it exists in order to not take it into account, like in the mentioned issue?

**Comment by fabpot** [comment]
The `_parent` item is purely internal stuff that only exists in the context of a loop and is not guaranteed to exist.
It might disappear in 4.0.

**Comment by fabpot** [comment]
See [#4153](https://github.com/twigphp/Twig/pull/4153/commits/e3c8d375663b003a2d1b6704cae39c5e7f07bbce)

**Comment by ericmorand** [comment]
Very good news. Thank you.
