### ISSUE TITLE
[Twig\Loader\ChainLoader] Constructor could accept iterable instead of array.

### ISSUE THREAD

**Issue by TheCelavi** [twigphp/Twig#4200]
Proposal - Instead of current constructor:

```php
    /**
     * @param LoaderInterface[] $loaders
     */
    public function __construct(array $loaders = [])
    {
        foreach ($loaders as $loader) {
            $this->addLoader($loader);
        }
    }
```

replace it with:

```php
    /**
     * @param iterable<LoaderInterface> $loaders
     */
    public function __construct(iterable $loaders = [])
    {
        foreach ($loaders as $loader) {
            $this->addLoader($loader);
        }
    }
```

No BC break, allows to use `tagged_iterator` in SF autowiring for creating our own Twig environment (beside templating delivered with SF app by default).

WDYT?

**Comment by stof** [comment]
even better would be to support an iterable in the constructor without iterating it there, to benefit from the lazy-loading feature of the IteratorArgument in Symfony (when using `tagged_iterator`)

**Comment by fabpot** [comment]
Looks like good ideas. @TheCelavi Do you want to work on a PR?

**Comment by TheCelavi** [comment]
Why not - it has been a long time... 😃 

Thx guys, sending PR soon.
