### ISSUE TITLE
Port Number Not Included in `absolute_url()` and `url()` Functions

### ISSUE THREAD

**Issue by ucscode** [twigphp/Twig#4208]
When using Symfony's Twig functions `absolute_url()` or `url()`, the generated URL does not include the port number if the application is accessed through a domain with a specific port number. This results in URLs being generated without the necessary port, which can cause issues when working with non-standard ports.

**Example:**

- **URL Accessed:** `localhost:7000`
- **Twig Code:**
  ```twig
  {{ absolute_url(path('name')) }}
  ```
- **Actual Result:**
  ```
  http://localhost/path/to/route
  ```
- **Expected Result:**
  ```
  http://localhost:7000/path/to/route
  ```

**Steps to Reproduce:**

1. Access a Symfony project through a URL with a port number (e.g., `localhost:7000`).
2. Use the `absolute_url()` or `url()` function in a Twig template to generate a URL.
3. Observe that the port number is omitted from the generated URL (specifically on `TemplatedEmail`)

**Expected Behavior:**

The `absolute_url()` and `url()` functions should include the port number in the generated URLs when the application is accessed via a domain with a specific port beyond `80` and `443`

**Additional Information:**

- Symfony version: 7.1
- Twig version: 3.0
- Web server: Apache 2.4

**Possible Solution:**

Ensure that the URL generation functions respect the port number configured in the request. This might involve updating the URL generator service to include the port number when generating absolute URLs.

**Additional Notes:**

If there are any workarounds or configurations to address this issue, please share them. Otherwise, a fix in the codebase would be appreciated.

**Comment by fabpot** [comment]
Can you report the issue on the Symfony repository as all functions you mentioned are part of Symfony, not Twig. Thank you.

**Comment by ucscode** [comment]
> Can you report the issue on the Symfony repository as all functions you mentioned are part of Symfony, not Twig. Thank you.

Issue reported to:

https://github.com/symfony/symfony/issues/58023
