### ISSUE TITLE
Twig Documentation format_currency error

### ISSUE THREAD

**Issue by OrsonFun** [twigphp/Twig#4220]
Please investigate the Symfony Documentation because this didnt work for me i had to change the ":" to "=" could be frustrating for searching the error.

From:
{{ '1000000'|format_currency('EUR', locale: 'de') }}

To:
{{ '1000000'|format_currency('EUR', locale= 'de') }}

**Comment by xabbuh** [comment]
this is related to #4209, starting with Twig 3.12 it will be possible to use colons for named arguments

**Comment by fabpot** [comment]
Sorry for that, I forgot that the docs are published right away, so here, before the release of the feature.
