### ISSUE TITLE
Force Twig to render a specific cache file

### ISSUE THREAD

**Issue by nickpapoutsis** [twigphp/Twig#4278]
If I ask Twig to render `example.twig` it will generate a cache file named something like `8e8456gffc99c672976eff.php` (if cache is enabled).

Is there a way to then take `8e8456gffc99c672976eff.php`, and make Twig run it directly without even having access to the original `example.twig` file?

I want something like `$this->twig->renderCache('8e8456gffc99c672976eff.php', $data);` but haven't found a straightforward way to do it (I can hardcode it but would prefer a generalized solution).

**Comment by stof** [comment]
there is no such API. The internal format of the cache is purely internal.

**Comment by nickpapoutsis** [comment]
> there is no such API. The internal format of the cache is purely internal.

That's unfortunate :(

Current solution (for 1.x at least) is to init Twig, `include_once` the php cache file (have modified its class name to that of the template), call render and in `Twig_Environment::loadTemplate`  do `if (class_exists('__TwigTemplate_' . str_replace('.twig', '', $name))) { $cls = '__TwigTemplate_' . str_replace('.twig', '', $name); }` to trick it into loading the cache instead of the `.twig` file.

**Comment by stof** [comment]
@nickpapoutsis this trick is a total hack and could stop working in any release of Twig (even patch versions) as the internal implementation of the cache is not covered by backward compatibility at all (as a matter of fact, it has *already* changed in the history of Twig).

What is your use case ?

**Comment by nickpapoutsis** [comment]
> What is your use case ?

I don't want to distribute the original twig file but don't care enough about the php cache file (although I could encrypt/obfuscate it if needed).

Due to the nature of the project I am forced to use 1.x for compatibility with PHP 5.6 so newer Twig versions aren't in the picture at all.

**Comment by stof** [comment]
Rendering Twig without shipping the Twig files is not a supported usage of Twig.

Note that with a custom loader, you could actually encrypt the twig files. And it would even work if your template relies on other Twig templates through `{% extends %}`, `{% use %}`, `{% include %}` or `{ embed %}`

**Comment by nickpapoutsis** [comment]
> Note that with a custom loader, you could actually encrypt the twig files.

If I am not mistaken, I cannot freely share the templates/loader (let's say upload them on GH) while also making it impossible for a third party to decrypt them back to the original twig.

**Comment by fabpot** [comment]
Closing as this is not a use case we are to going to support in core.
