### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by ruudk** [twigphp/Twig#4282]
Currently I have to use the unreleased version of Twig in [TwigStan](https://github.com/twigstan/twigstan) because I want to use the new types tag and the compiler optimizations. 

@fabpot I know you’re probably busy, but do you have any idea when a new release can be done?

Thanks 🙏🏻 

https://github.com/twigphp/Twig/compare/v3.12.0...3.x

**Comment by fabpot** [comment]
Released

**Comment by ruudk** [comment]
Thank you 🥳
