### ISSUE TITLE
[HTML Extra] html_cva - Unknown argument "default_variants"

### ISSUE THREAD

**Issue by setineos** [twigphp/Twig#4373]
With the following code I have the error below:
`Unknown argument "default_variants" for function "html_cva(base, variants, compound_variants, default_variant)".`

```twig
{% set color = 'red' %}
{% set size = 'lg' %}

{% set alert = html_cva(
    base='alert ',
    variants={
        color: {
            blue: 'bg-blue',
            red: 'bg-red',
            green: 'bg-green',
        },
        size: {
            sm: 'text-sm',
            md: 'text-md',
            lg: 'text-lg',
        },
        rounded: {
            sm: 'rounded-sm',
            md: 'rounded-md',
            lg: 'rounded-lg',
        }
    },
    defaultVariants={
        rounded: 'md',
    }
) %}

<div class="{{ alert.apply({color, size}) }}">
    ...
</div>
```

**Comment by jdreesen** [comment]
Because the parameter is named `$defaultVariant` (without the `s`).

**Comment by stof** [comment]
As said in the error message, the argument is name `default_variant`

**Comment by setineos** [comment]
On https://cva.style/docs/getting-started/variants and https://ui.shadcn.com/docs/components/button , `defaultVariants` with an "s" is used though :).

**Comment by stof** [comment]
Those are not docs about Twig. This is the doc about a JS library (and I don't know why they decided to use a plural name for a setting containing a single variant)
