### ISSUE TITLE
Inconsistent deprecation on escaping interpolation mark #

### ISSUE THREAD

**Issue by cfieux** [twigphp/Twig#4375]
Since Twig 3.12, a deprecation notice is raised when trying to escape the interpolation mark `#` :
`Since twig/twig 3.12: Character "#" at position 18 should not be escaped; the "\" character is ignored in Twig v3 but will not be in v4. Please remove the extra "\" character.`

However according to the documentation, it's how it is meant to be : https://twig.symfony.com/doc/3.x/templates.html#string-interpolation

Version used : *3.14*

**Comment by stof** [comment]
What is your actual content ?

**Comment by cfieux** [comment]
```twig
{% set id = 42 %}
{{ "Your real ID is \##{id}" }}
```

**Comment by stof** [comment]
the first `#` does not need escaping. Escaping is needed only for a `#` followed by `{` (i.e. what would start a string interpolation if not escaped)
