### ISSUE TITLE
add component to guard tag

### ISSUE THREAD

**Issue by tacman** [twigphp/Twig#4390]
I love the guard tag, and was wondering if it could be applied to twig components, too, so that something like this would work:

```twig
{% guard component 'bootstrap:accordion' %}
<twig:bootstrap:accordion />
{% else %}
{# dump data as paragraphs #}
{% endif %}
```

I put the issue in the ux repo, but perhaps it belongs here.

https://github.com/symfony/ux/issues/2255

**Comment by stof** [comment]
given that Twig itself knows nothing about twig components (which are a concept of symfony/ux, not of Twig), I don't think it can be added in the core tag.

However, from a quick look at the implementation of TwigComponent in symfony/ux, I don't have the impression that they validate component names are compile time. If this is indeed a runtime check, a `{% if component_exists('bootstrap:accordion') %}` would work (assuming they define such a `component_exists` function), or an alternative `{% if 'bootstrap:accordion' is component %}` if they prefer exposing a test. anyway, such choice would belong to the symfony/ux repo.

**Comment by tacman** [comment]
Yeah, that's why I opened it there.  But the original PR mentioned something like "currently the guard tags supports filters and  functions", it made me think perhaps where was a way a 3rd-party component could "attach" itself to it.  

But a component_exists() function seems like an easier solution anyway.

**Comment by stof** [comment]
there is not hook for third-party extensions in it (which would not be possible anyway, as the implementation relies on checking for that filter/function/test on the Environment instance).

**Comment by tacman** [comment]
thanks for the explanation!

**Comment by smnandre** [comment]
A `guard` can be used at a higher level to check whether `symfony/ux-twig-component` is installed or not.

```twig

{% guard function component %}
    <twig:bootstrap:accordion />
{% endguard %}

```

**Comment by tacman** [comment]
@smnandre yes, but it'd also be nice to check if a specific component was installed.

```twig
{% set count = 15 %}
{% guard function component %}
    {% if (component_exists('bootstrap:badge') %}
        <twig:bootstrap:badge :message="count"  />
   {% else %}
        {# badge is in my bundle if ux-component is installed, so I don't need to check for it #}
        <twig:my-bundle:badge :message="count"  />
   {% endif %}
{% else %}
       <span class="badge">{{ count }}</span>
{% endguard %}
```

**Comment by smnandre** [comment]
I know I Even answered you about this on the UX repository :)
