### ISSUE TITLE
[Parser][Lexer]  Incorrect(?) exception message for invalid block names

### ISSUE THREAD

**Issue by smnandre** [twigphp/Twig#4433]
Using invalid block names triggers incorrect (?) error messages. Not sure if due to recent changes or if it was always the case.

Two exemples using a dash -> two different error messages 

## `{% block x-foo %}`

Note: i just wrote them, so the expects may be wrong.. but see how the results seem a bit illogical.

### Test 1: `Unknown endblock tag`

```
--TEST--
Invalid block block name
--TEMPLATE--
{% block x-foo %}a{% endblock %}
--DATA--
return []
--EXPECT--
Twig\Error\SyntaxError: Invalid block name "x-foo" in "index.twig" at line 2.
```

```diff
--ACTUAL--
- Twig\Error\SyntaxError: Unknown "endblock" tag in "index.twig" at line 2.
```

### Test 2: `block 'x' has already been defined`

```
--TEST--
Invalid block block name
--TEMPLATE--
{% block x-bar %}
    {% block x-foobar %}FooBar{% endblock %}
{% endblock %}
--DATA--
return []
--EXPECT--
Twig\Error\SyntaxError: Invalid block name "x-bar" in "index.twig" at line 2.
```

```diff
--ACTUAL--
- Twig\Error\SyntaxError: The block 'x' has already been defined line 2 in "index.twig" at line 3.
```

**Comment by fabpot** [comment]
That's because `-` is not supported in a name. So, `{% block x-foo %}a{% endblock %}` is interpreted as `{% block x -foo %}a{% endblock %}` where `-foo` is the content of the block. So, the `endblock` is unexpected as the block is already "closed".

**Comment by smnandre** [comment]
> That's because - is not supported in a name. So, {% block x-foo %}a{% endblock %} is interpreted as {% block x -foo %}a{% endblock %} where -foo is the content of the block. So, the endblock is unexpected as the block is already "closed".

This is precisely what i was testing. But i did not think about the short block declaration.. so this felt a bit surprising :)

```twig
{% set bar = 123 %} 

{% block foo-bar %}
-123
```

So indeed, no incorrect message here :) 

I can imagine situations** where this could lead to unexpected results

```twig
{% set card = '4242424242424242' %}

{# ... #}

{% block step-card-1 %}

{# --> would display -4242424242424241 #}
```

** did not say "realistic situations"

--- 

Note: TwigCsFixer does find this odd and forces you back on a more readable syntax (thx @VincentLanglet)

```
 ------- ---------------------------------------------------- 
  ERROR   46   |                                              
          47   | {% block step-card-1 %}                      
          >>   | Expecting 1 whitespace after "-"; found 0.   
          48   | -123                                         
 ------- ---------------------------------------------------- 
  ERROR   46   |                                              
          47   | {% block step-card-1 %}                      
          >>   | Expecting 1 whitespace before "-"; found 0.  
          48   | -123                                         
 ------- ---------------------------------------------------- 
```

So I guess no real-life problem here: let's close :)
