### ISSUE TITLE
Regression: GHSA-6377-hfv9-hqf6 fix can exceed recursion limits / OOM

### ISSUE THREAD

**Issue by mradcliffe** [twigphp/Twig#4439]
Several of us who updated twig/twig:3.14.1 on our Drupal web sites have seen that this new recursive logic causes OOM or stack limits. This seems related to [https://github.com/twigphp/Twig/security/advisories/GHSA-6377-hfv9-hqf6](GHSA-6377-hfv9-hqf6).

With xdebug enable, this is displayed as

    Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '1000' frames in Twig\Extension\SandboxExtension->isSandboxed() (line 56 of /var/www/html/vendor/twig/twig/src/Extension/SandboxExtension.php).
    
    Twig\Extension\SandboxExtension->ensureToStringAllowed() (Line: 124)
    Twig\Extension\SandboxExtension->ensureToStringAllowed() (Line: 93)

Drupal form render arrays are often very nested and very deep. I do not quite understand the twig sandbox code so I do not know if this is fixable downstream, but it seems like we would only need to recurse if the value is an object rather than on every array/list value.

Any help would be appreciated.

**Steps to reproduce**

1. Install Drupal 10.3 or >11.0.1 (helpful to use Standard profile) 
2. Update to twig/twig:3.14.1
3. Log in as an administrative user.
4. Attempt to create a node.

[drupal.org issue](https://www.drupal.org/project/drupal/issues/3485956)

**Comment by jfrumkin-ucla** [comment]
This is indeed happening on any local installs I attempt today, and my cypress tests on github also break due to this.

**Comment by StirStudios** [comment]
Same here. As a quick fix downgrading back to v3.14.0 resolves the issue.

**Comment by kentr** [comment]
Also happening for me.

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate
262144 bytes) in .../vendor/twig/twig/src/Extension/SandboxExtension.php on line 130
```

**Comment by ionmacariatremend** [comment]
I can confirm that it's happening now on Drupal core 10.2.10
![image](https://github.com/user-attachments/assets/20fd15ea-69ac-44cc-814f-f7c84c6ae82d)

**Comment by mably** [comment]
Same problem on Drupal 11.0.5, we get a WSOD when we try to render some Views with BEF.

**Comment by nicolas-grekas** [comment]
Fixed by #4441, to be released soon.

**Comment by fabpot** [comment]
I've just released new versions.

**Comment by StirStudios** [comment]
Thanks so much and confirmed all is good again!
