### ISSUE TITLE
Concern Regarding the Use of "goto" in Recent Commit

### ISSUE THREAD

**Issue by PSF1** [twigphp/Twig#4448]
I hope this message finds you well. I am reaching out to address a concern that has come up within our development team regarding a recent addition to the Twig codebase. We noticed that the "goto" statement, a PHP control structure, has been introduced in commit [b957e5a](https://github.com/twigphp/Twig/commit/b957e5a44cc0075d04ccff52f8fa9d8e6db3e3a0).

While we recognize that "goto" can be useful in certain contexts, there are longstanding discussions about its potential impact on code maintainability and readability. The [PHP documentation](https://www.php.net/manual/en/control-structures.goto.php) itself mentions that its usage can often lead to code that is more difficult to understand and can be prone to errors if not handled very carefully.

Given Twig's wide usage and importance in the PHP community, we are concerned that incorporating "goto" into the code might introduce unintended side effects and might lead to a decrease in stability. We would like to kindly request a reconsideration of its usage in the codebase for the benefit of maintaining Twig's high standards of quality and reliability.

We appreciate the hard work that goes into maintaining such a valuable project, and please understand that our intention is purely to ensure the continued integrity of the code.

Thank you for considering our perspective. We look forward to your thoughts on this matter.

Best regards

P.S. Alternatively, if the usage of "goto" is essential for the implementation, perhaps we could discuss documenting the rationale behind this decision to clarify its necessity for future contributors.

Usage detected by gorkagr of Drupal Community.

**Comment by PSF1** [comment]
![imagen](https://github.com/user-attachments/assets/c8d39080-47e6-48e1-9606-eb6c06ba779d)

**Comment by gorkaguerrero** [comment]
`goto` found in lines [L1651](https://github.com/twigphp/Twig/blob/b957e5a44cc0075d04ccff52f8fa9d8e6db3e3a0/src/Extension/CoreExtension.php#L1651) and [L1730](https://github.com/twigphp/Twig/blob/b957e5a44cc0075d04ccff52f8fa9d8e6db3e3a0/src/Extension/CoreExtension.php#L1730), jumping to [L1759](https://github.com/twigphp/Twig/blob/b957e5a44cc0075d04ccff52f8fa9d8e6db3e3a0/src/Extension/CoreExtension.php#L1759)

**Comment by stof** [comment]
Extracting the method check logic into a private method called in both place would add an extra method call for each attribute access that ends up checking methods (which is most on them in projects using getters, which are quite common today).
this method is the hottest path of Twig, so making it slower to avoid a `goto` usage is a no-go for us.

This code also have extensive coverage in tests, so I'm not concerned about the maintainability impact of that single `goto`

**Comment by gorkaguerrero** [comment]
hi @stof,
thanks for the prompt reply. 
Do you have any benchmark or performance comparison between goto / no-goto or how changing to a no-goto code degradates the render of a page?

Personally, i have tested in a Drupal instance with both 3.14.2 (goto & changing code to no-goto), and i have not noticed any degradation or performance issue, but i am not expert in profiling/benchmarking this type of changes in the code.

**Comment by stof** [comment]
@gorkaguerrero how did you change the code ?

**Comment by gorkaguerrero** [comment]
direct change in the file in a local installation

**Comment by stof** [comment]
@gorkaguerrero *which change* ?

**Comment by gorkaguerrero** [comment]
```
private static function methodCheck($object, $item, $isDefinedTest, $propertyNotAllowedError, $ignoreStrictCheck, $env, $sandboxed, $lineno, $source, $arguments) {
      static $cache = [];

      $class = \get_class($object);

      // object method
      // precedence: getXxx() > isXxx() > hasXxx()
      if (!isset($cache[$class])) {
          $methods = get_class_methods($object);
          sort($methods);
          $lcMethods = array_map(function ($value) { return strtr($value, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'); }, $methods);
          $classCache = [];
          foreach ($methods as $i => $method) {
              $classCache[$method] = $method;
              $classCache[$lcName = $lcMethods[$i]] = $method;

              if ('g' === $lcName[0] && str_starts_with($lcName, 'get')) {
                  $name = substr($method, 3);
                  $lcName = substr($lcName, 3);
              } elseif ('i' === $lcName[0] && str_starts_with($lcName, 'is')) {
                  $name = substr($method, 2);
                  $lcName = substr($lcName, 2);
              } elseif ('h' === $lcName[0] && str_starts_with($lcName, 'has')) {
                  $name = substr($method, 3);
                  $lcName = substr($lcName, 3);
                  if (\in_array('is'.$lcName, $lcMethods)) {
                      continue;
                  }
              } else {
                  continue;
              }

              // skip get() and is() methods (in which case, $name is empty)
              if ($name) {
                  if (!isset($classCache[$name])) {
                      $classCache[$name] = $method;
                  }

                  if (!isset($classCache[$lcName])) {
                      $classCache[$lcName] = $method;
                  }
              }
          }
          $cache[$class] = $classCache;
      }

      $call = false;
      if (isset($cache[$class][$item])) {
          $method = $cache[$class][$item];
      } elseif (isset($cache[$class][$lcItem = strtr($item, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')])) {
          $method = $cache[$class][$lcItem];
      } elseif (isset($cache[$class]['__call'])) {
          $method = $item;
          $call = true;
      } else {
          if ($isDefinedTest) {
              return false;
          }

          if ($propertyNotAllowedError) {
              throw $propertyNotAllowedError;
          }

          if ($ignoreStrictCheck || !$env->isStrictVariables()) {
              return;
          }

          throw new RuntimeError(\sprintf('Neither the property "%1$s" nor one of the methods "%1$s()", "get%1$s()"/"is%1$s()"/"has%1$s()" or "__call()" exist and have public access in class "%2$s".', $item, $class), $lineno, $source);
      }

      if ($sandboxed) {
          try {
              $env->getExtension(SandboxExtension::class)->checkMethodAllowed($object, $method, $lineno, $source);
          } catch (SecurityNotAllowedMethodError $e) {
              if ($isDefinedTest) {
                  return false;
              }

              if ($propertyNotAllowedError) {
                  throw $propertyNotAllowedError;
              }

              throw $e;
          }
      }

      if ($isDefinedTest) {
          return true;
      }

      // Some objects throw exceptions when they have __call, and the method we try
      // to call is not supported. If ignoreStrictCheck is true, we should return null.
      try {
          $ret = $object->$method(...$arguments);
      } catch (\BadMethodCallException $e) {
          if ($call && ($ignoreStrictCheck || !$env->isStrictVariables())) {
              return;
          }
          throw $e;
      }

      return $ret;
    }
```


    then replace each goto and the code after the label with

`return self::methodCheck($object, $item, $isDefinedTest, $propertyNotAllowedError, $ignoreStrictCheck, $env, $sandboxed, $lineno, $source, $arguments);`

**Comment by nicolas-grekas** [comment]
I'm sorry but this discussion looks like a waste of time. We're perfectly able to evaluate when using goto makes sense.
Also the goto in the xkcd is mocking the language structure from the C language. In PHP (and others), goto cannot jump to arbitrary code. This all looks like self-FUD sorry :)
