### ISSUE TITLE
Remove internal annotation for TokenStream::getSourceContext

### ISSUE THREAD

**Issue by iquito** [twigphp/Twig#4457]
In a Twig extension of mine I have code similar to this, where I call `TokenStream::getSourceContext` to initialize a SyntaxError:

```php
use Twig\Error\SyntaxError;
use Twig\Node\Node;
use Twig\TokenParser\AbstractTokenParser;

class SomeTokenParser extends AbstractTokenParser
{
    public function parse(Token $token): Node
    {
        $stream = $this->parser->getStream();

        // some code where $value is extracted from token stream
        
        if ($value > 5) {
            throw new SyntaxError(
                'some tag is being used with an unsupported value above 5.',
                $stream->getCurrent()->getLine(),
                $stream->getSourceContext(),
            );
        }
    }
}
```

Everything in that example is part of the Twig API, except for the call to `$stream->getSourceContext()`. One could remove that line, but would lose the context of the error (the uncompiled code and the source path) which can be quite helpful for somebody who encounters a syntax error.

`getSourceContext` is the only method in `TokenStream` that is marked as internal - the returned `Source` object is not internal. I am therefore wondering if it would not make sense to remove the internal flag for `getSourceContext` as an easy way to officially provide the source context when processing the token stream.

**Comment by fabpot** [comment]
I don't remember why, so #4471

**Comment by iquito** [comment]
Thanks!
