### ISSUE TITLE
Confusing test names in docs

### ISSUE THREAD

**Issue by willrowe** [twigphp/Twig#4462]
Is there any way to include spaces in the links for `Tests` in the docs? Every time I go to look up `same as` or `divisible by` it is confusing because the links do not include spaces, but when you go to the page they include a space. Anybody using the list as a quick reference will end up with an error trying to use `sameas` and `divisibleby`.

![Screenshot 2024-11-20 at 09 48 17](https://github.com/user-attachments/assets/00c6ccf7-f253-4273-b41f-ee3c4f2b458b)
![Screenshot 2024-11-20 at 09 51 22](https://github.com/user-attachments/assets/f49c7ffb-65b7-40ad-b276-f5c1ea007ded)
![Screenshot 2024-11-20 at 09 51 31](https://github.com/user-attachments/assets/cffbcf90-1173-4362-bd59-eeca9e39175e)

**Comment by fabpot** [comment]
Fixed.
