### ISSUE TITLE
Allow a way of parsing things that look like functions

### ISSUE THREAD

**Issue by m-vo** [twigphp/Twig#4463]
The changes from #4398 unfortunately breaks our code (Contao CMS).

```
Twig\Error\SyntaxError : An exception has been thrown during the compilation of a template ("Attribute "name" does not exist for Node "Twig\Node\Expression\ConstantExpression".") in "template.html.twig".
````

### How we use addImportedSymbol()

We support a "slot" tag, that looks like this:
```twig
{% slot foo %}
    <section id="foo">{{ slot() }}</section> 
{% endslot %}
```
In this example, if content for the "foo" slot is available, the section gets output and the content inserted where the `slot()` function was put. The function is not a real function (compare it to `parent()` in block context). 

We implemented this like so in our token parser:
```php
$markerExpression = new ConstantExpression('', 0);
$this->parser->addImportedSymbol('function', 'slot', '', $markerExpression);

// then traverse the node's body and replace the marker expression with a PrintNode outputting the content
```

### How to resolve this?

Maybe our usage is not how things are intended - but how would we achieve the same results then?

**Comment by stof** [comment]
you should use an actual `slot` function with a custom node class (and maybe a custom parser callable if needed).

Hacking `addImportedSymbol` to import constant expressions is clearly not an intended usage of `addImportedSymbol`

**Comment by m-vo** [comment]
Of course I could use a real function (as a matter of fact I'm doing this now as a workaround), but semantically it is not the same. The function now exists "globally" and I must prevent anyone calling it while before it was scoped to the node and just did not exist outside. 

It would be nice if there was a supported way of doing this *without* creating a real function.

**Comment by stof** [comment]
Well, either with a custom parser_callable in the function definition or with a node visitor (I don't know which one would be easier to implement in your case), you could still trigger a Syntax error when using `slot` outside the expected node.

Btw, `parent` is a normal function in Twig now: https://github.com/twigphp/Twig/blob/2d5b3964cc21d0188633d7ddce732dc8e874db02/src/Extension/CoreExtension.php#L274

**Comment by fabpot** [comment]
Closing as I suppose you have everything you need to do it the "proper way" now.
