### ISSUE TITLE
In version 3.15.0, when accessing SplObjectStorage by index (object), an error is generated

### ISSUE THREAD

**Issue by maninhat** [twigphp/Twig#4476]
```
{% for q in sections[s] %}
```
where section is SplObjectStorage 
and s is a object
Raise error  An exception has been thrown during the rendering of a template ("Object of class App\Attempt\Section could not be converted to string").

**Comment by fabpot** [comment]
The error seems legit if your `Section` does not implement `Stringable`/__toString().
If it used to work before, please can you provide a small reproducer (as I cannot reproduce something that worked before 3.15.0 and broken after)?

**Comment by gharlan** [comment]
The reason is this change: https://github.com/twigphp/Twig/pull/4425#discussion_r1869120001
