### ISSUE TITLE
Link to Twigfiddle alternative on https://twig.symfony.com/development

### ISSUE THREAD

**Issue by kudosscience** [twigphp/Twig#4478]
[Twigfiddle](https://twigfiddle.com/) is [down for the foreseeable future](https://github.com/ninsuo/twigfiddle/issues/89)

We currently link to it under the "Support" heading on [https://twig.symfony.com/development](https://twig.symfony.com/development)

Could we link to the Twigfiddle alternative mentioned in a reply to [Twigfiddle Issue #89](https://github.com/ninsuo/twigfiddle/issues/89#issuecomment-2485196441) for the time being?

**Comment by fabpot** [comment]
As this is based on a JS port, I prefer not to (behavior won't be the same).
I will see how I can help restore this service.

**Comment by xabbuh** [comment]
@kudosscience FYI: https://symfony.com/blog/introducing-the-new-twig-playground
