### ISSUE TITLE
Null-coalescing does not work when method returns null

### ISSUE THREAD

**Issue by norkunas** [twigphp/Twig#4499]
```twig
{{ something.nice(category) ?? 'nope' }}
```
should return `nope` but the result is empty

tried to add a test to `tests/IntegrationTest.php` but not sure how to inject an object for `tests/Fixtures/tests/null_coalesce.test`

this broke my code after latest release: i had a function where it accepts only string type but then the null coalesce stopped working and null was passed instead of the fallback string

**Comment by fabpot** [comment]
Can you share a small reproducer? Or at least, tell me if `category` exists, and the `nice()` call return value.

**Comment by fabpot** [comment]
> Can you share a small reproducer? Or at least, tell me if `category` exists, and the `nice()` call return value.

I think I know: the method and argument does exist, and the method returns an empty string or `null`. It should then return `nope` but it returns an empty string instead.

**Comment by azlotnikov** [comment]
It can be reproduced when object getter is used. Here is example:

```php
require_once 'vendor/autoload.php';

class SomeClass {
    private ?string $var = null;

    public function getVar(): ?string {
        return $this->var;
    }
}

$loader = new \Twig\Loader\FilesystemLoader('templates');
$twig = new \Twig\Environment($loader);

$a = new SomeClass();

echo $twig->render('test.twig', [
    'a' => $a,
]);
```

```twig
{{ a.var ?? 123 }}
```

Twig 3.17 Output:
```

```

Twig 3.16 Output:
```
123
```

**Comment by fabpot** [comment]
New release published.
