### ISSUE TITLE
Twig 3.15 introduces potential bc break for extensions with operators

### ISSUE THREAD

**Issue by marc1706** [twigphp/Twig#4503]
The issue is caused by this PR: https://github.com/twigphp/Twig/pull/4367

Unfortunately I'm currently on the road and don't have much time to debug deeper into the issue, but it essentially comes down to the fact that classes extending `\Twig\Extension\AbstractExtension` and also implementing operators via `getOperators()` will have to be updated to `precedence_change`.

We end up running into this issue with one of our extensions in phpBB after updating twig to the latest version:
```
Twig\Error\SyntaxError: An exception has been thrown during the compilation of a template ("Undefined array key "precedence_change"") in "define.html".
```
(see this build: https://github.com/phpbb/phpbb/actions/runs/12332949057/job/34421397543?pr=6761)

As of right now this ends up being a backwards incompatible change and not just a deprecation.

### Sample code
I've created some sample code for reproducing this issue (test project called `twig_test`).

Base file we'll access is `twig_test/test.php`:
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Twig\Environment;
use Twig\Loader\FilesystemLoader;
use MyVendor\CustomExtension;

// Set up Twig loader and environment
$loader = new FilesystemLoader(__DIR__ . '/templates');
$twig = new Environment($loader);
$twig->addExtension(new CustomExtension());

// Render a template with the extension
echo $twig->render('example.twig', [
	'foo'	=> true,
]);

```

`twig_test/composer.json`:
```json
{
  "require": {
    "twig/twig": "3.15.*"
  },
  "autoload": {
    "psr-4": {
      "MyVendor\\": "src/"
    }
  }
}

```

`twig_test/src/CustomExtension.php`:
```php
<?php

namespace MyVendor;

use Twig\Extension\AbstractExtension;

class CustomExtension extends AbstractExtension
{
	public function getOperators()
	{
		return [
			[
				'!' => ['precedence' => 50, 'class' => '\Twig\Node\Expression\Unary\NotUnary'],
			],
			[]
		];
	}
}

```

Template file `twig_test/templates/example.twig`:
```twig
{% if !foo %}
    not foo
{% else %}
    foo
{% endif %}

```

Expected output when accessing `test.php` (works until 3.14):
`foo`

Actual output with 3.15:
```
Warning: Undefined array key "precedence_change" in /var/www/html/twig_test/vendor/twig/twig/src/ExpressionParser.php on line 152
foo
```

**Comment by stof** [comment]
Please provide the full stack trace, including the previous exception (which has a more useful location to debug this issue).
The `precedence_change` is meant to be optional in the config of operators (and most core operators don't provide one).

**Comment by rxu** [comment]
It can be found following the build link given above, but here it is:
```
Caused by
PHPUnit\Framework\Error\Warning: Undefined array key "precedence_change"

/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/ExpressionParser.php:152
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/ExpressionParser.php:249
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/ExpressionParser.php:103
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/TokenParser/IfTokenParser.php:39
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/Parser.php:202
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/Parser.php:95
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/Environment.php:539
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/Environment.php:567
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/Environment.php:395
/home/runner/work/phpbb/phpbb/phpBB/phpbb/template/twig/environment.php:284
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/Environment.php:357
/home/runner/work/phpbb/phpbb/phpBB/vendor/twig/twig/src/Environment.php:320
/home/runner/work/phpbb/phpbb/phpBB/phpbb/template/twig/environment.php:230
/home/runner/work/phpbb/phpbb/phpBB/phpbb/template/twig/environment.php:200
/home/runner/work/phpbb/phpbb/phpBB/phpbb/template/twig/twig.php:293
/home/runner/work/phpbb/phpbb/tests/template/template_test_case.php:43
/home/runner/work/phpbb/phpbb/tests/template/template_test_case.php:162
/home/runner/work/phpbb/phpbb/tests/template/template_test.php:556
```

At the top of the trace, it seems to be this line https://github.com/twigphp/Twig/blob/918f52e818f7c56e90ec462ae90b230da244a7ed/src/ExpressionParser.php#L152

**Comment by stof** [comment]
do you have a Twig template triggering the issue (ideally a minimal one) ?

**Comment by rxu** [comment]
It's as simple as this:

```twig
{% if !variable_does_not_exist %}
{{ 'Get Undefined array key "precedence_change" PHP Warning' }}
{% endif %}
```

**Comment by fabpot** [comment]
> It's as simple as this:
> 
> ```
> {% if !variable_does_not_exist %}
> {{ 'Get Undefined array key "precedence_change" PHP Warning' }}
> {% endif %}
> ```

As `!` is not supported by Twig, I suppose it's defined somewhere. Can you share how it's defined?

**Comment by rxu** [comment]
Sure. It's here https://github.com/phpbb/phpbb/blob/1096b094cb54043c682e85dd8e34daa4e98f9891/phpBB/phpbb/template/twig/extension.php#L111

**Comment by marc1706** [comment]
@stof I've added sample code to the issue above which also includes a working sample and the differences between 3.14 and 3.15.

**Comment by ericmorand** [comment]
> Please provide the full stack trace, including the previous exception (which has a more useful location to debug this issue). The `precedence_change` is meant to be optional in the config of operators (and most core operators don't provide one).

According to this part of the code, it is not optional:

https://github.com/twigphp/Twig/blob/c7be3889392cf49482c301b593f07abadff42c11/src/ExpressionParser.php#L152

**Comment by fabpot** [comment]
See #4519
