### ISSUE TITLE
MacroNode `$name` argument overriden in constructor loop ?

### ISSUE THREAD

**Issue by smnandre** [twigphp/Twig#4515]
In [MacroNode](https://github.com/twigphp/Twig/blob/c1f7277b7b6dc66859686347d359229e9edd2be9/src/Node/MacroNode.php#L34-L57) constructor, the `$name` argument can be overridden by the last "key" of the `$argments` argument

```php
    //                                     🟢 
    public function __construct(string $name, Node $body, Node $arguments, int $lineno)
    {
         // ...

        if (!$arguments instanceof ArrayExpression) {
             // ...
            
            //                       🟢 
            foreach ($arguments as $name => $default) { 
                $args->addElement($default, new LocalVariable($name, $default->getTemplateLine()));
            }

            // ...
        }

        // ...
        //                                                                            🟢 
        parent::__construct(['body' => $body, 'arguments' => $arguments], ['name' => $name], $lineno);
    }
```

https://github.com/twigphp/Twig/blob/c1f7277b7b6dc66859686347d359229e9edd2be9/src/Node/MacroNode.php#L34-L57

Not sure if this has any real occurence / consequence... if no sorry for the waste of time 🤷

**Comment by fabpot** [comment]
I think you're right, let's fix it by using `$n` in the loop. I suppose we didn't notice because this condition is always false for 99% of the users.
