### ISSUE TITLE
New Twig playground doesn't handle some non-latin characters

### ISSUE THREAD

**Issue by alexchexes** [twigphp/Twig#4520]
I am not sure if this is the right place to report this, but I couldn't find a repository for the new playground at https://github.com/orgs/symfony/repositories, so I’m posting it here to bring it to your attention:

When inserting certain non-Latin characters, for example, the Russian letter `Й`, into any part of the new Twig playground (https://twig.symfony.com/play), it breaks — no output is displayed. The output reappears if such characters are removed.  

Video:

https://github.com/user-attachments/assets/496f8c34-6362-4ee5-a5c7-4b56cf623b7b

**Comment by fabpot** [comment]
Good catch, this has been fixed and deployed now.
