### ISSUE TITLE
Twig and magic __get

### ISSUE THREAD

**Issue by tiois** [twigphp/Twig#601]
I got a BaseEntity class that implements the __call() and __get() functions. In my Twig template, I call entity.name (name doesn't exists in my entity class). The __get() method never gets called by Twig because of this line :

``` php
// Template.php line 381
if (isset($object->$item) || array_key_exists($item, $object)) {
```

isset function returns false, while echo($object->$item) returns the appropriate value.

And because of this line :

``` php
// Template.php line 406
} elseif (isset(self::$cache[$class]['methods']['__call'])) {
```

Twig is trying to call $entity->$property() instead of $entity->$property, which is wrong.

Why is __call magic function supported but not __get ?

**Comment by lifewcody** [comment]
After 12 years, we ran into this issue. Thank you for providing a resolution 💯

**Comment by cmedi32** [comment]
Same here, 2024, ran into this issue. 

But it does not seem to appear all the time, sometimes just implementing the __get method is enough. In my case, the issue came up after extending the class.

**Comment by fnagel** [comment]
Link above is dead, here's current one: https://twig.symfony.com/doc/recipes.html#using-dynamic-object-properties
