### ISSUE TITLE
Partials / Inherited blocks suggestion

### ISSUE THREAD

**Issue by jhogendorn** [twigphp/Twig#644]
It would be good if I could include a template, and allow that template to extend upon blocks in the file doing the include. As far as I can make out, there's no real way to do this between import, use, and include.

ie:

```
{# parent.twig #}
    {% block javascript %}
    {% endblock %}


{# child.twig #}
    {% extends 'parent.twig' %}
    {% block javascript %}
        {{ parent() }}
    {% endblock %}
    {% include subtemplate with subtemplatedata %}

{# subtemplate.twig #}
    {% block javascript %}
        {{ parent() }} {# ie, this code should appear in child.twigs javascript block #}
        alert('some subtemplate specific javascript');
    {% endblock %}
```

**Comment by fulopattila122** [comment]
OK understood. Considering this, how would you resolve the following problem?
- You have a `layout.html.twig`
- It contains a block `javascripts`
- jquery gets included within the block `javascripts` in file `layout.html.twig` before the closing `</body>` tag
- There is a functionality I'm using in a single subtemplate the requires jquery to have `$(document).ready(...)`
- If I simply put this in the template, then it precedes jquery -> won't work.
- I would be appending this script to the end of the `javascript` block (or anywhere else but *after* including jquery)

What is the suggested way of doing such thing?
