### ISSUE TITLE
Child template's macro imports don't override those of parent

### ISSUE THREAD

**Issue by jmikola** [twigphp/Twig#651]
Let's say I have the following macro templates:

``` jinja
{# filename:childMacros.html.twig #}

{% macro foo() %}
    FOO
{% endmacro %}
```

``` jinja
{# filename: parentMacros.html.twig #}

{% macro bar() %}
    BAR
{% endmacro %}
```

I also have a child template that extends a parent:

``` jinja
{# filename: child.html.twig #}
{% extends "parent.html.twig" %}
{% import "childMacros.html.twig" as macro %}

{% block content %}
    {{ macro.foo() }}
{% endblock %}
```

``` jinja
{# filename: parent.html.twig #}
{% import "parentMacros.html.twig" as macro %}

{% block content %}
    {{ macro.bar() }}
{% endblock %}
```

When rendering the child, I receive a Twig_Error_Runtime exception stating:

> Method "foo" for object "__TwigTemplate_c5f32e3601a3106fa6a99f6f8f2a9008" does not exist in "child.html.twig" at line 6

Peeking into the cached template, it appears that it actually contains the compiled code for `parentMacros.html.twig`. It seems like the parent's import statement and alias is preventing the child's import from functioning. I don't believe this behavior is documented, but is it intentional?

**Comment by fabpot** [comment]
As of #3012, you get a slightly better error message: `Variable "bar_macros" does not exist in "index" at line 6`.

**Comment by fabpot** [comment]
As of #3012, you get `FOO` as output, which is "logical" (macros are imported for the local template). so, I'm closing here as the "bug" seems to be fixed.
