### ISSUE TITLE
Break a for loop?

### ISSUE THREAD

**Issue by dnizetic** [twigphp/Twig#654]
Hi,

is it possible to break a loop?

I googled and searched it here, but it seems like this isn't supported in Twig.

So I was wandering - how come it's left out?

**Comment by ernestob** [comment]
how dum is that ... a break should be included
who cares about the loop.index

#fails

```
{% set my_array = ['a', 'b', 'c', 'b'] %}
{% set counter = 0 %}
{% for element in my_array %}
    {% if element == 'b' %}
        {% set index = counter %}
        {% break %}
    {% endif %}
    {% set counter = counter + 1 %}
{% endfor %}
```

#workaround

```
{% set counter = 0 %}
{% set found = false %}
{% set my_array = ['a', 'b', 'c', 'b'] %}
{% for element in my_array %}
    {% if element == 'b' %}
        {% if not found %}
            {% set index = counter %}
            {% set found = true %}
        {% endif %}
    {% endif %}
    {% set counter = counter + 1 %}
{% endfor %}
```

Holly

**Comment by ndusan** [comment]
I just had to do something similar and I think it could be interesting for the others.
If we take the case where u should stop looping after X, u can do it so:

{% set cnt = 10 }
{% for el in collection if cnt > 0 %}
{% set cnt = cnt - 1 %}

{# do something #}

{% endfor %}

Maybe this will help someone :)

**Comment by ArlingtonHouse** [comment]
Breaking a loop is not business logic at all, it is display logic that belongs in twig at the view layer.   How many items in a specific array do I want to display on this page?  UPDATE: the way to accomplish this is using the Twig filter "slice" to cut down your array in the template .

**Comment by Maxooo** [comment]
7 years later, the need is still here... 🙈

**Comment by sarath49** [comment]
still in need and not implemented 
I see one craft3 implementation for twig, can it be extended/implemented.
https://github.com/marionnewlevant/craft-mnbreakandcontinue

**Comment by sfaragy** [comment]
{% for x in allx %}
//statements
//conditions
 {% set break = true %}
{% endfor %}

**Comment by bajahranks** [comment]
It's amazing that years later and still nothing has been done. Just incredible. If "break" is business logic then "for and if" statements are business logic as well. SMH.

**Comment by fabpot** [comment]
What’s incredible is that nobody took the time to submit a PR in 7 years. Closing now. If someone wants to work on it, feel free too open a PR.

**Comment by btinet** [comment]
Hi Folks,

you can achieve a break in a for loop like following:

```
# /src/Twig/Extension/FunctionExtension.php
<?php

namespace YourApp\Twig\Extension;

class FunctionExtension extends \Twig\Extension\AbstractExtension
{
    function getTokenParsers() {
        return array(
            new BreakToken(),
        );
    }
    public function getName()
    {
        return FunctionExtension::t('Vapita For-Loop-Break Tag');
    }
}
```

```
# /src/Twig/Extension/BreakToken.php
<?php

namespace YourApp\Twig\Extension;

use Twig\Error\SyntaxError;
use Twig\Token;
use Twig\TokenParser\AbstractTokenParser;

class BreakToken extends AbstractTokenParser
{
    public function parse(Token $token)
    {
        $lineno = $token->getLine();
        $stream = $this->parser->getStream();

        $stream->expect(Token::BLOCK_END_TYPE);

        return new BreakNode(array(), array(), $lineno, $this->getTag());
    }
    public function getTag()
    {
        return 'break';
    }
}
```

```
# /src/Twig/Extension/BreakNode.php
<?php

namespace YourApp\Twig\Extension;

use Twig\Compiler;
use Twig\Node\Node;

class BreakNode extends Node
{
    public function compile(Compiler $compiler)
    {
        $compiler->addDebugInfo($this);

        $compiler->write("break;\n");
    }
}
```

Then you can use the `{% break %}`-tag in your loop.

```
{% for x in y %}
    {% if x is true %}
        {% break %}
    {% endif %}
{% endfor %}
```

p.s.: it does not check whether the break tag is inside a for-loop or not.

kind regards,

Ben

**Comment by SpacePossum** [comment]
you might be better off using my PR as it deals with more case, just not all possible ones... maybe someone wants to pick it up?
