### ISSUE TITLE
expose api for rendering individual blocks

### ISSUE THREAD

**Issue by mathiasverraes** [twigphp/Twig#676]
This post http://www.richsage.co.uk/2011/12/16/rendering-emails-with-twig-in-symfony2/ shows an elegant method to make email templates that have a body and a subject block:

``` php
<?php
$subject = $myEmailTemplate->renderBlock('subject', $context);
$body = $myEmailTemplate->renderBlock('body', $context);
// ... use $subject and $body in an email
```

Unfortunately, Twig_Template::renderBlock(), hasBlock() getBlockNames() are marked internal, and the Twig_TemplateInterface doesn't have those methods. If the above example is considered a valid use case, the methods should be exposed. The methods then could also be added to Twig_Environment. 

If not, is there a better way to do something similar?

I'd be happy to provide a PR.

**Comment by sandermarechal** [comment]
Now that Twig 2.0 is in the works, will this be re-evaluated? Being able to render individual blocks from a template can be a very useful tool. Not just for rendering e-mails but also for writing extendable generic bundles.
