### ISSUE TITLE
Caching alternatives to filesystem

### ISSUE THREAD

**Issue by shabbyrobe** [twigphp/Twig#728]
It would be awesome to be able to substitute the filesystem for caching compiled templates for something else, like APC, Redis, Memcache, whatever. Currently the file caching seems fairly tightly woven into the `Twig_Environment` class. 

I've got a hacked up version that works for my needs - tens of thousands of compiled files are humming away in Redis, expiring quietly and purging nearly instantly - but that version would hardly be considered "core worthy".

I'm happy to work on a real patch if you'd be happy to consider it.

**Comment by dmhendricks** [comment]
> It's not about performance or sharding for me.

**Comment by warrickhill** [comment]
+1
Our use case for a redis cache is we are using read only docker containers, we literally can't write to filesystem cache, and some caching in redis is better than no caching

**Comment by fabpot** [comment]
@warrickhill You should probably generate the cache during the build phase. That's what I'm doing and it works perfectly fine.
