### ISSUE TITLE
Capitalize should not force lowercase on other characters.

### ISSUE THREAD

**Issue by reecefowell** [twigphp/Twig#764]
The nature of capitalize is to uppercase the first character, i don't feel however it should forcefully lowercase the remaining characters.

in php we would use ucfirst($foo) and if necessary, we want the rest lower, we would do ucfirst(strtolower($foo)).

Twig already has a lower filter, so we could do in twig, {{ foo | lower | capitalize }}. However, if we only want the first character affected without creating a custom twig filter, there seems to be no way to do that unless i am missing something. Presently the behaviour of | lower | capitalize is forced on you even if you only want the first character affected.

Suggest changing of the capitalise filter to only upper case first character and NOT lower the rest of the string, this can be done manually if needed.

Otherwise, a new filter is needed, ie; {{ foo | ucfirst }}.

**Comment by Boycce** [comment]
Omg. Why close... +1 for ucfirst

**Comment by npub** [comment]
The [u filter](https://twig.symfony.com/doc/3.x/filters/u.html) works fine:
`{{ 'foo bar' | u.title }} {* Foo bar *}`
