### ISSUE TITLE
Problem with numeric keys in array

### ISSUE THREAD

**Issue by billmn** [twigphp/Twig#766]
If I have an array like :

<pre>
["006"] =>  int(100)
[700]   =>  int(150)
["008"] =>  int(200)
["a"]   =>  int(300)
</pre>

I cannot retrieve the values from the keys that are numeric and starts with ZERO.

<pre>
{{ test['006'] }}    ---> null !!!!
{{ test['700'] }}    ---> 150
{{ test['a'] }}      ---> 300
</pre>

The problem is in the getAttribute() method in Twig_Template class when there's a INTEGER CAST

Class : Twig_Template

<pre>
protected function getAttribute($object, $item, array $arguments = array(), $type = Twig_TemplateInterface::ANY_CALL, $isDefinedTest = false, $ignoreStrictCheck = false)
   {
       $item = ctype_digit((string) $item) ? (int) $item : (string) $item;
...
</pre>

This is a bug or not?
And if not why exists this CAST?

**Comment by ogwugo** [comment]
it is a bug

**Comment by xabbuh** [comment]
Commenting on a closed issue that has been fixed in the past does not help. If you think there is still a bug, you should rather open a new issue with some steps describing the behaviour you experience an what you did expect instead.
