### ISSUE TITLE
default filter does not work on (bool) false in array

### ISSUE THREAD

**Issue by havvg** [twigphp/Twig#769]
The following behavior seems odd to me.
A value of an array should be checked for existence when using the default filter (the second dump).

``` jinja
{% set var = { 'foo': 0, 'bar': false } %}

{# expected 0, got 0 #}
{{ dump(var.foo|default(true)) }}

{# expected false, got true #}
{{ dump(var.bar|default(true)) }}

{# expected true, got true #}
{{ dump(var.baz|default(true)) }}
```

**Comment by cenobitedk** [comment]
You can use this workaround for this problem.

```twig
{# main.twig #}
{% set var = var ?? false %}

{% if var %}
    <span>I'm special!</span>
{% endif %}
```
```twig
{# child1.twig #}
{% extends "main.twig" %}
{% set var = true %}
```
```twig
{# child2.twig #}
{% extends "main.twig" %}
```

Here's an example: http://twigfiddle.com/ziwbxt
Select "Set as main template" for child2.twig as well and see the difference in the output on the right.

**Comment by gggeek** [comment]
One more vote for not triggering the 'default' filter on FALSE but only on NULL or UNDEF

**Comment by lyrixx** [comment]
may be we could add an option to the default filter
I already hit this behavior, and indeed this is not very convenient

**Comment by stof** [comment]
@gggeek but then, that would be exactly the `??` operator (but slower as it could not always be identified as such at compile time and be replaced by the `??` operator which compiles to faster code when it can use the PHP `??` operator)

**Comment by gggeek** [comment]
@stof "I'm never quite so stupid as when i'm being smart". Point taken.
Maybe it would be worth mentioning the '??' operator in the doc. page for 'default' ?

**Comment by Neirda24** [comment]
@gggeek , @stof:  👍 for adding it to the twig `default` page. As I stumbled upon this today as well and had to find this issue to find my answers.

**Comment by johnmarinelli** [comment]
this is _so_ counterintuitive and dumb
\- $0.02

**Comment by xabbuh** [comment]
I suggest to close here. The suggested change would be a BC break, there already is the `??` operator and noone seemed to be interested in updating the docs for the `defined` test.

**Comment by c33s** [comment]
should really be changed. just wasted time to debug. this is really counterintutive. php gets stricter and stricter and twig is doing the oposite
