### ISSUE TITLE
Consider auto-importing macros in the same file

### ISSUE THREAD

**Issue by schmittjoh** [twigphp/Twig#861]
I've always found it a bit weird that you cannot directly call macros defined in the same file.

Having to "import" something that is in the technically in the same file feels a bit weird (especially as you import on a per-file basis).

Can't we simply auto-import them? Obviously, if you define them in the same file, you probably want to use them there.

**Comment by chetzof** [comment]
Did the changes in #1215 mature enough? :)

**Comment by fabpot** [comment]
Implemented in #3019.
