### ISSUE TITLE
template_from_string bug with "use"

### ISSUE THREAD

**Issue by syrm** [twigphp/Twig#877]
{% use template_from_string("{% block body %}Go{% endblock %}") %}

Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'The template references in a "use" statement must be a string in "event:dynamic" at line 3.' in /_vendor/TwigLibrary/lib/Twig/TokenParser/Use.php:41 Stack trace: 
#0 /_vendor/TwigLibrary/lib/Twig/Parser.php(192): Twig_TokenParser_Use->parse(Object(Twig_Token))
#1 /_vendor/TwigLibrary/lib/Twig/Parser.php(100): Twig_Parser->subparse(NULL, false)

 #2 /_vendor/TwigLibrary/lib/Twig/Environment.php(486): Twig_Parser->parse(Object(Twig_TokenStream)) 
#3 /_vendor/TwigLibrary/lib/Twig/Environment.php(536): Twig_Environment->parse(Object(Twig_TokenStream))
#4 /_vendor/TwigLibrary/lib/Twig/Environment.php(330): Twig_Environment->compileSource('{% extends "lay...', 'event:dynamic') # in /_vendor/TwigLibrary/lib/Twig/TokenParser/Use.php on line 41

**Comment by 4d4ch4u32** [comment]
I'm using Twig 3.3 in Symfony 5.2.3, it's still not possible. :(
