### ISSUE TITLE
Named arguments for macros

### ISSUE THREAD

**Issue by hason** [twigphp/Twig#929]
```
--TEST--
macro
--TEMPLATE--
{% from _self import test %}

{% macro test(a, b = 'bar') -%}
{{ a }}{{ b }}
{%- endmacro %}

{{ test('foo') }}
{{ test('bar', 'foo') }}
{{ test(b = 'bar', a = 'foo') }}
--DATA--
return array();
--EXPECT--
foobar
barfoo
foobar
```

Twig_Error_Syntax: Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",") in "C:\public_html\Twig\test\Twig\Tests\Fixtures\macros\default_values.test" at line 10

**Comment by ninsuo** [comment]
@chetzof just discovered that named arguments are already implemented and do work very well.
http://twigfiddle.com/w1dwmd
Anyway, if you have lots and lots of arguments, the second solution I given looks cleaner.

**Comment by zimmermanj42** [comment]
@ninsuo Just to clarify, named arguments for calls to macros still are not implemented. The example you link to does not used named function in the calls. This would be a more proper example, and as you can see, it fails even with the latest Twig code at this time.
http://twigfiddle.com/w1dwmd/2

**Comment by ninsuo** [comment]
I do not understand the notation:

```jinja
{{ _self.test(1, b=42) }}
```

Do you want this to be read as "pass `42` to test and `set b = 42` ? 

IMHO, this would introduce some ugly practices in templates.

**Comment by zimmermanj42** [comment]
@ninsuo The modification I made wasn't intended to be a good use of the feature, but just to show that the feature being discussed here is still not implemented (as it throws the exception), as you had stated in an earlier comment that it was.  In hindsight I probably should have taken the time to build a more relevant example.  I came to this thread from a search and didn't want people to possibly be confused and thinking that this should be working for them.

In terms of the feature, in a way I can see it being more of something like "code smell", but I see no difference in been able to define arguments by name in the macro call or using the array of options methodology.  They essentially do the same thing.

However, I see named arguments as a better solution as enforcement of those arguments are defined in the macro definition and handled via the engine vs. needing to write more twig code in the macro to make sure things are set, defaulted, etc.

Despite this, I understand that supporting this is a much deeper issue with the code, so the array of options is an OK workaround until this may be able to be integrated into the software.

**Comment by alpacagh** [comment]
@ninsuo your link shows the "default values", not a "named arguments".
The notation `{{ _self.test(1, b=42) }}` is pretty common and is already implemented for functions filters and tests.

**Comment by jameswtc** [comment]
Hi, is the named argument for macro still not supported? 
I'm using "version": "v1.24.0",

**Comment by fabpot** [comment]
I've worked quite a bit on the macros lately and I don't think we will change the current implementation anytime soon. As I said in the first comment, the current infrastructure makes it impossible to implement this feature. So I'm going to close this issue as a "won't fix".

**Comment by hanoii** [comment]
old, but FWIW, you can achieve this easy with an optional object argument:

```twig
{% macro h2(title, options = {}) %}
  <h2 {{ options.attributes}} class="{{ options.classes }}" style="{{ options.title_color ? '--color: ' ~ options.title_color : '' }}">{{ title }}</h2>
{% endmacro h2 %}
```

And then

```twig
{{ h2('Title', {classes: 'bold italic etc'}) }}
```

**Comment by dunglas** [comment]
Now that PHP 8 supports named arguments natively, can't we add support for this in Twig (for users having PHP8+)?

**Comment by mmarton** [comment]
> Now that PHP 8 supports named arguments natively, can't we add support for this in Twig (for users having PHP8+)?

Also interested in this question. @fabpot ?

**Comment by stof** [comment]
@mmarton relying on PHP 8 named arguments to support named macro arguments would require that Twig requires PHP 8 (making the availability of a feature of the templating syntax depend on the PHP version on which the template is compiled makes it a pain to manage this availability). So that's not an option yet.

**Comment by 19h47** [comment]
Don't know if it's related, but this is what I like to do to mimic some named args with macro and default values:

```twig
{% macro button( args ) %}
	{% set args = { title: 'foo', classes: '', icon: 'arrow' } | merge( args ) %}

	<button type="button" class="{{ args.classes }}">
		{{- args.title -}}{{- icon( args.icon ) -}}
	</button>
{% endmacro %}
```

And then:
```twig
{{- _self.button( { title: 'bar', classes: 'baz', icon: 'chevron' } ) -}}
```
Hope it helps!

**Comment by iparr** [comment]
Building upon the excellent workof @19h47 and @ninsuo , you can:

```
{% macro button( args = {} ) %}
	{% set args = { title: 'foo', classes: '', icon: 'arrow' } | merge( args ) %}

	<button type="button" class="{{ args.classes }}">
		{{- args.title -}}{{- icon( args.icon ) -}}
	</button>
{% endmacro %}
```

I use `args` as storage for optional options and with this (note the `args = {}`) they become truly 'optional'.

I use this for setting sensible defaults for every macro (@hanoii touches upon this, but I personally prefer the other approaches where you store all the defaults at the top of the macro, rather than inline).
